### ISSUE TITLE
All commits fail with the following error: All checks have failed

### ISSUE THREAD

**Issue by thecesrom** [Homebrew/homebrew-cask#101309]
The last PR that was merged and successfully passed all CI checks is #100748, back in March 5, ever since all commits have failed with the following message:

```
All checks have failed
3 failing checks
@github-actions
Sync templates and CI config. / sync-templates-and-ci-config (Homebrew/homebrew-cask-drivers) (push) — sync-templates-and-ci-config (Homebrew/homebrew-cask-drivers)
Details
@github-actions
Sync templates and CI config. / sync-templates-and-ci-config (Homebrew/homebrew-cask-fonts) (push) — sync-templates-and-ci-config (Homebrew/homebrew-cask-fonts)
Details
@github-actions
Sync templates and CI config. / sync-templates-and-ci-config (Homebrew/homebrew-cask-versions) (push) — sync-templates-and-ci-config (Homebrew/homebrew-cask-versions)
Details
```

Failing workflow: [Sync templates and CI config.](https://github.com/Homebrew/homebrew-cask/blob/master/.github/workflows/sync-templates-and-ci-config.yml)

```
Run ./.github/actions/sync/templates.rb 'vendor/Homebrew/homebrew-cask-drivers' 'Homebrew/homebrew-cask-drivers' 'sync-templates-and-ci-config'
/var/lib/gems/2.7.0/gems/fileutils-1.5.0/lib/fileutils.rb:1466:in `unlink': No such file or directory @ apply2files - vendor/Homebrew/homebrew-cask-drivers/.github/ISSUE_TEMPLATE/02_feature_request.md (Errno::ENOENT)
Detecting changes…
	from /var/lib/gems/2.7.0/gems/fileutils-1.5.0/lib/fileutils.rb:1466:in `block in remove_file'
	from /var/lib/gems/2.7.0/gems/fileutils-1.5.0/lib/fileutils.rb:1471:in `platform_support'
	from /var/lib/gems/2.7.0/gems/fileutils-1.5.0/lib/fileutils.rb:1465:in `remove_file'
	from /var/lib/gems/2.7.0/gems/fileutils-1.5.0/lib/fileutils.rb:798:in `remove_file'
	from /var/lib/gems/2.7.0/gems/fileutils-1.5.0/lib/fileutils.rb:585:in `block in rm'
	from /var/lib/gems/2.7.0/gems/fileutils-1.5.0/lib/fileutils.rb:584:in `each'
	from /var/lib/gems/2.7.0/gems/fileutils-1.5.0/lib/fileutils.rb:584:in `rm'
	from ./.github/actions/sync/templates.rb:41:in `<main>'
Error: Process completed with exit code 1.
```

This is the info for the PR and commit where this behavior has been initially detected.

PR: https://github.com/Homebrew/homebrew-cask/pull/100765
Commit: https://github.com/Homebrew/homebrew-cask/commit/cb2178b3c4023079095621a1d84245d450bf3d77

**Comment by reitermarkus** [comment]
Should be fixed now.
