### ISSUE TITLE
Error: Cask 'java' is unreadable: undefined method `undent' for #<String: xxx>

### ISSUE THREAD

**Issue by physixfan** [Homebrew/homebrew-cask#109452]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

When i run `brew doctor` or `brew upgrade`, I see this error in title.

This issue is the same as this one: https://github.com/Homebrew/homebrew-cask/issues/90904 

However, when I try to use the solution provided `brew uninstall --force java`, I also see this error. So I can't continue. What should i do?

### Command that failed

brew doctor

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

(base) xfan@physixfansmbp15 ~ % brew doctor --verbose --debug
Error: Cask 'java' is unreadable: undefined method `undent' for #<String:0x00007ffb9fae2f98>
Did you mean?  undef
               indent
               indent!
/usr/local/Caskroom/java/.metadata/1.8.0_131-b11,d54c1d3a095b4ff2b6607d096fa80163/20170507211831.290/Casks/java.rb:82:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:61:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:61:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:48:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:87:in `cask'
/usr/local/Caskroom/java/.metadata/1.8.0_131-b11,d54c1d3a095b4ff2b6607d096fa80163/20170507211831.290/Casks/java.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:45:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:51:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:131:in `<main>'

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

(base) xfan@physixfansmbp15 ~ % brew doctor --verbose
Error: Cask 'java' is unreadable: undefined method `undent' for #<String:0x00007fcb498abcb0>
Did you mean?  undef
               indent
               indent!

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

(base) xfan@physixfansmbp15 ~ % brew tap
heroku/brew
homebrew/cask
homebrew/core
homebrew/services

</code></pre></details>

**Comment by physixfan** [comment]
Never mind, I found the solution on this page is useful and the problem is solved: https://www.gowhich.com/blog/1082
