### ISSUE TITLE
Error: Cask 'inkscape' definition is invalid: invalid depends_on key: ':x11'

### ISSUE THREAD

**Issue by hktalent** [Homebrew/homebrew-cask#112838]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

```
$ brew remove inkscape
Error: Cask 'inkscape' definition is invalid: invalid depends_on key: ':x11'

$ brew doctor
Warning: Unexpected method 'license' called on Cask angry-ip-scanner.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'inkscape' definition is invalid: invalid depends_on key: ':x11'
```

### Command that failed

brew remove inkscape

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

```
$ brew remove inkscape --verbose --debug
Error: Cask 'inkscape' definition is invalid: invalid depends_on key: ':x11'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:241:in `rescue in depends_on'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:238:in `depends_on'
/usr/local/Caskroom/inkscape/.metadata/0.92.2-1,11269/20180615095821.733/Casks/inkscape.rb:9:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:63:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:63:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:50:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:87:in `cask'
/usr/local/Caskroom/inkscape/.metadata/0.92.2-1,11269/20180615095821.733/Casks/inkscape.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `load'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:143:in `load_formula_or_cask'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:59:in `block in to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:58:in `each'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:58:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:58:in `to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:273:in `to_kegs_to_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:48:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'


```

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

$ brew doctor --verbose --debug
Warning: Unexpected method 'license' called on Cask angry-ip-scanner.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'inkscape' definition is invalid: invalid depends_on key: ':x11'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:241:in `rescue in depends_on'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:238:in `depends_on'
/usr/local/Caskroom/inkscape/.metadata/0.92.2-1,11269/20180615095821.733/Casks/inkscape.rb:9:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:63:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:63:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:50:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:87:in `cask'
/usr/local/Caskroom/inkscape/.metadata/0.92.2-1,11269/20180615095821.733/Casks/inkscape.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:45:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:51:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

$brew tap
homebrew/core

</code></pre></details>

**Comment by hktalent** [comment]
@miccal 
```
$ brew uninstall --force angry-ip-scanner
Warning: Unexpected method 'license' called on Cask angry-ip-scanner.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Warning: Unexpected method 'license' called on Cask angry-ip-scanner.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'jad' is unreadable: undefined method `undent' for #<String:0x00007f99f8a25320>
Did you mean?  undef
               indent
               indent!
```

**Comment by hktalent** [comment]
```
$ cd  "$(brew --prefix)/Caskroom/"   

$  rm -rf *

now 
$  brew doctor

is Ok

```
thanks @miccal @carlocab
