### ISSUE TITLE
Snowflake-snowsql doesn't work!

### ISSUE THREAD

**Issue by yuhaodai** [Homebrew/homebrew-cask#118828]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

formulae url: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/snowflake-snowsql.rb

I tried to use this command both on wsl but it did not work.

on wsl it shows "No Cask with this name exists"

It worked on my MacOS, so I thought it's either my network's problem (company VPN) or brew's problem.

Please provide any guidance : )

### Command that failed

brew install --cask snowflake-snowsql

### Output of command with `--verbose --debug`

```shell
brew install --cask snowflake-snowsql --verbose --debug
Running `brew update --preinstall`...
Error: Cask 'snowflake-snowsql' is unavailable: No Cask with this name exists.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cask/cask_loader.rb:196:in `load'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `load'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:142:in `load_formula_or_cask'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:59:in `block in to_formulae_and_casks'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:58:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:58:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:58:in `to_formulae_and_casks'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:170:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
brew doctor --verbose
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/y2d/miniconda3/bin/icu-config
  /home/y2d/miniconda3/bin/ncursesw6-config
  /home/y2d/miniconda3/bin/python3-config
  /home/y2d/miniconda3/bin/python3.9-config
  /home/y2d/miniconda3/bin/xml2-config

Warning: /usr/bin occurs before /home/linuxbrew/.linuxbrew/bin in your PATH.
This means that system-provided programs will be used instead of those
provided by Homebrew. Consider setting your PATH so that
/home/linuxbrew/.linuxbrew/bin occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >> ~/.profile

The following tools exist at both paths:
  addr2line
  ar
  as
  bunzip2
  bzcat
  bzcmp
  bzdiff
  bzegrep
  bzfgrep
  bzgrep
  bzip2
  bzip2recover
  bzless
  bzmore
  c++filt
  captoinfo
  choom
  chrt
  clear
  col
  colcrt
  colrm
  column
  curl
  c_rehash
  dmesg
  dwp
  eject
  elfedit
  envsubst
  fallocate
  fincore
  findmnt
  flock
  getopt
  gettext
  gettext.sh
  git
  git-receive-pack
  git-shell
  git-upload-archive
  git-upload-pack
  gold
  gprof
  hexdump
  i386
  infocmp
  infotocap
  ionice
  ipcmk
  ipcrm
  ipcs
  last
  lastb
  ld
  ld.bfd
  ld.gold
  linux32
  linux64
  logger
  look
  lsblk
  lscpu
  lsipc
  lslocks
  lslogins
  lsmem
  lsns
  lzcat
  lzcmp
  lzdiff
  lzegrep
  lzfgrep
  lzgrep
  lzless
  lzma
  lzmainfo
  lzmore
  mcookie
  mesg
  more
  mount
  mountpoint
  namei
  ngettext
  nm
  nsenter
  objcopy
  objdump
  openssl
  prlimit
  ranlib
  readelf
  renice
  reset
  rev
  script
  scriptreplay
  setarch
  setsid
  setterm
  size
  strings
  strip
  tabs
  taskset
  tic
  toe
  tput
  tset
  ul
  umount
  unlzma
  unshare
  unxz
  utmpdump
  uuidgen
  uuidparse
  wall
  wdctl
  whereis
  x86_64
  xz
  xzcat
  xzcmp
  xzdiff
  xzegrep
  xzfgrep
  xzgrep
  xzless
  xzmore

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /home/linuxbrew/.linuxbrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/home/linuxbrew/.linuxbrew/sbin:$PATH"' >> ~/.profile
```

### Output of `brew tap`

```shell
homebrew/core
```

**Comment by bevanjkay** [comment]
The `homebrew-cask` tap is currently untapped on your install.
Running the command `brew tap homebrew/cask` should fix the issue.

**Comment by carlocab** [comment]
Casks are macOS-only; sorry.

IIRC that should be the error message you see whenever you try to do `brew install --cask` on Linux. Not sure why that's not what you see here.
