### ISSUE TITLE
Uninstall adobe-creative-cloud "Error: Operation not permitted"

### ISSUE THREAD

**Issue by wingsofovnia** [Homebrew/homebrew-cask#119528]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Trying to uninstall adobe-creative-cloud cask but it fails at Removing files task.

It's similar to https://github.com/Homebrew/homebrew-cask/issues/70511 but an error is slightly different. It was suggested to grant FDA to Terminal but it didn't help. Neither helped granting FDA to `ruby`, `bash`, `zsh` and `brew`.

Current OS version: Monterey but I had the same failure on previous versions.

### Command that failed

`brew remove --cask adobe-creative-cloud`

### Output of command with `--verbose --debug`

```shell
❯ brew remove --cask adobe-creative-cloud --verbose --debug
#/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading... (skipped)
==> Uninstalling Cask adobe-creative-cloud
==> Uninstalling Cask adobe-creative-cloud
==> Uninstalling artifacts
==> 5 artifacts defined
#<SortedSet: {#<Cask::Artifact::Preflig...(skipped)
==> Uninstalling artifact of class Cask::Artifact::PreflightBlock
==> Changing ownership of paths required by adobe-creative-cloud; your password may be necessary.
/usr/bin/sudo -E -- /usr/sbin/chown -R -- iovchynnikov:staff /Library/Application\ Support/Adobe
==> Uninstalling artifact of class Cask::Artifact::Uninstall
==> Running uninstall script /usr/bin/pluginkit
/usr/bin/pluginkit -r /Applications/Utilities/Adobe\ Sync/CoreSync/Core\ Sync.app/Contents/PlugIns/ACCFinderSync.appex
==> Removing launchctl service Adobe_Genuine_Software_Integrity_Service
/bin/launchctl list Adobe_Genuine_Software_Integrity_Service
/usr/bin/sudo -E -- /bin/launchctl list Adobe_Genuine_Software_Integrity_Service
==> Removing launchctl service com.adobe.AdobeCreativeCloud
/bin/launchctl list com.adobe.AdobeCreativeCloud
/usr/bin/sudo -E -- /bin/launchctl list com.adobe.AdobeCreativeCloud
==> Removing launchctl service com.adobe.acc.installer
/bin/launchctl list com.adobe.acc.installer
/usr/bin/sudo -E -- /bin/launchctl list com.adobe.acc.installer
==> Removing launchctl service com.adobe.acc.installer.v2
/bin/launchctl list com.adobe.acc.installer.v2
/usr/bin/sudo -E -- /bin/launchctl list com.adobe.acc.installer.v2
==> Removing launchctl service com.adobe.ccxprocess
/bin/launchctl list com.adobe.ccxprocess
/usr/bin/sudo -E -- /bin/launchctl list com.adobe.ccxprocess
osascript -l JavaScript -e \'use\ strict\'\;'
''
'ObjC.import\(\'stdlib\'\)'
''
'function\ run\(argv\)\ \{'
'\ \ try\ \{'
'\ \ \ \ var\ app\ =\ Application\(argv\[0\]\)'
'\ \ \ \ if\ \(app.running\(\)\)\ \{'
'\ \ \ \ \ \ \$.exit\(0\)'
'\ \ \ \ \}'
'\ \ \}\ catch\ \(err\)\ \{\ \}'
''
'\ \ \$.exit\(1\)'
'\}'
' com.adobe.acc.AdobeCreativeCloud
==> Signalling 'QUIT' to application ID 'com.adobe.accmac'
/bin/launchctl list
==> Running uninstall script /usr/bin/pkill
/usr/bin/pkill Adobe\ Desktop\ Service AdobeIPCBroker AdobeCRDaemon
==> Removing files:
/Applications/Adobe Creative Cloud/*Adobe Creative Cloud
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Applications/Adobe Creative Cloud/Icon?
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Applications/Adobe Creative Cloud/.Uninstall*
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Applications/Utilities/Adobe Creative Cloud*
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Applications/Utilities/Adobe Application Manager
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Applications/Utilities/Adobe Sync
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Applications/Utilities/Adobe Installers/Uninstall Adobe Creative Cloud
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Applications/Utilities/Adobe Installers/.Uninstall*
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Application Support/Adobe/CEP/extensions/CC_*
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Application Support/Adobe/CEP/extensions/com.adobe.ccx.*
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Application Support/Adobe/Adobe Desktop Common
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Application Support/Adobe/AdobeApplicationManager
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Application Support/Adobe/AdobeGC*
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Application Support/Adobe/*[Ii]nstall*
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Application Support/Adobe/ADCRefs
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Application Support/Adobe/caps
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Application Support/Adobe/OOBE
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Application Support/Adobe/PCF
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Application Support/Adobe/SL*
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Application Support/Adobe/Vulcan
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Application Support/regid.*.com.adobe
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
~/Library/Application Support/Adobe/AAMUpdater
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
~/Library/Application Support/Adobe/ExtensibilityLibrary
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
~/Library/Application Support/Adobe/FloodGate
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
~/Library/Application Support/Adobe/.adobelicnotification
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
~/Library/Application Support/CrashReporter/AdobeCRDaemon_*.plist
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
~/Library/Application Scripts/com.adobe.accmac.ACCFinderSync
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
~/Library/*/Adobe/CoreSync
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/*/com.adobe.acc*
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
Error: Operation not permitted - /Users/iovchynnikov/Library/com.apple.internal.ck
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:343:in `glob'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:343:in `glob'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:343:in `block in each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:327:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:327:in `each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:357:in `uninstall_delete'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:76:in `dispatch_uninstall_directive'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:15:in `block in uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:14:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:447:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:444:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:393:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:51:in `block in uninstall_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:39:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:39:in `uninstall_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:70:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
❯ brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
#/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/...(skipped)
==> Homebrew Version
3.3.16-15-g6661f5b
==> macOS
12.3
==> SIP
Enabled
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3965 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (212 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (206 casks)
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase
  lua@5.1
  php@7.4

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gnupg
```

### Output of `brew tap`

```shell
❯ brew tap
acrogenesis/macchanger
b-ramsey/kali
beeftornado/rmtree
ethereum/ethereum
homebrew/aliases
homebrew/cask
homebrew/cask-drivers
homebrew/cask-versions
homebrew/core
homebrew/services
vapor/tap
web3j/web3j
```

**Comment by miccal** [comment]
I cannot reproduce this, and I suspect that the issue may be because you are using a Beta version of macOS, which we do not support:
```
==> macOS
12.3
```
On my machine:
```
==> macOS
12.2.1
```
and the `uninstall` works fine.
