### ISSUE TITLE
yandex failed to build on Mac OS Monterey Intel Macbook

### ISSUE THREAD

**Issue by jmcca11um** [Homebrew/homebrew-cask#122442]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

I have an older Macbook (not M1!) and I've just done a clean install of Monterey last week
I have installed Brave  & Chrome browsers yesterday without any issues.
Today tried installing Yandex and it doesn't work, it fails at the end - this is the output:

"
brew install --cask yandex
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 26 formulae.
==> Updated Casks
Updated 1 cask.

==> Downloading https://browser.yandex.ru/download/?os=mac&full=1
==> Downloading from https://ext-cachev2-cogent02.cdn.yandex.net/download.cdn.ya
######################################################################## 100.0%
Warning: No checksum defined for cask 'yandex', skipping verification.
==> Installing Cask yandex
==> Purging files for version 22.1.0 of Cask yandex
Error: It seems the App source '/usr/local/Caskroom/yandex/22.1.0/Yandex.app' is not there.
"

### Command that failed

brew install --cask yandex

### Output of command with `--verbose --debug`

```shell
❯ brew install --cask yandex --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://browser.yandex.ru/download/?os=mac&full=1
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.4.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.3.1\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://browser.yandex.ru/download/\?os=mac\&full=1
Already downloaded: /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe
==> Checking quarantine support
/usr/bin/xattr -h
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe
/usr/bin/xattr -p com.apple.quarantine /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe
==> /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe is quarantined
Warning: No checksum defined for cask 'yandex', skipping verification.
hdiutil imageinfo -format /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe
file -b /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe
==> Installing Cask yandex
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Executable for /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe
cp -p /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe /usr/local/Caskroom/yandex/22.1.0/Yandex.exe
==> Verifying Gatekeeper status of /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe
/usr/bin/xattr -p com.apple.quarantine /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe
==> /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe is quarantined
==> Propagating quarantine from /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe to /usr/local/Caskroom/yandex/22.1.0
/usr/bin/xattr -p com.apple.quarantine /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;62653297\;Homebrew\\x20Cask\;F171DAF7-587F-401E-B00C-8BBF26AC09E2
==> Creating metadata directory: /usr/local/Caskroom/yandex/.metadata/22.1.0/20220424112118.034
==> Creating metadata subdirectory: /usr/local/Caskroom/yandex/.metadata/22.1.0/20220424112118.034/Casks
==> Installing artifacts
==> 1 artifact defined
#<SortedSet: {#<Cask::Artifact::App:0x00007fe632ac0d08 @cask=#<Cask::Cask:0x00007fe632a44758 @token="yandex", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/yandex.rb>, @source="cask \"yandex\" do\n  arch = Hardware::CPU.intel? ? \"\" : \"&arch=arm64\"\n\n  version \"22.1.0\"\n  sha256 :no_check\n\n  url \"https://browser.yandex.ru/download/?os=mac\#{arch}&full=1\"\n  name \"Yandex.Browser\"\n  desc \"Web browser\"\n  homepage \"https://browser.yandex.ru/\"\n\n  livecheck do\n    url :url\n    strategy :header_match do |headers|\n      match = headers[\"location\"].match(/(\\d+)_(\\d+)_(\\d+)/i)\n      next if match.blank?\n\n      \"\#{match[1]}.\#{match[2]}.\#{match[3]}\"\n    end\n  end\n\n  auto_updates true\n\n  app \"Yandex.app\"\nend\n", @tap=#<Tap:0x00007fe632a2ec00 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fe632a446b8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/yandex.rb:1>, @default_config=#<Cask::Config:0x00007fe632a42070 @explicit={}, @env={}, @default={:languages=>["en-GB"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/jmcc/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/jmcc/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/jmcc/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/jmcc/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/jmcc/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/jmcc/Library/Fonts>, :servicedir=>#<Pathname:/Users/jmcc/Library/Services>, :input_methoddir=>#<Pathname:/Users/jmcc/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/jmcc/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/jmcc/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/jmcc/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/jmcc/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/jmcc/Library/Screen Savers>}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/yandex>, @metadata_main_container_path=#<Pathname:/usr/local/Caskroom/yandex/.metadata>, @config=#<Cask::Config:0x00007fe632ac25b8 @explicit={}, @env={}, @default={:languages=>["en-GB"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/jmcc/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/jmcc/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/jmcc/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/jmcc/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/jmcc/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/jmcc/Library/Fonts>, :servicedir=>#<Pathname:/Users/jmcc/Library/Services>, :input_methoddir=>#<Pathname:/Users/jmcc/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/jmcc/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/jmcc/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/jmcc/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/jmcc/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/jmcc/Library/Screen Savers>}>, @dsl=#<Cask::DSL:0x00007fe632ac21f8 @cask=#<Cask::Cask:0x00007fe632a44758 ...>, @token="yandex", @version="22.1.0", @sha256=:no_check, @url=#<URL::DSL:0x00007fe632ac1820 @uri=#<URI::HTTPS https://browser.yandex.ru/download/?os=mac&full=1>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}>, @name=["Yandex.Browser"], @desc="Web browser", @homepage="https://browser.yandex.ru/", @livecheck=#<Livecheck:0x00007fe632ac11e0 @formula_or_cask=#<Cask::DSL:0x00007fe632ac21f8 ...>, @referenced_cask_name=nil, @referenced_formula_name=nil, @regex=nil, @skip=false, @skip_msg=nil, @strategy=:header_match, @url=:url, @strategy_block=#<Proc:0x00007fe632ac10c8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/yandex.rb:14>>, @livecheckable=true, @auto_updates=true, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/yandex/22.1.0>, @language_eval=nil>>, @source_string="Yandex.app", @target_string="", @source=#<Pathname:/usr/local/Caskroom/yandex/22.1.0/Yandex.app>, @target=#<Pathname:/Applications/Yandex.app>>}>
==> Installing artifact of class Cask::Artifact::App
==> Purging files for version 22.1.0 of Cask yandex
Error: It seems the App source '/usr/local/Caskroom/yandex/22.1.0/Yandex.app' is not there.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:48:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:20:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:242:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:235:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:117:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:77:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:77:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:179:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
❯ brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/warning-1.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tapioca-0.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/yard-sorbet-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/yard-0.9.27/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/spoom-1.1.11/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-0.5.9889/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-static-0.5.9889-universal-darwin-14/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-cobertura-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.21.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.12.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.6.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.14.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.13.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-1.27.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-ast-1.17.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec_junit_formatter-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-sorbet-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-github-2.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.11.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/rdiscount-2.2.0.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rbi-0.0.14/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unparser-0.6.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/pry-0.14.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parlour-6.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-0.5.9889/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-3.1.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-3.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.22.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/method_source-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.8.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrick-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubyntlm-0.6.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.13.4-x86_64-darwin/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/racc-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/racc-1.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-4.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2022.0105/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json_schemer-0.2.20/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/uri_template-0.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hana-1.3.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ecma-re-validator-0.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/regexp_parser-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/unf_ext-0.0.8.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/did_you_mean-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/commander-4.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/highline-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coderay-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/byebug-11.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/byebug-11.1.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bootsnap-1.11.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/bootsnap-1.11.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/msgpack-1.4.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/msgpack-1.4.5
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.10/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/addressable-2.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/public_suffix-4.0.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.15.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin21
/Library/Ruby/Site/2.6.0/universal-darwin21
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin21
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin21
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin21
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
3.4.7
==> macOS
12.3.1
==> SIP
Enabled
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4002 casks)
Your system is ready to brew.
```

### Output of `brew tap`

```shell
❯ brew tap
homebrew/cask
homebrew/core
```

**Comment by cho-m** [comment]
Odd. Yandex redirected you to Windows exe: 
```
==> Downloading https://browser.yandex.ru/download/?os=mac&full=1
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.4.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.3.1\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://browser.yandex.ru/download/\?os=mac\&full=1
Already downloaded: /Users/jmcc/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.exe
```

The final installation ends up being:
```
/usr/local/Caskroom/yandex/22.1.0/Yandex.exe
```

Yandex may have changed their download URLs or added some cookies/etc.

**Comment by n1kutochkin** [comment]
I've got same issue – Brew downloaded Windows binary of browser

**Comment by bevanjkay** [comment]
@n1kutochkin Can you please try again after running `brew update`? https://github.com/Homebrew/homebrew-cask/pull/122798 May have fixed the issue.

**Comment by miccal** [comment]
From what I can see this has now been resolved:
```
|-> brew fetch yandex
==> Downloading https://browser.yandex.ru/download/?os=mac&full=1
==> Downloading from https://ext-cachev2-cogent01.cdn.yandex.net/download.cdn.yandex.net/browser/yandex/22_3_3_866_31642/ru/Yandex.dmg?vup=1&browser=Safari/32/10.0&pps=installID%3D2758651621652248704_1652248704036&yandexuid=275865162165
######################################################################## 100.0%
Downloaded to: /Users/miccal/Library/Caches/Homebrew/downloads/b30804fcc0f636cf871a692fc8d05b1d4bc7db08973b13b1572654408d391e2f--Yandex.dmg
SHA256: 4f538d722cda4469c6e4304d791b971e654ad77aa75a02fac3e09ae126d4e2d4
Warning: No checksum defined for cask 'yandex', skipping verification.
```
