### ISSUE TITLE
Calling Cask::DSL::Version#before_colon is disabled! Use Cask::DSL::Version#csv instead.

### ISSUE THREAD

**Issue by intfish123** [Homebrew/homebrew-cask#125069]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Run `brew search npm`, and output fllow information:
```
Warning: Calling depends_on :macos => :yosemite is deprecated! There is no replacement.
Please report this issue to the homebrew/cask tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/manuscripts.rb:11

Error: Calling Cask::DSL::Version#before_colon is disabled! Use Cask::DSL::Version#csv instead.
Please report this issue to the homebrew/cask tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/imazing-mini.rb:6
```

### Command that failed

brew search npm

### Output of command with `--verbose --debug`

```shell
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.5.1-24-ga3d14ff\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.0.1\)\ curl/7.77.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/code\?q=user\%3AHomebrew\+path\%3AFormula\+path\%3ACasks\+path\%3A.\+filename\%3Anpm\+extension\%3Arb\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --dump-header /private/tmp/github_api_headers20220609-18954-911xrv
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nfpm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pnpm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nvm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nim.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rpm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qpm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gpm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cpm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::AliasLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb
Warning: Calling depends_on :macos => :yosemite is deprecated! There is no replacement.
Please report this issue to the homebrew/cask tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/manuscripts.rb:11

Error: Calling Cask::DSL::Version#before_colon is disabled! Use Cask::DSL::Version#csv instead.
Please report this issue to the homebrew/cask tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/imazing-mini.rb:6

/usr/local/Homebrew/Library/Homebrew/cask/dsl/version.rb:156:in `before_colon'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/imazing-mini.rb:6:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:64:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:64:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:51:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:87:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:144:in `cask'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/imazing-mini.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:28:in `block in all'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:27:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:27:in `all'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/search.rb:39:in `search_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:130:in `search_names'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:82:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
The current git origin is:
  https://mirrors.aliyun.com/homebrew/brew.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew" remote set-url origin https://github.com/Homebrew/brew

Warning: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.4.


Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.4.


Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://mirrors.aliyun.com/homebrew/homebrew-core.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libecpg.6.dylib
  /usr/local/lib/libecpg_compat.3.dylib
  /usr/local/lib/libpgtypes.3.dylib
  /usr/local/lib/libpq.5.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  kubernetes-cli

Warning: You have uncommitted modifications to Homebrew/brew.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew && git stash && git clean -d -f

Uncommitted files:
  ?? .github/ISSUE_TEMPLATE/bug.md
  ?? .github/ISSUE_TEMPLATE/feature.md
  ?? .github/stale.yml
  ?? .github/workflows/tapioca.yml
  ?? .yardopts
  ?? Library/Homebrew/bintray.rb
  ?? Library/Homebrew/cask/cmd/--cache.rb
  ?? Library/Homebrew/cask/cmd/abstract_internal_command.rb
  ?? Library/Homebrew/cask/cmd/cat.rb
  ?? Library/Homebrew/cask/cmd/create.rb
  ?? Library/Homebrew/cask/cmd/doctor.rb
  ?? Library/Homebrew/cask/cmd/edit.rb
  ?? Library/Homebrew/cask/cmd/help.rb
  ?? Library/Homebrew/cask/cmd/home.rb
  ?? Library/Homebrew/cask/cmd/internal_help.rb
  ?? Library/Homebrew/cask/cmd/internal_stanza.rb
  ?? Library/Homebrew/cask/cmd/outdated.rb
  ?? Library/Homebrew/cask/cmd/style.rb
  ?? Library/Homebrew/cask/topological_hash.rb
  ?? Library/Homebrew/cask/verify.rb
  ?? Library/Homebrew/cmd/--version.rb
  ?? Library/Homebrew/cmd/cask.rb
  ?? Library/Homebrew/cmd/switch.rb
  ?? Library/Homebrew/compat.rb
  ?? Library/Homebrew/compat/cli/parser.rb
  ?? Library/Homebrew/compat/dependencies_helpers.rb
  ?? Library/Homebrew/compat/extend/nil.rb
  ?? Library/Homebrew/compat/extend/string.rb
  ?? Library/Homebrew/compat/language/haskell.rb
  ?? Library/Homebrew/compat/language/java.rb
  ?? Library/Homebrew/compat/language/python.rb
  ?? Library/Homebrew/compat/os/mac.rb
  ?? Library/Homebrew/dev-cmd/diy.rb
  ?? Library/Homebrew/dev-cmd/mirror.rb
  ?? Library/Homebrew/dev-cmd/pull.rb
  ?? Library/Homebrew/dev-cmd/release-notes.rb
  ?? Library/Homebrew/extend/os/caveats.rb
  ?? Library/Homebrew/extend/os/linux/dependency_collector.rb
  ?? Library/Homebrew/extend/os/linux/requirements/java_requirement.rb
  ?? Library/Homebrew/extend/os/linux/requirements/osxfuse_requirement.rb
  ?? Library/Homebrew/extend/os/linux/resource.rb
  ?? Library/Homebrew/extend/os/linux/tap.rb
  ?? Library/Homebrew/extend/os/linux/utils/analytics.rb
  ?? Library/Homebrew/extend/os/mac/caveats.rb
  ?? Library/Homebrew/extend/os/mac/formula.rb
  ?? Library/Homebrew/extend/os/mac/requirements/java_requirement.rb
  ?? Library/Homebrew/extend/os/mac/requirements/osxfuse_requirement.rb
  ?? Library/Homebrew/extend/os/mac/requirements/x11_requirement.rb
  ?? Library/Homebrew/extend/os/mac/resource.rb
  ?? Library/Homebrew/extend/os/requirements/java_requirement.rb
  ?? Library/Homebrew/extend/os/requirements/osxfuse_requirement.rb
  ?? Library/Homebrew/extend/os/requirements/x11_requirement.rb
  ?? Library/Homebrew/extend/os/resource.rb
  ?? Library/Homebrew/language/haskell.rb
  ?? Library/Homebrew/manpages/brew-cask.1.md
  ?? Library/Homebrew/os/global.rb
  ?? Library/Homebrew/os/linux/diagnostic.rb
  ?? Library/Homebrew/os/linux/global.rb
  ?? Library/Homebrew/os/mac/architecture_list.rb
  ?? Library/Homebrew/os/mac/xquartz.rb
  ?? Library/Homebrew/requirements/java_requirement.rb
  ?? Library/Homebrew/requirements/osxfuse_requirement.rb
  ?? Library/Homebrew/requirements/tuntap_requirement.rb
  ?? Library/Homebrew/requirements/x11_requirement.rb
  ?? Library/Homebrew/rubocops/cask/homepage_matches_url.rb
  ?? Library/Homebrew/rubocops/deprecate.rb
  ?? Library/Homebrew/sorbet/files.yaml
  ?? Library/Homebrew/sorbet/rbi/cli.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/activesupport@6.0.3.2.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/colorize@0.8.1.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/commander@4.5.2.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/docile@1.3.2.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/docile@1.3.5.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/i18n@1.8.5.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/mini_portile2@2.4.0.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/minitest@5.14.1.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/net-http-persistent@4.0.0.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/parallel_tests@3.1.0.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/parlour@4.0.1.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/pry@0.13.1.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/rspec-core@3.9.2.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/rspec-expectations@3.9.2.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/rspec-mocks@3.9.1.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/rspec-support@3.9.3.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/rspec@3.9.0.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/rubocop-ast@0.3.0.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/ruby-macho@2.2.0.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/simplecov-html@0.12.2.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/simplecov@0.19.0.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/tapioca@0.4.20.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/thread_safe@0.3.6.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/tzinfo@1.2.7.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/unf_ext@0.0.7.7.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/webrobots@0.1.2.rbi
  ?? Library/Homebrew/sorbet/rbi/gems/zeitwerk@2.4.0.rbi
  ?? Library/Homebrew/sorbet/rbi/homebrew.rbi
  ?? Library/Homebrew/sorbet/rbi/os.rbi
  ?? Library/Homebrew/sorbet/rbi/utils/inreplace.rbi
  ?? Library/Homebrew/sorbet/rbi/utils/notability.rbi
  ?? Library/Homebrew/sorbet/rbi/utils/shell.rbi
  ?? Library/Homebrew/sorbet/rbi/utils/spdx.rbi
  ?? Library/Homebrew/sorbet/rbi/utils/tty.rbi
  ?? Library/Homebrew/sorbet/rbi/utils/user.rbi
  ?? Library/Homebrew/sorbet/rbi/utils/utils.rbi
  ?? Library/Homebrew/test/bintray_spec.rb
  ?? Library/Homebrew/test/cask/cmd/cache_spec.rb
  ?? Library/Homebrew/test/cask/cmd/cat_spec.rb
  ?? Library/Homebrew/test/cask/cmd/create_spec.rb
  ?? Library/Homebrew/test/cask/cmd/doctor_spec.rb
  ?? Library/Homebrew/test/cask/cmd/edit_spec.rb
  ?? Library/Homebrew/test/cask/cmd/home_spec.rb
  ?? Library/Homebrew/test/cask/cmd/internal_stanza_spec.rb
  ?? Library/Homebrew/test/cask/cmd/outdated_spec.rb
  ?? Library/Homebrew/test/cask/cmd/shared_examples/invalid_option.rb
  ?? Library/Homebrew/test/cask/cmd/shared_examples/requires_cask_token.rb
  ?? Library/Homebrew/test/cask/cmd/style_spec.rb
  ?? Library/Homebrew/test/cask/cmd_spec.rb
  ?? Library/Homebrew/test/cmd/cask_spec.rb
  ?? Library/Homebrew/test/cmd/switch_spec.rb
  ?? Library/Homebrew/test/dev-cmd/man_spec.rb
  ?? Library/Homebrew/test/dev-cmd/pull_spec.rb
  ?? Library/Homebrew/test/download_strategies_spec.rb
  ?? Library/Homebrew/test/formula_support/bottle_disable_reason_spec.rb
  ?? Library/Homebrew/test/java_requirement_spec.rb
  ?? Library/Homebrew/test/os/mac/java_requirement_spec.rb
  ?? Library/Homebrew/test/requirements/java_requirement_spec.rb
  ?? Library/Homebrew/test/requirements/osxfuse_requirement_spec.rb
  ?? Library/Homebrew/test/rubocops/cask/homepage_matches_url_spec.rb
  ?? Library/Homebrew/test/rubocops/checksum_spec.rb
  ?? Library/Homebrew/test/rubocops/class_spec.rb
  ?? Library/Homebrew/test/rubocops/deprecate_spec.rb
  ?? Library/Homebrew/test/string_spec.rb
  ?? Library/Homebrew/test/support/fixtures/cask/Casks/github-with-appcast.rb
  ?? Library/Homebrew/test/support/fixtures/cask/Casks/github-without-appcast.rb
  ?? Library/Homebrew/test/support/fixtures/cask/Casks/with-depends-on-x11-false.rb
  ?? Library/Homebrew/test/support/fixtures/cask/Casks/with-depends-on-x11.rb
  ?? Library/Homebrew/test/support/helper/cask/fake_system_command.rb
  ?? Library/Homebrew/test/utils/bottles/bintray_spec.rb
  ?? Library/Homebrew/test/utils/livecheck_formula_spec.rb
  ?? Library/Homebrew/test/x11_requirement_spec.rb
  ?? Library/Homebrew/utils/livecheck_formula.rb
  ?? Library/Homebrew/utils/notability.rb
  ?? completions/zsh/_brew_cask
  ?? docs/Homebrew-homebrew-core-Merge-Checklist.md

You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
  ?? .github/ISSUE_TEMPLATE/bug.md
  ?? .github/stale.yml
  ?? .github/support.yml
  ?? .github/workflows/cancel-previous-runs.yml
  ?? .github/workflows/label-pull-request.yml
  ?? Formula/amap.rb
  ?? Formula/atlassian-cli.rb
  ?? Formula/aurora-cli.rb
  ?? Formula/avian.rb
  ?? Formula/badtouch.rb
  ?? Formula/boost@1.55.rb
  ?? Formula/boost@1.57.rb
  ?? Formula/boost@1.59.rb
  ?? Formula/boost@1.60.rb
  ?? Formula/confluent-platform.rb
  ?? Formula/curl-openssl.rb
  ?? Formula/erlang@20.rb
  ?? Formula/fcct.rb
  ?? Formula/fmsx.rb
  ?? Formula/geant4.rb
  ?? Formula/giter8.rb
  ?? Formula/gobby.rb
  ?? Formula/godep.rb
  ?? Formula/grakn.rb
  ?? Formula/gst-validate.rb
  ?? Formula/joplin.rb
  ?? Formula/kafkacat.rb
  ?? Formula/kde-extra-cmake-modules.rb
  ?? Formula/kde-threadweaver.rb
  ?? Formula/libinfinity.rb
  ?? Formula/llvm@6.rb
  ?? Formula/meson-internal.rb
  ?? Formula/minizip2.rb
  ?? Formula/mysql-connector-c++@1.1.rb
  ?? Formula/now-cli.rb
  ?? Formula/ocamlsdl.rb
  ?? Formula/ori.rb
  ?? Formula/osquery.rb
  ?? Formula/pandoc-citeproc.rb
  ?? Formula/parallelstl.rb
  ?? Formula/pgplot.rb
  ?? Formula/prest.rb
  ?? Formula/prestosql.rb
  ?? Formula/protobuf-swift.rb
  ?? Formula/protobuf@3.7.rb
  ?? Formula/rmtrash.rb
  ?? Formula/scw@1.rb
  ?? Formula/selenium-server-standalone.rb
  ?? Formula/stlviewer.rb
  ?? Formula/terraform-provisioner-ansible.rb
  ?? Formula/tj.rb
  ?? Formula/unp64.rb
  ?? Formula/unrar.rb
  ?? Formula/vavrdiasm.rb
  ?? Formula/weboob.rb
  ?? Formula/woboq_codebrowser.rb
  ?? Formula/wxmac.rb
  ?? Formula/xspin.rb
  ?? Formula/xu4.rb

You have uncommitted modifications to Homebrew/homebrew-cask.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask && git stash && git clean -d -f

Uncommitted files:
  ?? .github/ISSUE_TEMPLATE/01_bug_report.md
  ?? .github/ISSUE_TEMPLATE/02_feature_request.md
  ?? .github/ISSUE_TEMPLATE/03_cask_request.md
  ?? .github/actions/automerge/Dockerfile
  ?? .github/actions/automerge/action.yml
  ?? .github/actions/automerge/automerge.rb
  ?? .github/actions/automerge/git_diff_extensions.rb
  ?? .github/actions/checkout_cask_pr/action.yml
  ?? .github/no-response.yml
  ?? .github/support.yml
  ?? .github/workflows/sync_labels.yml
  ?? .github/workflows/sync_templates_and_ci_config.yml
  ?? Casks/.rubocop.yml
  ?? Casks/0xed.rb
  ?? Casks/ableton-live.rb
  ?? Casks/adobe-air-sdk.rb
  ?? Casks/aliwangwang.rb
  ?? Casks/anvil.rb
  ?? Casks/arrayfire.rb
  ?? Casks/aspera-connect.rb
  ?? Casks/barxtemp.rb
  ?? Casks/battery-guardian.rb
  ?? Casks/beatport-pro.rb
  ?? Casks/blackhole.rb
  ?? Casks/blizz.rb
  ?? Casks/brogue.rb
  ?? Casks/canary.rb
  ?? Casks/catalina-cache-cleaner.rb
  ?? Casks/chicken.rb
  ?? Casks/cisdem-pdftoolkit.rb
  ?? Casks/clashxr.rb
  ?? Casks/coronasdk.rb
  ?? Casks/daedalus.rb
  ?? Casks/delta.rb
  ?? Casks/disablemonitor.rb
  ?? Casks/djay-pro.rb
  ?? Casks/docear.rb
  ?? Casks/doly.rb
  ?? Casks/eventstore.rb
  ?? Casks/evom.rb
  ?? Casks/facebook-ios-sdk.rb
  ?? Casks/flash-npapi.rb
  ?? Casks/flash-player-debugger-npapi.rb
  ?? Casks/flash-player-debugger-ppapi.rb
  ?? Casks/flash-player-debugger.rb
  ?? Casks/flash-player.rb
  ?? Casks/flash-ppapi.rb
  ?? Casks/fractal-bot.rb
  ?? Casks/futuniuniu.rb
  ?? Casks/gfortran.rb
  ?? Casks/ghost.rb
  ?? Casks/gifs.rb
  ?? Casks/google-hangouts.rb
  ?? Casks/hand-mirror.rb
  ?? Casks/hockey.rb
  ?? Casks/imaging-edge.rb
  ?? Casks/imazing-mini.rb
  ?? Casks/insomnia-designer.rb
  ?? Casks/irip.rb
  ?? Casks/java.rb
  ?? Casks/jeromelebel-mongohub.rb
  ?? Casks/jing.rb
  ?? Casks/jira-client.rb
  ?? Casks/kafka-tool.rb
  ?? Casks/kekadefaultapp.rb
  ?? Casks/kindlegen.rb
  ?? Casks/kiwi-for-g-suite.rb
  ?? Casks/kk7ds-python-runtime.rb
  ?? Casks/kode54-cog.rb
  ?? Casks/levelator.rb
  ?? Casks/lightpaper.rb
  ?? Casks/magicplotpro.rb
  ?? Casks/magicplotstudent.rb
  ?? Casks/manuscripts.rb
  ?? Casks/master-password.rb
  ?? Casks/megahertz-knotes.rb
  ?? Casks/mist.rb
  ?? Casks/mongodb-compass-community.rb
  ?? Casks/monogame.rb
  ?? Casks/near-lock.rb
  ?? Casks/nosql-workbench-for-amazon-dynamodb.rb
  ?? Casks/noteplan.rb
  ?? Casks/odio.rb
  ?? Casks/oni.rb
  ?? Casks/openxcom.rb
  ?? Casks/phiewer.rb
  ?? Casks/pibakery.rb
  ?? Casks/pins.rb
  ?? Casks/podman.rb
  ?? Casks/project-slippi-dolphin.rb
  ?? Casks/protonmail-unofficial.rb
  ?? Casks/psequel.rb
  ?? Casks/racket-cs.rb
  ?? Casks/raven.rb
  ?? Casks/realm-studio.rb
  ?? Casks/ring.rb
  ?? Casks/ringtones.rb
  ?? Casks/ripit.rb
  ?? Casks/scaleft.rb
  ?? Casks/screen.rb
  ?? Casks/simplecap.rb
  ?? Casks/softu2f.rb
  ?? Casks/sound-blaster-command.rb
  ?? Casks/station.rb
  ?? Casks/tagalicious.rb
  ?? Casks/use-engine.rb
  ?? Casks/veonim.rb
  ?? Casks/xact.rb
  ?? Casks/yandexradio.rb
  ?? Casks/yyets.rb
  ?? Casks/zoomin.rb
  ?? cmd/brewcask-ci.rb
  ?? doc/development/hacking.md
  ?? doc/faq/apps_with_malware.md
  ?? doc/faq/not_a_discoverability_service.md
  ?? doc/faq/rejected_casks.md

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc

Warning: Your Xcode (12.5.1) is too outdated.
Please update to Xcode 13.4 (or delete it).
Xcode can be updated from the App Store.


Warning: Your Xcode (12.5.1) is outdated.
Please update to Xcode 13.4 (or delete it).
Xcode can be updated from the App Store.
```

### Output of `brew tap`

```shell
carlocab/personal
homebrew/cask
homebrew/core
homebrew/services
```

**Comment by bevanjkay** [comment]
Looking at the `brew doctor` output both of the errors are caused by changes you have in your local version of the `homebrew-cask` tap and not in our version. Have a read of the errors and you should be able to work out what edits to make to fix the issues.
