### ISSUE TITLE
404 on Windscribe

### ISSUE THREAD

**Issue by Kwadz** [Homebrew/homebrew-cask#126464]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

It seems the URL of the formula needs to be updated.

```
brew install --cask --force windscribe
==> Downloading https://assets.windscribe.com/desktop/mac/Windscribe.dmg
curl: (22) The requested URL returned error: 404

Error: Download failed on Cask 'windscribe' with message: Download failed: https://assets.windscribe.com/desktop/mac/Windscribe.dmg
```
FYI the new link from their download page is https://assets.totallyacdn.com/desktop/mac/Windscribe_2.3.dmg.

### Command that failed

brew install --cask --force windscribe

### Output of command with `--verbose --debug`

```shell
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.5.2-145-gfe853fc\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.3.1\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://assets.windscribe.com/desktop/mac/Windscribe.dmg
==> Downloading https://assets.windscribe.com/desktop/mac/Windscribe.dmg
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.5.2-145-gfe853fc\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.3.1\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location --head https://assets.windscribe.com/desktop/mac/Windscribe.dmg
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.5.2-145-gfe853fc\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.3.1\)\ curl/7.79.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/richard/Library/Caches/Homebrew/downloads/0d6e26495af6735e120a6a305af3e5de33f593f9350f960417fb2f8629f3d32c--Windscribe.dmg.incomplete https://assets.windscribe.com/desktop/mac/Windscribe.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Error: Download failed on Cask 'windscribe' with message: Download failed: https://assets.windscribe.com/desktop/mac/Windscribe.dmg
/opt/homebrew/Library/Homebrew/download_strategy.rb:417:in `rescue in fetch'
/opt/homebrew/Library/Homebrew/download_strategy.rb:414:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:25:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:185:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:75:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:106:in `install'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:79:in `block in install_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `each'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `install_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:183:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
Not related
```

### Output of `brew tap`

```shell
homebrew/cask
homebrew/core
homebrew/services
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/126452
