### ISSUE TITLE
Spyder 5.3.3 checksum does not match error: SHA256 mismatch

### ISSUE THREAD

**Issue by gbstan** [Homebrew/homebrew-cask#131034]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Cannot install or upgrade Spyder via homebrew, even after deleting the downloaded file from ~/Library/Caches/Homebrew/downloads/

### Command that failed

brew install --cask spyder

### Output of command with `--verbose --debug`

```shell
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://github.com/spyder-ide/spyder/releases/download/v5.3.3/Spyder.dmg
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.5.10-118-g9972cba\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.5.1\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://github.com/spyder-ide/spyder/releases/download/v5.3.3/Spyder.dmg
Already downloaded: /Users/guy-bartstan/Library/Caches/Homebrew/downloads/199decd6dbbe0d57f377aefaeb59cc39b4ceac3489fb7e2afef0689ed2381c63--Spyder.dmg
==> Checking quarantine support
/usr/bin/xattr -h
/usr/bin/swift -target x86_64-apple-macosx12 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/guy-bartstan/Library/Caches/Homebrew/downloads/199decd6dbbe0d57f377aefaeb59cc39b4ceac3489fb7e2afef0689ed2381c63--Spyder.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/guy-bartstan/Library/Caches/Homebrew/downloads/199decd6dbbe0d57f377aefaeb59cc39b4ceac3489fb7e2afef0689ed2381c63--Spyder.dmg
==> /Users/guy-bartstan/Library/Caches/Homebrew/downloads/199decd6dbbe0d57f377aefaeb59cc39b4ceac3489fb7e2afef0689ed2381c63--Spyder.dmg is quarantined
==> Verifying checksum for cask 'spyder'
Error: SHA256 mismatch
Expected: 076e3195ae2d0bde78002be3f00421a0217023e7075245cbfa4b0f121159a30b
  Actual: d5f79908f181469a5ba90fb2572b7f56e1ba95c7f78ea05d4992e08ed68d654a
    File: /Users/guy-bartstan/Library/Caches/Homebrew/downloads/199decd6dbbe0d57f377aefaeb59cc39b4ceac3489fb7e2afef0689ed2381c63--Spyder.dmg
To retry an incomplete download, remove the file above.
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:292:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:68:in `verify_download_integrity'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:33:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:178:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:68:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:79:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:187:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/warning-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tapioca-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/yard-sorbet-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/yard-0.9.28/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/spoom-1.1.11/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-static-and-runtime-0.5.10175/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-0.5.10175/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-static-0.5.10175-universal-darwin-15/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-cobertura-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.21.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.12.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.6.11/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.15.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.14.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-1.35.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-ast-1.21.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec_junit_formatter-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-sorbet-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-github-2.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.11.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-15/2.6.0-static/rdiscount-2.2.0.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rbi-0.0.14/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unparser-0.6.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/pry-0.14.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parlour-8.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-0.5.10175/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-3.1.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-3.12.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.22.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/method_source-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrick-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubyntlm-0.6.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.13.8-x86_64-darwin/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/racc-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-15/2.6.0-static/racc-1.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-4.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2022.0105/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json_schemer-0.2.21/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/uri_template-0.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-15/2.6.0-static/json-2.6.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-15/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hana-1.3.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ecma-re-validator-0.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/regexp_parser-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-15/2.6.0-static/unf_ext-0.0.8.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/did_you_mean-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/commander-4.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/highline-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coderay-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/byebug-11.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-15/2.6.0-static/byebug-11.1.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bootsnap-1.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-15/2.6.0-static/bootsnap-1.13.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/msgpack-1.5.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-15/2.6.0-static/msgpack-1.5.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.10/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/addressable-2.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/public_suffix-5.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.16.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.12.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin21
/Library/Ruby/Site/2.6.0/universal-darwin21
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin21
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin21
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin21
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
3.5.10-118-g9972cba
==> macOS
12.5.1
==> SIP
Enabled
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4056 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (225 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1971 casks)
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  fasd
  subliminal

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/Caskroom/miniconda/base/bin/python3.9-config
  /usr/local/Caskroom/miniconda/base/bin/python3-config
  /usr/local/Caskroom/miniconda/base/bin/ncursesw6-config
```

### Output of `brew tap`

```shell
beeftornado/rmtree
federico-terzi/espanso
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
ms-jpq/sad
saulpw/vd
tankerhq/repo
zdcthomas/tools
```

**Comment by carlocab** [comment]
Please follow the instructions at https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match.

**Comment by gbstan** [comment]
I have tried but it doesn't work. I don't know what I am doing wrong.

brew bump-cask-pr --version 5.3.3 spyder
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask-fonts).

==> Installing 'bundler' gem
Fetching bundler-1.17.3.gem
Fetching gem metadata from https://rubygems.org/.........
Fetching zeitwerk 2.6.0
Fetching concurrent-ruby 1.1.10
Fetching minitest 5.16.3
Installing minitest 5.16.3
Installing zeitwerk 2.6.0
Installing concurrent-ruby 1.1.10
Fetching public_suffix 5.0.0
Fetching ast 2.4.2
Installing ast 2.4.2
Fetching bindata 2.4.10
Installing public_suffix 5.0.0
Fetching msgpack 1.5.6
Installing bindata 2.4.10
Using bundler 1.17.3
Fetching byebug 11.1.3
Fetching connection_pool 2.2.5
Installing msgpack 1.5.6 with native extensions
Installing byebug 11.1.3 with native extensions
Installing connection_pool 2.2.5
Fetching did_you_mean 1.6.1
Installing did_you_mean 1.6.1
Fetching diff-lcs 1.5.0
Installing diff-lcs 1.5.0
Fetching docile 1.4.0
Installing docile 1.4.0
Fetching unf_ext 0.0.8.2
Installing unf_ext 0.0.8.2 with native extensions
Fetching regexp_parser 2.5.0
Installing regexp_parser 2.5.0
Fetching hana 1.3.7
Installing hana 1.3.7
Fetching hpricot 0.8.6
Installing hpricot 0.8.6 with native extensions
Fetching json 2.6.2
Installing json 2.6.2 with native extensions
Fetching uri_template 0.7.0
Installing uri_template 0.7.0
Fetching mime-types-data 3.2022.0105
Installing mime-types-data 3.2022.0105
Fetching net-http-digest_auth 1.4.1
Installing net-http-digest_auth 1.4.1
Fetching mini_portile2 2.8.0
Installing mini_portile2 2.8.0
Fetching racc 1.6.0
Installing racc 1.6.0 with native extensions
Fetching rubyntlm 0.6.3
Installing rubyntlm 0.6.3
Fetching webrick 1.7.0
Installing webrick 1.7.0
Fetching webrobots 0.1.2
Installing webrobots 0.1.2
Fetching mustache 1.1.1
Installing mustache 1.1.1
Fetching parallel 1.22.1
Installing parallel 1.22.1
Fetching plist 3.6.0
Installing plist 3.6.0
Fetching rack 2.2.4
Installing rack 2.2.4
Fetching rainbow 3.1.1
Installing rainbow 3.1.1
Fetching rdiscount 2.2.0.2
Fetching rexml 3.2.5
Installing rexml 3.2.5
Installing rdiscount 2.2.0.2 with native extensions
Fetching rspec-support 3.11.0
Installing rspec-support 3.11.0
Fetching sorbet-runtime 0.5.10175
Installing sorbet-runtime 0.5.10175
Fetching ruby-progressbar 1.11.0
Installing ruby-progressbar 1.11.0
Fetching unicode-display_width 2.2.0
Installing unicode-display_width 2.2.0
Fetching ruby-macho 3.0.0
Installing ruby-macho 3.0.0
Fetching simplecov-html 0.12.3
Installing simplecov-html 0.12.3
Fetching simplecov_json_formatter 0.1.4
Installing simplecov_json_formatter 0.1.4
Fetching warning 1.3.0
Installing warning 1.3.0
Fetching parser 3.1.2.1
Installing parser 3.1.2.1
Fetching i18n 1.12.0
Installing i18n 1.12.0
Fetching tzinfo 2.0.5
Installing tzinfo 2.0.5
Fetching addressable 2.8.1
Installing addressable 2.8.1
Fetching elftools 1.1.3
Installing elftools 1.1.3
Fetching net-http-persistent 4.0.1
Installing net-http-persistent 4.0.1
Fetching bootsnap 1.13.0
Installing bootsnap 1.13.0 with native extensions
Fetching ecma-re-validator 0.4.0
Installing ecma-re-validator 0.4.0
Fetching unf 0.1.4
Installing unf 0.1.4
Fetching mime-types 3.4.1
Fetching parallel_tests 3.12.0
Installing mime-types 3.4.1
Installing parallel_tests 3.12.0
Fetching nokogiri 1.13.8 (x86_64-darwin)
Fetching rspec-core 3.11.0
Installing rspec-core 3.11.0
Fetching rspec-expectations 3.11.0
Fetching rspec-mocks 3.11.1
Installing rspec-expectations 3.11.0
Fetching rspec-sorbet 1.8.3
Installing rspec-mocks 3.11.1
Fetching simplecov 0.21.2
Installing rspec-sorbet 1.8.3
Installing simplecov 0.21.2
Installing nokogiri 1.13.8 (x86_64-darwin)
Fetching rubocop-ast 1.21.0
Fetching activesupport 6.1.6.1
Installing rubocop-ast 1.21.0
Installing activesupport 6.1.6.1
Fetching patchelf 1.3.0
Installing patchelf 1.3.0
Fetching ronn 0.7.3
Installing ronn 0.7.3
Fetching json_schemer 0.2.21
Installing json_schemer 0.2.21
Fetching domain_name 0.5.20190701
Fetching rspec-github 2.3.1
Fetching rspec-retry 0.6.2
Installing rspec-github 2.3.1
Installing rspec-retry 0.6.2
Installing domain_name 0.5.20190701
Fetching rspec_junit_formatter 0.5.1
Fetching rspec-its 1.3.0
Fetching rspec 3.11.0
Installing rspec_junit_formatter 0.5.1
Fetching simplecov-cobertura 2.1.0
Installing rspec-its 1.3.0
Installing rspec 3.11.0
Fetching rubocop 1.35.1
Fetching http-cookie 1.0.5
Installing simplecov-cobertura 2.1.0
Fetching rspec-wait 0.0.9
Installing http-cookie 1.0.5
Installing rubocop 1.35.1
Fetching mechanize 2.8.5
Installing rspec-wait 0.0.9
Installing mechanize 2.8.5
Fetching rubocop-rspec 2.12.1
Fetching rubocop-performance 1.14.3
Fetching rubocop-rails 2.15.2
Installing rubocop-performance 1.14.3
Installing rubocop-rspec 2.12.1
Installing rubocop-rails 2.15.2
Fetching rubocop-sorbet 0.6.11
Installing rubocop-sorbet 0.6.11
Bundle complete! 34 Gemfile dependencies, 78 gems now installed.
Bundled gems are installed into `../../usr/local/Homebrew/Library/Homebrew/vendor/bundle`
==> Downloading https://github.com/spyder-ide/spyder/releases/download/v5.3.3/Spyder.dmg
Already downloaded: /Users/guy-bartstan/Library/Caches/Homebrew/downloads/199decd6dbbe0d57f377aefaeb59cc39b4ceac3489fb7e2afef0689ed2381c63--Spyder.dmg
==> replace /version\s+["']5\.3\.3["']/m with "version \"5.3.3\""
==> replace /["']076e3195ae2d0bde78002be3f00421a0217023e7075245cbfa4b0f121159a30b["']/m with "\"d5f79908f181469a5ba90fb2572b7f56e1
audit for spyder: passed

1 file inspected, no offenses detected
Error: Unable to fork: Not Found!

**Comment by carlocab** [comment]
Try creating a GitHub token and then do
```sh
export HOMEBREW_GITHUB_API_TOKEN=your_token_here
```
before doing `brew bump-cask-pr`.

You also don't need to set `HOMEBREW_GITHUB_API_TOKEN` if you cache your credentials with `git`. That's a bit nicer, since you can store the token in your Keychain instead of an environment variable.

**Comment by gbstan** [comment]
I did set the HOMEBREW_GITHUB_API_TOKEN already, so the error must be from somewhere else?

Do I need to execute the command from a specific directory?

brew bump-cask-pr --version 5.3.3 spyder --sha256 d5f79908f181469a5ba90fb2572b7f56e1ba95c7f78ea05d4992e08ed68d654a
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

==> replace /version\s+["']5\.3\.3["']/m with "version \"5.3.3\""
==> replace /["']076e3195ae2d0bde78002be3f00421a0217023e7075245cbfa4b0f121159a30b["']/m with "\"d5f79908f181469a5ba90fb2572b7f56e1ba95c7f78ea05d4992e08ed68d654a\""
audit for spyder: passed

1 file inspected, no offenses detected
Error: Unable to fork: Not Found!

**Comment by carlocab** [comment]
Ok, try forking this repository first through the GitHub UI before doing `bump-cask-pr`.

**Comment by carlocab** [comment]
Alternatively, you could also open a pull request manually with the checksum update. You can find the local copy of the repository at
```
brew --repository homebrew/cask
```

**Comment by gbstan** [comment]
I am not familiar with forking of a repository or doing a pull request manually, unfortunately. I just wanted to help out by mentioning this SHA256 error. Can you help with making the request to update the SHA256 please?

**Comment by carlocab** [comment]
Here's how to fork a repository on GitHub: https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository

I'm on mobile at the moment, but I can try to take a look at it tomorrow when I get back to my computer.

**Comment by gbstan** [comment]
Thank you so much for your help. It would be great if you could have a look tomorrow.

**Comment by carlocab** [comment]
Have you tried forking this repository? It's just a button that says "fork".

**Comment by gbstan** [comment]
Thanks. Didn’t try yet. Might try tomorrow when I get a chance.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/131055
