### ISSUE TITLE
eclipse-installer download is failing

### ISSUE THREAD

**Issue by zenno-code-monk** [Homebrew/homebrew-cask#135881]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

When running `brew install eclipse-installer`, homebrew fails with the following error:

`==> Purging files for version 4.25.0,2022-09 of Cask eclipse-installer
Error: It seems the App source '/Users/zcm/brew/Caskroom/eclipse-installer/4.25.0,2022-09/Eclipse Installer.app' is not there.`

I have never installed `eclipse-installer` before and it does not show up when I run `brew list --cask`. Why is it checking for an existing app there if I am installing it for the first time?

Just to be sure, I have run `brew remove --zap eclipse-installer` and tried again, as well as trying again on a different installation of homebrew (same machine but different user, ring fenced installation), with the same results.

Just to humour the installer, I created an empty `Eclipse Installer.app` file to see what happens. homebrew copy&pasted the file over to `/Applications/Eclipse Installer.app` and exited successfully.

### Command that failed

brew install eclipse-installer

### Output of command with `--verbose --debug`

```shell
==> Auto-updated Homebrew!
==> Updated Homebrew from 06b7573e0 to af1e1da9e.
Updated 1 tap (homebrew/core).

Running `brew update --auto-update`...
==> Cask::Installer#install
==> Printing caveats
==> Caveats
eclipse-installer requires Java. You can install the latest version with:
  brew install --cask temurin

==> Cask::Installer#fetch
==> Downloading https://eclipse.org/downloads/download.php?file=/oomph/epp/2022-09/R/eclipse-inst-aarch64.tar.gz&r=1
/Users/zcm/brew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.11-7-gaf1e1da\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.0\)\ curl/7.84.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://eclipse.org/downloads/download.php\?file=/oomph/epp/2022-09/R/eclipse-inst-aarch64.tar.gz\&r=1
==> Downloading from https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2022-09/R/eclipse-inst-aarch64.tar.gz&r=1
/Users/zcm/brew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.11-7-gaf1e1da\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.0\)\ curl/7.84.0 --header Accept-Language:\ en --retry 3 --location --head https://www.eclipse.org/downloads/download.php\?file=/oomph/epp/2022-09/R/eclipse-inst-aarch64.tar.gz\&r=1
/Users/zcm/brew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.11-7-gaf1e1da\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.0\)\ curl/7.84.0 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php.incomplete https://www.eclipse.org/downloads/download.php\?file=/oomph/epp/2022-09/R/eclipse-inst-aarch64.tar.gz\&r=1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17201    0 17201    0     0  13857      0 --:--:--  0:00:01 --:--:-- 13916
==> Checking quarantine support
/usr/bin/xattr -h
/usr/bin/swift -target arm64-apple-macosx13 /Users/zcm/brew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php
/usr/bin/xattr -p com.apple.quarantine /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php
==> /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php is not quarantined
==> Quarantining /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php
/usr/bin/swift -target arm64-apple-macosx13 /Users/zcm/brew/Library/Homebrew/cask/utils/quarantine.swift /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php https://eclipse.org/downloads/download.php\?file=/oomph/epp/2022-09/R/eclipse-inst-aarch64.tar.gz\&r=1 https://eclipse.org/
==> Verifying checksum for cask 'eclipse-installer'
hdiutil imageinfo -format /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php
==> Installing Cask eclipse-installer
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Uncompressed for /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php
cp -p /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php /Users/zcm/brew/Caskroom/eclipse-installer/4.25.0,2022-09/download.php
==> Verifying Gatekeeper status of /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php
/usr/bin/xattr -p com.apple.quarantine /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php
==> /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php is quarantined
==> Propagating quarantine from /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php to /Users/zcm/brew/Caskroom/eclipse-installer/4.25.0,2022-09
/usr/bin/xattr -p com.apple.quarantine /Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;63743b48\;Homebrew\\x20Cask\;139C9E89-A9E2-4256-B146-8094EFBF591B
==> Creating metadata directory: /Users/zcm/brew/Caskroom/eclipse-installer/.metadata/4.25.0,2022-09/20221116012216.480
==> Creating metadata subdirectory: /Users/zcm/brew/Caskroom/eclipse-installer/.metadata/4.25.0,2022-09/20221116012216.480/Casks
==> Installing artifacts
==> 1 artifact defined
#<Cask::ArtifactSet: {#<Cask::Artifact::App:0x00000001329aebf0 @cask=#<Cask::Cask:0x000000013288c1f0 @token="eclipse-installer", @sourcefile_path=#<Pathname:/Users/zcm/brew/Library/Taps/homebrew/homebrew-cask/Casks/eclipse-installer.rb>, @source="cask \"eclipse-installer\" do\n  arch arm: \"aarch64\", intel: \"mac64\"\n\n  version \"4.25.0,2022-09\"\n  sha256 arm:   \"5836c85d1592c9d28ff8ea2c4cb0abea76ca5e24af4e5f60e7c4b4065c683fd7\",\n         intel: \"4005fcf9ef11813d8ea8cabd21153c639a6e951d42f73c2941b3f119dcd668b9\"\n\n  url \"https://eclipse.org/downloads/download.php?file=/oomph/epp/\#{version.csv.second}/R/eclipse-inst-\#{arch}.tar.gz&r=1\"\n  name \"Eclipse Installer\"\n  name \"Eclipse IDE installer\"\n  desc \"Install and update your Eclipse Development Environment\"\n  homepage \"https://eclipse.org/\"\n\n  livecheck do\n    cask \"eclipse-ide\"\n  end\n\n  app \"Eclipse Installer.app\"\n\n  caveats do\n    depends_on_java\n  end\nend\n", @tap=#<Tap:0x00000001336268b0 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/Users/zcm/brew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/Users/zcm/brew/Library/Taps/homebrew/homebrew-cask/Casks>>, @allow_reassignment=false, @block=#<Proc:0x000000013288c128@/Users/zcm/brew/Library/Taps/homebrew/homebrew-cask/Casks/eclipse-installer.rb:1>, @default_config=#<Cask::Config:0x000000013285c040 @explicit={}>, @caskroom_path=#<Pathname:/Users/zcm/brew/Caskroom/eclipse-installer>, @metadata_main_container_path=#<Pathname:/Users/zcm/brew/Caskroom/eclipse-installer/.metadata>, @config=#<Cask::Config:0x00000001329a4740 @explicit={}>, @dsl=#<Cask::DSL:0x00000001329a4560 @cask=#<Cask::Cask:0x000000013288c1f0 ...>, @token="eclipse-installer", @on_system_blocks_exist=true, @arch="aarch64", @version="4.25.0,2022-09", @sha256=#<Checksum:0x00000001329aff50 @hexdigest="5836c85d1592c9d28ff8ea2c4cb0abea76ca5e24af4e5f60e7c4b4065c683fd7">, @url=#<URL::DSL:0x00000001329af708 @uri=#<URI::HTTPS https://eclipse.org/downloads/download.php?file=/oomph/epp/2022-09/R/eclipse-inst-aarch64.tar.gz&r=1>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @only_path=nil, @specs={:user_agent=>:default}>, @name=["Eclipse Installer", "Eclipse IDE installer"], @desc="Install and update your Eclipse Development Environment", @homepage="https://eclipse.org/", @livecheck=#<Livecheck:0x00000001329af078 @package_or_resource=#<Cask::DSL:0x00000001329a4560 ...>, @referenced_cask_name="eclipse-ide", @referenced_formula_name=nil, @regex=nil, @skip=false, @skip_msg=nil, @strategy=nil, @url=nil>, @livecheckable=true, @artifacts=#<Cask::ArtifactSet: {...}>, @caveats=#<Cask::DSL::Caveats:0x00000001329aea88 @cask=#<Cask::Cask:0x000000013288c1f0 ...>, @command=SystemCommand, @built_in_caveats={[:depends_on_java]=>"eclipse-installer requires Java. You can install the latest version with:\n  brew install --cask temurin\n"}, @custom_caveats=[], @discontinued=false>, @language_eval=nil>, @download=#<Pathname:/Users/zcm/Library/Caches/Homebrew/downloads/27afcb50bf7fff7c18108913619d3b0942b68bdc357d0e2199c51469e87f8a30--download.php>>, @dsl_args=["Eclipse Installer.app", {}], @source_string="Eclipse Installer.app", @target_string="">}>
==> Installing artifact of class Cask::Artifact::App
==> Purging files for version 4.25.0,2022-09 of Cask eclipse-installer
Error: It seems the App source '/Users/zcm/brew/Caskroom/eclipse-installer/4.25.0,2022-09/Eclipse Installer.app' is not there.
/Users/zcm/brew/Library/Homebrew/cask/artifact/moved.rb:39:in `move'
/Users/zcm/brew/Library/Homebrew/cask/artifact/moved.rb:20:in `install_phase'
/Users/zcm/brew/Library/Homebrew/cask/installer.rb:241:in `block in install_artifacts'
/Users/zcm/brew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/Users/zcm/brew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/Users/zcm/brew/Library/Homebrew/cask/installer.rb:234:in `install_artifacts'
/Users/zcm/brew/Library/Homebrew/cask/installer.rb:111:in `install'
/Users/zcm/brew/Library/Homebrew/cask/cmd/install.rb:111:in `block in install_casks'
/Users/zcm/brew/Library/Homebrew/cask/cmd/install.rb:110:in `each'
/Users/zcm/brew/Library/Homebrew/cask/cmd/install.rb:110:in `install_casks'
/Users/zcm/brew/Library/Homebrew/cmd/install.rb:192:in `install'
/Users/zcm/brew/Library/Homebrew/brew.rb:95:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/warning-1.3.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/tapioca-0.7.3/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/yard-sorbet-0.6.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/yard-0.9.28/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/spoom-1.1.11/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/thor-1.2.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-static-and-runtime-0.5.10461/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-0.5.10461/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-static-0.5.10461-universal-darwin-21/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/simplecov-cobertura-2.1.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/simplecov-0.21.2/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/simplecov_json_formatter-0.1.4/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/simplecov-html-0.12.3/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-macho-3.0.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-sorbet-0.6.11/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-rspec-2.15.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-rails-2.17.2/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-performance-1.15.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.35.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/unicode-display_width-2.3.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-ast-1.23.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec_junit_formatter-0.6.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-sorbet-1.9.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-its-1.3.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-github-2.4.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-3.12.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-mocks-3.12.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-expectations-3.12.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.12.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-support-3.12.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ronn-0.7.3/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rexml-3.2.5/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rdiscount-2.2.7/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/rdiscount-2.2.7
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rbi-0.0.14/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/unparser-0.6.4/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rack-3.0.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/pry-0.14.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/plist-3.6.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parlour-8.0.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rainbow-3.1.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parser-3.1.2.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel_tests-3.13.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.22.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/mustache-1.1.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/mechanize-2.8.5/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/webrobots-0.1.2/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/webrick-1.7.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubyntlm-0.6.3/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.13.9-x86_64-darwin/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/racc-1.6.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/racc-1.6.0
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/net-http-persistent-4.0.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/mime-types-3.4.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/mime-types-data-3.2022.0105/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/json_schemer-0.2.23/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/uri_template-0.7.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/json-2.6.2/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/json-2.6.2
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/http-cookie-1.0.5/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/hpricot-0.8.6/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/hpricot-0.8.6
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/hana-1.3.7/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/elftools-1.2.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ecma-re-validator-0.4.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/regexp_parser-2.6.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/domain_name-0.5.20190701/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/unf-0.1.4/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/unf_ext-0.0.8.2/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/unf_ext-0.0.8.2
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/docile-1.4.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/diff-lcs-1.5.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/did_you_mean-1.6.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.3.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/highline-2.0.3/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/coderay-1.1.3/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/byebug-11.1.3/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/byebug-11.1.3
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.13.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/bootsnap-1.13.0
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/msgpack-1.6.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/msgpack-1.6.0
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bindata-2.4.14/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ast-2.4.2/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/addressable-2.8.1/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/public_suffix-5.0.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.7/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.6/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/tzinfo-2.0.5/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.16.3/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.12.0/lib
~/brew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/arm64e-darwin22
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin22
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/arm64e-darwin22
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin22
~/brew/Library/Homebrew
==> Homebrew Version
3.6.11-7-gaf1e1da
==> macOS
13.0
==> SIP
Enabled
==> Homebrew Cask Staging Location
~/brew/Caskroom
==> Homebrew Cask Taps:
/Users/zcm/brew/Library/Taps/homebrew/homebrew-cask (4119 casks)
/Users/zcm/brew/Library/Taps/homebrew/homebrew-cask-drivers (216 casks)
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /opt/homebrew.

Many of Homebrew's bottles (binary packages) can only be used with the default prefix.
Consider uninstalling Homebrew and reinstalling into the default prefix.
It is expected behaviour that some formulae will fail to build in this unsupported configuration.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

### Output of `brew tap`

```shell
buo/cask-upgrade
homebrew/cask
homebrew/cask-drivers
homebrew/core
```

**Comment by bevanjkay** [comment]
The issue here is that the download is not completing, so rather than downloading the binary the URL is returning a PHP rendered HTML document. Therefore Homebrew is unable to find the `.app`. It is possible that upstream have added additional requirements to the download that make the standard `curl` fetch unable to access it.
