### ISSUE TITLE
graphviz is not found

### ISSUE THREAD

**Issue by harikrishna553** [Homebrew/homebrew-cask#137825]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

I tried to search graphviz in my mac, but do not find the formula.

```
$brew search graphviz
==> Casks
graphiql

If you meant "graphviz" specifically:
It was migrated from homebrew/cask to homebrew/core.
```

But as per this documentation (https://graphviz.org/download/) there is a formula graphviz.

### Command that failed

graphviz

### Output of command with `--verbose --debug`

```shell
$brew --verbose --debug
Error: Unknown command: --verbose
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/utils.rb:164:in `exit'
/usr/local/Homebrew/Library/Homebrew/utils.rb:164:in `odie'
/usr/local/Homebrew/Library/Homebrew/brew.rb:121:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
$brew doctor --verbose
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The following directories are not writable by your user:
/usr/local/lib/pkgconfig
/usr/local/share/zsh
/usr/local/share/zsh/site-functions

You should change the ownership of these directories to your user.
  sudo chown -R $(whoami) /usr/local/lib/pkgconfig /usr/local/share/zsh /usr/local/share/zsh/site-functions

And make sure that your user has write permission.
  chmod u+w /usr/local/lib/pkgconfig /usr/local/share/zsh /usr/local/share/zsh/site-functions

Warning: Homebrew/homebrew-core was not tapped properly! Run:
  rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core"
  brew tap homebrew/core

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libMsgCom.dylib
  /usr/local/lib/libSysCtlCom.dylib
  /usr/local/lib/libwep_airdrop.dylib
  /usr/local/lib/libwep_burn.dylib
  /usr/local/lib/libwep_cbcarbon.dylib
  /usr/local/lib/libwep_cbcocoa.dylib
  /usr/local/lib/libwep_chrome.dylib
  /usr/local/lib/libwep_dutil.dylib
  /usr/local/lib/libwep_ff.dylib
  /usr/local/lib/libwep_icloud.dylib
  /usr/local/lib/libwep_mail.dylib
  /usr/local/lib/libwep_post.dylib
  /usr/local/lib/libwep_printer.dylib
  /usr/local/lib/libwep_screen.dylib

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout master
```

### Output of `brew tap`

```shell
$brew tap
homebrew/cask
homebrew/core
```

**Comment by carlocab** [comment]
> ```
> Warning: Homebrew/homebrew-core was not tapped properly! Run:
>  rm -rf "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core"
>  brew tap homebrew/core
> ```
