### ISSUE TITLE
failure on brew install rar command - Error: It seems there is already a Generic Artifact at '/usr/local/lib/default.sfx'. 

### ISSUE THREAD

**Issue by tomorrowx-git** [Homebrew/homebrew-cask#140486]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

failure on brew install rar command - Error: It seems there is already a Generic Artifact at '/usr/local/lib/default.sfx'. 

### Command that failed

brew install rar

### Output of command with `--verbose --debug`

```shell
STUARTMACKENZIE@MAC-NETWORK ~ % brew install rar --verbose --debug
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-167-g7a5f614\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.1\)\ curl/7.85.0 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/STUARTMACKENZIE/Library/Caches/Homebrew/api/formula.json --time-cond /Users/STUARTMACKENZIE/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-167-g7a5f614\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.1\)\ curl/7.85.0 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/rar.rb
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-167-g7a5f614\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.1\)\ curl/7.85.0 --header Accept-Language:\ en --fail --max-time 5 --retry 3 --location --remote-time --output /Users/STUARTMACKENZIE/Library/Caches/Homebrew/api/cask.json --time-cond /Users/STUARTMACKENZIE/Library/Caches/Homebrew/api/cask.json --compressed --silent https://formulae.brew.sh/api/cask.json
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://www.rarlab.com/rar/rarmacos-x64-620.tar.gz
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-167-g7a5f614\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.1\)\ curl/7.85.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://www.rarlab.com/rar/rarmacos-x64-620.tar.gz
Already downloaded: /Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz
==> Checking quarantine support
/usr/bin/xattr -h
/usr/bin/swift -target x86_64-apple-macosx13 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz
==> /Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz is quarantined
==> Verifying checksum for cask 'rar'
tar --list --file /Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz
==> Installing Cask rar
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Tar for /Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz
tar --extract --no-same-owner --file /Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz --directory /private/tmp/d20230201-24659-16a3uer
cp -pR /private/tmp/d20230201-24659-16a3uer/rar/. /usr/local/Caskroom/rar/6.20/rar
chmod -Rf +w /private/tmp/d20230201-24659-16a3uer
==> Verifying Gatekeeper status of /Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz
==> /Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz is quarantined
==> Propagating quarantine from /Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz to /usr/local/Caskroom/rar/6.20
/usr/bin/xattr -p com.apple.quarantine /Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;63d124d8\;Homebrew\\x20Cask\;0484DB08-427A-47E8-AD7C-2E2D58D565E4
==> Installing artifacts
==> 4 artifacts defined
#<Cask::ArtifactSet: {#<Cask::Artifact::Artifact:0x00007f98b9acc1b0 @cask=#<Cask::Cask:0x00007f98b8a94770 @token="rar", @sourcefile_path=nil, @source=nil, @tap=nil, @allow_reassignment=false, @block=#<Proc:0x00007f98b8a946f8@/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:225>, @default_config=#<Cask::Config:0x00007f98add0e510 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/rar>, @metadata_main_container_path=#<Pathname:/usr/local/Caskroom/rar/.metadata>, @config=#<Cask::Config:0x00007f98b9acd3a8 @explicit={}>, @dsl=#<Cask::DSL:0x00007f98b9acd1c8 @cask=#<Cask::Cask:0x00007f98b8a94770 ...>, @token="rar", @version="6.20", @sha256=#<Checksum:0x00007f98b9acced0 @hexdigest="29b1545b70852dbe393cc45d10481c1f2f46101dc7a84919c02af43372760d1e">, @url=#<URL::DSL:0x00007f98b9acc9f8 @uri=#<URI::HTTPS https://www.rarlab.com/rar/rarmacos-x64-620.tar.gz>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @only_path=nil, @specs={:user_agent=>:default}>, @name=["RAR Archiver"], @desc="Archive manager for data compression and backups", @homepage="https://www.rarlab.com/", @artifacts=#<Cask::ArtifactSet: {...}>, @language_eval=nil>, @download=#<Pathname:/Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz>>, @dsl_args=["rar/default.sfx", {:target=>"/usr/local/lib/default.sfx"}], @source_string="rar/default.sfx", @target_string="/usr/local/lib/default.sfx">, #<Cask::Artifact::Artifact:0x00007f98ba1c3c48 @cask=#<Cask::Cask:0x00007f98b8a94770 @token="rar", @sourcefile_path=nil, @source=nil, @tap=nil, @allow_reassignment=false, @block=#<Proc:0x00007f98b8a946f8@/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:225>, @default_config=#<Cask::Config:0x00007f98add0e510 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/rar>, @metadata_main_container_path=#<Pathname:/usr/local/Caskroom/rar/.metadata>, @config=#<Cask::Config:0x00007f98b9acd3a8 @explicit={}>, @dsl=#<Cask::DSL:0x00007f98b9acd1c8 @cask=#<Cask::Cask:0x00007f98b8a94770 ...>, @token="rar", @version="6.20", @sha256=#<Checksum:0x00007f98b9acced0 @hexdigest="29b1545b70852dbe393cc45d10481c1f2f46101dc7a84919c02af43372760d1e">, @url=#<URL::DSL:0x00007f98b9acc9f8 @uri=#<URI::HTTPS https://www.rarlab.com/rar/rarmacos-x64-620.tar.gz>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @only_path=nil, @specs={:user_agent=>:default}>, @name=["RAR Archiver"], @desc="Archive manager for data compression and backups", @homepage="https://www.rarlab.com/", @artifacts=#<Cask::ArtifactSet: {...}>, @language_eval=nil>, @download=#<Pathname:/Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz>>, @dsl_args=["rar/rarfiles.lst", {:target=>"/usr/local/etc/rarfiles.lst"}], @source_string="rar/rarfiles.lst", @target_string="/usr/local/etc/rarfiles.lst">, #<Cask::Artifact::Binary:0x00007f98ba1c36f8 @cask=#<Cask::Cask:0x00007f98b8a94770 @token="rar", @sourcefile_path=nil, @source=nil, @tap=nil, @allow_reassignment=false, @block=#<Proc:0x00007f98b8a946f8@/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:225>, @default_config=#<Cask::Config:0x00007f98add0e510 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/rar>, @metadata_main_container_path=#<Pathname:/usr/local/Caskroom/rar/.metadata>, @config=#<Cask::Config:0x00007f98b9acd3a8 @explicit={}>, @dsl=#<Cask::DSL:0x00007f98b9acd1c8 @cask=#<Cask::Cask:0x00007f98b8a94770 ...>, @token="rar", @version="6.20", @sha256=#<Checksum:0x00007f98b9acced0 @hexdigest="29b1545b70852dbe393cc45d10481c1f2f46101dc7a84919c02af43372760d1e">, @url=#<URL::DSL:0x00007f98b9acc9f8 @uri=#<URI::HTTPS https://www.rarlab.com/rar/rarmacos-x64-620.tar.gz>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @only_path=nil, @specs={:user_agent=>:default}>, @name=["RAR Archiver"], @desc="Archive manager for data compression and backups", @homepage="https://www.rarlab.com/", @artifacts=#<Cask::ArtifactSet: {...}>, @language_eval=nil>, @download=#<Pathname:/Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz>>, @dsl_args=["rar/rar", {}], @source_string="rar/rar", @target_string="">, #<Cask::Artifact::Binary:0x00007f98ba1c3248 @cask=#<Cask::Cask:0x00007f98b8a94770 @token="rar", @sourcefile_path=nil, @source=nil, @tap=nil, @allow_reassignment=false, @block=#<Proc:0x00007f98b8a946f8@/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:225>, @default_config=#<Cask::Config:0x00007f98add0e510 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/rar>, @metadata_main_container_path=#<Pathname:/usr/local/Caskroom/rar/.metadata>, @config=#<Cask::Config:0x00007f98b9acd3a8 @explicit={}>, @dsl=#<Cask::DSL:0x00007f98b9acd1c8 @cask=#<Cask::Cask:0x00007f98b8a94770 ...>, @token="rar", @version="6.20", @sha256=#<Checksum:0x00007f98b9acced0 @hexdigest="29b1545b70852dbe393cc45d10481c1f2f46101dc7a84919c02af43372760d1e">, @url=#<URL::DSL:0x00007f98b9acc9f8 @uri=#<URI::HTTPS https://www.rarlab.com/rar/rarmacos-x64-620.tar.gz>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @only_path=nil, @specs={:user_agent=>:default}>, @name=["RAR Archiver"], @desc="Archive manager for data compression and backups", @homepage="https://www.rarlab.com/", @artifacts=#<Cask::ArtifactSet: {...}>, @language_eval=nil>, @download=#<Pathname:/Users/STUARTMACKENZIE/Library/Caches/Homebrew/downloads/019c6105dc9670883dd486ed33865c1b75a8a5666ea5c1947cc999b9c3ba7161--rarmacos-x64-620.tar.gz>>, @dsl_args=["rar/unrar", {}], @source_string="rar/unrar", @target_string="">}>
==> Installing artifact of class Cask::Artifact::Artifact
==> Purging files for version 6.20 of Cask rar
Error: It seems there is already a Generic Artifact at '/usr/local/lib/default.sfx'.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:66:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:20:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:241:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:234:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:112:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:111:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:111:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:185:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
STUARTMACKENZIE@MAC-NETWORK ~ %
```

### Output of `brew doctor` and `brew config`

```shell
STUARTMACKENZIE@MAC-NETWORK ~ % brew doctor
Your system is ready to brew.
STUARTMACKENZIE@MAC-NETWORK ~ % brew config
HOMEBREW_VERSION: 3.6.20-167-g7a5f614
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7a5f6143d3e7447a64255c548d2e51138c83acd3
Last commit: 25 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7e80272b585ced37b11125d7c04ce77a44e00a76
Core tap last commit: 7 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
STUARTMACKENZIE@MAC-NETWORK ~ %
```

### Output of `brew tap`

```shell
STUARTMACKENZIE@MAC-NETWORK ~ % brew tap
carlocab/personal
homebrew/cask
homebrew/cask-versions
homebrew/core
instantclienttap/instantclient
STUARTMACKENZIE@MAC-NETWORK ~ %
```

**Comment by miccal** [comment]
Try running `brew install --force rar`.

**Comment by tomorrowx-git** [comment]
==> Installing Cask rar
Warning: It seems there is already a Generic Artifact at '/usr/local/lib/default.sfx'; overwriting.
==> Removing Generic Artifact '/usr/local/lib/default.sfx'
==> Moving Generic Artifact 'default.sfx' to '/usr/local/lib/default.sfx'
Warning: It seems there is already a Generic Artifact at '/usr/local/etc/rarfiles.lst'; overwriting.
==> Removing Generic Artifact '/usr/local/etc/rarfiles.lst'
==> Moving Generic Artifact 'rarfiles.lst' to '/usr/local/etc/rarfiles.lst'
==> Linking Binary 'rar' to '/usr/local/bin/rar'
==> Linking Binary 'unrar' to '/usr/local/bin/unrar'
🍺  rar was successfully installed!

Thanks @miccal 🙏🏻
