### ISSUE TITLE
Virtualbox formula doesn't work on ARM macs M1 / M2

### ISSUE THREAD

**Issue by roryabraham** [Homebrew/homebrew-cask#140523]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

As of v7, virtualbox is compatible with M1 and M2 macs: https://www.virtualbox.org/wiki/Changelog-7.0#v00

However, the cask still prevents you from installing `virtualbox` due to architecture incompatibility.

### Command that failed

`brew install virtualbox`

### Output of command with `--verbose --debug`

```shell
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://download.virtualbox.org/virtualbox/7.0.6/VirtualBox-7.0.6-155176-OSX.dmg
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://download.virtualbox.org/virtualbox/7.0.6/VirtualBox-7.0.6-155176-OSX.dmg
Already downloaded: /Users/roryabraham/Library/Caches/Homebrew/downloads/252097eae56ced8353c3e09e5d255f09de30463cb9bd3eae4177eba6f96806d2--VirtualBox-7.0.6-155176-OSX.dmg
==> Checking quarantine support
/usr/bin/xattr -h
/usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/roryabraham/Library/Caches/Homebrew/downloads/252097eae56ced8353c3e09e5d255f09de30463cb9bd3eae4177eba6f96806d2--VirtualBox-7.0.6-155176-OSX.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/roryabraham/Library/Caches/Homebrew/downloads/252097eae56ced8353c3e09e5d255f09de30463cb9bd3eae4177eba6f96806d2--VirtualBox-7.0.6-155176-OSX.dmg
==> /Users/roryabraham/Library/Caches/Homebrew/downloads/252097eae56ced8353c3e09e5d255f09de30463cb9bd3eae4177eba6f96806d2--VirtualBox-7.0.6-155176-OSX.dmg is quarantined
==> Verifying checksum for cask 'virtualbox'
Error: Cask virtualbox depends on hardware architecture being one of [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}.
/opt/homebrew/Library/Homebrew/cask/installer.rb:293:in `arch_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:273:in `satisfy_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:100:in `install'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:112:in `block in install_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:111:in `each'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:111:in `install_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:189:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:98:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell                     
Your system is ready to brew.

...
...

HOMEBREW_VERSION: 3.6.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: 344d32bf7f40183359592ef81ca6486e0587981b
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c7c38c40e91994ba2b59fa8570f836df0178d064
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/cask
homebrew/core
```

**Comment by roryabraham** [comment]
Ah, actually was able to install the developer beta via:

```shell
brew tap homebrew/cask-versions
brew install virtualbox-beta
```

I see [here](https://www.virtualbox.org/wiki/Downloads) that macOS ARM support is still only a developer preview
