### ISSUE TITLE
brew upgrade error

### ISSUE THREAD

**Issue by wjlmelody** [Homebrew/homebrew-cask#140629]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

brew upgrade error

### Command that failed

brew upgrade

### Output of command with `--verbose --debug`

```shell
--remote-time --output /Users/jeremywang/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: formula.json: update failed, falling back to cached version.
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.20-261-gb3a71ba\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 10 --location --remote-time --output /Users/jeremywang/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: formula.json: update failed, falling back to cached version.
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.20-261-gb3a71ba\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 10 --location --remote-time --output /Users/jeremywang/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: formula.json: update failed, falling back to cached version.
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.20-261-gb3a71ba\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 10 --location --remote-time --output /Users/jeremywang/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
Warning: formula.json: update failed, falling back to cached version.
Error: Cannot download non-corrupt https://formulae.brew.sh/api/formula.json!
Error: Kernel.exit
/opt/homebrew/Library/Homebrew/utils.rb:165:in `exit'
/opt/homebrew/Library/Homebrew/utils.rb:165:in `odie'
/opt/homebrew/Library/Homebrew/api.rb:77:in `rescue in fetch_json_api_file'
/opt/homebrew/Library/Homebrew/api.rb:51:in `fetch_json_api_file'
/opt/homebrew/Library/Homebrew/api/formula.rb:21:in `all_formulae'
/opt/homebrew/Library/Homebrew/formulary.rb:667:in `loader_for'
/opt/homebrew/Library/Homebrew/formulary.rb:561:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:609:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:582:in `from_rack'
/opt/homebrew/Library/Homebrew/formula.rb:1870:in `block in installed'
/opt/homebrew/Library/Homebrew/formula.rb:1869:in `each'
/opt/homebrew/Library/Homebrew/formula.rb:1869:in `flat_map'
/opt/homebrew/Library/Homebrew/formula.rb:1869:in `installed'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:135:in `upgrade_outdated_formulae'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:116:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Warning: formula.json: update failed, falling back to cached version.
Warning: formula.json: update failed, falling back to cached version.
Warning: formula.json: update failed, falling back to cached version.
Warning: formula.json: update failed, falling back to cached version.
Error: Cannot download non-corrupt https://formulae.brew.sh/api/formula.json!
```

### Output of `brew tap`

```shell
buo/cask-upgrade
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/command-not-found
homebrew/core
majd/repo
```

**Comment by miccal** [comment]
Ping @Rylan12.
