### ISSUE TITLE
Visual Studio Code 1.75.0 installation fails

### ISSUE THREAD

**Issue by moofigoofi** [Homebrew/homebrew-cask#140609]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Installation of Microsoft Visual Studio 1.75.0 fails with the error message

> Error: It seems the symlink source '/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code' is not there.

The `code` binary seems to be preset in the downloaded zip
```shell
$ unzip -l VSCode-darwin.zip | grep '/code$'
     1034  02-01-2023 17:20   Visual Studio Code.app/Contents/Resources/app/bin/code
```

Unsure whether it is related, as you can see my `brew config`, the `--app-dir` option is and point to a different path than shown in the error message above.

### Command that failed

brew install visual-studio-code

### Output of command with `--verbose --debug`

```shell
$ brew install visual-studio-code --verbose --debug --force
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --cookie /dev/null --globoff --user-agent Homebrew/3.6.20-232-g39e158f\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 10 --location --remote-time --output /Users/foo/Library/Caches/Homebrew/api/formula.json --time-cond /Users/foo/Library/Caches/Homebrew/api/formula.json --compressed --silent https://formulae.brew.sh/api/formula.json
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --cookie /dev/null --globoff --user-agent Homebrew/3.6.20-232-g39e158f\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --max-time 10 --location --remote-time --output /Users/foo/Library/Caches/Homebrew/api/cask.json --time-cond /Users/foo/Library/Caches/Homebrew/api/cask.json --compressed --silent https://formulae.brew.sh/api/cask.json
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-232-g39e158f\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://update.code.visualstudio.com/1.75.0/darwin/stable
==> Downloading https://update.code.visualstudio.com/1.75.0/darwin/stable
==> Downloading from https://az764295.vo.msecnd.net/stable/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/VSCode-darwin.zip
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-232-g39e158f\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --location --head https://az764295.vo.msecnd.net/stable/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/VSCode-darwin.zip
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.20-232-g39e158f\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip.incomplete https://az764295.vo.msecnd.net/stable/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/VSCode-darwin.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  124M  100  124M    0     0  3115k      0  0:00:40  0:00:40 --:--:-- 2705k
==> Checking quarantine support
/usr/bin/xattr -h
/usr/bin/swift -target x86_64-apple-macosx13 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip
/usr/bin/xattr -p com.apple.quarantine /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip
==> /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip is not quarantined
==> Quarantining /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip
/usr/bin/swift -target x86_64-apple-macosx13 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip https://update.code.visualstudio.com/1.75.0/darwin/stable https://code.visualstudio.com/
==> Verifying checksum for cask 'visual-studio-code'
hdiutil imageinfo -format /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip
zipinfo -1 /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip
==> Installing Cask visual-studio-code
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip
zipinfo -1 /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading unzip from API
/usr/bin/env PATH=/usr/local/opt/unzip/bin:/usr/local/Homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin unzip -o /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip -d /private/tmp/d20230205-42638-193ji3l
cp -pR /private/tmp/d20230205-42638-193ji3l/Visual\ Studio\ Code.app/. /usr/local/Caskroom/visual-studio-code/1.75.0/Visual\ Studio\ Code.app
chmod -Rf +w /private/tmp/d20230205-42638-193ji3l
==> Verifying Gatekeeper status of /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip
/usr/bin/xattr -p com.apple.quarantine /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip
==> /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip is quarantined
==> Propagating quarantine from /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip to /usr/local/Caskroom/visual-studio-code/1.75.0
/usr/bin/xattr -p com.apple.quarantine /Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0381\;63df649b\;\;6C520128-3565-485F-87C8-6CD7FE743AA7
==> Installing artifacts
==> 3 artifacts defined
#<Cask::ArtifactSet: {#<Cask::Artifact::App:0x00007fedc80e7f78 @cask=#<Cask::Cask:0x00007fedc5f658a0 @token="visual-studio-code", @sourcefile_path=nil, @source=nil, @tap=#<Tap:0x00007fedbc343aa8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @allow_reassignment=false, @block=#<Proc:0x00007fedc5f65828@/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:233>, @default_config=#<Cask::Config:0x00007fedbfbcd5e0 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/visual-studio-code>, @metadata_main_container_path=#<Pathname:/usr/local/Caskroom/visual-studio-code/.metadata>, @config=#<Cask::Config:0x00007fedc80d6638 @explicit={}>, @dsl=#<Cask::DSL:0x00007fedc80d6160 @cask=#<Cask::Cask:0x00007fedc5f658a0 ...>, @token="visual-studio-code", @version="1.75.0", @sha256=#<Checksum:0x00007fedc80d5c60 @hexdigest="57599dd9e2a32fdbb7421f05d337b064b6b58e71b96a2d88544a9880af9e22de">, @url=#<URL::DSL:0x00007fedc80d52b0 @uri=#<URI::HTTPS https://update.code.visualstudio.com/1.75.0/darwin/stable>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @only_path=nil, @specs={:user_agent=>:default}>, @name=["Microsoft Visual Studio Code", "VS Code"], @desc="Open-source code editor", @homepage="https://code.visualstudio.com/", @auto_updates=true, @artifacts=#<Cask::ArtifactSet: {...}>, @language_eval=nil>, @download=#<Pathname:/Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip>>, @dsl_args=["Visual Studio Code.app", {}], @source_string="Visual Studio Code.app", @target_string="">, #<Cask::Artifact::Binary:0x00007fedc80e77d0 @cask=#<Cask::Cask:0x00007fedc5f658a0 @token="visual-studio-code", @sourcefile_path=nil, @source=nil, @tap=#<Tap:0x00007fedbc343aa8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @allow_reassignment=false, @block=#<Proc:0x00007fedc5f65828@/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:233>, @default_config=#<Cask::Config:0x00007fedbfbcd5e0 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/visual-studio-code>, @metadata_main_container_path=#<Pathname:/usr/local/Caskroom/visual-studio-code/.metadata>, @config=#<Cask::Config:0x00007fedc80d6638 @explicit={}>, @dsl=#<Cask::DSL:0x00007fedc80d6160 @cask=#<Cask::Cask:0x00007fedc5f658a0 ...>, @token="visual-studio-code", @version="1.75.0", @sha256=#<Checksum:0x00007fedc80d5c60 @hexdigest="57599dd9e2a32fdbb7421f05d337b064b6b58e71b96a2d88544a9880af9e22de">, @url=#<URL::DSL:0x00007fedc80d52b0 @uri=#<URI::HTTPS https://update.code.visualstudio.com/1.75.0/darwin/stable>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @only_path=nil, @specs={:user_agent=>:default}>, @name=["Microsoft Visual Studio Code", "VS Code"], @desc="Open-source code editor", @homepage="https://code.visualstudio.com/", @auto_updates=true, @artifacts=#<Cask::ArtifactSet: {...}>, @language_eval=nil>, @download=#<Pathname:/Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip>>, @dsl_args=["/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code", {}], @source_string="/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code", @target_string="">, #<Cask::Artifact::Zap:0x00007fedc80e6e48 @cask=#<Cask::Cask:0x00007fedc5f658a0 @token="visual-studio-code", @sourcefile_path=nil, @source=nil, @tap=#<Tap:0x00007fedbc343aa8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @allow_reassignment=false, @block=#<Proc:0x00007fedc5f65828@/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:233>, @default_config=#<Cask::Config:0x00007fedbfbcd5e0 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/visual-studio-code>, @metadata_main_container_path=#<Pathname:/usr/local/Caskroom/visual-studio-code/.metadata>, @config=#<Cask::Config:0x00007fedc80d6638 @explicit={}>, @dsl=#<Cask::DSL:0x00007fedc80d6160 @cask=#<Cask::Cask:0x00007fedc5f658a0 ...>, @token="visual-studio-code", @version="1.75.0", @sha256=#<Checksum:0x00007fedc80d5c60 @hexdigest="57599dd9e2a32fdbb7421f05d337b064b6b58e71b96a2d88544a9880af9e22de">, @url=#<URL::DSL:0x00007fedc80d52b0 @uri=#<URI::HTTPS https://update.code.visualstudio.com/1.75.0/darwin/stable>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @only_path=nil, @specs={:user_agent=>:default}>, @name=["Microsoft Visual Studio Code", "VS Code"], @desc="Open-source code editor", @homepage="https://code.visualstudio.com/", @auto_updates=true, @artifacts=#<Cask::ArtifactSet: {...}>, @language_eval=nil>, @download=#<Pathname:/Users/foo/Library/Caches/Homebrew/downloads/163d2ec03dc8a703a705533ff72b3595e720cf36e37162b4ad519d8a09b5a99a--VSCode-darwin.zip>>, @dsl_args=[{:trash=>["~/.vscode", "~/Library/Application Support/Code", "~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.microsoft.vscode.sfl*", "~/Library/Caches/com.microsoft.VSCode.ShipIt", "~/Library/Caches/com.microsoft.VSCode", "~/Library/Preferences/ByHost/com.microsoft.VSCode.ShipIt.*.plist", "~/Library/Preferences/com.microsoft.VSCode.helper.plist", "~/Library/Preferences/com.microsoft.VSCode.plist", "~/Library/Saved Application State/com.microsoft.VSCode.savedState"]}], @directives={:trash=>["~/.vscode", "~/Library/Application Support/Code", "~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.microsoft.vscode.sfl*", "~/Library/Caches/com.microsoft.VSCode.ShipIt", "~/Library/Caches/com.microsoft.VSCode", "~/Library/Preferences/ByHost/com.microsoft.VSCode.ShipIt.*.plist", "~/Library/Preferences/com.microsoft.VSCode.helper.plist", "~/Library/Preferences/com.microsoft.VSCode.plist", "~/Library/Saved Application State/com.microsoft.VSCode.savedState"], :signal=>[]}>}>
==> Installing artifact of class Cask::Artifact::App
==> Moving App 'Visual Studio Code.app' to '/Users/foo/Applications/Visual Studio Code.app'
==> Installing artifact of class Cask::Artifact::Binary
==> Reverting installation of artifact of class Cask::Artifact::App
==> Backing App 'Visual Studio Code.app' up to '/usr/local/Caskroom/visual-studio-code/1.75.0/Visual Studio Code.app'
/bin/cp -pR /Users/foo/Applications/Visual\ Studio\ Code.app /usr/local/Caskroom/visual-studio-code/1.75.0/Visual\ Studio\ Code.app
==> Removing App '/Users/foo/Applications/Visual Studio Code.app'
==> Purging files for version 1.75.0 of Cask visual-studio-code
Error: It seems the symlink source '/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code' is not there.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:50:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/binary.rb:13:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:25:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:241:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:234:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:112:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:111:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:111:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:185:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Your system is ready to brew.


```shell
$ brew config
HOMEBREW_VERSION: 3.6.20-232-g39e158f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 39e158fb939dadcdf6ee0a67a0930b15f9b16b39
Last commit: 17 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3cb013317ee128696c35ecf552d9186863d2c69f
Core tap last commit: 2 hours ago
Core tap branch: master
Core tap JSON: 05 Feb 09:20
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--appdir=/Users/foo/Applications", "--fontdir=/Users/foo/Library/Fonts"]
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 1
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 1
HOMEBREW_CURLRC: set
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.K9JQmXqHpN/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSECURE_REDIRECT: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.1
```
```


### Output of `brew tap`

```shell
$ brew tap
buo/cask-upgrade
homebrew/bundle
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by miccal** [comment]
This is the same issue as reported in https://github.com/Homebrew/brew/issues/14505.

See https://github.com/Homebrew/brew/issues/14505#issuecomment-1416902207 for a workaround.
