### ISSUE TITLE
Download failed on Cask ithoughtsX with message: Download failed: https://cdn.toketaware.com?download=iThoughtsX.zip

### ISSUE THREAD

**Issue by otrai** [Homebrew/homebrew-cask#141671]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

After going through the steps provided, I've confirmed the version number is outdated. As stated, I tried to submit a fix by updating the cask with the terminal command provided on github; however, it keeps retrying to dowload gem...but nothing ever happens.

The only difference I can see is that the error is 404, not 403 as stated on the homebrew page for common errors (not sure if that's important) but the newest version on my other computer is 9.3 , while it is 9.2.0 when I do the brew info ithoughtsx command on my new computer.

### Command that failed

.dotfiles 1 % brew install ithoughtsx                                                        21:07:05 ==> Downloading https://cdn.toketaware.com?download=iThoughtsX.zip curl: (22) The requested URL returned error: 404                                Error: Download failed on Cask 'ithoughtsx' with message: Download failed: https://cdn.toketaware.com?download=iThoughtsX.zip

### Output of command with `--verbose --debug`

```shell
.dotfiles 1 % brew install ithoughtsx --verbose --debug                                      21:04:24
==> Downloading https://formulae.brew.sh/api/formula.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.0.3-32-ga3207a0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --fail --location --remote-time --output /Users/otrai/Library/Caches/Homebrew/api/formula.json --time-cond /Users/otrai/Library/Caches/Homebrew/api/formula.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3408k  100 3408k    0     0  9180k      0 --:--:-- --:--:-- --:--:-- 9261k
==> Downloading https://formulae.brew.sh/api/cask.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.0.3-32-ga3207a0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --fail --location --remote-time --output /Users/otrai/Library/Caches/Homebrew/api/cask.json --time-cond /Users/otrai/Library/Caches/Homebrew/api/cask.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  707k  100  707k    0     0  6740k      0 --:--:-- --:--:-- --:--:-- 7008k
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading ithoughtsx
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.3-32-ga3207a0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://cdn.toketaware.com\?download=iThoughtsX.zip
==> Downloading https://cdn.toketaware.com?download=iThoughtsX.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.3-32-ga3207a0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location --head https://cdn.toketaware.com\?download=iThoughtsX.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.3-32-ga3207a0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/otrai/Library/Caches/Homebrew/downloads/881c97c48ad9c0fd6a041c4a298c67cfff17dedf131f32f52b310c9a0c558693--download=iThoughtsX.zip.incomplete https://cdn.toketaware.com\?download=iThoughtsX.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Error: Download failed on Cask 'ithoughtsx' with message: Download failed: https://cdn.toketaware.com?download=iThoughtsX.zip
/opt/homebrew/Library/Homebrew/download_strategy.rb:418:in `rescue in fetch'
/opt/homebrew/Library/Homebrew/download_strategy.rb:415:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:25:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:181:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:100:in `install'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:110:in `block in install_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `each'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `install_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:185:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
.dotfiles 1 % brew doctor                                                                    Your system is ready to brew.

.dotfiles 1 % brew config                                                                    21:06:02
HOMEBREW_VERSION: 4.0.3-32-ga3207a0
ORIGIN: https://github.com/Homebrew/brew
HEAD: a3207a03900d7b012c999fad911a701baed82be5
Last commit: 61 minutes ago
Core tap JSON: 22 Feb 05:04 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
.dotfiles 1 % brew tap                                                                       
homebrew/bundle
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/141033

**Comment by bevanjkay** [comment]
This is actually a slightly different bug to #141033 which only effects the audits.

URL parameters are not currently being passed due to them not being available through the API.
You can temporarily workaround this by setting the environment variable`HOMEBREW_NO_INSTALL_FROM_API=1` but note that this will disable the new API functionality of Homebrew and revert to using `git` instead, and should **not** be considered the long term solution. The bug is being tracked here - https://github.com/Homebrew/brew/issues/14728 - and once fixed you can resume using the API by unsetting the variable.

This issue is also tracked here - https://github.com/Homebrew/homebrew-cask/issues/141562
