### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by SebastianBalle** [Homebrew/homebrew-cask#142136]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I receive the following error when running `brew install --cask meld`:
Error: SHA256 mismatch
Expected: 3df2a1f5fe7fe3d1a71b3401c0edb398234a7f290ec736b90ba7e2ab71c5fb2f
  Actual: 913129f686c606a4a032541da6ca360c67508481aadabf376aab3e0b4a886f1f
     URL: https://raw.githubusercontent.com/Homebrew/homebrew-cask/d67c7a45f9057359a6021ff944c1542cd458171c/Casks/meld.rb

Running the following command: `curl https://raw.githubusercontent.com/Homebrew/homebrew-cask/d67c7a45f9057359a6021ff944c1542cd458171c/Casks/meld.rb` I get the following response:
```html
<html>
<head><title>302 Moved Temporarily</title></head>
<body>
<center><h1>302 Moved Temporarily</h1></center>
<hr><center>Umbrella Cloud Security Gateway</center>
</body>
</html>
```

When following the curl command:
`curl https://raw.githubusercontent.com/Homebrew/homebrew-cask/d67c7a45f9057359a6021ff944c1542cd458171c/Casks/meld.rb -L` I see the following response:
```sh
cask "meld" do
  version "3.21.0-r3,19"
  sha256 "50a4a45b3b7f44910c1a4c782c044579bc9dd09432c5e0a965dbeb973bbc767e"

  url "https://github.com/yousseb/meld/releases/download/osx-#{version.csv.second}/meldmerge.dmg",
      verified: "github.com/yousseb/meld/"
  name "Meld for OSX"
  desc "Visual diff and merge tool"
  homepage "https://yousseb.github.io/meld/"

  livecheck do
    url "https://github.com/yousseb/meld/releases/latest"
    strategy :page_match do |page|
      match = page.match(/Release\s+\(?(\d+(?:\.\d+)*)\.osx(\d+)\)?/i)
      tag = page[%r{href=.*?/osx-(\d+)/meldmerge\.dmg}i, 1]
      "#{match[1]}-r#{match[2]},#{tag}"
    end
  end

  depends_on macos: ">= :high_sierra"

  app "Meld.app"
  # shim script (https://github.com/Homebrew/homebrew-cask/issues/18809)
  shimscript = "#{staged_path}/meld.wrapper.sh"
  binary shimscript, target: "meld"

  preflight do
    File.write shimscript, <<~EOS
      #!/bin/sh
      exec '#{appdir}/Meld.app/Contents/MacOS/Meld' "$@"
    EOS
  end

  zap trash: [
    "~/Library/Preferences/org.gnome.meld.plist",
    "~/.local/share/meld",
    "~/Library/Saved Application State/org.gnome.meld.savedState/",
  ]
end
```

When doing a `sha256sum` on the first response I get `913129f686c606a4a032541da6ca360c67508481aadabf376aab3e0b4a886f1f`but on the second I get the following `3df2a1f5fe7fe3d1a71b3401c0edb398234a7f290ec736b90ba7e2ab71c5fb2f`.

After collecting all information I get the following response from `brew install --cask meld`

```sh
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################## 100.0%
Error: /opt/homebrew/Library/Homebrew/cask/cask_loader.rb:43: syntax error, unexpected '<'
<html>
^
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:44: syntax error, unexpected tCONSTANT, expecting end-of-input
<head><title>302 Moved Temporarily</title></head>
                 ^~~~~
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `load'
/opt/homebrew/Library/Homebrew/cask/installer.rb:569:in `load_cask_from_source_api!'
/opt/homebrew/Library/Homebrew/cask/installer.rb:67:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:102:in `install'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:110:in `block in install_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `each'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `install_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:185:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### Command that failed

 brew install --cask meld

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading meld
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --fail https://raw.githubusercontent.com/Homebrew/homebrew-cask/d67c7a45f9057359a6021ff944c1542cd458171c/Casks/meld.rb
Error: SHA256 mismatch
Expected: 3df2a1f5fe7fe3d1a71b3401c0edb398234a7f290ec736b90ba7e2ab71c5fb2f
  Actual: 913129f686c606a4a032541da6ca360c67508481aadabf376aab3e0b4a886f1f
     URL: https://raw.githubusercontent.com/Homebrew/homebrew-cask/d67c7a45f9057359a6021ff944c1542cd458171c/Casks/meld.rb
Check if you can access the URL in your browser.
Regardless, try again in a few minutes.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:147:in `fetch_homebrew_cask_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:25:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:244:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:396:in `load'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:129:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:57:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:176:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
`brew doctor`
lease note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

`brew config`
HOMEBREW_VERSION: 4.0.4-86-g7c15dce
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7c15dce285900c85476d445dcbc01418e61be37c
Last commit: 18 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bfaf49746e3d82ba3734dcd18e13a7cd582f1df8
Core tap last commit: 3 hours ago
Core tap branch: master
Core tap JSON: 01 Mar 08:53 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
azure/kubelogin
coursier/formulas
dagger/tap
homebrew/cask
homebrew/core
microsoft/git
vmware-tanzu/carvel
```

**Comment by SMillerDev** [comment]
> I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

Please don't check boxes you didn't do.

**Comment by SebastianBalle** [comment]
I verified the latest version on meld Github:
https://github.com/yousseb/meld/releases/tag/osx-19

`brew info meld`
==> meld: 3.21.0-r3,19
https://yousseb.github.io/meld/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/meld.rb
==> Name
Meld for OSX
==> Description
Visual diff and merge tool
==> Artifacts
Meld.app (App)
/opt/homebrew/Caskroom/meld/3.21.0-r3,19/meld.wrapper.sh -> meld (Binary)
==> Analytics
install: 3,023 (30 days), 10,907 (90 days), 43,172 (365 days)
