### ISSUE TITLE
vnc-viewer: Download URL 404

### ISSUE THREAD

**Issue by uhthomas** [Homebrew/homebrew-cask#142408]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

```
❯ brew install vnc-viewer
==> Downloading https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-7.0.1-MacOSX-universal.dmg
curl: (22) The requested URL returned error: 404                              

Error: Download failed on Cask 'vnc-viewer' with message: Download failed: https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-7.0.1-MacOSX-universal.dmg
```

### Command that failed

brew install vnc-viewer

### Output of command with `--verbose --debug`

```shell
❯ brew install vnc-viewer --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading vnc-viewer
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-7.0.1-MacOSX-universal.dmg
==> Downloading https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-7.0.1-MacOSX-universal.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --location --head https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-7.0.1-MacOSX-universal.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/thomas/Library/Caches/Homebrew/downloads/c637373a073041eb5a9019b02685a26c37c5b1efda9123293549d48e51e19d51--VNC-Viewer-7.0.1-MacOSX-universal.dmg.incomplete https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-7.0.1-MacOSX-universal.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Error: Download failed on Cask 'vnc-viewer' with message: Download failed: https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-7.0.1-MacOSX-universal.dmg
/opt/homebrew/Library/Homebrew/download_strategy.rb:418:in `rescue in fetch'
/opt/homebrew/Library/Homebrew/download_strategy.rb:415:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:25:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:181:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:100:in `install'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:110:in `block in install_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `each'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `install_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:185:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Your system is ready to brew.
❯ brew config
HOMEBREW_VERSION: 4.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4d0154fa7926e8a7b06e9b074dd45957e820407c
Last commit: 7 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e16f3ba881dfb7489510f275fa66418ae7f44df3
Core tap last commit: 13 days ago
Core tap branch: master
Core tap JSON: 06 Mar 13:01 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.3.0.0.1.1677462456
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
❯ brew tap
homebrew/cask
homebrew/command-not-found
homebrew/core
```

**Comment by wolfposd** [comment]
url needs to be changed to:
`url "https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-#{version}-MacOSX-universal.dmg"`
