### ISSUE TITLE
nordvpn fails to install

### ISSUE THREAD

**Issue by ashokm** [Homebrew/homebrew-cask#142554]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

From around 04 Mar 2023, `nordvpn` Cask is failing to install.
Possibly related to https://github.com/Homebrew/homebrew-cask/pull/142084

**Command output:**
```
$ brew install --cask nordvpn
==> Downloading https://downloads.nordcdn.com/apps/macos/generic/NordVPN-OpenVPN/7.17.1/NordVPN.pkg
curl: (22) The requested URL returned error: 404

Error: Download failed on Cask 'nordvpn' with message: Download failed: https://downloads.nordcdn.com/apps/macos/generic/NordVPN-OpenVPN/7.17.1/NordVPN.pkg
```

**Environment:**
* macOS Monterey 12.6.3

### Command that failed

brew install --cask nordvpn

### Output of command with `--verbose --debug`

```shell
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.0.5-102-g3e2c713\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --fail --location --remote-time --output /Users/redacted/Library/Caches/Homebrew/api/cask.jws.json --time-cond /Users/redacted/Library/Caches/Homebrew/api/cask.jws.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading nordvpn
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.5-102-g3e2c713\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://downloads.nordcdn.com/apps/macos/generic/NordVPN-OpenVPN/7.17.1/NordVPN.pkg
==> Downloading https://downloads.nordcdn.com/apps/macos/generic/NordVPN-OpenVPN/7.17.1/NordVPN.pkg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.5-102-g3e2c713\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --location --head https://downloads.nordcdn.com/apps/macos/generic/NordVPN-OpenVPN/7.17.1/NordVPN.pkg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.5-102-g3e2c713\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/redacted/Library/Caches/Homebrew/downloads/ec490916db199214bc325c5f1c23dbfa4ae8eaae68977c16544fb6e6dac1d818--NordVPN.pkg.incomplete https://downloads.nordcdn.com/apps/macos/generic/NordVPN-OpenVPN/7.17.1/NordVPN.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Error: Download failed on Cask 'nordvpn' with message: Download failed: https://downloads.nordcdn.com/apps/macos/generic/NordVPN-OpenVPN/7.17.1/NordVPN.pkg
/opt/homebrew/Library/Homebrew/download_strategy.rb:418:in `rescue in fetch'
/opt/homebrew/Library/Homebrew/download_strategy.rb:415:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:25:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:175:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:102:in `install'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:110:in `block in install_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `each'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `install_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:185:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
==> Downloading https://formulae.brew.sh/api/formula.jws.json

Your system is ready to brew.
```

### Output of `brew tap`

```shell
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/core
snyk/tap
```

**Comment by bevanjkay** [comment]
Looks like the release was pulled from availability by upstream. I have opened a PR to fix.
