### ISSUE TITLE
Failure on `brew install free-gpgmail` - It seems the Generic Artifact source '/usr/local/Caskroom/free-gpgmail/7.1,2023.1,/Free-GPGMail_7.1.mailbundle' is not there.

### ISSUE THREAD

**Issue by boris1993** [Homebrew/homebrew-cask#143524]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Failure on `brew install free-gpgmail` - It seems the Generic Artifact source '/usr/local/Caskroom/free-gpgmail/7.1,2023.1,/Free-GPGMail_7.1.mailbundle' is not there.

### Command that failed

brew install free-gpgmail

### Output of command with `--verbose --debug`

```shell
$ brew install free-gpgmail --verbose --debug

/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading free-gpgmail
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://github.com/Free-GPGMail/Free-GPGMail/releases/download/v2023.1/Free-GPGMail_7.1-2023.1.mailbundle.zip
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.9-20-gce07d6a\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://github.com/Free-GPGMail/Free-GPGMail/releases/download/v2023.1/Free-GPGMail_7.1-2023.1.mailbundle.zip
Already downloaded: /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx13 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip
==> /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip is quarantined
==> Verifying checksum for cask 'free-gpgmail'
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gpg-suite-no-mail
/usr/bin/env hdiutil imageinfo -format /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip
/usr/bin/env zipinfo -1 /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip
All formula dependencies satisfied.
==> Installing Cask free-gpgmail
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip
/usr/bin/env zipinfo -1 /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading unzip from API
/usr/bin/env PATH=/usr/local/opt/unzip/bin:/usr/local/Homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin unzip -o /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip -d /private/tmp/d20230322-58945-48zvs2
/usr/bin/env cp -pR /private/tmp/d20230322-58945-48zvs2/Free-GPGMail_7.mailbundle/. /usr/local/Caskroom/free-gpgmail/7.1,2023.1,/Free-GPGMail_7.mailbundle
==> Verifying Gatekeeper status of /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip
==> /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip is quarantined
==> Propagating quarantine from /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip to /usr/local/Caskroom/free-gpgmail/7.1,2023.1,
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/boris1993/Library/Caches/Homebrew/downloads/ec50538b14ee11a55617902ca3589eff71321cef38490b2d0cc0323b66948cee--Free-GPGMail_7.1-2023.1.mailbundle.zip
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0381\;6419efe2\;\;579EA6A8-8C9D-4B8A-A516-5D5A635F9BBD
==> Creating metadata directory: /usr/local/Caskroom/free-gpgmail/.metadata/7.1,2023.1,/20230322050015.403
==> Creating metadata subdirectory: /usr/local/Caskroom/free-gpgmail/.metadata/7.1,2023.1,/20230322050015.403/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Artifact
==> Purging files for version 7.1,2023.1, of Cask free-gpgmail
Error: It seems the Generic Artifact source '/usr/local/Caskroom/free-gpgmail/7.1,2023.1,/Free-GPGMail_7.1.mailbundle' is not there.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:39:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:20:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:237:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:230:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:108:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:108:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:185:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Your system is ready to brew.

$ brew config
HOMEBREW_VERSION: 4.0.9-20-gce07d6a
ORIGIN: https://github.com/Homebrew/brew
HEAD: ce07d6ad31151c05b9bdfedd931c78f554bbe4c9
Last commit: 3 hours ago
Core tap JSON: 22 Mar 04:57 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_ENV_HINTS: set
all_proxy: socks5://127.0.0.1:7890
http_proxy: http://127.0.0.1:7890
https_proxy: http://127.0.0.1:7890
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.40.0 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
```

### Output of `brew tap`

```shell
$ brew tap
beeftornado/rmtree
bell-sw/liberica
git-jiro/jiro
homebrew/autoupdate
homebrew/cask-fonts
homebrew/cask-versions
isen-ng/dotnet-sdk-versions
```

**Comment by toobuntu** [comment]
It is a similar issue on `upgrade`:
```Error: free-gpgmail: It seems there is already a Generic Artifact at '/usr/local/Caskroom/free-gpgmail/7,2022.2.1,/Free-GPGMail_7.mailbundle'.```

Then, after `uninstall`, `cleanup` and attempting to re-`install`:
```Error: It seems the Generic Artifact source '/usr/local/Caskroom/free-gpgmail/7.1,2023.1,/Free-GPGMail_7.1.mailbundle' is not there.```

**Comment by boris1993** [comment]
> It is a similar issue on `upgrade`: `Error: free-gpgmail: It seems there is already a Generic Artifact at '/usr/local/Caskroom/free-gpgmail/7,2022.2.1,/Free-GPGMail_7.mailbundle'.`
> 
> Then, after `uninstall`, `cleanup` and attempting to re-`install`: `Error: It seems the Generic Artifact source '/usr/local/Caskroom/free-gpgmail/7.1,2023.1,/Free-GPGMail_7.1.mailbundle' is not there.`

Exactly what happened to me.

**Comment by julianwki** [comment]
> It is a similar issue on `upgrade`: `Error: free-gpgmail: It seems there is already a Generic Artifact at '/usr/local/Caskroom/free-gpgmail/7,2022.2.1,/Free-GPGMail_7.mailbundle'.`
> 
> Then, after `uninstall`, `cleanup` and attempting to re-`install`: `Error: It seems the Generic Artifact source '/usr/local/Caskroom/free-gpgmail/7.1,2023.1,/Free-GPGMail_7.1.mailbundle' is not there.`

I had the same issues when upgrading, even after merged commits of https://github.com/Homebrew/homebrew-cask/pull/143528
I did `brew install --cask --force free-gpgmail` w/o uninstalling `free-gpgmail` beforehand. Now the package is not part of `brew outdated` any more.

HTH,
  Julian
