### ISSUE TITLE
Errors on brew install mactex

### ISSUE THREAD

**Issue by TangChiaHsin** [Homebrew/homebrew-cask#143642]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

input: brew install mactex
output:
==> Caveats
You must restart your terminal window for the installation of MacTex CLI tools to take effect.
Alternatively, Bash and Zsh users can run the command:

eval "$(/usr/libexec/path_helper)"

==> Downloading https://mirror.ctan.org/systems/mac/mactex/mactex-20220321.pkg
==> Downloading from https://mirrors.sustech.edu.cn/CTAN/systems/mac/mactex/mactex-20220321.pkg
curl: (22) The requested URL returned error: 404

Error: Download failed on Cask 'mactex' with message: Download failed: https://mirror.ctan.org/systems/mac/mactex/mactex-20220321.pkg

It should be 404 not found certainly. Because the latest mactex version is 2023.0314, not 2022.0321.
So plz update the script, I'm waiting for using it.🤣

### Command that failed

brew install mactex

### Output of command with `--verbose --debug`

```shell
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/api/formula.jws.json
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.0.9\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --fail --location --remote-time --output /Users/sss/Library/Caches/Homebrew/api/formula.jws.json --time-cond /Users/sss/Library/Caches/Homebrew/api/formula.jws.json --compressed --speed-limit 100 --speed-time 5 https://mirrors.ustc.edu.cn/homebrew-bottles/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 3702k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/api/cask.jws.json
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.0.9\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --fail --location --remote-time --output /Users/sss/Library/Caches/Homebrew/api/cask.jws.json --time-cond /Users/sss/Library/Caches/Homebrew/api/cask.jws.json --compressed --speed-limit 100 --speed-time 5 https://mirrors.ustc.edu.cn/homebrew-bottles/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  914k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading mactex
==> Cask::Installer#install
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading basictex
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading mactex-no-gui
==> Printing caveats
==> Caveats
You must restart your terminal window for the installation of MacTex CLI tools to take effect.
Alternatively, Bash and Zsh users can run the command:

  eval "$(/usr/libexec/path_helper)"

==> Cask::Installer#fetch
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.9\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://mirror.ctan.org/systems/mac/mactex/mactex-20220321.pkg
==> Downloading https://mirror.ctan.org/systems/mac/mactex/mactex-20220321.pkg
==> Downloading from https://mirrors.ustc.edu.cn/CTAN/systems/mac/mactex/mactex-20220321.pkg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.9\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --location --head https://mirrors.ustc.edu.cn/CTAN/systems/mac/mactex/mactex-20220321.pkg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.9\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/sss/Library/Caches/Homebrew/downloads/b4a8f6bffbfd2af819208c808eda31fdbb959295674dd63f1d0797d4f94d37d3--mactex-20220321.pkg.incomplete https://mirrors.ustc.edu.cn/CTAN/systems/mac/mactex/mactex-20220321.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   150    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Error: Download failed on Cask 'mactex' with message: Download failed: https://mirror.ctan.org/systems/mac/mactex/mactex-20220321.pkg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:418:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:415:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:25:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:176:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:102:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:108:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:108:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:185:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
HOMEBREW_VERSION: 4.0.9
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: 584588afb4ab557bcc0536f2794b4d043c333bb9
Last commit: 3 days ago
Core tap origin: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: b7e525330968bcfe754ea1dd95b3f4768feaa0a0
Core tap last commit: 2 days ago
Core tap branch: master
Core tap JSON: 23 Mar 09:49 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_API_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles/api
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_BREW_GIT_REMOTE: https://mirrors.ustc.edu.cn/brew.git
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://mirrors.ustc.edu.cn/homebrew-core.git
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2

Your system is ready to brew.
```

### Output of `brew tap`

```shell
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/command-not-found
homebrew/core
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/143412

https://github.com/Homebrew/homebrew-cask/pull/143411

**Comment by laguileracl** [comment]
I have the same problem!
Please, review that...

The message indicates that Homebrew is trying to upgrade one outdated package, which is mactex from version 2022.0321 to 2023.0314. However, during the upgrade process, Homebrew encountered an error while downloading the package from the mirror.ctan.org server. Specifically, it received a "404" error, which indicates that the requested URL for the package could not be found on the server. This error suggests that the package file may have been moved or deleted from the server or that there was a temporary issue with the server. 

I tried running the brew upgrade command again later to see if the error has been resolved, but nothing.

**Comment by TangChiaHsin** [comment]
@laguileracl 
This issue has been solved 3 days ago.🤣 I have installed mactex 2023.0314. Maybe you should try to use 'brew update' firstly.

**Comment by ecastroth** [comment]
@TangChiaHsin
Did you install mactex or  mactex-no-gui? I'm having the same issue from yesterday but I'm getting a 404 on the updated link (https://mirror.ctan.org/systems/mac/mactex/mactex-20230314.pkg).

**Comment by TangChiaHsin** [comment]
@ecastroth 
I have installed mactex 20230314, and the updated link you gave can be accessed on my MacBook.
