### ISSUE TITLE
yed: download url now serving html contents (sha256 mismatch)

### ISSUE THREAD

**Issue by eriksw** [Homebrew/homebrew-cask#143851]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Brew is not able to download yed from the url in the cask formula.

The downloaded file is html, attached below (ignore the `.txt` extension to bypass GitHub's attachment rules):

[f90fc07d340511403c9aed3cc4a042fa43092423656342692620f9fee9f34c20--yed.txt](https://github.com/Homebrew/homebrew-cask/files/11081102/f90fc07d340511403c9aed3cc4a042fa43092423656342692620f9fee9f34c20--yed.txt)

I attempted to use `brew bump-cask-pr --version 3.23 yed --force` to fix it, but that failed because the updated sha256 is that of the html: https://github.com/Homebrew/homebrew-cask/pull/143850

### Command that failed

brew install --cask yed

### Output of command with `--verbose --debug`

```shell
➜  ~ brew install --cask yed --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading yed
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://www.yworks.com/resources/yed/demo/yEd-3.23_with-JRE15.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.10-4-geff1cd2\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://www.yworks.com/resources/yed/demo/yEd-3.23_with-JRE15.dmg
Already downloaded: /Users/erik/Library/Caches/Homebrew/downloads/f90fc07d340511403c9aed3cc4a042fa43092423656342692620f9fee9f34c20--yed
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/erik/Library/Caches/Homebrew/downloads/f90fc07d340511403c9aed3cc4a042fa43092423656342692620f9fee9f34c20--yed
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/erik/Library/Caches/Homebrew/downloads/f90fc07d340511403c9aed3cc4a042fa43092423656342692620f9fee9f34c20--yed
==> /Users/erik/Library/Caches/Homebrew/downloads/f90fc07d340511403c9aed3cc4a042fa43092423656342692620f9fee9f34c20--yed is quarantined
==> Verifying checksum for cask 'yed'
Error: SHA256 mismatch
Expected: 9ee18425fd0a3cc1b91921fb3ad6da01464a0d02f67aa442dc52f1691b2b5ea9
  Actual: aa34dcfc2e8b03c9de4be4ec62018cecbbf3559eb735a4ea94f5ec80f7e07fde
    File: /Users/erik/Library/Caches/Homebrew/downloads/f90fc07d340511403c9aed3cc4a042fa43092423656342692620f9fee9f34c20--yed
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:292:in `verify_checksum'
/opt/homebrew/Library/Homebrew/cask/download.rb:68:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:33:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:176:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:102:in `install'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `block in install_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:108:in `each'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:108:in `install_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:188:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
➜  ~ brew doctor
Your system is ready to brew.
➜  ~ brew config
HOMEBREW_VERSION: 4.0.10-4-geff1cd2
ORIGIN: https://github.com/Homebrew/brew
HEAD: eff1cd2d8b79b28c568267ceab24403c787f7fd0
Last commit: 64 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 514ed472a22553f3c2efa69ba4703b930d6cb874
Core tap last commit: 18 minutes ago
Core tap branch: master
Core tap JSON: 27 Mar 16:26 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
➜  ~ brew tap
homebrew/cask
homebrew/cask-drivers
homebrew/core
retailnext/[REDACTED]
rinchsan/tap
```

**Comment by bevanjkay** [comment]
I am unable to replicate the issue locally, can you try again and see if it was a transient issue?

**Comment by razvanazamfirei** [comment]
Hi @eriksw, can you confirm if you are still having this issue?

**Comment by eriksw** [comment]
I can't reproduce it any more.
