### ISSUE TITLE
XAMPP cask installer doesn't run (Quarentined)

### ISSUE THREAD

**Issue by eduardomozart** [Homebrew/homebrew-cask#145517]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Hello,
When running ``brew install xampp --force`` to install XAMPP cask, it fails with the message:

![image](https://user-images.githubusercontent.com/2974895/233435229-225df844-06ee-49f2-9b46-2930deb3f3f1.png)

I'd already seem it into the past, it seems to be related to the ``com.apple.quarentine`` attribute. Maybe the XAMPP cask should be updated to use ``xattr`` to remove it first? As seen here: https://derflounder.wordpress.com/2012/11/20/clearing-the-quarantine-extended-attribute-from-downloaded-applications/

### Command that failed

/usr/bin/sudo -E PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin -- /usr/local/Caskroom/xampp/8.2.4-0/xampp-osx-8.2.4-0-installer.app/Contents/MacOS/osx-x86_64 --mode unattended

### Output of command with `--verbose --debug`

```shell
mac@MacBook-Pro-de-mac ~ % brew install xampp --force --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading xampp
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://downloads.sourceforge.net/xampp/xampp-osx-8.2.4-0-installer.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.14-80-g72bdefb\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.5\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://downloads.sourceforge.net/xampp/xampp-osx-8.2.4-0-installer.dmg
Already downloaded: /Users/mac/Library/Caches/Homebrew/downloads/dc2d477067374fcf6f45ccc575bf1c60e4c7be1191053fbd48d771b3343f2c19--xampp-osx-8.2.4-0-installer.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx12 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/mac/Library/Caches/Homebrew/downloads/dc2d477067374fcf6f45ccc575bf1c60e4c7be1191053fbd48d771b3343f2c19--xampp-osx-8.2.4-0-installer.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/mac/Library/Caches/Homebrew/downloads/dc2d477067374fcf6f45ccc575bf1c60e4c7be1191053fbd48d771b3343f2c19--xampp-osx-8.2.4-0-installer.dmg
==> /Users/mac/Library/Caches/Homebrew/downloads/dc2d477067374fcf6f45ccc575bf1c60e4c7be1191053fbd48d771b3343f2c19--xampp-osx-8.2.4-0-installer.dmg is quarantined
==> Verifying checksum for cask 'xampp'
/usr/bin/env tar --list --file /Users/mac/Library/Caches/Homebrew/downloads/dc2d477067374fcf6f45ccc575bf1c60e4c7be1191053fbd48d771b3343f2c19--xampp-osx-8.2.4-0-installer.dmg
/usr/bin/env hdiutil imageinfo -format /Users/mac/Library/Caches/Homebrew/downloads/dc2d477067374fcf6f45ccc575bf1c60e4c7be1191053fbd48d771b3343f2c19--xampp-osx-8.2.4-0-installer.dmg
==> Installing Cask xampp
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/mac/Library/Caches/Homebrew/downloads/dc2d477067374fcf6f45ccc575bf1c60e4c7be1191053fbd48d771b3343f2c19--xampp-osx-8.2.4-0-installer.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230420-87295-15w8h9y /Users/mac/Library/Caches/Homebrew/downloads/dc2d477067374fcf6f45ccc575bf1c60e4c7be1191053fbd48d771b3343f2c19--xampp-osx-8.2.4-0-installer.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20230420-87295-1iosxtc.list -- /private/tmp/20230420-87295-14cb7zt.bom
/usr/bin/env ditto --bom /private/tmp/20230420-87295-14cb7zt.bom -- /private/tmp/d20230420-87295-15w8h9y/dmg.XMbV1F /private/tmp/d20230420-87295-1bk4k8q
/usr/bin/env diskutil info -plist /private/tmp/d20230420-87295-15w8h9y/dmg.XMbV1F
/usr/bin/env diskutil eject /private/tmp/d20230420-87295-15w8h9y/dmg.XMbV1F
/usr/bin/env cp -pR /private/tmp/d20230420-87295-1bk4k8q/xampp-osx-8.2.4-0-installer.app/. /usr/local/Caskroom/xampp/8.2.4-0/xampp-osx-8.2.4-0-installer.app
==> Verifying Gatekeeper status of /Users/mac/Library/Caches/Homebrew/downloads/dc2d477067374fcf6f45ccc575bf1c60e4c7be1191053fbd48d771b3343f2c19--xampp-osx-8.2.4-0-installer.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/mac/Library/Caches/Homebrew/downloads/dc2d477067374fcf6f45ccc575bf1c60e4c7be1191053fbd48d771b3343f2c19--xampp-osx-8.2.4-0-installer.dmg
==> /Users/mac/Library/Caches/Homebrew/downloads/dc2d477067374fcf6f45ccc575bf1c60e4c7be1191053fbd48d771b3343f2c19--xampp-osx-8.2.4-0-installer.dmg is quarantined
==> Propagating quarantine from /Users/mac/Library/Caches/Homebrew/downloads/dc2d477067374fcf6f45ccc575bf1c60e4c7be1191053fbd48d771b3343f2c19--xampp-osx-8.2.4-0-installer.dmg to /usr/local/Caskroom/xampp/8.2.4-0
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/mac/Library/Caches/Homebrew/downloads/dc2d477067374fcf6f45ccc575bf1c60e4c7be1191053fbd48d771b3343f2c19--xampp-osx-8.2.4-0-installer.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;64416737\;Homebrew\\x20Cask\;9055E6BE-1495-438C-BA78-20BAFB20CD89
==> Creating metadata directory: /usr/local/Caskroom/xampp/.metadata/8.2.4-0/20230420165016.608
==> Creating metadata subdirectory: /usr/local/Caskroom/xampp/.metadata/8.2.4-0/20230420165016.608/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Installer
==> Running installer script 'xampp-osx-8.2.4-0-installer.app/Contents/MacOS/osx-x86_64'
/usr/bin/sudo -E PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin -- /usr/local/Caskroom/xampp/8.2.4-0/xampp-osx-8.2.4-0-installer.app/Contents/MacOS/osx-x86_64 --mode unattended
==> Purging files for version 8.2.4-0 of Cask xampp
Error: Failure while executing; `/usr/bin/sudo -E PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin -- /usr/local/Caskroom/xampp/8.2.4-0/xampp-osx-8.2.4-0-installer.app/Contents/MacOS/osx-x86_64 --mode unattended` was terminated by uncaught signal KILL.
/usr/local/Homebrew/Library/Homebrew/system_command.rb:311:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:63:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:38:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:42:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/installer.rb:37:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:237:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:230:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:239:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:230:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:230:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
mac@MacBook-Pro-de-mac ~ % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libTitleGenerator.0.5.5.dylib
  /usr/local/lib/libVisio2Svg.0.5.5.dylib
  /usr/local/lib/libusb-0.1.4.dylib
  /usr/local/lib/libusbpp-0.1.4.dylib
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/usb.h
  /usr/local/include/usbpp.h
  /usr/local/include/visio2svg/TitleGenerator.h
  /usr/local/include/visio2svg/Visio2Svg.h
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libsane.la
  /usr/local/lib/libusb.la
  /usr/local/lib/libusbpp.la

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/libusb.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libusb.a
  /usr/local/lib/libusbpp.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  handbrake

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

```
mac@MacBook-Pro-de-mac ~ % brew config
HOMEBREW_VERSION: 4.0.14-80-g72bdefb
ORIGIN: https://github.com/Homebrew/brew
HEAD: 72bdefb814083854830ceb2d8adad2c4983f49c8
Last commit: 7 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 43c6563b50a58a20b00f2ec1da91b03a00ee8d07
Core tap last commit: 40 minutes ago
Core tap branch: master
Core tap JSON: 20 Apr 16:46 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.CVdzvy7fPi/org.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 12.6.5-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

### Output of `brew tap`

```shell
mac@MacBook-Pro-de-mac ~ % brew tap
gromgit/fuse
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
```

**Comment by SMillerDev** [comment]
> I'd already seem it into the past, it seems to be related to the com.apple.quarentine attribute. Maybe the XAMPP cask should be updated to use xattr to remove it first?

Definitely not, this is an Apple security feature that Homebrew goes to great lengths to support. A much better solution is to get XAMPP to sign their installer so Apple can verify it.

**Comment by eduardomozart** [comment]
So remove this cask from Homebrew because it simply doesn't work.

**Comment by SMillerDev** [comment]
It had 6000 installs over the past year and you're the first one to mention that so I suspect it has something to do with your system rather than XAMPP.

**Comment by eduardomozart** [comment]
There was only 2 installs into the last two days and there's also reports about this into the XAMPP forums: https://community.apachefriends.org/f/viewtopic.php?f=29&t=82832
They didn't seem that will sign the XAMPP installer app soon.
Downloading the installer from SourceForge manually I also had to remove it from quarentine to be able to run it.

**Comment by SMillerDev** [comment]
That one just mentions that XAMPP is broken though. Not much brew can do about it.

If XAMPP won't fix this and it affects the majority of XAMPP users we can always remove it later.
