### ISSUE TITLE
Error Installing Cask calibre 6.17.0 hdiutil: attach failed - no mountable file systems

### ISSUE THREAD

**Issue by mattgrieser** [Homebrew/homebrew-cask#146005]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Getting a no mountable file systems error when updating to calibre 6.17.0

### Command that failed

brew install --cask calibre --force --verbose --debug

### Output of command with `--verbose --debug`

```shell
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading calibre
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://download.calibre-ebook.com/6.17.0/calibre-6.17.0.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-84-g9d5b017\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.7.6\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://download.calibre-ebook.com/6.17.0/calibre-6.17.0.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-84-g9d5b017\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.7.6\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://download.calibre-ebook.com/6.17.0/calibre-6.17.0.dmg
Already downloaded: /Users/XXXXXXXX/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx11 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/XXXXXXXX/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/XXXXXXXX/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg
==> /Users/XXXXXXXX/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg is quarantined
==> Verifying checksum for cask 'calibre'
/usr/bin/env tar --list --file /Users/XXXXXXXX/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg
/usr/bin/env hdiutil imageinfo -format /Users/XXXXXXXX/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg
==> Installing Cask calibre
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/XXXXXXXX/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230427-71756-606pzh /Users/XXXXXXXX/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg
/usr/bin/env hdiutil convert -format UDTO -o /private/tmp/d20230427-71756-606pzh/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.cdr /Users/XXXXXXXX/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230427-71756-606pzh /private/tmp/d20230427-71756-606pzh/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.cdr
hdiutil: attach failed - no mountable file systems
==> Purging files for version 6.17.0 of Cask calibre
Error: Failure while executing; `/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230427-71756-606pzh /private/tmp/d20230427-71756-606pzh/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.cdr` exited with 1. Here's the output:
hdiutil: attach failed - no mountable file systems

/usr/local/Homebrew/Library/Homebrew/system_command.rb:305:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:59:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:38:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:26:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:211:in `block in mount'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:181:in `mount'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:171:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:116:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:131:in `block in extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:128:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:213:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:79:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:107:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.

HOMEBREW_VERSION: 4.0.15-84-g9d5b017
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9d5b017bb9ce1f9addfdd2325f28afbeb64f968a
Last commit: 3 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6524544aab85de5b5872793590bb0b8791794379
Core tap last commit: 23 minutes ago
Core tap branch: master
Core tap JSON: 27 Apr 13:57 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 13.0.0 build 1300
Git: 2.40.1 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 11.7.6-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

### Output of `brew tap`

```shell
buo/cask-upgrade
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/core
homebrew/services
```

**Comment by razvanazamfirei** [comment]
Hi @mattgrieser, thank you for opening this! 

Can you run `brew cleanup --prune=all` and try installing it again.
If it still doesn't work could you provide the output of: 
```
hdiutil verify ~/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg
hdiutil attach ~/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg
hdiutil info
```
Thank you!

**Comment by mattgrieser** [comment]
✅ `brew cleanup --prune=all`. 

```
brew install --cask calibre
```
```
==> Downloading https://formulae.brew.sh/api/cask.jws.json
############################################################################################## 100.0%
==> Downloading https://download.calibre-ebook.com/6.17.0/calibre-6.17.0.dmg
############################################################################################## 100.0%==> Installing Cask calibre
hdiutil: attach failed - no mountable file systems
==> Purging files for version 6.17.0 of Cask calibre
Error: Failure while executing; `/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230427-76071-t40jgf /private/tmp/d20230427-76071-t40jgf/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.cdr` exited with 1. Here's the output:
hdiutil: attach failed - no mountable file systems
```
```

➜  ~ hdiutil verify ~/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified   CRC32 $AF3AFDA0
Checksumming GPT Header (Primary GPT Header : 1)…
 GPT Header (Primary GPT Header : 1): verified   CRC32 $A935E652
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified   CRC32 $CA68E731
Checksumming  (Apple_Free : 3)…
                    (Apple_Free : 3): verified   CRC32 $00000000
Checksumming disk image (Apple_APFS : 4)…
....................................................................................................
         disk image (Apple_APFS : 4): verified   CRC32 $38698475
Checksumming  (Apple_Free : 5)…
....................................................................................................
                    (Apple_Free : 5): verified   CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
....................................................................................................
GPT Partition Data (Backup GPT Table: verified   CRC32 $CA68E731
Checksumming GPT Header (Backup GPT Header : 7)…
....................................................................................................
  GPT Header (Backup GPT Header : 7): verified   CRC32 $7B4F4197
....................................................................................................
verified   CRC32 $7C89FE41
hdiutil: verify: checksum of "~/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg" is VALID
```
```
➜  ~ hdiutil attach ~/Library/Caches/Homebrew/downloads/cd6108ef823810415a19d310ea5eb578822cc6661cc9508a94e6a28eb44544de--calibre-6.17.0.dmg   
expected   CRC32 $7C89FE41
hdiutil: attach failed - no mountable file systems
```
```
➜  ~ hdiutil info
framework       : 595.140.1
driver          : 595.140.1
```

**Comment by razvanazamfirei** [comment]
Hi @mattgrieser, thank you for this! 

This seems similar to https://github.com/Homebrew/homebrew-cask/issues/96093. I've been able to partially reproduce this, in that running the commands manually gives a similar error. I will say that I had no issues installing directly using homebrew. 

I would try uninstalling calibri (if already) present, clearing the entire cache see below) and installing it again using the `--no-quarantine` flag. 

```
rm -rf "$(brew --cache)"
```

If that doesn't work, I suspect the issue is either .dmg or permissions related.

**Comment by bevanjkay** [comment]
Does the dmg mount correctly if you open it from finder?
