### ISSUE TITLE
TeamViewer installer pkg is installed twice during install

### ISSUE THREAD

**Issue by i0ntempest** [Homebrew/homebrew-cask#146185]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

When installing TeamViewer, the pkg is installed twice:
```
$ brew install teamviewer
==> Downloading https://download.teamviewer.com/download/TeamViewer.dmg
Already downloaded: /Users/Admin/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg
Warning: No checksum defined for cask 'teamviewer', skipping verification.
==> Installing Cask teamviewer
==> Running installer for teamviewer; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is TeamViewer
installer: Upgrading at base path /
installer: The upgrade was successful.
==> Running installer for teamviewer; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is TeamViewer
installer: Upgrading at base path /
installer: The upgrade was successful.
==> The TeamViewer package postinstall script launches TeamViewer app
==> Attempting to close TeamViewer app to avoid unwanted user intervention
🍺  teamviewer was successfully installed!
```
I guess this is due to both `on_mojave :or_newer do` and `on_big_sur :or_newer do` are in the cask file. It looks like `on_mojave :or_newer do` should be `on_mojave do`, but if I do that, although the pkg is installed once, I get this after installing:

```
Error: undefined method `latest?' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:242:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:239:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:230:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:230:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Command that failed

Nothing failed

### Output of command with `--verbose --debug`

```shell
$ brew reinstall --verbose --debug teamviewer
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromDefaultTapPathLoader): loading teamviewer
==> Cask::Installer#reinstall
==> Cask::Installer#install
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromDefaultTapPathLoader): loading teamviewer-host
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://download.teamviewer.com/download/TeamViewer.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://download.teamviewer.com/download/TeamViewer.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://download.teamviewer.com/download/TeamViewer.dmg
Already downloaded: /Users/Admin/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx13 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/Admin/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/Admin/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg
==> /Users/Admin/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg is quarantined
Warning: No checksum defined for cask 'teamviewer', skipping verification.
/usr/bin/env hdiutil imageinfo -format /Users/Admin/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg
==> Installing Cask teamviewer
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/Admin/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230430-29926-1cmr4o /Users/Admin/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20230430-29926-18va919.list -- /private/tmp/20230430-29926-1fnf7ie.bom
/usr/bin/env ditto --bom /private/tmp/20230430-29926-1fnf7ie.bom -- /private/tmp/d20230430-29926-1cmr4o/dmg.gV1sAn /private/tmp/d20230430-29926-f68b6z
/usr/bin/env diskutil info -plist /private/tmp/d20230430-29926-1cmr4o/dmg.gV1sAn
/usr/bin/env diskutil eject /private/tmp/d20230430-29926-1cmr4o/dmg.gV1sAn
/usr/bin/env cp -pR /private/tmp/d20230430-29926-f68b6z/Background.png /usr/local/Caskroom/teamviewer/15.41.8/Background.png
/usr/bin/env cp -pR /private/tmp/d20230430-29926-f68b6z/Install\ TeamViewer.app/. /usr/local/Caskroom/teamviewer/15.41.8/Install\ TeamViewer.app
==> Verifying Gatekeeper status of /Users/Admin/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/Admin/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg
==> /Users/Admin/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg is quarantined
==> Propagating quarantine from /Users/Admin/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg to /usr/local/Caskroom/teamviewer/15.41.8
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/Admin/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;644de36c\;Homebrew\\x20Cask\;6D995A7B-54A0-4623-8B9C-C28E5376856B
==> Creating metadata directory: /usr/local/Caskroom/teamviewer/.metadata/15.41.8/20230430043150.433
==> Creating metadata subdirectory: /usr/local/Caskroom/teamviewer/.metadata/15.41.8/20230430043150.433/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for teamviewer; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
/usr/bin/sudo -E LOGNAME=Admin USER=Admin USERNAME=Admin -- /usr/sbin/installer -pkg /usr/local/Caskroom/teamviewer/15.41.8/Install\ TeamViewer.app/Contents/Resources/Install\ TeamViewer.pkg -target / -verboseR
installer: Package name is TeamViewer
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing TeamViewer…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%2.200000
installer:PHASE:Validating packages…
installer:%5.595377
installer:PHASE:Writing files…
installer:%36.298105
installer:PHASE:Writing files…
installer:%45.508924
installer:PHASE:Writing files…
installer:%65.575869
installer:PHASE:Running package scripts…
installer:%71.783949
installer:PHASE:Registering package with system…
installer:%88.893809
installer:PHASE:Running package scripts…
installer:%89.660669
installer:PHASE:Running package scripts…
installer:%90.431733
installer:PHASE:Running package scripts…
installer:%91.200189
installer:PHASE:Running package scripts…
installer:%91.968919
installer:PHASE:Running package scripts…
installer:%92.736473
installer:PHASE:Running package scripts…
installer:%93.098153
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer:STATUS:Running installer actions…
installer:STATUS:
installer:PHASE:Finishing the Installation…
installer:STATUS:
installer:%100.000000
installer:PHASE:The software was successfully installed.
installer: The upgrade was successful.
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for teamviewer; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
/usr/bin/sudo -E LOGNAME=Admin USER=Admin USERNAME=Admin -- /usr/sbin/installer -pkg /usr/local/Caskroom/teamviewer/15.41.8/Install\ TeamViewer.app/Contents/Resources/Install\ TeamViewer.pkg -target / -verboseR
installer: Package name is TeamViewer
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing TeamViewer…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%2.200000
installer:PHASE:Validating packages…
installer:%5.595377
installer:PHASE:Writing files…
installer:%31.692696
installer:PHASE:Writing files…
installer:%42.438651
installer:PHASE:Writing files…
installer:%65.654688
installer:PHASE:Running package scripts…
installer:%71.797397
installer:PHASE:Registering package with system…
installer:%88.942024
installer:PHASE:Running package scripts…
installer:%89.706424
installer:PHASE:Running package scripts…
installer:%90.472218
installer:PHASE:Running package scripts…
installer:%91.243200
installer:PHASE:Running package scripts…
installer:%92.011715
installer:PHASE:Running package scripts…
installer:%92.780360
installer:PHASE:Running package scripts…
installer:%93.098153
installer:PHASE:Running package scripts…
installer:%93.128951
installer:PHASE:Writing package receipts…
installer:PHASE:Validating packages…
installer:%97.750000
installer:STATUS:Running installer actions…
installer:STATUS:
installer:PHASE:Finishing the Installation…
installer:STATUS:
installer:%100.000000
installer:PHASE:The software was successfully installed.
installer: The upgrade was successful.
==> Installing artifact of class Cask::Artifact::PostflightBlock
==> The TeamViewer package postinstall script launches TeamViewer app
==> Attempting to close TeamViewer app to avoid unwanted user intervention
/usr/bin/env /usr/bin/pkill -f /Applications/TeamViewer.app
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/git --version
🍺  teamviewer was successfully installed!
```

### Output of `brew doctor` and `brew config`

```shell
$ brew config
HOMEBREW_VERSION: 4.0.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 763c41f006ab9b44261e313b0aaa24a047431b06
Last commit: 6 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c97ee7e2776aa88bce1b94c715aa683d9fc29743
Core tap last commit: 2 hours ago
Core tap branch: master
Core tap JSON: 30 Apr 04:04 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.pOHYa0qXBK/org.macports:0
HOMEBREW_EDITOR: /opt/local/bin/nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-x86_64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
```

### Output of `brew tap`

```shell
$ brew tap
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
nrlquaker/createzap
```

**Comment by razvanazamfirei** [comment]
Hi @i0ntempest, 

Thank you for opening this. The cask ended up being very confusing and I decided to rework it. Would you mind checking out #146197 and seeing if that resolves your issue?
