### ISSUE TITLE
Audacity cask has outdated checksums

### ISSUE THREAD

**Issue by matgaj** [Homebrew/homebrew-cask#146121]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

https://www.audacityteam.org/download/mac/ lists different chechsums than the cask code for audacity and therefore audacity won't install

### Command that failed

brew upgrade audacity

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading audacity
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/audacity/.metadata/3.3.0/20230426204306.521/Casks/audacity.json
audacity 3.3.0 -> 3.3.1
==> Started upgrade process for Cask audacity
==> Upgrading audacity
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://github.com/audacity/audacity/releases/download/Audacity-3.3.1/audacity-macOS-3.3.1-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-97-ge191b82\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/audacity/audacity/releases/download/Audacity-3.3.1/audacity-macOS-3.3.1-arm64.dmg
Already downloaded: /Users/matgaj24/Library/Caches/Homebrew/downloads/b56245cef91842a09767bc3645ee46b7d832f23d5612553d1a28c3f3ae28658b--audacity-macOS-3.3.1-arm64.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/matgaj24/Library/Caches/Homebrew/downloads/b56245cef91842a09767bc3645ee46b7d832f23d5612553d1a28c3f3ae28658b--audacity-macOS-3.3.1-arm64.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/matgaj24/Library/Caches/Homebrew/downloads/b56245cef91842a09767bc3645ee46b7d832f23d5612553d1a28c3f3ae28658b--audacity-macOS-3.3.1-arm64.dmg
==> /Users/matgaj24/Library/Caches/Homebrew/downloads/b56245cef91842a09767bc3645ee46b7d832f23d5612553d1a28c3f3ae28658b--audacity-macOS-3.3.1-arm64.dmg is quarantined
==> Verifying checksum for 'b56245cef91842a09767bc3645ee46b7d832f23d5612553d1a28c3f3ae28658b--audacity-macOS-3.3.1-arm64.dmg'
==> Purging files for version 3.3.1 of Cask audacity
Error: audacity: SHA256 mismatch
Expected: 133915a9f227a5f754ee7f3b09b402b14f99ebb7cc81736e9c936722b4cb09c1
  Actual: b06126b34a8011c47c36c738587ef100c40013fabb3c974f2d8cb5c5eca88e74
    File: /Users/matgaj24/Library/Caches/Homebrew/downloads/b56245cef91842a09767bc3645ee46b7d832f23d5612553d1a28c3f3ae28658b--audacity-macOS-3.3.1-arm64.dmg
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:127:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:253:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'

(this is after I did cleanup -s so it's not the old file)
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.

HOMEBREW_VERSION: 4.0.15-97-ge191b82
ORIGIN: https://github.com/Homebrew/brew
HEAD: e191b827cce991f52be36b0a8fc3daed3ef66143
Last commit: 9 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3ea787a8b039e5d662dbd5145686add250f7fe72
Core tap last commit: 8 minutes ago
Core tap branch: master
Core tap JSON: 28 Apr 16:55 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/aliases
homebrew/bundle
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
```

**Comment by matgaj** [comment]
im stupid sorry
