### ISSUE TITLE
brew install <any cask> doesnt work

### ISSUE THREAD

**Issue by Mosrepos** [Homebrew/homebrew-cask#146461]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

brew doesnt install any casks whatsoever

### Command that failed

brew install fig

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading fig
==> Cask::Installer#install
==> Printing caveats
==> Caveats
Please launch the Fig application to finish setup...

==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.16\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://repo.fig.io/generic/stable/asset/2.15.0/universal/fig.dmg
Error: private method `download_name' called for #<Cask::Download:0x000000011b2dc5c8>
Did you mean?  downloader
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/exceptions.rb:612:in `initialize'
/opt/homebrew/Library/Homebrew/downloadable.rb:89:in `new'
/opt/homebrew/Library/Homebrew/downloadable.rb:89:in `rescue in fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:86:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:51:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:174:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:100:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.

HOMEBREW_VERSION: 4.0.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 01e0c20d01c6aab28d844280d130f0e745e2ddd9
Last commit: 4 days ago
Core tap JSON: 04 May 10:50 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### Output of `brew tap`

```shell
no output
```

**Comment by bevanjkay** [comment]
@Bo98 This looks the same as the previous issue #146287
