### ISSUE TITLE
SHA256 mismatch on android-platform-tools

### ISSUE THREAD

**Issue by FvdKlaauw** [Homebrew/homebrew-cask#146961]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

SHA256 mismatch on android-platform-tools

==> Downloading https://dl.google.com/android/repository/platform-tools_r34.0.1-darwin.zip
Error: SHA256 mismatch
Expected: ef3dd374ebd2dddf5d8ab6179feb8016462ad25473ccc44555a98fb37adc9d63
  Actual: 38e4abc642250e7090041e569d9de8d3f1dee2908fa30daf5ebe45a3089ec54b

### Command that failed

brew install --force android-platform-tools

### Output of command with `--verbose --debug`

```shell
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.17-63-g32f2258\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://dl.google.com/android/repository/platform-tools_r34.0.1-darwin.zip
==> Downloading https://dl.google.com/android/repository/platform-tools_r34.0.1-darwin.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.17-63-g32f2258\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --location --head https://dl.google.com/android/repository/platform-tools_r34.0.1-darwin.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.17-63-g32f2258\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/Username/Library/Caches/Homebrew/downloads/005288f91f3bb87ab8eb3f0e01977da70607cb4cb9658cb193bad69c07582827--platform-tools_r34.0.1-darwin.zip.incomplete https://dl.google.com/android/repository/platform-tools_r34.0.1-darwin.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.6M  100 10.6M    0     0  13.0M      0 --:--:-- --:--:-- --:--:-- 13.1M
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/Username/Library/Caches/Homebrew/downloads/005288f91f3bb87ab8eb3f0e01977da70607cb4cb9658cb193bad69c07582827--platform-tools_r34.0.1-darwin.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/Username/Library/Caches/Homebrew/downloads/005288f91f3bb87ab8eb3f0e01977da70607cb4cb9658cb193bad69c07582827--platform-tools_r34.0.1-darwin.zip
==> /Users/Username/Library/Caches/Homebrew/downloads/005288f91f3bb87ab8eb3f0e01977da70607cb4cb9658cb193bad69c07582827--platform-tools_r34.0.1-darwin.zip is not quarantined
==> Quarantining /Users/Username/Library/Caches/Homebrew/downloads/005288f91f3bb87ab8eb3f0e01977da70607cb4cb9658cb193bad69c07582827--platform-tools_r34.0.1-darwin.zip
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/Username/Library/Caches/Homebrew/downloads/005288f91f3bb87ab8eb3f0e01977da70607cb4cb9658cb193bad69c07582827--platform-tools_r34.0.1-darwin.zip https://dl.google.com/android/repository/platform-tools_r34.0.1-darwin.zip https://developer.android.com/studio/releases/platform-tools
==> Verifying checksum for '005288f91f3bb87ab8eb3f0e01977da70607cb4cb9658cb193bad69c07582827--platform-tools_r34.0.1-darwin.zip'
Error: SHA256 mismatch
Expected: ef3dd374ebd2dddf5d8ab6179feb8016462ad25473ccc44555a98fb37adc9d63
  Actual: 38e4abc642250e7090041e569d9de8d3f1dee2908fa30daf5ebe45a3089ec54b
    File: /Users/Username/Library/Caches/Homebrew/downloads/005288f91f3bb87ab8eb3f0e01977da70607cb4cb9658cb193bad69c07582827--platform-tools_r34.0.1-darwin.zip
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:288:in `verify_checksum'
/opt/homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:81:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:60:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:169:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.

HOMEBREW_VERSION: 4.0.17-63-g32f2258
ORIGIN: https://github.com/Homebrew/brew
HEAD: 32f225897e9388da44f2f55b1f1d179ed7df0af7
Last commit: 10 hours ago
Core tap JSON: 11 May 11:36 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
none
```

**Comment by life-is-a-boat** [comment]
a temporary solution to install it!
https://stackoverflow.com/questions/31374085/installing-adb-on-macos

**Comment by SMillerDev** [comment]
> I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

From the checklist has suggestions how to fix it.
