### ISSUE TITLE
per-cask option to ignore "--require-sha" from HOMEBREW_CASK_OPTS

### ISSUE THREAD

**Issue by driverkt** [Homebrew/homebrew-cask#147305]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The "--require-sha" option for `HOMEBREW_CASK_OPTS` is a valuable setting. However, some maintainers are unwilling and/or have not yet added checksums to their formulae. 

Consider adding a setting where a cask can be set to ignore this flag so that initial installs and subsequent updates don't throw errors, such that only the particular cask is affected. 

### Command that failed

brew install --cask chromium

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading chromium
==> Cask::Installer#install
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading eloston-chromium
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading freesmug-chromium
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/3550a0e48efbbf3fe920f83a221764e440dfa04a/Casks/chromium.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.18\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/3550a0e48efbbf3fe920f83a221764e440dfa04a/Casks/chromium.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.18\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://raw.githubusercontent.com/Homebrew/homebrew-cask/3550a0e48efbbf3fe920f83a221764e440dfa04a/Casks/chromium.rb
Already downloaded: ~/Library/Caches/Homebrew/downloads/89947a18e10d5bbda8e2b5d15a60b6823353f019ea1a4b74e3d9c4f91248776e--chromium.rb
==> Verifying checksum for '89947a18e10d5bbda8e2b5d15a60b6823353f019ea1a4b74e3d9c4f91248776e--chromium.rb'
==> Checking cask has checksum
Error: Cask 'chromium' does not have a sha256 checksum defined and was not installed.
This means you have the --require-sha option set, perhaps in your HOMEBREW_CASK_OPTS.
/opt/homebrew/Library/Homebrew/cask/installer.rb:177:in `verify_has_sha'
/opt/homebrew/Library/Homebrew/cask/installer.rb:67:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.





HOMEBREW_VERSION: 4.0.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0dc84b117f54f6b18e0528b95477c54e409ebdd
Last commit: 4 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1655c17518c96f9f5c4819b95cbe51539d30d3e9
Core tap last commit: 3 months ago
Core tap branch: master
Core tap JSON: 16 May 22:01 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--require-sha"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.DFCTkIwwmq/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSECURE_REDIRECT: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### Output of `brew tap`

```shell
adoptopenjdk/openjdk
beeftornado/rmtree
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
samtay/tui
```

**Comment by bevanjkay** [comment]
@driverkt There are instances where it isn't possible to add a `shasum` such as in the case of `chromium`. This is because the available download URL is not versioned, which would result in the cask breaking every time upstream update the software (because the shasum for the binary would change).

I would recommend that when you see the error you try running the same command with `--force` so that you can override the `--require-sha` option on an as-needed basis.

**Comment by SMillerDev** [comment]
I don't think there is anything cask can or should do here. Some software can't be checksummed, if you want to force checksums you will have to accept that some software will throw errors because of that.
