### ISSUE TITLE
Homebrew install fails due to write permissions issue

### ISSUE THREAD

**Issue by Volatus** [Homebrew/homebrew-cask#148253]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

`brew` will fail updating casks due to write permissions issues since the application already exists. This issue currently happens for me with the https://github.com/Homebrew/homebrew-cask/blob/master/Casks/docker.rb and https://github.com/Homebrew/homebrew-cask/blob/master/Casks/alfred.rb casks.

### Command that failed

`brew update && brew upgrade --greedy` (also tried with `brew reinstall --cask --force alfred`

### Output of command with `--verbose --debug`

```shell
❯ brew reinstall --force --cask --debug --verbose alfred         
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading alfred
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://cachefly.alfredapp.com/Alfred_5.1.1_2138.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.20-2-ga380aed\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://cachefly.alfredapp.com/Alfred_5.1.1_2138.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.20-2-ga380aed\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://cachefly.alfredapp.com/Alfred_5.1.1_2138.dmg
Already downloaded: /Users/menace/Library/Caches/Homebrew/downloads/c07c71d56fbadd9a0880939c29fd4ef7adfa58117b9d88baabcd72700a23e6ce--Alfred_5.1.1_2138.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/menace/Library/Caches/Homebrew/downloads/c07c71d56fbadd9a0880939c29fd4ef7adfa58117b9d88baabcd72700a23e6ce--Alfred_5.1.1_2138.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/menace/Library/Caches/Homebrew/downloads/c07c71d56fbadd9a0880939c29fd4ef7adfa58117b9d88baabcd72700a23e6ce--Alfred_5.1.1_2138.dmg
==> /Users/menace/Library/Caches/Homebrew/downloads/c07c71d56fbadd9a0880939c29fd4ef7adfa58117b9d88baabcd72700a23e6ce--Alfred_5.1.1_2138.dmg is quarantined
==> Verifying checksum for 'c07c71d56fbadd9a0880939c29fd4ef7adfa58117b9d88baabcd72700a23e6ce--Alfred_5.1.1_2138.dmg'
/usr/bin/env hdiutil imageinfo -format /Users/menace/Library/Caches/Homebrew/downloads/c07c71d56fbadd9a0880939c29fd4ef7adfa58117b9d88baabcd72700a23e6ce--Alfred_5.1.1_2138.dmg
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/alfred/.metadata/5.1,2134/20230428155442.423/Casks/alfred.json
==> Uninstalling Cask alfred
==> Uninstalling artifacts
==> 3 artifacts defined
#<Cask::ArtifactSet: {#<Cask::Artifact::Uninstall:0x00000001060bd4f0 @cask=#<Cask alfred>, @dsl_args=[{:login_item=>"Alfred5", :quit=>"com.runningwithcrayons.Alfred"}], @directives={:login_item=>"Alfred5", :quit=>"com.runningwithcrayons.Alfred", :signal=>[]}>, #<Cask::Artifact::App:0x00000001060bcc58 @cask=#<Cask alfred>, @dsl_args=["Alfred 5.app", {}], @source_string="Alfred 5.app", @target_string="">, #<Cask::Artifact::Zap:0x00000001060bc0a0 @cask=#<Cask alfred>, @dsl_args=[{:trash=>["~/Library/Application Support/Alfred", "~/Library/Caches/com.runningwithcrayons.Alfred", "~/Library/Cookies/com.runningwithcrayons.Alfred.binarycookies", "~/Library/Preferences/com.runningwithcrayons.Alfred.plist", "~/Library/Preferences/com.runningwithcrayons.Alfred-Preferences.plist", "~/Library/Saved Application State/com.runningwithcrayons.Alfred-Preferences.savedState"]}], @directives={:trash=>["~/Library/Application Support/Alfred", "~/Library/Caches/com.runningwithcrayons.Alfred", "~/Library/Cookies/com.runningwithcrayons.Alfred.binarycookies", "~/Library/Preferences/com.runningwithcrayons.Alfred.plist", "~/Library/Preferences/com.runningwithcrayons.Alfred-Preferences.plist", "~/Library/Saved Application State/com.runningwithcrayons.Alfred-Preferences.savedState"], :signal=>[]}>}>
==> Uninstalling artifact of class Cask::Artifact::Uninstall
/usr/bin/env osascript -l JavaScript -e \'use\ strict\'\;'
''
'ObjC.import\(\'stdlib\'\)'
''
'function\ run\(argv\)\ \{'
'\ \ try\ \{'
'\ \ \ \ var\ app\ =\ Application\(argv\[0\]\)'
'\ \ \ \ if\ \(app.running\(\)\)\ \{'
'\ \ \ \ \ \ \$.exit\(0\)'
'\ \ \ \ \}'
'\ \ \}\ catch\ \(err\)\ \{\ \}'
''
'\ \ \$.exit\(1\)'
'\}'
' com.runningwithcrayons.Alfred
==> Post-uninstalling artifact of class Cask::Artifact::Uninstall
==> Uninstalling artifact of class Cask::Artifact::App
Warning: It seems there is already an App at '/opt/homebrew/Caskroom/alfred/5.1,2134/Alfred 5.app'; overwriting.
==> Removing App '/opt/homebrew/Caskroom/alfred/5.1,2134/Alfred 5.app'
==> Backing App 'Alfred 5.app' up to '/opt/homebrew/Caskroom/alfred/5.1,2134/Alfred 5.app'
/usr/bin/env /bin/cp -pR /Applications/Alfred\ 5.app /opt/homebrew/Caskroom/alfred/5.1,2134/Alfred\ 5.app
==> Removing App '/Applications/Alfred 5.app'
Error: Operation not permitted @ rb_sysopen - /Applications/Alfred 5.app/.homebrew-write-test
/opt/homebrew/Library/Homebrew/cask/quarantine.rb:217:in `write'
/opt/homebrew/Library/Homebrew/cask/quarantine.rb:217:in `app_management_permissions_granted?'
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:156:in `delete'
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:147:in `move_back'
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:23:in `uninstall_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:466:in `block in uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:463:in `uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:401:in `uninstall'
/opt/homebrew/Library/Homebrew/cask/installer.rb:153:in `uninstall_existing_cask'
/opt/homebrew/Library/Homebrew/cask/installer.rb:105:in `install'
/opt/homebrew/Library/Homebrew/cask/reinstall.rb:31:in `block in reinstall_casks'
/opt/homebrew/Library/Homebrew/cask/reinstall.rb:22:in `each'
/opt/homebrew/Library/Homebrew/cask/reinstall.rb:22:in `reinstall_casks'
/opt/homebrew/Library/Homebrew/cmd/reinstall.rb:170:in `reinstall'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor                  
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the rhyeal/aws-rotate-iam-keys tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/rhyeal/homebrew-aws-rotate-iam-keys/Formula/aws-rotate-iam-keys.rb:53

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Found Ruby file outside rhyeal/aws-rotate-iam-keys tap formula directory.
(/opt/homebrew/Library/Taps/rhyeal/homebrew-aws-rotate-iam-keys/Formula):
  /opt/homebrew/Library/Taps/rhyeal/homebrew-aws-rotate-iam-keys/aws-rotate-iam-keys.template.rb
```
```
❯ brew config                                           
HOMEBREW_VERSION: 4.0.20-2-ga380aed
ORIGIN: https://github.com/Homebrew/brew
HEAD: a380aed887f40cbe29953269798d510502bf177d
Last commit: 21 hours ago
Core tap JSON: 31 May 13:28 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
❯ brew tap   
homebrew/cask-fonts
homebrew/services
jorgelbg/tap
rhyeal/aws-rotate-iam-keys
```

**Comment by singularitti** [comment]
I have the same issue:

```
Error: Operation not permitted @ rb_sysopen - /Applications/1Password.app/.homebrew-write-test
```

and it seems to be fixed after I gave the terminal full disk access. I wonder if it will cause any problem in my system, or it is just a warning that can be ignored @Volatus? Thank you!

**Comment by Volatus** [comment]
> I have the same issue:
> 
> 
> 
> ```
> 
> Error: Operation not permitted @ rb_sysopen - /Applications/1Password.app/.homebrew-write-test
> 
> ```
> 
> 
> 
> And it seems to be fixed after I gave the terminal full disk access. I wonder if it will cause any problem in my system (e.g., I will lose some files when installing the aforementioned app), or if it is just a harmless warning that can be ignored @Volatus? Thank you!

Think it should largely be fine. It'd be more convenient if we could give access to specific directories but I don't think it's that big of a deal.

**Comment by orip** [comment]
An informative error message - pointing towards granting the terminal full disk access, or even to this discussion - could help

**Comment by JBYoshi** [comment]
There's supposed to be a catch on that but it might not be catching the correct error type.

**Comment by Volatus** [comment]
@singularitti and for everyone else experiencing problems, I'd suggest enabling `System Settings -> Privacy & Security -> App Management` for the terminal emulator instead of Full Disk Access, it's less permissions and should still resolve the issue until my PR is merged in.

**Comment by monomycelium** [comment]
> @singularitti and for everyone else experiencing problems, I'd suggest enabling `System Settings -> Privacy & Security -> App Management` for the terminal emulator instead of Full Disk Access, it's less permissions and should still resolve the issue until my PR is merged in.

That solved my problem; thanks!
