### ISSUE TITLE
Cannot install font-literata: BUG: config.c:129: kvi should not be set while parsing a config source

### ISSUE THREAD

**Issue by homocomputeris** [Homebrew/homebrew-cask#148499]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Cannot install font-literata:
```
brew install --force font-literata
==> Cloning https://github.com/google/fonts.git
Updating /Users/user/Library/Caches/Homebrew/Cask/font-literata--git-sparse
BUG: config.c:129: kvi should not be set while parsing a config source
Error: Download failed on Cask 'font-literata' with message: Failure while executing; `/usr/bin/env git fetch origin` was terminated by uncaught signal ABRT. Here's the output:
BUG: config.c:129: kvi should not be set while parsing a config source
```

### Command that failed

brew install --force font-literat

### Output of command with `--verbose --debug`

```shell
brew install --verbose --debug --force font-literata
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/git --version
==> Cloning https://github.com/google/fonts.git
/usr/bin/env git --git-dir /Users/user/Library/Caches/Homebrew/Cask/font-literata--git-sparse/.git status -s
Updating /Users/user/Library/Caches/Homebrew/Cask/font-literata--git-sparse
/usr/bin/env git config remote.origin.url https://github.com/google/fonts.git
/usr/bin/env git config remote.origin.fetch \+refs/heads/main:refs/remotes/origin/main
/usr/bin/env git config remote.origin.tagOpt --no-tags
/usr/bin/env git config advice.detachedHead false
/usr/bin/env git config core.fsmonitor false
/usr/bin/env git config origin.partialclonefilter blob:none
/usr/bin/env git config core.sparseCheckout true
/usr/bin/env git fetch origin
BUG: config.c:129: kvi should not be set while parsing a config source
Error: Download failed on Cask 'font-literata' with message: Failure while executing; `/usr/bin/env git fetch origin` was terminated by uncaught signal ABRT. Here's the output:
BUG: config.c:129: kvi should not be set while parsing a config source

/usr/local/Homebrew/Library/Homebrew/system_command.rb:313:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:59:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:38:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:26:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:161:in `command!'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:985:in `update_repo'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:878:in `update'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:205:in `fetch'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:51:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:172:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:104:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor
Your system is ready to brew.
brew doctor  4.31s user 3.07s system 83% cpu 8.818 total

brew config
HOMEBREW_VERSION: 4.0.20-20-ge9a1cd4
ORIGIN: https://github.com/Homebrew/brew
HEAD: e9a1cd41d78c7c99ccf415be24727756cfa3ec5f
Last commit: 14 hours ago
Core tap JSON: 04 Jun 21:59 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.41.0 => /usr/local/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
```

### Output of `brew tap`

```shell
brew tap
bell-sw/liberica
homebrew-ffmpeg/ffmpeg
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/services
```

**Comment by krehel** [comment]
While I don't have a direct answer for what is causing this (others please chime in), I was able to reproduce it by installing, uninstalling, and then attempting to re-install `font-literata`.  Same error as above when attempting re-install.

I was able to work around this issue by removing the existing directory from the install from `~/Library/Caches/Homebrew/Cask/font-literata--git-sparse`.  Install then worked.

Also note, being in that directory and simply issuing `git fetch origin` standalone outside of `brew` causes the same error.

**Comment by razvanazamfirei** [comment]
Thanks @homocomputeris and @krehel! This seems related to `git 2.41.0`. Will be looking into it some more.
