### ISSUE TITLE
jdownloader fails to install on M2 Apple Silicon

### ISSUE THREAD

**Issue by xavier7179** [Homebrew/homebrew-cask#148510]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

When installing jDownloader on Apple Silicon (M2) something is off and during the purging phase the execution throws: `env: /opt/homebrew/Caskroom/jdownloader/47853/JDownloader Installer.app/Contents/MacOS/JavaApplicationStub: Bad CPU type in executable`

### Command that failed

brew install  jdownloader

### Output of command with `--verbose --debug`

```shell
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.0.20\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --fail --location --remote-time --output /Users/username/Library/Caches/Homebrew/api/formula.jws.json --time-cond /Users/username/Library/Caches/Homebrew/api/formula.jws.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.0.20\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --fail --location --remote-time --output /Users/username/Library/Caches/Homebrew/api/cask.jws.json --time-cond /Users/username/Library/Caches/Homebrew/api/cask.jws.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading jdownloader
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.20\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/9c56b31a74e350d8b09ca41c5e8ddfee19cee727/Casks/jdownloader.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.20\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://raw.githubusercontent.com/Homebrew/homebrew-cask/9c56b31a74e350d8b09ca41c5e8ddfee19cee727/Casks/jdownloader.rb
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/9c56b31a74e350d8b09ca41c5e8ddfee19cee727/Casks/jdownloader.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.20\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --location --remote-time --output /Users/username/Library/Caches/Homebrew/downloads/c1b5a575a35e9ec4d86e3eac613fecf6762a8021e644bde0f256da41933887e9--jdownloader.rb.incomplete https://raw.githubusercontent.com/Homebrew/homebrew-cask/9c56b31a74e350d8b09ca41c5e8ddfee19cee727/Casks/jdownloader.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.20\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET --location --remote-time --output /Users/username/Library/Caches/Homebrew/downloads/c1b5a575a35e9ec4d86e3eac613fecf6762a8021e644bde0f256da41933887e9--jdownloader.rb.incomplete https://raw.githubusercontent.com/Homebrew/homebrew-cask/9c56b31a74e350d8b09ca41c5e8ddfee19cee727/Casks/jdownloader.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.20\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --fail --connect-timeout 15 --retry 3 --location --remote-time --output /Users/username/Library/Caches/Homebrew/downloads/c1b5a575a35e9ec4d86e3eac613fecf6762a8021e644bde0f256da41933887e9--jdownloader.rb.incomplete https://raw.githubusercontent.com/Homebrew/homebrew-cask/9c56b31a74e350d8b09ca41c5e8ddfee19cee727/Casks/jdownloader.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1034  100  1034    0     0  16487      0 --:--:-- --:--:-- --:--:-- 17525
==> Verifying checksum for 'c1b5a575a35e9ec4d86e3eac613fecf6762a8021e644bde0f256da41933887e9--jdownloader.rb'
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Mozilla/5.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10_12_3\)\ AppleWebKit/602.4.8\ \(KHTML,\ like\ Gecko\)\ Version/10.0.3\ Safari/602.4.8 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://installer.jdownloader.org/clean/JD2Setup.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Mozilla/5.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10_12_3\)\ AppleWebKit/602.4.8\ \(KHTML,\ like\ Gecko\)\ Version/10.0.3\ Safari/602.4.8 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://installer.jdownloader.org/clean/JD2Setup.dmg
==> Downloading https://installer.jdownloader.org/clean/JD2Setup.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Mozilla/5.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10_12_3\)\ AppleWebKit/602.4.8\ \(KHTML,\ like\ Gecko\)\ Version/10.0.3\ Safari/602.4.8 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --location --remote-time --output /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg.incomplete https://installer.jdownloader.org/clean/JD2Setup.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Mozilla/5.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10_12_3\)\ AppleWebKit/602.4.8\ \(KHTML,\ like\ Gecko\)\ Version/10.0.3\ Safari/602.4.8 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET --location --remote-time --output /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg.incomplete https://installer.jdownloader.org/clean/JD2Setup.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Mozilla/5.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10_12_3\)\ AppleWebKit/602.4.8\ \(KHTML,\ like\ Gecko\)\ Version/10.0.3\ Safari/602.4.8 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg.incomplete https://installer.jdownloader.org/clean/JD2Setup.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5454k  100 5454k    0     0  6441k      0 --:--:-- --:--:-- --:--:-- 6462k
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
==> /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg is not quarantined
==> Quarantining /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg https://installer.jdownloader.org/clean/JD2Setup.dmg https://jdownloader.org/
Warning: No checksum defined for cask 'jdownloader', skipping verification.
/usr/bin/env hdiutil imageinfo -format /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
==> Installing Cask jdownloader
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230605-3213-1fy15bh /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20230605-3213-eyh37.list -- /private/tmp/20230605-3213-p3cz25.bom
/usr/bin/env ditto --bom /private/tmp/20230605-3213-p3cz25.bom -- /private/tmp/d20230605-3213-1fy15bh/dmg.YMNFe1 /private/tmp/d20230605-3213-1md7pcz
/usr/bin/env diskutil info -plist /private/tmp/d20230605-3213-1fy15bh/dmg.YMNFe1
/usr/bin/env diskutil eject /private/tmp/d20230605-3213-1fy15bh/dmg.YMNFe1
/usr/bin/env cp -pR /private/tmp/d20230605-3213-1md7pcz/JDownloader\ Installer.app/. /opt/homebrew/Caskroom/jdownloader/47853/JDownloader\ Installer.app
==> Verifying Gatekeeper status of /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
==> /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg is quarantined
==> Propagating quarantine from /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg to /opt/homebrew/Caskroom/jdownloader/47853
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/username/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0381\;647d92e0\;\;FBCC5ED2-7E8B-42BB-A5E7-1CC5D73608AA
==> Creating metadata directory: /opt/homebrew/Caskroom/jdownloader/.metadata/47853/20230605074651.345
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/jdownloader/.metadata/47853/20230605074651.345/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::PreflightBlock
/usr/bin/env /opt/homebrew/Caskroom/jdownloader/47853/JDownloader\ Installer.app/Contents/MacOS/JavaApplicationStub -dir /Applications -q -Dinstall4j.suppressStdout=true -Dinstall4j.debug=false -VcreateDesktopLinkAction\$Boolean=false -VaddToDockAction\$Boolean=false
==> Purging files for version 47853 of Cask jdownloader
Error: Failure while executing; `/usr/bin/env /opt/homebrew/Caskroom/jdownloader/47853/JDownloader\ Installer.app/Contents/MacOS/JavaApplicationStub -dir /Applications -q -Dinstall4j.suppressStdout=true -Dinstall4j.debug=false -VcreateDesktopLinkAction\$Boolean=false -VaddToDockAction\$Boolean=false` exited with 126. Here's the output:
env: /opt/homebrew/Caskroom/jdownloader/47853/JDownloader Installer.app/Contents/MacOS/JavaApplicationStub: Bad CPU type in executable

/opt/homebrew/Library/Homebrew/system_command.rb:313:in `assert_success!'
/opt/homebrew/Library/Homebrew/system_command.rb:59:in `run!'
/opt/homebrew/Library/Homebrew/system_command.rb:34:in `run'
/opt/homebrew/Library/Homebrew/system_command.rb:38:in `run!'
/opt/homebrew/Library/Homebrew/cask/dsl/base.rb:23:in `system_command'
/Users/username/Library/Caches/Homebrew/api-source/Homebrew/homebrew-cask/9c56b31a74e350d8b09ca41c5e8ddfee19cee727/Cask/jdownloader.rb:19:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:49:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:49:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:28:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:234:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:227:in `install_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:115:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor:
Your system is ready to brew.

brew config:
HOMEBREW_VERSION: 4.0.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8917acac9560f8e2846eedc4181470f0345f6db8
Last commit: 6 days ago
Core tap JSON: 05 Jun 07:46 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.UjpVBjHElh/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3
Rosetta 2: false
```

### Output of `brew tap`

```shell
adoptopenjdk/openjdk
homebrew/bundle
homebrew/cask-versions
```

**Comment by miccal** [comment]
See https://github.com/Homebrew/homebrew-cask/issues/60626.

**Comment by xavier7179** [comment]
So If get the suggestion, basically, there is no way of installing jDownloader as a cask, right?
