### ISSUE TITLE
Fail to install genymotion on Apple M1 device due to virtualbox dependency

### ISSUE THREAD

**Issue by xiazeyu** [Homebrew/homebrew-cask#148776]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The [Latest update of Genymotion](https://www.genymotion.com/blog/genymotion-desktop-3-4-is-released/) has built-in Apple Silicon support under Rosetta 2, and don't need to install virtualbox as a dependency. The cask however, is treating virtualbox as the dependency under all architectures.

Current this package can only be install by `brew install --cask genymotion --skip-cask-deps`. And it is confirmed on my Apple MacBook Pro with M2 Pro chip to run successfully.

```shell
==> Downloading https://dl.genymotion.com/releases/genymotion-3.4.0/genymotion-3.4
Already downloaded: /Users/zeyuxia/Library/Caches/Homebrew/downloads/21ccc4f283f54bc60b03daa5e1997d21934720449828f28be766a5a6bb49753c--genymotion-3.4.0.dmg
==> Installing dependencies: virtualbox
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/7d30f5e70
Already downloaded: /Users/zeyuxia/Library/Caches/Homebrew/downloads/c666a323c1da9052c751218d7cac52b7df0170f46ae51258a53607ec6cf84688--virtualbox.rb
==> Downloading https://download.virtualbox.org/virtualbox/7.0.8/VirtualBox-7.0.8-
Already downloaded: /Users/zeyuxia/Library/Caches/Homebrew/downloads/08af93128d6ff80757a49e5520255f42ccb578aae32e9528295abe42e7a7a431--VirtualBox-7.0.8-156879-OSX.dmg
Error: Cask virtualbox depends on hardware architecture being one of [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}.
``` 

### Command that failed

brew install --cask genymotion --force

### Output of command with `--verbose --debug`

```shell
❯ brew reinstall --cask genymotion --verbose --debug

/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading genymotion
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://dl.genymotion.com/releases/genymotion-3.4.0/genymotion-3.4.0.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.21-10-g83db703\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://dl.genymotion.com/releases/genymotion-3.4.0/genymotion-3.4.0.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.21-10-g83db703\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://dl.genymotion.com/releases/genymotion-3.4.0/genymotion-3.4.0.dmg
Already downloaded: /Users/zeyuxia/Library/Caches/Homebrew/downloads/21ccc4f283f54bc60b03daa5e1997d21934720449828f28be766a5a6bb49753c--genymotion-3.4.0.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/zeyuxia/Library/Caches/Homebrew/downloads/21ccc4f283f54bc60b03daa5e1997d21934720449828f28be766a5a6bb49753c--genymotion-3.4.0.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/zeyuxia/Library/Caches/Homebrew/downloads/21ccc4f283f54bc60b03daa5e1997d21934720449828f28be766a5a6bb49753c--genymotion-3.4.0.dmg
==> /Users/zeyuxia/Library/Caches/Homebrew/downloads/21ccc4f283f54bc60b03daa5e1997d21934720449828f28be766a5a6bb49753c--genymotion-3.4.0.dmg is quarantined
==> Verifying checksum for '21ccc4f283f54bc60b03daa5e1997d21934720449828f28be766a5a6bb49753c--genymotion-3.4.0.dmg'
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading virtualbox
/usr/bin/env tar --list --file /Users/zeyuxia/Library/Caches/Homebrew/downloads/21ccc4f283f54bc60b03daa5e1997d21934720449828f28be766a5a6bb49753c--genymotion-3.4.0.dmg
/usr/bin/env hdiutil imageinfo -format /Users/zeyuxia/Library/Caches/Homebrew/downloads/21ccc4f283f54bc60b03daa5e1997d21934720449828f28be766a5a6bb49753c--genymotion-3.4.0.dmg
==> Installing dependencies: virtualbox
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/7d30f5e70bf6b649f3c9b69f2e9dcaac19dc4a32/Casks/virtualbox.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.21-10-g83db703\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/7d30f5e70bf6b649f3c9b69f2e9dcaac19dc4a32/Casks/virtualbox.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.21-10-g83db703\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://raw.githubusercontent.com/Homebrew/homebrew-cask/7d30f5e70bf6b649f3c9b69f2e9dcaac19dc4a32/Casks/virtualbox.rb
Already downloaded: /Users/zeyuxia/Library/Caches/Homebrew/downloads/c666a323c1da9052c751218d7cac52b7df0170f46ae51258a53607ec6cf84688--virtualbox.rb
==> Verifying checksum for 'c666a323c1da9052c751218d7cac52b7df0170f46ae51258a53607ec6cf84688--virtualbox.rb'
==> Downloading https://download.virtualbox.org/virtualbox/7.0.8/VirtualBox-7.0.8-156879-OSX.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.21-10-g83db703\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://download.virtualbox.org/virtualbox/7.0.8/VirtualBox-7.0.8-156879-OSX.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.21-10-g83db703\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://download.virtualbox.org/virtualbox/7.0.8/VirtualBox-7.0.8-156879-OSX.dmg
Already downloaded: /Users/zeyuxia/Library/Caches/Homebrew/downloads/08af93128d6ff80757a49e5520255f42ccb578aae32e9528295abe42e7a7a431--VirtualBox-7.0.8-156879-OSX.dmg
==> Verifying Gatekeeper status of /Users/zeyuxia/Library/Caches/Homebrew/downloads/08af93128d6ff80757a49e5520255f42ccb578aae32e9528295abe42e7a7a431--VirtualBox-7.0.8-156879-OSX.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/zeyuxia/Library/Caches/Homebrew/downloads/08af93128d6ff80757a49e5520255f42ccb578aae32e9528295abe42e7a7a431--VirtualBox-7.0.8-156879-OSX.dmg
==> /Users/zeyuxia/Library/Caches/Homebrew/downloads/08af93128d6ff80757a49e5520255f42ccb578aae32e9528295abe42e7a7a431--VirtualBox-7.0.8-156879-OSX.dmg is quarantined
==> Verifying checksum for '08af93128d6ff80757a49e5520255f42ccb578aae32e9528295abe42e7a7a431--VirtualBox-7.0.8-156879-OSX.dmg'
Error: Cask virtualbox depends on hardware architecture being one of [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}.
/opt/homebrew/Library/Homebrew/cask/installer.rb:288:in `arch_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:268:in `satisfy_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:72:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:104:in `install'
/opt/homebrew/Library/Homebrew/cask/installer.rb:352:in `block in cask_and_formula_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:338:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:338:in `cask_and_formula_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:269:in `satisfy_dependencies'
/opt/homebrew/Library/Homebrew/cask/installer.rb:72:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:104:in `install'
/opt/homebrew/Library/Homebrew/cask/reinstall.rb:31:in `block in reinstall_casks'
/opt/homebrew/Library/Homebrew/cask/reinstall.rb:22:in `each'
/opt/homebrew/Library/Homebrew/cask/reinstall.rb:22:in `reinstall_casks'
/opt/homebrew/Library/Homebrew/cmd/reinstall.rb:170:in `reinstall'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Your system is ready to brew.

❯ brew config
HOMEBREW_VERSION: 4.0.21-10-g83db703
ORIGIN: https://github.com/Homebrew/brew
HEAD: 83db7039efd74f9ae8f6ecdcdebf671c09941bb8
Last commit: 23 hours ago
Core tap JSON: 08 Jun 12:06 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.MGgg95xlqy/org.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

### Output of `brew tap`

```shell
❯ brew tap
homebrew/bundle
homebrew/cask-fonts
homebrew/services
sunnyyoung/repo
```

**Comment by razvanazamfirei** [comment]
@xiazeyu, just to clarify, does this require VirtualBox for the intel distribution?

**Comment by xiazeyu** [comment]
> @xiazeyu, just to clarify, does this require VirtualBox for the intel distribution?

I think it still requires. I'm borrowing my friend's Intel Mac to have a test with that.

**Comment by xiazeyu** [comment]
@razvanazamfirei Unable to test. According to their [Requirement](https://www.genymotion.com/download/)

System Requirements
macOS 12 (Monterey) and above
Intel x86_64 CPU
Apple Silicon CPU (Mac M1/M2)
VirtualBox 7.0.8 (optional - not available for mac M1/M2)

It is a optional dependency for Intel Mac
