### ISSUE TITLE
BloodHound 4.3.1 sha256 hash mismatch

### ISSUE THREAD

**Issue by Esonhugh** [Homebrew/homebrew-cask#149129]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I Got error.

```
==> Downloading https://github.com/BloodHoundAD/BloodHound/releases/download/v4.3.1/BloodHound-darwin-arm64.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/56452110/cfc94d70-5f6e-4df5-8a45-22c463a73797?X-Amz-Algo
################################################################################################################################################### 100.0%
Error: SHA256 mismatch
Expected: 48803fdefd4d4db8cf6d7e41004ddf2827022a8f848c3ce631ef06a4620c58da
  Actual: 86e37a3b78826bd1c9ebd6b6c65eab9e81261af8f18abe8fda8311ce500e4316
    File: /Users/esonhugh/Library/Caches/Homebrew/downloads/b0c2dd0d406d7510b40611526b5acaf2407320c5f3b235dc376e8fab6d8c23a6--BloodHound-darwin-arm64.zip
To retry an incomplete download, remove the file above.
```

### Command that failed

brew reinstall bloodhound

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading bloodhound
==> Cask::Installer#install
==> Printing caveats
==> Caveats
According to https://github.com/BloodHoundAD/BloodHound/issues/504
this app will not work with quarantine attributes.

==> Cask::Installer#fetch
==> Downloading https://github.com/BloodHoundAD/BloodHound/releases/download/v4.3.1/BloodHound-darwin-arm64.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.22-6-gf71294d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/BloodHoundAD/BloodHound/releases/download/v4.3.1/BloodHound-darwin-arm64.zip
Already downloaded: /Users/esonhugh/Library/Caches/Homebrew/downloads/b0c2dd0d406d7510b40611526b5acaf2407320c5f3b235dc376e8fab6d8c23a6--BloodHound-darwin-arm64.zip
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/esonhugh/Library/Caches/Homebrew/downloads/b0c2dd0d406d7510b40611526b5acaf2407320c5f3b235dc376e8fab6d8c23a6--BloodHound-darwin-arm64.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/esonhugh/Library/Caches/Homebrew/downloads/b0c2dd0d406d7510b40611526b5acaf2407320c5f3b235dc376e8fab6d8c23a6--BloodHound-darwin-arm64.zip
==> /Users/esonhugh/Library/Caches/Homebrew/downloads/b0c2dd0d406d7510b40611526b5acaf2407320c5f3b235dc376e8fab6d8c23a6--BloodHound-darwin-arm64.zip is quarantined
==> Verifying checksum for 'b0c2dd0d406d7510b40611526b5acaf2407320c5f3b235dc376e8fab6d8c23a6--BloodHound-darwin-arm64.zip'
Error: SHA256 mismatch
Expected: 48803fdefd4d4db8cf6d7e41004ddf2827022a8f848c3ce631ef06a4620c58da
  Actual: 86e37a3b78826bd1c9ebd6b6c65eab9e81261af8f18abe8fda8311ce500e4316
    File: /Users/esonhugh/Library/Caches/Homebrew/downloads/b0c2dd0d406d7510b40611526b5acaf2407320c5f3b235dc376e8fab6d8c23a6--BloodHound-darwin-arm64.zip
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:288:in `verify_checksum'
/opt/homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:81:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:60:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:172:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:104:in `install'
/opt/homebrew/Library/Homebrew/cask/reinstall.rb:31:in `block in reinstall_casks'
/opt/homebrew/Library/Homebrew/cask/reinstall.rb:22:in `each'
/opt/homebrew/Library/Homebrew/cask/reinstall.rb:22:in `reinstall_casks'
/opt/homebrew/Library/Homebrew/cmd/reinstall.rb:170:in `reinstall'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  php@7.4

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  coreutils
  pygments
  numpy
  pillow
  pyyaml
  python-typing-extensions
  nuclei
HOMEBREW_VERSION: 4.0.22-6-gf71294d
ORIGIN: https://github.com/Homebrew/brew
HEAD: f71294d483e1ce9920fd10d8169b1419c0ba41fb
Last commit: 17 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d9de1016854f4eb707df978d42c7553f683babc4
Core tap last commit: 20 minutes ago
Core tap branch: master
Core tap JSON: 14 Jun 09:05 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.V0HMjv8H1m/org.xquartz:0
HOMEBREW_EDITOR: lvim
HOMEBREW_MAKE_JOBS: 10
all_proxy: socks5://127.0.0.1:7890
http_proxy: http://127.0.0.1:7890
https_proxy: http://127.0.0.1:7890
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
caffix/amass
datawire/blackbird
gcenx/wine
hashicorp/tap
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
instantclienttap/instantclient
jandedobbeleer/oh-my-posh
ktr0731/evans
kubeshark/kubeshark
tencentcloud/tccli
tonarino/innernet
```

**Comment by Esonhugh** [comment]
86e37a3b78826bd1c9ebd6b6c65eab9e81261af8f18abe8fda8311ce500e4316  BloodHound-darwin-arm64.zip
1276dd8636403e98d7c3611dc652d53d92db77255414be4ddd5e572051249019  BloodHound-linux-arm64.zip
5ada70505b8a57566ca4cd20445cb38967d9884316537c26ef81e9ae125b29a6  BloodHound-win32-arm64.zip
no hash match the 
48803fdefd4d4db8cf6d7e41004ddf2827022a8f848c3ce631ef06a4620c58da

**Comment by razvanazamfirei** [comment]
You confirmed the following was true and yet this is a checksum issue:
```
I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.
```

**Comment by Esonhugh** [comment]
> You confirmed the following was true and yet this is a checksum issue:
> 
> ```
> I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.
> ```

Error made it. But it is checksum problem.

**Comment by razvanazamfirei** [comment]
https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match

**Comment by Esonhugh** [comment]
> https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match

Take it. Thank u.
