### ISSUE TITLE
Brew pin not working for the vmware-fusion cask

### ISSUE THREAD

**Issue by edpichler** [Homebrew/homebrew-cask#150045]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

In the image we can see the commands and the versions I have:

![image](https://github.com/Homebrew/homebrew-cask/assets/358696/e3b576a5-0df4-4a9d-a4c1-8ae2da548b54)

### Command that failed

brew pin

### Output of command with `--verbose --debug`

```shell
➜  ~ brew pin vmware-fusion                                                                                                                                
Error: No available formula with the name "vmware-fusion".
➜  ~ brew pin vmware-fusion --verbose --debug                                                                                                              
Error: No available formula with the name "vmware-fusion".
/opt/homebrew/Library/Homebrew/formulary.rb:633:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:722:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:373:in `resolve'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:210:in `resolve_formula'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:128:in `block in load_formula_or_cask'
/opt/homebrew/Library/Homebrew/api.rb:191:in `with_no_api_env_if_needed'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:118:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:83:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:216:in `to_resolved_formulae'
/opt/homebrew/Library/Homebrew/cmd/pin.rb:25:in `pin'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>

```
```


### Output of `brew doctor` and `brew config`

```shell
➜  ~ brew doctor                                                                                                                                          
Your system is ready to brew.


➜  ~ brew config                                                                                                                                           
HOMEBREW_VERSION: 4.0.26-2-gc5cbe64
ORIGIN: https://github.com/Homebrew/brew
HEAD: c5cbe6406b8b9d040c5d1850b5f041af4ddef83c
Last commit: 16 hours ago
Core tap JSON: 28 Jun 08:45 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```
```


### Output of `brew tap`

```shell
➜  ~ brew tap                                                                                                                                             
browsh-org/browsh
graalvm/tap
homebrew/bundle
mvndaemon/mvnd
```
```

**Comment by SMillerDev** [comment]
That is correct, `brew pin` only works on formula, as `brew pin --help` will tell you

**Comment by edpichler** [comment]
> That is correct, `brew pin` only works on formula, as `brew pin --help` will tell you

@SMillerDev Is it a technical limitation or a deliberate decision?

**Comment by SMillerDev** [comment]
I'm guessing nobody bothered implementing it.
