### ISSUE TITLE
curl issue on forticlient and forticlient-vpn

### ISSUE THREAD

**Issue by chung1905** [Homebrew/homebrew-cask#150388]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I'm using MacOS 12.0.1

Issue happens with `forticlient` and `forticlient-vpn`, curl can't download the dmg file, the link is still working with browser.

```
% brew install --cask forticlient-vpn
==> Downloading https://formulae.brew.sh/api/cask.jws.json
#=O#-   #      #
Error: Download failed on Cask 'forticlient-vpn' with message: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.26\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.0.1\)\ curl/7.77.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNOnlineInstaller_7.0.dmg` exited with 52. Here's the output:
curl: (52) Empty reply from server
```

### Command that failed

brew install --cask forticlient-vpn

### Output of command with `--verbose --debug`

```shell
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.0.26\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.0.1\)\ curl/7.77.0 --header Accept-Language:\ en --fail --remote-time --output /Users/chung/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/chung/Library/Caches/Homebrew/api/cask.jws.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading forticlient-vpn
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.26\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.0.1\)\ curl/7.77.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNOnlineInstaller_7.0.dmg
Error: Download failed on Cask 'forticlient-vpn' with message: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.26\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.0.1\)\ curl/7.77.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNOnlineInstaller_7.0.dmg` exited with 52. Here's the output:
curl: (52) Empty reply from server

/opt/homebrew/Library/Homebrew/system_command.rb:313:in `assert_success!'
/opt/homebrew/Library/Homebrew/utils/curl.rb:232:in `block in curl_headers'
/opt/homebrew/Library/Homebrew/utils/curl.rb:210:in `each'
/opt/homebrew/Library/Homebrew/utils/curl.rb:210:in `curl_headers'
/opt/homebrew/Library/Homebrew/download_strategy.rb:483:in `resolve_url_basename_time_file_size'
/opt/homebrew/Library/Homebrew/download_strategy.rb:475:in `resolved_url_and_basename'
/opt/homebrew/Library/Homebrew/download_strategy.rb:323:in `resolved_basename'
/opt/homebrew/Library/Homebrew/download_strategy.rb:307:in `cached_location'
/opt/homebrew/Library/Homebrew/download_strategy.rb:280:in `temporary_path'
/opt/homebrew/Library/Homebrew/download_strategy.rb:404:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:51:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:172:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:104:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 14.2.


% brew config
HOMEBREW_VERSION: 4.0.26
ORIGIN: https://github.com/Homebrew/brew
HEAD: eff45ef570f265e226f14ce91da72d7a6e7d516a
Last commit: 7 days ago
Core tap JSON: 04 Jul 13:34 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
N/A
```

**Comment by miccal** [comment]
For `forticlient`:
```
|-> curl -I https://links.fortinet.com/forticlient/mac/fabricagent
HTTP/2 302 
date: Tue, 04 Jul 2023 18:54:45 GMT
set-cookie: PHPSESSID=003d72cea37905a49f011d112da539b3; path=/;Max-Age=60000; HttpOnly
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
content-type: text/html; charset=UTF-8
x-envoy-upstream-service-time: 191
x-storage: default
x-retries: 0
location: https://filestore.fortinet.com/forticlient/FortiClient_OnlineInstaller.dmg
age: 0
x-cache: MISS
x-cache-hits: 0
x-cache-ttl: 120.000
server: envoy
set-cookie: cookiesession1=678A3E4DB20331E218
```
while for `forticlient-vpn`:
```
|-> curl -I https://links.fortinet.com/forticlient/mac/vpnagent
HTTP/2 302 
date: Tue, 04 Jul 2023 18:53:48 GMT
set-cookie: PHPSESSID=4bed3aefa0d0fb6456a8db7fec2cdcb8; path=/;Max-Age=60000; HttpOnly
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
content-type: text/html; charset=UTF-8
x-envoy-upstream-service-time: 188
x-storage: default
x-retries: 0
location: https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNOnlineInstaller_7.0.dmg
age: 0
x-cache: MISS
x-cache-hits: 0
x-cache-ttl: 120.000
server: envoy
set-cookie: cookiesession1=678A3E4DCDF3704E3CF6B23F8A94CA38;Expires=Wed, 03 Jul 2024 18:53:48 GMT;Path=/;HttpOnly
strict-transport-security: max-age=15552000
```
Note that the `set-cookie: PHPSESSID=` values constantly change, meaning the we cannot `curl` a consistent `url`, so these two Cask may have to be removed.

**Comment by bevanjkay** [comment]
I tested these yesterday and the URL was not working when accessed from upstream's website.

Are you able to download the files directly from the website?

**Comment by erwindosianipar** [comment]
```
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.0.27\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3\)\ curl/7.87.0 --header Accept-Language:\ en --fail --remote-time --output /Users/erwindosianipar/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/erwindosianipar/Library/Caches/Homebrew/api/cask.jws.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading forticlient
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/ad08964ce3b5f90e60f5339c3b3dfe87d6a883ba/Casks/forticlient.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.27\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/ad08964ce3b5f90e60f5339c3b3dfe87d6a883ba/Casks/forticlient.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.27\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://raw.githubusercontent.com/Homebrew/homebrew-cask/ad08964ce3b5f90e60f5339c3b3dfe87d6a883ba/Casks/forticlient.rb
Already downloaded: /Users/erwindosianipar/Library/Caches/Homebrew/downloads/a9ad9e01b43dd19b17cd6450df03a07432d7c6e34c1aa82c1ac55bdf65585e80--forticlient.rb
==> Verifying checksum for 'a9ad9e01b43dd19b17cd6450df03a07432d7c6e34c1aa82c1ac55bdf65585e80--forticlient.rb'
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.27\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://filestore.fortinet.com/forticlient/downloads/FortiClient_7.0.0.22_macosx.dmg
Error: Download failed on Cask 'forticlient' with message: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.27\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://filestore.fortinet.com/forticlient/downloads/FortiClient_7.0.0.22_macosx.dmg` exited with 52. Here's the output:
curl: (52) Empty reply from server

/opt/homebrew/Library/Homebrew/system_command.rb:313:in `assert_success!'
/opt/homebrew/Library/Homebrew/utils/curl.rb:232:in `block in curl_headers'
/opt/homebrew/Library/Homebrew/utils/curl.rb:210:in `each'
/opt/homebrew/Library/Homebrew/utils/curl.rb:210:in `curl_headers'
/opt/homebrew/Library/Homebrew/download_strategy.rb:483:in `resolve_url_basename_time_file_size'
/opt/homebrew/Library/Homebrew/download_strategy.rb:475:in `resolved_url_and_basename'
/opt/homebrew/Library/Homebrew/download_strategy.rb:323:in `resolved_basename'
/opt/homebrew/Library/Homebrew/download_strategy.rb:307:in `cached_location'
/opt/homebrew/Library/Homebrew/download_strategy.rb:280:in `temporary_path'
/opt/homebrew/Library/Homebrew/download_strategy.rb:404:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:51:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:172:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:104:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by bevanjkay** [comment]
Given that these are both `installer manual` casks there is not great benefit for them being managed within Homebrew, so it may be best to remove them at this stage.
The challenge here is that the website is setting cookies to enable the download that are not compatible with the `curl` setup within Homebrew.
