### ISSUE TITLE
Error: SHA256 mismatch when installing android-platform-tools r34.0.4

### ISSUE THREAD

**Issue by aircraft-cerier** [Homebrew/homebrew-cask#151464]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Hi,

I'm running:
`brew install android-platform-tools 
`The output is:

```
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://dl.google.com/android/repository/platform-tools_r34.0.4-darwin.zip
############################################################################################### 100.0%
Error: SHA256 mismatch
Expected: bd09b834c150181a383deba63e157e9a53a6eb5a9cf4849b2b79dd89d0a2ddf1
  Actual: c60d9ee0acade673b649543b2d53c632ba54f9ca083ed612176105117fa16102
    File: /Users/brcerier/Library/Caches/Homebrew/downloads/9b8e257fff105a69876e9b1fd1ce420143d0bf4001e48cdbde5fbd9d848bdad9--platform-tools_r34.0.4-darwin.zip
To retry an incomplete download, remove the file above.
```

Also get similar error with this command after running the remove command on the file:

`brew install --cask android-platform-tools 
`
Output:

```
==> Downloading https://dl.google.com/android/repository/platform-tools_r34.0.4-darwin.zip
############################################################################################### 100.0%
Error: SHA256 mismatch
Expected: bd09b834c150181a383deba63e157e9a53a6eb5a9cf4849b2b79dd89d0a2ddf1
  Actual: c60d9ee0acade673b649543b2d53c632ba54f9ca083ed612176105117fa16102
    File: /Users/brcerier/Library/Caches/Homebrew/downloads/9b8e257fff105a69876e9b1fd1ce420143d0bf4001e48cdbde5fbd9d848bdad9--platform-tools_r34.0.4-darwin.zip
To retry an incomplete download, remove the file above.

```

### Command that failed

`brew install --cask android-platform-tools
`
### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading android-platform-tools
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.0-15-g5226cd4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://dl.google.com/android/repository/platform-tools_r34.0.4-darwin.zip
==> Downloading https://dl.google.com/android/repository/platform-tools_r34.0.4-darwin.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.0-15-g5226cd4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/brcerier/Library/Caches/Homebrew/downloads/9b8e257fff105a69876e9b1fd1ce420143d0bf4001e48cdbde5fbd9d848bdad9--platform-tools_r34.0.4-darwin.zip.incomplete --location https://dl.google.com/android/repository/platform-tools_r34.0.4-darwin.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.6M  100 10.6M    0     0  19.5M      0 --:--:-- --:--:-- --:--:-- 19.7M
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/brcerier/Library/Caches/Homebrew/downloads/9b8e257fff105a69876e9b1fd1ce420143d0bf4001e48cdbde5fbd9d848bdad9--platform-tools_r34.0.4-darwin.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/brcerier/Library/Caches/Homebrew/downloads/9b8e257fff105a69876e9b1fd1ce420143d0bf4001e48cdbde5fbd9d848bdad9--platform-tools_r34.0.4-darwin.zip
==> /Users/brcerier/Library/Caches/Homebrew/downloads/9b8e257fff105a69876e9b1fd1ce420143d0bf4001e48cdbde5fbd9d848bdad9--platform-tools_r34.0.4-darwin.zip is not quarantined
==> Quarantining /Users/brcerier/Library/Caches/Homebrew/downloads/9b8e257fff105a69876e9b1fd1ce420143d0bf4001e48cdbde5fbd9d848bdad9--platform-tools_r34.0.4-darwin.zip
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/brcerier/Library/Caches/Homebrew/downloads/9b8e257fff105a69876e9b1fd1ce420143d0bf4001e48cdbde5fbd9d848bdad9--platform-tools_r34.0.4-darwin.zip https://dl.google.com/android/repository/platform-tools_r34.0.4-darwin.zip https://developer.android.com/studio/releases/platform-tools
==> Verifying checksum for '9b8e257fff105a69876e9b1fd1ce420143d0bf4001e48cdbde5fbd9d848bdad9--platform-tools_r34.0.4-darwin.zip'
Error: SHA256 mismatch
Expected: bd09b834c150181a383deba63e157e9a53a6eb5a9cf4849b2b79dd89d0a2ddf1
  Actual: c60d9ee0acade673b649543b2d53c632ba54f9ca083ed612176105117fa16102
    File: /Users/brcerier/Library/Caches/Homebrew/downloads/9b8e257fff105a69876e9b1fd1ce420143d0bf4001e48cdbde5fbd9d848bdad9--platform-tools_r34.0.4-darwin.zip
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:288:in `verify_checksum'
/opt/homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:81:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:60:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:172:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:104:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:240:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:231:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:231:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.


HOMEBREW_VERSION: 4.1.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ac93842f8d13913f462aedb246cfacd08d6b7f05
Last commit: 2 days ago
Core tap JSON: 21 Jul 21:09 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.2 => /Applications/Xcode15.0beta4.app/Contents/Developer/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 15.0.0.0.1.1688827124
Xcode: 15.0 => /Applications/Xcode15.0beta4.app/Contents/Developer
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/cask-fonts
homebrew/services
```

**Comment by osalbahr** [comment]
> I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

To me, it looks like this is a "checksum does not match" error.
