### ISSUE TITLE
Unexpected SHA mismatch for p4v cask

### ISSUE THREAD

**Issue by dasizeman** [Homebrew/homebrew-cask#151462]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

This is actually a "checksum does not match issue", but the behavior is fishy.

When I run the cask install for P4V with brew, I get a file that does not match hashes. I get a file with the same hash when I directly `wget` the dmg file as well from the same URL that brew is using.

The hash I get in this case is
```
fba5813f43a9af3a9080611ec5bb0ad4713dc06360e005a4ee8c1d1b9e4ee4c7
```

However, when I download the same version manually from the browser here: https://www.perforce.com/downloads/helix-visual-client-p4v

with selections MacOS/macOS 10.14+ Universal (x64 and ARM64)/2023.2/2446649

then I get a dmg file with the hash that brew is expecting, ie
```
a837f5d46526603ff179630d371944cb4acfba1cada5458bf733ef3c9f7b71f6
```

So this is not as simple as "Perforce has updated their build in-place and the cask needs to be updated"

### Command that failed

brew install p4v

### Output of command with `--verbose --debug`

```shell
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.1.0-15-g5226cd4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --fail --remote-time --output /Users/dsizer/Library/Caches/Homebrew/api/formula.jws.json --location --time-cond /Users/dsizer/Library/Caches/Homebrew/api/formula.jws.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.1.0-15-g5226cd4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --fail --remote-time --output /Users/dsizer/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/dsizer/Library/Caches/Homebrew/api/cask.jws.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading p4v
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/7be98c9060ac9dd19f2c9b9b6074ae04aa3db6a4/Casks/p4v.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.0-15-g5226cd4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/7be98c9060ac9dd19f2c9b9b6074ae04aa3db6a4/Casks/p4v.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.0-15-g5226cd4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://raw.githubusercontent.com/Homebrew/homebrew-cask/7be98c9060ac9dd19f2c9b9b6074ae04aa3db6a4/Casks/p4v.rb
Already downloaded: /Users/dsizer/Library/Caches/Homebrew/downloads/4a31ddb4474611b3d87b3318c1919ef50063bbcf5bb7eefed77767fb96519759--p4v.rb
==> Verifying checksum for '4a31ddb4474611b3d87b3318c1919ef50063bbcf5bb7eefed77767fb96519759--p4v.rb'
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.0-15-g5226cd4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://www.perforce.com/downloads/perforce/r23.2/bin.macosx12u/P4V.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.0-15-g5226cd4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://www.perforce.com/downloads/perforce/r23.2/bin.macosx12u/P4V.dmg
==> Downloading https://www.perforce.com/downloads/perforce/r23.2/bin.macosx12u/P4V.dmg
==> Downloading from https://cdist2.perforce.com/perforce/r23.2/bin.macosx12u/P4V.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.0-15-g5226cd4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/dsizer/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg.incomplete --location https://cdist2.perforce.com/perforce/r23.2/bin.macosx12u/P4V.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  522M  100  522M    0     0  11.8M      0  0:00:44  0:00:44 --:--:-- 15.6M
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/dsizer/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/dsizer/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg
==> /Users/dsizer/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg is not quarantined
==> Quarantining /Users/dsizer/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/dsizer/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg https://www.perforce.com/downloads/perforce/r23.2/bin.macosx12u/P4V.dmg https://www.perforce.com/products/helix-core-apps/helix-visual-client-p4v
==> Verifying checksum for 'fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg'
Error: SHA256 mismatch
Expected: a837f5d46526603ff179630d371944cb4acfba1cada5458bf733ef3c9f7b71f6
  Actual: fba5813f43a9af3a9080611ec5bb0ad4713dc06360e005a4ee8c1d1b9e4ee4c7
    File: /Users/dsizer/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:288:in `verify_checksum'
/opt/homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:81:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:60:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:172:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:104:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:240:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:231:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:231:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

HOMEBREW_VERSION: 4.1.0-15-g5226cd4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5226cd434494991fae9da7eb6ab6a3095a16f563
Last commit: 84 minutes ago
Core tap JSON: 21 Jul 21:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: Solarized (light)
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/cask-fonts
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/151730

**Comment by gsong** [comment]
Still failing:

```
==> Upgrading 1 outdated package:
p4v 2023.2,2446649 -> 2023.2,2467475
==> Upgrading p4v
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/57af634e69e6b9e5
Already downloaded: /Users/george/Library/Caches/Homebrew/downloads/c80832f160bd6a902ba4540588fb142845a19c207fc2ce6240d77e5d58ca09d4--p4v.rb
==> Downloading https://www.perforce.com/downloads/perforce/r23.2/bin.macosx12u/P4V.dmg
Already downloaded: /Users/george/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg
==> Purging files for version 2023.2,2467475 of Cask p4v
Error: p4v: SHA256 mismatch
Expected: fba5813f43a9af3a9080611ec5bb0ad4713dc06360e005a4ee8c1d1b9e4ee4c7
  Actual: a837f5d46526603ff179630d371944cb4acfba1cada5458bf733ef3c9f7b71f6
```

**Comment by shikhanshu** [comment]
I noticed that if the downloads happen from `filehost.perforce.com` instead of `cdist2` (or other), the SHAs look good.
https://github.com/orgs/Homebrew/discussions/4686#discussioncomment-6628463
