### ISSUE TITLE
Error: p4v: SHA256 mismatch

### ISSUE THREAD

**Issue by manoj7shekhawat** [Homebrew/homebrew-cask#152002]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

p4v is not able to install due to SHA256 mismatch, details:

```
mshekhawat@mac-pro ~ % brew install p4v        
==> Upgrading 1 outdated package:
p4v 2023.2,2446649 -> 2023.2,2467475
==> Upgrading p4v
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/f4c88c67755b3711affef6a7cd00c39d3146e7a5/Casks/p4v.rb
Already downloaded: /Users/mshekhawat/Library/Caches/Homebrew/downloads/9c384c52808093dce9e39ed7b0537832964532a4550ae35a153a2e055f092f2b--p4v.rb
==> Downloading https://www.perforce.com/downloads/perforce/r23.2/bin.macosx12u/P4V.dmg
Already downloaded: /Users/mshekhawat/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg
==> Purging files for version 2023.2,2467475 of Cask p4v
Error: p4v: SHA256 mismatch
Expected: fba5813f43a9af3a9080611ec5bb0ad4713dc06360e005a4ee8c1d1b9e4ee4c7
  Actual: a837f5d46526603ff179630d371944cb4acfba1cada5458bf733ef3c9f7b71f6
    File: /Users/mshekhawat/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg
To retry an incomplete download, remove the file above.
```

I tried to delete the P4V.dmg and re-tired but without success

### Command that failed

brew install p4v

### Output of command with `--verbose --debug`

```shell
mshekhawat@mac-pro ~ % brew install p4v --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading p4v
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/p4v/.metadata/2023.2,2446649/20230611162909.794/Casks/p4v.rb
p4v 2023.2,2446649 -> 2023.2,2467475
==> Started upgrade process for Cask p4v
==> Upgrading p4v
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/f4c88c67755b3711affef6a7cd00c39d3146e7a5/Casks/p4v.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.2-33-gc531a35\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/f4c88c67755b3711affef6a7cd00c39d3146e7a5/Casks/p4v.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.2-33-gc531a35\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://raw.githubusercontent.com/Homebrew/homebrew-cask/f4c88c67755b3711affef6a7cd00c39d3146e7a5/Casks/p4v.rb
Already downloaded: /Users/mshekhawat/Library/Caches/Homebrew/downloads/9c384c52808093dce9e39ed7b0537832964532a4550ae35a153a2e055f092f2b--p4v.rb
==> Verifying checksum for '9c384c52808093dce9e39ed7b0537832964532a4550ae35a153a2e055f092f2b--p4v.rb'
==> Downloading https://www.perforce.com/downloads/perforce/r23.2/bin.macosx12u/P4V.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.2-33-gc531a35\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://www.perforce.com/downloads/perforce/r23.2/bin.macosx12u/P4V.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.2-33-gc531a35\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://www.perforce.com/downloads/perforce/r23.2/bin.macosx12u/P4V.dmg
Already downloaded: /Users/mshekhawat/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/mshekhawat/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/mshekhawat/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg
==> /Users/mshekhawat/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg is quarantined
==> Verifying checksum for 'fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg'
==> Purging files for version 2023.2,2467475 of Cask p4v
Error: p4v: SHA256 mismatch
Expected: fba5813f43a9af3a9080611ec5bb0ad4713dc06360e005a4ee8c1d1b9e4ee4c7
  Actual: a837f5d46526603ff179630d371944cb4acfba1cada5458bf733ef3c9f7b71f6
    File: /Users/mshekhawat/Library/Caches/Homebrew/downloads/fcbc839c1aeb569ab7b91855a69e9ee6b59f19ef0c41df253c9ce10210f09cb6--P4V.dmg
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:288:in `verify_checksum'
/opt/homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:81:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:60:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:167:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:193:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:114:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:250:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
mshekhawat@mac-pro ~ % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have an unnecessary local Cask tap.
This can cause problems installing up-to-date casks.
Please remove it by running:
  brew untap homebrew/cask

Warning: You have an unnecessary local Core tap!
This can cause problems installing up-to-date formulae.
Please remove it by running:
 brew untap homebrew/core

mshekhawat@mac-pro ~ % brew config
HOMEBREW_VERSION: 4.1.2-33-gc531a35
ORIGIN: https://github.com/Homebrew/brew
HEAD: c531a35ae70bcef65f6d0d9f00875fbbce7f2cc9
Last commit: 35 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e01250cfb2bd0daae46f7377d7644e3995bd6cd2
Core tap last commit: 32 minutes ago
Core tap branch: master
Core tap JSON: 31 Jul 06:11 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
mshekhawat@mac-pro ~ %
```

### Output of `brew tap`

```shell
mshekhawat@mac-pro ~ % brew tap 
aquasecurity/trivy
azure/functions
cloudfoundry/tap
hashicorp/tap
homebrew/cask
homebrew/core
homebrew/services
mshekhawat@mac-pro ~ %
```

**Comment by SMillerDev** [comment]
That sounds exactly like the fourth checkbox: https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match

**Comment by daniel-white** [comment]
what a disappointing response, especially after someone else attempted to fix this in #151462

**Comment by krehel** [comment]
Not going to resurrect a closed thread, but @daniel-white you may want to look at and try the steps mentioned in https://github.com/orgs/Homebrew/discussions/4686.

**Comment by shikhanshu** [comment]
I posted a possible solution (url update) in https://github.com/orgs/Homebrew/discussions/4686
