### ISSUE TITLE
mysql-shell 8.1.1 can't upgrade

### ISSUE THREAD

**Issue by jayjanssen** [Homebrew/homebrew-cask#152533]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

mysql-shell 8.1.1 refuses to download

```

Error: mysql-shell: Download failed on Cask 'mysql-shell' with message: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.4-18-gd313e8b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 403
HTTP/2 403
server: AkamaiNetStorage
content-length: 4535
content-type: text/html
set-cookie: AK_NETWORKTYPE=ESSL; expires=Tue, 08-Aug-2023 12:36:54 GMT
etag: "46491460e504640b96a3f5e60da0945f:1434117667"
expires: Tue, 08 Aug 2023 12:34:54 GMT
cache-control: max-age=0, no-cache, no-store
pragma: no-cache
date: Tue, 08 Aug 2023 12:34:54 GMT
```

The weird thing is that `wget` on that url works just fine and the resulting download's sha256 matches what's in the current cask:
```
~/tmp wget https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg
--2023-08-08 08:36:03--  https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg
Resolving dev.mysql.com (dev.mysql.com)... 23.0.26.132, 2600:1408:c400:188c::2e31, 2600:1408:c400:1881::2e31
Connecting to dev.mysql.com (dev.mysql.com)|23.0.26.132|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://cdn.mysql.com//Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg [following]
--2023-08-08 08:36:04--  https://cdn.mysql.com//Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg
Resolving cdn.mysql.com (cdn.mysql.com)... 23.13.159.227, 2600:1408:c400:1884::1d68, 2600:1408:c400:188d::1d68
Connecting to cdn.mysql.com (cdn.mysql.com)|23.13.159.227|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 65024293 (62M) [application/x-apple-diskimage]
Saving to: ‘mysql-shell-8.1.1-macos13-arm64.dmg’

mysql-shell-8.1.1-macos13- 100%[========================================>]  62.01M  18.4MB/s    in 3.4s

2023-08-08 08:36:07 (18.4 MB/s) - ‘mysql-shell-8.1.1-macos13-arm64.dmg’ saved [65024293/65024293]

~/tmp sha256sum mysql-shell-8.1.1-macos13-arm64.dmg
ab53c775b44ddc06b245374790d9c002232b6401ad89553facd966d19ce7ad47  mysql-shell-8.1.1-macos13-arm64.dmg
```

### Command that failed

brew upgrade mysql-shell

### Output of command with `--verbose --debug`

```shell
brew upgrade mysql-shell --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading mysql-shell
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/mysql-shell/.metadata/8.0.33/20230504170858.188/Casks/mysql-shell.json
mysql-shell 8.0.33 -> 8.1.1
==> Started upgrade process for Cask mysql-shell
==> Upgrading mysql-shell
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.4-18-gd313e8b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.4-18-gd313e8b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg
==> Purging files for version 8.1.1 of Cask mysql-shell
Error: mysql-shell: Download failed on Cask 'mysql-shell' with message: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.4-18-gd313e8b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 403
HTTP/2 403
server: AkamaiNetStorage
content-length: 4535
content-type: text/html
set-cookie: AK_NETWORKTYPE=ESSL; expires=Tue, 08-Aug-2023 12:35:42 GMT
etag: "46491460e504640b96a3f5e60da0945f:1434117667"
expires: Tue, 08 Aug 2023 12:33:42 GMT
cache-control: max-age=0, no-cache, no-store
pragma: no-cache
date: Tue, 08 Aug 2023 12:33:42 GMT

/opt/homebrew/Library/Homebrew/system_command.rb:313:in `assert_success!'
/opt/homebrew/Library/Homebrew/utils/curl.rb:232:in `block in curl_headers'
/opt/homebrew/Library/Homebrew/utils/curl.rb:210:in `each'
/opt/homebrew/Library/Homebrew/utils/curl.rb:210:in `curl_headers'
/opt/homebrew/Library/Homebrew/download_strategy.rb:483:in `resolve_url_basename_time_file_size'
/opt/homebrew/Library/Homebrew/download_strategy.rb:475:in `resolved_url_and_basename'
/opt/homebrew/Library/Homebrew/download_strategy.rb:323:in `resolved_basename'
/opt/homebrew/Library/Homebrew/download_strategy.rb:307:in `cached_location'
/opt/homebrew/Library/Homebrew/download_strategy.rb:280:in `temporary_path'
/opt/homebrew/Library/Homebrew/download_strategy.rb:404:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:51:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:167:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:193:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:114:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:253:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
brew config
HOMEBREW_VERSION: 4.1.4-18-gd313e8b
ORIGIN: https://github.com/Homebrew/brew
HEAD: d313e8b02752588b3f19a9729e6c0eac3765b23d
Last commit: 62 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c71bdecfd1d034143e7e4a70dd987651b85daf71
Core tap last commit: 23 minutes ago
Core tap branch: master
Core tap JSON: 08 Aug 12:30 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
~/tmp brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  proto-lint
Warning: Starting from 2023/8/14, AWS SAM CLI will no longer support installing through aws/tap/aws-sam-cli.
        Please use supported installers, for more information
        https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  bazaar

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  terraform
  protobuf

Warning: You have an unnecessary local Cask tap.
This can cause problems installing up-to-date casks.
Please remove it by running:
  brew untap homebrew/cask

Warning: You have an unnecessary local Core tap!
This can cause problems installing up-to-date formulae.
Please remove it by running:
 brew untap homebrew/core

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /opt/homebrew/bin/p2-everywhere
```

### Output of `brew tap`

```shell
~/tmp brew tap
aws/tap
homebrew/cask
homebrew/core
homebrew/services
square/formula
```

**Comment by razvanazamfirei** [comment]
Hi @jayjanssen,

Thank you for opening this. It seems like the `mysql.com` CDN is blocking your request. This is likely temporary and should resolve itself. I haven't been able to reproduce the error, so I don't believe this is a widespread block against Homebrew's user agent. 

Let us know if the issue is not resolved and we can try to adjust the cask. 

Thank you!

**Comment by jayjanssen** [comment]
hi @razvanazamfirei , thanks for the reply.

I retried this week and am getting the same error:

```
==> Upgrading 1 outdated package:
mysql-shell 8.0.33 -> 8.1.1
==> Upgrading mysql-shell
==> Purging files for version 8.1.1 of Cask mysql-shell
Error: mysql-shell: Download failed on Cask 'mysql-shell' with message: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg` exited with 22. Here's the output:
HTTP/2 403
server: AkamaiNetStorage
content-length: 4534
content-type: text/html
set-cookie: AK_NETWORKTYPE=ESSL; expires=Mon, 14-Aug-2023 11:46:27 GMT
etag: "46491460e504640b96a3f5e60da0945f:1434117667"
expires: Mon, 14 Aug 2023 11:44:27 GMT
cache-control: max-age=0, no-cache, no-store
pragma: no-cache
date: Mon, 14 Aug 2023 11:44:27 GMT

curl: (22) The requested URL returned error: 403
```

However, in the exact same terminal session, I can pull it with `wget`:
```
~ wget https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg
--2023-08-14 07:44:58--  https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg
Resolving dev.mysql.com (dev.mysql.com)... 23.49.176.249, 2600:1408:c400:1280::2e31, 2600:1408:c400:1297::2e31
Connecting to dev.mysql.com (dev.mysql.com)|23.49.176.249|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://cdn.mysql.com//Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg [following]
--2023-08-14 07:44:58--  https://cdn.mysql.com//Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg
Resolving cdn.mysql.com (cdn.mysql.com)... 23.197.109.102, 2600:1408:c400:1285::1d68, 2600:1408:c400:1283::1d68
Connecting to cdn.mysql.com (cdn.mysql.com)|23.197.109.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 65024293 (62M) [application/x-apple-diskimage]
Saving to: ‘mysql-shell-8.1.1-macos13-arm64.dmg’

mysql-shell-8.1.1-macos13- 100%[========================================>]  62.01M  11.1MB/s    in 6.2s

2023-08-14 07:45:05 (10.0 MB/s) - ‘mysql-shell-8.1.1-macos13-arm64.dmg’ saved [65024293/65024293]
```

That suggests if Akamai is blocking the curl command from homebrew, it must have something to do with the user-agent or similar and not something like my ip address / network.  

I was going to try to test/tweak the curl command myself, but:
```
~ /usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg
curl: This shim is internal and must be run via brew.
```

**Comment by jayjanssen** [comment]
I retried the curl command with my default `curl` and was able to reproduce the issue:

```
~ curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.4\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg
HTTP/2 403
server: AkamaiNetStorage
content-length: 4534
content-type: text/html
set-cookie: AK_NETWORKTYPE=ESSL; expires=Mon, 14-Aug-2023 11:50:09 GMT
etag: "46491460e504640b96a3f5e60da0945f:1434117667"
expires: Mon, 14 Aug 2023 11:48:09 GMT
cache-control: max-age=0, no-cache, no-store
pragma: no-cache
date: Mon, 14 Aug 2023 11:48:09 GMT

curl: (22) The requested URL returned error: 403
```

If I remove the custom user agent, it downloads successfully:
```
~ curl --disable --cookie /dev/null --globoff --show-error  --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg
HTTP/2 302
content-type: text/html; charset=UTF-8
content-length: 0
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=15768000
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
location: https://cdn.mysql.com//Downloads/MySQL-Shell/mysql-shell-8.1.1-macos13-arm64.dmg
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
date: Mon, 14 Aug 2023 11:48:38 GMT
set-cookie: MySQL_S=avf3201n673sjjhed1uo476rvq8k2qps; path=/; domain=mysql.com; HttpOnly
server-timing: cdn-cache; desc=MISS
server-timing: edge; dur=33
server-timing: origin; dur=51
akamai-grn: 0.966adc17.1692013718.42c85f58
server-timing: ak_p; desc="1692013718605_400321174_1120427864_8431_5417_46_0_15";dur=1

HTTP/1.1 200 OK
Accept-Ranges: bytes
ETag: "1865431e55c6fab7d57be206081c80df:1690351550.930323"
Last-Modified: Tue, 11 Jul 2023 17:04:41 GMT
Server: AkamaiNetStorage
Content-Length: 65024293
Date: Mon, 14 Aug 2023 11:48:39 GMT
Connection: keep-alive
Content-Type: application/x-apple-diskimage
```
