### ISSUE TITLE
Ultimate vocal remover cask is outdated

### ISSUE THREAD

**Issue by lqtx** [Homebrew/homebrew-cask#152983]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The cask Ultimate vocal remover is outdated.
ultimate-vocal-remover: 5.5.0
https://github.com/Anjok07/ultimatevocalremovergui/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/u/ultimate-vocal-remover.rb
==> Name
Ultimate Vocal Remover
==> Description
Removes vocals from audio files
==> Artifacts
Ultimate Vocal Remover.app (App)
==> Analytics
install: 0 (30 days), 0 (90 days), 4 (365 days)

The current version is 5.5.1. It triggers a checksum error during the install.

Error: SHA256 mismatch
Expected: 51f7927c04dea12e9e8acee9326eb195c5532c5142437633b0fbcaa92c5f4613
 Actual: fecc265d04f885f7aaf572a88003311155a0bd9c4c811e17e9ec78aa99b0da67

The actual matches with the checksum of the file directly downloaded from the website.

I have tried : 
brew bump --open-pr --cask ultimate-vocal-remover 
but I had an error message :
Error: Cask 'ultimate-vocal-remover' is unavailable: No Cask with this name exists.

### Command that failed

brew bump --open-pr --cask ultimate-vocal-remover 

### Output of command with `--verbose --debug`

```shell
Error: Cask 'ultimate-vocal-remover' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:397:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:406:in `load'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:158:in `block in load_formula_or_cask'
/opt/homebrew/Library/Homebrew/api.rb:186:in `with_no_api_env'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:89:in `block in create_validator_slow'
/opt/homebrew/Library/Homebrew/api.rb:196:in `with_no_api_env_if_needed'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:118:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:83:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:54:in `to_casks'
/opt/homebrew/Library/Homebrew/dev-cmd/bump.rb:74:in `block in bump'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:499:in `with_env'
/opt/homebrew/Library/Homebrew/api.rb:188:in `with_no_api_env'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/dev-cmd/bump.rb:65:in `bump'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.
HOMEBREW_VERSION: 4.1.5-2-g0bd17c5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0bd17c5b79d750ad85ec229ce8eaca7314e8c0d9
Last commit: 10 hours ago
Core tap JSON: 14 Aug 21:45 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
none
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/152984
