### ISSUE TITLE
Wrong download url in clone-hero cask

### ISSUE THREAD

**Issue by ianrobrien** [Homebrew/homebrew-cask#154032]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

It appears that the download URL for `clone-hero` is incorrect. It looks like it can be download from GitHub from <https://github.com/clonehero-game/releases/releases/download/V1.0.0.4080/CloneHero-mac.dmg>.

### Command that failed

brew install clone-hero

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading clone-hero
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.7-14-g340b982\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5.1\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://pubdl.clonehero.net/clonehero-v1.0.0.4080-final/clonehero-mac-universal.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.7-14-g340b982\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5.1\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://pubdl.clonehero.net/clonehero-v1.0.0.4080-final/clonehero-mac-universal.dmg
Error: Download failed on Cask 'clone-hero' with message: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.7-14-g340b982\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5.1\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://pubdl.clonehero.net/clonehero-v1.0.0.4080-final/clonehero-mac-universal.dmg` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 403
HTTP/2 403
server: nginx/1.20.2
date: Wed, 30 Aug 2023 09:33:07 GMT
content-type: text/html; charset=utf-8
content-length: 153

/opt/homebrew/Library/Homebrew/system_command.rb:313:in `assert_success!'
/opt/homebrew/Library/Homebrew/utils/curl.rb:241:in `block in curl_headers'
/opt/homebrew/Library/Homebrew/utils/curl.rb:219:in `each'
/opt/homebrew/Library/Homebrew/utils/curl.rb:219:in `curl_headers'
/opt/homebrew/Library/Homebrew/download_strategy.rb:483:in `resolve_url_basename_time_file_size'
/opt/homebrew/Library/Homebrew/download_strategy.rb:475:in `resolved_url_and_basename'
/opt/homebrew/Library/Homebrew/download_strategy.rb:323:in `resolved_basename'
/opt/homebrew/Library/Homebrew/download_strategy.rb:307:in `cached_location'
/opt/homebrew/Library/Homebrew/download_strategy.rb:280:in `temporary_path'
/opt/homebrew/Library/Homebrew/download_strategy.rb:404:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:51:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:167:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
HOMEBREW_VERSION: 4.1.7-14-g340b982
ORIGIN: https://github.com/Homebrew/brew
HEAD: 340b982df8abf57b0cbf314e722144c077f96b9e
Last commit: 38 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cdb8d4ba0326aad53405b65bb185a773bfc7a90e
Core tap last commit: 2 hours ago
Core tap branch: master
Core tap JSON: 30 Aug 09:32 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT: set
HOMEBREW_BAT_CONFIG_PATH: /Users/ianrobrien/.config/bat/config
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code --wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSECURE_REDIRECT: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
macos-fuse-t/cask
```

**Comment by ianrobrien** [comment]
Looks like this is using the public mirror and that is returning a 403. This should be fixed on the server side, or the GitHub URL could be used.
