### ISSUE TITLE
Uninstalling wireshark "Error: Failure while executing; `/usr/bin/sudo -E -- /usr/sbin/installer -pkg ChmodBPF.pkg"

### ISSUE THREAD

**Issue by Danrancan** [Homebrew/homebrew-cask#154193]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

OS: MacOS Big Sur
When trying to uninstall wireshark I get the following error:
```
brew uninstall --cask wireshark --force
==> Uninstalling Cask wireshark
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/wireshark/4.0.7/Uninstall\ ChmodBPF.pkg -target /` exited with 1. Here's the output:
installer: Package name is Uninstall ChmodBPF
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Uninstall ChmodBPF.pkg”.)
```
When navigating in finder to /usr/local/Caskroom/wireshark/4.0.7/Uninstall\ ChmodBPF.pkg and doubleclicking the uninstaller package, I get an error screen saying "The Installation failed. The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance."
<img width="615" alt="Install Uninstall ChmodBPF 2023-09-01 07-39-30" src="https://github.com/Homebrew/homebrew-cask/assets/30222551/4204cecd-22de-4e9b-b68a-4bc051c35e03">

### Command that failed

brew uninstall --cask wireshark --force

### Output of command with `--verbose --debug`

```shell
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading zenmap
==> Uninstalling Cask wireshark
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb
==> Uninstalling Cask wireshark
==> Uninstalling artifacts
==> 46 artifacts defined
#<Cask::ArtifactSet: {#<Cask::Artifact::PreflightBlock:0x00007fa4d1799230 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=[], @directives={:uninstall_preflight=>#<Proc:0x00007fa4d1799280@/usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb:76>}>, #<Cask::Artifact::Uninstall:0x00007fa4d1798df8 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=[{:pkgutil=>"org.wireshark.*"}], @directives={:pkgutil=>"org.wireshark.*", :signal=>[]}>, #<Cask::Artifact::Pkg:0x00007fa4d1782da0 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["Add Wireshark to the system path.pkg", {}], @path=#<Pathname:/usr/local/Caskroom/wireshark/4.0.7/Add Wireshark to the system path.pkg>, @stanza_options={}>, #<Cask::Artifact::Pkg:0x00007fa4d1781e78 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["Install ChmodBPF.pkg", {}], @path=#<Pathname:/usr/local/Caskroom/wireshark/4.0.7/Install ChmodBPF.pkg>, @stanza_options={}>, #<Cask::Artifact::App:0x00007fa4d1783250 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["Wireshark.app", {}], @source_string="Wireshark.app", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d178bb30 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/extcap/androiddump", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/extcap/androiddump", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d178b630 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/extcap/ciscodump", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/extcap/ciscodump", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d178b130 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/extcap/randpktdump", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/extcap/randpktdump", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d178ac30 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/extcap/sshdump", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/extcap/sshdump", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d178a730 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/extcap/udpdump", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/extcap/udpdump", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d178a230 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/idl2wrs", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/idl2wrs", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d17814a0 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/capinfos", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/capinfos", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d1789830 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/mmdbresolve", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/mmdbresolve", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d1789330 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/randpkt", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/randpkt", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d1788e30 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/rawshark", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/rawshark", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d1788930 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/reordercap", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/reordercap", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d1788430 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/sharkd", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/sharkd", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d1793ee8 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/text2pcap", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/text2pcap", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d17939e8 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/tshark", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/tshark", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d1789d30 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/mergecap", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/mergecap", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d1780fa0 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/captype", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/captype", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d1780aa0 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/dftest", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/dftest", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d17805a0 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/dumpcap", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/dumpcap", @target_string="">, #<Cask::Artifact::Binary:0x00007fa4d17800a0 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/MacOS/editcap", {}], @source_string="/Applications/Wireshark.app/Contents/MacOS/editcap", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d179b5a8 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/reordercap.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/reordercap.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d17934e8 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/androiddump.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/androiddump.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d1793010 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/capinfos.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/capinfos.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d1792b38 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/captype.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/captype.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d1792660 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/ciscodump.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/ciscodump.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d1792188 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/dftest.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/dftest.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d1791cb0 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/dumpcap.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/dumpcap.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d17917d8 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/editcap.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/editcap.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d1791300 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/etwdump.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/etwdump.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d1790e28 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/mergecap.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/mergecap.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d1790950 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/mmdbresolve.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/mmdbresolve.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d1790478 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/randpkt.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/randpkt.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d179bf58 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/randpktdump.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/randpktdump.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d179ba80 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/rawshark.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/rawshark.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d179b0d0 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/sshdump.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/sshdump.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d179abf8 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/text2pcap.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/text2pcap.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d179a720 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/tshark.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/tshark.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d179a248 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/udpdump.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/udpdump.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d1799d70 @section="1", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man1/wireshark.1", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man1/wireshark.1", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d1799898 @section="4", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man4/extcap.4", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man4/extcap.4", @target_string="">, #<Cask::Artifact::Manpage:0x00007fa4d17993c0 @section="4", @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=["/Applications/Wireshark.app/Contents/Resources/share/man/man4/wireshark-filter.4", {}], @source_string="/Applications/Wireshark.app/Contents/Resources/share/man/man4/wireshark-filter.4", @target_string="">, #<Cask::Artifact::Zap:0x00007fa4d17985d8 @cask=#<Cask wireshark /usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb>, @dsl_args=[{:trash=>["~/.config/wireshark", "~/Library/Caches/org.wireshark.Wireshark", "~/Library/Cookies/org.wireshark.Wireshark.binarycookies", "~/Library/HTTPStorages/org.wireshark.Wireshark.binarycookies", "~/Library/Preferences/org.wireshark.Wireshark.plist", "~/Library/Saved Application State/org.wireshark.Wireshark.savedState"]}], @directives={:trash=>["~/.config/wireshark", "~/Library/Caches/org.wireshark.Wireshark", "~/Library/Cookies/org.wireshark.Wireshark.binarycookies", "~/Library/HTTPStorages/org.wireshark.Wireshark.binarycookies", "~/Library/Preferences/org.wireshark.Wireshark.plist", "~/Library/Saved Application State/org.wireshark.Wireshark.savedState"], :signal=>[]}>}>
==> Uninstalling artifact of class Cask::Artifact::PreflightBlock
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/wireshark/4.0.7/Uninstall\ ChmodBPF.pkg -target /
Enter PIN for 'Certificate For PIV Authentication (Yubico PIV Authentication)':
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/wireshark/4.0.7/Uninstall\ ChmodBPF.pkg -target /` exited with 1. Here's the output:
installer: Package name is Uninstall ChmodBPF
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Uninstall ChmodBPF.pkg”.)
/usr/local/Homebrew/Library/Homebrew/system_command.rb:313:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:59:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:38:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/dsl/base.rb:23:in `system_command'
/usr/local/Caskroom/wireshark/.metadata/4.0.7/20230804041600.045/Casks/wireshark.rb:77:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:49:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:49:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:32:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:461:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:458:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:396:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/uninstall.rb:15:in `block in uninstall_casks'
/usr/local/Homebrew/Library/Homebrew/cask/uninstall.rb:10:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/uninstall.rb:10:in `uninstall_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:77:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```
```


### Output of `brew doctor` and `brew config`

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash -u && git clean -d -f

Uncommitted files:
  ?? .DS_Store

Warning: Xcode alone is not sufficient on Big Sur.
Install the Command Line Tools:
  xcode-select --install

brew config
HOMEBREW_VERSION: 4.1.7-31-gec9bb2f
ORIGIN: https://github.com/Homebrew/brew
HEAD: ec9bb2fe6848bc9e2336843682b21385e58fd827
Last commit: 5 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c2b0b006de61eef66e4c53a0c932a70139030e40
Core tap last commit: 41 minutes ago
Core tap branch: master
Core tap JSON: 01 Sep 12:34 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.uOSpaOt6YY/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 13.0.0 build 1300
Git: 2.42.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 11.7.9-x86_64
CLT: N/A
Xcode: 13.2.1
```

### Output of `brew tap`

```shell
brew tap
buo/cask-upgrade
homebrew/autoupdate
homebrew/bundle
homebrew/cask
homebrew/cask-versions
homebrew/core
teamookla/speedtest
```

**Comment by bevanjkay** [comment]
@Danrancan Not being able to uninstall directly from the uninstaller would likely indicate that the issue is with the software vendor and not with homebrew.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/156903
