### ISSUE TITLE
Cask graalvm-jdk17 exists in multiple taps

### ISSUE THREAD

**Issue by danny-su** [Homebrew/homebrew-cask#154668]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

<img width="467" alt="image" src="https://github.com/Homebrew/homebrew-cask/assets/12178855/6dfe55d2-d4ac-4114-b9fc-ed79dabf7872">

### Command that failed

brew search jdk

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading jd from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading mdk from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading cdk from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@11.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@11-full.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@11-lite.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@12.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@13.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@13-full.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@13-lite.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@14.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@14-full.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@14-lite.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@15.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@15-full.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@15-lite.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@16.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@16-full.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@16-lite.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@17.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@17-full.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@17-lite.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@18.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@18-full.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@18-lite.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@19.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@19-full.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@19-lite.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@20.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@20-full.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/bell-sw/homebrew-liberica/Formula/liberica-jdk@20-lite.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading openjdk from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading openjdk@11 from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading openjdk@17 from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading openjdk@8 from API
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading adoptopenjdk
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk11
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk11-full
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk11-lite
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk12
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk12-lite
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk13
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk13-full
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk13-lite
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk14
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk14-full
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk14-lite
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk15
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk15-full
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk15-lite
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk16
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk16-full
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk16-lite
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk17
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk17-full
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk17-lite
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk18
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk18-full
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk18-lite
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk19
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk19-full
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk19-lite
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk20
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk20-full
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk20-lite
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk8
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading bell-sw/liberica/liberica-jdk8-full
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gama-jdk
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading graalvm-jdk
Error: Cask graalvm-jdk17 exists in multiple taps:
  graalvm/tap/graalvm-jdk17
  homebrew/cask-versions/graalvm-jdk17
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:433:in `for'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:407:in `load'
/opt/homebrew/Library/Homebrew/search.rb:96:in `block in search_casks'
/opt/homebrew/Library/Homebrew/search.rb:95:in `map'
/opt/homebrew/Library/Homebrew/search.rb:95:in `search_casks'
/opt/homebrew/Library/Homebrew/search.rb:115:in `search_names'
/opt/homebrew/Library/Homebrew/cmd/search.rb:85:in `search'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  dockutil
  docui
  exa
  gofish
  kubeless
  kubeval

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  dart
  dtc
  pcre
  wireshark
```

### Output of `brew tap`

```shell
bell-sw/liberica
buo/cask-upgrade
cockroachdb/tap
cue-lang/tap
dapr/tap
dart-lang/dart
derailed/k9s
edamameldn/tap
fluxcd/tap
go-delve/delve
go-task/tap
graalvm/tap
hashicorp/tap
homebrew/bundle
homebrew/cask-fonts
homebrew/cask-versions
homebrew/services
jandedobbeleer/oh-my-posh
jbangdev/tap
ktr0731/evans
kylef/formulae
layer5io/tap
metalbear-co/mirrord
microconfig/microconfig
microconfig/microctl
microsoft/azdata-cli-release
microsoft/mssql-release
mvndaemon/mvnd
oven-sh/bun
pivotal/tap
pot-app/tap
project-env/tap
quarkusio/tap
sourcegraph/src-cli
spring-io/tap
ubuntu/microk8s
yoheimuta/protolint
```

**Comment by miccal** [comment]
This is not a bug -- we cannot control what Cask's are in private taps.
