### ISSUE TITLE
Unable to install private-internet-access cask.

### ISSUE THREAD

**Issue by drpaulatkinson** [Homebrew/homebrew-cask#155709]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Fresh install of MacOS Ventura 13.5.2 on Intel based MacBook Pro
Fresh install of Homebrew.
Multiple other casks installing normally without error but getting Curl SSL certificate error on private-internet-access

curl: (60) SSL certificate problem: unable to get local issuer certificate

Problem persists on --force and after reset/ update commands.

### Command that failed

brew install --cask private-internet-access        

### Output of command with `--verbose --debug`

```shell
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading private-internet-access
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.12-2-g1f80e82\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.5.2\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://installers.privateinternetaccess.com/download/pia-macos-3.5-07703.zip
Error: Download failed on Cask 'private-internet-access' with message: Failure while executing; `/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.12-2-g1f80e82\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.5.2\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://installers.privateinternetaccess.com/download/pia-macos-3.5-07703.zip` exited with 60. Here's the output:
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

/usr/local/Homebrew/Library/Homebrew/system_command.rb:313:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/utils/curl.rb:241:in `block in curl_headers'
/usr/local/Homebrew/Library/Homebrew/utils/curl.rb:219:in `each'
/usr/local/Homebrew/Library/Homebrew/utils/curl.rb:219:in `curl_headers'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:491:in `resolve_url_basename_time_file_size'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:483:in `resolved_url_and_basename'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:331:in `resolved_basename'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:315:in `cached_location'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:288:in `temporary_path'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:412:in `fetch'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:55:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:167:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
% brew doctor                                                   
Your system is ready to brew.


% brew config
HOMEBREW_VERSION: 4.1.12-2-g1f80e82
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1f80e82dd72fce6642e4ea360f7a1feef5d78470
Last commit: 13 hours ago
Core tap JSON: 20 Sep 21:04 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-x86_64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
```

### Output of `brew tap`

```shell
%brew tap
(nothing)
```

**Comment by miccal** [comment]
I cannot reproduce this, so I assume it was a temporary issue:
```
|-> brew fetch private-internet-access
==> Downloading https://installers.privateinternetaccess.com/download/pia-macos-3.5-07703.zip
################################################################################################################ 100.0%
Downloaded to: /Users/00084858/Library/Caches/Homebrew/downloads/86a07a5eff6c24007a76b24bd9c38eb6f04aa5488854b2c9ac10a8196b1d037a--pia-macos-3.5-07703.zip
SHA256: d7c451dcf28b914ae0e25ad48c967ea82e294d9f42b8232ca92ad45ba212d67c
```
