### ISSUE TITLE
`brew install packages` fails

### ISSUE THREAD

**Issue by steve-mackinnon** [Homebrew/homebrew-cask#156098]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

`brew install --cask packages` is failing because the name of the .pkg installer contained in Packages.dmg is incorrect.

### Command that failed

brew install --cask packages

### Output of command with `--verbose --debug`

```shell
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading packages
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading http://s.sudre.free.fr/Software/files/Packages.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.13-4-gf1d345a\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head http://s.sudre.free.fr/Software/files/Packages.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.13-4-gf1d345a\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET http://s.sudre.free.fr/Software/files/Packages.dmg
Already downloaded: /Users/stevemackinnon/Library/Caches/Homebrew/downloads/02a5de38825fc3ddbe60b7fa49ca849cab656a74b8b0fb64158ea39f1a2bcff9--Packages.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx13 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/stevemackinnon/Library/Caches/Homebrew/downloads/02a5de38825fc3ddbe60b7fa49ca849cab656a74b8b0fb64158ea39f1a2bcff9--Packages.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/stevemackinnon/Library/Caches/Homebrew/downloads/02a5de38825fc3ddbe60b7fa49ca849cab656a74b8b0fb64158ea39f1a2bcff9--Packages.dmg
==> /Users/stevemackinnon/Library/Caches/Homebrew/downloads/02a5de38825fc3ddbe60b7fa49ca849cab656a74b8b0fb64158ea39f1a2bcff9--Packages.dmg is quarantined
Warning: No checksum defined for cask 'packages', skipping verification.
/usr/bin/env hdiutil imageinfo -format /Users/stevemackinnon/Library/Caches/Homebrew/downloads/02a5de38825fc3ddbe60b7fa49ca849cab656a74b8b0fb64158ea39f1a2bcff9--Packages.dmg
==> Installing Cask packages
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/stevemackinnon/Library/Caches/Homebrew/downloads/02a5de38825fc3ddbe60b7fa49ca849cab656a74b8b0fb64158ea39f1a2bcff9--Packages.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230925-14145-k2n7ua /Users/stevemackinnon/Library/Caches/Homebrew/downloads/02a5de38825fc3ddbe60b7fa49ca849cab656a74b8b0fb64158ea39f1a2bcff9--Packages.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20230925-14145-52pucg.list -- /private/tmp/20230925-14145-11i7vr2.bom
/usr/bin/env ditto --bom /private/tmp/20230925-14145-11i7vr2.bom -- /private/tmp/d20230925-14145-k2n7ua/dmg.3dx8YL /private/tmp/d20230925-14145-1u0nzw2
/usr/bin/env diskutil info -plist /private/tmp/d20230925-14145-k2n7ua/dmg.3dx8YL
/usr/bin/env diskutil eject /private/tmp/d20230925-14145-k2n7ua/dmg.3dx8YL
/usr/bin/env cp -pR /private/tmp/d20230925-14145-1u0nzw2/background.tif /usr/local/Caskroom/packages/1.2.10/background.tif
/usr/bin/env cp -pR /private/tmp/d20230925-14145-1u0nzw2/Read\ Before\ You\ Install\ Packages.rtf /usr/local/Caskroom/packages/1.2.10/Read\ Before\ You\ Install\ Packages.rtf
/usr/bin/env cp -pR /private/tmp/d20230925-14145-1u0nzw2/Install\ Packages.pkg /usr/local/Caskroom/packages/1.2.10/Install\ Packages.pkg
/usr/bin/env cp -pR /private/tmp/d20230925-14145-1u0nzw2/Extras/. /usr/local/Caskroom/packages/1.2.10/Extras
==> Verifying Gatekeeper status of /Users/stevemackinnon/Library/Caches/Homebrew/downloads/02a5de38825fc3ddbe60b7fa49ca849cab656a74b8b0fb64158ea39f1a2bcff9--Packages.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/stevemackinnon/Library/Caches/Homebrew/downloads/02a5de38825fc3ddbe60b7fa49ca849cab656a74b8b0fb64158ea39f1a2bcff9--Packages.dmg
==> /Users/stevemackinnon/Library/Caches/Homebrew/downloads/02a5de38825fc3ddbe60b7fa49ca849cab656a74b8b0fb64158ea39f1a2bcff9--Packages.dmg is quarantined
==> Propagating quarantine from /Users/stevemackinnon/Library/Caches/Homebrew/downloads/02a5de38825fc3ddbe60b7fa49ca849cab656a74b8b0fb64158ea39f1a2bcff9--Packages.dmg to /usr/local/Caskroom/packages/1.2.10
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/stevemackinnon/Library/Caches/Homebrew/downloads/02a5de38825fc3ddbe60b7fa49ca849cab656a74b8b0fb64158ea39f1a2bcff9--Packages.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;6511ba4a\;Homebrew\\x20Cask\;DDCBB636-3744-4F39-9908-127E10122B76
==> Creating metadata directory: /usr/local/Caskroom/packages/.metadata/1.2.10/20230925170740.737
==> Creating metadata subdirectory: /usr/local/Caskroom/packages/.metadata/1.2.10/20230925170740.737/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for packages; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
==> Purging files for version 1.2.10 of Cask packages
Error: Could not find PKG source file 'packages/Packages.pkg', found 'Install Packages.pkg' instead.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:49:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:33:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:229:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:222:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:110:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  go@1.16
```

### Output of `brew tap`

```shell
brew tap
1password/tap
homebrew/bundle
```

**Comment by razvanazamfirei** [comment]
Thank you for opening this @steve-mackinnon and @krehel for the PR.

**Comment by fauxpark** [comment]
This still seems to be failing: https://github.com/qmk/qmk_toolbox/actions/runs/6368754047/job/17288366372

**Comment by bevanjkay** [comment]
@fauxpark Can you try running `brew update` in the CI run prior to `brew install`?

**Comment by fauxpark** [comment]
Thanks, that seemed to work, but I'm not sure why it is necessary now.

**Comment by Bo98** [comment]
Unlike when you are running locally, GitHub Actions by default force disable auto-updates so it only updates on the interval that GitHub issue new CI images. The last GitHub Actions macOS image was build on 2023-09-21 but we fixed this issue on 2023-09-25.
