### ISSUE TITLE
gzdoom - release format change

### ISSUE THREAD

**Issue by belthesar** [Homebrew/homebrew-cask#157325]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The gzdoom project has changed how they name release artifacts, which causes installing or updating the gzdoom cask to fail. It seems that this has been in flux for a little bit as the project settles on a convention to name ARM artifacts. zdoom now seems to demarcate any release with an ARM binary with an `a` in the file name. 

https://github.com/ZDoom/gzdoom/releases

Former naming convention: 
`gzdoom-4-10-0-macOS.zip`

New naming convention:
`gzdoom-4-11-0a-macOS.zip`

### Command that failed

brew upgrade 

### Output of command with `--verbose --debug`

```shell
brew upgrade --cask gzdoom --verbose --debug
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.1.15\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5.2\)\ curl/8.1.2 --header Accept-Language:\ en --fail --remote-time --output /Users/belthesar/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/belthesar/Library/Caches/Homebrew/api/cask.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.15\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5.2\)\ curl/8.1.2 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1012k  100 1012k    0     0  3590k      0 --:--:-- --:--:-- --:--:-- 3643k
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gzdoom
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/gzdoom/.metadata/4.10.0/20230508222530.666/Casks/gzdoom.json
gzdoom 4.10.0 -> 4.11.0
==> Started upgrade process for Cask gzdoom
==> Upgrading gzdoom
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.15\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5.2\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/ZDoom/gzdoom/releases/download/g4.11.0/gzdoom-4-11-0-macOS.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.15\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5.2\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/ZDoom/gzdoom/releases/download/g4.11.0/gzdoom-4-11-0-macOS.zip
==> Downloading https://github.com/ZDoom/gzdoom/releases/download/g4.11.0/gzdoom-4-11-0-macOS.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.15\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5.2\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/ZDoom/gzdoom/releases/download/g4.11.0/gzdoom-4-11-0-macOS.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.15\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5.2\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/ZDoom/gzdoom/releases/download/g4.11.0/gzdoom-4-11-0-macOS.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.15\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5.2\)\ curl/8.1.2 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/belthesar/Library/Caches/Homebrew/downloads/460f06c9c9bda5f4b4c299da9be58bdeb30864be2a9eae0f3ce67c463f2bd731--gzdoom-4-11-0-macOS.zip.incomplete --location https://github.com/ZDoom/gzdoom/releases/download/g4.11.0/gzdoom-4-11-0-macOS.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> Purging files for version 4.11.0 of Cask gzdoom
Error: gzdoom: Download failed on Cask 'gzdoom' with message: Download failed: https://github.com/ZDoom/gzdoom/releases/download/g4.11.0/gzdoom-4-11-0-macOS.zip
/opt/homebrew/Library/Homebrew/download_strategy.rb:447:in `rescue in fetch'
/opt/homebrew/Library/Homebrew/download_strategy.rb:444:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:55:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:167:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:193:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:114:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:253:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  syncthing
  python-certifi
  pygments
  docutils
  yt-dlp
  dotnet
  six
  python-mutagen
  protobuf

---

HOMEBREW_VERSION: 4.1.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: e57a87cfe9c15f192cd4fc6695a2b3b7acf0ddf7
Last commit: 34 hours ago
Core tap JSON: 10 Oct 20:51 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0
Rosetta 2: false
```

### Output of `brew tap`

```shell
apple/apple
gcenx/wine
homebrew/bundle
homebrew/cask-fonts
homebrew/cask-versions
homebrew/services
minacle/chntpw
sidneys/homebrew
slp/krun
```

**Comment by belthesar** [comment]
It appears I was mistaken - scanning issues in the repo, it appears there was a hotfix release for ARM targets for this release based off of https://github.com/ZDoom/gzdoom/issues/2188, which was resolved by https://github.com/ZDoom/gzdoom/commit/72fc6a6d79ec1229358dcff914d484e9b56461ea. This should purely be a version bump at this point.
