### ISSUE TITLE
broken --cask nosqlbooster-for-mongodb

### ISSUE THREAD

**Issue by yohanvalencia** [Homebrew/homebrew-cask#157786]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I've tried running `brew install --cask nosqlbooster-for-mongodb`
and get this error:
```
➜  ~ brew install --cask --force nosqlbooster-for-mongodb
==> Downloading https://s3.mongobooster.com/download/releasesv8/nosqlbooster4mongo-8.1.0.dmg
curl: (47) Maximum (50) redirects followed

Error: Download failed on Cask 'nosqlbooster-for-mongodb' with message: Download failed: https://s3.mongobooster.com/download/releasesv8/nosqlbooster4mongo-8.1.0.dmg
```

I thought it was something with the version and tried to bump it to it's latest patched version `8.1.1`. I've followed the steps to create a new [PR](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#create-your-pull-request-from-a-new-branch) and still got the same error while testing

``` 
➜  homebrew-cask git:(bump-nosqlbooster-for-mongodb-8.1.1) ✗ HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source nosqlbooster-for-mongodb
==> Downloading https://s3.mongobooster.com/download/releasesv8/nosqlbooster4mongo-8.1.1.dmg
curl: (47) Maximum (50) redirects followed      #           #                                                                                        

Error: Download failed on Cask 'nosqlbooster-for-mongodb' with message: Download failed: https://s3.mongobooster.com/download/releasesv8/nosqlbooster4mongo-8.1.1.dmg
```

I've tried using `curl` and `wget` and getting the same result:

- `curl -L https://s3.mongobooster.com/download/releasesv8/nosqlbooster4mongo-8.1.1.dmg --output test.dmg`
- `wget https://s3.mongobooster.com/download/releasesv8/nosqlbooster4mongo-8.1.1.dmg`

### Command that failed

brew install --cask nosqlbooster-for-mongodb

### Output of command with `--verbose --debug`

```shell
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading nosqlbooster-for-mongodb
[35m==>[0m [1mCask::Installer#install[0m
[35m==>[0m [1mPrinting caveats[0m
[35m==>[0m [1mCask::Installer#fetch[0m
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.16\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.5.2\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://s3.mongobooster.com/download/releasesv8/nosqlbooster4mongo-8.1.0.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.16\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.5.2\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://s3.mongobooster.com/download/releasesv8/nosqlbooster4mongo-8.1.0.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.16\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.5.2\)\ curl/8.1.2 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/yohanvalencia/Library/Caches/Homebrew/downloads/9635924d56ce2bb9809de353bfe8c8127a37501fb8ccbbcabea69082559ad9b7--nosqlbooster4mongo-8.1.0.dmg.incomplete --location https://s3.mongobooster.com/download/releasesv8/nosqlbooster4mongo-8.1.0.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   178    0   178    0     0   1419      0 --:--:-- --:--:-- --:--:--  1508

100   178    0   178    0     0    975      0 --:--:-- --:--:-- --:--:--   975

100   178    0   178    0     0    694      0 --:--:-- --:--:-- --:--:--   694

100   178    0   178    0     0    636      0 --:--:-- --:--:-- --:--:--   636

100   178    0   178    0     0    557      0 --:--:-- --:--:-- --:--:--   557

100   178    0   178    0     0    520      0 --:--:-- --:--:-- --:--:--   520

100   178    0   178    0     0    433      0 --:--:-- --:--:-- --:--:--   433

100   178    0   178    0     0    411      0 --:--:-- --:--:-- --:--:--   411

100   178    0   178    0     0    390      0 --:--:-- --:--:-- --:--:--   390

100   178    0   178    0     0    370      0 --:--:-- --:--:-- --:--:--   370

100   178    0   178    0     0    354      0 --:--:-- --:--:-- --:--:--   354

100   178    0   178    0     0    329      0 --:--:-- --:--:-- --:--:--   329

100   178    0   178    0     0    316      0 --:--:-- --:--:-- --:--:--   316
100   178    0   178    0     0    315      0 --:--:-- --:--:-- --:--:--     0

100   178    0   178    0     0    286      0 --:--:-- --:--:-- --:--:--   286

100   178    0   178    0     0    275      0 --:--:-- --:--:-- --:--:--   275

100   178    0   178    0     0    264      0 --:--:-- --:--:-- --:--:--   264

100   178    0   178    0     0    254      0 --:--:-- --:--:-- --:--:--   254

100   178    0   178    0     0    246      0 --:--:-- --:--:-- --:--:--   246

100   178    0   178    0     0    233      0 --:--:-- --:--:-- --:--:--   233

100   178    0   178    0     0    227      0 --:--:-- --:--:-- --:--:--   227

100   178    0   178    0     0    221      0 --:--:-- --:--:-- --:--:--   221

100   178    0   178    0     0    215      0 --:--:-- --:--:-- --:--:--   215

100   178    0   178    0     0    209      0 --:--:-- --:--:-- --:--:--   209

100   178    0   178    0     0    203      0 --:--:-- --:--:-- --:--:--   203

100   178    0   178    0     0    198      0 --:--:-- --:--:-- --:--:--   198

100   178    0   178    0     0    193      0 --:--:-- --:--:-- --:--:--   193

100   178    0   178    0     0    188      0 --:--:-- --:--:-- --:--:--   188

100   178    0   178    0     0    181      0 --:--:-- --:--:-- --:--:--   181

100   178    0   178    0     0    177      0 --:--:--  0:00:01 --:--:--   177

100   178    0   178    0     0    171      0 --:--:--  0:00:01 --:--:--   171

100   178    0   178    0     0    167      0 --:--:--  0:00:01 --:--:--   167

100   178    0   178    0     0    161      0 --:--:--  0:00:01 --:--:--   161

100   178    0   178    0     0    158      0 --:--:--  0:00:01 --:--:--   158

100   178    0   178    0     0    155      0 --:--:--  0:00:01 --:--:--   155

100   178    0   178    0     0    145      0 --:--:--  0:00:01 --:--:--   145

100   178    0   178    0     0    141      0 --:--:--  0:00:01 --:--:--   141

100   178    0   178    0     0    138      0 --:--:--  0:00:01 --:--:--   138

100   178    0   178    0     0    135      0 --:--:--  0:00:01 --:--:--   135

100   178    0   178    0     0    132      0 --:--:--  0:00:01 --:--:--   132

100   178    0   178    0     0    128      0 --:--:--  0:00:01 --:--:--   128

100   178    0   178    0     0    124      0 --:--:--  0:00:01 --:--:--   124

100   178    0   178    0     0    122      0 --:--:--  0:00:01 --:--:--   122

100   178    0   178    0     0    120      0 --:--:--  0:00:01 --:--:--   120

100   178    0   178    0     0    118      0 --:--:--  0:00:01 --:--:--   118

100   178    0   178    0     0    117      0 --:--:--  0:00:01 --:--:--   117

100   178    0   178    0     0    115      0 --:--:--  0:00:01 --:--:--   115

100   178    0   178    0     0    113      0 --:--:--  0:00:01 --:--:--   113
100   178    0   178    0     0    113      0 --:--:--  0:00:01 --:--:--     0

100   178    0   178    0     0    111      0 --:--:--  0:00:01 --:--:--   111

100   178    0   178    0     0    109      0 --:--:--  0:00:01 --:--:--   109

100   178    0   178    0     0    106      0 --:--:--  0:00:01 --:--:--   106

100   178    0   178    0     0    104      0 --:--:--  0:00:01 --:--:--   104
curl: (47) Maximum (50) redirects followed
Error: Download failed on Cask 'nosqlbooster-for-mongodb' with message: Download failed: https://s3.mongobooster.com/download/releasesv8/nosqlbooster4mongo-8.1.0.dmg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:447:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:444:in `fetch'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:89:in `block in create_validator_slow'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:55:in `fetch'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:167:in `download'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
`brew doctor`
Your system is ready to brew.

`brew config`
HOMEBREW_VERSION: 4.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: c0c8a4dd4dd19ec16deb429abd50cdf82ea33b27
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dd1554860d6775ceb77be8afb17ba0d839159910
Core tap last commit: 45 minutes ago
Core tap branch: master
Core tap JSON: 16 Oct 19:19 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-x86_64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
```

### Output of `brew tap`

```shell
dbt-labs/dbt
homebrew/cask
homebrew/core
```

**Comment by yohanvalencia** [comment]
JIC I just tried doing this:
`curl -A "Mozilla/5.0 (Linux; Android 10; SM-G996U Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Mobile Safari/537.36" -L https://s3.nosqlbooster.com/download/releasesv8/nosqlbooster4mongo-8.1.1.dmg -o test.dmg`
and it worked. Not sure if we need to flag somewhere so brew uses another User-Agent.
