### ISSUE TITLE
Module named 'idna' missing in esphome 2023.10.6

### ISSUE THREAD

**Issue by JL-EU** [Homebrew/homebrew-cask#159499]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I am not sure how to report an issue in the brew formulae, so excuse me if this is the wrong place.

I can't run esphome and get the following error when : ModuleNotFoundError: No module named 'idna'

https://github.com/Homebrew/homebrew-core/commits/e2bba732d6a3f5289c7357ce5a3ffa8c909aa61a/Formula/e/esphome.rb

esphome/2023.10.6

-----------
Traceback (most recent call last):
  File "/opt/homebrew/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/__main__.py", line 1036, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/__main__.py", line 1023, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/__main__.py", line 409, in command_compile
    exit_code = compile_program(args, config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/__main__.py", line 216, in compile_program
    rc = platformio_api.run_compile(config, CORE.verbose)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/platformio_api.py", line 108, in run_compile
    return run_platformio_cli_run(config, verbose, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/platformio_api.py", line 101, in run_platformio_cli_run
    return run_platformio_cli(*command, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/platformio_api.py", line 90, in run_platformio_cli
    import platformio.__main__
  File "/opt/homebrew/opt/platformio/libexec/lib/python3.12/site-packages/platformio/__main__.py", line 21, in <module>
    from platformio import __version__, exception, maintenance
  File "/opt/homebrew/opt/platformio/libexec/lib/python3.12/site-packages/platformio/maintenance.py", line 22, in <module>
    from platformio import __version__, app, exception, fs, telemetry
  File "/opt/homebrew/opt/platformio/libexec/lib/python3.12/site-packages/platformio/telemetry.py", line 25, in <module>
    import requests
  File "/opt/homebrew/opt/platformio/libexec/lib/python3.12/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/opt/homebrew/opt/platformio/libexec/lib/python3.12/site-packages/requests/packages.py", line 16, in <module>
    locals()[package] = __import__(package)
                        ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'idna'

### Command that failed

esphome compile

### Output of command with `--verbose --debug`

```shell
not valid options for the above command
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.

HOMEBREW_VERSION: 4.1.19-17-gff404fe
ORIGIN: https://github.com/Homebrew/brew
HEAD: ff404fe5ab7491b074568b3e20ef001b5ca39595
Last commit: 9 hours ago
Core tap JSON: 06 Nov 21:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.6-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0.1
Rosetta 2: false
```

### Output of `brew tap`

```shell
no output
```

**Comment by bevanjkay** [comment]
@JL-EU This issue should be opened in the [`homebrew-core`](https://github.com/homebrew/homebrew-core) repository instead. Thanks.
