### ISSUE TITLE
current version of openzfs 2.2.0 on intel macOS Sonoma is no longer available.

### ISSUE THREAD

**Issue by fang-ling** [Homebrew/homebrew-cask#160561]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

According to the [zfs-macOS-2.2.0 release](https://openzfsonosx.org/forum/viewtopic.php?f=20&t=3848#p12546), it's mentioned that the original OpenZFSonOsX-2.2.0-Sonoma-14.pkg (with id=497) was incorrect and a new OpenZFSonOsX-2.2.0-Sonoma-14.REPACK.pkg (with id=499) has been produced.

I tried to update the `version` (2.2.0,497 to 2.2.0,499) and corresponding `sha256` for Intel Sonoma accordingly in `openzfs.rb`.  However, I am not sure if this will work, as the pkg file name has also changed (`.REPACK` has been added).

### Command that failed

brew upgrade openzfs

### Output of command with `--verbose --debug`

```shell
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading openzfs
==> Upgrading 1 outdated package:
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /usr/local/Caskroom/openzfs/.metadata/2.1.6,437/20231023113305.424/Casks/openzfs.rb
openzfs 2.1.6,437 -> 2.2.0,497
==> Started upgrade process for Cask openzfs
==> Upgrading openzfs
==> Printing caveats
==> Caveats
openzfs requires a kernel extension to work.
If the installation fails, retry after you enable it in:
  System Preferences → Security & Privacy → General

For more information, refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Cask::Installer#fetch
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.16-24-g35746e0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.0\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/a5e6444192f0ce43e93c2ee7ade060e6368bdf9c/Casks/o/openzfs.rb
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.16-24-g35746e0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.0\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://raw.githubusercontent.com/Homebrew/homebrew-cask/a5e6444192f0ce43e93c2ee7ade060e6368bdf9c/Casks/o/openzfs.rb
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/a5e6444192f0ce43e93c2ee7ade060e6368bdf9c/Casks/o/openzfs.rb
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.16-24-g35746e0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.0\)\ curl/8.1.2 --header Accept-Language:\ en --fail --connect-timeout 15 --retry 3 --remote-time --output /Users/louisshen/Library/Caches/Homebrew/downloads/0e26a8b98c015bb86bbd07d68414d445d27e87bf7bbccb76dda3841781658c63--openzfs.rb.incomplete --location https://raw.githubusercontent.com/Homebrew/homebrew-cask/a5e6444192f0ce43e93c2ee7ade060e6368bdf9c/Casks/o/openzfs.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3538  100  3538    0     0   1865      0  0:00:01  0:00:01 --:--:--  1868
==> Verifying checksum for '0e26a8b98c015bb86bbd07d68414d445d27e87bf7bbccb76dda3841781658c63--openzfs.rb'
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.16-24-g35746e0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.0\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://openzfsonosx.org/forum/download/file.php\?id=497
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.16-24-g35746e0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.0\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://openzfsonosx.org/forum/download/file.php\?id=497
==> Downloading https://openzfsonosx.org/forum/download/file.php?id=497
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.16-24-g35746e0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.0\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://openzfsonosx.org/forum/download/file.php\?id=497
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.16-24-g35746e0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.0\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://openzfsonosx.org/forum/download/file.php\?id=497
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.16-24-g35746e0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.0\)\ curl/8.1.2 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/louisshen/Library/Caches/Homebrew/downloads/ed2934b25fde006578a1dd4706665b99b6d76a11efae6c93f80ccbb10b785d09--file.php.incomplete --location https://openzfsonosx.org/forum/download/file.php\?id=497
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  6390    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404
==> Purging files for version 2.2.0,497 of Cask openzfs
Error: openzfs: Download failed on Cask 'openzfs' with message: Download failed: https://openzfsonosx.org/forum/download/file.php?id=497
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:447:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:444:in `fetch'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:55:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:167:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/upgrade.rb:193:in `upgrade_cask'
/usr/local/Homebrew/Library/Homebrew/cask/upgrade.rb:114:in `block in upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cask/upgrade.rb:113:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/upgrade.rb:113:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:253:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
HOMEBREW_VERSION: 4.1.16-24-g35746e0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35746e0a6ba6c3c5cfe56d99f79d9ec9f52ee15f
Last commit: 4 weeks ago
Core tap JSON: 20 Nov 05:47 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 20-core 64-bit cometlake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-x86_64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
```

### Output of `brew tap`

```shell
homebrew/services
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/160607
