### ISSUE TITLE
sonic3air checksum doesn't match (can't open a PR using brew bump)

### ISSUE THREAD

**Issue by lightningx10** [Homebrew/homebrew-cask#161983]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Hello, sorry to open up an issue like this. I've checked the download for sonic3air and gotten its hash from multiple different locations multiple times, each getting the same SHA256 checksum. Looking at the cask, this seems to be different, so I think the host must have updated the dmg in-place.

I tried making a PR the recommended way:
```shell
$ brew bump --open-pr sonic3air
```
But it came back with the following error:
```
Error: No available formula with the name "sonic3air".
```
Which is rather odd, but unrelated to this issue.

The SHA256 sum in the cask is:
```
6ef193c894005e8c8f91916705da52f5bdf0ef74a1e438f7445ab617663eae30
```
The actual SHA256 sum that I seem to be getting at multiple different locations is:
```
9fef41c547550292ec2ffa95063af2ed2be9b623496a857f4c5ecc07f698272f
```

Again sorry to post this here as an issue, **this is NOT an issue with homebrew-cask**, but the PR function doesn't work for me and the guide said to post here after trying and failing to use that.

### Command that failed

brew install --cask sonic3air

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading sonic3air
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.24-6-g08b7835\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.1.2\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://projects.sappharad.com/s3air_mac/sonic3air_mac_231118.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.24-6-g08b7835\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.1.2\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://projects.sappharad.com/s3air_mac/sonic3air_mac_231118.dmg
==> Downloading https://projects.sappharad.com/s3air_mac/sonic3air_mac_231118.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.24-6-g08b7835\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.1.2\)\ curl/8.1.2 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/ethan/Library/Caches/Homebrew/downloads/4dabd3a2808a217adffc503aa58b7aa95bb105c3f97fa01a93049cf925034256--sonic3air_mac_231118.dmg.incomplete --location https://projects.sappharad.com/s3air_mac/sonic3air_mac_231118.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28.5M  100 28.5M    0     0  2366k      0  0:00:12  0:00:12 --:--:-- 2420k
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/ethan/Library/Caches/Homebrew/downloads/4dabd3a2808a217adffc503aa58b7aa95bb105c3f97fa01a93049cf925034256--sonic3air_mac_231118.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/ethan/Library/Caches/Homebrew/downloads/4dabd3a2808a217adffc503aa58b7aa95bb105c3f97fa01a93049cf925034256--sonic3air_mac_231118.dmg
==> /Users/ethan/Library/Caches/Homebrew/downloads/4dabd3a2808a217adffc503aa58b7aa95bb105c3f97fa01a93049cf925034256--sonic3air_mac_231118.dmg is not quarantined
==> Quarantining /Users/ethan/Library/Caches/Homebrew/downloads/4dabd3a2808a217adffc503aa58b7aa95bb105c3f97fa01a93049cf925034256--sonic3air_mac_231118.dmg
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/ethan/Library/Caches/Homebrew/downloads/4dabd3a2808a217adffc503aa58b7aa95bb105c3f97fa01a93049cf925034256--sonic3air_mac_231118.dmg https://projects.sappharad.com/s3air_mac/sonic3air_mac_231118.dmg https://sonic3air.org/
==> Verifying checksum for '4dabd3a2808a217adffc503aa58b7aa95bb105c3f97fa01a93049cf925034256--sonic3air_mac_231118.dmg'
Error: SHA256 mismatch
Expected: 6ef193c894005e8c8f91916705da52f5bdf0ef74a1e438f7445ab617663eae30
  Actual: 9fef41c547550292ec2ffa95063af2ed2be9b623496a857f4c5ecc07f698272f
    File: /Users/ethan/Library/Caches/Homebrew/downloads/4dabd3a2808a217adffc503aa58b7aa95bb105c3f97fa01a93049cf925034256--sonic3air_mac_231118.dmg
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:288:in `verify_checksum'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation_2_7.rb:424:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation_2_7.rb:424:in `block in create_validator_procedure_fast1'
/opt/homebrew/Library/Homebrew/cask/download.rb:85:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/download.rb:64:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:167:in `download'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 4.1.24-6-g08b7835
ORIGIN: https://github.com/Homebrew/brew
HEAD: 08b78357a13977c9421e78eb5bc763cb4eaa3e81
Last commit: 18 hours ago
Core tap JSON: 07 Dec 14:34 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.2-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
clojure/tools
d12frosted/emacs-plus
homebrew/cask-versions
homebrew/services
koekeishiya/formulae
railwaycat/emacsmacport
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/162000
