### ISSUE TITLE
Wrong sha256 in lm-studio 0.2.9

### ISSUE THREAD

**Issue by TommyPec** [Homebrew/homebrew-cask#162670]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Wrong sha256 in lm-studio 0.2.9

### Command that failed

brew install lm-studio

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading lm-studio
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://s3.amazonaws.com/releases.lmstudio.ai/0.2.9/LM+Studio-darwin-arm64-0.2.9.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.25-67-g29d1be9\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://s3.amazonaws.com/releases.lmstudio.ai/0.2.9/LM+Studio-darwin-arm64-0.2.9.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.25-67-g29d1be9\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://s3.amazonaws.com/releases.lmstudio.ai/0.2.9/LM+Studio-darwin-arm64-0.2.9.zip
Already downloaded: /Users/pecos/Library/Caches/Homebrew/downloads/72150e86a085373070d258abb6666ed5a6323b23be28c285aec0815c2594e152--LM+Studio-darwin-arm64-0.2.9.zip
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/pecos/Library/Caches/Homebrew/downloads/72150e86a085373070d258abb6666ed5a6323b23be28c285aec0815c2594e152--LM+Studio-darwin-arm64-0.2.9.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/pecos/Library/Caches/Homebrew/downloads/72150e86a085373070d258abb6666ed5a6323b23be28c285aec0815c2594e152--LM+Studio-darwin-arm64-0.2.9.zip
==> /Users/pecos/Library/Caches/Homebrew/downloads/72150e86a085373070d258abb6666ed5a6323b23be28c285aec0815c2594e152--LM+Studio-darwin-arm64-0.2.9.zip is quarantined
==> Verifying checksum for '72150e86a085373070d258abb6666ed5a6323b23be28c285aec0815c2594e152--LM+Studio-darwin-arm64-0.2.9.zip'
Error: SHA256 mismatch
Expected: acefb3f5b7a34caa846badfb8e10b5bddf7d77a76763ec709f139361dcb48522
  Actual: e0773b434fe96d89c6021aa26b10ccca5aae49931e1c79e0d8199143b06b7faa
    File: /Users/pecos/Library/Caches/Homebrew/downloads/72150e86a085373070d258abb6666ed5a6323b23be28c285aec0815c2594e152--LM+Studio-darwin-arm64-0.2.9.zip
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:288:in `verify_checksum'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation_2_7.rb:428:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation_2_7.rb:428:in `block in create_validator_procedure_fast1'
/opt/homebrew/Library/Homebrew/cask/download.rb:85:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/download.rb:64:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:167:in `download'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  lua@5.3
  openssl@1.1

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  handbrake


HOMEBREW_VERSION: 4.1.25-67-g29d1be9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 29d1be9e9a602afc1e050aba53466b8ac165d91d
Last commit: 13 hours ago
Core tap JSON: 16 Dec 11:19 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.4O1QTKpi9J/org.xquartz:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.1
Rosetta 2: false
```

### Output of `brew tap`

```shell
<empty>
```

**Comment by SMillerDev** [comment]
>  I made doubly sure this is not a checksum does not match / SHA256 mismatch error (do not open an issue before trying to open a PR to fix first).

So definitely this thing then
