### ISSUE TITLE
Unable to install camunda-modeler

### ISSUE THREAD

**Issue by ihor-sviziev** [Homebrew/homebrew-cask#163347]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

installing camunda modeler through brew strated failing due to invalida certificate

### Command that failed

brew install --cask camunda-modeler

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading camunda-modeler
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.1-18-gdbb800b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://camunda.org/release/camunda-modeler/5.18.0/camunda-modeler-5.18.0-mac.zip
==> Downloading https://camunda.org/release/camunda-modeler/5.18.0/camunda-modeler-5.18.0-mac.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.1-18-gdbb800b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://camunda.org/release/camunda-modeler/5.18.0/camunda-modeler-5.18.0-mac.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.1-18-gdbb800b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/ihor/Library/Caches/Homebrew/downloads/dfad93bb44d7509fb0473060bf2ffd9e9a53ddead892329293374ff76fbed1ca--camunda-modeler-5.18.0-mac.zip.incomplete --location https://camunda.org/release/camunda-modeler/5.18.0/camunda-modeler-5.18.0-mac.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error: Download failed on Cask 'camunda-modeler' with message: Download failed: https://camunda.org/release/camunda-modeler/5.18.0/camunda-modeler-5.18.0-mac.zip
/opt/homebrew/Library/Homebrew/download_strategy.rb:447:in `rescue in fetch'
/opt/homebrew/Library/Homebrew/download_strategy.rb:444:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:55:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:180:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:100:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
➜  ~ brew doctor                                                                                                       1 ✘
Your system is ready to brew.
➜  ~ brew config                                                                                                         ✔
HOMEBREW_VERSION: 4.2.1-18-gdbb800b
ORIGIN: https://github.com/Homebrew/brew
HEAD: dbb800b7d34b36c976d94c176decb2847de7d92a
Last commit: 16 hours ago
Core tap JSON: 28 Dec 00:18 UTC
Core cask tap JSON: 28 Dec 00:18 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
➜  ~ brew tap                                                                                                            ✔
mutagen-io/mutagen
wardenenv/warden
```

**Comment by hkbertoson** [comment]
Looks like the download URL changed. I just opened a PR to fix this.

**Comment by ihor-sviziev** [comment]
Thank you for the quick fix!
