### ISSUE TITLE
jdownloader Apple Silicon

### ISSUE THREAD

**Issue by ulab** [Homebrew/homebrew-cask#163482]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

The jdownloader cask will result with an error on Apple Silicon machines:
```
Error: Failure while executing; `/usr/bin/env /opt/homebrew/Caskroom/jdownloader/48254/JDownloader\ Installer.app/Contents/MacOS/JavaApplicationStub -dir /Applications -q -Dinstall4j.suppressStdout=true -Dinstall4j.debug=false -VcreateDesktopLinkAction\$Boolean=false -VaddToDockAction\$Boolean=false` exited with 126. Here's the output:
env: /opt/homebrew/Caskroom/jdownloader/48254/JDownloader Installer.app/Contents/MacOS/JavaApplicationStub: Bad CPU type in executable
```
The jdownloader download page has a package for "Apple Silicon+Intel", but links to mega.nz and I can't find the installer on the location of currently used URL, so I am not sure how to fix it myself.

### Command that failed

brew install jdownloader

### Output of command with `--verbose --debug`

```shell
➜  ~ brew --verbose --debug install jdownloader
Error: Unknown command: --verbose
Error: Kernel.exit
/opt/homebrew/Library/Homebrew/extend/kernel.rb:83:in `exit'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:83:in `odie'
/opt/homebrew/Library/Homebrew/brew.rb:110:in `<main>'
➜  ~ brew install --verbose --debug jdownloader
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.2.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --remote-time --output /Users/balu/Library/Caches/Homebrew/api/formula.jws.json --location --time-cond /Users/balu/Library/Caches/Homebrew/api/formula.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.2.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --remote-time --output /Users/balu/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/balu/Library/Caches/Homebrew/api/cask.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading jdownloader
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/106c4f4cb32feda33ab0eb9769330711b9026c20/Casks/j/jdownloader.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/106c4f4cb32feda33ab0eb9769330711b9026c20/Casks/j/jdownloader.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://raw.githubusercontent.com/Homebrew/homebrew-cask/106c4f4cb32feda33ab0eb9769330711b9026c20/Casks/j/jdownloader.rb
Already downloaded: /Users/balu/Library/Caches/Homebrew/downloads/4035533bac701b08e50823a58ad4083d946b8f38b9fdb3e3499f21653fc5eb2e--jdownloader.rb
==> Verifying checksum for '4035533bac701b08e50823a58ad4083d946b8f38b9fdb3e3499f21653fc5eb2e--jdownloader.rb'
==> Downloading https://installer.jdownloader.org/clean/JD2Setup.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Mozilla/5.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10_15_7\)\ AppleWebKit/605.1.15\ \(KHTML,\ like\ Gecko\)\ Version/17.0\ Safari/605.1.15 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://installer.jdownloader.org/clean/JD2Setup.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Mozilla/5.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10_15_7\)\ AppleWebKit/605.1.15\ \(KHTML,\ like\ Gecko\)\ Version/17.0\ Safari/605.1.15 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://installer.jdownloader.org/clean/JD2Setup.dmg
Already downloaded: /Users/balu/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/balu/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/balu/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
==> /Users/balu/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg is quarantined
Warning: No checksum defined for cask 'jdownloader', skipping verification.
/usr/bin/env hdiutil imageinfo -format /Users/balu/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
==> Installing Cask jdownloader
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/balu/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20231230-39331-pwah34 /Users/balu/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20231230-39331-1ootw9.list -- /private/tmp/20231230-39331-k4efm0.bom
/usr/bin/env ditto --bom /private/tmp/20231230-39331-k4efm0.bom -- /private/tmp/d20231230-39331-pwah34/dmg.Tic4pa /private/tmp/d20231230-39331-ga30is
/usr/bin/env diskutil info -plist /private/tmp/d20231230-39331-pwah34/dmg.Tic4pa
/usr/bin/env diskutil eject /private/tmp/d20231230-39331-pwah34/dmg.Tic4pa
/usr/bin/env cp -pR /private/tmp/d20231230-39331-ga30is/JDownloader\ Installer.app/. /opt/homebrew/Caskroom/jdownloader/48254/JDownloader\ Installer.app
==> Verifying Gatekeeper status of /Users/balu/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/balu/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
==> /Users/balu/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg is quarantined
==> Propagating quarantine from /Users/balu/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg to /opt/homebrew/Caskroom/jdownloader/48254
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/balu/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0381\;65906a96\;\;4EED5979-2F95-46F6-B1E1-DE8DE72DE065
==> Creating metadata directory: /opt/homebrew/Caskroom/jdownloader/.metadata/48254/20231230192032.721
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/jdownloader/.metadata/48254/20231230192032.721/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::PreflightBlock
/usr/bin/env /opt/homebrew/Caskroom/jdownloader/48254/JDownloader\ Installer.app/Contents/MacOS/JavaApplicationStub -dir /Applications -q -Dinstall4j.suppressStdout=true -Dinstall4j.debug=false -VcreateDesktopLinkAction\$Boolean=false -VaddToDockAction\$Boolean=false
==> Purging files for version 48254 of Cask jdownloader
Error: Failure while executing; `/usr/bin/env /opt/homebrew/Caskroom/jdownloader/48254/JDownloader\ Installer.app/Contents/MacOS/JavaApplicationStub -dir /Applications -q -Dinstall4j.suppressStdout=true -Dinstall4j.debug=false -VcreateDesktopLinkAction\$Boolean=false -VaddToDockAction\$Boolean=false` exited with 126. Here's the output:
env: /opt/homebrew/Caskroom/jdownloader/48254/JDownloader Installer.app/Contents/MacOS/JavaApplicationStub: Bad CPU type in executable

/opt/homebrew/Library/Homebrew/system_command.rb:346:in `assert_success!'
/opt/homebrew/Library/Homebrew/system_command.rb:69:in `run!'
/opt/homebrew/Library/Homebrew/system_command.rb:34:in `run'
/opt/homebrew/Library/Homebrew/system_command.rb:38:in `run!'
/opt/homebrew/Library/Homebrew/cask/dsl/base.rb:23:in `system_command'
/Users/balu/Library/Caches/Homebrew/api-source/Homebrew/homebrew-cask/106c4f4cb32feda33ab0eb9769330711b9026c20/Cask/jdownloader.rb:19:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:49:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:49:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:28:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:242:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:235:in `install_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:111:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
➜  ~ brew doctor
Your system is ready to brew.
➜  ~ brew config
HOMEBREW_VERSION: 4.2.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7817518992920b8dbd15e48a5e6c5ad768f4ba8b
Last commit: 6 days ago
Core tap JSON: 30 Dec 19:20 UTC
Core cask tap JSON: 30 Dec 19:20 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 14
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 14-core 64-bit dunno
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
➜  ~ brew tap
```

**Comment by SMillerDev** [comment]
Is there a download link on the homepage for ARM?

**Comment by ulab** [comment]
The homepage lists:

[Download Installer macOS High Sierra or higher (Java 17, Apple Silicon+Intel)](https://mega.nz/file/nEM0CapQ#zSj72mSX4J6EALn8MBUIibY-Cn_x0wYnOs7qBUyR4fY)

**Comment by SMillerDev** [comment]
If that's the same as we download you should contact upstream that it doesn't actually work on ARM

**Comment by ulab** [comment]
It is not. Brew loads https://installer.jdownloader.org/clean/JD2Setup.dmg which results in a file that's only 5.6 MB and probably loads everything else during the installing phase.

The files they link to are 54.5 MB for the intel one and 62.7 MB for the universal one.

I will try and ask them if there are direct downloads or a universal JD2Setup.dmg installer instead.

**Comment by Bo98** [comment]
Yeah unfortunately we can't use mega.nz as they don't work over curl. If they have a universal bootstrap DMG like the existing one that would be ideal.

**Comment by ulab** [comment]
I've got a reply from the JD2 support. He mentioned that someone from the Homebrew Project has access to direct URLs for all OS/CPU variants.

So I am not sure if the links have not been upgraded to the universal installer or the installer isn't available for my M3.

**Comment by Bo98** [comment]
I'm not aware of anyone from JD2 providing us with direct URLs beyond the old x86_64-only bootstrap installer DMG we have, but if they've given it to an individual then maybe they'll come across this issue.

```
$ file /Volumes/jd2/JDownloader\ Installer.app/Contents/MacOS/JavaApplicationStub 
/Volumes/jd2/JDownloader Installer.app/Contents/MacOS/JavaApplicationStub: Mach-O 64-bit executable x86_64
```

**Comment by Bo98** [comment]
Ok I tracked it down who had the, - will take a look further.

**Comment by ulab** [comment]
I can download from both URLs after manually putting the arch into each, but it seems to be 1.70.3, while the latest is 1.70.4.1, I think.

Either way, support suggested for someone responsible to contact them directly (support at jdownloader.org) and they will send all required information. It shouldn't be too difficult of a change, especially since they have a unified installer now.

Perhaps use my ticket ID "[#WYG-977-96989]" in the subject, so the request stays together.

It's probably best to get a direct contact instead of me being a middle man ;)

**Comment by Bo98** [comment]
Ah yeah sorry I must have mistyped it. The version number is probably just the JDK so maybe not hugely important but would be nice for new builds to appear there. Will take a look at the execution issue shortly.

**Comment by ulab** [comment]
As I said, you might want to contact them first for the universal installer. That's easier than having to mess with two packages, their checksums, etc.

**Comment by bevanjkay** [comment]
As Homebrew doesn't have specific maintainers for Cask/Formulae, it doesn't make sense for a maintainer to have to contact upstream every time the `url` breaks.
It creates unnecessary maintenance burden that doesn't exist in any other cask.

I don't see why upstream can't provide you with the `urls` @ulab, as you seem to be interested in fixing the cask.
If they require any proof that a Homebrew maintainer would like you to manage this, feel free to link to this comment.

**Comment by Bo98** [comment]
I tried the latest installer from mega.nz and it seems to also exit with an error code:

```
"/Volumes/JDownloader 2/JDownloader 2 Installer.app/Contents/MacOS/JavaApplicationStub" -dir /Applications -q
echo $?
```

It seems like it does install, but something's busted towards the end that makes it exit with code 22.

**Comment by ulab** [comment]
@bevanjkay I would have asked for direct links, but didn't want to interfere with Bo98's efforts. As for the link change, I think a new type of installer (universal vs intel only) should allow for that.

@Bo98 Upstream is looking into that and will provide a new build/URL.

**Comment by indianets** [comment]
I can install jdownloader cask without issues on M1 with macOS Sonoma.

```
% brew install --cask --debug jdownloader
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading jdownloader
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
...
...
==> Installing Cask jdownloader
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/vijay/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20240106-57721-it6l1i /Users/vijay/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20240106-57721-534d2u.list -- /private/tmp/20240106-57721-whvkay.bom
/usr/bin/env ditto --bom /private/tmp/20240106-57721-whvkay.bom -- /private/tmp/d20240106-57721-it6l1i/dmg.PRZXgb /private/tmp/d20240106-57721-bh0gem
/usr/bin/env diskutil info -plist /private/tmp/d20240106-57721-it6l1i/dmg.PRZXgb
/usr/bin/env diskutil eject /private/tmp/d20240106-57721-it6l1i/dmg.PRZXgb
/usr/bin/env cp -pR /private/tmp/d20240106-57721-bh0gem/JDownloader\ Installer.app/. /opt/homebrew/Caskroom/jdownloader/48254/JDownloader\ Installer.app
==> Verifying Gatekeeper status of /Users/vijay/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/vijay/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
==> /Users/vijay/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg is quarantined
==> Propagating quarantine from /Users/vijay/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg to /opt/homebrew/Caskroom/jdownloader/48254
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/vijay/Library/Caches/Homebrew/downloads/598f1ad471e12602e49d18e41f5359e0043fb55058fa2909d6d019a51bf8d152--JD2Setup.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;65984d67\;Homebrew\\x20Cask\;FD876340-9FDF-49D7-AB67-E02C59B97B58
==> Creating metadata directory: /opt/homebrew/Caskroom/jdownloader/.metadata/48254/20240105184143.864
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/jdownloader/.metadata/48254/20240105184143.864/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::PreflightBlock
/usr/bin/env /opt/homebrew/Caskroom/jdownloader/48254/JDownloader\ Installer.app/Contents/MacOS/JavaApplicationStub -dir /Applications -q -Dinstall4j.suppressStdout=true -Dinstall4j.debug=false -VcreateDesktopLinkAction\$Boolean=false -VaddToDockAction\$Boolean=false
🍺  jdownloader was successfully installed!
```

**Comment by ulab** [comment]
> I can install jdownloader cask without issues on M1 with macOS Sonoma.

Do you have Rosetta installed so you can run apps built for Intel Macs?

**Comment by indianets** [comment]
Sorry for my ignorance, yes it installs Intel version.

**Comment by jiaz83** [comment]
> It seems like it does install, but something's busted towards the end that makes it exit with code 22. It does this 100% of the time without any Homebrew involved.
fixed

> If upstream are able to track down and fix the cause, and upload a new version to installer.jdownload.org/homebrew (or equivalent) then we will definitely use it. The exit code issue is definitely not caused by anything on our side given I can reproduce it with just the command above.
Updated and available [here](https://installer.jdownloader.org/homebrew/)

**Comment by Bo98** [comment]
Thank you! Will take a look.

**Comment by jiaz83** [comment]
> Thank you! Will take a look.

If you need anything changed/fixed or being different, just let me know!

**Comment by ulab** [comment]
@Bo98 Did you take a look yet? :-)

**Comment by ulab** [comment]
I have tried replacing the old installer with `JDownloader2Setup_macos-universal_v21_0_1.dmg` in the Ruby file, but it results in

```
Error: Failure while executing; `/usr/bin/env /opt/homebrew/Caskroom/jdownloader/48254/JDownloader\ Installer.app/Contents/MacOS/JavaApplicationStub -dir /Applications -q -Dinstall4j.suppressStdout=true -Dinstall4j.debug=false -VcreateDesktopLinkAction\$Boolean=false -VaddToDockAction\$Boolean=false` exited with 127. Here's the output:
env: /opt/homebrew/Caskroom/jdownloader/48254/JDownloader Installer.app/Contents/MacOS/JavaApplicationStub: No such file or directory
```

Extracting the App from the dmg and running it manually seemed to work - even though it seems to have ignored the parameters.

```
$  ~ /Applications/JDownloader\ 2\ Installer.app/Contents/MacOS/JavaApplicationStub -dir /Applications -q -Dinstall4j.suppressStdout=true -Dinstall4j.debug=false -VcreateDesktopLinkAction$Boolean=false -VaddToDockAction$Boolean=false
Simple boolean - boolean
Simple class java.lang.Boolean - Boolean
Simple class java.lang.String - String
Simple double - double
Simple class java.lang.Number - Number
Simple class java.lang.Double - Double
Simple int - int
Simple class java.lang.Integer - Integer
Simple float - float
Simple class java.lang.Float - Float
Simple long - long
Simple class java.lang.Long - Long
Simple byte - byte
Simple class java.lang.Byte - Byte
Simple short - short
Simple class java.lang.Short - Short
Simple char - char
Simple class java.lang.Character - Character
Simple class java.lang.Object - Object
Simple class java.util.Date - Date
The installation directory has been set to /Applications/JDownloader 2.0.240111.
Import proxyList
null
MacOS: detected sw_vers:14.2.1
StepID: CREATE_PACKAGE
StepID: DOWNLOAD
StepID: EXTRACTION
StepID: PREPARE_INSTALL
StepID: PREPARE_INSTALL
StepID: INSTALLING
StepID: INSTALLING
StepID: CLIENT_OPTIONS
StepID: CLEANUP
StepID: CREATE_PACKAGE
StepID: DOWNLOAD
StepID: EXTRACTION
StepID: PREPARE_INSTALL
StepID: PREPARE_INSTALL
StepID: INSTALLING
StepID: INSTALLING
StepID: CLIENT_OPTIONS
StepID: CLEANUP
CustomProxyListPath: /Applications/JDownloader 2.0.240111/cfg/org.jdownloader.settings.InternetConnectionSettings.customproxylist.json
[1/3|Priority: 0]ShutdownController: start item->ShutdownEvent: SaveAllStorageHandler
[1/3|Priority: 0]ShutdownController: item ended after->0
[Done:1/3]
[2/3|Priority: 0]ShutdownController: start item->ShutdownEvent: ProcessDelayedWrites num=0
[2/3|Priority: 0]ShutdownController: item ended after->0
[Done:2/3]
[3/3|Priority: 0]ShutdownController: start item->ShutdownEvent: Save JSonStorages
[3/3|Priority: 0]ShutdownController: item ended after->0
[Done:3/3]
Shutdown Hooks Finished
```

My knowledge of brew is too limited to find the cause for the above issue.

**Comment by Bo98** [comment]
I was away last week so haven't had a chance to look yet, but it looks like you forgot to change the `JDownloader Installer.app` to `JDownloader 2 Installer.app` in the Ruby file

**Comment by ulab** [comment]
Duh. You are correct.

I am not sure how to handle the version numbering of it though either.

The stanza says `version "48254"` which is the latest revision from [the livecheck](https://svn.jdownloader.org/build.php). Should it be replaced with the version of the installer file and used in the `url` stanza? And what about the livecheck then.

I wish I could help more instead of asking stupid questions ;-)

**Comment by jiaz83** [comment]
> The stanza says `version "48254"` which is the latest revision from [the livecheck](https://svn.jdownloader.org/build.php). Should it be replaced with the version of the installer file and used in the `url` stanza? And what about the livecheck then.

You should not use that at all. JDownloader will update itself. All installers are online installer and will always install the latest available version. We do update them irregular but no need to re-install with newer installer then. So installer should be used for first/initial installation and then JDownloader will update itself

**Comment by ulab** [comment]
I know, that's why I am confused with what's used in the file. It has `auto_updates true`, so it won't get updated by brew.

I guess the installer version `v21_0_1` is more relevant then.

**Comment by Bo98** [comment]
We've only just recently added arm64 CI so I will try this out tomorrow.

**Comment by jiaz83** [comment]
I've updated URLs, please use https://installer.jdownloader.org/homebrew/latest/ URLs as the links are static

**Comment by daeho-ro** [comment]
Anyone tested?
