### ISSUE TITLE
vlc 2.0.20 install checksum error

### ISSUE THREAD

**Issue by d7an** [Homebrew/homebrew-cask#163462]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

VLC 2.0.30 cask install reported that it has an incorrect checksum of the downloaded dmg file.

From [vlc.com](https://www.videolan.org/)
```
Downloading VLC 3.0.20 for macOS
Thanks! Your download will start in few seconds...
If not, [click here](https://mirror.safe-con.dk/vlc/vlc/3.0.20/macosx/vlc-3.0.20-arm64.dmg).
SHA-256 checksum: 5d5f0ee52d81982a622f4021928a64b4705a9554499e20c33d0bac22590b118e

```

brew install will result with a downloaded dmg file that fails the checksum check.  If you open up the dmg file, you'll find that it's actually a html file, with a redirect link to then download the actual dmg file.
```
❯ brew install --cask vlc
==> Upgrading 1 outdated package:
vlc 3.0.18 -> 3.0.20
==> Upgrading vlc
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/964d865bc6ae274899a0f8b2da8d691a58ffc6dd/Casks/v/vlc.rb
Already downloaded: ~/Library/Caches/Homebrew/downloads/8ef8df418239b402aeec799410af1ee5ad8dffde8e248d1fca5332cb2e6bb316--vlc.rb
==> Verifying checksum for '8ef8df418239b402aeec799410af1ee5ad8dffde8e248d1fca5332cb2e6bb316--vlc.rb'
==> Downloading https://get.videolan.org/vlc/3.0.20/macosx/vlc-3.0.20-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.1-30-gf3c687e\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/dtan/Library/Caches/Homebrew/downloads/7ebc0bd6a2923078fb4d597a0e622be3d61748ad149fc3088a14f0122f70fa0e--vlc-3.0.20-arm64.dmg.incomplete --location https://get.videolan.org/vlc/3.0.20/macosx/vlc-3.0.20-arm64.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25885    0 25885    0     0  22270      0 --:--:--  0:00:01 --:--:-- 22276
==> Verifying checksum for '7ebc0bd6a2923078fb4d597a0e622be3d61748ad149fc3088a14f0122f70fa0e--vlc-3.0.20-arm64.dmg'
==> Purging files for version 3.0.20 of Cask vlc
Error: vlc: SHA256 mismatch
Expected: 5d5f0ee52d81982a622f4021928a64b4705a9554499e20c33d0bac22590b118e
  Actual: 7ec8654c00c5e8e90a3448373c4c5ff41d228cc7ad93be77442dbdc04103a760
    File: ~/Library/Caches/Homebrew/downloads/7ebc0bd6a2923078fb4d597a0e622be3d61748ad149fc3088a14f0122f70fa0e--vlc-3.0.20-arm64.dmg
To retry an incomplete download, remove the file above.

```

### Command that failed

brew install --cask vlc

### Output of command with `--verbose --debug`

```shell
❯ brew install --cask vlc --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading vlc
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/vlc/.metadata/3.0.18/20221130021218.161/Casks/vlc.rb
vlc 3.0.18 -> 3.0.20
==> Started upgrade process for Cask vlc
==> Upgrading vlc
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading homebrew/cask-versions/vlc-nightly
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/964d865bc6ae274899a0f8b2da8d691a58ffc6dd/Casks/v/vlc.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.1-30-gf3c687e\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/964d865bc6ae274899a0f8b2da8d691a58ffc6dd/Casks/v/vlc.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.1-30-gf3c687e\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://raw.githubusercontent.com/Homebrew/homebrew-cask/964d865bc6ae274899a0f8b2da8d691a58ffc6dd/Casks/v/vlc.rb
Already downloaded: ~/Library/Caches/Homebrew/downloads/8ef8df418239b402aeec799410af1ee5ad8dffde8e248d1fca5332cb2e6bb316--vlc.rb
==> Verifying checksum for '8ef8df418239b402aeec799410af1ee5ad8dffde8e248d1fca5332cb2e6bb316--vlc.rb'
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.1-30-gf3c687e\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://get.videolan.org/vlc/3.0.20/macosx/vlc-3.0.20-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.1-30-gf3c687e\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://get.videolan.org/vlc/3.0.20/macosx/vlc-3.0.20-arm64.dmg
==> Downloading https://get.videolan.org/vlc/3.0.20/macosx/vlc-3.0.20-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.1-30-gf3c687e\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output ~/Library/Caches/Homebrew/downloads/7ebc0bd6a2923078fb4d597a0e622be3d61748ad149fc3088a14f0122f70fa0e--vlc-3.0.20-arm64.dmg.incomplete --location https://get.videolan.org/vlc/3.0.20/macosx/vlc-3.0.20-arm64.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25885    0 25885    0     0  21698      0 --:--:--  0:00:01 --:--:-- 21715
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of ~/Library/Caches/Homebrew/downloads/7ebc0bd6a2923078fb4d597a0e622be3d61748ad149fc3088a14f0122f70fa0e--vlc-3.0.20-arm64.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine ~/Library/Caches/Homebrew/downloads/7ebc0bd6a2923078fb4d597a0e622be3d61748ad149fc3088a14f0122f70fa0e--vlc-3.0.20-arm64.dmg
==> ~/Library/Caches/Homebrew/downloads/7ebc0bd6a2923078fb4d597a0e622be3d61748ad149fc3088a14f0122f70fa0e--vlc-3.0.20-arm64.dmg is not quarantined
==> Quarantining ~/Library/Caches/Homebrew/downloads/7ebc0bd6a2923078fb4d597a0e622be3d61748ad149fc3088a14f0122f70fa0e--vlc-3.0.20-arm64.dmg
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift ~/Library/Caches/Homebrew/downloads/7ebc0bd6a2923078fb4d597a0e622be3d61748ad149fc3088a14f0122f70fa0e--vlc-3.0.20-arm64.dmg https://get.videolan.org/vlc/3.0.20/macosx/vlc-3.0.20-arm64.dmg https://www.videolan.org/vlc/
==> Verifying checksum for '7ebc0bd6a2923078fb4d597a0e622be3d61748ad149fc3088a14f0122f70fa0e--vlc-3.0.20-arm64.dmg'
==> Purging files for version 3.0.20 of Cask vlc
Error: vlc: SHA256 mismatch
Expected: 5d5f0ee52d81982a622f4021928a64b4705a9554499e20c33d0bac22590b118e
  Actual: 7ec8654c00c5e8e90a3448373c4c5ff41d228cc7ad93be77442dbdc04103a760
    File: ~/Library/Caches/Homebrew/downloads/7ebc0bd6a2923078fb4d597a0e622be3d61748ad149fc3088a14f0122f70fa0e--vlc-3.0.20-arm64.dmg
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:288:in `verify_checksum'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation_2_7.rb:1029:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation_2_7.rb:1029:in `block in create_validator_procedure_medium1'
/opt/homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation_2_7.rb:428:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation_2_7.rb:428:in `block in create_validator_procedure_fast1'
/opt/homebrew/Library/Homebrew/cask/download.rb:85:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/download.rb:64:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:180:in `download'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:193:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:114:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/install.rb:250:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor                              
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  difffork
  meld
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/warning-1.3.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/tapioca-0.11.14/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/yard-sorbet-0.8.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/yard-0.9.34/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/stackprof-0.2.25/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/x86_64-darwin-15/3.1.0-static/stackprof-0.2.25
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/spoom-1.2.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/thor-1.3.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/syntax_tree-6.2.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-static-and-runtime-0.5.11155/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-0.5.11155/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-static-0.5.11155-universal-darwin/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/simplecov-cobertura-2.1.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/simplecov-0.22.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/simplecov_json_formatter-0.1.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/simplecov-html-0.12.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/ruby-prof-1.6.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/x86_64-darwin-15/3.1.0-static/ruby-prof-1.6.3
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/ruby-macho-4.0.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-sorbet-0.7.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-rspec-2.25.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-rails-2.23.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-performance-1.20.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-factory_bot-2.24.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-capybara-2.19.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-1.59.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/unicode-display_width-2.5.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/ruby-progressbar-1.13.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-ast-1.30.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec_junit_formatter-0.6.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-sorbet-1.9.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-retry-0.6.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-its-1.3.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-github-2.4.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-3.12.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-mocks-3.12.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.12.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-core-3.12.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-support-3.12.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/ronn-0.7.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rexml-3.2.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rdiscount-2.2.7.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/x86_64-darwin-15/3.1.0-static/rdiscount-2.2.7.2
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rbi-0.1.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rack-3.0.8/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/pry-0.14.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/prism-0.19.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/x86_64-darwin-15/3.1.0-static/prism-0.19.0
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/prettier_print-1.2.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/plist-3.7.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/patchelf-1.4.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/parlour-8.1.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rainbow-3.1.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/parser-3.2.2.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/racc-1.7.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/x86_64-darwin-15/3.1.0-static/racc-1.7.3
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/parallel_tests-4.4.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/parallel-1.24.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/netrc-0.11.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/method_source-1.0.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/language_server-protocol-3.17.0.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/json_schemer-2.1.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/simpleidn-0.2.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/unf-0.1.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/unf_ext-0.0.9.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/x86_64-darwin-15/3.1.0-static/unf_ext-0.0.9.1
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/regexp_parser-2.8.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/json-2.7.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/x86_64-darwin-15/3.1.0-static/json-2.7.1
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/hpricot-0.8.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/x86_64-darwin-15/3.1.0-static/hpricot-0.8.6
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/hana-1.3.7/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/erubi-1.12.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/elftools-1.2.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/docile-1.4.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/diff-lcs-1.5.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/highline-2.0.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/coderay-1.1.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/byebug-11.1.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/x86_64-darwin-15/3.1.0-static/byebug-11.1.3
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.17.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/x86_64-darwin-15/3.1.0-static/bootsnap-1.17.0
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/msgpack-1.7.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/x86_64-darwin-15/3.1.0-static/msgpack-1.7.2
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bindata-2.4.15/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/ast-2.4.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/addressable-2.8.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/public_suffix-5.0.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.7.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.12/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/tzinfo-2.0.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/minitest-5.20.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/i18n-1.14.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/vendor_ruby/3.1.0
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/vendor_ruby/3.1.0/arm64-darwin20
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/vendor_ruby
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/arm64-darwin20
/opt/homebrew/Library/Homebrew
==> Homebrew Version
4.2.1-30-gf3c687e
==> macOS
14.2.1
==> SIP
Enabled
==> Homebrew Cask Staging Location
/opt/homebrew/Caskroom
==> Homebrew Cask Taps:
/opt/homebrew/Library/Taps/homebrew/homebrew-cask-versions (249 casks)
/opt/homebrew/Library/Taps/homebrew/homebrew-cask-fonts (2142 casks)
/opt/homebrew/Library/Taps/artginzburg/homebrew-tap (5 casks)

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1
  youtube-dl


❯ brew config
HOMEBREW_VERSION: 4.2.1-30-gf3c687e
ORIGIN: https://github.com/Homebrew/brew
HEAD: f3c687e4728d5a678e9ebd63a9bf95e7cc7a0ac0
Last commit: 32 hours ago
Core tap HEAD: 128412134549c4dcdb921a369b8d080e4b53269f
Core tap last commit: 62 minutes ago
Core tap JSON: 30 Dec 04:30 UTC
Core cask tap HEAD: 964d865bc6ae274899a0f8b2da8d691a58ffc6dd
Core cask tap last commit: 74 minutes ago
Core cask tap JSON: 30 Dec 04:30 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CURLRC: TRUE
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_SORBET_RUNTIME: set
HOMEBREW_VERBOSE: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
❯ brew tap   
artginzburg/tap
buo/cask-upgrade
claui/whence
homebrew/autoupdate
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/command-not-found
homebrew/core
homebrew/services
romkatv/powerlevel10k
samtay/tui
saulpw/vd
teamookla/speedtest
```

**Comment by bevanjkay** [comment]
>  I made doubly sure this is not a checksum does not match / SHA256 mismatch error (do not open an issue before trying to open a PR to fix first).

What steps have you taken to try to open a PR to fix this?

**Comment by d7an** [comment]
> > I made doubly sure this is not a checksum does not match / SHA256 mismatch error (do not open an issue before trying to open a PR to fix first).
> 
> What steps have you taken to try to open a PR to fix this?

Hi Season Greetings!
I've made as much observation as possible up to the point where I think it's broken. Which is that the download URL doesn't actually initiate the download, but brings you to a download page, where a "timed" browser redirects then kicks off the download. I do not know how the curl command can be adapted to handle that.

**Comment by Bo98** [comment]
Seems like they have changed it so it doesn't respond to `curl` anymore (but does respond to `wget`).

**Comment by Bo98** [comment]
Seems to work for me locally now. Perhaps was a mirror issue?

**Comment by krehel** [comment]
Possibly. I also tried a few times over the past couple days and could not reproduce.
