### ISSUE TITLE
Failed to install ImHex

### ISSUE THREAD

**Issue by oxoocoffee** [Homebrew/homebrew-cask#164012]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Yesterday I attempted to install ```imhex```. At some point, I had ```imhex``` installed. But do not remember if it was manually installed or using ```brew```.

### Command that failed

brew install --cask imhex

### Output of command with `--verbose --debug`

```shell
$ brew install --force --verbose --debug --cask imhex

/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading imhex
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://github.com/WerWolv/ImHex/releases/download/v1.32.2/imhex-1.32.2-macOS-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.3-2-g9cdfcd3\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/WerWolv/ImHex/releases/download/v1.32.2/imhex-1.32.2-macOS-arm64.dmg
Already downloaded: /Users/rob/Library/Caches/Homebrew/downloads/c6afe815dc6dc6087c916c4d17eea00d8fcde49da017c611a1d16e7db7720c2a--imhex-1.32.2-macOS-arm64.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/rob/Library/Caches/Homebrew/downloads/c6afe815dc6dc6087c916c4d17eea00d8fcde49da017c611a1d16e7db7720c2a--imhex-1.32.2-macOS-arm64.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/rob/Library/Caches/Homebrew/downloads/c6afe815dc6dc6087c916c4d17eea00d8fcde49da017c611a1d16e7db7720c2a--imhex-1.32.2-macOS-arm64.dmg
==> /Users/rob/Library/Caches/Homebrew/downloads/c6afe815dc6dc6087c916c4d17eea00d8fcde49da017c611a1d16e7db7720c2a--imhex-1.32.2-macOS-arm64.dmg is quarantined
==> Verifying checksum for 'c6afe815dc6dc6087c916c4d17eea00d8fcde49da017c611a1d16e7db7720c2a--imhex-1.32.2-macOS-arm64.dmg'
/usr/bin/env hdiutil imageinfo -format /Users/rob/Library/Caches/Homebrew/downloads/c6afe815dc6dc6087c916c4d17eea00d8fcde49da017c611a1d16e7db7720c2a--imhex-1.32.2-macOS-arm64.dmg
==> Installing Cask imhex
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/rob/Library/Caches/Homebrew/downloads/c6afe815dc6dc6087c916c4d17eea00d8fcde49da017c611a1d16e7db7720c2a--imhex-1.32.2-macOS-arm64.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20240108-69283-jei7vr /Users/rob/Library/Caches/Homebrew/downloads/c6afe815dc6dc6087c916c4d17eea00d8fcde49da017c611a1d16e7db7720c2a--imhex-1.32.2-macOS-arm64.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20240108-69283-1uis5j.list -- /private/tmp/20240108-69283-80mi6j.bom
/usr/bin/env ditto --bom /private/tmp/20240108-69283-80mi6j.bom -- /private/tmp/d20240108-69283-jei7vr/dmg.meviSe /private/tmp/d20240108-69283-j49f7c
/usr/bin/env diskutil info -plist /private/tmp/d20240108-69283-jei7vr/dmg.meviSe
/usr/bin/env diskutil eject disk4s1
/usr/bin/env cp -pR /private/tmp/d20240108-69283-j49f7c/ImHex.app/. /opt/homebrew/Caskroom/imhex/1.32.2/ImHex.app
==> Verifying Gatekeeper status of /Users/rob/Library/Caches/Homebrew/downloads/c6afe815dc6dc6087c916c4d17eea00d8fcde49da017c611a1d16e7db7720c2a--imhex-1.32.2-macOS-arm64.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/rob/Library/Caches/Homebrew/downloads/c6afe815dc6dc6087c916c4d17eea00d8fcde49da017c611a1d16e7db7720c2a--imhex-1.32.2-macOS-arm64.dmg
==> /Users/rob/Library/Caches/Homebrew/downloads/c6afe815dc6dc6087c916c4d17eea00d8fcde49da017c611a1d16e7db7720c2a--imhex-1.32.2-macOS-arm64.dmg is quarantined
==> Propagating quarantine from /Users/rob/Library/Caches/Homebrew/downloads/c6afe815dc6dc6087c916c4d17eea00d8fcde49da017c611a1d16e7db7720c2a--imhex-1.32.2-macOS-arm64.dmg to /opt/homebrew/Caskroom/imhex/1.32.2
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/rob/Library/Caches/Homebrew/downloads/c6afe815dc6dc6087c916c4d17eea00d8fcde49da017c611a1d16e7db7720c2a--imhex-1.32.2-macOS-arm64.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;659839a0\;Homebrew\\x20Cask\;B0A4AC41-93CD-4D40-A930-BEB3B1683BF4
==> Creating metadata directory: /opt/homebrew/Caskroom/imhex/.metadata/1.32.2/20240108152830.188
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/imhex/.metadata/1.32.2/20240108152830.188/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::App
==> Purging files for version 1.32.2 of Cask imhex
Error: It seems the App source '/opt/homebrew/Caskroom/imhex/1.32.2/imhex.app' is not there.
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:39:in `move'
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:19:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:243:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:236:in `install_artifacts'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/call_validation.rb:256:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11155/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:112:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor  
                  
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

$ brew config

HOMEBREW_VERSION: 4.2.3-2-g9cdfcd3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9cdfcd353ba099178633edeab0071d649a1fbe42
Last commit: 2 hours ago
Core tap HEAD: cb61eb6d59fb34d24bcb541002822a1e504927e1
Core tap last commit: 32 minutes ago
Core tap JSON: 08 Jan 15:23 UTC
Core cask tap HEAD: 9d812e2eb38535143b76fe70142468bb67503e48
Core cask tap last commit: 23 minutes ago
Core cask tap JSON: 08 Jan 15:23 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0.0
HOMEBREW_EDITOR: vi
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
$ brew tap

beeftornado/rmtree
buo/cask-upgrade
gitea/tap
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/core
homebrew/services
osx-cross/avr
```

**Comment by SMillerDev** [comment]
> Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
> The default macOS filesystem is case-insensitive. Please report any apparent problems.

It's probably this.
