### ISSUE TITLE
Permission error updating playdate-simulator to 2.2.0

### ISSUE THREAD

**Issue by SlaunchaMan** [Homebrew/homebrew-cask#164483]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

When I try to update the `playdate-simulator` cask, I’m getting a permission denied error:

```
Error: playdate-simulator: Permission denied @ apply2files - /usr/local/bin/arm-none-eabi-addr2line
```

### Command that failed

brew upgrade playdate-simulator

### Output of command with `--verbose --debug`

```shell
~$ brew upgrade playdate-simulator --verbose --debug                           
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading playdate-simulator
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/playdate-simulator/.metadata/2.1.1/20231223191913.788/Casks/playdate-simulator.rb
playdate-simulator 2.1.1 -> 2.2.0
==> Started upgrade process for Cask playdate-simulator
==> Upgrading playdate-simulator
==> Printing caveats
==> Caveats
Installing playdate-simulator means you have AGREED to the license at:
  https://play.date/dev/sdk-license

==> Cask::Installer#fetch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/fe1746bb09a3dedd6a78c513dff536d55c77102d/Casks/p/playdate-simulator.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.4-8-gcea60ca\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/fe1746bb09a3dedd6a78c513dff536d55c77102d/Casks/p/playdate-simulator.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.4-8-gcea60ca\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://raw.githubusercontent.com/Homebrew/homebrew-cask/fe1746bb09a3dedd6a78c513dff536d55c77102d/Casks/p/playdate-simulator.rb
Already downloaded: /Users/jeff/Library/Caches/Homebrew/downloads/e7a9d7f0af493e0a6657f21308bb1f42bb10a71a4a8d5a563a813c899f89ddad--playdate-simulator.rb
==> Verifying checksum for 'e7a9d7f0af493e0a6657f21308bb1f42bb10a71a4a8d5a563a813c899f89ddad--playdate-simulator.rb'
==> Downloading https://download-keycdn.panic.com/playdate_sdk/PlaydateSDK-2.2.0.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.4-8-gcea60ca\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://download-keycdn.panic.com/playdate_sdk/PlaydateSDK-2.2.0.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.4-8-gcea60ca\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://download-keycdn.panic.com/playdate_sdk/PlaydateSDK-2.2.0.zip
Already downloaded: /Users/jeff/Library/Caches/Homebrew/downloads/6cf676275e010207b87afef23353a6869329ce3716c7cc48ed3c6e36e29c4817--PlaydateSDK-2.2.0.zip
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/jeff/Library/Caches/Homebrew/downloads/6cf676275e010207b87afef23353a6869329ce3716c7cc48ed3c6e36e29c4817--PlaydateSDK-2.2.0.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/jeff/Library/Caches/Homebrew/downloads/6cf676275e010207b87afef23353a6869329ce3716c7cc48ed3c6e36e29c4817--PlaydateSDK-2.2.0.zip
==> /Users/jeff/Library/Caches/Homebrew/downloads/6cf676275e010207b87afef23353a6869329ce3716c7cc48ed3c6e36e29c4817--PlaydateSDK-2.2.0.zip is quarantined
==> Verifying checksum for '6cf676275e010207b87afef23353a6869329ce3716c7cc48ed3c6e36e29c4817--PlaydateSDK-2.2.0.zip'
/usr/bin/env hdiutil imageinfo -format /Users/jeff/Library/Caches/Homebrew/downloads/6cf676275e010207b87afef23353a6869329ce3716c7cc48ed3c6e36e29c4817--PlaydateSDK-2.2.0.zip
/usr/bin/env zipinfo -1 /Users/jeff/Library/Caches/Homebrew/downloads/6cf676275e010207b87afef23353a6869329ce3716c7cc48ed3c6e36e29c4817--PlaydateSDK-2.2.0.zip
==> Uninstalling artifacts
==> 4 artifacts defined
#<Cask::ArtifactSet: {#<Cask::Artifact::PreflightBlock:0x000000010873f3d0 @cask=#<Cask playdate-simulator /opt/homebrew/Caskroom/playdate-simulator/.metadata/2.1.1/20231223191913.788/Casks/playdate-simulator.rb>, @dsl_args=[], @directives={:uninstall_preflight=>#<Proc:0x000000010873f4e8 /opt/homebrew/Caskroom/playdate-simulator/.metadata/2.1.1/20231223191913.788/Casks/playdate-simulator.rb:20>}>, #<Cask::Artifact::Uninstall:0x000000010873ee58 @cask=#<Cask playdate-simulator /opt/homebrew/Caskroom/playdate-simulator/.metadata/2.1.1/20231223191913.788/Casks/playdate-simulator.rb>, @dsl_args=[{:pkgutil=>"date.play.sdk", :trash=>"~/Developer/PlaydateSDK", :delete=>"/usr/local/playdate", :rmdir=>"~/Developer"}], @directives={:pkgutil=>"date.play.sdk", :trash=>"~/Developer/PlaydateSDK", :delete=>"/usr/local/playdate", :rmdir=>"~/Developer", :signal=>[]}>, #<Cask::Artifact::Pkg:0x000000010873fe98 @cask=#<Cask playdate-simulator /opt/homebrew/Caskroom/playdate-simulator/.metadata/2.1.1/20231223191913.788/Casks/playdate-simulator.rb>, @dsl_args=["PlaydateSDK.pkg"], @path=#<Pathname:/opt/homebrew/Caskroom/playdate-simulator/2.1.1/PlaydateSDK.pkg>, @stanza_options={}>, #<Cask::Artifact::Zap:0x000000010873e688 @cask=#<Cask playdate-simulator /opt/homebrew/Caskroom/playdate-simulator/.metadata/2.1.1/20231223191913.788/Casks/playdate-simulator.rb>, @dsl_args=[{:trash=>"~/.Playdate"}], @directives={:trash=>"~/.Playdate", :signal=>[]}>}>
==> Uninstalling artifact of class Cask::Artifact::PreflightBlock
==> Purging files for version 2.2.0 of Cask playdate-simulator
Error: playdate-simulator: Permission denied @ apply2files - /usr/local/bin/arm-none-eabi-addr2line
/opt/homebrew/Caskroom/playdate-simulator/.metadata/2.1.1/20231223191913.788/Casks/playdate-simulator.rb:22:in `unlink'
/opt/homebrew/Caskroom/playdate-simulator/.metadata/2.1.1/20231223191913.788/Casks/playdate-simulator.rb:22:in `unlink'
/opt/homebrew/Caskroom/playdate-simulator/.metadata/2.1.1/20231223191913.788/Casks/playdate-simulator.rb:22:in `block (3 levels) in load'
/opt/homebrew/Caskroom/playdate-simulator/.metadata/2.1.1/20231223191913.788/Casks/playdate-simulator.rb:21:in `each'
/opt/homebrew/Caskroom/playdate-simulator/.metadata/2.1.1/20231223191913.788/Casks/playdate-simulator.rb:21:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:49:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:49:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:32:in `uninstall_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:469:in `block in uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:466:in `uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:425:in `start_upgrade'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:196:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:114:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:260:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:141:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
~$ brew doctor                                                                 
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1
~$ brew config                                                                 
HOMEBREW_VERSION: 4.2.4-8-gcea60ca
ORIGIN: https://github.com/Homebrew/brew
HEAD: cea60ca745f7b461d7aa282a21b1080cd09b3fab
Last commit: 2 hours ago
Core tap JSON: 15 Jan 18:40 UTC
Core cask tap JSON: 15 Jan 18:40 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false
```

### Output of `brew tap`

```shell
~$ brew tap                                                                    
homebrew/bundle
muter-mutation-testing/formulae
spmdestinations/tap
```

**Comment by bevanjkay** [comment]
What is the output of `ls -l /usr/local/bin/arm-none-eabi-addr2line`

**Comment by SlaunchaMan** [comment]
```
lrwxr-xr-x  1 jeff  admin  81 Mar  6  2022 /usr/local/bin/arm-none-eabi-addr2line -> /usr/local/playdate/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-addr2line
```

**Comment by krehel** [comment]
Able to replicate.

The issue (for me, and I assume the same for @SlaunchaMan) is the files in `/usr/local/bin` are permissioned to `user:admin` (as above) but the `/usr/local/bin` folder is permissioned as `root:wheel` and the `uninstall_preflight` fails because it is trying to unlink files it does not have permissions to.

Hacky, temporary workaround:

1. Permission temporarily `/usr/local/bin` to allow `other` to have `rwx`, e.g. change permission from 755 => 757 on only that folder and _not_ recursive.
2. Run the upgrade, which should allow the modification of the files (as the upgrade deletes files and then replaces them)
3. Revert the folder permissions back to the previous level of 755.

The cask itself I will submit a patch to use the Cask-internal function that does sudo + remove if needed, rather than a normal unlink.
