### ISSUE TITLE
mono-mdk checksum mismatch

### ISSUE THREAD

**Issue by ice-j** [Homebrew/homebrew-cask#165876]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

It looks like the checksum for the same version of mono-mdk has updated. 

I manually downloaded the file and got the new checksum using both `shasum` and `openssl sha256`.
Both of them matched the new checksum so I'm updating the cask to match this change.

#165873 

### Command that failed

brew install mono-mdk

### Output of command with `--verbose --debug`

```shell
➜  m git:(master) brew install --cask mono-mdk --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading mono-mdk
==> Cask::Installer#install
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading homebrew/cask-versions/mono-mdk-for-visual-studio
==> Printing caveats
==> Caveats
Installing mono-mdk removes mono and mono dependant formula binaries in
/usr/local/bin and adds mono-mdk to /private/etc/paths.d/
You may want to:

  brew unlink {formula} && brew link {formula}

and/or remove /private/etc/paths.d/mono-commands

==> Cask::Installer#fetch
==> Downloading https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.199.macos10.xamarin.universal.pkg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.6-72-g8f89403\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.3\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.199.macos10.xamarin.universal.pkg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.6-72-g8f89403\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.3\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.199.macos10.xamarin.universal.pkg
Already downloaded: /Users/icej/Library/Caches/Homebrew/downloads/de1d154214acc997edcdc7d4cb2f6814d43c638e030aab236cb31e655087b93b--MonoFramework-MDK-6.12.0.199.macos10.xamarin.universal.pkg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/icej/Library/Caches/Homebrew/downloads/de1d154214acc997edcdc7d4cb2f6814d43c638e030aab236cb31e655087b93b--MonoFramework-MDK-6.12.0.199.macos10.xamarin.universal.pkg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/icej/Library/Caches/Homebrew/downloads/de1d154214acc997edcdc7d4cb2f6814d43c638e030aab236cb31e655087b93b--MonoFramework-MDK-6.12.0.199.macos10.xamarin.universal.pkg
==> /Users/icej/Library/Caches/Homebrew/downloads/de1d154214acc997edcdc7d4cb2f6814d43c638e030aab236cb31e655087b93b--MonoFramework-MDK-6.12.0.199.macos10.xamarin.universal.pkg is quarantined
==> Verifying checksum for 'de1d154214acc997edcdc7d4cb2f6814d43c638e030aab236cb31e655087b93b--MonoFramework-MDK-6.12.0.199.macos10.xamarin.universal.pkg'
Error: SHA256 mismatch
Expected: 65d755bdc7d0b017ddaa211544f0d89a7836c5e3549c63fe5c2fb8f69c649489
  Actual: bd578dc2aa15e19411e9bf1c2ceadec50d3d05c1ab61c02dcc22fa2d50d7ddb7
    File: /Users/icej/Library/Caches/Homebrew/downloads/de1d154214acc997edcdc7d4cb2f6814d43c638e030aab236cb31e655087b93b--MonoFramework-MDK-6.12.0.199.macos10.xamarin.universal.pkg
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:291:in `verify_checksum'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/call_validation_2_7.rb:687:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/call_validation_2_7.rb:687:in `block in create_validator_procedure_fast1'
/opt/homebrew/Library/Homebrew/cask/download.rb:85:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/download.rb:64:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:181:in `download'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11223/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
➜  homebrew git:(master) brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  android-sdk

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  mono
  openssl@1.1

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc







------------------------





➜  homebrew git:(master) brew config
HOMEBREW_VERSION: 4.2.6-72-g8f89403
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8f89403b23df018f9bd7dcd7d88890aedc3411fe
Last commit: 10 minutes ago
Core tap JSON: 02 Feb 11:41 UTC
Core cask tap JSON: 02 Feb 11:41 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode-15.2.0.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2 => /Applications/Xcode-15.2.0.app/Contents/Developer
Rosetta 2: false
```

### Output of `brew tap`

```shell
➜  homebrew git:(master) brew tap
homebrew/cask-versions
robotsandpencils/made
xcodesorg/made
```

**Comment by SMillerDev** [comment]
No need to open an issue and a PR
