### ISSUE TITLE
roundpie Error: SHA256 mismatch when install

### ISSUE THREAD

**Issue by reishou** [Homebrew/homebrew-cask#166108]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Error: SHA256 mismatch
Expected: 21afc76f03495933a7f75e5969d5d01f735611a892005f85750b9515c53d45ef
  Actual: 4249b963e22f6d7bb53cb6071ee37a88eb36132d3b709d7899eedc67e04ae642

### Command that failed

brew install roundpie

### Output of command with `--verbose --debug`

```shell
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.2.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.3\)\ curl/8.4.0 --header Accept-Language:\ en --fail --remote-time --output /Users/reishou/Library/Caches/Homebrew/api/formula.jws.json --location --time-cond /Users/reishou/Library/Caches/Homebrew/api/formula.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.3\)\ curl/8.4.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4332k  100 4332k    0     0  16.1M      0 --:--:-- --:--:-- --:--:-- 16.1M
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.2.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.3\)\ curl/8.4.0 --header Accept-Language:\ en --fail --remote-time --output /Users/reishou/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/reishou/Library/Caches/Homebrew/api/cask.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.3\)\ curl/8.4.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1056k  100 1056k    0     0  5310k      0 --:--:-- --:--:-- --:--:-- 5334k
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading roundpie
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://roundpie.app/installers/RoundPie-1.5.1558.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.3\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://roundpie.app/installers/RoundPie-1.5.1558.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.3\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://roundpie.app/installers/RoundPie-1.5.1558.dmg
Already downloaded: /Users/reishou/Library/Caches/Homebrew/downloads/1b1c13b32d226a36ebf3fc2e1871b1c774254069f808d946f0b2cdde189b8286--RoundPie-1.5.1558.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx14 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/reishou/Library/Caches/Homebrew/downloads/1b1c13b32d226a36ebf3fc2e1871b1c774254069f808d946f0b2cdde189b8286--RoundPie-1.5.1558.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/reishou/Library/Caches/Homebrew/downloads/1b1c13b32d226a36ebf3fc2e1871b1c774254069f808d946f0b2cdde189b8286--RoundPie-1.5.1558.dmg
==> /Users/reishou/Library/Caches/Homebrew/downloads/1b1c13b32d226a36ebf3fc2e1871b1c774254069f808d946f0b2cdde189b8286--RoundPie-1.5.1558.dmg is quarantined
==> Verifying checksum for '1b1c13b32d226a36ebf3fc2e1871b1c774254069f808d946f0b2cdde189b8286--RoundPie-1.5.1558.dmg'
Error: SHA256 mismatch
Expected: 21afc76f03495933a7f75e5969d5d01f735611a892005f85750b9515c53d45ef
  Actual: 4249b963e22f6d7bb53cb6071ee37a88eb36132d3b709d7899eedc67e04ae642
    File: /Users/reishou/Library/Caches/Homebrew/downloads/1b1c13b32d226a36ebf3fc2e1871b1c774254069f808d946f0b2cdde189b8286--RoundPie-1.5.1558.dmg
To retry an incomplete download, remove the file above.
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:291:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:85:in `verify_download_integrity'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:64:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:181:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.

HOMEBREW_VERSION: 4.2.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6170b6297c61ef0b68814c708eeff2199d8b0d11
Last commit: 30 hours ago
Core tap JSON: 06 Feb 18:00 UTC
Core cask tap JSON: 06 Feb 18:00 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.43.0 => /usr/local/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3-x86_64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
```

### Output of `brew tap`

```shell
homebrew/cask-fonts
```

**Comment by bevanjkay** [comment]
>     * [x]  I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

Have you actually tried to open a PR to fix this issue?

https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match
