### ISSUE TITLE
Cannot install Autodesk Fusion 360

### ISSUE THREAD

**Issue by lukasmalkmus** [Homebrew/homebrew-cask#166468]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Seeing the following error:

```
env: /opt/homebrew/Caskroom/autodesk-fusion360/latest/Install Autodesk Fusion 360.app/Contents/MacOS/Fusion 360 Client Downloader: No such file or directory
```

### Command that failed

brew install autodesk-fusion360

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading autodesk-fusion360
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Client%20Downloader.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.7-122-g0782ba1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.3.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://dl.appstreaming.autodesk.com/production/installers/Fusion\%20360\%20Client\%20Downloader.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.7-122-g0782ba1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.3.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://dl.appstreaming.autodesk.com/production/installers/Fusion\%20360\%20Client\%20Downloader.dmg
Already downloaded: /Users/lukasmalkmus/Library/Caches/Homebrew/downloads/a5f7524e4b646b466bee418c43ffca2190d0375f7f5af0085b3a7dbc5122b871--appstream
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/lukasmalkmus/Library/Caches/Homebrew/downloads/a5f7524e4b646b466bee418c43ffca2190d0375f7f5af0085b3a7dbc5122b871--appstream
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/lukasmalkmus/Library/Caches/Homebrew/downloads/a5f7524e4b646b466bee418c43ffca2190d0375f7f5af0085b3a7dbc5122b871--appstream
==> /Users/lukasmalkmus/Library/Caches/Homebrew/downloads/a5f7524e4b646b466bee418c43ffca2190d0375f7f5af0085b3a7dbc5122b871--appstream is quarantined
Warning: No checksum defined for cask 'autodesk-fusion360', skipping verification.
/usr/bin/env hdiutil imageinfo -format /Users/lukasmalkmus/Library/Caches/Homebrew/downloads/a5f7524e4b646b466bee418c43ffca2190d0375f7f5af0085b3a7dbc5122b871--appstream
==> Installing Cask autodesk-fusion360
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Uncompressed for /Users/lukasmalkmus/Library/Caches/Homebrew/downloads/a5f7524e4b646b466bee418c43ffca2190d0375f7f5af0085b3a7dbc5122b871--appstream
cp -p /Users/lukasmalkmus/Library/Caches/Homebrew/downloads/a5f7524e4b646b466bee418c43ffca2190d0375f7f5af0085b3a7dbc5122b871--appstream /opt/homebrew/Caskroom/autodesk-fusion360/latest/appstream
==> Verifying Gatekeeper status of /Users/lukasmalkmus/Library/Caches/Homebrew/downloads/a5f7524e4b646b466bee418c43ffca2190d0375f7f5af0085b3a7dbc5122b871--appstream
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/lukasmalkmus/Library/Caches/Homebrew/downloads/a5f7524e4b646b466bee418c43ffca2190d0375f7f5af0085b3a7dbc5122b871--appstream
==> /Users/lukasmalkmus/Library/Caches/Homebrew/downloads/a5f7524e4b646b466bee418c43ffca2190d0375f7f5af0085b3a7dbc5122b871--appstream is quarantined
==> Propagating quarantine from /Users/lukasmalkmus/Library/Caches/Homebrew/downloads/a5f7524e4b646b466bee418c43ffca2190d0375f7f5af0085b3a7dbc5122b871--appstream to /opt/homebrew/Caskroom/autodesk-fusion360/latest
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/lukasmalkmus/Library/Caches/Homebrew/downloads/a5f7524e4b646b466bee418c43ffca2190d0375f7f5af0085b3a7dbc5122b871--appstream
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;65c7bde7\;Homebrew\\x20Cask\;51765622-D6D7-46C2-9E9E-2B70F35C7E5C
==> Creating metadata directory: /opt/homebrew/Caskroom/autodesk-fusion360/.metadata/latest/20240210182002.846
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/autodesk-fusion360/.metadata/latest/20240210182002.846/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Installer
==> Running installer script '/opt/homebrew/Caskroom/autodesk-fusion360/latest/Install Autodesk Fusion 360.app/Contents/MacOS/Fusion 360 Client Downloader'
/usr/bin/env PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin /opt/homebrew/Caskroom/autodesk-fusion360/latest/Install\ Autodesk\ Fusion\ 360.app/Contents/MacOS/Fusion\ 360\ Client\ Downloader --quiet
env: /opt/homebrew/Caskroom/autodesk-fusion360/latest/Install Autodesk Fusion 360.app/Contents/MacOS/Fusion 360 Client Downloader: No such file or directory
==> Purging files for version latest of Cask autodesk-fusion360
Error: Failure while executing; `/usr/bin/env PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin /opt/homebrew/Caskroom/autodesk-fusion360/latest/Install\ Autodesk\ Fusion\ 360.app/Contents/MacOS/Fusion\ 360\ Client\ Downloader --quiet` exited with 127. Here's the output:
env: /opt/homebrew/Caskroom/autodesk-fusion360/latest/Install Autodesk Fusion 360.app/Contents/MacOS/Fusion 360 Client Downloader: No such file or directory

/opt/homebrew/Library/Homebrew/system_command.rb:344:in `assert_success!'
/opt/homebrew/Library/Homebrew/system_command.rb:67:in `run!'
/opt/homebrew/Library/Homebrew/system_command.rb:32:in `run'
/opt/homebrew/Library/Homebrew/system_command.rb:36:in `run!'
/opt/homebrew/Library/Homebrew/cask/artifact/installer.rb:37:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:243:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:236:in `install_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:112:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```
```


### Output of `brew doctor` and `brew config`

```shell
`brew doctor`:


Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  md5sha1sum
```

`brew config`:

```
HOMEBREW_VERSION: 4.2.7-122-g0782ba1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0782ba112c7eb957edd8bc5258466616fbdacb3a
Last commit: 8 minutes ago
Core tap JSON: 10 Feb 18:16 UTC
Core cask tap JSON: 10 Feb 18:16 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false
```
```


### Output of `brew tap`

```shell
artginzburg/tap
axiomhq/tap
buo/cask-upgrade
homebrew/bundle
homebrew/cask-fonts
homebrew/services
mvp/uhubctl
```
```

**Comment by lukasmalkmus** [comment]
<img width="699" alt="Screenshot 2024-02-10 at 19 23 11" src="https://github.com/Homebrew/homebrew-cask/assets/9931588/bb2937e6-d2d8-4b92-bc2e-9d85a438f404">

Looks like they just dropped the `360` from the binary name.

**Comment by NikoKS** [comment]
any solution to this @lukasmalkmus ?
