### ISSUE TITLE
Superproductivity 8.0.0 changed the release assets

### ISSUE THREAD

**Issue by thetric** [Homebrew/homebrew-cask#166645]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

The release assets

* superProductivity-8.0.0.dmg
* superProductivity-8.0.0-arm64.dmg

were changed after the release.

I have opened this issue as suggested in https://github.com/Homebrew/homebrew-cask/pull/166634#issuecomment-1941641323. 
The current checksums are fixed in https://github.com/Homebrew/homebrew-cask/pull/166634

### Command that failed

brew upgrade

### Output of command with `--verbose --debug`

```shell
==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/superproductivity/.metadata/7.17.2/20240102082737.076/Casks/superproductivity.json
superproductivity 7.17.2 -> 8.0.0
==> Started upgrade process for Cask superproductivity
==> Upgrading superproductivity
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://github.com/johannesjo/super-productivity/releases/download/v8.0.0/superProductivity-8.0.0-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.8-28-g49ddb57\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.3.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/johannesjo/super-productivity/releases/download/v8.0.0/superProductivity-8.0.0-arm64.dmg
Already downloaded: /Users/dominik.broj/Library/Caches/Homebrew/downloads/ba899cc046390bf12d27caf96c31086512ee95076e1151868c028ce069577040--superProductivity-8.0.0-arm64.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/dominik.broj/Library/Caches/Homebrew/downloads/ba899cc046390bf12d27caf96c31086512ee95076e1151868c028ce069577040--superProductivity-8.0.0-arm64.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/dominik.broj/Library/Caches/Homebrew/downloads/ba899cc046390bf12d27caf96c31086512ee95076e1151868c028ce069577040--superProductivity-8.0.0-arm64.dmg
==> /Users/dominik.broj/Library/Caches/Homebrew/downloads/ba899cc046390bf12d27caf96c31086512ee95076e1151868c028ce069577040--superProductivity-8.0.0-arm64.dmg is quarantined
==> Verifying checksum for 'ba899cc046390bf12d27caf96c31086512ee95076e1151868c028ce069577040--superProductivity-8.0.0-arm64.dmg'
==> Purging files for version 8.0.0 of Cask superproductivity
Error: superproductivity: SHA256 mismatch
Expected: 7a20d2a2b31849b7f40fb12df6090ca8ad0880c47b064a869fda185af3543b56
  Actual: 50870d0e1eb247a6f18f328bc3934903f19c8cf7148cca95d70cafe73b36ebad
    File: /Users/dominik.broj/Library/Caches/Homebrew/downloads/ba899cc046390bf12d27caf96c31086512ee95076e1151868c028ce069577040--superProductivity-8.0.0-arm64.dmg
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:291:in `verify_checksum'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation_2_7.rb:687:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation_2_7.rb:687:in `block in create_validator_procedure_fast1'
/opt/homebrew/Library/Homebrew/cask/download.rb:85:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/download.rb:64:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:181:in `download'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:193:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:114:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11247/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:260:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:141:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Warning: Cask microsoft/git/git-credential-manager-core was renamed to git-credential-manager-core.
Warning: Cask microsoft/git/git-credential-manager-core was renamed to git-credential-manager-core.
Your system is ready to brew
```

```
❯ brew config
HOMEBREW_VERSION: 4.2.8-28-g49ddb57
ORIGIN: https://github.com/Homebrew/brew
HEAD: 49ddb57527ef49ffa77986da4efb09eb404c9cae
Last commit: 2 hours ago
Core tap JSON: 13 Feb 15:51 UTC
Core cask tap JSON: 13 Feb 15:51 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.43.1 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```
```


### Output of `brew tap`

```shell
❯ brew tap
hashicorp/tap
microsoft/git
romkatv/powerlevel10k
```

**Comment by SMillerDev** [comment]
This should be created in the upstream repo, not the brew (downstream) repo
