### ISSUE TITLE
Screaming Frog SEO Spider, download redirect to different version

### ISSUE THREAD

**Issue by hardyjohnson** [Homebrew/homebrew-cask#167196]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Current Screaming Frog SEO Spider cask version is unavailable.

Cask version: 19.6 (https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/s/screaming-frog-seo-spider.rb)
Website current download version: 19.4

<img width="1394" alt="image" src="https://github.com/Homebrew/homebrew-cask/assets/350943/76448758-1088-4f6c-b9f8-1187a063bb13">

Cask version download gets 301 redirected to 19.4, reverting to (https://github.com/Homebrew/homebrew-cask/commit/b19627dce589a0aab732a2e7aadac9cb4246f96b) where this has been seen previously would resolve.

```
curl -v https://download.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-19.6-aarch64.dmg                                        ─╯
*   Trying 192.124.249.107:443...
* Connected to download.screamingfrog.co.uk (192.124.249.107) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=download.screamingfrog.co.uk
*  start date: Nov 29 08:17:06 2023 GMT
*  expire date: Nov 29 08:17:06 2024 GMT
*  subjectAltName: host "download.screamingfrog.co.uk" matched cert's "download.screamingfrog.co.uk"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=Starfield Technologies, Inc.; OU=http://certs.starfieldtech.com/repository/; CN=Starfield Secure Certificate Authority - G2
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://download.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-19.6-aarch64.dmg
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: download.screamingfrog.co.uk]
* [HTTP/2] [1] [:path: /products/seo-spider/ScreamingFrogSEOSpider-19.6-aarch64.dmg]
* [HTTP/2] [1] [user-agent: curl/8.4.0]
* [HTTP/2] [1] [accept: */*]
> GET /products/seo-spider/ScreamingFrogSEOSpider-19.6-aarch64.dmg HTTP/2
> Host: download.screamingfrog.co.uk
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/2 301
< server: nginx
< date: Tue, 20 Feb 2024 18:12:05 GMT
< content-type: text/html; charset=iso-8859-1
< content-length: 304
< location: https://download.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-19.4-aarch64.dmg
< x-sucuri-id: 11007
< x-xss-protection: 1; mode=block
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< content-security-policy: upgrade-insecure-requests;
< x-sucuri-cache: HIT
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://download.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-19.4-aarch64.dmg">here</a>.</p>
</body></html>
* Connection #0 to host download.screamingfrog.co.uk left intact

```

### Command that failed

brew upgrade --cask screaming-frog-seo-spider

### Output of command with `--verbose --debug`

```shell
brew upgrade --cask screaming-frog-seo-spider --verbose --debug                                                                                 ─╯
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.2.9-50-g14ba271\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.3.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --remote-time --output /Users/USER/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/USER/Library/Caches/Homebrew/api/cask.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.9-50-g14ba271\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.3.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading screaming-frog-seo-spider
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/screaming-frog-seo-spider/.metadata/19.4/20231107173822.788/Casks/screaming-frog-seo-spider.json
screaming-frog-seo-spider 19.4 -> 19.6
==> Started upgrade process for Cask screaming-frog-seo-spider
==> Upgrading screaming-frog-seo-spider
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.9-50-g14ba271\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.3.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://download.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-19.6-aarch64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.9-50-g14ba271\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.3.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://download.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-19.6-aarch64.dmg
==> Downloading https://download.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-19.6-aarch64.dmg
==> Downloading from https://download.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-19.4-aarch64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.9-50-g14ba271\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.3.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --location https://download.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-19.4-aarch64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.9-50-g14ba271\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.3.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/USER/Library/Caches/Homebrew/downloads/e00071b5505718c40f1e158bdd1e19dcbf03ed97eeb4e2c67698af8042341ea4--ScreamingFrogSEOSpider-19.4-aarch64.dmg.incomplete --continue-at - --location https://download.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-19.4-aarch64.dmg
** Resuming transfer from byte position 18288640
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  525M  100  525M    0     0  4172k      0  0:02:08  0:02:08 --:--:-- 5070k
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/USER/Library/Caches/Homebrew/downloads/e00071b5505718c40f1e158bdd1e19dcbf03ed97eeb4e2c67698af8042341ea4--ScreamingFrogSEOSpider-19.4-aarch64.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/USER/Library/Caches/Homebrew/downloads/e00071b5505718c40f1e158bdd1e19dcbf03ed97eeb4e2c67698af8042341ea4--ScreamingFrogSEOSpider-19.4-aarch64.dmg
==> /Users/USER/Library/Caches/Homebrew/downloads/e00071b5505718c40f1e158bdd1e19dcbf03ed97eeb4e2c67698af8042341ea4--ScreamingFrogSEOSpider-19.4-aarch64.dmg is not quarantined
==> Quarantining /Users/USER/Library/Caches/Homebrew/downloads/e00071b5505718c40f1e158bdd1e19dcbf03ed97eeb4e2c67698af8042341ea4--ScreamingFrogSEOSpider-19.4-aarch64.dmg
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/USER/Library/Caches/Homebrew/downloads/e00071b5505718c40f1e158bdd1e19dcbf03ed97eeb4e2c67698af8042341ea4--ScreamingFrogSEOSpider-19.4-aarch64.dmg https://download.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-19.6-aarch64.dmg https://www.screamingfrog.co.uk/seo-spider/
==> Verifying checksum for 'e00071b5505718c40f1e158bdd1e19dcbf03ed97eeb4e2c67698af8042341ea4--ScreamingFrogSEOSpider-19.4-aarch64.dmg'
==> Purging files for version 19.6 of Cask screaming-frog-seo-spider
Error: screaming-frog-seo-spider: SHA256 mismatch
Expected: 632db404e412caa096b58db0f8d5ca7ee8bf57561511da3f5e83f3eea3b37cf8
  Actual: 5acc603d7e2f7dc81f2af928fe5e52be42faf3b6cc2c992311a09aee8a38258c
    File: /Users/USER/Library/Caches/Homebrew/downloads/e00071b5505718c40f1e158bdd1e19dcbf03ed97eeb4e2c67698af8042341ea4--ScreamingFrogSEOSpider-19.4-aarch64.dmg
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:291:in `verify_checksum'
/opt/homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:85:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:64:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:181:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:193:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:114:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:260:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:141:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```
```


### Output of `brew doctor` and `brew config`

```shell
> brew doctor                                                                                                                                     
Your system is ready to brew.


brew config                                                                                                                                     ─╯
HOMEBREW_VERSION: 4.2.9-50-g14ba271
ORIGIN: https://github.com/Homebrew/brew
HEAD: 14ba2715335c1b2eefeb2f2c6d013c256e2968d3
Last commit: 6 hours ago
Core tap JSON: 20 Feb 18:07 UTC
Core cask tap JSON: 20 Feb 18:33 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: 
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.43.2 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false
```
```


### Output of `brew tap`

```shell
> brew tap
>
```

**Comment by bevanjkay** [comment]
This has been resolved https://github.com/Homebrew/homebrew-cask/pull/167195
