### ISSUE TITLE
Unable to download Racket installer

### ISSUE THREAD

**Issue by sgdot** [Homebrew/homebrew-cask#168096]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

I can't install racket like in #62029

I think right download link is https://download.racket-lang.org/installers/8.12/racket-8.12-aarch64-macosx-cs.dmg from page https://download.racket-lang.org/

### Command that failed

brew install --cask racket

### Output of command with `--verbose --debug`

```shell
❯ brew install --cask racket --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading racket
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.10\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://mirror.racket-lang.org/installers/8.12/racket-8.12-x86_64-macosx-cs.dmg
==> Downloading https://mirror.racket-lang.org/installers/8.12/racket-8.12-x86_64-macosx-cs.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.10\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://mirror.racket-lang.org/installers/8.12/racket-8.12-x86_64-macosx-cs.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.10\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/sgdot/Library/Caches/Homebrew/downloads/3076733c0b4042c3d4a451df3d9dee0c3cfe285e8cbaea57d81cadbdcd978272--racket-8.12-x86_64-macosx-cs.dmg.incomplete --location https://mirror.racket-lang.org/installers/8.12/racket-8.12-x86_64-macosx-cs.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to mirror.racket-lang.org port 443 after 75003 ms: Couldn't connect to server
Warning: Problem : timeout. Will retry in 1 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to mirror.racket-lang.org port 443 after 75001 ms: Couldn't connect to server
Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to mirror.racket-lang.org port 443 after 75004 ms: Couldn't connect to server
Warning: Problem : timeout. Will retry in 4 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to mirror.racket-lang.org port 443 after 75024 ms: Couldn't connect to server
Error: Download failed on Cask 'racket' with message: Download failed: https://mirror.racket-lang.org/installers/8.12/racket-8.12-x86_64-macosx-cs.dmg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:447:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:444:in `fetch'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:55:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:181:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase
  openssl@1.1
  python@3.8

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libpas2jslib.dylib

----
❯ brew config
HOMEBREW_VERSION: 4.2.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: c6d959218f143cd17b1fc3e0f10f143cbd273528
Last commit: 7 days ago
Core tap JSON: 03 Mar 07:47 UTC
Core cask tap JSON: 03 Mar 07:58 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-x86_64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
```

### Output of `brew tap`

```shell
❯ brew tap
hashicorp/tap
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
kabel/php-ext
ytsutano/toolbox
```

**Comment by bevanjkay** [comment]
Is the issue still present? I am able to fetch the cask with no issues.

**Comment by krehel** [comment]
Can you please confirm this is still the case?

I am able to fetch the files without issues.

Maybe there was a delay in updating the mirror.

**Comment by sgdot** [comment]
Yes, issue still present
It may not work with Russian IPs
```
❯ date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
DATE: 2024-03-04
TIME: 08:45:57
sgdot@sgdot ~
❯ brew install --cask racket --verbose --debug
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.2.10\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --remote-time --output /Users/sgdot/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/sgdot/Library/Caches/Homebrew/api/cask.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.10\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1063k  100 1063k    0     0   374k      0  0:00:02  0:00:02 --:--:--  374k
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading racket
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.10\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://mirror.racket-lang.org/installers/8.12/racket-8.12-x86_64-macosx-cs.dmg
==> Downloading https://mirror.racket-lang.org/installers/8.12/racket-8.12-x86_64-macosx-cs.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.10\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://mirror.racket-lang.org/installers/8.12/racket-8.12-x86_64-macosx-cs.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.10\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.2.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/sgdot/Library/Caches/Homebrew/downloads/3076733c0b4042c3d4a451df3d9dee0c3cfe285e8cbaea57d81cadbdcd978272--racket-8.12-x86_64-macosx-cs.dmg.incomplete --location https://mirror.racket-lang.org/installers/8.12/racket-8.12-x86_64-macosx-cs.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to mirror.racket-lang.org port 443 after 75004 ms: Couldn't connect to server
Warning: Problem : timeout. Will retry in 1 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to mirror.racket-lang.org port 443 after 75002 ms: Couldn't connect to server
Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:16 --:--:--     0
curl: (28) Failed to connect to mirror.racket-lang.org port 443 after 76598 ms: Couldn't connect to server
Warning: Problem : timeout. Will retry in 4 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to mirror.racket-lang.org port 443 after 75001 ms: Couldn't connect to server
Error: Download failed on Cask 'racket' with message: Download failed: https://mirror.racket-lang.org/installers/8.12/racket-8.12-x86_64-macosx-cs.dmg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:447:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:444:in `fetch'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:55:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:181:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:244:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

**Comment by SMillerDev** [comment]
In that case I don't think there is anything we can do here.

**Comment by sgdot** [comment]
@SMillerDev Can you change the download link to https://download.racket-lang.org/installers/8.12/racket-8.12-aarch64-macosx-cs.dmg?
