### ISSUE TITLE
Cask 'google-chrome' does not have a sha256 checksum defined and was not installed.

### ISSUE THREAD

**Issue by GildedPleb** [Homebrew/homebrew-cask#168214]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

There is no checksum for google-chrome. 

### Command that failed

 brew install --cask google-chrome --verbose --debug

### Output of command with `--verbose --debug`

```shell
% brew install --cask google-chrome --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading google-chrome
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Checking cask has checksum
Error: Cask 'google-chrome' does not have a sha256 checksum defined and was not installed.
This means you have the --require-sha option set, perhaps in your HOMEBREW_CASK_OPTS.
/opt/homebrew/Library/Homebrew/cask/installer.rb:189:in `verify_has_sha'
/opt/homebrew/Library/Homebrew/cask/installer.rb:68:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:246:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
% brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.18/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/warning-1.3.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/tapioca-0.12.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/yard-sorbet-0.8.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/yard-0.9.36/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/stackprof-0.2.26/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/arm64-darwin-20/3.1.0-static/stackprof-0.2.26
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/spoom-1.2.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/thor-1.3.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/syntax_tree-6.2.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-static-and-runtime-0.5.11284/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-0.5.11284/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-static-0.5.11284-universal-darwin/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/simplecov-cobertura-2.1.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/simplecov-0.22.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/simplecov_json_formatter-0.1.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/simplecov-html-0.12.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/ruby-prof-1.7.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/arm64-darwin-20/3.1.0-static/ruby-prof-1.7.0
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/ruby-macho-4.0.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-sorbet-0.7.7/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-rspec-2.26.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-performance-1.20.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-md-1.2.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-factory_bot-2.25.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-capybara-2.20.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-1.61.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/unicode-display_width-2.5.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/ruby-progressbar-1.13.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rubocop-ast-1.31.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec_junit_formatter-0.6.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-sorbet-1.9.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-retry-0.6.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-its-1.3.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-github-2.4.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-3.13.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-mocks-3.13.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-expectations-3.13.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-core-3.13.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rspec-support-3.13.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/ronn-0.7.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rexml-3.2.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rdiscount-2.2.7.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/arm64-darwin-20/3.1.0-static/rdiscount-2.2.7.3
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rbi-0.1.9/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/pry-0.14.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/prism-0.24.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/arm64-darwin-20/3.1.0-static/prism-0.24.0
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/prettier_print-1.2.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/plist-3.7.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/patchelf-1.5.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/parlour-8.1.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/rainbow-3.1.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/parser-3.3.0.5/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/racc-1.7.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/arm64-darwin-20/3.1.0-static/racc-1.7.3
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/parallel_tests-4.5.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/parallel-1.24.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/netrc-0.11.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/mustache-1.1.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/minitest-5.22.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/method_source-1.0.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/language_server-protocol-3.17.0.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/json_schemer-2.1.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/simpleidn-0.2.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/unf-0.1.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/unf_ext-0.0.9.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/arm64-darwin-20/3.1.0-static/unf_ext-0.0.9.1
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/regexp_parser-2.9.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/json-2.7.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/arm64-darwin-20/3.1.0-static/json-2.7.1
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/hpricot-0.8.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/arm64-darwin-20/3.1.0-static/hpricot-0.8.6
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/hana-1.3.7/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/erubi-1.12.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/elftools-1.3.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/docile-1.4.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/diff-lcs-1.5.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/highline-2.0.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/coderay-1.1.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/byebug-11.1.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/arm64-darwin-20/3.1.0-static/byebug-11.1.3
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.18.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/arm64-darwin-20/3.1.0-static/bootsnap-1.18.3
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/msgpack-1.7.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/extensions/arm64-darwin-20/3.1.0-static/msgpack-1.7.2
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/bindata-2.5.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/ast-2.4.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/addressable-2.8.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/public_suffix-5.0.4/lib
/opt/homebrew/Library/Homebrew
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/vendor_ruby/3.1.0
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/vendor_ruby/3.1.0/arm64-darwin20
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/vendor_ruby
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/arm64-darwin20
==> Homebrew Version
4.2.11
==> macOS
14.3.1
==> SIP
Enabled
==> Homebrew Cask Staging Location
/opt/homebrew/Caskroom
==> Homebrew Cask Taps:
/opt/homebrew/Library/Taps/homebrew/homebrew-cask (4397 casks)
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found (0 casks)
/opt/homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/opt/homebrew/Library/Taps/kardolus/homebrew-chatgpt-cli (0 casks)
/opt/homebrew/Library/Taps/mac-cleanup/homebrew-mac-cleanup-py (0 casks)
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Xcode is installed to a directory with a space in the name.
This will cause some formulae to fail to build.

% brew config --verbose                   
HOMEBREW_VERSION: 4.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: d7d4c8266210c024b93a450a7d357cec0b46a1bb
Last commit: 11 hours ago
Core tap JSON: 04 Mar 19:41 UTC
Core cask tap JSON: 04 Mar 20:02 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--require-sha"]
HOMEBREW_MAKE_JOBS: 14
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSECURE_REDIRECT: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 14-core 64-bit arm_palma
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2 => /Applications/Xcode-15.2.0.app/Contents/Developer
Rosetta 2: false
```

### Output of `brew tap`

```shell
% brew tap              
homebrew/command-not-found
kardolus/chatgpt-cli
mac-cleanup/mac-cleanup-py
```

**Comment by GildedPleb** [comment]
I didnt retry the command with `--force` out of an abundance of caution. If anyone can give me a rundown on why its a good idea to run with `--force`, great!

```
% brew info google-chrome          
==> google-chrome: 122.0.6261.94 (auto_updates)
https://www.google.com/chrome/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/g/google-chrome.rb
==> Name
Google Chrome
==> Description
Web browser
==> Artifacts
Google Chrome.app (App)
```

This version seems up to date. Yet there is no checksum?

**Comment by bevanjkay** [comment]
A checksum cannot be used because the versions provided by the vendor are unversioned. 

If a checksum was added the cask would stop working every time there is an update.
