### ISSUE TITLE
devtunnel SHA not matching

### ISSUE THREAD

**Issue by dkbhadeshiya** [Homebrew/homebrew-cask#168816]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

SHA for `devtunnel` is not matching for arm64 based mac. 

### Command that failed

brew upgrade devtunnel

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading devtunnel
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading devtunnel
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading devtunnel
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading devtunnel
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/devtunnel/.metadata/1.0.1229+c3607a1c01/20240307132758.279/Casks/devtunnel.json
devtunnel 1.0.1229+c3607a1c01 -> 1.0.1230+5abf679d5f
==> Started upgrade process for Cask devtunnel
==> Upgrading devtunnel
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://tunnelsassetsprod.blob.core.windows.net/cli/1.0.1230+5abf679d5f/osx-arm64-devtunnel-zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.12-13-g2d77465\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://tunnelsassetsprod.blob.core.windows.net/cli/1.0.1230+5abf679d5f/osx-arm64-devtunnel-zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.12-13-g2d77465\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://tunnelsassetsprod.blob.core.windows.net/cli/1.0.1230+5abf679d5f/osx-arm64-devtunnel-zip
Already downloaded: /Users/dkbhadeshiya/Library/Caches/Homebrew/downloads/a6d7c3ff47f41041f450b6b8951e9c6da02de87ef7bbe37ba2a680d417715d45--osx-arm64-devtunnel-zip
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/dkbhadeshiya/Library/Caches/Homebrew/downloads/a6d7c3ff47f41041f450b6b8951e9c6da02de87ef7bbe37ba2a680d417715d45--osx-arm64-devtunnel-zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/dkbhadeshiya/Library/Caches/Homebrew/downloads/a6d7c3ff47f41041f450b6b8951e9c6da02de87ef7bbe37ba2a680d417715d45--osx-arm64-devtunnel-zip
==> /Users/dkbhadeshiya/Library/Caches/Homebrew/downloads/a6d7c3ff47f41041f450b6b8951e9c6da02de87ef7bbe37ba2a680d417715d45--osx-arm64-devtunnel-zip is quarantined
==> Verifying checksum for 'a6d7c3ff47f41041f450b6b8951e9c6da02de87ef7bbe37ba2a680d417715d45--osx-arm64-devtunnel-zip'
==> Purging files for version 1.0.1230+5abf679d5f of Cask devtunnel
Error: devtunnel: SHA256 mismatch
Expected: 02a6e0bf521b045cf5826f407a1a14df7b6c5420b87f2a31a2448bfa7690fa2d
  Actual: d29b03e39a8e39b5806a0ba78047f633b2048ea64fe084f7e04028bc460d8771
    File: /Users/dkbhadeshiya/Library/Caches/Homebrew/downloads/a6d7c3ff47f41041f450b6b8951e9c6da02de87ef7bbe37ba2a680d417715d45--osx-arm64-devtunnel-zip
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:291:in `verify_checksum'
/opt/homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:85:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:64:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:181:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:193:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:114:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:264:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:144:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
1 ❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python-jinja

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python-pytz
  python-pyparsing
  python-dateutil
  cryptography
  python-lxml
  certifi
1 ❯ brew config
HOMEBREW_VERSION: 4.2.12-13-g2d77465
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2d774654e23ff00e61e697e467b7fcfb02e7baae
Last commit: 9 hours ago
Core tap JSON: 12 Mar 06:41 UTC
Core cask tap JSON: 12 Mar 06:41 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
❯ brew tap
homebrew/services
mongodb/brew
oven-sh/bun
pulumi/tap
reviewdog/tap
robusta-dev/krr
snyk/tap
```

**Comment by bevanjkay** [comment]
There is an open PR for this issue already - https://github.com/Homebrew/homebrew-cask/pull/168709
We have not received confirmation from upstream to confirm the change, as it can indicate that the releases have been compromised.
