### ISSUE TITLE
An error occurred when I installed tencent-meeting. Please fix it

### ISSUE THREAD

**Issue by zhoupeng260641663** [Homebrew/homebrew-cask#170199]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

When I installed tencent-meeting, I got an error: "It seems the App source"，
Please deal with it

### Command that failed

brew install --cask tencent-meeting

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading tencent-meeting
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/tencent-meeting/.metadata/3.16.6.417,1ec38b0c73c3ffdc459b0f19f3aa486c/20230517110955.109/Casks/tencent-meeting.json
tencent-meeting 3.16.6.417,d913daa77527d9098864115253ee58bb -> 3.24.3.401,7861cf367f7764fc531090effa381b3c
==> Started upgrade process for Cask tencent-meeting
==> Upgrading tencent-meeting
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://updatecdn.meeting.qq.com/cos/7861cf367f7764fc531090effa381b3c/TencentMeeting_0300000000_3.24.3.401.publish.arm64.officialwebsite.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.15-46-gec74bad\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://updatecdn.meeting.qq.com/cos/7861cf367f7764fc531090effa381b3c/TencentMeeting_0300000000_3.24.3.401.publish.arm64.officialwebsite.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.15-46-gec74bad\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://updatecdn.meeting.qq.com/cos/7861cf367f7764fc531090effa381b3c/TencentMeeting_0300000000_3.24.3.401.publish.arm64.officialwebsite.dmg
Already downloaded: /Users/zhoupengpeng/Library/Caches/Homebrew/downloads/fa671c1f07dbd85d7e10c462ef6403bd9cbcfa8fafd3da42b003a3f53336ec0d--TencentMeeting_0300000000_3.24.3.401.publish.arm64.officialwebsite.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/zhoupengpeng/Library/Caches/Homebrew/downloads/fa671c1f07dbd85d7e10c462ef6403bd9cbcfa8fafd3da42b003a3f53336ec0d--TencentMeeting_0300000000_3.24.3.401.publish.arm64.officialwebsite.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/zhoupengpeng/Library/Caches/Homebrew/downloads/fa671c1f07dbd85d7e10c462ef6403bd9cbcfa8fafd3da42b003a3f53336ec0d--TencentMeeting_0300000000_3.24.3.401.publish.arm64.officialwebsite.dmg
==> /Users/zhoupengpeng/Library/Caches/Homebrew/downloads/fa671c1f07dbd85d7e10c462ef6403bd9cbcfa8fafd3da42b003a3f53336ec0d--TencentMeeting_0300000000_3.24.3.401.publish.arm64.officialwebsite.dmg is quarantined
==> Verifying checksum for 'fa671c1f07dbd85d7e10c462ef6403bd9cbcfa8fafd3da42b003a3f53336ec0d--TencentMeeting_0300000000_3.24.3.401.publish.arm64.officialwebsite.dmg'
/usr/bin/env hdiutil imageinfo -format /Users/zhoupengpeng/Library/Caches/Homebrew/downloads/fa671c1f07dbd85d7e10c462ef6403bd9cbcfa8fafd3da42b003a3f53336ec0d--TencentMeeting_0300000000_3.24.3.401.publish.arm64.officialwebsite.dmg
==> Uninstalling artifacts
==> 3 artifacts defined
#<Cask::ArtifactSet: {#<Cask::Artifact::Uninstall:0x000000010611f5b0 @cask=#<Cask tencent-meeting>, @dsl_args=[{:quit=>"com.tencent.meeting"}], @directives={:quit=>"com.tencent.meeting", :signal=>[]}>, #<Cask::Artifact::App:0x000000010611e9d0 @cask=#<Cask tencent-meeting>, @dsl_args=["TencentMeeting.app"], @source_string="TencentMeeting.app", @target_string="">, #<Cask::Artifact::Zap:0x000000010611cf68 @cask=#<Cask tencent-meeting>, @dsl_args=[{:trash=>["~/Library/Application Scripts/FN2V63AD2J.com.tencent.meeting", "~/Library/Application Scripts/com.tencent.meeting", "~/Library/Caches/com.tencent.meeting", "~/Library/Containers/com.tencent.meeting", "~/Library/Containers/com.tencent.wemeet.FileDelta", "~/Library/Group Containers/FN2V63AD2J.com.tencent.meeting", "~/Library/HTTPStorages/com.tencent.meeting", "~/Library/HTTPStorages/com.tencent.meeting.binarycookies", "~/Library/Preferences/com.tencent.meeting.plist", "~/Library/Saved Application State/com.tencent.meeting.savedState", "~/Library/WebKit/com.tencent.meeting"]}], @directives={:trash=>["~/Library/Application Scripts/FN2V63AD2J.com.tencent.meeting", "~/Library/Application Scripts/com.tencent.meeting", "~/Library/Caches/com.tencent.meeting", "~/Library/Containers/com.tencent.meeting", "~/Library/Containers/com.tencent.wemeet.FileDelta", "~/Library/Group Containers/FN2V63AD2J.com.tencent.meeting", "~/Library/HTTPStorages/com.tencent.meeting", "~/Library/HTTPStorages/com.tencent.meeting.binarycookies", "~/Library/Preferences/com.tencent.meeting.plist", "~/Library/Saved Application State/com.tencent.meeting.savedState", "~/Library/WebKit/com.tencent.meeting"], :signal=>[]}>}>
==> Uninstalling artifact of class Cask::Artifact::Uninstall
==> Post-uninstalling artifact of class Cask::Artifact::Uninstall
==> Uninstalling artifact of class Cask::Artifact::App
==> Purging files for version 3.24.3.401,7861cf367f7764fc531090effa381b3c of Cask tencent-meeting
Error: tencent-meeting: It seems the App source '/Applications/TencentMeeting.app' is not there.
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:160:in `move_back'
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:23:in `uninstall_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:474:in `block in uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:471:in `uninstall_artifacts'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11316/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11316/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11316/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:430:in `start_upgrade'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11316/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11316/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11316/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:196:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11316/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11316/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11316/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:114:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11316/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11316/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11316/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/install.rb:252:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:91:in `public_send'
/opt/homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1
```

```shell
❯ brew config
HOMEBREW_VERSION: 4.2.15-46-gec74bad
ORIGIN: https://github.com/Homebrew/brew
HEAD: ec74bad6d3910c66aac7ce9ab292e83f3abb54ce
Last commit: 5 minutes ago
Core tap HEAD: e8eb3bce7ff3f691e54bd862f2e7e6e8c0949a35
Core tap last commit: 3 hours ago
Core tap JSON: 29 Mar 08:17 UTC
Core cask tap HEAD: 2dd77eec5312ebb33a6246c5cd591e35205b3ac9
Core cask tap last commit: 4 hours ago
Core cask tap JSON: 29 Mar 08:17 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
all_proxy: socks5://127.0.0.1:7890
http_proxy: http://127.0.0.1:7890
https_proxy: http://127.0.0.1:7890
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
```
### Output of `brew tap`
```shell
homebrew/cask
homebrew/cask-fonts
homebrew/core
romkatv/powerlevel10k
sunnyyoung/repo
```

**Comment by zhoupeng260641663** [comment]
Sorry, he succeeded when I executed reinstall

**Comment by zhoupeng260641663** [comment]
Sorry, he succeeded when I executed reinstall
