### ISSUE TITLE
Beekeeper Studio formula tries to install non-existing release.

### ISSUE THREAD

**Issue by bkane-msft** [Homebrew/homebrew-cask#170472]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

`beekeeper-studio` is pointed to a non-existing download link.

Would ya'll be receptive to a PR to change the link to the release in https://github.com/beekeeper-studio/beekeeper-studio/releases/tag/v4.1.13 ?

### Command that failed

brew install beekeeper-studio

### Output of command with `--verbose --debug`

```shell
$ brew install beekeeper-studio --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading beekeeper-studio
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading beekeeper-studio
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading beekeeper-studio
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.16\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v4.2.5/Beekeeper-Studio-4.2.5-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.16\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v4.2.5/Beekeeper-Studio-4.2.5-arm64.dmg
==> Downloading https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v4.2.5/Beekeeper-Studio-4.2.5-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.16\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v4.2.5/Beekeeper-Studio-4.2.5-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.16\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v4.2.5/Beekeeper-Studio-4.2.5-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.16\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/bkane/Library/Caches/Homebrew/downloads/9c334717d202d05c77fd4d38685d109574020db038f9bb2ade81c0323919b932--Beekeeper-Studio-4.2.5-arm64.dmg.incomplete --location https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v4.2.5/Beekeeper-Studio-4.2.5-arm64.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Error: Download failed on Cask 'beekeeper-studio' with message: Download failed: https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v4.2.5/Beekeeper-Studio-4.2.5-arm64.dmg
/opt/homebrew/Library/Homebrew/download_strategy.rb:447:in `rescue in fetch'
/opt/homebrew/Library/Homebrew/download_strategy.rb:444:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:55:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:186:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:247:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:236:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:236:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Your system is ready to brew.

$ brew config
HOMEBREW_VERSION: 4.2.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: bd1155be8f50998429a795c15a69c8fe75250510
Last commit: 30 hours ago
Core tap JSON: 02 Apr 21:02 UTC
Core cask tap JSON: 02 Apr 21:02 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: 1337
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_lobos
Clang: 15.0.0 build 1500
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
$ brew tap
bbkane/tap
homebrew/cask-fonts
homebrew/services
rsteube/tap
```

**Comment by bkane-msft** [comment]
Will do this week unless the Beekeeper Studio devs say something otherwise in https://github.com/beekeeper-studio/beekeeper-studio/issues/2071
