### ISSUE TITLE
404 when installing 'banksiagui', and can't update it with `brew bump`

### ISSUE THREAD

**Issue by skycloudd** [Homebrew/homebrew-cask#170590]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Running `brew install banksiagui` gives a 404 not found, and i can verify via a browser that the url is indeed a 404.

Homebrew has an outdated version (`0.55`) and the new version is `0.58/rc1` as found at https://banksiagui.com/download/

Now following the instructions to update it, with `brew bump --open-pr banksiagui`, i get the following error:

```
Error: No available formula with the name "banksiagui".
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

I'm not quite sure what the problem here is, but I suspect I need to have it installed first for `brew bump` to work? which is impossible if the download url doesnt exist. :(

### Command that failed

brew bump --open-pr banksiagui

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/bin/bundle clean
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading banksiagui
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::NullLoader): loading banksiagui
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading banksiagui
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading banksiagui
Error: No available formula with the name "banksiagui".
/opt/homebrew/Library/Homebrew/formulary.rb:848:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:964:in `factory'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:167:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/formulary.rb:455:in `resolve'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:211:in `resolve_formula'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:203:in `block in load_formula_or_cask'
/opt/homebrew/Library/Homebrew/api.rb:197:in `with_no_api_env'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:191:in `block in create_validator_slow'
/opt/homebrew/Library/Homebrew/api.rb:207:in `with_no_api_env_if_needed'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:118:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:83:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/dev-cmd/bump.rb:86:in `block in run'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:495:in `with_env'
/opt/homebrew/Library/Homebrew/api.rb:199:in `with_no_api_env'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/dev-cmd/bump.rb:68:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.

HOMEBREW_VERSION: 4.2.16-69-gfcc190b
ORIGIN: https://github.com/Homebrew/brew
HEAD: fcc190b5c659d9c74454011f094de568789ef8fd
Last commit: 4 hours ago
Core tap JSON: 03 Apr 21:52 UTC
Core cask tap JSON: 03 Apr 21:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: Catppuccin-mocha
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/cask-fonts
homebrew/services
```

**Comment by bevanjkay** [comment]
The version has to be manually bumped, because `livecheck` is blocked by anti-crawl protection, which means that `brew bump` cannot find the latest version.
