### ISSUE TITLE
Cannot install Visual Studio

### ISSUE THREAD

**Issue by Matthew-owo** [Homebrew/homebrew-cask#172245]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Cannot install Visual Studio in Macbook M1 Pro.

`Warning: Cask 'mono-mdk-for-visual-studio' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
Error: No casks found for mono-mdk-for-visual-studio.`

### Command that failed

brew install --cask visual-studio

### Output of command with `--verbose --debug`

```shell
❯ brew install --cask visual-studio --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading visual-studio
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://download.visualstudio.microsoft.com/download/pr/d9bdf235-5f23-4901-a4d4-88b1fc208e50/4d6cb7eba0d59cb70f7ef2adaf48fc60/visualstudioformac-17.6.11.400-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.19\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://download.visualstudio.microsoft.com/download/pr/d9bdf235-5f23-4901-a4d4-88b1fc208e50/4d6cb7eba0d59cb70f7ef2adaf48fc60/visualstudioformac-17.6.11.400-arm64.dmg
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/38b84e5d601cc5239c47842cad1c21a0e8b2260063eaf4aa6c59bc798f223444--visualstudioformac-17.6.11.400-arm64.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/user/Library/Caches/Homebrew/downloads/38b84e5d601cc5239c47842cad1c21a0e8b2260063eaf4aa6c59bc798f223444--visualstudioformac-17.6.11.400-arm64.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/user/Library/Caches/Homebrew/downloads/38b84e5d601cc5239c47842cad1c21a0e8b2260063eaf4aa6c59bc798f223444--visualstudioformac-17.6.11.400-arm64.dmg
==> /Users/user/Library/Caches/Homebrew/downloads/38b84e5d601cc5239c47842cad1c21a0e8b2260063eaf4aa6c59bc798f223444--visualstudioformac-17.6.11.400-arm64.dmg is quarantined
==> Verifying checksum for '38b84e5d601cc5239c47842cad1c21a0e8b2260063eaf4aa6c59bc798f223444--visualstudioformac-17.6.11.400-arm64.dmg'
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::NullLoader): loading mono-mdk-for-visual-studio
Warning: Cask 'mono-mdk-for-visual-studio' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading mono-mdk-for-visual-studio
==> Searching for similarly named casks...
Error: No casks found for mono-mdk-for-visual-studio.
Error: Kernel.exit
/opt/homebrew/Library/Homebrew/extend/kernel.rb:83:in `exit'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:83:in `odie'
/opt/homebrew/Library/Homebrew/cmd/install.rb:406:in `rescue in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:166:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Your system is ready to brew.
❯ brew config
HOMEBREW_VERSION: 4.2.19
ORIGIN: https://github.com/Homebrew/brew
HEAD: 54bea636b41f7953c01a7da5f488f08c1b42ffd1
Last commit: 5 days ago
Core tap JSON: 26 Apr 10:00 UTC
Core cask tap JSON: 26 Apr 10:00 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
❯ brew tap
homebrew/cask-fonts
```

**Comment by ChristopherA** [comment]
I am having the exact same problem on a new M3 MacBook Air.

**Comment by Matthew-owo** [comment]
According to Microsoft, Visual Studio for Mac will no longer be support after 2024-8-31. So, should we look for an IDE to replace Visual Studio for Mac?

**Comment by razvanazamfirei** [comment]
@Matthew-owo and @ChristopherA, running `brew tap homebrew/cask-versions` should fix the issue temporarily. 

This is related to the migration from `homebrew/cask-versions` to `homebrew/cask`.
