### ISSUE TITLE
404: prosys-opc-ua-browser

### ISSUE THREAD

**Issue by JayStolzenwald** [Homebrew/homebrew-cask#173226]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Apparently, the link is broken. I get:

==> Downloading https://www.prosysopc.com/opcua/apps/UaBrowser/dist/5.0.0-173/prosys-opc-ua-browser-mac-x64-5.0.0-173.dmg
curl: (22) The requested URL returned error: 404                                                                             

Error: Download failed on Cask 'prosys-opc-ua-browser' with message: Download failed: https://www.prosysopc.com/opcua/apps/UaBrowser/dist/5.0.0-173/prosys-opc-ua-browser-mac-x64-5.0.0-173.dmg

### Command that failed

brew install --cask prosys-opc-ua-browser

### Output of command with `--verbose --debug`

```shell
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.2.21\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.6\)\ curl/8.4.0 --header Accept-Language:\ en --fail --remote-time --output /Users/janis/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/janis/Library/Caches/Homebrew/api/cask.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.21\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.6\)\ curl/8.4.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading prosys-opc-ua-browser
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.21\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.6\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://www.prosysopc.com/opcua/apps/UaBrowser/dist/5.0.0-173/prosys-opc-ua-browser-mac-x64-5.0.0-173.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.21\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.6\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://www.prosysopc.com/opcua/apps/UaBrowser/dist/5.0.0-173/prosys-opc-ua-browser-mac-x64-5.0.0-173.dmg
==> Downloading https://www.prosysopc.com/opcua/apps/UaBrowser/dist/5.0.0-173/prosys-opc-ua-browser-mac-x64-5.0.0-173.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.21\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.6\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://www.prosysopc.com/opcua/apps/UaBrowser/dist/5.0.0-173/prosys-opc-ua-browser-mac-x64-5.0.0-173.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.21\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.6\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://www.prosysopc.com/opcua/apps/UaBrowser/dist/5.0.0-173/prosys-opc-ua-browser-mac-x64-5.0.0-173.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.21\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.6\)\ curl/8.4.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/janis/Library/Caches/Homebrew/downloads/1d6a426202ce737d155bade26e3344fdaab182d0fbb0f3c91d7b19d919efe91e--prosys-opc-ua-browser-mac-x64-5.0.0-173.dmg.incomplete --location https://www.prosysopc.com/opcua/apps/UaBrowser/dist/5.0.0-173/prosys-opc-ua-browser-mac-x64-5.0.0-173.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404
Error: Download failed on Cask 'prosys-opc-ua-browser' with message: Download failed: https://www.prosysopc.com/opcua/apps/UaBrowser/dist/5.0.0-173/prosys-opc-ua-browser-mac-x64-5.0.0-173.dmg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:433:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:430:in `fetch'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:86:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:53:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:187:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:102:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```

### Output of `brew tap`

```shell
derailed/k9s
hashicorp/tap
homebrew/services
```

**Comment by JayStolzenwald** [comment]
The correct link looks like this:
https://downloads.prosysopc.com/opcua/apps/UaBrowser/dist/5.0.0-173/prosys-opc-ua-browser-mac-x64-5.0.0-173.dmg

seems they changed their subdomain
