### ISSUE TITLE
zoom 6.0+ fails to install -- invalid path for downloaded package

### ISSUE THREAD

**Issue by nobeh** [Homebrew/homebrew-cask#173944]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

The Zoom cask used to work fine. After version 6.0.2+ , I've started to get the following error details.

### Command that failed

brew install --cask --verbose zoom

### Output of command with `--verbose --debug`

```shell
$ brew install --cask --verbose --debug zoom
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading zoom
==> Cask::Installer#install
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading zoom-for-it-admins
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/6205060c3a7cb7eed708d762227997e3a746602d/Casks/z/zoom.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/6205060c3a7cb7eed708d762227997e3a746602d/Casks/z/zoom.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://raw.githubusercontent.com/Homebrew/homebrew-cask/6205060c3a7cb7eed708d762227997e3a746602d/Casks/z/zoom.rb
Already downloaded: /Users/bnobakht/Library/Caches/Homebrew/downloads/7a443c1289a2a4ebef6dbe9fbdd570f85327c35a0d6564b85b30b8c3ff3bf8cf--zoom.rb
==> Verifying checksum for '7a443c1289a2a4ebef6dbe9fbdd570f85327c35a0d6564b85b30b8c3ff3bf8cf--zoom.rb'
==> Downloading https://cdn.zoom.us/prod/6.0.2.33403/arm64/zoomusInstallerFull.pkg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://cdn.zoom.us/prod/6.0.2.33403/arm64/zoomusInstallerFull.pkg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://cdn.zoom.us/prod/6.0.2.33403/arm64/zoomusInstallerFull.pkg
Already downloaded: /Users/bnobakht/Library/Caches/Homebrew/downloads/de3b1c5ef1cc9294ca556806590ea24f47eb283abb859ed413976c6b759b4323--zoomusInstallerFull.pkg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/bnobakht/Library/Caches/Homebrew/downloads/de3b1c5ef1cc9294ca556806590ea24f47eb283abb859ed413976c6b759b4323--zoomusInstallerFull.pkg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/bnobakht/Library/Caches/Homebrew/downloads/de3b1c5ef1cc9294ca556806590ea24f47eb283abb859ed413976c6b759b4323--zoomusInstallerFull.pkg
==> /Users/bnobakht/Library/Caches/Homebrew/downloads/de3b1c5ef1cc9294ca556806590ea24f47eb283abb859ed413976c6b759b4323--zoomusInstallerFull.pkg is quarantined
==> Verifying checksum for 'de3b1c5ef1cc9294ca556806590ea24f47eb283abb859ed413976c6b759b4323--zoomusInstallerFull.pkg'
/usr/bin/env hdiutil imageinfo -format /Users/bnobakht/Library/Caches/Homebrew/downloads/de3b1c5ef1cc9294ca556806590ea24f47eb283abb859ed413976c6b759b4323--zoomusInstallerFull.pkg
==> Installing Cask zoom
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Pkg for /Users/bnobakht/Library/Caches/Homebrew/downloads/de3b1c5ef1cc9294ca556806590ea24f47eb283abb859ed413976c6b759b4323--zoomusInstallerFull.pkg
cp -p /Users/bnobakht/Library/Caches/Homebrew/downloads/de3b1c5ef1cc9294ca556806590ea24f47eb283abb859ed413976c6b759b4323--zoomusInstallerFull.pkg /opt/homebrew/Caskroom/zoom/6.0.2.33403/zoomusInstallerFull.pkg
==> Verifying Gatekeeper status of /Users/bnobakht/Library/Caches/Homebrew/downloads/de3b1c5ef1cc9294ca556806590ea24f47eb283abb859ed413976c6b759b4323--zoomusInstallerFull.pkg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/bnobakht/Library/Caches/Homebrew/downloads/de3b1c5ef1cc9294ca556806590ea24f47eb283abb859ed413976c6b759b4323--zoomusInstallerFull.pkg
==> /Users/bnobakht/Library/Caches/Homebrew/downloads/de3b1c5ef1cc9294ca556806590ea24f47eb283abb859ed413976c6b759b4323--zoomusInstallerFull.pkg is quarantined
==> Propagating quarantine from /Users/bnobakht/Library/Caches/Homebrew/downloads/de3b1c5ef1cc9294ca556806590ea24f47eb283abb859ed413976c6b759b4323--zoomusInstallerFull.pkg to /opt/homebrew/Caskroom/zoom/6.0.2.33403
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/bnobakht/Library/Caches/Homebrew/downloads/de3b1c5ef1cc9294ca556806590ea24f47eb283abb859ed413976c6b759b4323--zoomusInstallerFull.pkg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0381\;66456840\;\;4D9D86B7-DBD2-4333-93AA-32EA6CE84F04
==> Creating metadata directory: /opt/homebrew/Caskroom/zoom/.metadata/6.0.2.33403/20240516015947.867
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/zoom/.metadata/6.0.2.33403/20240516015947.867/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for zoom with sudo; the password may be necessary.
/usr/bin/sudo -u root -E LOGNAME=bnobakht USER=bnobakht USERNAME=bnobakht -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/zoom/6.0.2.33403/zoomusInstallerFull.pkg -target / -verboseR
installer: Error - the package path specified was invalid: '/opt/homebrew/Caskroom/zoom/6.0.2.33403/zoomusInstallerFull.pkg'.
==> Purging files for version 6.0.2.33403 of Cask zoom
Error: Failure while executing; `/usr/bin/sudo -u root -E LOGNAME=bnobakht USER=bnobakht USERNAME=bnobakht -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/zoom/6.0.2.33403/zoomusInstallerFull.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Error - the package path specified was invalid: '/opt/homebrew/Caskroom/zoom/6.0.2.33403/zoomusInstallerFull.pkg'.
/opt/homebrew/Library/Homebrew/system_command.rb:352:in `assert_success!'
/opt/homebrew/Library/Homebrew/system_command.rb:75:in `run!'
/opt/homebrew/Library/Homebrew/system_command.rb:40:in `run'
/opt/homebrew/Library/Homebrew/system_command.rb:44:in `run!'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:63:in `block in run_installer'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:76:in `with_choices_file'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:56:in `run_installer'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:32:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:248:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:12:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:12:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:241:in `install_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
$ brew config
HOMEBREW_VERSION: 4.3.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8378cc825d83acffd125fb0fec041793df378a57
Last commit: 2 days ago
Core tap JSON: 16 May 01:56 UTC
Core cask tap JSON: 16 May 01:56 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

*`brew doctor` output is not relevant to zoom*

### Output of `brew tap`

```shell
$ brew tap
buo/cask-upgrade
homebrew/bundle
homebrew/cask-fonts
homebrew/cask-versions
homebrew/services
mrkai77/cask
ynqa/tap
```

**Comment by nobeh** [comment]
The debug outputs are attached above, but the summary is that it seems that download location assumed for the Zoom package has changed:

```
Installing zoom
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/6c9964a70c1996268b2edae6d762b7ac7e18b304/Casks/z/zoom.rb
==> Downloading https://cdn.zoom.us/prod/6.0.2.33403/arm64/zoomusInstallerFull.pkg
==> Installing Cask zoom
==> Running installer for zoom with sudo; the password may be necessary.
Error: Failure while executing; `/usr/bin/sudo -u root -E LOGNAME=bnobakht USER=bnobakht USERNAME=bnobakht -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/zoom/6.0.2.33403/zoomusInstallerFull.pkg -target /` exited with 1. Here's the output:
installer: Error - the package path specified was invalid: '/opt/homebrew/Caskroom/zoom/6.0.2.33403/zoomusInstallerFull.pkg'.
installer: Error - the package path specified was invalid: '/opt/homebrew/Caskroom/zoom/6.0.2.33403/zoomusInstallerFull.pkg'.
==> Purging files for version 6.0.2.33403 of Cask zoom
```

**Comment by miccal** [comment]
The `zoom` Casks were updated in https://github.com/Homebrew/homebrew-cask/pull/174335 and https://github.com/Homebrew/homebrew-cask/pull/174336, both of which passed our CI tests.

Also, `zoom` upgraded as normal on two of my personal machines (one Intel, one Arm), so this issue cannot be reproduced and therefore must be something with your particular set-up.

Sorry we cannot be of more help.
