### ISSUE TITLE
vmware-fusion cask download failed

### ISSUE THREAD

**Issue by kurgol** [Homebrew/homebrew-cask#174107]
### Verification

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

It looks like the broadcom acquisition of VMWARE may have changed the download URL but I'm unable to verify what the correct URL should be in order to update the cask with a PR.

The latest version available from the broadcom website is now 13.5.2 and homebrew is trying to download 13.5.1, though the download in the current cask is pointing at a file hosted on `vmware.com` domain.

### Command that failed

brew install --cask vmware-fusion

### Output of command with `--verbose --debug`

```
% brew install --cask vmware-fusion --verbose --
debug
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading vmware-fusion
==> Cask::Installer#install
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading vmware-fusion@preview
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/08840ce63265d7b93229ae62895c5fe4eb48f940/Casks/v/vmware-fusion.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://raw.githubusercontent.com/Homebrew/homebrew-cask/08840ce63265d7b93229ae62895c5fe4eb48f940/Casks/v/vmware-fusion.rb
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://raw.githubusercontent.com/Homebrew/homebrew-cask/08840ce63265d7b93229ae62895c5fe4eb48f940/Casks/v/vmware-fusion.rb
Already downloaded: /Users/kurgol/Library/Caches/Homebrew/downloads/3e435f0be7105c7ee8ec038289aec95463d488c9bff4f6cb8232d7cc5c408a01--vmware-fusion.rb
==> Verifying checksum for '3e435f0be7105c7ee8ec038289aec95463d488c9bff4f6cb8232d7cc5c408a01--vmware-fusion.rb'
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://download3.vmware.com/software/FUS-1351/VMware-Fusion-13.5.1-23298085_universal.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://download3.vmware.com/software/FUS-1351/VMware-Fusion-13.5.1-23298085_universal.dmg
==> Downloading https://download3.vmware.com/software/FUS-1351/VMware-Fusion-13.5.1-23298085_universal.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://download3.vmware.com/software/FUS-1351/VMware-Fusion-13.5.1-23298085_universal.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://download3.vmware.com/software/FUS-1351/VMware-Fusion-13.5.1-23298085_universal.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/kurgol/Library/Caches/Homebrew/downloads/97eb26a46d49ecf17a4cfef78570a5318efa71e6bcb8f38c44cfadbded737940--VMware-Fusion-13.5.1-23298085_universal.dmg.incomplete --location https://download3.vmware.com/software/FUS-1351/VMware-Fusion-13.5.1-23298085_universal.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    15    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 522
Error: Download failed on Cask 'vmware-fusion' with message: Download failed: https://download3.vmware.com/software/FUS-1351/VMware-Fusion-13.5.1-23298085_universal.dmg
/opt/homebrew/Library/Homebrew/download_strategy.rb:433:in `rescue in fetch'
/opt/homebrew/Library/Homebrew/download_strategy.rb:430:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:86:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:53:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:186:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:102:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

### Output of `brew doctor` and `brew config`

```
`% brew home vmware-fusion
Opening homepage for Cask vmware-fusion
kurgol@Kurgols-M2-MacBook-Pro ~ % brew config
HOMEBREW_VERSION: 4.3.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8378cc825d83acffd125fb0fec041793df378a57
Last commit: 3 days ago
Core tap JSON: 17 May 08:50 UTC
Core cask tap JSON: 17 May 08:50 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
% brew doctor

Your system is ready to brew.
```

### Output of `brew tap`

```
% brew tap
gcenx/wine
hashicorp/tap
homebrew/bundle
homebrew/cask-fonts
koekeishiya/formulae
```

**Comment by gscsnm** [comment]
same failed.

**Comment by bevanjkay** [comment]
I don't think there's a stable url available at the moment. We may need to wait until they migrated some more systems.

**Comment by viking1304** [comment]
I hope I am wrong, but I am very pessimistic about this issue. download3.vmware.com has been shut down since migration started, and it probably will never get back online. I cannot download the image even after I log in since my account has not been correctly migrated. 

If you go to https://www.vmware.com/products/desktop-hypervisor.html you will see that both links (for Mac and PC) now lead to https://support.broadcom.com/group/ecx/downloads and there is no option to download the installer without logging in first.

**Comment by miccal** [comment]
The downloads are available here and do not require logging in: 

https://customerconnect.omnissa.com/downloads/info/slug/desktop_end_user_computing/vmware_horizon_clients/horizon_8

At the moment they have the previous version, but I am sure the site will be updated eventually.

**Comment by krehel** [comment]
Draft PR at #174167

**Comment by krehel** [comment]
PR merged. Thanks everyone!
