### ISSUE TITLE
can't install bartender 

### ISSUE THREAD

**Issue by tkm5** [Homebrew/homebrew-cask#174119]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

When I try to download Bartender, it shows “SHA256 mismatch” and I can’t install it.

❯ brew install --cask bartender
==> Downloading https://macbartender.com/B2/updates/5-0-52/Bartender%205.zip
######################################################################################################################################### 100.0%
Error: SHA256 mismatch
Expected: b38281d2b744d3e057b6a1e82d80c43ddf5384fcae751b30655daceb16694e8e
  Actual: e5d54c9d31b2d7f50a22ce8e28b8010c2eba5686657d5caa0d7eada74b787b02
    File: /Users/takumig/Library/Caches/Homebrew/downloads/18511ca91a16177a87fc87d0bdeee17959dbeec371282b8101f8961543813700--Bartender 5.zip
To retry an incomplete download, remove the file above.

I tried deleting the displayed file and updating brew, but it didn't work.

### Command that failed

brew install --cask bartender

### Output of command with `--verbose --debug`

```shell
❯ brew install --cask bartender --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading bartender
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://macbartender.com/B2/updates/5-0-52/Bartender%205.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://macbartender.com/B2/updates/5-0-52/Bartender\%205.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://macbartender.com/B2/updates/5-0-52/Bartender\%205.zip
Already downloaded: /Users/takumig/Library/Caches/Homebrew/downloads/18511ca91a16177a87fc87d0bdeee17959dbeec371282b8101f8961543813700--Bartender 5.zip
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/takumig/Library/Caches/Homebrew/downloads/18511ca91a16177a87fc87d0bdeee17959dbeec371282b8101f8961543813700--Bartender 5.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/takumig/Library/Caches/Homebrew/downloads/18511ca91a16177a87fc87d0bdeee17959dbeec371282b8101f8961543813700--Bartender\ 5.zip
==> /Users/takumig/Library/Caches/Homebrew/downloads/18511ca91a16177a87fc87d0bdeee17959dbeec371282b8101f8961543813700--Bartender 5.zip is quarantined
==> Verifying checksum for '18511ca91a16177a87fc87d0bdeee17959dbeec371282b8101f8961543813700--Bartender 5.zip'
Error: SHA256 mismatch
Expected: b38281d2b744d3e057b6a1e82d80c43ddf5384fcae751b30655daceb16694e8e
  Actual: e5d54c9d31b2d7f50a22ce8e28b8010c2eba5686657d5caa0d7eada74b787b02
    File: /Users/takumig/Library/Caches/Homebrew/downloads/18511ca91a16177a87fc87d0bdeee17959dbeec371282b8101f8961543813700--Bartender 5.zip
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:300:in `verify_checksum'
/opt/homebrew/Library/Homebrew/downloadable.rb:100:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:83:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:62:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:186:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:102:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  neofetch

❯ brew config
HOMEBREW_VERSION: 4.3.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8378cc825d83acffd125fb0fec041793df378a57
Last commit: 3 days ago
Core tap JSON: 17 May 11:14 UTC
Core cask tap JSON: 17 May 11:14 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
azure/azd
dimentium/autoraise
domt4/autoupdate
homebrew/autoupdate
homebrew/bundle
homebrew/services
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/174106

**Comment by tkm5** [comment]
Fixed. Thanks.
