### ISSUE TITLE
github SHA256 Mismatch When Installing Version 3.3.18

### ISSUE THREAD

**Issue by kch-chiu** [Homebrew/homebrew-cask#174189]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

- Install github cask using brew on version 3.3.18
- The install command failed saying SHA256 mismatch

### Command that failed

brew install --cask github

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading github
==> Cask::Installer#install
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading github@beta
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0-78-gb8d844c\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.6.6\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://desktop.githubusercontent.com/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktop-arm64.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0-78-gb8d844c\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.6.6\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://desktop.githubusercontent.com/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktop-arm64.zip
==> Downloading https://desktop.githubusercontent.com/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktop-arm64.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.0-78-gb8d844c\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.6.6\)\ curl/8.4.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/kelchiu/Library/Caches/Homebrew/downloads/09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip.incomplete --location https://desktop.githubusercontent.com/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktop-arm64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  123M    0  123M    0     0  21.2M      0 --:--:--  0:00:05 --:--:-- 23.6M
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/kelchiu/Library/Caches/Homebrew/downloads/09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/kelchiu/Library/Caches/Homebrew/downloads/09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip
==> /Users/kelchiu/Library/Caches/Homebrew/downloads/09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip is not quarantined
==> Quarantining /Users/kelchiu/Library/Caches/Homebrew/downloads/09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/kelchiu/Library/Caches/Homebrew/downloads/09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip https://desktop.githubusercontent.com/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktop-arm64.zip https://desktop.github.com/
==> Verifying checksum for '09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip'
Error: SHA256 mismatch
Expected: 706652dfea890f3f4ee7506cabcffea175df91125d62c887ab4f58aa9d435b24
  Actual: e93de414170ed62263aaf278517a411bf2b8989ba58ce7679386c8760a24c017
    File: /Users/kelchiu/Library/Caches/Homebrew/downloads/09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:300:in `verify_checksum'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/downloadable.rb:100:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation_2_7.rb:687:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation_2_7.rb:687:in `block in create_validator_procedure_fast1'
/opt/homebrew/Library/Homebrew/cask/download.rb:83:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/download.rb:62:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:186:in `download'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:102:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11383/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.

HOMEBREW_VERSION: 4.3.0-78-gb8d844c
ORIGIN: https://github.com/Homebrew/brew
HEAD: b8d844ced8c2df5e8921dacfd02ea495a0ca8381
Last commit: 6 hours ago
Core tap HEAD: c4d29edcbae4da58a42e495e2d0a67715a2afad5
Core tap last commit: 2 hours ago
Core tap JSON: 17 May 18:19 UTC
Core cask tap HEAD: 4ad0de64113a72eb41568539edb14bf66019798f
Core cask tap last commit: 3 hours ago
Core cask tap JSON: 17 May 21:22 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
all_proxy: http://localhost:3128
ftp_proxy: http://localhost:3128
http_proxy: http://localhost:3128
https_proxy: http://localhost:3128
no_proxy: 127.0.0.*,10.*,172.*,192.168.*,*.fg.rbc.com,*.devfg.rbc.com,*.saifg.rbc.com,*.sterbc.com,localhost,*.azurecr.io,*.privatelink.canadaeast.azmk8s.io,*.privatelink.canadacentral.azmk8s.io,*.onmicrosoft.com,*.msappproxy.net,*.azureprivatedns.net,*.c1.rbc.com,kubernetes.docker.internal,*.database.windows.net,docker-secure-kyv0.rbcartifactory.fg.rbc.com,*.blob.core.windows.net
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 13.6.6-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
azure/kubelogin
homebrew/cask
homebrew/core
homebrew/services
```

**Comment by kch-chiu** [comment]
Reopening issue as the problem still exists.

**Comment by miccal** [comment]
I am unable to reproduce:
```
|-> brew fetch --arch=all github
==> Downloading https://desktop.githubusercontent.com/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktop-x64.zip
################################################################################################################ 100.0%
Downloaded to: /Users/miccal/Library/Caches/Homebrew/downloads/3249331d604ebe85bc118600b3e045fcdc0bab06c447a805015b103cf57edd01--GitHubDesktop-x64.zip
SHA256: 87ce40617255aee7be4c8ee12e7c0a0897878858e801f11a0fe548ea2d63524a
==> Downloading https://desktop.githubusercontent.com/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktop-arm64.zip
################################################################################################################ 100.0%
Downloaded to: /Users/miccal/Library/Caches/Homebrew/downloads/09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip
SHA256: 706652dfea890f3f4ee7506cabcffea175df91125d62c887ab4f58aa9d435b24
```

**Comment by kch-chiu** [comment]
Able to replicate this issue:

➜  ~ brew fetch --arch=all github

==> Downloading https://desktop.githubusercontent.com/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktop-x64.zip

                                                                                      #               #                #               #            -=O=-

Downloaded to: /Users/kelchiu/Library/Caches/Homebrew/downloads/3249331d604ebe85bc118600b3e045fcdc0bab06c447a805015b103cf57edd01--GitHubDesktop-x64.zip

SHA256: 46d068ff29f9e163c51c15f61b2253aac00266d79bcce144ef621edfb2a22e62

Warning: Cask reports different sha256: 87ce40617255aee7be4c8ee12e7c0a0897878858e801f11a0fe548ea2d63524a

==> Downloading https://desktop.githubusercontent.com/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktop-arm64.zip

Already downloaded: /Users/kelchiu/Library/Caches/Homebrew/downloads/09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip

SHA256: 0c297d9888cb551b50cace4fdfe8b54b7068bed1401400c7557cbe53e68872c1

Warning: Cask reports different sha256: 706652dfea890f3f4ee7506cabcffea175df91125d62c887ab4f58aa9d435b24

**Comment by kch-chiu** [comment]
On /Users/kelchiu/Library/Caches/Homebrew/downloads, running “sha256sum 09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip” gives me this result:

0c297d9888cb551b50cace4fdfe8b54b7068bed1401400c7557cbe53e68872c1  09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip

Not able to push updates to casks on master branch.
 
Can you please update this SHA256 Checksum on the github cask?

0c297d9888cb551b50cace4fdfe8b54b7068bed1401400c7557cbe53e68872c1

**Comment by miccal** [comment]
> Can you please update this SHA256 Checksum on the github cask?

I (still) cannot reproduce this issue, hence I am not able to do this:
```
|-> brew fetch --arch=all github
==> Downloading https://desktop.githubusercontent.com/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktop-x64.zip
########################################################################################################################################################################################################################################## 100.0%
Downloaded to: /Users/miccal/Library/Caches/Homebrew/downloads/3249331d604ebe85bc118600b3e045fcdc0bab06c447a805015b103cf57edd01--GitHubDesktop-x64.zip
SHA256: 87ce40617255aee7be4c8ee12e7c0a0897878858e801f11a0fe548ea2d63524a
==> Downloading https://desktop.githubusercontent.com/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktop-arm64.zip
########################################################################################################################################################################################################################################## 100.0%
Downloaded to: /Users/miccal/Library/Caches/Homebrew/downloads/09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip
SHA256: 706652dfea890f3f4ee7506cabcffea175df91125d62c887ab4f58aa9d435b24
```
Run the command `rm -rf "$(brew --cache)"` and then try again.

**Comment by kch-chiu** [comment]
Running these commands:

rm -rf “$(brew --cache)”
brew fetch --arch=arm github

Gives me this warning:

Downloaded to: /Users/kelchiu/Library/Caches/Homebrew/downloads/09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip
SHA256: 13c263100f8c714856d3040d39abbfb7fc4a6333f65a2c67ad82cc22ea6cffd6
Warning: Cask reports different sha256: 706652dfea890f3f4ee7506cabcffea175df91125d62c887ab4f58aa9d435b24

Will work with another cask which works for me.

**Comment by krehel** [comment]
Seeing the same as @miccal.  Have you verified the download is complete and valid @kch-chiu, such as by manually checking the zip and opening it?

```
brew fetch --arch=all github
==> Downloading https://desktop.githubusercontent.com/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktop-x64.zip
########################################################################################################################################### 100.0%
Downloaded to: /Users/jay/Library/Caches/Homebrew/downloads/3249331d604ebe85bc118600b3e045fcdc0bab06c447a805015b103cf57edd01--GitHubDesktop-x64.zip
SHA256: 87ce40617255aee7be4c8ee12e7c0a0897878858e801f11a0fe548ea2d63524a
==> Downloading https://desktop.githubusercontent.com/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktop-arm64.zip
Already downloaded: /Users/jay/Library/Caches/Homebrew/downloads/09233fd6b322306de20ee2bdf8693e9d18b7091313de5e00ae4335370239ac06--GitHubDesktop-arm64.zip
SHA256: 706652dfea890f3f4ee7506cabcffea175df91125d62c887ab4f58aa9d435b24
```

**Comment by kch-chiu** [comment]
Verified the download is complete. Can manually download the zip and open it. This command still doesn't work for me:
"brew install --cask github". Still getting the SHA256 mismatch error.

Issue is not there when installing other casks.

Closing the issue and retrying at a later time.

Thanks.
