### ISSUE TITLE
Cask texshop cannot be updated

### ISSUE THREAD

**Issue by Jamespark0** [Homebrew/homebrew-cask#174498]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

When updating Texshop, I constantly get the following message:
```
Error: SHA256 mismatch
Expected: 4ef9286e0d4c03f609690c39e2f219e31ee538abe454c125760fc68ba5d7a17f
  Actual: d6da42bc81f19f69de3e31f6a5b05e8937856ccdb07360a80873f898fe33c9a4
    File: /Users/simonhuang/Library/Caches/Homebrew/downloads/5140f69e123b23d28013911ceff2325ebc754bb75dd4f3a3fc9cb954eaa1dd07--texshop535.zip
```

### Command that failed

brew upgrade --cask texshop

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading texshop
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/texshop/.metadata/5.33/20240425091628.307/Casks/texshop.json
texshop 5.33 -> 5.35
==> Started upgrade process for Cask texshop
==> Upgrading texshop
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://pages.uoregon.edu/koch/texshop/texshop-64/texshop535.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://pages.uoregon.edu/koch/texshop/texshop-64/texshop535.zip
==> Downloading https://pages.uoregon.edu/koch/texshop/texshop-64/texshop535.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://pages.uoregon.edu/koch/texshop/texshop-64/texshop535.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://pages.uoregon.edu/koch/texshop/texshop-64/texshop535.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/simonhuang/Library/Caches/Homebrew/downloads/5140f69e123b23d28013911ceff2325ebc754bb75dd4f3a3fc9cb954eaa1dd07--texshop535.zip.incomplete --location https://pages.uoregon.edu/koch/texshop/texshop-64/texshop535.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 66.3M  100 66.3M    0     0   369k      0  0:03:04  0:03:04 --:--:--  385k
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/simonhuang/Library/Caches/Homebrew/downloads/5140f69e123b23d28013911ceff2325ebc754bb75dd4f3a3fc9cb954eaa1dd07--texshop535.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/simonhuang/Library/Caches/Homebrew/downloads/5140f69e123b23d28013911ceff2325ebc754bb75dd4f3a3fc9cb954eaa1dd07--texshop535.zip
==> /Users/simonhuang/Library/Caches/Homebrew/downloads/5140f69e123b23d28013911ceff2325ebc754bb75dd4f3a3fc9cb954eaa1dd07--texshop535.zip is not quarantined
==> Quarantining /Users/simonhuang/Library/Caches/Homebrew/downloads/5140f69e123b23d28013911ceff2325ebc754bb75dd4f3a3fc9cb954eaa1dd07--texshop535.zip
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/simonhuang/Library/Caches/Homebrew/downloads/5140f69e123b23d28013911ceff2325ebc754bb75dd4f3a3fc9cb954eaa1dd07--texshop535.zip https://pages.uoregon.edu/koch/texshop/texshop-64/texshop535.zip https://pages.uoregon.edu/koch/texshop/
==> Verifying checksum for '5140f69e123b23d28013911ceff2325ebc754bb75dd4f3a3fc9cb954eaa1dd07--texshop535.zip'
==> Purging files for version 5.35 of Cask texshop
Error: texshop: SHA256 mismatch
Expected: 4ef9286e0d4c03f609690c39e2f219e31ee538abe454c125760fc68ba5d7a17f
  Actual: d6da42bc81f19f69de3e31f6a5b05e8937856ccdb07360a80873f898fe33c9a4
    File: /Users/simonhuang/Library/Caches/Homebrew/downloads/5140f69e123b23d28013911ceff2325ebc754bb75dd4f3a3fc9cb954eaa1dd07--texshop535.zip
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:300:in `verify_checksum'
/opt/homebrew/Library/Homebrew/downloadable.rb:100:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:83:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:62:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:186:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:192:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:260:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:138:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.
HOMEBREW_VERSION: 4.3.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: e0bc557e7b991cb23583679e1cf1c8a92b793aeb
Last commit: 2 days ago
Core tap JSON: 22 May 09:17 UTC
Core cask tap JSON: 22 May 09:17 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: ansi
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### Output of `brew tap`

```shell
buo/cask-upgrade
coursier/formulas
homebrew/bundle
homebrew/services
tabbyml/tabby
```

**Comment by bevanjkay** [comment]
https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/174520

**Comment by Jamespark0** [comment]
> #174520

Thanks, the issue was solved. This message should have been sent a lot earlier.
