### ISSUE TITLE
cloudflare-warp fails to install

### ISSUE THREAD

**Issue by elisiariocouto** [Homebrew/homebrew-cask#174856]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Cloudflare Warp fails to install. Apparently, the extract process is not creating the pkg, possibly because of the comma on the version number?

### Command that failed

brew install cloudflare-warp

### Output of command with `--verbose --debug`

```shell
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.3.1-65-gf26fa34\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --remote-time --output /Users/elisiariocouto/Library/Caches/Homebrew/api/formula.jws.json --location --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1-65-gf26fa34\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4306k  100 4306k    0     0  29.8M      0 --:--:-- --:--:-- --:--:-- 30.0M
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading cloudflare-warp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading cloudflare-warp
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.3.1-65-gf26fa34\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --remote-time --output /Users/elisiariocouto/Library/Caches/Homebrew/api/cask.jws.json --location --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1-65-gf26fa34\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1449k  100 1449k    0     0  15.1M      0 --:--:-- --:--:-- --:--:-- 15.2M
==> Downloading https://formulae.brew.sh/api/cask_tap_migrations.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.3.1-65-gf26fa34\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --remote-time --output /Users/elisiariocouto/Library/Caches/Homebrew/api/cask_tap_migrations.jws.json --location --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1-65-gf26fa34\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask_tap_migrations.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1015  100  1015    0     0  26996      0 --:--:-- --:--:-- --:--:-- 27432
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading cloudflare-warp
==> Downloading https://formulae.brew.sh/api/formula_tap_migrations.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.3.1-65-gf26fa34\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --remote-time --output /Users/elisiariocouto/Library/Caches/Homebrew/api/formula_tap_migrations.jws.json --location --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1-65-gf26fa34\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula_tap_migrations.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   970  100   970    0     0  26204      0 --:--:-- --:--:-- --:--:-- 26944
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1-65-gf26fa34\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://1111-releases.cloudflareclient.com/mac/Cloudflare_WARP_2024.3.407.0.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1-65-gf26fa34\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://1111-releases.cloudflareclient.com/mac/Cloudflare_WARP_2024.3.407.0.zip
==> Downloading https://1111-releases.cloudflareclient.com/mac/Cloudflare_WARP_2024.3.407.0.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1-65-gf26fa34\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://1111-releases.cloudflareclient.com/mac/Cloudflare_WARP_2024.3.407.0.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1-65-gf26fa34\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://1111-releases.cloudflareclient.com/mac/Cloudflare_WARP_2024.3.407.0.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1-65-gf26fa34\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip.incomplete --location https://1111-releases.cloudflareclient.com/mac/Cloudflare_WARP_2024.3.407.0.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 70.1M  100 70.1M    0     0  3824k      0  0:00:18  0:00:18 --:--:-- 3905k
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip
==> /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip is not quarantined
==> Quarantining /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip https://1111-releases.cloudflareclient.com/mac/Cloudflare_WARP_2024.3.407.0.zip https://cloudflarewarp.com/
==> Verifying checksum for '4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip'
/usr/bin/env hdiutil imageinfo -format /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip
==> Installing Cask cloudflare-warp
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Xar for /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip
/usr/bin/env xar -x -f /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip -C /private/tmp/homebrew-unpack20240525-59270-9isbl6
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240525-59270-9isbl6/Distribution /opt/homebrew/Caskroom/cloudflare-warp/2024.3.407.0,20240329.17/Distribution
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240525-59270-9isbl6/Cloudflare_WARP_2024.3.407.0.pkg/. /opt/homebrew/Caskroom/cloudflare-warp/2024.3.407.0,20240329.17/Cloudflare_WARP_2024.3.407.0.pkg
==> Verifying Gatekeeper status of /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip
==> /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip is quarantined
==> Propagating quarantine from /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip to /opt/homebrew/Caskroom/cloudflare-warp/2024.3.407.0,20240329.17
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/elisiariocouto/Library/Caches/Homebrew/downloads/4a1511552233c26d6ab26052aec933e9f248ed59328e1967664fd9bffd4c33f7--Cloudflare_WARP_2024.3.407.0.zip
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;66523d84\;Homebrew\\x20Cask\;A17254E5-6401-4DDC-AD3C-E464FCCA518F
==> Creating metadata directory: /opt/homebrew/Caskroom/cloudflare-warp/.metadata/2024.3.407.0,20240329.17/20240525193533.211
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/cloudflare-warp/.metadata/2024.3.407.0,20240329.17/20240525193533.211/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for cloudflare-warp with sudo; the password may be necessary.
/usr/bin/sudo -u root -E LOGNAME=elisiariocouto USER=elisiariocouto USERNAME=elisiariocouto -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/cloudflare-warp/2024.3.407.0,20240329.17/Cloudflare_WARP_2024.3.407.0.pkg -target / -verboseR
installer: Error - the package path specified was invalid: '/opt/homebrew/Caskroom/cloudflare-warp/2024.3.407.0,20240329.17/Cloudflare_WARP_2024.3.407.0.pkg'.
==> Purging files for version 2024.3.407.0,20240329.17 of Cask cloudflare-warp
Error: Failure while executing; `/usr/bin/sudo -u root -E LOGNAME=elisiariocouto USER=elisiariocouto USERNAME=elisiariocouto -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/cloudflare-warp/2024.3.407.0,20240329.17/Cloudflare_WARP_2024.3.407.0.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Error - the package path specified was invalid: '/opt/homebrew/Caskroom/cloudflare-warp/2024.3.407.0,20240329.17/Cloudflare_WARP_2024.3.407.0.pkg'.
/opt/homebrew/Library/Homebrew/system_command.rb:352:in `assert_success!'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation_2_7.rb:652:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation_2_7.rb:652:in `block in create_validator_procedure_fast0'
/opt/homebrew/Library/Homebrew/system_command.rb:75:in `run!'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
/opt/homebrew/Library/Homebrew/system_command.rb:40:in `run'
/opt/homebrew/Library/Homebrew/system_command.rb:44:in `run!'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:63:in `block in run_installer'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:76:in `with_choices_file'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:56:in `run_installer'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:32:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:248:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:241:in `install_artifacts'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
`brew doctor`
Your system is ready to brew.

`brew config`
HOMEBREW_VERSION: 4.3.1-65-gf26fa34
ORIGIN: https://github.com/Homebrew/brew
HEAD: f26fa34232adc3f175c4e26a3a026ff14114a59a
Last commit: 2 hours ago
Core tap JSON: 25 May 19:35 UTC
Core cask tap JSON: 25 May 19:35 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
alexmyczko/mac
cue-lang/tap
hashicorp/tap
homebrew/services
jorgelbg/tap
styrainc/packages
```

**Comment by bevanjkay** [comment]
See previous discussion for reference - https://github.com/Homebrew/homebrew-cask/issues/171659

**Comment by cho-m** [comment]
Cloudflare may have changed download files?

For me, it looks like redirect goes to `.pkg` now:
```console
❯ curl -sI https://1111-releases.cloudflareclient.com/mac/Cloudflare_WARP_2024.3.407.0.zip | rg location:
location: https://appcenter-filemanagement-distrib3ede6f06e.azureedge.net/9754fdce-bef4-4215-8721-262dc5522c48/Cloudflare_WARP_2024.3.407.0.pkg?sv=2019-02-02&sr=c&sig=fKJYlMLrScYK%2BawoGsQwQSiCbqpnitnRXtoXyp1PJBc%3D&se=2024-05-28T12%3A06%3A04Z&sp=r
```

From download locations listed in docs at https://developers.cloudflare.com/warp-client/get-started/macos/,
* Microsoft App Center seems to be pkg
* 1.1.1.1 link is unversioned zip

**Comment by bevanjkay** [comment]
I'll see if updating to use the `pkg` link works.

**Comment by bevanjkay** [comment]
I think we have also seen some A/B testing in the past between a versioned and unversioned package, hopefully pointing directly to the `pkg` solves this issue.
