### ISSUE TITLE
scilab cask uses out-of-date URLs for download which are very slow

### ISSUE THREAD

**Issue by juergenpf** [Homebrew/homebrew-cask#174873]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

The scilab cask uses outdated URLs, which point to a very low bandwith server. I've contacted the scilab maintainers and they have reacted and now the MacOS packages are hosted on their main servers with much better download speeds.
The URLs for the current versions are now

https://www.scilab.org/download/2024.1.0/scilab-2024.1.0-x86_64.dmg
https://www.scilab.org/download/2024.1.0/scilab-2024.1.0-arm64.dmg

Would be great if you could update the scilab recipe.

### Command that failed

brew upgrade scilab --verbose --debug

### Output of command with `--verbose --debug`

```shell
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --remote-time --output /Users/juergen/Library/Caches/Homebrew/api/formula.jws.json --location --time-cond /Users/juergen/Library/Caches/Homebrew/api/formula.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading scilab
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading scilab
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading scilab
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --remote-time --output /Users/juergen/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/juergen/Library/Caches/Homebrew/api/cask.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading scilab
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/scilab/.metadata/2024.0.0/20231212003222.482/Casks/scilab.json
scilab 2024.0.0 -> 2024.1.0
==> Started upgrade process for Cask scilab
==> Upgrading scilab
==> Printing caveats
==> Caveats
scilab requires Java 8. You can install it with:
  brew install --cask temurin@8

==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://www.utc.fr/\~mottelet/scilab/download/2024.1.0/scilab-2024.1.0-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://www.utc.fr/\~mottelet/scilab/download/2024.1.0/scilab-2024.1.0-arm64.dmg
==> Downloading https://www.utc.fr/~mottelet/scilab/download/2024.1.0/scilab-2024.1.0-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://www.utc.fr/\~mottelet/scilab/download/2024.1.0/scilab-2024.1.0-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://www.utc.fr/\~mottelet/scilab/download/2024.1.0/scilab-2024.1.0-arm64.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/juergen/Library/Caches/Homebrew/downloads/c47690939b5b240c26975e287b3304df5717d2dbb97ebc4711189dc6f064ad44--scilab-2024.1.0-arm64.dmg.incomplete --location https://www.utc.fr/\~mottelet/scilab/download/2024.1.0/scilab-2024.1.0-arm64.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   150    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 502
Warning: Problem : HTTP error. Will retry in 1 seconds. 3 retries left.
  0   150    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 502
Warning: Problem : HTTP error. Will retry in 2 seconds. 2 retries left.
  0   150    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 502
Warning: Problem : HTTP error. Will retry in 4 seconds. 1 retries left.
  0   150    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 502
==> Purging files for version 2024.1.0 of Cask scilab
Error: scilab: Download failed on Cask 'scilab' with message: Download failed: https://www.utc.fr/~mottelet/scilab/download/2024.1.0/scilab-2024.1.0-arm64.dmg
/opt/homebrew/Library/Homebrew/download_strategy.rb:434:in `rescue in fetch'
/opt/homebrew/Library/Homebrew/download_strategy.rb:431:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:86:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:53:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:186:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:192:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:260:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:138:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
$
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  arduino
  brackets
  komodo-edit

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python-pathspec

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  neofetch
  openssl@1.1
  pam_yubico
  ykclient

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-versions
  Homebrew/homebrew-cask-drivers
Untap them with `brew untap`.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libhylafsp.dylib
  /usr/local/lib/libjson-c.2.dylib
  /usr/local/lib/libpas2jslib.dylib
  /usr/local/lib/libykclient.3.dylib
  /usr/local/lib/libykpers-1.1.dylib
  /usr/local/lib/libyubikey.0.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ocaml

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /opt/homebrew/bin/scilab
  /opt/homebrew/bin/scilab-cli

==========================================================================================
HOMEBREW_VERSION: 4.3.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: e0bc557e7b991cb23583679e1cf1c8a92b793aeb
Last commit: 6 days ago
Core tap JSON: 25 May 23:10 UTC
Core cask tap JSON: 25 May 23:10 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.JPzpGzICQI/org.xquartz:0
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/cask-drivers
homebrew/cask-versions
sidneys/homebrew
```

**Comment by krehel** [comment]
Appreciate reaching out to upstream and having this resolved for the community. Thank you!

Please do feel free to open a PR with the changes.

If you need help to get it finished we're happy to support.

**Comment by juergenpf** [comment]
Well, I created a PR, but it failed in some tests and that’s quite certainly because I’ve no experice with ruby.
Nevertheless the recipe is simple and I basically thought I understood what’s necessary.
I think the key issue is to provide the correct URL for the llivecheck.  I think I figured out what’s going wrong and will do a second attempt.
If that fails too, I might need some support.

Jürgen

**Comment by juergenpf** [comment]
Well, now the PR passed all the tests, it’s up to review now to get merged.

Jürgen
