### ISSUE TITLE
Unable to install yandex-cloud-cli (0.124.0)

### ISSUE THREAD

**Issue by unreturned** [Homebrew/homebrew-cask#175038]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Looks like the problem that described in https://github.com/Homebrew/homebrew-cask/issues/173982 and not solved by https://github.com/Homebrew/homebrew-cask/pull/174014 for me.

### Command that failed

brew install yandex-cloud-cli

### Output of command with `--verbose --debug`

```shell
brew install --verbose --debug yandex-cloud-cli
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading yandex-cloud-cli
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading yandex-cloud-cli
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading yandex-cloud-cli
==> Cask::Installer#install
==> Printing caveats
==> Caveats
To install shell completions add this to your profile:

  for bash users
    source "/opt/homebrew/Caskroom/yandex-cloud-cli/0.124.0/yandex-cloud-cli/completion.bash.inc"

  for zsh users
    source "/opt/homebrew/Caskroom/yandex-cloud-cli/0.124.0/yandex-cloud-cli/completion.zsh.inc"

==> Cask::Installer#fetch
==> Downloading https://storage.yandexcloud.net/yandexcloud-yc/install.sh
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.2-16-g92adf6a\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://storage.yandexcloud.net/yandexcloud-yc/install.sh
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.2-16-g92adf6a\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://storage.yandexcloud.net/yandexcloud-yc/install.sh
Already downloaded: /Users/kovalkov/Library/Caches/Homebrew/downloads/e0e68b066c559c1f3270ca5dda658681b4ba835addcd465d99f828ce47298c55--install.sh
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/kovalkov/Library/Caches/Homebrew/downloads/e0e68b066c559c1f3270ca5dda658681b4ba835addcd465d99f828ce47298c55--install.sh
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/kovalkov/Library/Caches/Homebrew/downloads/e0e68b066c559c1f3270ca5dda658681b4ba835addcd465d99f828ce47298c55--install.sh
==> /Users/kovalkov/Library/Caches/Homebrew/downloads/e0e68b066c559c1f3270ca5dda658681b4ba835addcd465d99f828ce47298c55--install.sh is quarantined
Warning: No checksum defined for cask 'yandex-cloud-cli', skipping verification.
/usr/bin/env hdiutil imageinfo -format /Users/kovalkov/Library/Caches/Homebrew/downloads/e0e68b066c559c1f3270ca5dda658681b4ba835addcd465d99f828ce47298c55--install.sh
==> Installing Cask yandex-cloud-cli
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Executable for /Users/kovalkov/Library/Caches/Homebrew/downloads/e0e68b066c559c1f3270ca5dda658681b4ba835addcd465d99f828ce47298c55--install.sh
cp -p /Users/kovalkov/Library/Caches/Homebrew/downloads/e0e68b066c559c1f3270ca5dda658681b4ba835addcd465d99f828ce47298c55--install.sh /opt/homebrew/Caskroom/yandex-cloud-cli/0.124.0/install.sh
==> Verifying Gatekeeper status of /Users/kovalkov/Library/Caches/Homebrew/downloads/e0e68b066c559c1f3270ca5dda658681b4ba835addcd465d99f828ce47298c55--install.sh
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/kovalkov/Library/Caches/Homebrew/downloads/e0e68b066c559c1f3270ca5dda658681b4ba835addcd465d99f828ce47298c55--install.sh
==> /Users/kovalkov/Library/Caches/Homebrew/downloads/e0e68b066c559c1f3270ca5dda658681b4ba835addcd465d99f828ce47298c55--install.sh is quarantined
==> Propagating quarantine from /Users/kovalkov/Library/Caches/Homebrew/downloads/e0e68b066c559c1f3270ca5dda658681b4ba835addcd465d99f828ce47298c55--install.sh to /opt/homebrew/Caskroom/yandex-cloud-cli/0.124.0
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/kovalkov/Library/Caches/Homebrew/downloads/e0e68b066c559c1f3270ca5dda658681b4ba835addcd465d99f828ce47298c55--install.sh
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0381\;663a6d3a\;\;2F3F6437-D50A-4D3E-AF4F-1F82FCE1F77D
==> Creating metadata directory: /opt/homebrew/Caskroom/yandex-cloud-cli/.metadata/0.124.0/20240527210739.944
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/yandex-cloud-cli/.metadata/0.124.0/20240527210739.944/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Installer
==> Running installer script 'yandex-cloud-cli/bin/yc'
/usr/bin/env PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin yandex-cloud-cli/bin/yc components post-update
env: yandex-cloud-cli/bin/yc: No such file or directory
==> Purging files for version 0.124.0 of Cask yandex-cloud-cli
Error: Failure while executing; `/usr/bin/env PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin yandex-cloud-cli/bin/yc components post-update` exited with 127. Here's the output:
env: yandex-cloud-cli/bin/yc: No such file or directory

/opt/homebrew/Library/Homebrew/system_command.rb:352:in `assert_success!'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation_2_7.rb:652:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation_2_7.rb:652:in `block in create_validator_procedure_fast0'
/opt/homebrew/Library/Homebrew/system_command.rb:75:in `run!'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
/opt/homebrew/Library/Homebrew/system_command.rb:40:in `run'
/opt/homebrew/Library/Homebrew/system_command.rb:44:in `run!'
/opt/homebrew/Library/Homebrew/cask/artifact/installer.rb:35:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:248:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:241:in `install_artifacts'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11391/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
~$ brew doctor; brew config
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python-jinja
  python-pluggy
  python-pyparsing
  python-mutagen
  python-brotli
  python-markupsafe

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  python-dateutil
  python-lxml
  python-pytz
  vault
HOMEBREW_VERSION: 4.3.2-16-g92adf6a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 92adf6a0b71e59d3348c982d11e2560dc9317687
Last commit: 3 hours ago
Core tap JSON: 27 May 21:05 UTC
Core cask tap JSON: 27 May 21:05 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: ssh-askpass
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
SUDO_ASKPASS: /opt/homebrew/opt/ssh-askpass/bin/ssh-askpass
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/services
int128/kubelogin
theseal/ssh-askpass
```

**Comment by yakimant** [comment]
Same!

**Comment by dgorpinchuk** [comment]
Same 
```
Yandex Cloud CLI 0.126.0 darwin/arm64
==> Running installer script 'yandex-cloud-cli/bin/yc'
==> Linking Binary 'docker-credential-yc' to '/opt/homebrew/bin/docker-credential-yc'
==> Linking Binary 'yc' to '/opt/homebrew/bin/yc'
Error: yandex-cloud-cli: Failure while executing; `/usr/bin/env PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin yandex-cloud-cli/bin/yc components post-update` exited with 127. Here's the output:
env: yandex-cloud-cli/bin/yc: No such file or directory
```

**Comment by dm4web** [comment]
#176462 not resolved this issue

`
==> Installing Cask yandex-cloud-cli
==> Running installer script 'yandex-cloud-cli/bin/yc'
env: yandex-cloud-cli/bin/yc: No such file or directory
==> Purging files for version 0.125.0 of Cask yandex-cloud-cli
Error: Failure while executing; `/usr/bin/env PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin yandex-cloud-cli/bin/yc components post-update` exited with 127. Here's the output:
env: yandex-cloud-cli/bin/yc: No such file or directory
`

**Comment by bevanjkay** [comment]
The upstream installer is setup to download and install the binaries on the fly, it looks like something is preventing the `curl` part to run on your machines. Does the installer succeed if you run it directly following the upstream instructions?

`curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash`

**Comment by bevanjkay** [comment]
Thanks @unreturned - I think I have found the issue and have opened a PR to fix.
