### ISSUE TITLE
Can't update or remove redis-stack-server

### ISSUE THREAD

**Issue by dwn3** [Homebrew/homebrew-cask#176394]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Cannot update or remove Redis-Stack-Server

### Command that failed

brew uninstall redis-stack-server 

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading redis-stack-server
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromNameLoader): loading redis-stack-server
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240417115015.852/Casks/redis-stack-server.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libtiff
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/gmp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/wget
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/rgbds
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/xorgproto
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libidn2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libxau
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/little-cms2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/go
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libpng
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/pixman
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/gdbm
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/mpdecimal
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libxdmcp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/cmake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/freetype
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/mpfr
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libunistring
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libyaml
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/icu4c
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/harfbuzz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/python@3.12
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/glib
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libxcb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/readline
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/r
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/lz4
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/ruby-install
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/graphite2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/gcc
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/cairo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/sqlite
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/fontconfig
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/chruby
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/openjdk
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/openblas
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/giflib
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libxrender
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/openssl@3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/ca-certificates
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/gettext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/zstd
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/tcl-tk
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/autoconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libxext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/m4
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/isl
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/pcre2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libomp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/sdl2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/python@3.11
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/bison
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libx11
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/automake
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/lzo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libffi
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/jpeg-turbo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading homebrew/core/libmpc
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading docker
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading firefox
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromNameLoader): loading redis-stack-server
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading rstudio
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading jpeg-turbo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading lz4
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading zstd
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libunistring
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gettext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libidn2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading ca-certificates
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading openssl@3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libpng
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libunistring
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gettext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xorgproto
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading jpeg-turbo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading lz4
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading zstd
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libtiff
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xorgproto
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libpng
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gmp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libpng
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading freetype
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading fontconfig
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pcre2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading mpdecimal
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading ca-certificates
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading openssl@3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading readline
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading sqlite
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading python@3.12
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gettext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading glib
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xorgproto
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxau
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxdmcp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxcb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libx11
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxrender
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading lzo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pixman
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cairo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading graphite2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading icu4c
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading mpdecimal
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading ca-certificates
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading openssl@3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading readline
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading sqlite
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pcre2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading mpdecimal
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading ca-certificates
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading openssl@3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading readline
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading sqlite
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading python@3.12
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gettext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xorgproto
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxau
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxdmcp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libpng
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading freetype
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading fontconfig
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pcre2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading mpdecimal
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading ca-certificates
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading openssl@3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading readline
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading sqlite
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading python@3.12
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gettext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading glib
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xorgproto
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxau
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxdmcp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxcb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libx11
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxrender
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading lzo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pixman
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cairo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gmp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading isl
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading mpfr
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libmpc
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading lz4
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading zstd
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gcc
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading jpeg-turbo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading openblas
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading tcl-tk
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gmp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading isl
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading mpfr
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libmpc
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading lz4
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading zstd
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libpng
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading freetype
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading fontconfig
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pcre2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gettext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading glib
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xorgproto
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxau
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxdmcp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxcb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libx11
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxrender
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading lzo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pixman
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading readline
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libpng
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading freetype
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading giflib
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libpng
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading freetype
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading fontconfig
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pcre2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading mpdecimal
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading ca-certificates
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading openssl@3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading readline
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading sqlite
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading python@3.12
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gettext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading glib
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xorgproto
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxau
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxdmcp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxcb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libx11
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxext
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxrender
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading lzo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading pixman
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading cairo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading graphite2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading icu4c
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading harfbuzz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading jpeg-turbo
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading lz4
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading zstd
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libtiff
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading little-cms2
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gmp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading isl
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading mpfr
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libmpc
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading lz4
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading zstd
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gcc
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xorgproto
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxau
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxdmcp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxcb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libx11
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading ca-certificates
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading lz4
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading ca-certificates
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading openssl@3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading m4
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xorgproto
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxau
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxdmcp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxcb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libx11
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gmp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading mpdecimal
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading ca-certificates
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading openssl@3
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading readline
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading sqlite
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xz
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading xorgproto
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxau
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxdmcp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading libxcb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading m4
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading autoconf
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gmp
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading mpfr
==> Uninstalling Cask redis-stack-server
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240417115015.852/Casks/redis-stack-server.rb
==> Uninstalling Cask redis-stack-server
==> Uninstalling artifacts
==> 2 artifacts defined
#<Cask::ArtifactSet: {#<Cask::Artifact::PostflightBlock:0x00000001407be288 @cask=#<Cask redis-stack-server /opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240417115015.852/Casks/redis-stack-server.rb>, @dsl_args=[], @directives={:uninstall_postflight=>#<Proc:0x00000001407be300 /opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240417115015.852/Casks/redis-stack-server.rb:26>}>, #<Cask::Artifact::PostflightBlock:0x00000001407be170 @cask=#<Cask redis-stack-server /opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240417115015.852/Casks/redis-stack-server.rb>, @dsl_args=[], @directives={:postflight=>#<Proc:0x00000001407be1c0 /opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240417115015.852/Casks/redis-stack-server.rb:51>}>}>
==> Uninstalling artifact of class Cask::Artifact::PostflightBlock
Error: undefined method `exists?' for class File
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240417115015.852/Casks/redis-stack-server.rb:34:in `block (3 levels) in load'
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240417115015.852/Casks/redis-stack-server.rb:32:in `each'
/opt/homebrew/Caskroom/redis-stack-server/.metadata/7.2.0-v10/20240417115015.852/Casks/redis-stack-server.rb:32:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:47:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:30:in `uninstall_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:474:in `block in uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:471:in `uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:409:in `uninstall'
/opt/homebrew/Library/Homebrew/cask/uninstall.rb:14:in `block in uninstall_casks'
/opt/homebrew/Library/Homebrew/cask/uninstall.rb:9:in `each'
/opt/homebrew/Library/Homebrew/cask/uninstall.rb:9:in `uninstall_casks'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:73:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.

HOMEBREW_VERSION: 4.3.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3f08c75e7b950d4340dab462f3e7f77e8093fa2b
Last commit: 11 hours ago
Core tap JSON: 11 Jun 14:12 UTC
Core cask tap JSON: 11 Jun 14:12 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.3.2 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.2/bin/ruby
CPU: 16-core 64-bit arm_palma
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### Output of `brew tap`

```shell
redis-stack/redis-stack
```

**Comment by miccal** [comment]
https://github.com/Homebrew/brew/issues/17458#issuecomment-2159256493
