### ISSUE TITLE
Formula "fxfactory" continuously updating incorrect sha256 by BrewTestBot

### ISSUE THREAD

**Issue by yuusharo** [Homebrew/homebrew-cask#179556]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

BrewTestBot refuses to update the formula to include the correct hash for FxFactory. This issue has persisted through multiple versions, and the various supported paths to issue a PR update are refused due to BrewTestBot's usage.

Current version: 8.0.16,7877
BrewTestBot's hash: 59967d2ae46570dafa7ab4bf680e068c0b26ec909e70046e2491d61b7dd263b7
Actual hash: 1f7b09867d2aa3eebcf3096e57fa38fc5d4fd8fe1e736156211845ebd8af00f1

### Command that failed

brew upgrade fxfactory

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading fxfactory
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading fxfactory
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading fxfactory
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading fxfactory
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/fxfactory/.metadata/8.0.15,7831/20240428054610.558/Casks/fxfactory.json
fxfactory 8.0.15,7831 -> 8.0.16,7877
==> Started upgrade process for Cask fxfactory
==> Upgrading fxfactory
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://fxfactory.s3.amazonaws.com/noiseindustries/fxfactory/FxFactory-8.0.16-7877.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.9-215-g795d032\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://fxfactory.s3.amazonaws.com/noiseindustries/fxfactory/FxFactory-8.0.16-7877.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.9-215-g795d032\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://fxfactory.s3.amazonaws.com/noiseindustries/fxfactory/FxFactory-8.0.16-7877.zip
Already downloaded: /Users/Yuu/Library/Caches/Homebrew/downloads/e82f9299678482abe077e886d46a24ba71d7c1d7d54d64b4c3f8151867725104--FxFactory-8.0.16-7877.zip
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx14 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/Yuu/Library/Caches/Homebrew/downloads/e82f9299678482abe077e886d46a24ba71d7c1d7d54d64b4c3f8151867725104--FxFactory-8.0.16-7877.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/Yuu/Library/Caches/Homebrew/downloads/e82f9299678482abe077e886d46a24ba71d7c1d7d54d64b4c3f8151867725104--FxFactory-8.0.16-7877.zip
==> /Users/Yuu/Library/Caches/Homebrew/downloads/e82f9299678482abe077e886d46a24ba71d7c1d7d54d64b4c3f8151867725104--FxFactory-8.0.16-7877.zip is quarantined
==> Verifying checksum for 'e82f9299678482abe077e886d46a24ba71d7c1d7d54d64b4c3f8151867725104--FxFactory-8.0.16-7877.zip'
==> Purging files for version 8.0.16,7877 of Cask fxfactory
Error: fxfactory: SHA256 mismatch
Expected: 59967d2ae46570dafa7ab4bf680e068c0b26ec909e70046e2491d61b7dd263b7
  Actual: 1f7b09867d2aa3eebcf3096e57fa38fc5d4fd8fe1e736156211845ebd8af00f1
    File: /Users/Yuu/Library/Caches/Homebrew/downloads/e82f9299678482abe077e886d46a24ba71d7c1d7d54d64b4c3f8151867725104--FxFactory-8.0.16-7877.zip
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:298:in `verify_checksum'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/downloadable.rb:100:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation_2_7.rb:687:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation_2_7.rb:687:in `block in create_validator_procedure_fast1'
/opt/homebrew/Library/Homebrew/cask/download.rb:83:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/download.rb:62:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:193:in `download'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:192:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:260:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:138:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  manymc

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python-markupsafe

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-versions
Untap them with `brew untap`.

---

HOMEBREW_VERSION: 4.3.9-215-g795d032
ORIGIN: https://github.com/Homebrew/brew
HEAD: 795d032dc2a3a63a26697b65da9c4d258b6f1c96
Last commit: 36 minutes ago
Core tap JSON: 15 Jul 00:38 UTC
Core cask tap HEAD: 9fcf9c0dd2c700fe66b14f2025b26bcd5519cd0f
Core cask tap last commit: 83 minutes ago
Core cask tap JSON: 15 Jul 00:38 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/cask
homebrew/cask-versions
```

**Comment by Bo98** [comment]
CI does a `brew fetch` so the sha256 would have been correct at the time the PR was created as CI would have never passed otherwise:

https://github.com/Homebrew/homebrew-cask/actions/runs/9453960601/job/26040475690#step:8:12

So the answer is that upstream issued a new download without bumping the version number here.

> This issue has persisted through multiple versions

Not sure what you mean about this as I checked the previous 5 versions and they were all correct and never changed: 8.0.16-7859, 8.0.16-7858,  8.0.15-7831, 8.0.15-7817 and 8.0.15-7816.

> the various supported paths to issue a PR update are refused due to BrewTestBot's usage

Since upstream has issued a new release without bumping the version, any normal paths won't work here anyway as they typically work via version comparisons. You would need to submit a PR by manually editing the file, assuming you've verified the sha256 change as legitimate and not something malicious.

**Comment by khipp** [comment]
It seems like upstream has a practice of updating their binaries in place after new releases. See [response of the FxFactory support](https://github.com/orgs/Homebrew/discussions/5155#discussioncomment-9905726) in a related discussion.
