### ISSUE TITLE
Auditing New Cask Fails Due to Curl Timeout

### ISSUE THREAD

**Issue by KKaminski93** [Homebrew/homebrew-cask#186473]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Hi, new contributor here. I'm trying to publish a cask for a software called VRoid Studio. When trying to audit my new cask Curl times out on the download. It finds an existing copy of the download and uses that, but then the audit finishes with an error reporting the timeout. I double-checked the URL and tried to use Curl to download the file which seemed to be progressing normally as expected. I also tried re-creating my new cask and appending "-2" to it, but I ran into the same troubles.

### Command that failed

brew audit --new --cask vroid-studio

### Output of command with `--verbose --debug`

```shell
kali  …/homebrew-cask   vroid-studio ?  ♥ 13:06  brew audit --new --cask vroid-studio --verbose --debug
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/bundle clean
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromNameLoader): loading vroid-studio
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromNameLoader): loading vroid-studio
/usr/bin/env XDG_CACHE_HOME=/Users/kali/Library/Caches/Homebrew/style /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby -W1 --disable=gems,rubyopt -- /opt/homebrew/Library/Homebrew/utils/rubocop.rb --format json --force-exclusion --parallel --extra-details --config /opt/homebrew/Library/.rubocop.yml /opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/v/vroid-studio.rb
==> Auditing Cask vroid-studio on os sequoia and arch arm
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/v/vroid-studio.rb
==> Auditing Rosetta 2 requirement
==> Downloading and extracting artifacts
==> Downloading https://download.vroid.com/dist/EYKGmv7H1S/VRoidStudio-v1.29.2-mac.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.24\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.0\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://download.vroid.com/dist/EYKGmv7H1S/VRoidStudio-v1.29.2-mac.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.24\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.0\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://download.vroid.com/dist/EYKGmv7H1S/VRoidStudio-v1.29.2-mac.dmg
Already downloaded: /Users/kali/Library/Caches/Homebrew/downloads/63694e93754218c7b6319a46d90947e96dc0378dcd4445172f6f4b3abb0c868a--VRoidStudio-v1.29.2-mac.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx15 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/kali/Library/Caches/Homebrew/downloads/63694e93754218c7b6319a46d90947e96dc0378dcd4445172f6f4b3abb0c868a--VRoidStudio-v1.29.2-mac.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/kali/Library/Caches/Homebrew/downloads/63694e93754218c7b6319a46d90947e96dc0378dcd4445172f6f4b3abb0c868a--VRoidStudio-v1.29.2-mac.dmg
==> /Users/kali/Library/Caches/Homebrew/downloads/63694e93754218c7b6319a46d90947e96dc0378dcd4445172f6f4b3abb0c868a--VRoidStudio-v1.29.2-mac.dmg is quarantined
==> Verifying checksum for '63694e93754218c7b6319a46d90947e96dc0378dcd4445172f6f4b3abb0c868a--VRoidStudio-v1.29.2-mac.dmg'
/usr/bin/env hdiutil imageinfo -format /Users/kali/Library/Caches/Homebrew/downloads/63694e93754218c7b6319a46d90947e96dc0378dcd4445172f6f4b3abb0c868a--VRoidStudio-v1.29.2-mac.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/homebrew-dmg20240924-18566-9w0b93 /Users/kali/Library/Caches/Homebrew/downloads/63694e93754218c7b6319a46d90947e96dc0378dcd4445172f6f4b3abb0c868a--VRoidStudio-v1.29.2-mac.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20240924-18566-e00u3o.list -- /private/tmp/20240924-18566-j74h8v.bom
/usr/bin/env ditto --bom /private/tmp/20240924-18566-j74h8v.bom -- /private/tmp/homebrew-dmg20240924-18566-9w0b93/dmg.Ge6wx4 /private/tmp/homebrew-unpack20240924-18566-42zhmb
/usr/bin/env diskutil info -plist /private/tmp/homebrew-dmg20240924-18566-9w0b93/dmg.Ge6wx4
/usr/bin/env diskutil eject disk4s1
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240924-18566-42zhmb/VRoidStudio.app/. /private/tmp/cask-audit20240924-18566-kalogl/VRoidStudio.app
/usr/bin/env cp -pR /private/tmp/homebrew-unpack20240924-18566-42zhmb/License.txt /private/tmp/cask-audit20240924-18566-kalogl/License.txt
/usr/bin/env plutil -convert xml1 -o - /private/tmp/cask-audit20240924-18566-kalogl/VRoidStudio.app/Contents/Info.plist
/usr/bin/env lipo -archs /private/tmp/cask-audit20240924-18566-kalogl/VRoidStudio.app/Contents/MacOS/VRoid\ Studio
==> x86_64 arm64

==> Auditing minimum OS version
/usr/bin/env plutil -convert xml1 -o - /private/tmp/cask-audit20240924-18566-kalogl/VRoidStudio.app/Contents/Info.plist
==> Detected minimum OS version: Plist 10.13
==> Declared minimum OS version: high_sierra
==> Auditing GitHub prerelease
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Mozilla/5.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10_15_7\)\ AppleWebKit/605.1.15\ \(KHTML,\ like\ Gecko\)\ Version/17.0\ Safari/605.1.15 --header Accept-Language:\ en --connect-timeout 15 --max-time 25 --retry 3 --retry-max-time 25 --dump-header - --output /private/tmp/20240924-18566-kut959 --location https://vroid.com/en/studio
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.24\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.0\)\ curl/8.7.1 --header Accept-Language:\ en --connect-timeout 15 --max-time 25 --retry 3 --retry-max-time 25 --dump-header - --output /private/tmp/20240924-18566-756osw --location https://download.vroid.com/dist/EYKGmv7H1S/VRoidStudio-v1.29.2-mac.dmg
==> Downloading https://download.vroid.com/dist/EYKGmv7H1S/VRoidStudio-v1.29.2-mac.dmg
Already downloaded: /Users/kali/Library/Caches/Homebrew/downloads/63694e93754218c7b6319a46d90947e96dc0378dcd4445172f6f4b3abb0c868a--VRoidStudio-v1.29.2-mac.dmg
==> Verifying Gatekeeper status of /Users/kali/Library/Caches/Homebrew/downloads/63694e93754218c7b6319a46d90947e96dc0378dcd4445172f6f4b3abb0c868a--VRoidStudio-v1.29.2-mac.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/kali/Library/Caches/Homebrew/downloads/63694e93754218c7b6319a46d90947e96dc0378dcd4445172f6f4b3abb0c868a--VRoidStudio-v1.29.2-mac.dmg
==> /Users/kali/Library/Caches/Homebrew/downloads/63694e93754218c7b6319a46d90947e96dc0378dcd4445172f6f4b3abb0c868a--VRoidStudio-v1.29.2-mac.dmg is quarantined
==> Verifying checksum for '63694e93754218c7b6319a46d90947e96dc0378dcd4445172f6f4b3abb0c868a--VRoidStudio-v1.29.2-mac.dmg'
==> Auditing signing
/usr/bin/env spctl --assess --type execute /private/tmp/cask-audit20240924-18566-kalogl/VRoidStudio.app
==> Auditing pkg stanza: allow_untrusted
==> Auditing stanzas which require an uninstall
==> Auditing preflight and postflight stanzas
==> Auditing single uninstall_* and zap stanzas
==> Auditing required stanzas
==> Auditing version :latest does not appear as a string ('latest')
==> Auditing sha256 :no_check with version :latest
==> Auditing sha256 string is a legal SHA-256 digest
==> Auditing sha256 is not a known invalid value
==> curl: (28) Operation timed out after 15005 milliseconds with 0 out of 709262722 bytes received
/opt/homebrew/Library/Homebrew/utils/curl.rb:166:in `curl_with_workarounds'
/opt/homebrew/Library/Homebrew/utils/curl.rb:233:in `curl_output'
/opt/homebrew/Library/Homebrew/utils/curl.rb:238:in `block in curl_headers'
/opt/homebrew/Library/Homebrew/utils/curl.rb:237:in `each'
/opt/homebrew/Library/Homebrew/utils/curl.rb:237:in `curl_headers'
/opt/homebrew/Library/Homebrew/livecheck/strategy.rb:182:in `block in page_headers'
/opt/homebrew/Library/Homebrew/livecheck/strategy.rb:180:in `each'
/opt/homebrew/Library/Homebrew/livecheck/strategy.rb:180:in `page_headers'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/livecheck/strategy/header_match.rb:84:in `find_versions'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/livecheck/livecheck.rb:771:in `block in latest_version'
/opt/homebrew/Library/Homebrew/livecheck/livecheck.rb:707:in `each'
/opt/homebrew/Library/Homebrew/livecheck/livecheck.rb:707:in `each_with_index'
/opt/homebrew/Library/Homebrew/livecheck/livecheck.rb:707:in `latest_version'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/audit.rb:639:in `audit_livecheck_version'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/audit.rb:297:in `audit_hosting_with_livecheck'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/audit.rb:67:in `block in run!'
/opt/homebrew/Library/Homebrew/cask/audit.rb:62:in `each'
/opt/homebrew/Library/Homebrew/cask/audit.rb:62:in `run!'
/opt/homebrew/Library/Homebrew/cask/auditor.rb:108:in `audit_cask_instance'
/opt/homebrew/Library/Homebrew/cask/auditor.rb:67:in `audit'
/opt/homebrew/Library/Homebrew/cask/auditor.rb:10:in `audit'
/opt/homebrew/Library/Homebrew/dev-cmd/audit.rb:249:in `block (3 levels) in run'
/opt/homebrew/Library/Homebrew/simulate_system.rb:29:in `with'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/dev-cmd/audit.rb:246:in `block (2 levels) in run'
/opt/homebrew/Library/Homebrew/dev-cmd/audit.rb:243:in `each'
/opt/homebrew/Library/Homebrew/dev-cmd/audit.rb:243:in `flat_map'
/opt/homebrew/Library/Homebrew/dev-cmd/audit.rb:243:in `block in run'
/opt/homebrew/Library/Homebrew/dev-cmd/audit.rb:240:in `each'
/opt/homebrew/Library/Homebrew/dev-cmd/audit.rb:240:in `each_with_object'
/opt/homebrew/Library/Homebrew/dev-cmd/audit.rb:240:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
audit for vroid-studio: failed
 - exception while auditing vroid-studio: curl: (28) Operation timed out after 15005 milliseconds with 0 out of 709262722 bytes received
vroid-studio
  * exception while auditing vroid-studio: curl: (28) Operation timed out after 15005 milliseconds with 0 out of 709262722 bytes received
Error: 1 problem in 1 cask detected.
```

### Output of `brew doctor` and `brew config`

```shell
kali  …/homebrew-cask   vroid-studio ?  ♥ 13:06  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have uncommitted modifications to Homebrew/homebrew-cask.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /opt/homebrew/Library/Taps/homebrew/homebrew-cask && git stash -u && git clean -d -f

Uncommitted files:
  ?? Casks/v/vroid-studio-2.rb

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/cask) checkout master

kali  …/homebrew-cask   vroid-studio ?  ♥ 13:07  brew audit
Error: Calling brew audit is disabled! Use brew audit --eval-all or HOMEBREW_EVAL_ALL instead.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### Output of `brew tap`

```shell
kali  …/homebrew-cask   vroid-studio ?  ♥ 13:08  brew tap
homebrew/cask
homebrew/core
```

**Comment by daeho-ro** [comment]
What is the download url? Maybe they reject any request without some header?

**Comment by bevanjkay** [comment]
Can you open a PR with your cask?
Even if it is still a WIP, it will help with some additional context.
