### ISSUE TITLE
OnyX package not upgrading from 4.6.2 to 4.7.0

### ISSUE THREAD

**Issue by vikingnope** [Homebrew/homebrew-cask#186784]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

First I tried updating the package from 4.6.2 to 4.7.0 and it did not work with the following error: `onyx: No such file or directory @ rb_file_s_rename - (/opt/homebrew/Caskroom/onyx/4.7.0, /opt/homebrew/Caskroom/onyx/4.7.0.upgrading)`. After I tried uninstalling the old version and installing the new one without the --force command and this is the error I get: `Error: onyx: It seems the App source '/Applications/OnyX.app' is not there.`. When running the --force command on the install I get the same error that was happening during the upgrade.

### Command that failed

brew install onyx --force

### Output of command with `--verbose --debug`

```shell
╰─ brew install onyx --verbose --debug                                       ─╯
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading onyx
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading onyx
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading onyx
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/onyx/.metadata/4.6.2/20240925193959.035/Casks/onyx.json
onyx 4.7.0 -> 4.7.0
==> Started upgrade process for Cask onyx
==> Upgrading onyx
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://www.titanium-software.fr/download/15/OnyX.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.24-95-g7b1e2d3\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.0\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://www.titanium-software.fr/download/15/OnyX.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.24-95-g7b1e2d3\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.0\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://www.titanium-software.fr/download/15/OnyX.dmg
Already downloaded: /Users/aidenschembri/Library/Caches/Homebrew/downloads/3d62d2c2404a4eae7270140a6a1850074c6b5d808971c13e8324542a1994ace8--OnyX.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -target arm64-apple-macosx15 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/aidenschembri/Library/Caches/Homebrew/downloads/3d62d2c2404a4eae7270140a6a1850074c6b5d808971c13e8324542a1994ace8--OnyX.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/aidenschembri/Library/Caches/Homebrew/downloads/3d62d2c2404a4eae7270140a6a1850074c6b5d808971c13e8324542a1994ace8--OnyX.dmg
==> /Users/aidenschembri/Library/Caches/Homebrew/downloads/3d62d2c2404a4eae7270140a6a1850074c6b5d808971c13e8324542a1994ace8--OnyX.dmg is quarantined
Warning: No checksum defined for cask 'onyx', skipping verification.
/usr/bin/env hdiutil imageinfo -format /Users/aidenschembri/Library/Caches/Homebrew/downloads/3d62d2c2404a4eae7270140a6a1850074c6b5d808971c13e8324542a1994ace8--OnyX.dmg
==> Uninstalling artifacts
==> 2 artifacts defined
#<Cask::ArtifactSet: {#<Cask::Artifact::App:0x0000000150819470 @cask=#<Cask onyx /opt/homebrew/Caskroom/onyx/.metadata/4.6.2/20240925193959.035/Casks/onyx.json>, @dsl_args=["OnyX.app"], @source_string="OnyX.app", @target_string="">, #<Cask::Artifact::Zap:0x000000013fff04e8 @cask=#<Cask onyx /opt/homebrew/Caskroom/onyx/.metadata/4.6.2/20240925193959.035/Casks/onyx.json>, @dsl_args=[{:trash=>["~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/com.titanium.OnyX.help*", "~/Library/Logs/OnyX.log", "~/Library/Preferences/com.titanium.OnyX.plist", "~/Library/Preferences/OnyX.plist", "~/Library/Saved Application State/com.titanium.OnyX.savedState"]}], @directives={:trash=>["~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/com.titanium.OnyX.help*", "~/Library/Logs/OnyX.log", "~/Library/Preferences/com.titanium.OnyX.plist", "~/Library/Preferences/OnyX.plist", "~/Library/Saved Application State/com.titanium.OnyX.savedState"], :signal=>[]}>}>
==> Uninstalling artifact of class Cask::Artifact::App
==> Purging files for version 4.7.0 of Cask onyx
Error: onyx: It seems the App source '/Applications/OnyX.app' is not there.
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:160:in `move_back'
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:21:in `uninstall_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:490:in `block in uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:487:in `uninstall_artifacts'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:446:in `start_upgrade'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:199:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:117:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:116:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:116:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/install.rb:251:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11582/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

brew doctor:

``` shell

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  fig

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  neofetch

Warning: You have uncommitted modifications to Homebrew/brew.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /opt/homebrew && git stash -u && git clean -d -f

Uncommitted files:
  ?? Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/unf-0.1.4/LICENSE
  ?? Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/unf-0.1.4/lib/unf.rb
  ?? Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/unf-0.1.4/lib/unf/normalizer.rb
  ?? Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/unf-0.1.4/lib/unf/normalizer_cruby.rb
  ?? Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/unf-0.1.4/lib/unf/normalizer_jruby.rb
  ?? Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/unf-0.1.4/lib/unf/version.rb
  ?? Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/unf_ext-0.0.9.1/LICENSE.txt
  ?? Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/unf_ext-0.0.9.1/lib/unf_ext.rb
  ?? Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/unf_ext-0.0.9.1/lib/unf_ext/version.rb

Warning: Your Xcode (15.4) at /Applications/Xcode.app is too outdated.
Please update to Xcode 16.0 (or delete it).
Xcode can be updated from the App Store.
```

brew config:

``` shell
╰─ brew config                                                                                                   ─╯
HOMEBREW_VERSION: 4.3.24-95-g7b1e2d3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7b1e2d377715a67ff8f1f31029c45f4b9a663d1f
Last commit: 40 minutes ago
Core tap HEAD: a454b7bb52040bcd38e43c365f88b8ea600c926b
Core tap last commit: 14 minutes ago
Core tap JSON: 27 Sep 07:06 UTC
Core cask tap HEAD: fe610b5514427a3dfe69ec18296fec0bac72550c
Core cask tap last commit: 12 minutes ago
Core cask tap JSON: 27 Sep 07:06 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.46.2 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: 15.4
Rosetta 2: false
```

### Output of `brew tap`

```shell
╰─ brew tap                                                                                                      ─╯
homebrew/cask
homebrew/core
homebrew/services
oven-sh/bun
russellbanks/tap
```

**Comment by daeho-ro** [comment]
Try with force option.
```
brew install --force onyx
```

**Comment by jfallon1997** [comment]
You can do a manual workaround. (Someone with brew packaging knowledge might be quite easily able to identify the proper fix based on these steps?!)

To install onyx, first run
1. `brew install onyx`.   

allowing it to fail with error message above from @vikingnope 

Next, install onyx to the applications folder using the now downloaded `dmg`.
2. Open the dmg file from the brew output dialogue: `Already downloaded: /Users/$USER/Library/Caches/Homebrew/downloads/3d62d2c2404a4eae7270140a6a1850074c6b5d808971c13e8324542a1994ace8--OnyX.dmg`
3. drag and drop the onyx app into applications.

You can now use onyx as it is fully installed.

However, to let brew know that onyx has been installed you may wish to insert a metadata entry:

`cp -r /usr/local/Caskroom/onyx/.metadata/4.6.2 /usr/local/Caskroom/onyx/.metadata/4.7.0`

Here I have copied the previous install's metadata, but you could alternatively download the metadata json file and place in `/usr/local/Caskroom/onyx/.metadata/4.7.0/20240930000000.001/Casks/onyx.json`

**Comment by vikingnope** [comment]
> Try with force option.
> 
> ```
> brew install --force onyx
> ```

![image](https://github.com/user-attachments/assets/40794796-9a88-44dc-b623-f6127110217f)

**Comment by Rylan12** [comment]
Can you post the output of `cat "$(brew --caskroom)/onyx/.metadata/INSTALL_RECEIPT.json"`?

It seems like Homebrew might think that you have an existing (outdated?) install of Onyx, and so it's trying to upgrade and failing to uninstall the old version (because you don't have an `/Applications/Onyx.app` file.

I'd recommend trying to `brew uninstall --force --cask onyx`. If that doesn't work, try manually deleting the `/opt/homebrew/Caskroom/onyx` directory and trying again

**Comment by vikingnope** [comment]
The `brew uninstall --force --cask onyx` worked and seems to have fully uninstalled and allowed me to install the program
