### ISSUE TITLE
Checksum mismatch on `font-geist`/`-mono` & Formula not found error on `brew test font-geist`/`-mono`

### ISSUE THREAD

**Issue by emonadeo** [Homebrew/homebrew-cask#187556]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Yes, this _is_ a checksum does not match / SHA256 mismatch error, and I tried opening a PR, but when I run `brew test font-geist-mono` I for some reason get `Error: No available formula with the name "font-geist-mono"` and even after running through all the steps I still get this error, so someone else has to do the PR. (Likewise with `font-geist`)

The assets linked in the [1.4.0 Release on vercel/geist-font](https://github.com/vercel/geist-font/releases/tag/1.4.0) (`Geist-v1.4.0.zip` and `GeistMono-v1.4.0.zip`) are marked as uploaded **2 days ago**.

However [`Casks/font/font-g/font-geist.rb`](https://github.com/Homebrew/homebrew-cask/blob/bf41222ce52f73b24e85fc888e74bb7e7a8b58a2/Casks/font/font-g/font-geist.rb) and [`Casks/font/font-g/font-geist-mono.rb`](https://github.com/Homebrew/homebrew-cask/blob/bf41222ce52f73b24e85fc888e74bb7e7a8b58a2/Casks/font/font-g/font-geist-mono.rb) have not seen changes in the **last 4 days**.

I conclude that the assets on vercel/geist-font must have been changed after the fact, resulting in the checksum mismatch.

The new hashes I evaluated are:
`font-geist`: `fafb2a4ce068d293bd53c29cef517597cef6437dc5f6eb5ecca8bc40337ec179`
`font-geist-mono`: `70423ceba8d5f768a9a9a9cb56c449a5307d20679d951113acdf38d7107a548b`

If someone could double-check if they get the same hashes and create a PR, that'd be great 🙏

### Command that failed

brew test font-geist-mono

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/bundle clean
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading font-geist-mono
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading font-geist-mono
Error: No available formula with the name "font-geist-mono".
/opt/homebrew/Library/Homebrew/formulary.rb:898:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:1016:in `factory'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/formulary.rb:499:in `resolve'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:261:in `resolve_formula'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:141:in `block in load_formula_or_cask'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:536:in `with_env'
/opt/homebrew/Library/Homebrew/api.rb:198:in `with_no_api_env'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/api.rb:205:in `with_no_api_env_if_needed'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:131:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:74:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:72:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:72:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:72:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:267:in `to_resolved_formulae'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/dev-cmd/test.rb:40:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11595/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Warning: Found Ruby file outside surrealdb/tap tap formula directory.
(/opt/homebrew/Library/Taps/surrealdb/homebrew-tap/Formula):
  /opt/homebrew/Library/Taps/surrealdb/homebrew-tap/nightly.rb
  /opt/homebrew/Library/Taps/surrealdb/homebrew-tap/release.rb

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python-packaging

HOMEBREW_VERSION: 4.4.0-66-g1e29665
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1e29665e62cda74becc8a82eccde038eba82520b
Last commit: 13 hours ago
Core tap HEAD: 860b927f9339549d76c3fe987800ee6bb54223d4
Core tap last commit: 45 minutes ago
Core tap JSON: 05 Oct 02:55 UTC
Core cask tap HEAD: bf41222ce52f73b24e85fc888e74bb7e7a8b58a2
Core cask tap last commit: 62 minutes ago
Core cask tap JSON: 05 Oct 02:55 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.46.2 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: 16.0
Rosetta 2: false
```

### Output of `brew tap`

```shell
apple/apple
ariga/tap
austinliuigi/brew-neovim-nightly
go-swagger/go-swagger
graalvm/tap
hashicorp/tap
homebrew-ffmpeg/ffmpeg
homebrew/cask
homebrew/core
homebrew/services
koekeishiya/formulae
oven-sh/bun
sergiobenitez/osxct
surrealdb/tap
zegervdv/zathura
```

**Comment by daeho-ro** [comment]
Here it is.
- https://github.com/Homebrew/homebrew-cask/pull/187562

**Comment by reitermarkus** [comment]
Thanks!
