### ISSUE TITLE
[macOS] Fonts cannot be removed after renaming the home folder.

### ISSUE THREAD

**Issue by Sugiton** [Homebrew/homebrew-cask#189846]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

I renamed my home folder following official guidance from Apple ([Change the name of your macOS user account and home folder](https://support.apple.com/en-us/102547)).

Thereafter, I could install new packages, upgrade formulas, but the upgrade of font casks failed with:
- `"It seems the Font source '... path using the previous home folder name ...' is not there.`

Consequently, the removal of font casks also proves unsuccessful due to the same underlying issue.

Employing the `--zap` stanza triggers the error message (`brew uninstall --zap font-sudo`): 
- `'It seems the Font source '... path using the previous home folder name ...' is not there.`

Interestingly, using the `--cask` flag (`brew uninstall --cask font-sudo`) yields a successful return despite the files remaining intact.

### Command that failed

brew uninstall --zap font-sudo

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading font-sudo
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading font-sudo
==> Zapping Cask font-sudo
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/font-sudo/.metadata/2.0.0/20241004120515.810/Casks/font-sudo.json
==> Implied `brew uninstall --cask font-sudo`
==> Uninstalling artifacts
==> 2 artifacts defined
#<Cask::ArtifactSet: {#<Cask::Artifact::Font:0x000000014c8d3450 @cask=#<Cask font-sudo /opt/homebrew/Caskroom/font-sudo/.metadata/2.0.0/20241004120515.810/Casks/font-sudo.json>, @dsl_args=["sudo/SudoUIVariable.ttf"], @source_string="sudo/SudoUIVariable.ttf", @target_string="">, #<Cask::Artifact::Font:0x000000014c8d3220 @cask=#<Cask font-sudo /opt/homebrew/Caskroom/font-sudo/.metadata/2.0.0/20241004120515.810/Casks/font-sudo.json>, @dsl_args=["sudo/SudoVariable.ttf"], @source_string="sudo/SudoVariable.ttf", @target_string="">}>
==> Uninstalling artifact of class Cask::Artifact::Font
Error: It seems the Font source '/Users/Saito/Library/Fonts/SudoUIVariable.ttf' is not there.
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:160:in `move_back'
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:21:in `uninstall_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:491:in `block in uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:488:in `uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:518:in `zap'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:70:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:65:in `each'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:65:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  font-ibm-plex
```

```
HOMEBREW_VERSION: 4.4.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35ebf4a047b00b2b3de33ba0081d71293cdadede
Last commit: 6 days ago
Core tap JSON: 26 Oct 12:43 UTC
Core cask tap JSON: 26 Oct 12:43 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0.1-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: 16.0
Rosetta 2: false
```
```


### Output of `brew tap`

```shell
homebrew/services
```

**Comment by SMillerDev** [comment]
Can you run `brew uninstall --force`?

**Comment by Sugiton** [comment]
To clarify, `brew uninstall --cask font-...` returns a success, but the font files aren't deleted. It only removes the font from the list of the `brew list` command. Then I need to remove the font files manually from the user fonts path `~/Library/Fonts/`.

brew fails to find, update and remove those font files (which are .ttf or .otf) because instead of a relative path, it stores an absolute path at the font installation (like `/Users/username/Library/Fonts/` but the username can change, which ends with either an error (with `update` or `--zap`) or a fake success (the files not being deleted).

Although it's easy to circumvent by deleting the font files manually, it still needs a fix so the command `brew uninstall --cask font-...` would not wrongly return success for the removal of the fonts.
