### ISSUE TITLE
mullvadvpn cask started giving Error: unexpected token at '{.....

### ISSUE THREAD

**Issue by conana** [Homebrew/homebrew-cask#190052]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

For the last few months (not sure since what date) mullvadvpn cannot being maintained. Both `brew upgrade mullvadvpn` and `brew uninstall mullvadvpn` give the same error. Adding `--force` doesn't help. I'm not sure where to look/poke next.

Full error output:

```sh
➜  ~ brew uninstall --force mullvadvpn
Error: unexpected token at '{
  "full_token": "mullvadvpn",
  "old_tokens": [

  ],
  "tap": "homebrew/cask",
  "name": [
    "Mullvad VPN"
  ],
  "desc": "VPN client",
  "homepage": "https://mullvad.net/",
  "url": "https://github.com/mullvad/mullvadvpn-app/releases/download/#{version}/MullvadVPN-#{version}.pkg",
  "url_specs": {
    "verified": "github.com/mullvad/mullvadvpn-app/"
  },
  # URL of the signature file
  gpg_signature_url = "https://example.com/example-cask-#{version}.dmg.sig"

  "version": "2024.4",
  "installed": null,
  "installed_time": null,
  "bundle_version": null,
  "bundle_short_version": null,
  "outdated": false,
  "sha256": "9b5c2efdf0aa8bad96ef8f2942345b774917e99a1d6a5f760da3907a8b8c5a09",
  "artifacts": [
    {
      "uninstall": [
        {
          "launchctl": "net.mullvad.daemon",
          "pkgutil": "net.mullvad.vpn",
          "delete": [
            "/Library/Caches/mullvad-vpn",
            "/Library/LaunchDaemons/net.mullvad.daemon.plist",
            "/opt/homebrew/share/fish/vendor_completions.d/mullvad.fish",
            "/usr/local/share/fish/vendor_completions.d/mullvad.fish",
            "/usr/local/share/zsh/site-functions/_mullvad",
            "/var/log/mullvad-vpn"
          ]
        }
      ]
    },
    {
      "pkg": [
        "MullvadVPN-2024.4.pkg"
      ]
    },
    {
      "zap": [
        {
          "trash": [
            "/etc/mullvad-vpn",
            "~/Library/Application Support/Mullvad VPN",
            "~/Library/Logs/Mullvad VPN",
            "~/Library/Preferences/net.mullvad.vpn.plist"
          ]
        }
      ]
    }
  ],
  "caveats": null,
  "depends_on": {
    "macos": {
      ">=": [
        "11"
      ]
    }
  },
  "conflicts_with": {
    "cask": [
      "mullvadvpn@beta"
    ]
  },
  "container": null,
  "auto_updates": null,
  "deprecated": false,
  "deprecation_date": null,
  "deprecation_reason": null,
  "disabled": false,
  "disable_date": null,
  "disable_reason": null,
  "tap_git_head": "45b5a534f0f370840e84f42da9b97817fd78dbf2",
  "languages": [

  ],
  "ruby_source_path": "Casks/m/mullvadvpn.rb",
  "ruby_source_checksum": {
    "sha256": "4f62480f3af60a5179bf55823324abc47c1c53901c52ff131f766d2040ac22c2"
  },
  "variations": {
  }
}'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/json/common.rb:219:in `parse'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/json/common.rb:219:in `parse'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:139:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:637:in `load_from_installed_caskfile'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:192:in `block in load_formula_or_cask'
/opt/homebrew/Library/Homebrew/api.rb:203:in `with_no_api_env_if_needed'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:131:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:74:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:72:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:72:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:72:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:377:in `to_kegs_to_casks'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:44:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### Command that failed

brew uninstall --force mullvadvpn

### Output of command with `--verbose --debug`

```shell
➜  ~ brew uninstall --verbose --debug mullvadvpn
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading mullvadvpn
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading mullvadvpn
Error: unexpected token at '{
  "full_token": "mullvadvpn",
  "old_tokens": [

  ],
  "tap": "homebrew/cask",
  "name": [
    "Mullvad VPN"
  ],
  "desc": "VPN client",
  "homepage": "https://mullvad.net/",
  "url": "https://github.com/mullvad/mullvadvpn-app/releases/download/#{version}/MullvadVPN-#{version}.pkg",
  "url_specs": {
    "verified": "github.com/mullvad/mullvadvpn-app/"
  },
  # URL of the signature file
  gpg_signature_url = "https://example.com/example-cask-#{version}.dmg.sig"

  "version": "2024.4",
  "installed": null,
  "installed_time": null,
  "bundle_version": null,
  "bundle_short_version": null,
  "outdated": false,
  "sha256": "9b5c2efdf0aa8bad96ef8f2942345b774917e99a1d6a5f760da3907a8b8c5a09",
  "artifacts": [
    {
      "uninstall": [
        {
          "launchctl": "net.mullvad.daemon",
          "pkgutil": "net.mullvad.vpn",
          "delete": [
            "/Library/Caches/mullvad-vpn",
            "/Library/LaunchDaemons/net.mullvad.daemon.plist",
            "/opt/homebrew/share/fish/vendor_completions.d/mullvad.fish",
            "/usr/local/share/fish/vendor_completions.d/mullvad.fish",
            "/usr/local/share/zsh/site-functions/_mullvad",
            "/var/log/mullvad-vpn"
          ]
        }
      ]
    },
    {
      "pkg": [
        "MullvadVPN-2024.4.pkg"
      ]
    },
    {
      "zap": [
        {
          "trash": [
            "/etc/mullvad-vpn",
            "~/Library/Application Support/Mullvad VPN",
            "~/Library/Logs/Mullvad VPN",
            "~/Library/Preferences/net.mullvad.vpn.plist"
          ]
        }
      ]
    }
  ],
  "caveats": null,
  "depends_on": {
    "macos": {
      ">=": [
        "11"
      ]
    }
  },
  "conflicts_with": {
    "cask": [
      "mullvadvpn@beta"
    ]
  },
  "container": null,
  "auto_updates": null,
  "deprecated": false,
  "deprecation_date": null,
  "deprecation_reason": null,
  "disabled": false,
  "disable_date": null,
  "disable_reason": null,
  "tap_git_head": "45b5a534f0f370840e84f42da9b97817fd78dbf2",
  "languages": [

  ],
  "ruby_source_path": "Casks/m/mullvadvpn.rb",
  "ruby_source_checksum": {
    "sha256": "4f62480f3af60a5179bf55823324abc47c1c53901c52ff131f766d2040ac22c2"
  },
  "variations": {
  }
}'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/json/common.rb:219:in `parse'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/json/common.rb:219:in `parse'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:139:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:637:in `load_from_installed_caskfile'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:192:in `block in load_formula_or_cask'
/opt/homebrew/Library/Homebrew/api.rb:203:in `with_no_api_env_if_needed'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:131:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:74:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:72:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:72:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:72:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:377:in `to_kegs_to_casks'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:44:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### Output of `brew doctor` and `brew config`

```shell
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  microsoft-remote-desktop
  mono-mdk-for-visual-studio
  pycharm-ce-with-anaconda-plugin


➜  ~ brew config
HOMEBREW_VERSION: 4.4.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91f3671b16fe62121364c465c14e0dfd088d7ead
Last commit: 26 hours ago
Core tap JSON: 28 Oct 18:19 UTC
Core cask tap JSON: 28 Oct 18:19 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.47.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.7-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: 16.0
Rosetta 2: false
```

### Output of `brew tap`

```shell
➜  ~ brew tap
bakks/bakks
```

**Comment by conana** [comment]
You are correct. It is a relic from local experimentation months ago. Thank you for highlighting this.
🤦‍♂️
