### ISSUE TITLE
ia-markdown-dictionary has incorrect checksum

### ISSUE THREAD

**Issue by nc-z** [Homebrew/homebrew-cask#192604]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

The package ia-markdown-dictionary won't install, because it expects the download to have a checksum of 'd1cddfd0f0e727e8a21e693759a105ead75a1341c8e3d024a370248021565a38'; the download seemingly has a checksum now of '723746bae20f5e5d3991a64514a25502ad31c166bbe7bde19046ad68dca66eb0'.

I tried to run  brew bump --open-pr ia-markdown-dictionary but I'm having trouble; first it complained that the package wasn't installed, and now it claims 'Error: No available formula with the name "ia-markdown-dictionary".'

### Command that failed

brew install --force ia-markdown-dictionary 

### Output of command with `--verbose --debug`

```shell
$ brew install --force --verbose --debug ia-markdown-dictionary 
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading ia-markdown-dictionary
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading ia-markdown-dictionary
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading ia-markdown-dictionary
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://files.ia.net/tips/iA-Markdown-1.0.dictionary.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.6\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 -V
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.6\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://files.ia.net/tips/iA-Markdown-1.0.dictionary.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.6\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET --http1.1 https://files.ia.net/tips/iA-Markdown-1.0.dictionary.zip
Already downloaded: /Users/kevin/Library/Caches/Homebrew/downloads/a58ee1926ddd9be78dfd9a82d20a0e4cca844a599b8f291cd4e77b07b012914a--iA-Markdown-1.0.dictionary.zip
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx15 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/kevin/Library/Caches/Homebrew/downloads/a58ee1926ddd9be78dfd9a82d20a0e4cca844a599b8f291cd4e77b07b012914a--iA-Markdown-1.0.dictionary.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/kevin/Library/Caches/Homebrew/downloads/a58ee1926ddd9be78dfd9a82d20a0e4cca844a599b8f291cd4e77b07b012914a--iA-Markdown-1.0.dictionary.zip
==> /Users/kevin/Library/Caches/Homebrew/downloads/a58ee1926ddd9be78dfd9a82d20a0e4cca844a599b8f291cd4e77b07b012914a--iA-Markdown-1.0.dictionary.zip is quarantined
==> Verifying checksum for 'a58ee1926ddd9be78dfd9a82d20a0e4cca844a599b8f291cd4e77b07b012914a--iA-Markdown-1.0.dictionary.zip'
Error: SHA256 mismatch
Expected: d1cddfd0f0e727e8a21e693759a105ead75a1341c8e3d024a370248021565a38
  Actual: 723746bae20f5e5d3991a64514a25502ad31c166bbe7bde19046ad68dca66eb0
    File: /Users/kevin/Library/Caches/Homebrew/downloads/a58ee1926ddd9be78dfd9a82d20a0e4cca844a599b8f291cd4e77b07b012914a--iA-Markdown-1.0.dictionary.zip
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:302:in `verify_checksum'
/opt/homebrew/Library/Homebrew/downloadable.rb:117:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:90:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:69:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:193:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:74:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:104:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:245:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:234:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:234:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor           
Your system is ready to brew.
$ brew config                                 
HOMEBREW_VERSION: 4.4.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: cc0b5d6d05d1f3af5b2f53e9fbb1e7bfa0c332ab
Last commit: 2 days ago
Core tap JSON: 19 Nov 15:36 UTC
Core cask tap JSON: 19 Nov 15:36 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: octa-core 64-bit arm_ibiza
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
$ brew tap   
$
```

**Comment by SMillerDev** [comment]
You checked:
> I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

But the text indicates that you did not
