### ISSUE TITLE
Problems with font-iosevka-comfy after upgrade

### ISSUE THREAD

**Issue by kevin-stuart** [Homebrew/homebrew-cask#195660]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

It seems `brew upgrade --cask --greedy` was a bad idea. The font font-iosevka-comfy seems to be broken. It says that the font cannot be found, and indeed, the directory /opt/homebrew/Caskroom/font-iosevka-comfy/latest/ is empty. How can I repair this?

### Command that failed

brew install --cask font-iosevka-comfy

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading font-iosevka-comfy
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env git --git-dir /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/.git status -s
==> Cloning https://github.com/protesilaos/iosevka-comfy.git
/usr/bin/env git config remote.origin.url https://github.com/protesilaos/iosevka-comfy.git
Updating /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git
/usr/bin/env git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
/usr/bin/env git config remote.origin.tagOpt --no-tags
/usr/bin/env git config advice.detachedHead false
/usr/bin/env git config core.fsmonitor false
/usr/bin/env git fetch origin
/usr/bin/env git checkout -f master --
==> Checking out branch master
Already on 'master'
/usr/bin/env git reset --hard origin/master --
Your branch is up to date with 'origin/master'.
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
HEAD is now at 4f7e6f1 Merge pull request #21 from nsemrau/master
/usr/bin/env /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -target arm64-apple-macosx15 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git
==> /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git is quarantined
Warning: No checksum defined for cask 'font-iosevka-comfy', skipping verification.
/usr/bin/env hdiutil imageinfo -format /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Git for /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git
/usr/bin/env cp -pR /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/LICENSE.md /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/iosevka-comfy-motion /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/iosevka-comfy-wide-duo /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/iosevka-comfy-wide-motion-duo /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/iosevka-comfy-motion-fixed /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/iosevka-comfy-duo /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/iosevka-comfy-fixed /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/iosevka-comfy /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/iosevka-comfy-wide /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/iosevka-comfy-wide-fixed /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/iosevka-comfy-motion-duo /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/iosevka-comfy-wide-motion /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/README.md /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/private-build-plans.toml /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/.gitattributes /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/iosevka-comfy-wide-motion-fixed /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git/.git /private/tmp/homebrew-unpack-20241218-83799-tx5xm3
==> Installing Cask font-iosevka-comfy
==> Verifying Gatekeeper status of /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/.git /opt/homebrew/Caskroom/font-iosevka-comfy/latest/.git
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/.gitattributes /opt/homebrew/Caskroom/font-iosevka-comfy/latest/.gitattributes
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/LICENSE.md /opt/homebrew/Caskroom/font-iosevka-comfy/latest/LICENSE.md
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/README.md /opt/homebrew/Caskroom/font-iosevka-comfy/latest/README.md
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/iosevka-comfy /opt/homebrew/Caskroom/font-iosevka-comfy/latest/iosevka-comfy
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/iosevka-comfy-duo /opt/homebrew/Caskroom/font-iosevka-comfy/latest/iosevka-comfy-duo
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/iosevka-comfy-fixed /opt/homebrew/Caskroom/font-iosevka-comfy/latest/iosevka-comfy-fixed
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/iosevka-comfy-motion /opt/homebrew/Caskroom/font-iosevka-comfy/latest/iosevka-comfy-motion
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/iosevka-comfy-motion-duo /opt/homebrew/Caskroom/font-iosevka-comfy/latest/iosevka-comfy-motion-duo
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/iosevka-comfy-motion-fixed /opt/homebrew/Caskroom/font-iosevka-comfy/latest/iosevka-comfy-motion-fixed
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/iosevka-comfy-wide /opt/homebrew/Caskroom/font-iosevka-comfy/latest/iosevka-comfy-wide
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/iosevka-comfy-wide-duo /opt/homebrew/Caskroom/font-iosevka-comfy/latest/iosevka-comfy-wide-duo
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/iosevka-comfy-wide-fixed /opt/homebrew/Caskroom/font-iosevka-comfy/latest/iosevka-comfy-wide-fixed
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/iosevka-comfy-wide-motion /opt/homebrew/Caskroom/font-iosevka-comfy/latest/iosevka-comfy-wide-motion
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/iosevka-comfy-wide-motion-duo /opt/homebrew/Caskroom/font-iosevka-comfy/latest/iosevka-comfy-wide-motion-duo
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/iosevka-comfy-wide-motion-fixed /opt/homebrew/Caskroom/font-iosevka-comfy/latest/iosevka-comfy-wide-motion-fixed
mv /private/tmp/homebrew-unpack-20241218-83799-tx5xm3/private-build-plans.toml /opt/homebrew/Caskroom/font-iosevka-comfy/latest/private-build-plans.toml
==> /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git is quarantined
==> Propagating quarantine from /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git to /opt/homebrew/Caskroom/font-iosevka-comfy/latest
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/user1/Library/Caches/Homebrew/Cask/font-iosevka-comfy--git
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;675f4763\;Homebrew\\x20Cask\;AD506841-9693-4513-BBA1-938956777A90
==> Creating metadata directory: /opt/homebrew/Caskroom/font-iosevka-comfy/.metadata/latest/20241218144258.347
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/font-iosevka-comfy/.metadata/latest/20241218144258.347/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Font
Error: It seems the Font source '/opt/homebrew/Caskroom/font-iosevka-comfy/latest/iosevka-comfy-motion/ttf/iosevka-comfy-motion-extrabolditalic.ttf' is not there.
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:37:in `move'
/opt/homebrew/Library/Homebrew/cask/artifact/moved.rb:17:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:255:in `block in install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:10:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:248:in `install_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:115:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:245:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:234:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:234:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
==> Purging files for version latest of Cask font-iosevka-comfy
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.
```

### Output of `brew tap`

```shell
artginzburg/tap
blacktop/tap
buo/cask-upgrade
coursier/formulas
dahlia/priv
fabianishere/personal
grishka/grishka
gromgit/fuse
homebrew/bundle
homebrew/services
isen-ng/dotnet-sdk-versions
jakehilborn/jakehilborn
marcuzzz/marcstap
oven-sh/bun
prbinu/touch2sudo
```

**Comment by kevin-stuart** [comment]
This sounds great. One thought though: Why is it not an option to uninstall and reinstall? Why does it fail when the cask was removed? What remains? I would really like to understand how my system could be "corrupted"?

**Comment by khipp** [comment]
This is a general issue. All installations or upgrades are failing because the repository's folder structure changed with [the release of version 2.0.0](https://github.com/protesilaos/iosevka-comfy/releases/tag/2.0.0). `version :latest` will simply download a current snapshot of the repository and install the fonts from the extracted archive. However, since the paths listed in the cask are based on an older release, they can no longer be resolved, causing the installation error you are seeing.

**Comment by kevin-stuart** [comment]
Oh. So it's not just my machine where it is broken, but it is broken for everyone if I understand you correctily. Thanks for the explanation.
