### ISSUE TITLE
Wrong sha256 in macs-fan-control

### ISSUE THREAD

**Issue by sukvvon** [Homebrew/homebrew-cask#195617]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

wrong sha256 in macs-fan-control

<img width="968" alt="image" src="https://github.com/user-attachments/assets/87a11a8f-e733-45cd-a9b5-4521b9648b8e" />

the right is `db659ef42c2553616817a3d92e61aaee6f20d18df98caba9d9fba73b26c1f9cf`

### Command that failed

brew install macs-fan-control

### Output of command with `--verbose --debug`

```shell
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.4.12\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --fail --remote-time --output /Users/sukvvon/Library/Caches/Homebrew/api/formula.jws.json --location --time-cond /Users/sukvvon/Library/Caches/Homebrew/api/formula.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.12\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4319k  100 4319k    0     0   922k      0  0:00:04  0:00:04 --:--:--  923k
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading macs-fan-control
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading macs-fan-control
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.4.12\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --fail --remote-time --output /Users/sukvvon/Library/Caches/Homebrew/api/cask.jws.json --location --time-cond /Users/sukvvon/Library/Caches/Homebrew/api/cask.jws.json --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.12\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --fail --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1552k  100 1552k    0     0   913k      0  0:00:01  0:00:01 --:--:--  913k
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading macs-fan-control
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://github.com/crystalidea/macs-fan-control/releases/download/v1.5.17/macsfancontrol.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.12\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 -V
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.12\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/crystalidea/macs-fan-control/releases/download/v1.5.17/macsfancontrol.zip
Already downloaded: /Users/sukvvon/Library/Caches/Homebrew/downloads/7224d21bf2d65e6b6019cd4070ff1435340a2697a34539b71c5132b88f350ac8--macsfancontrol.zip
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target arm64-apple-macosx15 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/sukvvon/Library/Caches/Homebrew/downloads/7224d21bf2d65e6b6019cd4070ff1435340a2697a34539b71c5132b88f350ac8--macsfancontrol.zip
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/sukvvon/Library/Caches/Homebrew/downloads/7224d21bf2d65e6b6019cd4070ff1435340a2697a34539b71c5132b88f350ac8--macsfancontrol.zip
==> /Users/sukvvon/Library/Caches/Homebrew/downloads/7224d21bf2d65e6b6019cd4070ff1435340a2697a34539b71c5132b88f350ac8--macsfancontrol.zip is quarantined
==> Verifying checksum for '7224d21bf2d65e6b6019cd4070ff1435340a2697a34539b71c5132b88f350ac8--macsfancontrol.zip'
Error: SHA256 mismatch
Expected: ec22fe2723e9bd77efbcaaf5ba129571c049d88f7078224a0c2836e943b02ea5
  Actual: db659ef42c2553616817a3d92e61aaee6f20d18df98caba9d9fba73b26c1f9cf
    File: /Users/sukvvon/Library/Caches/Homebrew/downloads/7224d21bf2d65e6b6019cd4070ff1435340a2697a34539b71c5132b88f350ac8--macsfancontrol.zip
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:302:in `verify_checksum'
/opt/homebrew/Library/Homebrew/downloadable.rb:117:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:90:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:69:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:193:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:74:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:104:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:245:in `block in run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:234:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:234:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
 ✘ sukvvon  ~/Documents 
```

### Output of `brew doctor` and `brew config`

```shell
✘ sukvvon  ~/Documents  brew doctor
Your system is ready to brew.

 sukvvon  ~/Documents  brew config
HOMEBREW_VERSION: 4.4.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3001afe88112c13b5aafdd92e097680897060881
Last commit: 3 days ago
Branch: stable
Core tap JSON: 18 Dec 06:24 UTC
Core cask tap JSON: 18 Dec 06:24 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
no output
```

**Comment by SMillerDev** [comment]
>  I made doubly sure this is not a checksum does not match / SHA256 mismatch error (do not open an issue before trying to open a PR to fix first).

Please don't check boxes you didn't do

**Comment by sukvvon** [comment]
> > I made doubly sure this is not a checksum does not match / SHA256 mismatch error (do not open an issue before trying to open a PR to fix first).
> 
> Please don't check boxes you didn't do

@SMillerDev i fixed! thanks for your advice!
