### ISSUE TITLE
Cask `altair-graphql-client` not available in version 8.1.1

### ISSUE THREAD

**Issue by Anticom** [Homebrew/homebrew-cask#196733]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Homebrew currently offers Cask `altair-graphql-client` in version 8.1.1

```sh
$ brew info --cask altair-graphql-client
==> altair-graphql-client: 8.1.1
https://altair.sirmuel.design/
Installed
/opt/homebrew/Caskroom/altair-graphql-client/8.1.0 (297.5MB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/a/altair-graphql-client.rb
==> Name
Altair GraphQL Client
==> Description
GraphQL client
==> Artifacts
Altair GraphQL Client.app (App)
==> Analytics
install: 192 (30 days), 667 (90 days), 3,022 (365 days)
```

However looking at the [Releases in the Repo](https://github.com/imolorhe/altair/releases/) referenced in the [cask file](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/a/altair-graphql-client.rb#L4), this release is (no longer?) present.

My assumption is, that this release has been removed due to issues etc.  
The latest currently available Release is 8.0.5.

Can we please revert back to that version?  
I am not familiar with whether brew has some kind of automated process updating the formulae or whether this is done manually. However I am happy to provide a PR for that if you'd like me to.

### Command that failed

```sh
brew upgrade --cask altair-graphql-client
```

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading altair-graphql-client
/usr/bin/env PATH=/opt/homebrew/opt/gh/bin:/opt/homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin HOME=/Users/anticom gh auth token --hostname github.com
/usr/bin/env HOME=/Users/anticom git credential-osxkeychain get
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/altair-graphql-client/.metadata/8.1.0/20241229111145.706/Casks/altair-graphql-client.json
altair-graphql-client 8.1.0 -> 8.1.1
==> Started upgrade process for Cask altair-graphql-client
==> Upgrading altair-graphql-client
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.13-53-g9626df0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 -V
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.13-53-g9626df0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/imolorhe/altair/releases/download/v8.1.1/altair_8.1.1_arm64_mac.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.13-53-g9626df0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 -V
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.13-53-g9626df0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET --http1.1 https://github.com/imolorhe/altair/releases/download/v8.1.1/altair_8.1.1_arm64_mac.zip
==> Downloading https://github.com/imolorhe/altair/releases/download/v8.1.1/altair_8.1.1_arm64_mac.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.13-53-g9626df0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/imolorhe/altair/releases/download/v8.1.1/altair_8.1.1_arm64_mac.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.13-53-g9626df0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 -V
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.13-53-g9626df0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET --http1.1 https://github.com/imolorhe/altair/releases/download/v8.1.1/altair_8.1.1_arm64_mac.zip
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.13-53-g9626df0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/anticom/Library/Caches/Homebrew/downloads/e8f6109f37db2d456056e5aa4a86798709fa46bbf4820c0341fdab8fb601313d--altair_8.1.1_arm64_mac.zip.incomplete --location https://github.com/imolorhe/altair/releases/download/v8.1.1/altair_8.1.1_arm64_mac.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) The requested URL returned error: 404
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.13-53-g9626df0\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.1.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 -V
==> Purging files for version 8.1.1 of Cask altair-graphql-client
Error: altair-graphql-client: Download failed on Cask 'altair-graphql-client' with message: Download failed: https://github.com/imolorhe/altair/releases/download/v8.1.1/altair_8.1.1_arm64_mac.zip
/opt/homebrew/Library/Homebrew/download_strategy.rb:433:in `rescue in fetch'
/opt/homebrew/Library/Homebrew/download_strategy.rb:430:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:103:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:175:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:175:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:117:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/cask/download.rb:60:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:194:in `download'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:74:in `fetch'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:195:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:116:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:115:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:115:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:257:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/call_validation.rb:278:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11708/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
-
```

### Output of `brew tap`

```shell
-
```

**Comment by Anticom** [comment]
Looking into it a bit more, those two commits appear to be the culprit:
* da70cfff
* d9b1112

Questions:
1. Can we just revert to db4a434 ?
2. Will brew pick this up automatically and perform a downgrade on next `brew up && brew upgrade` or does this require some additional steps / flags in order for a downgrade to work?

**Comment by Anticom** [comment]
Thanks!

**Comment by bevanjkay** [comment]
You have probably already discovered this... but yes `brew upgrade` will install the current version of the cask file, if it differs to the one installed (regardless of if it is newer or older).

**Comment by Anticom** [comment]
@bevanjkay yep I did. Thank you for elaborating on my question just in case.
