### ISSUE TITLE
brew cask list: Error: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by twogee** [Homebrew/homebrew-cask#47613]
During `brew upgrade` I noticed
```
 ==> Auto-updated Homebrew!
Updated Homebrew from 97645d061 to e4c02fafd.
==> Migrating tap caskroom/cask to homebrew/cask...
Moving /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
Changing remote from https://github.com/caskroom/homebrew-cask to https://github.com/Homebrew/homebrew-cask...
```
Since then, many `brew cask` commands (e.g., `list`) result in the following
```
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:44:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:44:in `Pathname'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:44:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:27:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:27:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:20:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:20:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:40:in `list_installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
