### ISSUE TITLE
Error: No such file or directory - /usr/bin/xattr

### ISSUE THREAD

**Issue by vikassry** [Homebrew/homebrew-cask#48284]
While installing minikube. I got this error

#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
I wanted to install minikube. Then I got following error: 
Error: No such file or directory - /usr/bin/xattr

#### Command that failed
```
brew cask install minikube
```

#### Output of command with `--force --verbose --debug`

```
==> Determining which containers to use based on 'container :type'
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubernetes-cli.rb
All Formula dependencies satisfied.
==> Downloading
==> Downloading https://storage.googleapis.com/minikube/releases/v0.27.0/minikube-darwin-amd64
Already downloaded: /Users/vikass/Library/Caches/Homebrew/Cask/minikube--0.27.0
==> Downloaded to -> /Users/vikass/Library/Caches/Homebrew/Cask/minikube--0.27.0
==> Verifying download
==> Determining which verifications to run for Cask minikube
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask minikube
==> SHA256 checksums match
==> Installing Cask minikube
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on 'container :type'
==> Using container class Hbc::Container::Naked for /Users/vikass/Library/Caches/Homebrew/Cask/minikube--0.27.0
==> Executing: ["/usr/bin/ditto", "--", "/Users/vikass/Library/Caches/Homebrew/Cask/minikube--0.27.0", "/usr/local/Caskroom/minikube/0.27.0/minikube-darwin-amd64"]
==> Creating metadata directory /usr/local/Caskroom/minikube/.metadata/0.27.0/20180611115927.299.
==> Creating metadata subdirectory /usr/local/Caskroom/minikube/.metadata/0.27.0/20180611115927.299/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x0000010245b250>
==> Installing artifact of class Hbc::Artifact::Binary
==> Linking Binary 'minikube-darwin-amd64' to '/usr/local/bin/minikube'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/minikube/0.27.0/minikube-darwin-amd64", "/usr/local/bin/minikube"]
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
==> Executing: ["/usr/bin/xattr", "-p", "com.apple.metadata:kMDItemAlternateNames", "/usr/local/Caskroom/minikube/0.27.0/minikube-darwin-amd64"]
==> Purging files for version 0.27.0 of Cask minikube
Error: No such file or directory - /usr/bin/xattr
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/open3.rb:199:in `spawn'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/open3.rb:95:in `popen3'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:88:in `each_output_line'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:25:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:59:in `add_altname_metadata'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:60:in `create_filesystem_link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:48:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/binary.rb:7:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:15:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:176:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:168:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:82:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:31:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:94:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:128:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:174:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:174:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:152:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:128:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.7-72-g3081390
Homebrew/homebrew-cask (git revision 881bae; last commit 2018-06-11)
==> macOS
10.10.5
==> SIP
N/A
==> Java
1.8.0_101
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 40.6MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3976 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

**Comment by commitay** [comment]
Please fill out the template and provide all of the requested information.

**Comment by vikassry** [comment]
I have provided the the information.

**Comment by commitay** [comment]
Whats the output of `/usr/bin/xattr` and `/usr/bin/csrutil status`?

**Comment by vikassry** [comment]
no such file or directory: usr/bin/file

**Comment by commitay** [comment]
`$ /usr/bin/csrutil status`?

**Comment by vikassry** [comment]
no such file or directory: /usr/bin/csrutil
I was getting errors for upgrading exixsting brew packages as well because of my macOs version: 10.10

**Comment by commitay** [comment]
`/usr/bin/xattr` is a utility provided by macOS, that it is missing means a problem with your system and not with Cask. I'm afraid you'll have to figure this out yourself.
