### ISSUE TITLE
Checksum for Cask 'mactracker' does not match

### ISSUE THREAD

**Issue by kaspermalfroid** [Homebrew/homebrew-cask#48441]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Checksum for Cask 'mactracker' does not match

#### Command that failed

```
brew cask install mactracker
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install mactracker --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://www.mactracker.ca/downloads/Mactracker_7.7.4.zip
Already downloaded: /Users/malfroid/Library/Caches/Homebrew/Cask/mactracker--7.7.4.zip
==> Downloaded to -> /Users/malfroid/Library/Caches/Homebrew/Cask/mactracker--7.7.4.zip
==> Verifying download
==> Determining which verifications to run for Cask mactracker
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask mactracker
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'mactracker' does not match.

Expected: c387757a8efc3df785ecaf6967a8394cdae319d270a06523ee3f50d67088a746
Actual:   5a07024328322b1736070cc98136318d1adfa1ac544fb7025995b4131a3d6940
File:     /Users/malfroid/Library/Caches/Homebrew/Cask/mactracker--7.7.4.zip

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:42:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:22:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:21:in `block in all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:140:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:52:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:77:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:31:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:127:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:151:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:127:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.6.8-25-g9b21422
Homebrew/homebrew-cask (git revision 8bd847; last commit 2018-06-14)
==> macOS
10.13.5
==> SIP
Enabled
==> Java
10.0.1, 9.0.4, 1.8.0_172
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (61 files, 4.2GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3977 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (180 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-eid (11 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1162 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (149 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
$ brew tap
buo/cask-upgrade
david0/audio
domt4/autoupdate
homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
vitorgalvao/tiny-scripts
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error

https://github.com/Homebrew/homebrew-cask/pull/48469
