### ISSUE TITLE
checksum error on install rar 5.6.0

### ISSUE THREAD

**Issue by cyberdemon8** [Homebrew/homebrew-cask#49298]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Error: Checksum for Cask 'rar' does not match.

#### Command that failed

```
brew cask install --force rar
```

#### Output of command with `--force --verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
Instructions on using rar and unrar are available in

  /usr/local/Caskroom/rar/5.6.0/rar/rar.txt

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://www.rarlab.com/rar/rarosx-5.6.0.tar.gz
Already downloaded: /Users/valentino/Library/Caches/Homebrew/Cask/rar--5.6.0.tar.gz
==> Downloaded to -> /Users/valentino/Library/Caches/Homebrew/Cask/rar--5.6.0.tar.gz
==> Verifying download
==> Determining which verifications to run for Cask rar
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask rar
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'rar' does not match.

Expected: 381eb0c0645bfbd603e7e20a6a8cb34e484c6eeca161a1b3017cf93415448fde
Actual:   381ca05ca2701cf72148da49d36a4dda4e8e29cd0c3879f697b2861326277d5d
File:     /Users/valentino/Library/Caches/Homebrew/Cask/rar--5.6.0.tar.gz

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:42:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:22:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:21:in `block in all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:140:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:52:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:77:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:95:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:164:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:129:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:153:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:129:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.9-123-g4840b68
Homebrew/homebrew-cask (git revision ddacc0; last commit 2018-07-06)
==> macOS
10.13.5
==> SIP
Enabled
==> Java
10.0.1, 10, 9.0.4
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (18 files, 565.8MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3989 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (183 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1163 casks)
/usr/local/Homebrew/Library/Taps/colindean/homebrew-fonts-nonfree (1 cask)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
colindean/fonts-nonfree
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/49149
