### ISSUE TITLE
Cask 'google-chrome-canary' is unavailable

### ISSUE THREAD

**Issue by dnicolson** [Homebrew/homebrew-cask#49510]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The cask 'google-chrome-canary' is unable to be installed.

#### Command that failed

```
brew cask install google-chrome-canary --verbose --force --debug
```

#### Output of command with `--force --verbose --debug`

```
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
Error: Cask 'google-chrome-canary' is unavailable: No Cask with this name exists.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:51:in `rescue in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.13
Homebrew/homebrew-cask (git revision 153b2; last commit 2018-07-11)
==> macOS
10.13.3
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 52.7MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3994 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/cask/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/fish"
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/core
homebrew/services
```

I was only able to install it by running `brew cask install https://raw.github...google-chrome-canary.rb`.

The following is the output of `brew` cleanup tasks, removing and installing the cask.

```
$ brew update; brew cleanup; brew cask cleanup

[removed]

$ brew cask remove google-chrome-canary
==> Uninstalling Cask google-chrome-canary
==> Running uninstall process for google-chrome-canary; your password may be necessary
==> Removing launchctl service com.google.keystone.agent
Password:
==> Removing launchctl service com.google.keystone.daemon
==> Backing App 'Google Chrome Canary.app' up to '/usr/local/Caskroom/google-chrome-canary/latest/Google Chrome Canary.app'.
==> Removing App '/Applications/Google Chrome Canary.app'.
==> Purging files for version latest of Cask google-chrome-canary

$ brew cask install google-chrome-canary --verbose

Error: Cask 'google-chrome-canary' is unavailable: No Cask with this name exists.
Error: Kernel.exit
```

**Comment by commitay** [comment]
Please complete the steps in the template and provide all of the requested information.

**Comment by commitay** [comment]
`brew tap homebrew/cask-versions && brew cask install google-chrome-canary`
