### ISSUE TITLE
Error: No such file or directory @ rb_file_s_rename

### ISSUE THREAD

**Issue by phdoerfler** [Homebrew/homebrew-cask#49512]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
  - I have fixed zero of the issues reported there as they appear to be unrelated to this
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I ran `brew cask upgrade --greedy && brew cask cleanup`. It failed:

```
==> Purging files for version latest of Cask miniconda
Error: uninitialized constant HashValidator::CaskError
Did you mean?  ScanError
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils/hash_validator.rb:5:in `assert_valid_keys'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:48:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/installer.rb:26:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:176:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:168:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:69:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:32:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Command that failed

```
brew cask upgrade --greedy
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask upgrade --greedy --force --verbose --debug
Alias tip: cask upgrade --greedy --force --verbose --debug
==> Determining which containers to use based on 'container :type'
==> Upgrading 6 outdated packages, with result:
miniconda latest, printopia 3.0.11, sourcetree 2.7.6a, suspicious-package 3.3.2, synergy 2.0.12,b1807-50472cde, visual-studio-code 1.25.0,0f080e5267e829de46638128001aeb7ca2d6d50e
==> Started upgrade process for Cask miniconda
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Printing caveats
==> Caveats
To use miniconda, you may need to add the /usr/local/miniconda3/bin directory
to your PATH environment variable, eg (for bash shell):

  export PATH=/usr/local/miniconda3/bin:"$PATH"

Cask miniconda installs files under /usr/local. The presence of such
files can cause warnings when running "brew doctor", which is considered
to be a bug in Homebrew-Cask.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
/usr/bin/curl -q --show-error --user-agent Homebrew/1.6.13 (Macintosh; Intel Mac OS X 10.13.5) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/phi/Library/Caches/Homebrew/Cask/miniconda--latest.sh.incomplete https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34.9M  100 34.9M    0     0  14.6M      0  0:00:02  0:00:02 --:--:-- 14.7M
==> Downloaded to -> /Users/phi/Library/Caches/Homebrew/Cask/miniconda--latest.sh
==> Verifying download
==> Determining which verifications to run for Cask miniconda
==> Checking for verification class Hbc::Verify::Checksum
==> No checksum defined for Cask miniconda, skipping verification
==> 0 verifications defined
==> Starting upgrade for Cask miniconda
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00000103e112a8>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for miniconda; your password may be necessary
==> Removing files:
/usr/local/miniconda3
==> Executing: ["/usr/bin/sudo", "-E", "PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
==> Un-installing artifact of class Hbc::Artifact::PostflightBlock
Error: No such file or directory @ rb_file_s_rename - (/usr/local/Caskroom/miniconda/latest, /usr/local/Caskroom/miniconda/latest.upgrading)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:369:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:369:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:369:in `backup'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:365:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:62:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:32:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
Alias tip: cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.6.13
Homebrew/homebrew-cask (git revision 153b2; last commit 2018-07-11)
==> macOS
10.13.5
==> SIP
Enabled
==> Java
10.0.1, 1.8.0_144, 1.8.0_131, 1.8.0_112, 1.8.0_45, 1.7.0_79
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (12 files, 1GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3994 casks)
/usr/local/Homebrew/Library/Taps/railwaycat/homebrew-emacsmacport (2 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (185 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
$ brew tap
buo/cask-upgrade
homebrew/boneyard
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/dupes
homebrew/fuse
homebrew/games
homebrew/python
homebrew/science
homebrew/versions
homebrew/x11
martido/brew-graph
railwaycat/emacsmacport
```

**Comment by reitermarkus** [comment]
This is fixed now.
