### ISSUE TITLE
Anaconda cask install gives "Error: uninitialized constant HashValidator::CaskError"

### ISSUE THREAD

**Issue by CryoRenegade** [Homebrew/homebrew-cask#49529]
Completed recommended steps in https://github.com/Homebrew/homebrew-cask#reporting-bugs.
Still happens.

Use of `brew cask install anaconda --verbose --debug`
[`==> Determining which containers to use based on 'container :type'
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
To use anaconda, you may need to add the /usr/local/anaconda3/bin directory
to your PATH environment variable, eg (for bash shell):

  export PATH=/usr/local/anaconda3/bin:"$PATH"

Cask anaconda installs files under /usr/local. The presence of such
files can cause warnings when running "brew doctor", which is considered
to be a bug in Homebrew-Cask.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://repo.anaconda.com/archive/Anaconda3-5.2.0-MacOSX-x86_64.sh
Already downloaded: /Users/jacobledbetter/Library/Caches/Homebrew/Cask/anaconda--5.2.0.sh
==> Downloaded to -> /Users/jacobledbetter/Library/Caches/Homebrew/Cask/anaconda--5.2.0.sh
==> Verifying download
==> Determining which verifications to run for Cask anaconda
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask anaconda
==> SHA256 checksums match
==> Installing Cask anaconda
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on 'container :type'
==> Using container class Hbc::Container::Naked for /Users/jacobledbetter/Library/Caches/Homebrew/Cask/anaconda--5.2.0.sh
==> Executing: ["/usr/bin/ditto", "--", "/Users/jacobledbetter/Library/Caches/Homebrew/Cask/anaconda--5.2.0.sh", "/usr/local/Caskroom/anaconda/5.2.0/Anaconda3-5.2.0-MacOSX-x86_64.sh"]
==> Creating metadata directory /usr/local/Caskroom/anaconda/.metadata/5.2.0/20180711162354.898.
==> Creating metadata subdirectory /usr/local/Caskroom/anaconda/.metadata/5.2.0/20180711162354.898/Casks.
==> Installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x00007f954d040968>
==> Installing artifact of class Hbc::Artifact::Installer
==> Running installer script 'Anaconda3-5.2.0-MacOSX-x86_64.sh'
==> Purging files for version 5.2.0 of Cask anaconda
Error: uninitialized constant HashValidator::CaskError
Did you mean?  ScanError
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils/hash_validator.rb:5:in `assert_valid_keys'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:48:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/installer.rb:26:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:176:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:168:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:82:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:145:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'`

**Comment by CryoRenegade** [comment]
👍
