### ISSUE TITLE
Error: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by kkrauth** [Homebrew/homebrew-cask#49533]
OS: High Sierra 10.13.4 (17E199)
Xcode: Version 9.4.1 (9F2000)

I ran brew update-reset && brew update.

After adding the cask-versions tap (homebrew/cask-versions) I get the following error:

```
$ brew search java
Error: undefined method `[]' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/gpg-suite-nightly.rb:8:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/url.rb:10:in `block in from'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/stanza_proxy.rb:8:in `block in once'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/stanza_proxy.rb:21:in `to_s'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/gpg-suite-nightly.rb:12:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:36:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:36:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:67:in `cask'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cask_loader.rb:15:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:113:in `cask'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/gpg-suite-nightly.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:20:in `block in each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:26:in `select'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:26:in `search_string'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:7:in `search'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/search.rb:29:in `search_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:83:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

My installed taps:
```
$ brew tap
Updating Homebrew...
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
