### ISSUE TITLE
Mono-mdk file doesn’t exists

### ISSUE THREAD

**Issue by DJManas** [Homebrew/homebrew-cask#49925]
Hello,

I had run `brew cask upgrade`, but **mono-mdk** fails to upgrade with following reason:
```
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 1 outdated package, with result:
mono-mdk 5.12.0.301
==> Caveats
Installing mono-mdk removes mono and mono dependant formula binaries in
/usr/local/bin and adds mono-mdk to /private/etc/paths.d/
You may want to:

  brew unlink {formula} && brew link {formula}

and/or remove /private/etc/paths.d/mono-commands

==> Satisfying dependencies
==> Downloading https://download.mono-project.com/archive/5.12.0/macos-10-universal/MonoFramework-MDK-5.12.0.301.macos10.xamarin.universal.pkg
Already downloaded: /Users/djmanas/Library/Caches/Homebrew/Cask/mono-mdk--5.12.0.301.pkg
==> Verifying checksum for Cask mono-mdk
==> Starting upgrade for Cask mono-mdk
==> Running uninstall process for mono-mdk; your password may be necessary
==> Uninstalling packages:
==> Removing files:
/Library/Frameworks/Mono.framework/Versions/5.12.0
/private/etc/paths.d/mono-commands
==> Removing directories if empty:
/Library/Frameworks/Mono.framework/Versions
/Library/Frameworks/Mono.framework
Error: No such file or directory @ rb_file_s_rename - (/usr/local/Caskroom/mono-mdk/5.12.0.226, /usr/local/Caskroom/mono-mdk/5.12.0.226.upgrading)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:405:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:405:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:405:in `backup'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:401:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:63:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:33:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

I had tried `brew update-reset && brew update`, but it haven’t solved my issue and it is not between „general issues“...

Thanks,
Regards,
Petr Sourek

**Comment by commitay** [comment]
Output of `brew cask doctor`?

**Comment by DJManas** [comment]
Sorry, I am dumb... :-(

```
RinceWind:git djmanas$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.7.0-77-gc5f92bf
Homebrew/homebrew-cask (git revision 84c56; last commit 2018-07-23)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
1.8.0_131, 1.8.0_121
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 347.6MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3998 casks)
/usr/local/Homebrew/Library/Taps/mengbo/homebrew-ch340g-ch34g-ch34x-mac-os-x-driver (1 cask)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (149 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
Please `brew update` and try `brew cask upgrade` again.

**Comment by DJManas** [comment]
Did not help. But i had tried `brew cask reinstall mono-mdk` and it worked.
