### ISSUE TITLE
Installing Evernote fails with `Directory not empty @ dir_s_rmdir`

### ISSUE THREAD

**Issue by novasharper** [Homebrew/homebrew-cask#49940]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When I try installing Evernote, it fails at the `Purging files ...` step. It complains that the directory is not empty.

#### Command that failed

```
brew cask install evernote
```

#### Output of command with `--force --verbose --debug`

```
Updating Homebrew...
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://cdn1.evernote.com/mac-smd/public/Evernote_RELEASE_7.2.3_456885.dmg
Already downloaded: /Users/pllong/Library/Caches/Homebrew/Cask/evernote--7.2.3_456885.dmg
==> Downloaded to -> /Users/pllong/Library/Caches/Homebrew/Cask/evernote--7.2.3_456885.dmg
==> Verifying download
==> Determining which verifications to run for Cask evernote
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask evernote
==> SHA256 checksums match
==> Installing Cask evernote
==> Hbc::Installer#stage
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::SelfExtractingExecutable
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> /usr/bin/hdiutil imageinfo /Users/pllong/Library/Caches/Homebrew/Cask/evernote--7.2.3_456885.dmg
==> Extracting primary container
==> Using container class Hbc::Container::Dmg for /Users/pllong/Library/Caches/Homebrew/Cask/evernote--7.2.3_456885.dmg
==> /usr/bin/hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/qq/k2k8vc9x2td3xvg4vsvw3dt80000gn/T/d20180723-25429-wxowqf /Users/pllong/Library/Caches/Homebrew/Cask/evernote--7.2.3_456885.dmg
==> /usr/bin/hdiutil convert -quiet -format UDTO -o /var/folders/qq/k2k8vc9x2td3xvg4vsvw3dt80000gn/T/d20180723-25429-wxowqf/evernote--7.2.3_456885.cdr /Users/pllong/Library/Caches/Homebrew/Cask/evernote--7.2.3_456885.dmg
==> /usr/bin/hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/qq/k2k8vc9x2td3xvg4vsvw3dt80000gn/T/d20180723-25429-wxowqf /var/folders/qq/k2k8vc9x2td3xvg4vsvw3dt80000gn/T/d20180723-25429-wxowqf/evernote--7.2.3_456885.cdr
==> Purging files for version 7.2.3_456885 of Cask evernote
Error: Directory not empty @ dir_s_rmdir - /var/folders/qq/k2k8vc9x2td3xvg4vsvw3dt80000gn/T/d20180723-25429-wxowqf
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1446:in `rmdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1446:in `block in remove_dir1'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1457:in `platform_support'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1445:in `remove_dir1'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1438:in `remove'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:780:in `block in remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1495:in `ensure in postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1495:in `postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:778:in `remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:95:in `ensure in mktmpdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:95:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:34:in `mount'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:18:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/base.rb:18:in `extract'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:171:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:66:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:87:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:145:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.7.0-91-gdb29903
Homebrew/homebrew-cask (git revision 9df44; last commit 2018-07-23)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
10.0.2, 1.8.0_181
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 56.9MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3998 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (187 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1163 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
Updating Homebrew...
go-delve/delve
goreleaser/tap
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
```

**Comment by commitay** [comment]
Please `brew update` and try `brew cask install evernote` again.

**Comment by novasharper** [comment]
It worked this time.
