### ISSUE TITLE
error when using "brew cask install github"

### ISSUE THREAD

**Issue by mxcfb** [Homebrew/homebrew-cask#50095]
#### General troubleshooting steps

- [ ] I have retried my command with `--force` and the issue is still present.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

when I run brew cask install github
the result shows as follows

#### Command that failed

```
{
Updating Homebrew...
==> Satisfying dependencies
==> Downloading https://desktop.githubusercontent.com/releases/1.2.6-908a2695/GitHubDesktop.zip
Already downloaded: /Users/xxx/Library/Caches/Homebrew/Cask/github--1.2.6-908a2695.zip
==> Verifying checksum for Cask github
==> Installing Cask github
==> Moving App 'GitHub Desktop.app' to '/Applications/GitHub Desktop.app'.
==> Linking Binary 'github.sh' to '/usr/local/bin/github'.
==> Backing App 'GitHub Desktop.app' up to '/usr/local/Caskroom/github/1.2.6-908a2695/GitHub Desktop.app'.
==> Removing App '/Applications/GitHub Desktop.app'.
==> Purging files for version 1.2.6-908a2695 of Cask github
Error: Failure while executing; `/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames \(\"github\"\) /Applications/GitHub\ Desktop.app/Contents/Resources/app/static/github.sh` exited with 1. Here's the output:
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:97:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:46:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:21:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:25:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:71:in `add_altname_metadata'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:60:in `create_filesystem_link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:48:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/binary.rb:7:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:15:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:189:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:181:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:88:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'}
```

#### Output of command with `--force --verbose --debug`

```
{
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://desktop.githubusercontent.com/releases/1.2.6-908a2695/GitHubDesktop.zip
Already downloaded: /Users/xxx/Library/Caches/Homebrew/Cask/github--1.2.6-908a2695.zip
==> Downloaded to -> /Users/xxx/Library/Caches/Homebrew/Cask/github--1.2.6-908a2695.zip
==> Verifying download
==> Determining which verifications to run for Cask github
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask github
==> SHA256 checksums match
==> Installing Cask github
==> Hbc::Installer#stage
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::SelfExtractingExecutable
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> /usr/bin/hdiutil imageinfo /Users/xxx/Library/Caches/Homebrew/Cask/github--1.2.6-908a2695.zip
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Extracting primary container
==> Using container class Hbc::Container::Zip for /Users/ChenFengbo/Library/Caches/Homebrew/Cask/github--1.2.6-908a2695.zip
==> /usr/bin/ditto -x -k -- /Users/xxx/Library/Caches/Homebrew/Cask/github--1.2.6-908a2695.zip /var/folders/j5/hn49pnw535b4p5p8qwxjjx6m0000gn/T/d20180726-16358-1k3u6o
==> Creating metadata directory /usr/local/Caskroom/github/.metadata/1.2.6-908a2695/20180726023225.943.
==> Creating metadata subdirectory /usr/local/Caskroom/github/.metadata/1.2.6-908a2695/20180726023225.943/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x0000000102144940>
==> Installing artifact of class Hbc::Artifact::App
==> Moving App 'GitHub Desktop.app' to '/Applications/GitHub Desktop.app'.
==> Installing artifact of class Hbc::Artifact::Binary
==> Linking Binary 'github.sh' to '/usr/local/bin/github'.
==> /bin/ln -h -f -s -- /Applications/GitHub\ Desktop.app/Contents/Resources/app/static/github.sh /usr/local/bin/github
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
==> /usr/bin/xattr -p com.apple.metadata:kMDItemAlternateNames /Applications/GitHub\ Desktop.app/Contents/Resources/app/static/github.sh
==> Existing metadata is: ''
==> /bin/chmod -- u\+rw /Applications/GitHub\ Desktop.app/Contents/Resources/app/static/github.sh /Applications/GitHub\ Desktop.app/Contents/Resources/app/static/github.sh
==> /usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames \(\"github\"\) /Applications/GitHub\ Desktop.app/Contents/Resources/app/static/github.sh
==> Reverting installation of artifact of class Hbc::Artifact::App
==> Backing App 'GitHub Desktop.app' up to '/usr/local/Caskroom/github/1.2.6-908a2695/GitHub Desktop.app'.
==> Removing App '/Applications/GitHub Desktop.app'.
==> Purging files for version 1.2.6-908a2695 of Cask github
Error: Failure while executing; `/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames \(\"github\"\) /Applications/GitHub\ Desktop.app/Contents/Resources/app/static/github.sh` exited with 1. Here's the output:
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:97:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:46:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:21:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:25:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:71:in `add_altname_metadata'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:60:in `create_filesystem_link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:48:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/binary.rb:7:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:15:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:189:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:181:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:88:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:145:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'}
```

#### Output of `brew cask doctor`

```
{==> Homebrew-Cask Version
Homebrew-Cask 1.7.1
Homebrew/homebrew-cask (git revision 62622; last commit 2018-07-26)
==> macOS
10.13.5
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 65.7MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3999 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"}
```

#### Output of `brew tap`

```
{Updating Homebrew...
homebrew/cask
homebrew/core}
```

**Comment by adidalal** [comment]
Your system python may be at fault here.

Took a look at `github.sh`, this seems to be the issue:
`/usr/bin/python -c "import os,sys; print os.path.realpath(sys.argv[1])" "$0";`

Please try installing manually, and see if the issue persists.

If there is an issue, you may update the top post (the check boxes are there for a reason) and comment back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.
