### ISSUE TITLE
Unable to upgrade MPV to 0.29.0 on macOS 10.13.6

### ISSUE THREAD

**Issue by FoxBJK** [Homebrew/homebrew-cask#50162]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I'm unable to update MPV on macOS 10.13.6 due to a checksum mismatch:
Expected: 41f79cc33758888ed75d2163cb1c209d79e6fa7d558b6e8fef3dfe05b4a6fc29
Actual:   eeddff95ba8ece89c539485bbe94b942c43588500e32c60b2a2b9da1ae8a5f84

What's on the site is correct, and what's being downloaded is correct, but it seems the checksums for different OS versions in the formula don't match the MPV site.

#### Command that failed

```
brew cask upgrade
```

#### Output of command with `--force --verbose --debug`

```
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 2 outdated packages, with result:
mpv 0.29.0, virtualbox 5.2.16,123759
==> Started upgrade process for Cask mpv
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-0.29.0.tar.gz
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.1-31-g5d4adea (Macintosh; Intel Mac OS X 10.13.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/foxbjk/Library/Caches/Homebrew/Cask/mpv--0.29.0.tar.gz.incomplete https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-0.29.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.6M  100 16.6M    0     0  2523k      0  0:00:06  0:00:06 --:--:-- 3167k
==> Downloaded to -> /Users/foxbjk/Library/Caches/Homebrew/Cask/mpv--0.29.0.tar.gz
==> Verifying download
==> Determining which verifications to run for Cask mpv
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask mpv
==> Note: running "brew update" may fix sha256 checksum errors
==> Purging files for version 0.29.0 of Cask mpv
Error: Checksum for Cask 'mpv' does not match.

Expected: 41f79cc33758888ed75d2163cb1c209d79e6fa7d558b6e8fef3dfe05b4a6fc29
Actual:   eeddff95ba8ece89c539485bbe94b942c43588500e32c60b2a2b9da1ae8a5f84
File:     /Users/foxbjk/Library/Caches/Homebrew/Cask/mpv--0.29.0.tar.gz

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:42:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:22:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:21:in `block in all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:147:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:57:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:60:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:33:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:159:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:164:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:164:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.7.1-31-g5d4adea
Homebrew/homebrew-cask (git revision 6f6e1; last commit 2018-07-26)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (12 files, 656.4MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4006 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (187 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/50158

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error
