### ISSUE TITLE
Local By Flywheel not installing

### ISSUE THREAD

**Issue by BarryMode** [Homebrew/homebrew-cask#50318]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Tried to install local-by-flywheel. It installed Virtual Box and then failed.

#### Command that failed

```
brew cask install local-by-flywheel
```

#### Output of command with `--force --verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Installing Cask dependencies: virtualbox
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
To install and/or use virtualbox you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.virtualbox.org/virtualbox/5.2.16/VirtualBox-5.2.16-123759-OSX.dmg
Already downloaded: /Users/Barry/Library/Caches/Homebrew/Cask/virtualbox--5.2.16,123759.dmg
==> Downloaded to -> /Users/Barry/Library/Caches/Homebrew/Cask/virtualbox--5.2.16,123759.dmg
==> Verifying download
==> Determining which verifications to run for Cask virtualbox
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask virtualbox
==> SHA256 checksums match
==> Installing Cask virtualbox
==> Hbc::Installer#stage
==> hdiutil imageinfo /Users/Barry/Library/Caches/Homebrew/Cask/virtualbox--5.2.16,123759.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/Barry/Library/Caches/Homebrew/Cask/virtualbox--5.2.16,123759.dmg
==> hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/30/mf22kbd103j8zz4lh855xnw00000gn/T/d20180801-15390-6r7749 /Users/Barry/Library/Caches/Homebrew/Cask/virtualbox--5.2.16,123759.dmg
==> find . -print0
==> mkbom -s -i /var/folders/30/mf22kbd103j8zz4lh855xnw00000gn/T/20180801-15390-1kzwip6.list -- /var/folders/30/mf22kbd103j8zz4lh855xnw00000gn/T/20180801-15390-1in27x4.bom
==> ditto --bom /var/folders/30/mf22kbd103j8zz4lh855xnw00000gn/T/20180801-15390-1in27x4.bom -- /private/var/folders/30/mf22kbd103j8zz4lh855xnw00000gn/T/d20180801-15390-6r7749/dmg.33sm3P /var/folders/30/mf22kbd103j8zz4lh855xnw00000gn/T/d20180801-15390-1b26nj2
==> diskutil eject /private/var/folders/30/mf22kbd103j8zz4lh855xnw00000gn/T/d20180801-15390-6r7749/dmg.33sm3P
==> Creating metadata directory /usr/local/Caskroom/virtualbox/.metadata/5.2.16,123759/20180801151346.232.
==> Creating metadata subdirectory /usr/local/Caskroom/virtualbox/.metadata/5.2.16,123759/20180801151346.232/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00000001013abc20>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> /usr/bin/sudo -E -- env LOGNAME\=barry USER\=barry USERNAME\=barry /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/5.2.16,123759/VirtualBox.pkg -target / -verboseR
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%12.211756
installer:PHASE:Writing files…
installer:%29.058802
installer:PHASE:Writing files…
installer:%85.940625
installer:PHASE:Running package scripts…
installer:%86.992841
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 5.2.16,123759 of Cask virtualbox
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=barry USER=barry USERNAME=barry /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/5.2.16,123759/VirtualBox.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%12.211756
installer:PHASE:Writing files…
installer:%29.058802
installer:PHASE:Writing files…
installer:%85.940625
installer:PHASE:Running package scripts…
installer:%86.992841
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:97:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:45:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:58:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:64:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:50:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:31:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:89:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:292:in `block in cask_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:291:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:291:in `cask_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:218:in `satisfy_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:53:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:84:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.7.1-72-gdce6b87
Homebrew/homebrew-cask (git revision 0ceee; last commit 2018-08-01)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
10.0.2, 1.8.0_181, 1.8.0_172, 1.8.0_162
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 91.2MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4011 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (191 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1164 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
Updating Homebrew...
buo/cask-upgrade
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/php
homebrew/services
josegonzalez/php
```

**Comment by commitay** [comment]
Do this:
```
==> Caveats
To install and/or use virtualbox you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html
```

then `brew cask install --force virtualbox && brew cask install local-by-flywheel`

**Comment by BarryMode** [comment]
Thanks, it appears that installing Virtual Box first is required. That's the first time for me that a cask command didn't work on its own.
