### ISSUE TITLE
Error: Cask 'hexchat' is unavailable: No Cask with this name exists

### ISSUE THREAD

**Issue by sgon00** [Homebrew/homebrew-cask#50411]
#### General troubleshooting steps

```
$ brew tap
dart-lang/dart
homebrew/cask
homebrew/core

$ brew search hexchat
It was migrated from homebrew/core to homebrew/cask.
You can access it again by running:
  brew tap homebrew/cask
And then you can install it by running:
  brew cask install hexchat

$ brew cask install hexchat
Error: Cask 'hexchat' is unavailable: No Cask with this name exists.
```

#### Description of issue

cask repo is built-in by default. I have no idea why `brew search hexchat` asks me to tap cask again manually. I didn't follow the instruction, thus I didn't execute `brew tap homebrew/cask` because cask is built-in. I don't know why I can not install `hexchat`. I have installed many apps by using `brew cask install <apps>` commands. 

#### Command that failed

```
$ brew cask install hexchat
Updating Homebrew...
Error: Cask 'hexchat' is unavailable: No Cask with this name exists.
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install hexchat --force --verbose --debug
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
==> Determining which containers to use based on 'container :type'
Error: Cask 'hexchat' is unavailable: No Cask with this name exists.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:51:in `rescue in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:45:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:145:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew doctor
Your system is ready to brew.

$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.7.1
Homebrew/homebrew-cask (git revision ea7702; last commit 2018-08-03)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (8 files, 1GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4014 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
dart-lang/dart
homebrew/cask
homebrew/core
```

**Comment by commitay** [comment]
`hexchat` was removed from cask in https://github.com/Homebrew/homebrew-cask/pull/31907, as it's still listed [here in the formula migrations](https://github.com/Homebrew/homebrew-core/blob/master/tap_migrations.json#L25) it appears in the search results.

I'll go through the formula migrations and remove any others that have also been removed.

**Comment by commitay** [comment]
https://github.com/Homebrew/homebrew-core/pull/30761

**Comment by sgon00** [comment]
@commitay got it. thanks a lot for the quick reply. The search output did confuse me a lot. I am not sure what the process of closing an issue here. Feel free to close this issue at any time. Thanks a lot.

**Comment by commitay** [comment]
Thanks for report this!
