### ISSUE TITLE
Checksum for Cask 'navicat-premium' does not match

### ISSUE THREAD

**Issue by derekjkeller** [Homebrew/homebrew-cask#50477]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Updating Navicat Premium fails with "Checksum for Cask 'navicat-premium' does not match."

#### Command that failed

```
$ brew cask install navicat-premium
==> Satisfying dependencies
==> Downloading http://download.navicat.com/download/navicat121_premium_en.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask navicat-premium
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'navicat-premium' does not match.

Expected: 5284d81fc3d46bdadf7b96b2121a31245237eb0cabc8b38b5ed0384d2f6eaaf2
Actual:   d332a0f7519251972abdf0663f416be0adba2d208b499137c2c8604f5a5b3dd0
File:     /Users/derek/Library/Caches/Homebrew/Cask/navicat-premium--12.1.4.dmg

To retry an incomplete download, remove the file above.
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install navicat-premium --force --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://download.navicat.com/download/navicat121_premium_en.dmg
Already downloaded: /Users/derek/Library/Caches/Homebrew/Cask/navicat-premium--12.1.4.dmg
==> Downloaded to -> /Users/derek/Library/Caches/Homebrew/Cask/navicat-premium--12.1.4.dmg
==> Verifying download
==> Determining which verifications to run for Cask navicat-premium
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask navicat-premium
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'navicat-premium' does not match.

Expected: 5284d81fc3d46bdadf7b96b2121a31245237eb0cabc8b38b5ed0384d2f6eaaf2
Actual:   d332a0f7519251972abdf0663f416be0adba2d208b499137c2c8604f5a5b3dd0
File:     /Users/derek/Library/Caches/Homebrew/Cask/navicat-premium--12.1.4.dmg

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:42:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:22:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:21:in `block in all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:147:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:57:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:84:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.7.1-133-g4a9e051
Homebrew/homebrew-cask (git revision b17f9; last commit 2018-08-06)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
10.0.2
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (10 files, 1009MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4019 casks)
/usr/local/Homebrew/Library/Taps/phinze/homebrew-cask (4019 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (191 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (152 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-versions
homebrew/core
homebrew/services
phinze/cask
```

**Comment by vitorgalvao** [comment]
> phinze/cask

You should `untap` that.

The fix to your issue is [liked](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) in [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs). I’m fixing it right now.

**Comment by derekjkeller** [comment]
Sorry, I thought I was following this correctly.  I'd tried the steps in the linked doc.

> 1. Go to the vendor’s website (`brew cask home {{cask_name}}`).
>    * Alternatively, if it has an `appcast`, read that (`curl "$(brew cask _stanza appcast {{cask_name}})"`).
> 2. Find out what the latest version is. It will likely be expressed in the URL used to download it.
> 3. Take a look at the cask’s version (`brew cask _stanza version {{cask_name}}`) and verify it is indeed outdated.
>    * If the app’s version is `latest`, it means the `url` itself is outdated. It will need to be changed to the new one.

The latest version for Mac is 12.1.4 which is listed in the cask's version, and the url doesn't seem to have changed.  I wasn't sure what to do, so I opened the ticket.

Thanks for the help.

**Comment by vitorgalvao** [comment]
> The latest version for Mac is 12.1.4

It’s `12.1.5`. I’ve already submitted PRs to update all `navicat` casks.
