### ISSUE TITLE
Error: invalid option: --caskroom=/opt/homebrew-cask/Caskroom

### ISSUE THREAD

**Issue by Labutin** [Homebrew/homebrew-cask#50644]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Every `brew cask ...` commands ends with error message:
Error: invalid option: --caskroom=/opt/homebrew-cask/Caskroom

#### Command that failed

```
bash-3.2$ brew cask list
Error: invalid option: --caskroom=/opt/homebrew-cask/Caskroom
bash-3.2$ brew cask doctor
Error: invalid option: --caskroom=/opt/homebrew-cask/Caskroom
bash-3.2$ brew cask cleanup
Error: invalid option: --caskroom=/opt/homebrew-cask/Caskroom
```

#### Output of command with `--force --verbose --debug`

```
bash-3.2$ brew cask --force --verbose --debug list
Error: invalid option: --caskroom=/opt/homebrew-cask/Caskroom
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:60:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:40:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:91:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:145:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
bash-3.2$ brew cask doctor
Error: invalid option: --caskroom=/opt/homebrew-cask/Caskroom
```

#### Output of `brew tap`

```
bash-3.2$ brew tap
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/php
homebrew/versions
```

**Comment by reitermarkus** [comment]
You need to fix your `HOMEBREW_CASK_OPTS` variable.
