### ISSUE TITLE
Error: No such file or directory @ rb_file_s_rename, still affected by #49512

### ISSUE THREAD

**Issue by phdoerfler** [Homebrew/homebrew-cask#51021]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
  - None of the issues seemed relevant
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I am still affected by #49512. How do I fix this? I ran `brew update` and then `brew cask upgrade miniconda` which ultimately results in the error.

#### Command that failed

```
brew cask upgrade miniconda
```

#### Output of command with `--force --verbose --debug`

```
~ brew cask upgrade miniconda --force --verbose --debug
Alias tip: cask upgrade miniconda --force --verbose --debug
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core, homebrew/cask).
==> Migrating cache entries...
No changes to formulae.

==> Upgrading 1 outdated package, with result:
miniconda latest
==> Started upgrade process for Cask miniconda
==> Printing caveats
==> Caveats
To use miniconda, you may need to add the /usr/local/miniconda3/bin directory
to your PATH environment variable, eg (for bash shell):

  export PATH=/usr/local/miniconda3/bin:"$PATH"

Cask miniconda installs files under /usr/local. The presence of such
files can cause warnings when running "brew doctor", which is considered
to be a bug in Homebrew-Cask.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.1-308-gc9aa25e\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --silent --head --write-out \%\{redirect_url\} --output /dev/null https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.1-308-gc9aa25e\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/phi/Library/Caches/Homebrew/Cask/miniconda--latest.sh.incomplete https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34.9M  100 34.9M    0     0  2363k      0  0:00:15  0:00:15 --:--:-- 2270k
==> Downloaded to -> /Users/phi/Library/Caches/Homebrew/Cask/miniconda--latest.sh
==> Verifying download
==> Determining which verifications to run for Cask miniconda
==> Checking for verification class Hbc::Verify::Checksum
==> No checksum defined for Cask miniconda, skipping verification
==> 0 verifications defined
==> Starting upgrade for Cask miniconda
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x000000010250e288>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for miniconda; your password may be necessary
==> Removing files:
/usr/local/miniconda3
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
==> Un-installing artifact of class Hbc::Artifact::PostflightBlock
Error: No such file or directory @ rb_file_s_rename - (/usr/local/Caskroom/miniconda/latest, /usr/local/Caskroom/miniconda/latest.upgrading)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:412:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:412:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:412:in `backup'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:408:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:63:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:33:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
~ brew cask doctor
Alias tip: cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.7.1-308-gc9aa25e
Homebrew/homebrew-cask (git revision 9d0ddc; last commit 2018-08-20)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
10.0.2, 1.8.0_144, 1.8.0_131, 1.8.0_112, 1.8.0_45, 1.7.0_79
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4029 casks)
/usr/local/Homebrew/Library/Taps/railwaycat/homebrew-emacsmacport (2 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (193 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
~ brew tap
buo/cask-upgrade
d12frosted/emacs-plus
homebrew/boneyard
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/dupes
homebrew/fuse
homebrew/games
homebrew/python
homebrew/science
homebrew/versions
homebrew/x11
martido/brew-graph
railwaycat/emacsmacport
```

**Comment by vitorgalvao** [comment]
Please fill the template anyway. Presumably the details won’t be the exact same.

**Comment by phdoerfler** [comment]
@vitorgalvao Template is filled. I hope this helps.

**Comment by phdoerfler** [comment]
@reitermarkus what's your take on this?

**Comment by phdoerfler** [comment]
I just tried removing miniconda manually:

```
brew cask remove miniconda
Alias tip: cask remove miniconda
==> Uninstalling Cask miniconda
==> Running uninstall process for miniconda; your password may be necessary
==> Removing files:
/usr/local/miniconda3
==> Purging files for version latest of Cask miniconda
miniconda latest.upgrading is still installed.
Remove it with `brew cask uninstall --force miniconda`.
```

then I used `--force --debug`:

```
brew cask remove --force --debug miniconda
Alias tip: cask remove --force --debug miniconda
==> Uninstalling Cask miniconda
==> Uninstalling Cask miniconda
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00000001019c74d8>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for miniconda; your password may be necessary
==> Removing files:
/usr/local/miniconda3
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
==> Un-installing artifact of class Hbc::Artifact::PostflightBlock
==> Purging files for version latest of Cask miniconda
==> Purging all staged versions of Cask miniconda
```

Seems to have been a success. I did try `brew cask upgrade miniconda` again just before doing this and the error was still there.

After removing I was able to reinstall miniconda again with cask.

**Comment by vitorgalvao** [comment]
When we install a cask, we keep a copy of it that will be used when uninstalling. This tends to be an issue when your local cask has old features no longer supported by HBC as a whole. It’s likely that’s what was happening here.

Closing in that case, but please do submit a new issue if you bump into this again.

**Comment by phdoerfler** [comment]
> When we install a cask, we keep a copy of it that will be used when uninstalling.

@vitorgalvao I had no idea, good to know! I usually run `brew cleanup` after upgrading everything and used to also run `brew cask cleanup` (which I assume got merged into `brew cleanup`) to free up space. Does that interfere with this mechanism you're describing?
