### ISSUE TITLE
failed to install virtualbox

### ISSUE THREAD

**Issue by lyang513** [Homebrew/homebrew-cask#51112]
#### General troubleshooting steps

- [ ] I have retried my command with `--force` and the issue is still present.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

brew failed to install virtualbox

#### Command that failed

brew cask install virtualbox

#### Output of command with `--force --verbose --debug`

```
brew cask install virtualbox --force --verbose --debug
Updating Homebrew...
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
To install and/or use virtualbox you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.virtualbox.org/virtualbox/5.2.18/VirtualBox-5.2.18-124319-OSX.dmg
Already downloaded: /Users/yanglin6/Library/Caches/Homebrew/Cask/virtualbox--5.2.18,124319.dmg
==> Downloaded to -> /Users/yanglin6/Library/Caches/Homebrew/Cask/virtualbox--5.2.18,124319.dmg
==> Verifying download
==> Determining which verifications to run for Cask virtualbox
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask virtualbox
==> SHA256 checksums match
==> Installing Cask virtualbox
==> Hbc::Installer#stage
hdiutil imageinfo /Users/yanglin6/Library/Caches/Homebrew/Cask/virtualbox--5.2.18,124319.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/yanglin6/Library/Caches/Homebrew/Cask/virtualbox--5.2.18,124319.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/r0/8nl7ft8j2l312q6lbgbnv6jh0000gn/T/d20180822-21652-fcyqqb /Users/yanglin6/Library/Caches/Homebrew/Cask/virtualbox--5.2.18,124319.dmg
find . -print0
mkbom -s -i /var/folders/r0/8nl7ft8j2l312q6lbgbnv6jh0000gn/T/20180822-21652-1xiwxcz.list -- /var/folders/r0/8nl7ft8j2l312q6lbgbnv6jh0000gn/T/20180822-21652-451h5d.bom
ditto --bom /var/folders/r0/8nl7ft8j2l312q6lbgbnv6jh0000gn/T/20180822-21652-451h5d.bom -- /private/var/folders/r0/8nl7ft8j2l312q6lbgbnv6jh0000gn/T/d20180822-21652-fcyqqb/dmg.ixCM69 /var/folders/r0/8nl7ft8j2l312q6lbgbnv6jh0000gn/T/d20180822-21652-1ega622
diskutil eject /private/var/folders/r0/8nl7ft8j2l312q6lbgbnv6jh0000gn/T/d20180822-21652-fcyqqb/dmg.ixCM69
cp -pR /var/folders/r0/8nl7ft8j2l312q6lbgbnv6jh0000gn/T/d20180822-21652-1ega622/VirtualBox.pkg /usr/local/Caskroom/virtualbox/5.2.18,124319/VirtualBox.pkg
cp -pR /var/folders/r0/8nl7ft8j2l312q6lbgbnv6jh0000gn/T/d20180822-21652-1ega622/VirtualBox_Uninstall.tool /usr/local/Caskroom/virtualbox/5.2.18,124319/VirtualBox_Uninstall.tool
cp -pR /var/folders/r0/8nl7ft8j2l312q6lbgbnv6jh0000gn/T/d20180822-21652-1ega622/UserManual.pdf /usr/local/Caskroom/virtualbox/5.2.18,124319/UserManual.pdf
==> Creating metadata directory /usr/local/Caskroom/virtualbox/.metadata/5.2.18,124319/20180822093723.904.
==> Creating metadata subdirectory /usr/local/Caskroom/virtualbox/.metadata/5.2.18,124319/20180822093723.904/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00007f8c401a3870>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=yanglin6 USER=yanglin6 USERNAME=yanglin6 /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/5.2.18,124319/VirtualBox.pkg -target / -verboseR
Password:
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%12.215071
installer:PHASE:Writing files…
installer:%39.590460
installer:PHASE:Writing files…
installer:%86.265026
installer:PHASE:Running package scripts…
installer:%87.316660
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 5.2.18,124319 of Cask virtualbox
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=yanglin6 USER=yanglin6 USERNAME=yanglin6 /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/5.2.18,124319/VirtualBox.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%12.215071
installer:PHASE:Writing files…
installer:%39.590460
installer:PHASE:Writing files…
installer:%86.265026
unless ENV["HOMEBREW_BREW_FILE"]
  raise "HOMEBREW_BREW_FILE was not exported! Please call bin/brew directly!"
end

std_trap = trap("INT") { exit! 130 } # no backtrace thanks

# check ruby version before requiring any modules.
RUBY_VERSION_SPLIT = RUBY_VERSION.split "."
RUBY_X = RUBY_VERSION_SPLIT[0].to_i
RUBY_Y = RUBY_VERSION_SPLIT[1].to_i
if RUBY_X < 2 || (RUBY_X == 2 && RUBY_Y < 3)
  raise "Homebrew must be run under Ruby 2.3! You're running #{RUBY_VERSION}."
end

require_relative "global"

begin
  trap("INT", std_trap) # restore default CTRL-C handler

  empty_argv = ARGV.empty?
  help_flag_list = %w[-h --help --usage -?]
  help_flag = !ENV["HOMEBREW_HELP"].nil?
  cmd = nil

  ARGV.dup.each_with_index do |arg, i|
    break if help_flag && cmd

    if arg == "help" && !cmd
      # Command-style help: `help <cmd>` is fine, but `<cmd> help` is not.
      help_flag = true
    elsif !cmd && !help_flag_list.include?(arg)
      cmd = ARGV.delete_at(i)
    end
  end

  path = PATH.new(ENV["PATH"])
  homebrew_path = PATH.new(ENV["HOMEBREW_PATH"])

  # Add SCM wrappers.
  path.append(HOMEBREW_SHIMS_PATH/"scm")
:87
installer:PHASE:Running package scripts…
installer:%87.316660
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:101:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:46:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:58:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:64:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:50:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:31:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:196:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:188:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.7.2-4-g713532e
Homebrew/homebrew-cask (git revision 8b6403; last commit 2018-08-21)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
10.0.2
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4029 casks)
/usr/local/Homebrew/Library/Taps/phinze/homebrew-cask (4029 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

homebrew/cask
homebrew/core
phinze/cask
```

**Comment by MindTooth** [comment]
Try giving a `brew cask zap virtualbox --force` first to remove any leftovers before trying to reinstall.  And did you run `brew update-reset && brew update` as described in the check list?

**Comment by vikas027** [comment]
Hello @MindTooth ,

I am too facing the same issue even after following your commands on OSX 10.13.6

```bash
  ~  brew cask install virtualbox
==> Caveats
To install and/or use virtualbox you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Satisfying dependencies
==> Downloading https://download.virtualbox.org/virtualbox/5.2.18/VirtualBox-5.2.18-124319-OSX.dmg
Already downloaded: /Users/vikas/Library/Caches/Homebrew/Cask/virtualbox--5.2.18,124319.dmg
==> Verifying checksum for Cask virtualbox
==> Installing Cask virtualbox
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 5.2.18,124319 of Cask virtualbox
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=vikas USER=vikas USERNAME=vikas /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/5.2.18,124319/VirtualBox.pkg -target /` exited with 1. Here's the output:
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:101:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:46:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:58:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:64:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:50:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:31:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:196:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:188:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
  ~ 
```

**Comment by MindTooth** [comment]
Just did a `zap` and rebooted.  Installed just fine.


Have you guys done anything to your environment, etc.?  Care to provide a `brew doctor` also?

**Comment by vikas027** [comment]
Hey @MindTooth ,

I had encountered that error while setting up a new laptop. Here is my `brew` configuration.

```bash
🍺  ~$ brew doctor
Your system is ready to brew.
🍺  ~$ brew config
HOMEBREW_VERSION: 1.7.2-18-gcc63c12
ORIGIN: https://github.com/Homebrew/brew
HEAD: cc63c1224727ea36c1599c0f211d02bf44c0bdfd
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 22a90d3a95fb4ec2cb5fcbb8e48144e0e10bc79d
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_VISUAL: /usr/local/bin/vim
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: N/A
XQuartz: N/A
🍺  ~$
```

Btw, every other brew installation is working perfectly, somehow only encountering issues with virtualbox.

**Comment by MindTooth** [comment]
Care to try to install it directly from [VirtualBox's homepage](https://www.virtualbox.org)?  Just to test whether it's the installer or Homebrew.

**Comment by vikas027** [comment]
Hey @MindTooth ,

Yeah, you are right. I also facing an error while trying to installing from a dmg file

![2018-08-30_20-12-26](https://user-images.githubusercontent.com/6998650/44845626-689aa200-ac91-11e8-8f97-9e01e55e648c.png)

**Comment by MindTooth** [comment]
May this [1] be of help?

[1] https://apple.stackexchange.com/questions/301303/virtualbox-5-1-28-fails-to-install-on-macos-10-13-due-to-kext-security

**Comment by vitorgalvao** [comment]
Closing as the issues is not related to HBC. But feel free to continue the discussion! Closing does not prevent further comments, but it will leave the repo a bit more tidy.
