### ISSUE TITLE
brew cask install bose-soundtouch fails with http error 403, forbidden.

### ISSUE THREAD

**Issue by iemwill** [Homebrew/homebrew-cask#51110]
#### Command that failed

```
brew cask install bose-soundtouch
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install --force --verbose --debug bose-soundtouch
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.bose.com/ced/soundtouch/mr1_2018_40489cb0/SoundTouch-app-installer-18.1.4-2009-4d9c32f.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.2-4-g713532e\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --silent --head --write-out \%\{redirect_url\} --output /dev/null https://downloads.bose.com/ced/soundtouch/mr1_2018_40489cb0/SoundTouch-app-installer-18.1.4-2009-4d9c32f.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.2-4-g713532e\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/willos/Library/Caches/Homebrew/Cask/bose-soundtouch--18.1.4-2009-4d9c32f,mr1_2018_40489cb0.dmg.incomplete https://downloads.bose.com/ced/soundtouch/mr1_2018_40489cb0/SoundTouch-app-installer-18.1.4-2009-4d9c32f.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
Error: Download failed on Cask 'bose-soundtouch' with message: Download failed: https://downloads.bose.com/ced/soundtouch/mr1_2018_40489cb0/SoundTouch-app-installer-18.1.4-2009-4d9c32f.dmg
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:39:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:35:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:15:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:140:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:57:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:161:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:161:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.7.2-4-g713532e
Homebrew/homebrew-cask (git revision 8b6403; last commit 2018-08-21)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
1.8.0_131
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4029 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (152 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
homebrew/cask
homebrew/cask-drivers
homebrew/core
```

**Comment by iemwill** [comment]
think the link needs to be the newest, like:
```
https://downloads.bose.com/ced/soundtouch/mr2_2018_32909916/SoundTouch-app-installer-18.1.4-2196-ef6eff6.dmg
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask-drivers/pull/496

**Comment by iemwill** [comment]
Perfect, haven't found #496 via search before.

But when will it be merged?

**Comment by vitorgalvao** [comment]
> haven't found #496 via search before.

It was made after your report.

> when will it be merged?

Now.
