### ISSUE TITLE
brew cask upgrade fails

### ISSUE THREAD

**Issue by uthark** [Homebrew/homebrew-cask#51220]
#### General troubleshooting steps

- [] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

{{replace this}}

#### Command that failed

```
brew cask upgrade
```

#### Output of command with `--force --verbose --debug`

```
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 4 outdated packages, with result:
java 10.0.2,13:19aef61b38124481863b1413dce1855f, minikube 0.28.2, vagrant 2.1.2, virtualbox 5.2.18,124319
==> Started upgrade process for Cask java
==> Printing caveats
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing java means you have AGREED to the license at
  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_osx-x64_bin.dmg
Already downloaded: /Local/Users/uthark/Library/Caches/Homebrew/Cask/java--10.0.2,13:19aef61b38124481863b1413dce1855f.dmg
==> Downloaded to -> /Local/Users/uthark/Library/Caches/Homebrew/Cask/java--10.0.2,13:19aef61b38124481863b1413dce1855f.dmg
==> Verifying download
==> Determining which verifications to run for Cask java
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask java
==> SHA256 checksums match
==> Starting upgrade for Cask java
==> Un-installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x00007f90880d1748>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for java; your password may be necessary
==> Removing launchctl service com.oracle.java.Helper-Tool
/bin/launchctl list com.oracle.java.Helper-Tool
/usr/bin/sudo -E -- /bin/launchctl list com.oracle.java.Helper-Tool
==> Removing launchctl service com.oracle.java.Java-Updater
/bin/launchctl list com.oracle.java.Java-Updater
/usr/bin/sudo -E -- /bin/launchctl list com.oracle.java.Java-Updater
==> Quitting application ID com.oracle.java.Java-Updater
/bin/launchctl list
==> Quitting application ID net.java.openjdk.cmd
/bin/launchctl list
==> Uninstalling packages:
/usr/sbin/pkgutil --pkgs=com.oracle.jdk-10.0.1
/usr/sbin/pkgutil --pkgs=com.oracle.jre
==> Removing files:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/PreferencePanes/JavaControlPanel.prefPane
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Java/Home
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Library/Java/MacOS
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
==> Removing directories if empty:
/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk
==> Un-installing artifact of class Hbc::Artifact::PostflightBlock
Error: No such file or directory @ rb_file_s_rename - (/usr/local/Caskroom/java/10.0.1,10:fb4372174a714e6b8c52526dc134031e, /usr/local/Caskroom/java/10.0.1,10:fb4372174a714e6b8c52526dc134031e.upgrading)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:412:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:412:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:412:in `backup'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:408:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:63:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:33:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.7.2
Homebrew/homebrew-cask (git revision 8e057; last commit 2018-08-23)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
9.0.4, 1.8.0_161
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4034 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1164 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
brew tap
buo/cask-upgrade
dart-lang/dart
go-delve/delve
homebrew/cask
homebrew/cask-fonts
homebrew/core
```

**Comment by vitorgalvao** [comment]
Try `brew cask reinstall --force java`, then `brew cask upgrade` again.

If that doesn’t work, do `rm -rf "$(brew --prefix)/Caskroom/java" ; brew reinstall java`, then `brew cask upgrade` again.
