### ISSUE TITLE
Unable to run brew cleanup after removing some applications

### ISSUE THREAD

**Issue by jgrim** [Homebrew/homebrew-cask#51234]
General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I was attempting to use Openconnect locally. When it failed I tried to remove all that I had done. I ran the following commands:

```
927  brew install openconnect && brew install Caskroom/cask/tuntap && brew cask install openconnect-gui
  928  brew cask reinstall openconnect-gui
  929  brew cask remove  openconnect-gui
  930  brew cleanup
  932  brew cask remove  openconnect-gui
  933  brew cleanup
  934  brew tap horar/openconnect-gui
  935  brew install openconnect-gui
  936  brew remove openconnect-gui
  937  brew remove -h
  938  brew untap horar/openconnect-gui
  939  brew remove openconnect && brew remove Caskroom/cask/tuntap
  940  brew remove untap
  941  brew install cask room/cask/tuntap
  942  brew install Caskroom/cask/tuntap
  943  brew cask remove tuntap
  944  brew cleanup
  945  brew doctor
  946  brew cask remove tuntap
  947  brew cleanup
  948  brew update
  949  ls /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask
  950  brew list
  951  brew cask -h
  952  brew cask audit
  953  brew cask doctor
  954  brew cleanup --force
  955  brew cask -h
  956  brew cask upgrade
  957  brew cask zap
  958  brew cask zap uptap
  960  brew update-reset && brew update
  961  brew cleanup
  962  brew doctor
  963  brew cleanup --force --verbose --debug
  964  brew cleanup --verbose --debug
  965  brew cleanup --debug
  966  brew cleanup
```

#### Command that failed

```
brew cleanup
```

#### Output of command with `--force --verbose --debug`

```
➜  ~ brew cleanup --force --verbose --debug
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cli_parser.rb:82:in `parse'
/usr/local/Homebrew/Library/Homebrew/cli_parser.rb:9:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:22:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
➜  ~ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.7.2-18-gcc63c12
Homebrew/homebrew-cask (git revision 044fe1e; last commit 2018-08-24)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Migrating tap caskroom/cask to homebrew/cask...
Changing remote from https://github.com/Homebrew/homebrew-cask to https://github.com/Homebrew/homebrew-cask...
Moving /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
Error: File exists - /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/homebrew-cask
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:523:in `block in mv'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1572:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1586:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1570:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:518:in `mv'
/usr/local/Homebrew/Library/Homebrew/compat/tap.rb:42:in `initialize'
/usr/local/Homebrew/Library/Homebrew/tap.rb:37:in `new'
/usr/local/Homebrew/Library/Homebrew/tap.rb:37:in `block in fetch'
/usr/local/Homebrew/Library/Homebrew/tap.rb:37:in `fetch'
/usr/local/Homebrew/Library/Homebrew/tap.rb:37:in `fetch'
/usr/local/Homebrew/Library/Homebrew/tap.rb:557:in `block (2 levels) in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:556:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:556:in `block in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:555:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:555:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/doctor.rb:73:in `select'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/doctor.rb:73:in `check_taps'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/doctor.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew tap`

```
➜  ~ brew tap
==> Migrating tap caskroom/cask to homebrew/cask...
Changing remote from https://github.com/Homebrew/homebrew-cask to https://github.com/Homebrew/homebrew-cask...
Moving /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
Error: File exists - /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/homebrew-cask
```

**Comment by jgrim** [comment]
I resolved it by running:
```
rm -rf /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask
