### ISSUE TITLE
unzip error when run "brew cask install prime95".

### ISSUE THREAD

**Issue by yenyolin** [Homebrew/homebrew-cask#51566]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I run `brew cask install prime95`, but it output unzip exited with 1.

#### Command that failed

```
brew cask install prime95
```

#### Output of command with `--force --verbose --debug`

```
fatpig:~ yenyolin$ brew cask --force --verbose --debug install prime95
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://www.mersenne.org/ftp_root/gimps/p95v294b7.MacOSX.zip
Already downloaded: /Users/yenyolin/Library/Caches/Homebrew/downloads/bfbc1dc990abe20a5801dc8183de6b53f498fdc66cc661641d354d047241709d--p95v294b7.MacOSX.zip
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/yenyolin/Library/Caches/Homebrew/downloads/bfbc1dc990abe20a5801dc8183de6b53f498fdc66cc661641d354d047241709d--p95v294b7.MacOSX.zip
/usr/bin/xattr -p com.apple.quarantine /Users/yenyolin/Library/Caches/Homebrew/downloads/bfbc1dc990abe20a5801dc8183de6b53f498fdc66cc661641d354d047241709d--p95v294b7.MacOSX.zip
==> /Users/yenyolin/Library/Caches/Homebrew/downloads/bfbc1dc990abe20a5801dc8183de6b53f498fdc66cc661641d354d047241709d--p95v294b7.MacOSX.zip is quarantined
==> Downloaded to -> /Users/yenyolin/Library/Caches/Homebrew/downloads/bfbc1dc990abe20a5801dc8183de6b53f498fdc66cc661641d354d047241709d--p95v294b7.MacOSX.zip
==> Verifying download
==> Determining which verifications to run for Cask prime95
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask prime95
==> SHA256 checksums match
==> Installing Cask prime95
==> Hbc::Installer#stage
zipinfo -1 /Users/yenyolin/Library/Caches/Homebrew/downloads/bfbc1dc990abe20a5801dc8183de6b53f498fdc66cc661641d354d047241709d--p95v294b7.MacOSX.zip
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/yenyolin/Library/Caches/Homebrew/downloads/bfbc1dc990abe20a5801dc8183de6b53f498fdc66cc661641d354d047241709d--p95v294b7.MacOSX.zip
unzip /Users/yenyolin/Library/Caches/Homebrew/downloads/bfbc1dc990abe20a5801dc8183de6b53f498fdc66cc661641d354d047241709d--p95v294b7.MacOSX.zip -d /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy
==> Purging files for version 29.4.b7 of Cask prime95
Error: Failure while executing; `unzip /Users/yenyolin/Library/Caches/Homebrew/downloads/bfbc1dc990abe20a5801dc8183de6b53f498fdc66cc661641d354d047241709d--p95v294b7.MacOSX.zip -d /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy` exited with 1. Here's the output:
Archive:  /Users/yenyolin/Library/Caches/Homebrew/downloads/bfbc1dc990abe20a5801dc8183de6b53f498fdc66cc661641d354d047241709d--p95v294b7.MacOSX.zip
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/license.txt  
Prime95.app/:  ucsize 102 <> csize 0 for STORED entry
         continuing with "compressed" size value
   creating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/
Prime95.app/Contents/:  ucsize 204 <> csize 0 for STORED entry
   creating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/
         continuing with "compressed" size value
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Info.plist  
Prime95.app/Contents/MacOS/:  ucsize 136 <> csize 0 for STORED entry
         continuing with "compressed" size value
   creating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/MacOS/
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/MacOS/libgmp.10.dylib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/MacOS/Prime95  
 extracting: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/PkgInfo  
Prime95.app/Contents/Resources/:  ucsize 816 <> csize 0 for STORED entry
         continuing with "compressed" size value
   creating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/About.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/Benchmark.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/Connection.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/Continue.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/CPU.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/ECM.nib  
Prime95.app/Contents/Resources/English.lproj/:  ucsize 136 <> csize 0 for STORED entry
   creating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/English.lproj/
         continuing with "compressed" size value
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/English.lproj/InfoPlist.strings  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/English.lproj/MainMenu.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/ManualCommunication.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/Mersenne.icns  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/Pminus1.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/Preferences.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/PrimeNet.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/PRP.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/QuitGIMPS.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/Status.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/Stop.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/Test.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/Time.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/TortureTest.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/Unreserve.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/Window.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/Prime95.app/Contents/Resources/WorkerWindows.nib  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/readme.txt  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/stress.txt  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/undoc.txt  
  inflating: /var/folders/kk/qhl3n5q90mx5twthkyzycq600000gn/T/d20180903-57447-56lpzy/whatsnew.txt  

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:101:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:46:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:16:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/zip.rb:19:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/unpack_strategy/zip.rb:5:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:119:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:126:in `block in extract_nestedly'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:123:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:185:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:75:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
fatpig:~ yenyolin$ 
```

#### Output of `brew cask doctor`

```
fatpig:~ yenyolin$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.7.2-116-g3b91c5f
Homebrew/homebrew-cask (git revision 73926; last commit 2018-09-02)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4045 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
fatpig:~ yenyolin$ 
```

#### Output of `brew tap`

```
fatpig:~ yenyolin$ brew tap
homebrew/cask
homebrew/core
fatpig:~ yenyolin$
```

**Comment by adidalal** [comment]
I can reproduce this issue. The app does not open.

`unzip` run manually throws up a warning, but continues:
```
[~/Downloads] > unzip p95v294b7.MacOSX.zip 
Archive:  p95v294b7.MacOSX.zip
  inflating: license.txt             
Prime95.app/:  ucsize 102 <> csize 0 for STORED entry
         continuing with "compressed" size value
   creating: Prime95.app/
Prime95.app/Contents/:  ucsize 204 <> csize 0 for STORED entry
         continuing with "compressed" size value
   creating: Prime95.app/Contents/
  inflating: Prime95.app/Contents/Info.plist  
Prime95.app/Contents/MacOS/:  ucsize 136 <> csize 0 for STORED entry
         continuing with "compressed" size value
   creating: Prime95.app/Contents/MacOS/
  inflating: Prime95.app/Contents/MacOS/libgmp.10.dylib  
  inflating: Prime95.app/Contents/MacOS/Prime95  
 extracting: Prime95.app/Contents/PkgInfo  
Prime95.app/Contents/Resources/:  ucsize 816 <> csize 0 for STORED entry
         continuing with "compressed" size value
   creating: Prime95.app/Contents/Resources/
  inflating: Prime95.app/Contents/Resources/About.nib  
  inflating: Prime95.app/Contents/Resources/Benchmark.nib  
  inflating: Prime95.app/Contents/Resources/Connection.nib  
  inflating: Prime95.app/Contents/Resources/Continue.nib  
  inflating: Prime95.app/Contents/Resources/CPU.nib  
  inflating: Prime95.app/Contents/Resources/ECM.nib  
Prime95.app/Contents/Resources/English.lproj/:  ucsize 136 <> csize 0 for STORED entry
         continuing with "compressed" size value
   creating: Prime95.app/Contents/Resources/English.lproj/
  inflating: Prime95.app/Contents/Resources/English.lproj/InfoPlist.strings  
  inflating: Prime95.app/Contents/Resources/English.lproj/MainMenu.nib  
  inflating: Prime95.app/Contents/Resources/ManualCommunication.nib  
  inflating: Prime95.app/Contents/Resources/Mersenne.icns  
  inflating: Prime95.app/Contents/Resources/Pminus1.nib  
  inflating: Prime95.app/Contents/Resources/Preferences.nib  
  inflating: Prime95.app/Contents/Resources/PrimeNet.nib  
  inflating: Prime95.app/Contents/Resources/PRP.nib  
  inflating: Prime95.app/Contents/Resources/QuitGIMPS.nib  
  inflating: Prime95.app/Contents/Resources/Status.nib  
  inflating: Prime95.app/Contents/Resources/Stop.nib  
  inflating: Prime95.app/Contents/Resources/Test.nib  
  inflating: Prime95.app/Contents/Resources/Time.nib  
  inflating: Prime95.app/Contents/Resources/TortureTest.nib  
  inflating: Prime95.app/Contents/Resources/Unreserve.nib  
  inflating: Prime95.app/Contents/Resources/Window.nib  
  inflating: Prime95.app/Contents/Resources/WorkerWindows.nib  
  inflating: readme.txt              
  inflating: stress.txt              
  inflating: undoc.txt               
  inflating: whatsnew.txt            
```

**Comment by vitorgalvao** [comment]
Seeing as this is an upstream bug and there seems to not be enough interest in the cask, going to remove it.
