### ISSUE TITLE
Adapter using unavailable url

### ISSUE THREAD

**Issue by edu-zamora** [Homebrew/homebrew-cask#51631]
#### Description of issue

When running `brew install homebrew/cask/adapter`, Adapter does not properly get installed, as the url being used returns a 503.

#### Command that failed

```
brew install homebrew/cask/adapter
```

#### Output of command with `--force --verbose --debug`

```
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.3\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head http://downloads.macroplant.com/Adapter-2.1.6.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.3\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head http://downloads.macroplant.com/Adapter-2.1.6.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.3\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/edu/Library/Caches/Homebrew/downloads/d49b49477409c11264c92f57f377b5768f08ea73539a720e27ff947b0b4412f8--Adapter-2.1.6.dmg.incomplete http://downloads.macroplant.com/Adapter-2.1.6.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 503 Service Unavailable
Error: Download failed on Cask 'adapter' with message: Download failed: http://downloads.macroplant.com/Adapter-2.1.6.dmg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:292:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:287:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:18:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:148:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:64:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:92:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:161:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:161:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

**Comment by vitorgalvao** [comment]
Next time, please fill **the whole template** and don’t delete parts of it.

**Comment by edu-zamora** [comment]
Thank you for the PR @vitorgalvao, and sorry for breaking the protocol (I thought the whole template was unnecessary for this)!

I'll know better for next time :)

**Comment by vitorgalvao** [comment]
> Thank you for the PR @vitorgalvao

Thank @miccal! I just merged it.

> I'll know better for next time :)

Thank you.

**Comment by edu-zamora** [comment]
Thank you @miccal! ;D
