### ISSUE TITLE
Vagrant fails on dependency

### ISSUE THREAD

**Issue by joedborg** [Homebrew/homebrew-cask#51632]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Latest Vagrant (2.4.1) cask installs fine but fails to run.  Error is:
```
/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/joe/.vagrant.d/gems/2.4.4/gems/nokogiri-1.8.2/lib/nokogiri/nokogiri.bundle, 9): Library not loaded: @rpath/libxml2.dylib (LoadError)
  Referenced from: /Users/joe/.vagrant.d/gems/2.4.4/gems/nokogiri-1.8.2/lib/nokogiri/nokogiri.bundle
  Reason: Incompatible library version: nokogiri.bundle requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0 - /Users/joe/.vagrant.d/gems/2.4.4/gems/nokogiri-1.8.2/lib/nokogiri/nokogiri.bundle
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/nokogiri-1.8.2/lib/nokogiri.rb:32:in `rescue in <top (required)>'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/nokogiri-1.8.2/lib/nokogiri.rb:28:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/fog-xml-0.1.3/lib/fog/xml.rb:2:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/fog-1.42.0/lib/fog.rb:13:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/vagrant-aws-0.7.2/lib/vagrant-aws/action/connect_aws.rb:1:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/vagrant-aws-0.7.2/lib/vagrant-aws/action.rb:97:in `block in action_read_state'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/vagrant-aws-0.7.2/lib/vagrant-aws/action.rb:95:in `tap'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/vagrant-aws-0.7.2/lib/vagrant-aws/action.rb:95:in `action_read_state'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/vagrant-aws-0.7.2/lib/vagrant-aws/provider.rb:16:in `action'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/machine.rb:196:in `block in action'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/machine.rb:190:in `block in action'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/machine.rb:194:in `action'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/vagrant-aws-0.7.2/lib/vagrant-aws/provider.rb:32:in `state'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/machine.rb:526:in `state'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/machine.rb:146:in `initialize'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/vagrantfile.rb:79:in `new'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/vagrantfile.rb:79:in `machine'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/environment.rb:719:in `machine'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/plugin/v2/command.rb:186:in `each'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/plugins/commands/up/command.rb:87:in `execute'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/cli.rb:54:in `execute'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/environment.rb:294:in `cli'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/bin/vagrant:164:in `<main>'
```

Have tried to force install of `vagrant` cask as well as `libxml2` and `libxslt`.

#### Command that failed

```
vagrant up
```

#### Output of command with `--force --verbose --debug`

N/A

#### Output of `brew cask doctor`

```
==> Homebrew Cask Version
Homebrew Cask 1.7.3-31-gf2cb0da
Homebrew/homebrew-cask (git revision 12255d; last commit 2018-09-05)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
N/A
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4045 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
datawire/blackbird
homebrew/cask
homebrew/cask-fonts
homebrew/core
```

**Comment by commitay** [comment]
You'll have to report this to `vagrant` upstream, all we do is install the `pkg`.

**Comment by joedborg** [comment]
FYI to anyone who comes across it: https://github.com/hashicorp/vagrant/issues/10176
