### ISSUE TITLE
Brew cu command stopped working

### ISSUE THREAD

**Issue by RobertFloor** [Homebrew/homebrew-cask#51679]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Very recently when I run "brew cu" it doesn't work anymore. It could have something to do with this: Pull Request #114 Rename module Hbc to Cask

#### Command that failed

```
brew cu
```

#### Output of command with `--force --verbose --debug`

```
brew cu --force --verbose --debug
Error: uninitialized constant Hbc
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:6:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:19:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew Version
1.7.3-59-g3d992db
==> macOS
10.13.6
==> SIP
Enabled
==> Java
10.0.2, 9.0.1, 9.0.0-zulu-9.0.1.3
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4047 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (151 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
buo/cask-upgrade
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/core
```

**Comment by vitorgalvao** [comment]
@RobertFloor Better yet, why are you still using that command? Do you realise we already have `upgrade` functionality?

**Comment by ylluminarious** [comment]
@vitorgalvao I faced the same issue and was not aware of `brew cask upgrade`. This basic functionality has been missing for a long time, and AFAIK, the addition of it was not announced anywhere for users to see. I am glad that this problem was finally fixed, but one cannot expect users to readily know about such a thing when it has been such a long-standing issue and its remedy was not proclaimed to users.

**Comment by vitorgalvao** [comment]
> AFAIK, the addition of it was not announced anywhere for users to see.

It was announced at least on the releases page and on the official twitter account multiple times, including discussions while it was being implemented.

We can’t make you follow our information channels, nor will we shove the information in your face after it’s added, but we do offer it.

> one cannot expect users to readily know about such a thing

I have no idea what you’re on about. I had no such expectation

Right after I replied to this issue I reiterated on the twitter account that we have `upgrade` functionality, went to the `cu` repo to open an issue about that, and later closed it to open a PR to clarify their outdated README.

All of this is public and you can verify it for yourself. I’m not linking you because I’m on a phone. But if there’s something that you can’t fairly accuse us of, if of not trying to inform users about `upgrade`. We do. If a user *only* uses the software and never participates on the issue tracker or other public channels, there’s only so much we can do.

**Comment by ylluminarious** [comment]
@vitorgalvao Sorry, I was not aware of all the chatter around this change. I'm not "on about" anything. I just thought perhaps you should recognize that @RobertFloor was not aware of the change since some people (including myself) are not involved in this project's development. No need to be upset.

**Comment by vitorgalvao** [comment]
> No need to be upset.

I’m not. Why are you assuming I am?

> just thought perhaps you should recognize that @RobertFloor was not aware of the change

I do! Again, why are you assuming hidden meaning in my words? I asked @RobertFloor two questions:

1. Why was he still using `cu`. Examples of valid answers: “because I didn’t know an alternative existed”; “because I like their output better”.
2. If he was aware we already support `upgrade`. Examples of valid answers: “yes”; “no”.

My questions were not rhetorical. They were clear and direct questions asked to get relevant information.
