### ISSUE TITLE
Installing simplenote errors out.

### ISSUE THREAD

**Issue by diegodesouza** [Homebrew/homebrew-cask#51691]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [?] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x ] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I am trying to install simple note in my machine. I am running macOS High Sierra `version 10.13.6`

```
➜  ~ brew --version
Homebrew 1.7.3
Homebrew/homebrew-core (git revision f6e8; last commit 2018-09-06)
```

I have tried uninstalling brew completely and re-installing it. I have tried changing the the path of my `HOMEBREW_CASK_OPTS ` based on [this](https://github.com/Homebrew/homebrew-cask/blob/1de4657a0ed35463602b31061b0c16dc9078b8a0/USAGE.md#options) with no luck.

#### Command that failed

```
➜  ~ brew cask install simplenote
==> Satisfying dependencies
==> Downloading https://github.com/Automattic/simplenote-electron/releases/download/v1.1.7/Simplenote.app.1.1.7.zip
Already downloaded: /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip
==> Verifying checksum for Cask simplenote
==> Installing Cask simplenote
==> Purging files for version 1.1.7 of Cask simplenote
Error: Failed to quarantine one or more files within /usr/local/Caskroom/simplenote/1.1.7. Here's the reason:
xattr: [Errno 13] Permission denied: '/usr/local/Caskroom/simplenote/1.1.7/Simplenote.app/Contents/Resources/app/node_modules/.cache/uglifyjs-webpack-plugin/content-v2/sha512/d5/f4/79ab5925076cd55a1805abb9a7cce4f6938e78db5521e09ac94c59aa454a8501e643f106576a1478dc3ca0ec3734352cb534e54ad2ceef40ec09fd683ce0'
xattr: [Errno 13] Permission denied: '/usr/local/Caskroom/simplenote/1.1.7/Simplenote.app/Contents/Resources/app/node_modules/.cache/uglifyjs-webpack-plugin/content-v2/sha512/f7/1c/310271bda5a06acbb89f930aaeda6bbc73336085c18b109ee8d12b5e5610c01fb30a859c3490b4373696bf19f4cc546731b48999579949e9a1b7f8fcaa33'
```

#### Output of command with `--force --verbose --debug`

```
➜  ~ brew cask install simplenote --force --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://github.com/Automattic/simplenote-electron/releases/download/v1.1.7/Simplenote.app.1.1.7.zip
Already downloaded: /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip
/usr/bin/xattr -p com.apple.quarantine /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip
==> /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip is quarantined
==> Downloaded to -> /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip
==> Verifying download
==> Determining which verifications to run for Cask simplenote
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask simplenote
==> SHA256 checksums match
==> Installing Cask simplenote
==> Hbc::Installer#stage
zipinfo -1 /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip
unzip /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip -d /var/folders/pq/339syw6j7jsft5xx8g25jq9c0000gn/T/d20180906-40729-xsewtx
cp -pR /var/folders/pq/339syw6j7jsft5xx8g25jq9c0000gn/T/d20180906-40729-xsewtx/Simplenote.app/. /usr/local/Caskroom/simplenote/1.1.7/Simplenote.app
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip
/usr/bin/xattr -p com.apple.quarantine /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip
==> /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip is quarantined
==> Propagating quarantine from /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip to /usr/local/Caskroom/simplenote/1.1.7
/usr/bin/xattr -p com.apple.quarantine /Users/diegodesouza/Library/Caches/Homebrew/downloads/4fb9d9e73ce1cb4c318d905ac0b6ad403c13831c8ba67bf37ee0cbd2a8892dd3--Simplenote.app.1.1.7.zip
/usr/bin/xattr -w -rs com.apple.quarantine 0081\;5b91511d\;Homebrew-Cask\;9035A6AF-C092-46DD-833B-666C10A878CB /usr/local/Caskroom/simplenote/1.1.7
==> Purging files for version 1.1.7 of Cask simplenote
Error: Failed to quarantine one or more files within /usr/local/Caskroom/simplenote/1.1.7. Here's the reason:
xattr: [Errno 13] Permission denied: '/usr/local/Caskroom/simplenote/1.1.7/Simplenote.app/Contents/Resources/app/node_modules/.cache/uglifyjs-webpack-plugin/content-v2/sha512/d5/f4/79ab5925076cd55a1805abb9a7cce4f6938e78db5521e09ac94c59aa454a8501e643f106576a1478dc3ca0ec3734352cb534e54ad2ceef40ec09fd683ce0'
xattr: [Errno 13] Permission denied: '/usr/local/Caskroom/simplenote/1.1.7/Simplenote.app/Contents/Resources/app/node_modules/.cache/uglifyjs-webpack-plugin/content-v2/sha512/f7/1c/310271bda5a06acbb89f930aaeda6bbc73336085c18b109ee8d12b5e5610c01fb30a859c3490b4373696bf19f4cc546731b48999579949e9a1b7f8fcaa33'

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/quarantine.rb:77:in `propagate'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:75:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:161:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:161:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
➜  ~ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.7.3
Homebrew/homebrew-cask (git revision 4739; last commit 2018-09-06)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
1.8.0_162
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4047 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
➜  ~ brew tap
homebrew/cask
homebrew/core
```

**Comment by vitorgalvao** [comment]
We need `brew cask doctor`, not `brew doctor`.

**Comment by diegodesouza** [comment]
@vitorgalvao I have updated that info
