### ISSUE TITLE
'brew install Caskroom/versions/java6' fails with numerous quarantine errors

### ISSUE THREAD

**Issue by dcommander** [Homebrew/homebrew-cask#51706]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`brew install Caskroom/versions/java6` fails with numerous quarantine errors.  This issue started occurring a bit over a week ago and was first noticed in the Travis build of libjpeg-turbo, which needs Java for OS X in order to test its Java interface with the macOS i386 architecture (Oracle Java does not provide a 32-bit JVM.)  This issue also exists with LibreOffice, apparently, and was filed as #51536 but closed because the issue was not reported in the correct format.  The issue also occurs when running `brew cask doctor`, which leads me to believe that it is a Homebrew bug.

#### Command that failed

```
brew install Caskroom/versions/java6
```

#### Output of command with `--force --verbose --debug`

```
Updating Homebrew...
==> brew cask install Caskroom/versions/java6 --force --debug --verbose
/usr/local/bin/brew cask install Caskroom/versions/java6 --force --debug --verbose
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://support.apple.com/downloads/DL1572/en_US/javaforosx.dmg
Already downloaded: /Volumes/Fezzik/Users/drc/Library/Caches/Homebrew/downloads/ef0dff3db9496248774373eb3eba27a50a91e83edda3fe32d2197db15a5ffc69--javaforosx.dmg
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:7:23: warning: extraneous '_' in parameter: 'string' has no keyword argument name
  mutating func write(_ string: String) { fputs(string, stderr) }
                      ^~
                      
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:10:26: error: unrecognized platform name 'macOS'
if #available(macOS 10.10, *) {
                         ^
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:5:18: error: use of undeclared type 'TextOutputStream'
struct swifterr: TextOutputStream {
                 ^~~~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:6:3: warning: declaring a public static var for an internal struct
  public static var stream = swifterr()
  ^~~~~~
  internal
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:11:7: error: use of unresolved identifier 'CommandLine'
  if (CommandLine.arguments.count < 4) {
      ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:15:60: error: use of unresolved identifier 'CommandLine'
  let dataLocationUrl: NSURL = NSURL.init(fileURLWithPath: CommandLine.arguments[1])
                                                           ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:22:40: error: use of unresolved identifier 'CommandLine'
    kLSQuarantineDataURLKey as String: CommandLine.arguments[2],
                                       ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:23:42: error: use of unresolved identifier 'CommandLine'
    kLSQuarantineOriginURLKey as String: CommandLine.arguments[3]
                                         ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:30:17: error: use of unresolved identifier 'URLResourceKey'
        forKey: URLResourceKey.quarantinePropertiesKey
                ^~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:34:13: error: value of type 'ErrorType' has no member 'localizedDescription'
      print(error.localizedDescription, to: &swifterr.stream)
            ^~~~~ ~~~~~~~~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:39:5: error: argument labels '(_:, to:)' do not match any available overloads
    print(errorBag!.localizedDescription, to: &swifterr.stream)
    ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:39:5: note: overloads for 'print' exist with these partially matching parameter lists: (Any..., separator: String, terminator: String), (T, appendNewline: Bool), (T, inout OutputStreamType)
    print(errorBag!.localizedDescription, to: &swifterr.stream)
    ^
==> Quarantine is available.
==> Verifying Gatekeeper status of /Volumes/Fezzik/Users/drc/Library/Caches/Homebrew/downloads/ef0dff3db9496248774373eb3eba27a50a91e83edda3fe32d2197db15a5ffc69--javaforosx.dmg
/usr/bin/xattr -p com.apple.quarantine /Volumes/Fezzik/Users/drc/Library/Caches/Homebrew/downloads/ef0dff3db9496248774373eb3eba27a50a91e83edda3fe32d2197db15a5ffc69--javaforosx.dmg
==> /Volumes/Fezzik/Users/drc/Library/Caches/Homebrew/downloads/ef0dff3db9496248774373eb3eba27a50a91e83edda3fe32d2197db15a5ffc69--javaforosx.dmg is not quarantined
==> Quarantining /Volumes/Fezzik/Users/drc/Library/Caches/Homebrew/downloads/ef0dff3db9496248774373eb3eba27a50a91e83edda3fe32d2197db15a5ffc69--javaforosx.dmg
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Volumes/Fezzik/Users/drc/Library/Caches/Homebrew/downloads/ef0dff3db9496248774373eb3eba27a50a91e83edda3fe32d2197db15a5ffc69--javaforosx.dmg https://support.apple.com/downloads/DL1572/en_US/javaforosx.dmg https://support.apple.com/kb/DL1572
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:7:23: warning: extraneous '_' in parameter: 'string' has no keyword argument name
  mutating func write(_ string: String) { fputs(string, stderr) }
                      ^~
                      
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:10:26: error: unrecognized platform name 'macOS'
if #available(macOS 10.10, *) {
                         ^
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:5:18: error: use of undeclared type 'TextOutputStream'
struct swifterr: TextOutputStream {
                 ^~~~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:6:3: warning: declaring a public static var for an internal struct
  public static var stream = swifterr()
  ^~~~~~
  internal
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:11:7: error: use of unresolved identifier 'CommandLine'
  if (CommandLine.arguments.count < 4) {
      ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:15:60: error: use of unresolved identifier 'CommandLine'
  let dataLocationUrl: NSURL = NSURL.init(fileURLWithPath: CommandLine.arguments[1])
                                                           ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:22:40: error: use of unresolved identifier 'CommandLine'
    kLSQuarantineDataURLKey as String: CommandLine.arguments[2],
                                       ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:23:42: error: use of unresolved identifier 'CommandLine'
    kLSQuarantineOriginURLKey as String: CommandLine.arguments[3]
                                         ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:30:17: error: use of unresolved identifier 'URLResourceKey'
        forKey: URLResourceKey.quarantinePropertiesKey
                ^~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:34:13: error: value of type 'ErrorType' has no member 'localizedDescription'
      print(error.localizedDescription, to: &swifterr.stream)
            ^~~~~ ~~~~~~~~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:39:5: error: argument labels '(_:, to:)' do not match any available overloads
    print(errorBag!.localizedDescription, to: &swifterr.stream)
    ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:39:5: note: overloads for 'print' exist with these partially matching parameter lists: (Any..., separator: String, terminator: String), (T, appendNewline: Bool), (T, inout OutputStreamType)
    print(errorBag!.localizedDescription, to: &swifterr.stream)
    ^
Error: Failed to quarantine /Volumes/Fezzik/Users/drc/Library/Caches/Homebrew/downloads/ef0dff3db9496248774373eb3eba27a50a91e83edda3fe32d2197db15a5ffc69--javaforosx.dmg. Here's the reason:
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:7:23: warning: extraneous '_' in parameter: 'string' has no keyword argument name
  mutating func write(_ string: String) { fputs(string, stderr) }
                      ^~
                      
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:10:26: error: unrecognized platform name 'macOS'
if #available(macOS 10.10, *) {
                         ^
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:5:18: error: use of undeclared type 'TextOutputStream'
struct swifterr: TextOutputStream {
                 ^~~~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:6:3: warning: declaring a public static var for an internal struct
  public static var stream = swifterr()
  ^~~~~~
  internal
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:11:7: error: use of unresolved identifier 'CommandLine'
  if (CommandLine.arguments.count < 4) {
      ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:15:60: error: use of unresolved identifier 'CommandLine'
  let dataLocationUrl: NSURL = NSURL.init(fileURLWithPath: CommandLine.arguments[1])
                                                           ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:22:40: error: use of unresolved identifier 'CommandLine'
    kLSQuarantineDataURLKey as String: CommandLine.arguments[2],
                                       ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:23:42: error: use of unresolved identifier 'CommandLine'
    kLSQuarantineOriginURLKey as String: CommandLine.arguments[3]
                                         ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:30:17: error: use of unresolved identifier 'URLResourceKey'
        forKey: URLResourceKey.quarantinePropertiesKey
                ^~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:34:13: error: value of type 'ErrorType' has no member 'localizedDescription'
      print(error.localizedDescription, to: &swifterr.stream)
            ^~~~~ ~~~~~~~~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:39:5: error: argument labels '(_:, to:)' do not match any available overloads
    print(errorBag!.localizedDescription, to: &swifterr.stream)
    ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:39:5: note: overloads for 'print' exist with these partially matching parameter lists: (Any..., separator: String, terminator: String), (T, appendNewline: Bool), (T, inout OutputStreamType)
    print(errorBag!.localizedDescription, to: &swifterr.stream)
    ^

/usr/local/Homebrew/Library/Homebrew/cask/quarantine.rb:77:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:53:in `quarantine'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:19:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:146:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.3-79-gcb2cf65
==> macOS
10.11.6
==> SIP
Enabled
==> Java
10.0.1, 9.0.4, 1.8.0_141, 1.6.0_65-b14-462
==> Gatekeeper support
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:7:23: warning: extraneous '_' in parameter: 'string' has no keyword argument name
  mutating func write(_ string: String) { fputs(string, stderr) }
                      ^~
                      
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:10:26: error: unrecognized platform name 'macOS'
if #available(macOS 10.10, *) {
                         ^
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:5:18: error: use of undeclared type 'TextOutputStream'
struct swifterr: TextOutputStream {
                 ^~~~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:6:3: warning: declaring a public static var for an internal struct
  public static var stream = swifterr()
  ^~~~~~
  internal
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:11:7: error: use of unresolved identifier 'CommandLine'
  if (CommandLine.arguments.count < 4) {
      ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:15:60: error: use of unresolved identifier 'CommandLine'
  let dataLocationUrl: NSURL = NSURL.init(fileURLWithPath: CommandLine.arguments[1])
                                                           ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:22:40: error: use of unresolved identifier 'CommandLine'
    kLSQuarantineDataURLKey as String: CommandLine.arguments[2],
                                       ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:23:42: error: use of unresolved identifier 'CommandLine'
    kLSQuarantineOriginURLKey as String: CommandLine.arguments[3]
                                         ^~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:30:17: error: use of unresolved identifier 'URLResourceKey'
        forKey: URLResourceKey.quarantinePropertiesKey
                ^~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:34:13: error: value of type 'ErrorType' has no member 'localizedDescription'
      print(error.localizedDescription, to: &swifterr.stream)
            ^~~~~ ~~~~~~~~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:39:5: error: argument labels '(_:, to:)' do not match any available overloads
    print(errorBag!.localizedDescription, to: &swifterr.stream)
    ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift:39:5: note: overloads for 'print' exist with these partially matching parameter lists: (Any..., separator: String, terminator: String), (T, appendNewline: Bool), (T, inout OutputStreamType)
    print(errorBag!.localizedDescription, to: &swifterr.stream)
    ^
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Migrating tap caskroom/versions to homebrew/cask-versions...
Changing remote from https://github.com/Caskroom/homebrew-versions to https://github.com/Homebrew/homebrew-cask-versions...
Moving /usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions...
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4046 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (195 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (195 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by vitorgalvao** [comment]
Please search before opening an issue (like the template asks you to). There are multiple issues on quarantining. We’re working on it.

**Comment by dcommander** [comment]
I did not find any issues that described the same symptoms, except for the aforementioned issue that was closed.  Please do not assume that the rest of the world is stupid just because they can't read your mind.

**Comment by vitorgalvao** [comment]
> Please do not assume that the rest of the world is stupid just because they can't read your mind.

1. I did not take a tone with you, so I appreciate you extend the same courtesy with me.
2. I did not call you stupid (or any other name) nor have I implied anything regarding your intelligence. People ignore the template all the time; that’s a way fairer assumption.
3. The request is *written* right there. Nobody asked you to read minds, you were asked to read instructions.

I’m not in the habit of insulting users (or anyone) so please don’t assume that. My request was reasonable, and while it may have been rushed it was not disrespectful.

**Comment by dcommander** [comment]
I *did* read instructions.  I searched for the specific error message I was receiving and got only one hit, the aforementioned issue that was closed for not being in the correct format.  I guess you expected me to trawl through the 30 issues that match "quarantine" and figure out whether any of those are the same issue, even though they have different symptoms?  How would you feel if you submitted an issue against libjpeg-turbo, my product, and I asked you to do likewise?

When people *follow your rules* and are still summarily dismissed, it makes them extremely disinclined to help you in the future.  I solely maintain the most popular JPEG library in the world, a library that you are in fact distributing in your product (to which I give *free advertising* on my web page.)  You think I don't get uninformed questions all the time?  But I certainly don't treat my users like you treated me.

Good day.

**Comment by vitorgalvao** [comment]
> I solely maintain the most popular JPEG library in the world

Thank you for your work. **Genuinely**.

> a library that you are in fact distributing in your product

For the benefit of our users, not our personal gain.

> to which I give *free advertising* on my web page.

It’s not like we’re making money out of working on Homebrew Cask, so I don’t get why that’s relevant. And I’ll assume a good chunk of your users also like that your software is distributed via Homebrew. You as well are using this software free of charge. It’s not like you’re getting the bad end of a deal, or something, nobody is leeching off of anybody.

> You think I don't get uninformed questions all the time?

No, I don’t think that. Once again, please don’t put words in my mouth.

> How would you feel if you submitted an issue against libjpeg-turbo, my product, and I asked you to do likewise?

I would have read the answer as I wrote it and assumed good intentions (which I always do). I’d ask for further clarification if I needed it, or not if I didn’t. Maybe I’d ask for a specific issue to track.

> But I certainly don't treat my users like you treated me.

I’ll reiterate I wasn’t disrespectful to you. Abrupt, maybe, but I haven’t insulted you in any way, and I have no idea why you’re mad.

*I didn’t even ignore your issue*. I asked you for something and ended with “we’re working on it”. That means “we’re aware of this problem and working on the fix, I’m closing as it’s being tracked somewhere else”. I’m not out to get you, and at no point in this interaction have I wished the slightest harm on you or tried to get you angry.

> Good day.

Too you as well. I hope our interaction hasn’t soiled your day. If you don’t mind, for both our sakes, I’ll lock the issue as resolved. Have a great weekend, and again thank you for working on a useful and liked piece of open-source.
