### ISSUE TITLE
Issue with Swift in OSX 10.12

### ISSUE THREAD

**Issue by Fohlen** [Homebrew/homebrew-cask#51787]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I am having a problem installing any casks that include `.dmg` files. Apparently this has to do with the native MACOSX SDK.
When I try to install a `.dmg` with brew I get a weird issue which I couldn't make any sense of either with extensive googling.

#### Command that failed

```
 ~/w/imgag  brew cask install qt-creator
==> Satisfying dependencies
==> Downloading http://download.qt.io/official_releases/qtcreator/4.7/4.7.0/qt-creator-opensource-mac-x86_64-4.7.0.dmg
Already downloaded: /Users/fohlen/Library/Caches/Homebrew/downloads/d68e5b47cfd65e43d9d3b849b1aaec14c0b90e7b76e4ff97a7fa213409a1cca1--qt-creator-opensource-mac-x86_64-4.7.0.dmg
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'
Error: Failed to quarantine /Users/fohlen/Library/Caches/Homebrew/downloads/d68e5b47cfd65e43d9d3b849b1aaec14c0b90e7b76e4ff97a7fa213409a1cca1--qt-creator-opensource-mac-x86_64-4.7.0.dmg. Here's the reason:
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://download.qt.io/official_releases/qtcreator/4.7/4.7.0/qt-creator-opensource-mac-x86_64-4.7.0.dmg
Already downloaded: /Users/fohlen/Library/Caches/Homebrew/downloads/d68e5b47cfd65e43d9d3b849b1aaec14c0b90e7b76e4ff97a7fa213409a1cca1--qt-creator-opensource-mac-x86_64-4.7.0.dmg
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/fohlen/Library/Caches/Homebrew/downloads/d68e5b47cfd65e43d9d3b849b1aaec14c0b90e7b76e4ff97a7fa213409a1cca1--qt-creator-opensource-mac-x86_64-4.7.0.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/fohlen/Library/Caches/Homebrew/downloads/d68e5b47cfd65e43d9d3b849b1aaec14c0b90e7b76e4ff97a7fa213409a1cca1--qt-creator-opensource-mac-x86_64-4.7.0.dmg
==> /Users/fohlen/Library/Caches/Homebrew/downloads/d68e5b47cfd65e43d9d3b849b1aaec14c0b90e7b76e4ff97a7fa213409a1cca1--qt-creator-opensource-mac-x86_64-4.7.0.dmg is not quarantined
==> Quarantining /Users/fohlen/Library/Caches/Homebrew/downloads/d68e5b47cfd65e43d9d3b849b1aaec14c0b90e7b76e4ff97a7fa213409a1cca1--qt-creator-opensource-mac-x86_64-4.7.0.dmg
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/fohlen/Library/Caches/Homebrew/downloads/d68e5b47cfd65e43d9d3b849b1aaec14c0b90e7b76e4ff97a7fa213409a1cca1--qt-creator-opensource-mac-x86_64-4.7.0.dmg http://download.qt.io/official_releases/qtcreator/4.7/4.7.0/qt-creator-opensource-mac-x86_64-4.7.0.dmg https://www1.qt.io/developers/
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'
Error: Failed to quarantine /Users/fohlen/Library/Caches/Homebrew/downloads/d68e5b47cfd65e43d9d3b849b1aaec14c0b90e7b76e4ff97a7fa213409a1cca1--qt-creator-opensource-mac-x86_64-4.7.0.dmg. Here's the reason:
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'

/usr/local/Homebrew/Library/Homebrew/cask/quarantine.rb:109:in `cask!'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:53:in `quarantine'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:19:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:146:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.3-102-g88e69f5
==> macOS
10.13.6
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4051 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/fish"
```

#### Output of `brew tap`

```
 ~/w/imgag  brew tap
homebrew/cask
homebrew/core
```

**Comment by vitorgalvao** [comment]
This has to do with the quarantining feature we’re reverting. For now, install with the `--no-quarantine` flag. This’ll be fixed with the next Homebrew release.
