### ISSUE TITLE
Error: Failed to quarantine: Swift does not support the SDK 'MacOSX10.12.sdk'

### ISSUE THREAD

**Issue by nickv2002** [Homebrew/homebrew-cask#51872]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

All zip files downloaded with `brew cask` are failing to install with the message:
```
Error: Failed to quarantine /path/to/file.zip. Here's the reason:
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'
```

#### Command that failed
All these fail with the same error
```
brew cask install coda
brew cask install mactracker
brew cask install the-unarchiver
```

#### Output of command with `--force --verbose --debug`

```
brew cask install the-unarchiver --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.devmate.com/com.macpaw.site.theunarchiver/120/1528909123/TheUnarchiver-120.zip
Already downloaded: /Users/nvance/Library/Caches/Homebrew/downloads/98453ef0dc4dc918d1a0e54e78e8c9f4aa8da4333252dd7835ad00af587e9426--TheUnarchiver-120.zip
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/nvance/Library/Caches/Homebrew/downloads/98453ef0dc4dc918d1a0e54e78e8c9f4aa8da4333252dd7835ad00af587e9426--TheUnarchiver-120.zip
/usr/bin/xattr -p com.apple.quarantine /Users/nvance/Library/Caches/Homebrew/downloads/98453ef0dc4dc918d1a0e54e78e8c9f4aa8da4333252dd7835ad00af587e9426--TheUnarchiver-120.zip
==> /Users/nvance/Library/Caches/Homebrew/downloads/98453ef0dc4dc918d1a0e54e78e8c9f4aa8da4333252dd7835ad00af587e9426--TheUnarchiver-120.zip is not quarantined
==> Quarantining /Users/nvance/Library/Caches/Homebrew/downloads/98453ef0dc4dc918d1a0e54e78e8c9f4aa8da4333252dd7835ad00af587e9426--TheUnarchiver-120.zip
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/nvance/Library/Caches/Homebrew/downloads/98453ef0dc4dc918d1a0e54e78e8c9f4aa8da4333252dd7835ad00af587e9426--TheUnarchiver-120.zip https://dl.devmate.com/com.macpaw.site.theunarchiver/120/1528909123/TheUnarchiver-120.zip https://theunarchiver.com/
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'
Error: Failed to quarantine /Users/nvance/Library/Caches/Homebrew/downloads/98453ef0dc4dc918d1a0e54e78e8c9f4aa8da4333252dd7835ad00af587e9426--TheUnarchiver-120.zip. Here's the reason:
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'

/usr/local/Homebrew/Library/Homebrew/cask/quarantine.rb:109:in `cask!'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:53:in `quarantine'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:19:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:146:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.4-26-ga37d46f
==> macOS
10.13.6
==> SIP
Enabled
==> Java
1.8.0_181, 1.8.0_172, 1.8.0_162, 1.8.0_121, 1.8.0_72, 1.8.0_40, 1.8.0_25, 1.8.0_05, 1.7.0_51
==> Gatekeeper support
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4052 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1175 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (151 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/core
homebrew/services
```

**Comment by nickv2002** [comment]
Looks like it's the same issue [as this](https://github.com/Homebrew/homebrew-cask/issues/51787) so I'm closing for now as it's a feature in development.
