### ISSUE TITLE
`brew cask edit $cask_name` doesn't work if $cask_name has syntax errors

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-cask#51907]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
If there is syntax error in cask, then `brew cask edit` doesn't work. In my case it was missing coma in `zap delete:` array.
#### Command that failed

```
brew cask edit cappuccino-beta
```

#### Output of command with `--force --verbose --debug`
`--force` is not available for `edit`
```
$ brew cask edit cappuccino-beta --verbose --debug
Warning: Cask 'cappuccino-beta' is unreadable: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/cappuccino-beta.rb:14: syntax error, unexpected tSTRING_BEG, expecting ']'
  				"~/Library/Application Scripts/it.nebula.cappuccino.beta",
  				 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/cappuccino-beta.rb:14: syntax error, unexpected ',', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/cappuccino-beta.rb:15: syntax error, unexpected ',', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/cappuccino-beta.rb:17: syntax error, unexpected ',', expecting keyword_end
Error: Cask 'cappuccino-beta' is unreadable: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/cappuccino-beta.rb:14: syntax error, unexpected tSTRING_BEG, expecting ']'
  				"~/Library/Application Scripts/it.nebula.cappuccino.beta",
  				 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/cappuccino-beta.rb:14: syntax error, unexpected ',', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/cappuccino-beta.rb:15: syntax error, unexpected ',', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/cappuccino-beta.rb:17: syntax error, unexpected ',', expecting keyword_end Run brew cask create cappuccino-beta to create a new Cask.
/usr/local/Homebrew/Library/Homebrew/cask/cmd/edit.rb:15:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/edit.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew Version
1.7.4-43-g1b45666
==> macOS
10.14
==> SIP
Enabled (custom configuration)

configuration:
apple internal: disabled
kext signing: disabled
filesystem protections: disabled
debugging restrictions: disabled
dtrace restrictions: disabled
nvram protections: disabled
basesystem verification: disabled
==> Java
10.0.2
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4053 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (196 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-eid (11 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1175 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (151 casks)
/usr/local/Homebrew/Library/Taps/yurikoles/homebrew-yurikoles (5 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

buo/cask-upgrade
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/command-not-found
homebrew/core
homebrew/livecheck
homebrew/services
jeffreywildman/virt-manager
kde-mac/kde
theseal/ssh-askpass
vitorgalvao/tiny-scripts
yurikoles/yurikoles
```

**Comment by vitorgalvao** [comment]
I thought we already had an issue for this, but apparently not (can’t find any).

Agreed. If a cask exists, `brew cask edit` should always work.
