### ISSUE TITLE
brew cask install yourkit-java-profiler maps to wrong version: http 404

### ISSUE THREAD

**Issue by marcottedan** [Homebrew/homebrew-cask#51912]
#### Description of issue

The yourkit-java-profiler artifacts ends up downloading a version that Yourkit removed on their website. It reaches a 404. The latest version seems to be https://www.yourkit.com/download/YourKit-JavaProfiler-2018.04-b83.dmg

Instead of https://www.yourkit.com/download/YourKit-JavaProfiler-2018.04-b81.dmg

#### Command that failed

```
brew cask install yourkit-java-profiler
```

#### Output of command with `--force --verbose --debug`

```
brew cask install yourkit-java-profiler --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://www.yourkit.com/download/YourKit-JavaProfiler-2018.04-b81.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.4\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://www.yourkit.com/download/YourKit-JavaProfiler-2018.04-b81.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.4\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://www.yourkit.com/download/YourKit-JavaProfiler-2018.04-b81.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.4\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/Daniel.Marcotte/Library/Caches/Homebrew/downloads/9d665d7b643b0e36590e55c005333705eabd7fc8b47bbeb1f6916f8b2e029127--YourKit-JavaProfiler-2018.04-b81.dmg.incomplete https://www.yourkit.com/download/YourKit-JavaProfiler-2018.04-b81.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'yourkit-java-profiler' with message: Download failed: https://www.yourkit.com/download/YourKit-JavaProfiler-2018.04-b81.dmg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:292:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:287:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:18:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:146:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew Version
1.7.4
==> macOS
10.13.6
==> SIP
Enabled
==> Java
1.8.0_181
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4053 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (195 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
brew tap
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
git-cola                                                                   glm

homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
tm/homebrew
```

**Comment by vitorgalvao** [comment]
Thank you for the report and providing the new version. Fixing in #51918.
