### ISSUE TITLE
cask install is broken with Xcode 10 GM/Mojave Beta 11

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-cask#51958]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Can't install any cask after upgrade of Xcode 10 to GM and command-line tools to 10 GM/10.14. 

#### Command that failed

```
brew cask install 1clipboard
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install 1clipboard --force -vd
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://1clipboard.io/download/darwin/0.1.8/1Clipboard.zip
Already downloaded: /Users/yurikoles/Library/Caches/Homebrew/downloads/f93913674fcde8b7e6fdea16af9043496c8195b14144cd37f4e29a0c0a26d75a--1Clipboard.zip
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: note: while building module 'Darwin' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
#include <sys/types.h>
         ^
<module-includes>:353:9: note: in file included from <module-includes>:353:
#import "hfs/hfs_format.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'
        uuid_string_t   ext_jnl_uuid;
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: note: while building module 'Darwin' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
#include <sys/types.h>
         ^
<module-includes>:353:9: note: in file included from <module-includes>:353:
#import "hfs/hfs_format.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:796:20: error: use of undeclared identifier 'uuid_string_t'; did you mean 'uuid_variant'?
        char            reserved[JIB_RESERVED_SIZE];
                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:787:61: note: expanded from macro 'JIB_RESERVED_SIZE'
#define JIB_RESERVED_SIZE  ((32*sizeof(u_int32_t)) - sizeof(uuid_string_t) - 48)
                                                            ^
/usr/local/include/uuid/uuid.h:112:12: note: 'uuid_variant' declared here
extern int uuid_variant(const uuid_t uu);
           ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/CoreFoundation.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: error: could not build module 'Darwin'
#include <sys/types.h>
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:10: note: while building module 'Dispatch' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
#include <dispatch/dispatch.h>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "dispatch.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:25:10: error: could not build module 'Darwin'
#include <Availability.h>
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:10: note: while building module 'Dispatch' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
#include <dispatch/dispatch.h>
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:48:10: note: while building module 'os_object' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:48:
#include <os/object.h>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "os/object.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/os/object.h:25:10: error: could not build module 'Darwin'
#include <Availability.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/yurikoles/Library/Caches/Homebrew/downloads/f93913674fcde8b7e6fdea16af9043496c8195b14144cd37f4e29a0c0a26d75a--1Clipboard.zip
/usr/bin/xattr -p com.apple.quarantine /Users/yurikoles/Library/Caches/Homebrew/downloads/f93913674fcde8b7e6fdea16af9043496c8195b14144cd37f4e29a0c0a26d75a--1Clipboard.zip
==> /Users/yurikoles/Library/Caches/Homebrew/downloads/f93913674fcde8b7e6fdea16af9043496c8195b14144cd37f4e29a0c0a26d75a--1Clipboard.zip is not quarantined
==> Quarantining /Users/yurikoles/Library/Caches/Homebrew/downloads/f93913674fcde8b7e6fdea16af9043496c8195b14144cd37f4e29a0c0a26d75a--1Clipboard.zip
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/yurikoles/Library/Caches/Homebrew/downloads/f93913674fcde8b7e6fdea16af9043496c8195b14144cd37f4e29a0c0a26d75a--1Clipboard.zip http://1clipboard.io/download/darwin/0.1.8/1Clipboard.zip http://1clipboard.io/
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: note: while building module 'Darwin' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
#include <sys/types.h>
         ^
<module-includes>:353:9: note: in file included from <module-includes>:353:
#import "hfs/hfs_format.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'
        uuid_string_t   ext_jnl_uuid;
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: note: while building module 'Darwin' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
#include <sys/types.h>
         ^
<module-includes>:353:9: note: in file included from <module-includes>:353:
#import "hfs/hfs_format.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:796:20: error: use of undeclared identifier 'uuid_string_t'; did you mean 'uuid_variant'?
        char            reserved[JIB_RESERVED_SIZE];
                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:787:61: note: expanded from macro 'JIB_RESERVED_SIZE'
#define JIB_RESERVED_SIZE  ((32*sizeof(u_int32_t)) - sizeof(uuid_string_t) - 48)
                                                            ^
/usr/local/include/uuid/uuid.h:112:12: note: 'uuid_variant' declared here
extern int uuid_variant(const uuid_t uu);
           ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/CoreFoundation.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: error: could not build module 'Darwin'
#include <sys/types.h>
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:10: note: while building module 'Dispatch' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
#include <dispatch/dispatch.h>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "dispatch.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:25:10: error: could not build module 'Darwin'
#include <Availability.h>
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:10: note: while building module 'Dispatch' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
#include <dispatch/dispatch.h>
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:48:10: note: while building module 'os_object' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:48:
#include <os/object.h>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "os/object.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/os/object.h:25:10: error: could not build module 'Darwin'
#include <Availability.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
Error: Failed to quarantine /Users/yurikoles/Library/Caches/Homebrew/downloads/f93913674fcde8b7e6fdea16af9043496c8195b14144cd37f4e29a0c0a26d75a--1Clipboard.zip. Here's the reason:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: note: while building module 'Darwin' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
#include <sys/types.h>
         ^
<module-includes>:353:9: note: in file included from <module-includes>:353:
#import "hfs/hfs_format.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'
        uuid_string_t   ext_jnl_uuid;
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: note: while building module 'Darwin' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
#include <sys/types.h>
         ^
<module-includes>:353:9: note: in file included from <module-includes>:353:
#import "hfs/hfs_format.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:796:20: error: use of undeclared identifier 'uuid_string_t'; did you mean 'uuid_variant'?
        char            reserved[JIB_RESERVED_SIZE];
                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:787:61: note: expanded from macro 'JIB_RESERVED_SIZE'
#define JIB_RESERVED_SIZE  ((32*sizeof(u_int32_t)) - sizeof(uuid_string_t) - 48)
                                                            ^
/usr/local/include/uuid/uuid.h:112:12: note: 'uuid_variant' declared here
extern int uuid_variant(const uuid_t uu);
           ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/CoreFoundation.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: error: could not build module 'Darwin'
#include <sys/types.h>
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:10: note: while building module 'Dispatch' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
#include <dispatch/dispatch.h>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "dispatch.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:25:10: error: could not build module 'Darwin'
#include <Availability.h>
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:10: note: while building module 'Dispatch' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
#include <dispatch/dispatch.h>
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:48:10: note: while building module 'os_object' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:48:
#include <os/object.h>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "os/object.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/os/object.h:25:10: error: could not build module 'Darwin'
#include <Availability.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'

/usr/local/Homebrew/Library/Homebrew/cask/quarantine.rb:109:in `cask!'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:53:in `quarantine'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:19:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:146:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew Version
1.7.4-50-g76b41ba
==> macOS
10.14
==> SIP
Enabled (custom configuration)

configuration:
apple internal: disabled
kext signing: disabled
filesystem protections: disabled
debugging restrictions: disabled
dtrace restrictions: disabled
nvram protections: disabled
basesystem verification: disabled
==> Java
10.0.2
==> Gatekeeper support
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: note: while building module 'Darwin' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
#include <sys/types.h>
         ^
<module-includes>:353:9: note: in file included from <module-includes>:353:
#import "hfs/hfs_format.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'
        uuid_string_t   ext_jnl_uuid;
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: note: while building module 'Darwin' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
#include <sys/types.h>
         ^
<module-includes>:353:9: note: in file included from <module-includes>:353:
#import "hfs/hfs_format.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:796:20: error: use of undeclared identifier 'uuid_string_t'; did you mean 'uuid_variant'?
        char            reserved[JIB_RESERVED_SIZE];
                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:787:61: note: expanded from macro 'JIB_RESERVED_SIZE'
#define JIB_RESERVED_SIZE  ((32*sizeof(u_int32_t)) - sizeof(uuid_string_t) - 48)
                                                            ^
/usr/local/include/uuid/uuid.h:112:12: note: 'uuid_variant' declared here
extern int uuid_variant(const uuid_t uu);
           ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/CoreFoundation.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: error: could not build module 'Darwin'
#include <sys/types.h>
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:10: note: while building module 'Dispatch' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
#include <dispatch/dispatch.h>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "dispatch.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:25:10: error: could not build module 'Darwin'
#include <Availability.h>
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:10: note: while building module 'Dispatch' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
#include <dispatch/dispatch.h>
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:48:10: note: while building module 'os_object' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:48:
#include <os/object.h>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "os/object.h"
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/os/object.h:25:10: error: could not build module 'Darwin'
#include <Availability.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4053 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (195 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-eid (11 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1175 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (151 casks)
/usr/local/Homebrew/Library/Taps/yurikoles/homebrew-yurikoles (5 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
buo/cask-upgrade
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/command-not-found
homebrew/core
homebrew/livecheck
homebrew/services
jeffreywildman/virt-manager
kde-mac/kde
theseal/ssh-askpass
vitorgalvao/tiny-scripts
yurikoles/yurikoles
```

**Comment by vitorgalvao** [comment]
This is a quarantining issue. Already being worked on. In the meantime, install with the `--no-quarantine` flag.

Pinging @amyspark for completeness.

**Comment by amyspark** [comment]
This is a mix of:
- a broken Mojave SDK (see how all referred files are within the Xcode folder)
- a typo on my part, which leads to the Swift standard error pipe being printed to console.

Apple has to fix the first one, but I'm dealing with the second in Homebrew/brew#4866.

**Comment by yurikoles** [comment]
duplicates #51873
