### ISSUE TITLE
'brew cleanup' fails with: Error: Calling "cask :v1 => 'token'" is disabled! Use "cask 'token'" instead.

### ISSUE THREAD

**Issue by tjluoma** [Homebrew/homebrew-cask#52016]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present. {There doesn't seem to be a valid way of using `--force` with `cleanup`. Unless I missed something. See output below.}

- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).

- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.

- [X] I ran `brew update-reset && brew update` and retried my command. {Yes, no change.}

- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command. {`brew doctor` reports: "Your system is ready to brew."}

- [X] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem. {Didn't see anything resembling this after searching for 'cleanup'}

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`brew cleanup` fails with this message: 

```
Error: Calling "cask :v1 => 'token'" is disabled! Use "cask 'token'" instead.
Please report this to the homebrew/cask tap, or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/doxygen.rb:1
```

#### Command that failed

```
brew cleanup
```

#### Output of command with `--force --verbose --debug`

I tried `brew --force --verbose --debug cleanup` and got this:

```
Error: Unknown command: --force
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/utils.rb:61:in `exit'
/usr/local/Homebrew/Library/Homebrew/utils.rb:61:in `odie'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

Then I tried `brew cleanup --force --verbose --debug` and got this:

```
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cli_parser.rb:82:in `parse'
/usr/local/Homebrew/Library/Homebrew/cli_parser.rb:9:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:22:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.4-58-gbde49f5
==> macOS
10.11.6
==> SIP
Enabled
==> Java
1.8.0_181
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (2193 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
homebrew/dupes
homebrew/headonly
```

**Comment by tjluoma** [comment]
Yes! That seemed to fix it! Thank you! 👍

**Comment by vitorgalvao** [comment]
@tjluoma For reference, the issue was you had a really old cask file (outdated syntax) in the tap.
