### ISSUE TITLE
Installation of lulu fails

### ISSUE THREAD

**Issue by Nothing4You** [Homebrew/homebrew-cask#52053]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

[lulu](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/lulu.rb) fails to install

#### Command that failed

```
brew cask install lulu
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Caveats
To install and/or use lulu you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://bitbucket.org/objective-see/deploy/downloads/LuLu_1.0.0.zip
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/ff78164d7bb8b0ad8548a0453fbd76c56206ce71202895145cc1cd883b24e87a--LuLu_1.0.0.zip
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/user/Library/Caches/Homebrew/downloads/ff78164d7bb8b0ad8548a0453fbd76c56206ce71202895145cc1cd883b24e87a--LuLu_1.0.0.zip
/usr/bin/xattr -p com.apple.quarantine /Users/user/Library/Caches/Homebrew/downloads/ff78164d7bb8b0ad8548a0453fbd76c56206ce71202895145cc1cd883b24e87a--LuLu_1.0.0.zip
==> /Users/user/Library/Caches/Homebrew/downloads/ff78164d7bb8b0ad8548a0453fbd76c56206ce71202895145cc1cd883b24e87a--LuLu_1.0.0.zip is quarantined
==> Downloaded to -> /Users/user/Library/Caches/Homebrew/downloads/ff78164d7bb8b0ad8548a0453fbd76c56206ce71202895145cc1cd883b24e87a--LuLu_1.0.0.zip
==> Verifying SHA-256 checksum for Cask 'lulu'.
==> Installing Cask lulu
==> Cask::Installer#stage
zipinfo -1 /Users/user/Library/Caches/Homebrew/downloads/ff78164d7bb8b0ad8548a0453fbd76c56206ce71202895145cc1cd883b24e87a--LuLu_1.0.0.zip
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/user/Library/Caches/Homebrew/downloads/ff78164d7bb8b0ad8548a0453fbd76c56206ce71202895145cc1cd883b24e87a--LuLu_1.0.0.zip
unzip /Users/user/Library/Caches/Homebrew/downloads/ff78164d7bb8b0ad8548a0453fbd76c56206ce71202895145cc1cd883b24e87a--LuLu_1.0.0.zip -d /var/folders/s0/3zcdmwqd3hdb0rrnz4b731z80000gn/T/d20180916-58578-1wv86bv
cp -pR /var/folders/s0/3zcdmwqd3hdb0rrnz4b731z80000gn/T/d20180916-58578-1wv86bv/LuLu\ Installer.app/. /usr/local/Caskroom/lulu/1.0.0/LuLu\ Installer.app
==> Verifying Gatekeeper status of /Users/user/Library/Caches/Homebrew/downloads/ff78164d7bb8b0ad8548a0453fbd76c56206ce71202895145cc1cd883b24e87a--LuLu_1.0.0.zip
/usr/bin/xattr -p com.apple.quarantine /Users/user/Library/Caches/Homebrew/downloads/ff78164d7bb8b0ad8548a0453fbd76c56206ce71202895145cc1cd883b24e87a--LuLu_1.0.0.zip
==> /Users/user/Library/Caches/Homebrew/downloads/ff78164d7bb8b0ad8548a0453fbd76c56206ce71202895145cc1cd883b24e87a--LuLu_1.0.0.zip is quarantined
==> Propagating quarantine from /Users/user/Library/Caches/Homebrew/downloads/ff78164d7bb8b0ad8548a0453fbd76c56206ce71202895145cc1cd883b24e87a--LuLu_1.0.0.zip to /usr/local/Caskroom/lulu/1.0.0
/usr/bin/xattr -p com.apple.quarantine /Users/user/Library/Caches/Homebrew/downloads/ff78164d7bb8b0ad8548a0453fbd76c56206ce71202895145cc1cd883b24e87a--LuLu_1.0.0.zip
/bin/chmod -R u\+w /usr/local/Caskroom/lulu/1.0.0
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5b9e6632\;Homebrew\\x20Cask\;37CB2B03-C878-4D61-BDCB-B0473890C115
==> Creating metadata directory /usr/local/Caskroom/lulu/.metadata/1.0.0/20180916143608.434.
==> Creating metadata subdirectory /usr/local/Caskroom/lulu/.metadata/1.0.0/20180916143608.434/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x000000010115e288>
==> Installing artifact of class Cask::Artifact::Installer
==> Running installer script '/usr/local/Caskroom/lulu/1.0.0/Lulu Installer.app/Contents/MacOS/LuLu Installer'
/usr/bin/sudo -E -- env PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm /usr/local/Caskroom/lulu/1.0.0/Lulu\ Installer.app/Contents/MacOS/LuLu\ Installer -install
env: /usr/local/Caskroom/lulu/1.0.0/Lulu Installer.app/Contents/MacOS/LuLu Installer: No such file or directory
==> Purging files for version 1.0.0 of Cask lulu
Error: Failure while executing; `/usr/bin/sudo -E -- env PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm /usr/local/Caskroom/lulu/1.0.0/Lulu\ Installer.app/Contents/MacOS/LuLu\ Installer -install` exited with 127. Here's the output:
env: /usr/local/Caskroom/lulu/1.0.0/Lulu Installer.app/Contents/MacOS/LuLu Installer: No such file or directory


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:101:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:46:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/installer.rb:45:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:207:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:199:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:96:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.4-58-gbde49f5
==> macOS
10.13.6
==> SIP
Enabled
==> Java
1.8.0_171, 1.8.0_144
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4043 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
homebrew/php
homebrew/services
```

**Comment by vitorgalvao** [comment]
Cask has been updated to `1.1.0`. Please try again and make a new bug report if it fails.
