### ISSUE TITLE
Cask upgrade fails with Error: No such file or directory @ rb_file_s_rename

### ISSUE THREAD

**Issue by vioint** [Homebrew/homebrew-cask#52271]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Trying to upgrade all casks, powershell seems to fail with an error about a failed file rename originating at Homebrew/cask/installer.rb:456.
Please also note that this fails without providing a prompt for the admin password (or prior to it).

#### Command that failed

```
brew cask upgrade
```

#### Output of command with `--force --verbose --debug`

```
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 1 outdated package, with result:
powershell 6.0.4 -> 6.1.0
==> Started upgrade process for Cask powershell
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
All Formula dependencies satisfied.
==> Downloading
==> Downloading https://github.com/PowerShell/PowerShell/releases/download/v6.1.0/powershell-6.1.0-osx-x64.pkg
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/fe83473bf87c8735310496b628e17f62d05e616c20b8dd1fd42eabeb72bbd640--powershell-6.1.0-osx-x64.pkg
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/admin/Library/Caches/Homebrew/downloads/fe83473bf87c8735310496b628e17f62d05e616c20b8dd1fd42eabeb72bbd640--powershell-6.1.0-osx-x64.pkg
/usr/bin/xattr -p com.apple.quarantine /Users/admin/Library/Caches/Homebrew/downloads/fe83473bf87c8735310496b628e17f62d05e616c20b8dd1fd42eabeb72bbd640--powershell-6.1.0-osx-x64.pkg
==> /Users/admin/Library/Caches/Homebrew/downloads/fe83473bf87c8735310496b628e17f62d05e616c20b8dd1fd42eabeb72bbd640--powershell-6.1.0-osx-x64.pkg is quarantined
==> Downloaded to -> /Users/admin/Library/Caches/Homebrew/downloads/fe83473bf87c8735310496b628e17f62d05e616c20b8dd1fd42eabeb72bbd640--powershell-6.1.0-osx-x64.pkg
==> Verifying SHA-256 checksum for Cask 'powershell'.
==> Starting upgrade for Cask powershell
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x0000000101869b68>
==> Un-installing artifact of class Cask::Artifact::Uninstall
==> Running uninstall process for powershell; your password may be necessary
==> Uninstalling packages:
/usr/sbin/pkgutil --pkgs=com.microsoft.powershell
Error: No such file or directory @ rb_file_s_rename - (/usr/local/Caskroom/powershell/6.0.4, /usr/local/Caskroom/powershell/6.0.4.upgrading)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:456:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:456:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:456:in `backup'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:452:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:76:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'

```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.5-54-g3192d2d
==> macOS
10.13.6
==> SIP
Disabled
==> Java
10.0.2
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4040 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (195 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-eid (11 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1175 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (151 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"

```

#### Output of `brew tap`

```
heroku/brew
homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/php
homebrew/versions
vitorgalvao/tiny-scripts
```

For now I solved this by reinstalling (eg. 'brew cask reinstall powershell') but I reported this here for the community since I guess there might be others out there who might run into this soon.

**Comment by vitorgalvao** [comment]
Nobody else seems to be having this issue and you solved it in your setup, so closing.
