### ISSUE TITLE
hp-easy-start install fails

### ISSUE THREAD

**Issue by christianharke** [Homebrew/homebrew-cask#52371]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

On a freshly set up OS X, I cannot get hp-easy-start installed by Homebrew. Any ideas how to fix this?

#### Command that failed

```
brew cask install hp-easy-start
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://ftp.hp.com/pub/softlib/software12/HP_Quick_Start/osx/Applications/HP_Easy_Start.app.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.6-4-g27c2a0a\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.12.6\)\ curl/7.54.0 --location --silent --head http://ftp.hp.com/pub/softlib/software12/HP_Quick_Start/osx/Applications/HP_Easy_Start.app.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.6-4-g27c2a0a\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.12.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/christian/Library/Caches/Homebrew/downloads/49c29e3814a97bd259ea05ec287fd20787fc48e921f2f106624d5a1ed147cee4--HP_Easy_Start.app.zip.incomplete http://ftp.hp.com/pub/softlib/software12/HP_Quick_Start/osx/Applications/HP_Easy_Start.app.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9302k  100 9302k    0     0  1372k      0  0:00:06  0:00:06 --:--:-- 1995k
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/christian/Library/Caches/Homebrew/downloads/49c29e3814a97bd259ea05ec287fd20787fc48e921f2f106624d5a1ed147cee4--HP_Easy_Start.app.zip
/usr/bin/xattr -p com.apple.quarantine /Users/christian/Library/Caches/Homebrew/downloads/49c29e3814a97bd259ea05ec287fd20787fc48e921f2f106624d5a1ed147cee4--HP_Easy_Start.app.zip
==> /Users/christian/Library/Caches/Homebrew/downloads/49c29e3814a97bd259ea05ec287fd20787fc48e921f2f106624d5a1ed147cee4--HP_Easy_Start.app.zip is not quarantined
==> Quarantining /Users/christian/Library/Caches/Homebrew/downloads/49c29e3814a97bd259ea05ec287fd20787fc48e921f2f106624d5a1ed147cee4--HP_Easy_Start.app.zip
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/christian/Library/Caches/Homebrew/downloads/49c29e3814a97bd259ea05ec287fd20787fc48e921f2f106624d5a1ed147cee4--HP_Easy_Start.app.zip http://ftp.hp.com/pub/softlib/software12/HP_Quick_Start/osx/Applications/HP_Easy_Start.app.zip https://support.hp.com/
==> Downloaded to -> /Users/christian/Library/Caches/Homebrew/downloads/49c29e3814a97bd259ea05ec287fd20787fc48e921f2f106624d5a1ed147cee4--HP_Easy_Start.app.zip
==> No SHA-256 checksum defined for Cask 'hp-easy-start', skipping verification.
==> Installing Cask hp-easy-start
==> Cask::Installer#stage
zipinfo -1 /Users/christian/Library/Caches/Homebrew/downloads/49c29e3814a97bd259ea05ec287fd20787fc48e921f2f106624d5a1ed147cee4--HP_Easy_Start.app.zip
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/christian/Library/Caches/Homebrew/downloads/49c29e3814a97bd259ea05ec287fd20787fc48e921f2f106624d5a1ed147cee4--HP_Easy_Start.app.zip
unzip /Users/christian/Library/Caches/Homebrew/downloads/49c29e3814a97bd259ea05ec287fd20787fc48e921f2f106624d5a1ed147cee4--HP_Easy_Start.app.zip -d /var/folders/d2/38yx7krn75x6cmwp34l1ft1h0000gn/T/d20180923-21808-dkhhf4
cp -pR /var/folders/d2/38yx7krn75x6cmwp34l1ft1h0000gn/T/d20180923-21808-dkhhf4/HP\ Easy\ Start.app/. /usr/local/Caskroom/hp-easy-start/latest/HP\ Easy\ Start.app
==> Purging files for version latest of Cask hp-easy-start
/usr/bin/chflags -R -- 000 /usr/local/Caskroom/hp-easy-start/latest
/bin/chmod -R -- u\+rwx /usr/local/Caskroom/hp-easy-start/latest
/bin/chmod -R -N /usr/local/Caskroom/hp-easy-start/latest
Error: Directory not empty @ dir_s_rmdir - /var/folders/d2/38yx7krn75x6cmwp34l1ft1h0000gn/T/d20180923-21808-dkhhf4
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1446:in `rmdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1446:in `block in remove_dir1'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1457:in `platform_support'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1445:in `remove_dir1'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1438:in `remove'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:780:in `block in remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1495:in `ensure in postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:1495:in `postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/fileutils.rb:778:in `remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:95:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:124:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:184:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:73:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.6-4-g27c2a0a
==> macOS
10.12.6
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4033 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (151 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (198 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-versions
homebrew/core
```

**Comment by strafe** [comment]
I was going to get around to report this, same issue here.

**Comment by vitorgalvao** [comment]
I can’t reproduce this. Is is still happening to you?

**Comment by strafe** [comment]
@vitorgalvao can't reproduce anymore.

**Comment by vitorgalvao** [comment]
Might’ve been an upstream bug that has since been fixed.
