### ISSUE TITLE
golem network install on Mac rror: Failed executing: opam init --no-setup

### ISSUE THREAD

**Issue by ProTeXMining** [Homebrew/homebrew-cask#52570]
#### General troubleshooting steps

- [ ] I have retried my command with `--force` and the issue is still present.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

{{I am trying to install golem network on my Macbook pro , I have Mac OS 10.14 (MacOS Mojave)}}

#### Command that failed

```
{{Chads-MBP:~ chadwinter$ brew tap caskroom/cask 
Chads-MBP:~ chadwinter$ brew tap golemfactory/golem 
Chads-MBP:~ chadwinter$ brew cask install golem 
==> Satisfying dependencies
==> Installing Formula dependencies: golem
==> Installing dependencies for golemfactory/golem/golem: docker-machine-driver-xhyve, ilmbase, openexr, gmp, freeimage, golemfactory/hyperg/hyperg
==> Installing golemfactory/golem/golem dependency: docker-machine-driver-x
==> Cloning https://github.com/zchee/docker-machine-driver-xhyve.git
Updating /Users/chadwinter/Library/Caches/Homebrew/docker-machine-driver-xhyve--git
==> Checking out tag v0.3.3
HEAD is now at 7d92f74 xhyve: bump version 0.3.3
HEAD is now at 7d92f74 xhyve: bump version 0.3.3
Entering 'vendor/lib9p'
/Users/chadwinter/Library/Caches/Homebrew/docker-machine-driver-xhyve--git/vendor/lib9p
==> opam init --no-setup

Last 15 lines from /Users/chadwinter/Library/Logs/Homebrew/docker-machine-driver-xhyve/01.opam:
# sandbox-exec: sandbox_apply_container: Operation not permitted



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build ocaml-system 4.07.0
└─ 
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray base
│ ∗ install base-threads  base
│ ∗ install base-unix     base
└─ 
# Run eval $(opam env) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] Error: Failed executing: opam init --no-setup
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/formula.rb:1908:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1845:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1845:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/docker-machine-driver-xhyve.rb:47:in `block in install'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:128:in `chdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:128:in `cd'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/docker-machine-driver-xhyve.rb:36:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:143:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1134:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2074:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:523:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2073:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:103:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:173:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:172:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:98:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:75:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2049:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1129:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:114:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:523:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:192:in `<main>'
}}
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{Chads-MBP:~ chadwinter$ brew cask doctor
==> Homebrew Version
1.7.6
==> macOS
10.14
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4037 casks)
/usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem (2 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
Chads-MBP:~ chadwinter$ 
}}
```

#### Output of `brew tap`

```
{{Chads-MBP:~ chadwinter$ brew tap
golemfactory/golem
golemfactory/hyperg
homebrew/cask
homebrew/core
Chads-MBP:~ chadwinter$ 
}}
```

**Comment by commitay** [comment]
https://github.com/Homebrew/homebrew-core/pull/32461 should fix the problem with `docker-machine-driver-xhyve` once it is merged but you might want to report it to https://github.com/golemfactory/homebrew-golem as well
