### ISSUE TITLE
gisto checksum mismatch

### ISSUE THREAD

**Issue by y0y0z** [Homebrew/homebrew-cask#52597]
#### Description of issue
unable to install gisto 1.10.5

#### Command that failed

```bash
$ brew update-reset
$ brew update
$ brew cask install gisto
...
==> Verifying SHA-256 checksum for Cask 'gisto'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'gisto' does not match.

Expected: 1435b12c75777a97ddd3e28577fcd54247015326954e6aebb1befb72f2e5f66c
Actual:   e3def1a5950b3c34db6393e8e78316445311f00079e073fc875876b21f5e1a0b
File:     /Users/foo/Library/Caches/Homebrew/downloads/a9d4e5c96fbe18c0290b1317b52d49034ecaf334042e1d171efd4d5013b09e11--Gisto-1.10.5.dmg
```

#### Output of command with `--force --verbose --debug`

```bash
$ brew cask install gisto --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://github.com/Gisto/Gisto/releases/download/v1.10.5/Gisto-1.10.5.dmg
Already downloaded: /Users/foo/Library/Caches/Homebrew/downloads/a9d4e5c96fbe18c0290b1317b52d49034ecaf334042e1d171efd4d5013b09e11--Gisto-1.10.5.dmg
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/foo/Library/Caches/Homebrew/downloads/a9d4e5c96fbe18c0290b1317b52d49034ecaf334042e1d171efd4d5013b09e11--Gisto-1.10.5.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/foo/Library/Caches/Homebrew/downloads/a9d4e5c96fbe18c0290b1317b52d49034ecaf334042e1d171efd4d5013b09e11--Gisto-1.10.5.dmg
==> /Users/foo/Library/Caches/Homebrew/downloads/a9d4e5c96fbe18c0290b1317b52d49034ecaf334042e1d171efd4d5013b09e11--Gisto-1.10.5.dmg is quarantined
==> Downloaded to -> /Users/foo/Library/Caches/Homebrew/downloads/a9d4e5c96fbe18c0290b1317b52d49034ecaf334042e1d171efd4d5013b09e11--Gisto-1.10.5.dmg
==> Verifying SHA-256 checksum for Cask 'gisto'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'gisto' does not match.

Expected: 1435b12c75777a97ddd3e28577fcd54247015326954e6aebb1befb72f2e5f66c
Actual:   e3def1a5950b3c34db6393e8e78316445311f00079e073fc875876b21f5e1a0b
File:     /Users/foo/Library/Caches/Homebrew/downloads/a9d4e5c96fbe18c0290b1317b52d49034ecaf334042e1d171efd4d5013b09e11--Gisto-1.10.5.dmg

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/verify.rb:21:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:159:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:63:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```bash
$ brew cask doctor
==> Homebrew Version
1.7.6-22-gdae4791
==> macOS
10.14
==> SIP
Enabled
==> Java
10
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4037 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
HOMEBREW_CASK_OPTS="--appdir=~/Applications --fontdir=~/Library/Fonts"
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```bash
$ brew tap
buo/cask-upgrade
homebrew/cask
homebrew/core
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/52589#issuecomment-425477962

**Comment by vitorgalvao** [comment]
Also, please don’t delete the checklist. Follow it and check it.
