### ISSUE TITLE
failed to install cask virtualbox

### ISSUE THREAD

**Issue by markbsigler** [Homebrew/homebrew-cask#52659]
#### General troubleshooting steps

- [ X] I have retried my command with `--force` and the issue is still present.
- [ X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [ X] I ran `brew update-reset && brew update` and retried my command.
- [ X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ X] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [ X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

failed to install cask virtualbox

#### Command that failed

```
brew cask install --force --verbose --debug virtualbox
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install --force --verbose --debug virtualbox
==> Cask::Installer#install
==> Printing caveats
==> Caveats
To install and/or use virtualbox you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.virtualbox.org/virtualbox/5.2.18/VirtualBox-5.2.18-124319-OSX.dmg
Already downloaded: /Users/msigler/Library/Caches/Homebrew/downloads/4615b4fafa6c94c2f112089c0a964e613b0f6113b016ea526ccdb40cfc9f20de--VirtualBox-5.2.18-124319-OSX.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/msigler/Library/Caches/Homebrew/downloads/4615b4fafa6c94c2f112089c0a964e613b0f6113b016ea526ccdb40cfc9f20de--VirtualBox-5.2.18-124319-OSX.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/msigler/Library/Caches/Homebrew/downloads/4615b4fafa6c94c2f112089c0a964e613b0f6113b016ea526ccdb40cfc9f20de--VirtualBox-5.2.18-124319-OSX.dmg
==> /Users/msigler/Library/Caches/Homebrew/downloads/4615b4fafa6c94c2f112089c0a964e613b0f6113b016ea526ccdb40cfc9f20de--VirtualBox-5.2.18-124319-OSX.dmg is quarantined
==> Downloaded to -> /Users/msigler/Library/Caches/Homebrew/downloads/4615b4fafa6c94c2f112089c0a964e613b0f6113b016ea526ccdb40cfc9f20de--VirtualBox-5.2.18-124319-OSX.dmg
==> Verifying SHA-256 checksum for Cask 'virtualbox'.
==> Installing Cask virtualbox
==> Cask::Installer#stage
hdiutil imageinfo /Users/msigler/Library/Caches/Homebrew/downloads/4615b4fafa6c94c2f112089c0a964e613b0f6113b016ea526ccdb40cfc9f20de--VirtualBox-5.2.18-124319-OSX.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/msigler/Library/Caches/Homebrew/downloads/4615b4fafa6c94c2f112089c0a964e613b0f6113b016ea526ccdb40cfc9f20de--VirtualBox-5.2.18-124319-OSX.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/jk/dj03__c12y93lh98jc9f5bl80000gn/T/d20180930-4484-yn31t4 /Users/msigler/Library/Caches/Homebrew/downloads/4615b4fafa6c94c2f112089c0a964e613b0f6113b016ea526ccdb40cfc9f20de--VirtualBox-5.2.18-124319-OSX.dmg
find . -print0
mkbom -s -i /var/folders/jk/dj03__c12y93lh98jc9f5bl80000gn/T/20180930-4484-nf2k5o.list -- /var/folders/jk/dj03__c12y93lh98jc9f5bl80000gn/T/20180930-4484-y7z6ot.bom
ditto --bom /var/folders/jk/dj03__c12y93lh98jc9f5bl80000gn/T/20180930-4484-y7z6ot.bom -- /private/var/folders/jk/dj03__c12y93lh98jc9f5bl80000gn/T/d20180930-4484-yn31t4/dmg.C93HqX /var/folders/jk/dj03__c12y93lh98jc9f5bl80000gn/T/d20180930-4484-1e22kn5
diskutil eject /private/var/folders/jk/dj03__c12y93lh98jc9f5bl80000gn/T/d20180930-4484-yn31t4/dmg.C93HqX
cp -pR /var/folders/jk/dj03__c12y93lh98jc9f5bl80000gn/T/d20180930-4484-1e22kn5/VirtualBox.pkg /usr/local/Caskroom/virtualbox/5.2.18,124319/VirtualBox.pkg
cp -pR /var/folders/jk/dj03__c12y93lh98jc9f5bl80000gn/T/d20180930-4484-1e22kn5/VirtualBox_Uninstall.tool /usr/local/Caskroom/virtualbox/5.2.18,124319/VirtualBox_Uninstall.tool
cp -pR /var/folders/jk/dj03__c12y93lh98jc9f5bl80000gn/T/d20180930-4484-1e22kn5/UserManual.pdf /usr/local/Caskroom/virtualbox/5.2.18,124319/UserManual.pdf
==> Verifying Gatekeeper status of /Users/msigler/Library/Caches/Homebrew/downloads/4615b4fafa6c94c2f112089c0a964e613b0f6113b016ea526ccdb40cfc9f20de--VirtualBox-5.2.18-124319-OSX.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/msigler/Library/Caches/Homebrew/downloads/4615b4fafa6c94c2f112089c0a964e613b0f6113b016ea526ccdb40cfc9f20de--VirtualBox-5.2.18-124319-OSX.dmg
==> /Users/msigler/Library/Caches/Homebrew/downloads/4615b4fafa6c94c2f112089c0a964e613b0f6113b016ea526ccdb40cfc9f20de--VirtualBox-5.2.18-124319-OSX.dmg is quarantined
==> Propagating quarantine from /Users/msigler/Library/Caches/Homebrew/downloads/4615b4fafa6c94c2f112089c0a964e613b0f6113b016ea526ccdb40cfc9f20de--VirtualBox-5.2.18-124319-OSX.dmg to /usr/local/Caskroom/virtualbox/5.2.18,124319
/usr/bin/xattr -p com.apple.quarantine /Users/msigler/Library/Caches/Homebrew/downloads/4615b4fafa6c94c2f112089c0a964e613b0f6113b016ea526ccdb40cfc9f20de--VirtualBox-5.2.18-124319-OSX.dmg
/bin/chmod -R u\+w /usr/local/Caskroom/virtualbox/5.2.18,124319
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5babd56f\;Homebrew\\x20Cask\;46C08445-A6A2-422D-A080-88196B934946
==> Creating metadata directory /usr/local/Caskroom/virtualbox/.metadata/5.2.18,124319/20180930200258.246.
==> Creating metadata subdirectory /usr/local/Caskroom/virtualbox/.metadata/5.2.18,124319/20180930200258.246/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00007fc2b3b39f70>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=msigler USER=msigler USERNAME=msigler /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/5.2.18,124319/VirtualBox.pkg -target / -verboseR
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%10.109272
installer:PHASE:Writing files…
installer:%31.167263
installer:PHASE:Writing files…
installer:%64.861711
installer:PHASE:Moving items into place…
installer:%86.843525
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 5.2.18,124319 of Cask virtualbox
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=msigler USER=msigler USERNAME=msigler /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/5.2.18,124319/VirtualBox.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%10.109272
installer:PHASE:Writing files…
installer:%31.167263
installer:PHASE:Writing files…
installer:%64.861711
installer:PHASE:Moving items into place…
installer:%86.843525
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:105:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:48:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:25:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:51:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:31:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:96:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew Version
1.7.6-38-gb41d2e5
==> macOS
10.13.6
==> SIP
Enabled
==> Java
11
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4037 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
HOMEBREW_CASK_OPTS="--appdir=/Applications"
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
homebrew/cask
homebrew/core
homebrew/services
jenkins-x/jx
```

**Comment by My2ndAngelic** [comment]
As far as I can tell you are using macOS 10.13 so you might want to go to System Prefenrences and allow the kext to work. After that run the installer again to see what will happen.

**Comment by markbsigler** [comment]
Should've mentioned. That was the first thing i checked.

macOS 10.13.6

I did go to Setting>Security & Privacy>General and clicked Allow for Oracle but there wasn't an ask for kext explicitly.

Is there a kextload cli i can try?

**Comment by My2ndAngelic** [comment]
Well you just have to launch System Preference and reinstall again. I did have that problem also on 10.14.

**Comment by markbsigler** [comment]
> Well you just have to launch System Preference and reinstall again. I did have that problem also on 10.14 and that was my only try. So try to install Vbox twice after you first allow System Extension in the System Preference.

I used the VirtualBox_Uninstall.tool from the image to clean. Same results on install. Doesn't prompt to "Allow" kext. Virtualbox is installed but not cask list.

**Comment by markbsigler** [comment]
> What happens if you download and install it, all without homebrew-cask?

That was my next step, and same outcome. So not a cask issue per se, and fair dinkum to close this issue. Interesting that virtualbox seems to be functioning okay, and this is a new MacBook Pro that I'm doing initial setup.

**Comment by vitorgalvao** [comment]
Yep, definitely something to ask them.
