### ISSUE TITLE
Failed to download visual-studio cask (7.6.7.49)

### ISSUE THREAD

**Issue by alistairharris** [Homebrew/homebrew-cask#52696]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Upon running `brew cu -a`, I received an update for the visual-studio cask (7.6.7.49), but it failed to update [it was fine before this].  I attempted `brew cask reinstall visual-studio`, with no luck, followed by `brew cask uninstall visual-studio --force && brew cask install visual-studio`, and was met with the same error.

#### Command that failed

```
brew cask install visual-studio
```

#### Output of command with `--force --verbose --debug`

```
~ ❯❯❯ brew cask install visual-studio --force --verbose --debug                                                    ✘ 1 
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask-versions).
No changes to formulae.

==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
All Cask dependencies satisfied.
==> Downloading
==> Downloading https://dl.xamarin.com/VsMac/VisualStudioForMac-7.6.7.49.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.6-49-gbb038c7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --location --silent --head https://dl.xamarin.com/VsMac/VisualStudioForMac-7.6.7.49.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.6-49-gbb038c7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --location --silent --head https://dl.xamarin.com/VsMac/VisualStudioForMac-7.6.7.49.dmg
==> Downloading from https://download.visualstudio.microsoft.com/download/pr/9dc2f92a-8a40-4205-a4f1-35700e3df803/7a4dc5e5139e1b89175842dd6474cac0/visualstudioformac-7.6.7.49.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.6-49-gbb038c7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --location --head --range 0-1 --write-out \%\{http_code\} --output /dev/null https://download.visualstudio.microsoft.com/download/pr/9dc2f92a-8a40-4205-a4f1-35700e3df803/7a4dc5e5139e1b89175842dd6474cac0/visualstudioformac-7.6.7.49.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.6-49-gbb038c7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/alistair/Library/Caches/Homebrew/downloads/8094f06f4ae48870db5d49bc143741ea5611151285512c18369223891f12aa90--visualstudioformac-7.6.7.49.dmg.incomplete https://download.visualstudio.microsoft.com/download/pr/9dc2f92a-8a40-4205-a4f1-35700e3df803/7a4dc5e5139e1b89175842dd6474cac0/visualstudioformac-7.6.7.49.dmg
** Resuming transfer from byte position 561685052
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   389    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 416
Error: Download failed on Cask 'visual-studio' with message: Download failed: https://dl.xamarin.com/VsMac/VisualStudioForMac-7.6.7.49.dmg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:295:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:290:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:18:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:146:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
~ ❯❯❯ brew cask doctor
==> Homebrew Version
1.7.6-49-gbb038c7
==> macOS
10.14
==> SIP
Enabled
==> Java
11, 1.8.0_144
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4038 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (204 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1177 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (152 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
buo/cask-upgrade
dart-lang/dart
ethereum/ethereum
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/php
homebrew/services
osx-cross/avr
paritytech/paritytech
px4/px4
sass/sass
```

**Comment by alistairharris** [comment]
It's worth mentioning that if I use the target URL from the formula in a web browser, it downloads correctly, and I'm not met with a 416.

**Comment by amyspark** [comment]
HTTP 416 = download cannot be resumed (see the line `** Resuming transfer from byte position 561685052`).

**Comment by alistairharris** [comment]
> HTTP 416 = download cannot be resumed (see the line `** Resuming transfer from byte position 561685052`).

I'm aware, but I'm not sure about how to fix this.  It does this every time.

**Comment by vitorgalvao** [comment]
This is not a problem with HBC but with your configuration/connection. [These instructions](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#curl-error) might help but this is not an issue on our end.

**Comment by alistairharris** [comment]
@vitorgalvao Any connection I would run on would present the same issue, and the fix you've linked me to would not fix the issue, so I disagree; but I did _just_ carry out the following, which is a reasonable workaround:
`rm /Users/alistair/Library/Caches/Homebrew/downloads/8094f06f4ae48870db5d49bc143741ea5611151285512c18369223891f12aa90--visualstudioformac-7.6.7.49.dmg.incomplete; brew cask install visual-studio`

It'd be nice if `brew cleanup` (or an alternative command, if more appropriate) would clean up incomplete downloads.
