### ISSUE TITLE
casks fail to install with 'was not quarantined properly.'

### ISSUE THREAD

**Issue by core-code** [Homebrew/homebrew-cask#52738]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

since today many casks (e.g. iridium boostnote bluefish) fail to install with a quarantine issue. seems to randomly go away.

#### Command that failed

```
brew cask install iridium
```

#### Output of command with `--force --verbose --debug`

```
 brew cask install iridium
==> Satisfying dependencies
==> Downloading https://downloads.iridiumbrowser.de/macos/2018.4-0/iridium_browser_2018.04.66.0_macos_x64.dm
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'iridium'.
==> Installing Cask iridium
==> Purging files for version 2018.04.66.0,2018.4-0 of Cask iridium
Error: /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg was not quarantined properly.
Julians-MBP:~ julian$ brew cask --force install iridium
==> Satisfying dependencies
==> Downloading https://downloads.iridiumbrowser.de/macos/2018.4-0/iridium_browser_2018.04.66.0_macos_x64.dm
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'iridium'.
==> Installing Cask iridium
==> Purging files for version 2018.04.66.0,2018.4-0 of Cask iridium
Error: /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg was not quarantined properly.
Julians-MBP:~ julian$ brew cask --force --verbose --debug install iridium
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.iridiumbrowser.de/macos/2018.4-0/iridium_browser_2018.04.66.0_macos_x64.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.6-61-gf354160\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --location --silent --head https://downloads.iridiumbrowser.de/macos/2018.4-0/iridium_browser_2018.04.66.0_macos_x64.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.6-61-gf354160\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --location --silent --head https://downloads.iridiumbrowser.de/macos/2018.4-0/iridium_browser_2018.04.66.0_macos_x64.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.6-61-gf354160\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg.incomplete https://downloads.iridiumbrowser.de/macos/2018.4-0/iridium_browser_2018.04.66.0_macos_x64.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 70.7M  100 70.7M    0     0  8124k      0  0:00:08  0:00:08 --:--:-- 8997k
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg
==> /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg is not quarantined
==> Quarantining /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg https://downloads.iridiumbrowser.de/macos/2018.4-0/iridium_browser_2018.04.66.0_macos_x64.dmg https://iridiumbrowser.de/
==> Downloaded to -> /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg
==> Verifying SHA-256 checksum for Cask 'iridium'.
==> Installing Cask iridium
==> Cask::Installer#stage
hdiutil imageinfo /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/yq/8p0fcjdj3xsdw22j3ftlwb680000gn/T/d20181002-79230-8r4wvs /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg
find . -print0
mkbom -s -i /var/folders/yq/8p0fcjdj3xsdw22j3ftlwb680000gn/T/20181002-79230-10rasvd.list -- /var/folders/yq/8p0fcjdj3xsdw22j3ftlwb680000gn/T/20181002-79230-x6wl6.bom
ditto --bom /var/folders/yq/8p0fcjdj3xsdw22j3ftlwb680000gn/T/20181002-79230-x6wl6.bom -- /private/var/folders/yq/8p0fcjdj3xsdw22j3ftlwb680000gn/T/d20181002-79230-8r4wvs/dmg.UeF0oy /var/folders/yq/8p0fcjdj3xsdw22j3ftlwb680000gn/T/d20181002-79230-tv548g
diskutil eject /private/var/folders/yq/8p0fcjdj3xsdw22j3ftlwb680000gn/T/d20181002-79230-8r4wvs/dmg.UeF0oy
cp -pR /var/folders/yq/8p0fcjdj3xsdw22j3ftlwb680000gn/T/d20181002-79230-tv548g/Iridium.app/. /usr/local/Caskroom/iridium/2018.04.66.0,2018.4-0/Iridium.app
chmod -Rf +w /var/folders/yq/8p0fcjdj3xsdw22j3ftlwb680000gn/T/d20181002-79230-tv548g
==> Verifying Gatekeeper status of /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg
==> /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg is not quarantined
==> Purging files for version 2018.04.66.0,2018.4-0 of Cask iridium
Error: /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg was not quarantined properly.
/usr/local/Homebrew/Library/Homebrew/cask/quarantine.rb:131:in `propagate'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:190:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:73:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew Version
1.7.6-61-gf354160
==> macOS
10.14
==> SIP
Disabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4036 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (204 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-eid (11 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1177 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (152 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
brew tap
homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
vitorgalvao/tiny-scripts```

**Comment by amyspark** [comment]
Mojave seems to have some issues with my quarantine script. Can you run the following (in the given order) and report back with the results?
```
xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/julian/Library/Caches/Homebrew/downloads/f69cc2efe8e2ac9e1458eb74ac9743a27f6897d50d3fc726f840c8f901ec4316--iridium_browser_2018.04.66.0_macos_x64.dmg https://downloads.iridiumbrowser.de/macos/2018.4-0/iridium_browser_2018.04.66.0_macos_x64.dmg https://iridiumbrowser.de/
echo $?
```
The `swift` line will attempt to quarantine manually the download. Judging from your log, it should fail and give you an error log together with the exit code (`echo $?`).

**Comment by core-code** [comment]
sorry for the noise i think this was caused by a glitch on my end

**Comment by core-code** [comment]
in case anyone is interested in fixing this, if you do a 
'brew cleanup -s' 
while simultaneously doing a 
'brew cask install xxx'
then you (sometimes) get the described problem. it must be a race condition due to missing locking.
