### ISSUE TITLE
brew cask install unity-ios-support-for-editor FAILED!!

### ISSUE THREAD

**Issue by portalmafia** [Homebrew/homebrew-cask#52973]
#### General troubleshooting steps

- [ ] I have retried my command with `--force` and the issue is still present.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

{{replace this}}

#### Command that failed

```
brew cask reinstall unity-ios-support-for-editor --force --verbose --debug
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#reinstall
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
All Cask dependencies satisfied.
==> Downloading
==> Downloading https://netstorage.unity3d.com/unity/c591d9a97a0b/MacEditorTargetInstaller/UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg
Already downloaded: /Users/username/Library/Caches/Homebrew/downloads/daa865c981a9c477706e1aba52379d346f6e503f77e98b0d1f1a2d65d7e7a35a--UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/username/Library/Caches/Homebrew/downloads/daa865c981a9c477706e1aba52379d346f6e503f77e98b0d1f1a2d65d7e7a35a--UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg
/usr/bin/xattr -p com.apple.quarantine /Users/username/Library/Caches/Homebrew/downloads/daa865c981a9c477706e1aba52379d346f6e503f77e98b0d1f1a2d65d7e7a35a--UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg
==> /Users/username/Library/Caches/Homebrew/downloads/daa865c981a9c477706e1aba52379d346f6e503f77e98b0d1f1a2d65d7e7a35a--UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg is quarantined
==> Downloaded to -> /Users/username/Library/Caches/Homebrew/downloads/daa865c981a9c477706e1aba52379d346f6e503f77e98b0d1f1a2d65d7e7a35a--UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg
==> Verifying SHA-256 checksum for Cask 'unity-ios-support-for-editor'.
==> Installing Cask unity-ios-support-for-editor
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Pkg for /Users/username/Library/Caches/Homebrew/downloads/daa865c981a9c477706e1aba52379d346f6e503f77e98b0d1f1a2d65d7e7a35a--UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg
cp -p /Users/username/Library/Caches/Homebrew/downloads/daa865c981a9c477706e1aba52379d346f6e503f77e98b0d1f1a2d65d7e7a35a--UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg /usr/local/Caskroom/unity-ios-support-for-editor/2018.2.6f1,c591d9a97a0b/UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg
==> Verifying Gatekeeper status of /Users/username/Library/Caches/Homebrew/downloads/daa865c981a9c477706e1aba52379d346f6e503f77e98b0d1f1a2d65d7e7a35a--UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg
/usr/bin/xattr -p com.apple.quarantine /Users/username/Library/Caches/Homebrew/downloads/daa865c981a9c477706e1aba52379d346f6e503f77e98b0d1f1a2d65d7e7a35a--UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg
==> /Users/username/Library/Caches/Homebrew/downloads/daa865c981a9c477706e1aba52379d346f6e503f77e98b0d1f1a2d65d7e7a35a--UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg is quarantined
==> Propagating quarantine from /Users/username/Library/Caches/Homebrew/downloads/daa865c981a9c477706e1aba52379d346f6e503f77e98b0d1f1a2d65d7e7a35a--UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg to /usr/local/Caskroom/unity-ios-support-for-editor/2018.2.6f1,c591d9a97a0b
/usr/bin/xattr -p com.apple.quarantine /Users/username/Library/Caches/Homebrew/downloads/daa865c981a9c477706e1aba52379d346f6e503f77e98b0d1f1a2d65d7e7a35a--UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg
/bin/chmod -R u\+w /usr/local/Caskroom/unity-ios-support-for-editor/2018.2.6f1,c591d9a97a0b
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5bb8aa7c\;Homebrew\\x20Cask\;02866001-B37C-425C-9EC2-09321E90FC69
==> Creating metadata directory /usr/local/Caskroom/unity-ios-support-for-editor/.metadata/2018.2.6f1,c591d9a97a0b/20181006125157.125.
==> Creating metadata subdirectory /usr/local/Caskroom/unity-ios-support-for-editor/.metadata/2018.2.6f1,c591d9a97a0b/20181006125157.125/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x00007fbc26a99360>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for unity-ios-support-for-editor; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=username USER=username USERNAME=username /usr/sbin/installer -pkg /usr/local/Caskroom/unity-ios-support-for-editor/2018.2.6f1,c591d9a97a0b/UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg -target / -verboseR
Password:
installer: Package name is iOSSupport
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing iOSSupport…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%3.438111
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:%3.489992
installer:PHASE:Writing files…
installer:%4.016214
installer:PHASE:Writing files…
installer:%7.699767
installer:PHASE:Writing files…
installer:%11.646430
installer:PHASE:Writing files…
installer:%14.277539
installer:PHASE:Writing files…
installer:%18.224203
installer:PHASE:Writing files…
installer:%21.644645
installer:PHASE:Writing files…
installer:%25.328197
installer:PHASE:Writing files…
installer:%28.748639
installer:PHASE:Writing files…
installer:%32.169081
installer:PHASE:Writing files…
installer:%35.589523
installer:PHASE:Writing files…
installer:%39.009964
installer:PHASE:Writing files…
installer:%41.904184
installer:PHASE:Writing files…
installer:%45.324626
installer:PHASE:Writing files…
installer:%48.745068
installer:PHASE:Writing files…
installer:%52.165510
installer:PHASE:Writing files…
installer:%55.322840
installer:PHASE:Writing files…
installer:%59.006393
installer:PHASE:Writing files…
installer:%62.689946
installer:PHASE:Writing files…
installer:%66.373498
installer:PHASE:Writing files…
installer:%69.793940
installer:PHASE:Writing files…
installer:%72.951271
installer:PHASE:Writing files…
installer:%76.371713
installer:PHASE:Writing files…
installer:%79.529044
installer:PHASE:Writing files…
installer:%82.949485
installer:PHASE:Writing files…
installer:%86.106816
installer:PHASE:Writing files…
installer:%89.264147
installer:PHASE:Writing files…
installer:%91.632145
installer:PHASE:Writing files…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 2018.2.6f1,c591d9a97a0b of Cask unity-ios-support-for-editor
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=username USER=username USERNAME=username /usr/sbin/installer -pkg /usr/local/Caskroom/unity-ios-support-for-editor/2018.2.6f1,c591d9a97a0b/UnitySetup-iOS-Support-for-Editor-2018.2.6f1.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is iOSSupport
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing iOSSupport…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%3.438111
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:%3.489992
installer:PHASE:Writing files…
installer:%4.016214
installer:PHASE:Writing files…
installer:%7.699767
installer:PHASE:Writing files…
installer:%11.646430
installer:PHASE:Writing files…
installer:%14.277539
installer:PHASE:Writing files…
installer:%18.224203
installer:PHASE:Writing files…
installer:%21.644645
installer:PHASE:Writing files…
installer:%25.328197
installer:PHASE:Writing files…
installer:%28.748639
installer:PHASE:Writing files…
installer:%32.169081
installer:PHASE:Writing files…
installer:%35.589523
installer:PHASE:Writing files…
installer:%39.009964
installer:PHASE:Writing files…
installer:%41.904184
installer:PHASE:Writing files…
installer:%45.324626
installer:PHASE:Writing files…
installer:%48.745068
installer:PHASE:Writing files…
installer:%52.165510
installer:PHASE:Writing files…
installer:%55.322840
installer:PHASE:Writing files…
installer:%59.006393
installer:PHASE:Writing files…
installer:%62.689946
installer:PHASE:Writing files…
installer:%66.373498
installer:PHASE:Writing files…
installer:%69.793940
installer:PHASE:Writing files…
installer:%72.951271
installer:PHASE:Writing files…
installer:%76.371713
installer:PHASE:Writing files…
installer:%79.529044
installer:PHASE:Writing files…
installer:%82.949485
installer:PHASE:Writing files…
installer:%86.106816
installer:PHASE:Writing files…
installer:%89.264147
installer:PHASE:Writing files…
installer:%91.632145
installer:PHASE:Writing files…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:96:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:124:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:11:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.6-114-g8883735
==> macOS
10.13.6
==> SIP
Enabled
==> Java
11, 1.8.0_144
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4041 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
HOMEBREW_CASK_OPTS="--require-sha"
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/tcsh"
```

#### Output of `brew tap`

```
Updating Homebrew...
beeftornado/rmtree
homebrew/cask
homebrew/core
homebrew/services
```

Notes the same problem occoured in other machine (using zsh)

**Comment by brianmorton** [comment]
Were you previously using this cask and it has just stopped working recently?
