### ISSUE TITLE
Cocktail 12.0.1 sha256 mismatch

### ISSUE THREAD

**Issue by todeveni** [Homebrew/homebrew-cask#53145]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Cocktail 12.0.1 sha256sum mismatch.

```
==> Upgrading 1 outdated package:
cocktail 12.0.0.10 -> 12.0.1
==> Satisfying dependencies
==> Downloading https://www.maintain.se/downloads/sparkle/mojave/Cocktail_12.0.1.zip
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'cocktail'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
==> Purging files for version 12.0.1 of Cask cocktail
Error: Checksum for Cask 'cocktail' does not match.

Expected: 6a00bae70a5befa7fb9467c1320e8818939e5f074deadd70177021fbf4694b07
Actual:   a77cda30300b7ea943908dd57df365ce2cdf1d801230f0fc2fb9954fefb1c93f
```

```
$ curl -s https://www.maintain.se/downloads/sparkle/mojave/Cocktail_12.0.1.zip | gsha256sum
a77cda30300b7ea943908dd57df365ce2cdf1d801230f0fc2fb9954fefb1c93f  -
```

#### Command that failed

```
brew cask upgrade cocktail
```

#### Output of command with `--force --verbose --debug`

```
==> Upgrading 1 outdated package:
cocktail 12.0.0.10 -> 12.0.1
==> Started upgrade process for Cask cocktail
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://www.maintain.se/downloads/sparkle/mojave/Cocktail_12.0.1.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --location --silent --head https://www.maintain.se/downloads/sparkle/mojave/Cocktail_12.0.1.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --location --silent --head https://www.maintain.se/downloads/sparkle/mojave/Cocktail_12.0.1.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/toniv/Library/Caches/Homebrew/downloads/540627dead2feb46e9b386ef06f8a343ccea44af5cf40310043118b9bb00850a--Cocktail_12.0.1.zip.incomplete https://www.maintain.se/downloads/sparkle/mojave/Cocktail_12.0.1.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3055k  100 3055k    0     0   711k      0  0:00:04  0:00:04 --:--:--  712k
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/toniv/Library/Caches/Homebrew/downloads/540627dead2feb46e9b386ef06f8a343ccea44af5cf40310043118b9bb00850a--Cocktail_12.0.1.zip
/usr/bin/xattr -p com.apple.quarantine /Users/toniv/Library/Caches/Homebrew/downloads/540627dead2feb46e9b386ef06f8a343ccea44af5cf40310043118b9bb00850a--Cocktail_12.0.1.zip
==> /Users/toniv/Library/Caches/Homebrew/downloads/540627dead2feb46e9b386ef06f8a343ccea44af5cf40310043118b9bb00850a--Cocktail_12.0.1.zip is not quarantined
==> Quarantining /Users/toniv/Library/Caches/Homebrew/downloads/540627dead2feb46e9b386ef06f8a343ccea44af5cf40310043118b9bb00850a--Cocktail_12.0.1.zip
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/toniv/Library/Caches/Homebrew/downloads/540627dead2feb46e9b386ef06f8a343ccea44af5cf40310043118b9bb00850a--Cocktail_12.0.1.zip https://www.maintain.se/downloads/sparkle/mojave/Cocktail_12.0.1.zip https://www.maintain.se/cocktail/
==> Downloaded to -> /Users/toniv/Library/Caches/Homebrew/downloads/540627dead2feb46e9b386ef06f8a343ccea44af5cf40310043118b9bb00850a--Cocktail_12.0.1.zip
==> Verifying SHA-256 checksum for Cask 'cocktail'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
==> Purging files for version 12.0.1 of Cask cocktail
Error: Checksum for Cask 'cocktail' does not match.

Expected: 6a00bae70a5befa7fb9467c1320e8818939e5f074deadd70177021fbf4694b07
Actual:   a77cda30300b7ea943908dd57df365ce2cdf1d801230f0fc2fb9954fefb1c93f
File:     /Users/toniv/Library/Caches/Homebrew/downloads/540627dead2feb46e9b386ef06f8a343ccea44af5cf40310043118b9bb00850a--Cocktail_12.0.1.zip

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/verify.rb:21:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:157:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:73:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.7
==> macOS
10.14
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4033 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (204 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1181 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (155 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
thoughtbot/formulae
```

**Comment by todeveni** [comment]
> Were you not able to follow the linked instructions?

Yes. Just pointing out that you made a commit/update with a bad checksum.
Just trying to help.

**Comment by vitorgalvao** [comment]
> Just pointing out that you made a commit/update with a bad checksum.

No commit is made with a bad checksum, as they’re all checked by the CI. This disparity happens when upstream updates the app in place.

> Yes.

> Just trying to help.

And I was making a genuine question. The linked instructions *specifically ask* (emphasis added):

> If you’re having trouble, open an issue explaining your steps so far and **why you’re having trouble submitting the update**.

So I want to know where you had the trouble so I can help.

**Comment by todeveni** [comment]
> No commit is made with a bad checksum, as they’re all checked by the CI.  

Perhaps a look into the toolchain is in place then. Travis is doing a checks based on the underlying macOS version. Cocktail being one of the apps that has different versions for different OS.

The [commit](208f49490e044644d18f3b650d3cf04ec7e58775) was for Mojave (12.0.1) version, but [Travis checked](https://travis-ci.org/Homebrew/homebrew-cask/jobs/439035485#L322) High Sierra (11.6.3) version.

**Comment by vitorgalvao** [comment]
Nice catch. Thank you. Fixing now.
