### ISSUE TITLE
soundflowerbed exits install w/ hdiutil: attach failed

### ISSUE THREAD

**Issue by Neberheim** [Homebrew/homebrew-cask#53153]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Cask install of soundflowerbed fails with output `hdiutil: attach failed - no mountable file systems`

#### Command that failed

```
brew cask install soundflowerbed
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://github.com/mLupine/SoundflowerBed/releases/download/2.0.0-release/SoundflowerBed-2.0.0-release.dmg
Already downloaded: ~/Library/Caches/Homebrew/downloads/c88211108c907285860bba5b16b947b644f64502b114cff1b8edd76d8921511f--SoundflowerBed-2.0.0-release.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of ~/Library/Caches/Homebrew/downloads/c88211108c907285860bba5b16b947b644f64502b114cff1b8edd76d8921511f--SoundflowerBed-2.0.0-release.dmg
/usr/bin/xattr -p com.apple.quarantine ~/Library/Caches/Homebrew/downloads/c88211108c907285860bba5b16b947b644f64502b114cff1b8edd76d8921511f--SoundflowerBed-2.0.0-release.dmg
==> ~/Library/Caches/Homebrew/downloads/c88211108c907285860bba5b16b947b644f64502b114cff1b8edd76d8921511f--SoundflowerBed-2.0.0-release.dmg is quarantined
==> Downloaded to -> ~/Library/Caches/Homebrew/downloads/c88211108c907285860bba5b16b947b644f64502b114cff1b8edd76d8921511f--SoundflowerBed-2.0.0-release.dmg
==> Verifying SHA-256 checksum for Cask 'soundflowerbed'.
==> Installing Cask soundflowerbed
==> Cask::Installer#stage
hdiutil imageinfo ~/Library/Caches/Homebrew/downloads/c88211108c907285860bba5b16b947b644f64502b114cff1b8edd76d8921511f--SoundflowerBed-2.0.0-release.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for ~/Library/Caches/Homebrew/downloads/c88211108c907285860bba5b16b947b644f64502b114cff1b8edd76d8921511f--SoundflowerBed-2.0.0-release.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/8w/_ktf50353wn93lwh6m961v440000gn/T/d20181009-17836-drauxk ~/Library/Caches/Homebrew/downloads/c88211108c907285860bba5b16b947b644f64502b114cff1b8edd76d8921511f--SoundflowerBed-2.0.0-release.dmg
hdiutil convert -quiet -format UDTO -o /var/folders/8w/_ktf50353wn93lwh6m961v440000gn/T/d20181009-17836-drauxk/c88211108c907285860bba5b16b947b644f64502b114cff1b8edd76d8921511f--SoundflowerBed-2.0.0-release.cdr ~/Library/Caches/Homebrew/downloads/c88211108c907285860bba5b16b947b644f64502b114cff1b8edd76d8921511f--SoundflowerBed-2.0.0-release.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/8w/_ktf50353wn93lwh6m961v440000gn/T/d20181009-17836-drauxk /var/folders/8w/_ktf50353wn93lwh6m961v440000gn/T/d20181009-17836-drauxk/c88211108c907285860bba5b16b947b644f64502b114cff1b8edd76d8921511f--SoundflowerBed-2.0.0-release.cdr
hdiutil: attach failed - no mountable file systems
==> Purging files for version 2.0.0 of Cask soundflowerbed
Error: Failure while executing; `hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/8w/_ktf50353wn93lwh6m961v440000gn/T/d20181009-17836-drauxk /var/folders/8w/_ktf50353wn93lwh6m961v440000gn/T/d20181009-17836-drauxk/c88211108c907285860bba5b16b947b644f64502b114cff1b8edd76d8921511f--SoundflowerBed-2.0.0-release.cdr` exited with 1. Here's the output:
hdiutil: attach failed - no mountable file systems


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:17:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:155:in `block in mount'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:127:in `mount'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:117:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:120:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:127:in `block in extract_nestedly'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:124:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:182:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:72:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:94:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
/usr/bin occurs before /usr/local/bin
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
```

**Comment by Neberheim** [comment]
User error: After failing to mount an unrelated disk image and then known-good images, I discovered a process I had left running was inhibiting hdiutil, and killed it. Cask behavior is now as expected.
