### ISSUE TITLE
Wireshark won't install: Certificate used to sign package is not trusted.

### ISSUE THREAD

**Issue by twillowman** [Homebrew/homebrew-cask#53205]
#### General troubleshooting steps

- [√ ] I have retried my command with `--force` and the issue is still present.
- [√ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [√ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [ √] I ran `brew update-reset && brew update` and retried my command.
- [ √] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [√ ] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [√ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Can't install wireshark cask. The cask downloads correctly, then the installer fails with the error:
```
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=tyler USER=tyler USERNAME=tyler /usr/sbin/installer -pkg /usr/local/Caskroom/wireshark/2.6.3/Wireshark\ 2.6.3\ Intel\ 64.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Wireshark 2.6.3 Intel 64
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
```

#### Command that failed

```
brew cask install wireshark
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://www.wireshark.org/download/osx/Wireshark%202.6.3%20Intel%2064.dmg
Already downloaded: /Users/tyler/Library/Caches/Homebrew/downloads/db030c8e22824f6f880adaf438eea6f7476b5c360eaa1ebfb20bfc914b0a7cd8--Wireshark 2.6.3 Intel 64.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/tyler/Library/Caches/Homebrew/downloads/db030c8e22824f6f880adaf438eea6f7476b5c360eaa1ebfb20bfc914b0a7cd8--Wireshark 2.6.3 Intel 64.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/tyler/Library/Caches/Homebrew/downloads/db030c8e22824f6f880adaf438eea6f7476b5c360eaa1ebfb20bfc914b0a7cd8--Wireshark\ 2.6.3\ Intel\ 64.dmg
==> /Users/tyler/Library/Caches/Homebrew/downloads/db030c8e22824f6f880adaf438eea6f7476b5c360eaa1ebfb20bfc914b0a7cd8--Wireshark 2.6.3 Intel 64.dmg is quarantined
==> Downloaded to -> /Users/tyler/Library/Caches/Homebrew/downloads/db030c8e22824f6f880adaf438eea6f7476b5c360eaa1ebfb20bfc914b0a7cd8--Wireshark 2.6.3 Intel 64.dmg
==> Verifying SHA-256 checksum for Cask 'wireshark'.
==> Installing Cask wireshark
==> Cask::Installer#stage
hdiutil imageinfo /Users/tyler/Library/Caches/Homebrew/downloads/db030c8e22824f6f880adaf438eea6f7476b5c360eaa1ebfb20bfc914b0a7cd8--Wireshark\ 2.6.3\ Intel\ 64.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/tyler/Library/Caches/Homebrew/downloads/db030c8e22824f6f880adaf438eea6f7476b5c360eaa1ebfb20bfc914b0a7cd8--Wireshark 2.6.3 Intel 64.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/29/lyd3g2210jbb3_kfbjlxjyw80000gn/T/d20181010-12851-qqnfeb /Users/tyler/Library/Caches/Homebrew/downloads/db030c8e22824f6f880adaf438eea6f7476b5c360eaa1ebfb20bfc914b0a7cd8--Wireshark\ 2.6.3\ Intel\ 64.dmg
find . -print0
mkbom -s -i /var/folders/29/lyd3g2210jbb3_kfbjlxjyw80000gn/T/20181010-12851-1un7ogt.list -- /var/folders/29/lyd3g2210jbb3_kfbjlxjyw80000gn/T/20181010-12851-4x5iuw.bom
ditto --bom /var/folders/29/lyd3g2210jbb3_kfbjlxjyw80000gn/T/20181010-12851-4x5iuw.bom -- /private/var/folders/29/lyd3g2210jbb3_kfbjlxjyw80000gn/T/d20181010-12851-qqnfeb/dmg.tKtwDe /var/folders/29/lyd3g2210jbb3_kfbjlxjyw80000gn/T/d20181010-12851-1et7mqv
diskutil eject /private/var/folders/29/lyd3g2210jbb3_kfbjlxjyw80000gn/T/d20181010-12851-qqnfeb/dmg.tKtwDe
cp -pR /var/folders/29/lyd3g2210jbb3_kfbjlxjyw80000gn/T/d20181010-12851-1et7mqv/Wireshark\ 2.6.3\ Intel\ 64.pkg /usr/local/Caskroom/wireshark/2.6.3/Wireshark\ 2.6.3\ Intel\ 64.pkg
cp -pR /var/folders/29/lyd3g2210jbb3_kfbjlxjyw80000gn/T/d20181010-12851-1et7mqv/Read\ me\ first.rtf /usr/local/Caskroom/wireshark/2.6.3/Read\ me\ first.rtf
chmod -Rf +w /var/folders/29/lyd3g2210jbb3_kfbjlxjyw80000gn/T/d20181010-12851-1et7mqv
==> Verifying Gatekeeper status of /Users/tyler/Library/Caches/Homebrew/downloads/db030c8e22824f6f880adaf438eea6f7476b5c360eaa1ebfb20bfc914b0a7cd8--Wireshark 2.6.3 Intel 64.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/tyler/Library/Caches/Homebrew/downloads/db030c8e22824f6f880adaf438eea6f7476b5c360eaa1ebfb20bfc914b0a7cd8--Wireshark\ 2.6.3\ Intel\ 64.dmg
==> /Users/tyler/Library/Caches/Homebrew/downloads/db030c8e22824f6f880adaf438eea6f7476b5c360eaa1ebfb20bfc914b0a7cd8--Wireshark 2.6.3 Intel 64.dmg is quarantined
==> Propagating quarantine from /Users/tyler/Library/Caches/Homebrew/downloads/db030c8e22824f6f880adaf438eea6f7476b5c360eaa1ebfb20bfc914b0a7cd8--Wireshark 2.6.3 Intel 64.dmg to /usr/local/Caskroom/wireshark/2.6.3
/usr/bin/xattr -p com.apple.quarantine /Users/tyler/Library/Caches/Homebrew/downloads/db030c8e22824f6f880adaf438eea6f7476b5c360eaa1ebfb20bfc914b0a7cd8--Wireshark\ 2.6.3\ Intel\ 64.dmg
/bin/chmod -R u\+w /usr/local/Caskroom/wireshark/2.6.3
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5bbeb1ed\;Homebrew\\x20Cask\;318D45C3-01F7-4A97-ADE3-456A12F40507
==> Creating metadata directory /usr/local/Caskroom/wireshark/.metadata/2.6.3/20181011022728.275.
==> Creating metadata subdirectory /usr/local/Caskroom/wireshark/.metadata/2.6.3/20181011022728.275/Casks.
==> Installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x00007fd211378620>
==> Installing artifact of class Cask::Artifact::PreflightBlock
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for wireshark; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=tyler USER=tyler USERNAME=tyler /usr/sbin/installer -pkg /usr/local/Caskroom/wireshark/2.6.3/Wireshark\ 2.6.3\ Intel\ 64.pkg -target / -verboseR
installer: Package name is Wireshark 2.6.3 Intel 64
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
==> Reverting installation of artifact of class Cask::Artifact::PreflightBlock
==> Purging files for version 2.6.3 of Cask wireshark
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=tyler USER=tyler USERNAME=tyler /usr/sbin/installer -pkg /usr/local/Caskroom/wireshark/2.6.3/Wireshark\ 2.6.3\ Intel\ 64.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Wireshark 2.6.3 Intel 64
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:207:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:198:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.7-23-g17154ab
==> macOS
10.14
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4034 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
buo/cask-upgrade
homebrew/cask
homebrew/core
```

**Comment by commitay** [comment]
Please report this to Wireshark upstream.
