### ISSUE TITLE
`/usr/bin/xattr` exited with 1

### ISSUE THREAD

**Issue by pointlessone** [Homebrew/homebrew-cask#53219]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I'm trying to upgrade vagrant.

The command fails.

#### Command that failed

```
brew cask upgrade vagrant
```

#### Output of command with `--force --verbose --debug`

```
==> Upgrading 1 outdated package:
vagrant 2.1.2 -> 2.1.5
==> Started upgrade process for Cask vagrant
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://releases.hashicorp.com/vagrant/2.1.5/vagrant_2.1.5_x86_64.dmg
Already downloaded: /Users/pointlessone/Library/Caches/Homebrew/downloads/ea244660be021d8fa5f0d010139460e037213a9f92af066e182565e32b2e3b49--vagrant_2.1.5_x86_64.dmg
==> Checking quarantine support
/usr/bin/xattr
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
Error: Failure while executing; `/usr/bin/xattr` exited with 1. Here's the output:
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:17:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/cask/quarantine.rb:23:in `check_quarantine_support'
/usr/local/Homebrew/Library/Homebrew/cask/quarantine.rb:49:in `available?'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:50:in `quarantine'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:19:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:144:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:61:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:73:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.7-23-g17154ab
==> macOS
10.13.6
==> SIP
Enabled (custom configuration)

configuration:
apple internal: disabled
kext signing: disabled
filesystem protections: disabled
debugging restrictions: enabled
dtrace restrictions: enabled
nvram protections: enabled
basesystem verification: enabled
==> Java
1.8.0_112
==> Gatekeeper support
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
Error: Failure while executing; `/usr/bin/xattr` exited with 1. Here's the output:
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:17:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/cask/quarantine.rb:23:in `check_quarantine_support'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/doctor.rb:124:in `check_quarantine_support'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/doctor.rb:26:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew tap`

```
caryll/otfcc
caskformula/caskformula
codeclimate/formulae
eugenmayer/dockersync
homebrew/cask
homebrew/core
homebrew/nginx
homebrew/services
joshuaclayton/formulae
osx-cross/arm
osx-cross/avr
px4/px4
scribd/scribd
toolmantim/bksr
```

**Comment by vitorgalvao** [comment]
Ping @amyspark.

**Comment by amyspark** [comment]
Typo in the support check. I'll submit a pull request ASAP.

**Comment by amyspark** [comment]
@pointlessone You may also want to check your system Python installation. The exception you've obtained is caused by executing `xattr` with a system Python version other than 2.7.

**Comment by pointlessone** [comment]
I have next to 0 experience with Python. Could you please give me directions or a link to corresponding material elsewhere?

**Comment by amyspark** [comment]
@pointlessone sure!
- [This comment](https://github.com/Homebrew/homebrew-cask/issues/52128#issuecomment-424680522) explains why `xattr` doesn't work in certain MacOS versions.
- [Here's a StackOverflow question](https://superuser.com/questions/35256/how-can-i-change-the-default-python-version-on-snow-leopard) detailing how to change the Python version.
