### ISSUE TITLE
fluid app install not working

### ISSUE THREAD

**Issue by andyhubbert94** [Homebrew/homebrew-cask#53553]
#### General troubleshooting steps

- [x ] I have retried my command with `--force` and the issue is still present.
- [x ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x ] I made doubly sure this is not a [checksum does not match] -it is this error but see below (https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [ x] I ran `brew update-reset && brew update` and retried my command.
- [x ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Checksum doesn't match. I have checked and cask appears up to date, retried my download several times and ran all the other recommended steps. Nothing is working please see error below

#### Command that failed

```
brew cask upgrade
```

#### Output of command with `--force --verbose --debug`

```
brew cask upgrade --force --verbose --debug
Ignoring commonmarker-0.17.7.1 because its extensions are not built. Try: gem pristine commonmarker --version 0.17.7.1
Ignoring commonmarker-0.17.7.1 because its extensions are not built. Try: gem pristine commonmarker --version 0.17.7.1
Updating Homebrew...
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 1 outdated package:
fluid 1.8.6 -> 2.1
==> Started upgrade process for Cask fluid
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://fluidapp.com/dist/Fluid_2.1.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.7-38-g6626415\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --location --silent --head https://fluidapp.com/dist/Fluid_2.1.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.7-38-g6626415\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --location --silent --head https://fluidapp.com/dist/Fluid_2.1.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.7-38-g6626415\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/Andrew/Library/Caches/Homebrew/downloads/2319f86e0fdf73d29efdf3720bb8119762c16825d3d86fe6df2883556f2ed071--Fluid_2.1.zip.incomplete https://fluidapp.com/dist/Fluid_2.1.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8775k  100 8775k    0     0   521k      0  0:00:16  0:00:16 --:--:--  588k
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/Andrew/Library/Caches/Homebrew/downloads/2319f86e0fdf73d29efdf3720bb8119762c16825d3d86fe6df2883556f2ed071--Fluid_2.1.zip
/usr/bin/xattr -p com.apple.quarantine /Users/Andrew/Library/Caches/Homebrew/downloads/2319f86e0fdf73d29efdf3720bb8119762c16825d3d86fe6df2883556f2ed071--Fluid_2.1.zip
==> /Users/Andrew/Library/Caches/Homebrew/downloads/2319f86e0fdf73d29efdf3720bb8119762c16825d3d86fe6df2883556f2ed071--Fluid_2.1.zip is not quarantined
==> Quarantining /Users/Andrew/Library/Caches/Homebrew/downloads/2319f86e0fdf73d29efdf3720bb8119762c16825d3d86fe6df2883556f2ed071--Fluid_2.1.zip
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/Andrew/Library/Caches/Homebrew/downloads/2319f86e0fdf73d29efdf3720bb8119762c16825d3d86fe6df2883556f2ed071--Fluid_2.1.zip https://fluidapp.com/dist/Fluid_2.1.zip https://fluidapp.com/
==> Downloaded to -> /Users/Andrew/Library/Caches/Homebrew/downloads/2319f86e0fdf73d29efdf3720bb8119762c16825d3d86fe6df2883556f2ed071--Fluid_2.1.zip
==> Verifying SHA-256 checksum for Cask 'fluid'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
==> Purging files for version 2.1 of Cask fluid
Error: Checksum for Cask 'fluid' does not match.

Expected: aa99e0218d8de548a292751f2e3145f299ddb7d6acf929b9d05b8d88db86e8e5
Actual:   7b27dfcec1b74209496eb1150f38e464c95ae695dc9d95f1eab3d11925189e58
File:     /Users/Andrew/Library/Caches/Homebrew/downloads/2319f86e0fdf73d29efdf3720bb8119762c16825d3d86fe6df2883556f2ed071--Fluid_2.1.zip

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/verify.rb:21:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:157:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:73:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew Version
1.7.7-38-g6626415
==> macOS
10.14
==> SIP
Enabled
==> Java
1.8.0_112
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4038 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (204 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1181 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
brew tap
Ignoring commonmarker-0.17.7.1 because its extensions are not built. Try: gem pristine commonmarker --version 0.17.7.1
Ignoring commonmarker-0.17.7.1 because its extensions are not built. Try: gem pristine commonmarker --version 0.17.7.1
Updating Homebrew...
heroku/brew
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/dupes
homebrew/services
```

#### Output of `brew cask _stanza version fluid`

```
2.1
```

#### More info

Current version download link: https://fluidapp.com/dist/Fluid_2.1.zip

Thanks! This is my first bug report so please be kind!!

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/53560

**Comment by leos** [comment]
This isn't fixed - the PR referenced is still open and the download still doesn't work. Please reopen.

**Comment by vitorgalvao** [comment]
@leos No. There’s no point in keeping this open if the fix is already on the way. It’s just noise.
