### ISSUE TITLE
Brew cask install filezilla fail

### ISSUE THREAD

**Issue by tientq** [Homebrew/homebrew-cask#53634]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I cannot install `filezilla`

#### Command that failed

```
brew cask install filezilla
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install filezilla --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.7-61-g473155e\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --location --silent --head https://download.filezilla-project.org/client/FileZilla_3.37.4_macosx-x86.app.tar.bz2
==> Downloading https://download.filezilla-project.org/client/FileZilla_3.37.4_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.7-61-g473155e\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --location --silent --head https://download.filezilla-project.org/client/FileZilla_3.37.4_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.7-61-g473155e\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --location --head --range 0-1 --write-out \%\{http_code\} --output /dev/null https://download.filezilla-project.org/client/FileZilla_3.37.4_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.7-61-g473155e\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/quangtien92/Library/Caches/Homebrew/downloads/4751d257d12ebd67ecff5e3a69b4f4dd62a81f638dbc1a08bd1f2b3f743ea219--FileZilla_3.37.4_macosx-x86.app.tar.bz2.incomplete https://download.filezilla-project.org/client/FileZilla_3.37.4_macosx-x86.app.tar.bz2
** Resuming transfer from byte position 10640959
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 416
Error: Download failed on Cask 'filezilla' with message: Download failed: https://download.filezilla-project.org/client/FileZilla_3.37.4_macosx-x86.app.tar.bz2
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:298:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:293:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:18:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:144:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:61:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:89:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew Version
1.7.7-61-g473155e
==> macOS
10.14
==> SIP
Enabled
==> Java
1.8.0_181
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4039 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (204 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
$ brew tap
homebrew/cask
homebrew/cask-versions
homebrew/core
```

#### Others

I don't have any `.curlrc` file  
I have write permission to `~/Applications` folder

**Comment by LanikSJ** [comment]
This was discussed recently: https://github.com/Homebrew/homebrew-cask/issues/52149

I've gotten around the problem with some of the comments in the above issue.

**Comment by tientq** [comment]
I found some information:

I run `brew config`
```
$ brew config
HOMEBREW_VERSION: 1.7.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: c54a657cd5987cba2718f7012a55101324fde8b1
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b93d52146b4e30e5f43feea44c0d3e8e5f9634fa
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: N/A
```

Then try again with new version of curl
1. Remove incomplete file if exist
```
rm ~/Library/Caches/Homebrew/downloads/{HASH}--FileZilla_3.37.4_macosx-x86.app.tar.bz2.incomplete
```
2. Install latest version of `curl`
```
brew install curl
```
3. Force brew to use new version of `curl`
```
export HOMEBREW_FORCE_BREWED_CURL=1
```
Check `brew config`
```
$ brew config
HOMEBREW_VERSION: 1.7.7-61-g473155e
...
Curl: 7.61.1 => /usr/local/opt/curl/bin/curl
...
macOS: 10.14-x86_64
...
```
4. Try to install `filezilla`
```
brew cask install filezilla --force --verbose --debug
```

And it's worked

**Comment by fredsavoir** [comment]
nope

**Comment by fredsavoir** [comment]
stil got the same error : /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit

**Comment by fredsavoir** [comment]
ok need to rm -Rv ~/Library/Caches/Homebrew/downloads/
then exit terminal then works :)

**Comment by bheimbaugh** [comment]
You don't have to remove the entire downloads cache, just `rm ~/Library/Caches/Homebrew/downloads/*FileZilla*`
```
$ brew config | grep curl
Curl: 7.62.0 => /usr/local/opt/curl/bin/curl
$ rm ~/Library/Caches/Homebrew/downloads/*FileZilla*
$ brew cask install filezilla
Updating Homebrew...
==> Satisfying dependencies
==> Downloading https://download.filezilla-project.org/client/FileZilla_3.38.1_macosx-x8
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'filezilla'.
==> Installing Cask filezilla
==> Moving App 'FileZilla.app' to '/Applications/FileZilla.app'.
🍺  filezilla was successfully installed!
```

**Comment by krokofant** [comment]
Why doesn't brew update the embedded curl?
