### ISSUE TITLE
Installation of Snagit 2018 from cask fails

### ISSUE THREAD

**Issue by ladyadalovelace** [Homebrew/homebrew-cask#54192]
#### Description of issue

Attempting to install Snagit 2018 using `brew cask install `fails with `"Error: It seems the App source '/usr/local/Caskroom/snagit/2018/Snagit 2018.app' is not there."

#### Command that failed

```
brew cask install snagit
```

#### Output of command with `--force --verbose --debug`

```
==> Satisfying dependencies
==> Downloading https://download.techsmith.com/snagitmac/enu/Snagit.dmg
Already downloaded: /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg
==> No SHA-256 checksum defined for Cask 'snagit', skipping verification.
==> Installing Cask snagit
==> Purging files for version 2018 of Cask snagit
Error: It seems the App source '/usr/local/Caskroom/snagit/2018/Snagit 2018.app' is not there.
LyraOS:~ melodylam$ brew cask install snagit --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.techsmith.com/snagitmac/enu/Snagit.dmg
Already downloaded: /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg
==> /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg is quarantined
==> Downloaded to -> /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg
==> No SHA-256 checksum defined for Cask 'snagit', skipping verification.
==> Installing Cask snagit
==> Cask::Installer#stage
hdiutil imageinfo /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/8f/g21dd_qd2qb_z012skp4_78w0000gn/T/d20181028-8448-1nr82gh /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg
find . -print0
mkbom -s -i /var/folders/8f/g21dd_qd2qb_z012skp4_78w0000gn/T/20181028-8448-18ybhv6.list -- /var/folders/8f/g21dd_qd2qb_z012skp4_78w0000gn/T/20181028-8448-1tjr2h4.bom
ditto --bom /var/folders/8f/g21dd_qd2qb_z012skp4_78w0000gn/T/20181028-8448-1tjr2h4.bom -- /private/var/folders/8f/g21dd_qd2qb_z012skp4_78w0000gn/T/d20181028-8448-1nr82gh/dmg.VchGEx /var/folders/8f/g21dd_qd2qb_z012skp4_78w0000gn/T/d20181028-8448-ldty9w
diskutil eject /private/var/folders/8f/g21dd_qd2qb_z012skp4_78w0000gn/T/d20181028-8448-1nr82gh/dmg.VchGEx
cp -pR /var/folders/8f/g21dd_qd2qb_z012skp4_78w0000gn/T/d20181028-8448-ldty9w/.resources/. /usr/local/Caskroom/snagit/2018/.resources
cp -pR /var/folders/8f/g21dd_qd2qb_z012skp4_78w0000gn/T/d20181028-8448-ldty9w/Snagit\ 2019.app/. /usr/local/Caskroom/snagit/2018/Snagit\ 2019.app
chmod -Rf +w /var/folders/8f/g21dd_qd2qb_z012skp4_78w0000gn/T/d20181028-8448-ldty9w
==> Verifying Gatekeeper status of /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg
==> /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg is quarantined
==> Propagating quarantine from /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg to /usr/local/Caskroom/snagit/2018
/usr/bin/xattr -p com.apple.quarantine /Users/melodylam/Library/Caches/Homebrew/downloads/8edfc097459b681734e136b461a9f04bd64d28513753dcc61cc063f1fec7c235--Snagit.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5bd61ceb\;Homebrew\\x20Cask\;9386F963-980E-4D78-BCE2-2D8C3798379B
==> Creating metadata directory /usr/local/Caskroom/snagit/.metadata/2018/20181028215440.539.
==> Creating metadata subdirectory /usr/local/Caskroom/snagit/.metadata/2018/20181028215440.539/Casks.
==> Installing artifacts
==> 1 artifact/s defined
#<SortedSet:0x00007fea1e6002d8>
==> Installing artifact of class Cask::Artifact::App
==> Purging files for version 2018 of Cask snagit
Error: It seems the App source '/usr/local/Caskroom/snagit/2018/Snagit 2018.app' is not there.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:39:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:11:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:207:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:198:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.8.0-60-g3e44ed6
==> macOS
10.14
==> SIP
Enabled
==> Java
11.0.1
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4040 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.59.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask#reporting-bugs

https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#source-is-not-there-error

**Comment by ladyadalovelace** [comment]
Ah, my apologies -- I didn't realize that my error was already there.

I've tried using the  `cask-repair snagit` command and I'm getting

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Not sure why. Should I open a new issue? Sorry, I'm pretty new to contributing to github.
