### ISSUE TITLE
MagicaVoxel install is broken

### ISSUE THREAD

**Issue by itsjavi** [Homebrew/homebrew-cask#54239]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I run `brew cask install magicavoxel` (tried with homebrew 1.8.0, updated)

Output is:
```
==> Satisfying dependencies
==> Downloading http://192.241.207.218/uploads/MagicaVoxel-0.99.1-alpha-mac.zip
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'magicavoxel'.
==> Installing Cask magicavoxel
==> Purging files for version 0.99.1-alpha of Cask magicavoxel
Error: It seems the App Suite source '/usr/local/Caskroom/magicavoxel/0.99.1-alpha/MagicaVoxel-0.99.1-alpha-mac' is not there.
```

#### Command that failed

```
`brew cask install magicavoxel`
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://192.241.207.218/uploads/MagicaVoxel-0.99.1-alpha-mac.zip
Already downloaded: /Users/javi/Library/Caches/Homebrew/downloads/342601b827e08b84f3b1c63462977efc576bcff87658fab28f0633673a92b850--MagicaVoxel-0.99.1-alpha-mac.zip
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/javi/Library/Caches/Homebrew/downloads/342601b827e08b84f3b1c63462977efc576bcff87658fab28f0633673a92b850--MagicaVoxel-0.99.1-alpha-mac.zip
/usr/bin/xattr -p com.apple.quarantine /Users/javi/Library/Caches/Homebrew/downloads/342601b827e08b84f3b1c63462977efc576bcff87658fab28f0633673a92b850--MagicaVoxel-0.99.1-alpha-mac.zip
==> /Users/javi/Library/Caches/Homebrew/downloads/342601b827e08b84f3b1c63462977efc576bcff87658fab28f0633673a92b850--MagicaVoxel-0.99.1-alpha-mac.zip is quarantined
==> Downloaded to -> /Users/javi/Library/Caches/Homebrew/downloads/342601b827e08b84f3b1c63462977efc576bcff87658fab28f0633673a92b850--MagicaVoxel-0.99.1-alpha-mac.zip
==> Verifying SHA-256 checksum for Cask 'magicavoxel'.
==> Installing Cask magicavoxel
==> Cask::Installer#stage
zipinfo -1 /Users/javi/Library/Caches/Homebrew/downloads/342601b827e08b84f3b1c63462977efc576bcff87658fab28f0633673a92b850--MagicaVoxel-0.99.1-alpha-mac.zip
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/javi/Library/Caches/Homebrew/downloads/342601b827e08b84f3b1c63462977efc576bcff87658fab28f0633673a92b850--MagicaVoxel-0.99.1-alpha-mac.zip
unzip /Users/javi/Library/Caches/Homebrew/downloads/342601b827e08b84f3b1c63462977efc576bcff87658fab28f0633673a92b850--MagicaVoxel-0.99.1-alpha-mac.zip -d /var/folders/rh/lrrbl3y90l1fbd2dnxv9x_4m0000gn/T/d20181030-26404-xupoyc
cp -pR /var/folders/rh/lrrbl3y90l1fbd2dnxv9x_4m0000gn/T/d20181030-26404-xupoyc/cache/. /usr/local/Caskroom/magicavoxel/0.99.1-alpha/cache
cp -pR /var/folders/rh/lrrbl3y90l1fbd2dnxv9x_4m0000gn/T/d20181030-26404-xupoyc/config/. /usr/local/Caskroom/magicavoxel/0.99.1-alpha/config
cp -pR /var/folders/rh/lrrbl3y90l1fbd2dnxv9x_4m0000gn/T/d20181030-26404-xupoyc/MagicaVoxel.app/. /usr/local/Caskroom/magicavoxel/0.99.1-alpha/MagicaVoxel.app
cp -pR /var/folders/rh/lrrbl3y90l1fbd2dnxv9x_4m0000gn/T/d20181030-26404-xupoyc/vox/. /usr/local/Caskroom/magicavoxel/0.99.1-alpha/vox
cp -pR /var/folders/rh/lrrbl3y90l1fbd2dnxv9x_4m0000gn/T/d20181030-26404-xupoyc/readme.txt /usr/local/Caskroom/magicavoxel/0.99.1-alpha/readme.txt
cp -pR /var/folders/rh/lrrbl3y90l1fbd2dnxv9x_4m0000gn/T/d20181030-26404-xupoyc/shader/. /usr/local/Caskroom/magicavoxel/0.99.1-alpha/shader
cp -pR /var/folders/rh/lrrbl3y90l1fbd2dnxv9x_4m0000gn/T/d20181030-26404-xupoyc/export/. /usr/local/Caskroom/magicavoxel/0.99.1-alpha/export
cp -pR /var/folders/rh/lrrbl3y90l1fbd2dnxv9x_4m0000gn/T/d20181030-26404-xupoyc/palette/. /usr/local/Caskroom/magicavoxel/0.99.1-alpha/palette
chmod -Rf +w /var/folders/rh/lrrbl3y90l1fbd2dnxv9x_4m0000gn/T/d20181030-26404-xupoyc
==> Verifying Gatekeeper status of /Users/javi/Library/Caches/Homebrew/downloads/342601b827e08b84f3b1c63462977efc576bcff87658fab28f0633673a92b850--MagicaVoxel-0.99.1-alpha-mac.zip
/usr/bin/xattr -p com.apple.quarantine /Users/javi/Library/Caches/Homebrew/downloads/342601b827e08b84f3b1c63462977efc576bcff87658fab28f0633673a92b850--MagicaVoxel-0.99.1-alpha-mac.zip
==> /Users/javi/Library/Caches/Homebrew/downloads/342601b827e08b84f3b1c63462977efc576bcff87658fab28f0633673a92b850--MagicaVoxel-0.99.1-alpha-mac.zip is quarantined
==> Propagating quarantine from /Users/javi/Library/Caches/Homebrew/downloads/342601b827e08b84f3b1c63462977efc576bcff87658fab28f0633673a92b850--MagicaVoxel-0.99.1-alpha-mac.zip to /usr/local/Caskroom/magicavoxel/0.99.1-alpha
/usr/bin/xattr -p com.apple.quarantine /Users/javi/Library/Caches/Homebrew/downloads/342601b827e08b84f3b1c63462977efc576bcff87658fab28f0633673a92b850--MagicaVoxel-0.99.1-alpha-mac.zip
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5bd8361e\;Homebrew\\x20Cask\;E2FB990F-73EA-445F-87A7-C0EE3E7B9636
==> Creating metadata directory /usr/local/Caskroom/magicavoxel/.metadata/0.99.1-alpha/20181030105402.732.
==> Creating metadata subdirectory /usr/local/Caskroom/magicavoxel/.metadata/0.99.1-alpha/20181030105402.732/Casks.
==> Installing artifacts
==> 1 artifact/s defined
#<SortedSet:0x00007fc5e9d8b2e0>
==> Installing artifact of class Cask::Artifact::Suite
==> Purging files for version 0.99.1-alpha of Cask magicavoxel
Error: It seems the App Suite source '/usr/local/Caskroom/magicavoxel/0.99.1-alpha/MagicaVoxel-0.99.1-alpha-mac' is not there.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:39:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:11:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:207:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:198:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'

```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.8.0-74-g2b3f855
==> macOS
10.14
==> SIP
Enabled
==> Java
11.0.1
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4042 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (207 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1181 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.59.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"

```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core

```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask#reporting-bugs

https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#source-is-not-there-error

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/54244
