### ISSUE TITLE
unable to upgrade pdk, no such file or directory

### ISSUE THREAD

**Issue by jonathanc-blinds** [Homebrew/homebrew-cask#54714]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

unable to upgrade puppetlabs/pdk cask. fails with `Error: No such file or directory @ rb_file_s_rename - (/usr/local/Caskroom/pdk/unknown, /usr/local/Caskroom/pdk/unknown.upgrading)`

#### Command that failed

```
brew cask upgrade pdk
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask upgrade pdk --force --verbose --debug
==> Upgrading 1 outdated package:
puppetlabs/puppet/pdk  -> 1.7.1.0
==> Started upgrade process for Cask pdk
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.puppet.com/mac/puppet5/10.13/x86_64/pdk-1.7.1.0-1.osx10.13.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.2-33-gf289d59\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.1\)\ curl/7.54.0 --location --silent --head https://downloads.puppet.com/mac/puppet5/10.13/x86_64/pdk-1.7.1.0-1.osx10.13.dmg
Already downloaded: /Users/jonathanc/Library/Caches/Homebrew/downloads/3e4c1bb1cf2c12c4b1bdcec9dc89277ef5743945ce6533a7e6f9e12ef7450155--pdk-1.7.1.0-1.osx10.13.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/jonathanc/Library/Caches/Homebrew/downloads/3e4c1bb1cf2c12c4b1bdcec9dc89277ef5743945ce6533a7e6f9e12ef7450155--pdk-1.7.1.0-1.osx10.13.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/jonathanc/Library/Caches/Homebrew/downloads/3e4c1bb1cf2c12c4b1bdcec9dc89277ef5743945ce6533a7e6f9e12ef7450155--pdk-1.7.1.0-1.osx10.13.dmg
==> /Users/jonathanc/Library/Caches/Homebrew/downloads/3e4c1bb1cf2c12c4b1bdcec9dc89277ef5743945ce6533a7e6f9e12ef7450155--pdk-1.7.1.0-1.osx10.13.dmg is quarantined
==> Downloaded to -> /Users/jonathanc/Library/Caches/Homebrew/downloads/3e4c1bb1cf2c12c4b1bdcec9dc89277ef5743945ce6533a7e6f9e12ef7450155--pdk-1.7.1.0-1.osx10.13.dmg
==> Verifying SHA-256 checksum for Cask 'pdk'.
==> Starting upgrade for Cask pdk
==> Un-installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x00007f94d0873360>
==> Un-installing artifact of class Cask::Artifact::Uninstall
==> Running uninstall process for pdk; your password may be necessary
==> Uninstalling packages:
/usr/sbin/pkgutil --pkgs=com.puppetlabs.pdk
Error: No such file or directory @ rb_file_s_rename - (/usr/local/Caskroom/pdk/unknown, /usr/local/Caskroom/pdk/unknown.upgrading)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:393:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:393:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:393:in `backup'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:389:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:76:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.8.2-33-gf289d59
==> macOS
10.14.1
==> SIP
Enabled
==> Java
11.0.1
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4051 casks)
/usr/local/Homebrew/Library/Taps/puppetlabs/homebrew-puppet (5 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (208 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1184 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.60.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Gems/2.3.0/gems/json-2.1.0/lib
/Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.1.0
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
puppetlabs/puppet
```

**Comment by vitorgalvao** [comment]
This is a problem on their end. You’re on `10.14` but they don’t cover that case in their cask.
