### ISSUE TITLE
Error when upgrading Plex Media Server

### ISSUE THREAD

**Issue by rolfmblindgren** [Homebrew/homebrew-cask#55166]
#### General troubleshooting steps

- [ X ] I have retried my command with `--force` and the issue is still present.
- [ X ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [  X ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [ X ] I ran `brew update-reset && brew update` and retried my command.
- [ X ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ X ] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [ X ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Can't upgrade or remove plex media server. 

#### Command that failed

```
brew cask upgrade
```

#### Output of command with `--force --verbose --debug`

```
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 4 outdated packages:
plex-media-server 1.12.1.4885-1046ba85f -> 1.13.9.5456-ecd600442, qt-creator 4.7.1 -> 4.7.2, rstudio 1.1.456 -> 1.1.463, texmaker 5.0.2 -> 5.0.3
==> Started upgrade process for Cask plex-media-server
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.plex.tv/plex-media-server/1.13.9.5456-ecd600442/PlexMediaServer-1.13.9.5456-ecd600442-OSX.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.2-96-g4021aa8\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://downloads.plex.tv/plex-media-server/1.13.9.5456-ecd600442/PlexMediaServer-1.13.9.5456-ecd600442-OSX.zip
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/8c94199798d5a853d8c4a0cf3d755ce4e89d481de8f81b9a92e56564e2f41a05--PlexMediaServer-1.13.9.5456-ecd600442-OSX.zip
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/admin/Library/Caches/Homebrew/downloads/8c94199798d5a853d8c4a0cf3d755ce4e89d481de8f81b9a92e56564e2f41a05--PlexMediaServer-1.13.9.5456-ecd600442-OSX.zip
/usr/bin/xattr -p com.apple.quarantine /Users/admin/Library/Caches/Homebrew/downloads/8c94199798d5a853d8c4a0cf3d755ce4e89d481de8f81b9a92e56564e2f41a05--PlexMediaServer-1.13.9.5456-ecd600442-OSX.zip
==> /Users/admin/Library/Caches/Homebrew/downloads/8c94199798d5a853d8c4a0cf3d755ce4e89d481de8f81b9a92e56564e2f41a05--PlexMediaServer-1.13.9.5456-ecd600442-OSX.zip is quarantined
==> Downloaded to -> /Users/admin/Library/Caches/Homebrew/downloads/8c94199798d5a853d8c4a0cf3d755ce4e89d481de8f81b9a92e56564e2f41a05--PlexMediaServer-1.13.9.5456-ecd600442-OSX.zip
==> Verifying SHA-256 checksum for Cask 'plex-media-server'.
==> Starting upgrade for Cask plex-media-server
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00007f997963e650>
==> Un-installing artifact of class Cask::Artifact::Uninstall
==> Running uninstall process for plex-media-server; your password may be necessary
==> Removing launchctl service com.plexapp.mediaserver
/bin/launchctl list com.plexapp.mediaserver
/usr/bin/sudo -E -- /bin/launchctl list com.plexapp.mediaserver
/bin/launchctl list
Error: Failure while executing; `/bin/launchctl list` exited with 1.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:17:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:117:in `running_processes'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:129:in `block in uninstall_quit'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:128:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:128:in `uninstall_quit'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:60:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:56:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:56:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:429:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:425:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:388:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:76:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
beagle          crc32c          pulumi          sourcekitten    xtensor

cartr/qt4
homebrew/cask
homebrew/core
homebrew/dupes
homebrew/science
homebrew/services
kabel/php-ext
linuxbrew/xorg
```

**Comment by vitorgalvao** [comment]
Your `brew cask doctor` is incomplete.
