### ISSUE TITLE
Unable to install dashlane using brew due to invalid checksum

### ISSUE THREAD

**Issue by steinim** [Homebrew/homebrew-cask#55288]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Unable to install dashlane using brew due to invalid checksum.

I followed the instructions from https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error , but no cigar.

#### Command that failed

```
brew cask upgrade dashlane
```

#### Output of command with `--force --verbose --debug`

```
➜  ~  brew cask upgrade dashlane --force --verbose --debug
==> Upgrading 1 outdated package:
dashlane latest -> 6.1844.0
==> Started upgrade process for Cask dashlane
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://www.dashlane.com/directdownload?platform=mac
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.3-4-g7241156\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.1\)\ curl/7.54.0 --location --silent --head https://www.dashlane.com/directdownload\?platform=mac
Already downloaded: /Users/simo/Library/Caches/Homebrew/downloads/1c5d00fdc0eb6dd748d0629694a9ef5c7a766325875b82355896680eb716c7f2--directdownload?platform=mac
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/simo/Library/Caches/Homebrew/downloads/1c5d00fdc0eb6dd748d0629694a9ef5c7a766325875b82355896680eb716c7f2--directdownload?platform=mac
/usr/bin/xattr -p com.apple.quarantine /Users/simo/Library/Caches/Homebrew/downloads/1c5d00fdc0eb6dd748d0629694a9ef5c7a766325875b82355896680eb716c7f2--directdownload\?platform=mac
==> /Users/simo/Library/Caches/Homebrew/downloads/1c5d00fdc0eb6dd748d0629694a9ef5c7a766325875b82355896680eb716c7f2--directdownload?platform=mac is quarantined
==> Downloaded to -> /Users/simo/Library/Caches/Homebrew/downloads/1c5d00fdc0eb6dd748d0629694a9ef5c7a766325875b82355896680eb716c7f2--directdownload?platform=mac
==> Verifying SHA-256 checksum for Cask 'dashlane'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
==> Purging files for version 6.1844.0 of Cask dashlane
Error: Checksum for Cask 'dashlane' does not match.

Expected: 24b8cfca4698cdbbf53309b3abe09a5308f888fc0e46096b53d596c2c30a4b3b
Actual:   829b315e2963f88e69e1a392897ac05d3e4b2007db19d6c3c6ed7501df0fc73c
File:     /Users/simo/Library/Caches/Homebrew/downloads/1c5d00fdc0eb6dd748d0629694a9ef5c7a766325875b82355896680eb716c7f2--directdownload?platform=mac

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/verify.rb:21:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:157:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:73:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
➜  ~  brew cask doctor
==> Homebrew Version
1.8.3-4-g7241156
==> macOS
10.14.1
==> SIP
Enabled
==> Java
1.8.0_192
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4062 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (209 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.60.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
➜  ~  brew tap
homebrew/bundle
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by vitorgalvao** [comment]
>  followed the instructions from https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error , but no cigar.

Why not? I’ll need you to be specific.

**Comment by ran-dall** [comment]
@steinim I'm pretty sure the wrong URL was on the cask. Which is why you where getting that message. I updated the cask just now for you! 🤘https://github.com/Homebrew/homebrew-cask/pull/55302
