### ISSUE TITLE
'brew uninstall xquartz' does NOT remove XQuartz

### ISSUE THREAD

**Issue by mi-hol** [Homebrew/homebrew-cask#55431]
#### General troubleshooting steps

- [ x] I have retried my command with `--force` and the issue is still present.
- [ x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [ x] I ran `brew update-reset && brew update` and retried my command.
- [ x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x ] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

There was an outdated version of XQuartz on a few Macs that I tried to remove but didn't succeed yet.

# Summary:
1. XQuartz 2.7.5 (published 2013-11-10) & brew 1.7.1, **unclear how XQuartz was installed**!
2.  brew upgrade & brew cask reinstall xquartz => updated to XQuartz 2.7.11 failed, but 'brew config reports now XQuartz 2.7.11
3. uninstall xquartz => Error: No such keg: /usr/local/Cellar/xquartz 
Any suggestion what I should try next to uninstall XQuartz?

#### Command that failed

```
brew cask reinstall xquartz
==> Satisfying dependencies
==> Downloading https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
Already downloaded: /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> Verifying SHA-256 checksum for Cask 'xquartz'.
==> Uninstalling Cask xquartz
==> Running uninstall process for xquartz; your password may be necessary
==> Removing launchctl service org.macosforge.xquartz.startx
Password:
==> Removing launchctl service org.macosforge.xquartz.privileged_startx
==> Uninstalling packages:
org.macosforge.xquartz.pkg
==> Removing files:
/opt/X11
/private/etc/manpaths.d/40-XQuartz
/private/etc/paths.d/40-XQuartz
==> Purging files for version 2.7.11 of Cask xquartz
==> Installing Cask xquartz
==> Running installer for xquartz; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is XQuartz 2.7.11
installer: Installing at base path /
installer: The install was successful.
Could not find domain for
==> Purging files for version 2.7.11 of Cask xquartz
Error: Failure while executing; `/bin/launchctl load /Library/LaunchAgents/org.macosforge.xquartz.startx.plist` exited with 112. Here's the output:
Could not find domain for


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/dsl/base.rb:14:in `system_command'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/xquartz.rb:22:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:39:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:39:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:22:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:122:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:11:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of command with `--force --verbose --debug`

```
administrator$ brew cask reinstall xquartz --verbose --debug xquartz
==> Cask::Installer#reinstall
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.4-3-g6f0ef7d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
Already downloaded: /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg is quarantined
==> Downloaded to -> /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> Verifying SHA-256 checksum for Cask 'xquartz'.
==> Installing Cask xquartz
==> Cask::Installer#stage
hdiutil imageinfo /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/xr/6sbl8wj13rzcjdxq2q6frm1m0000gn/T/d20181126-14140-1n6o6rd /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
find . -print0
mkbom -s -i /var/folders/xr/6sbl8wj13rzcjdxq2q6frm1m0000gn/T/20181126-14140-ot2edj.list -- /var/folders/xr/6sbl8wj13rzcjdxq2q6frm1m0000gn/T/20181126-14140-119g6h5.bom
ditto --bom /var/folders/xr/6sbl8wj13rzcjdxq2q6frm1m0000gn/T/20181126-14140-119g6h5.bom -- /private/var/folders/xr/6sbl8wj13rzcjdxq2q6frm1m0000gn/T/d20181126-14140-1n6o6rd/dmg.I0nkxw /var/folders/xr/6sbl8wj13rzcjdxq2q6frm1m0000gn/T/d20181126-14140-7fdywt
diskutil eject /private/var/folders/xr/6sbl8wj13rzcjdxq2q6frm1m0000gn/T/d20181126-14140-1n6o6rd/dmg.I0nkxw
chmod +rw /var/folders/xr/6sbl8wj13rzcjdxq2q6frm1m0000gn/T/d20181126-14140-7fdywt/XQuartz.pkg
cp -p /var/folders/xr/6sbl8wj13rzcjdxq2q6frm1m0000gn/T/d20181126-14140-7fdywt/XQuartz.pkg /usr/local/Caskroom/xquartz/2.7.11/XQuartz.pkg
==> Verifying Gatekeeper status of /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg is quarantined
==> Propagating quarantine from /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg to /usr/local/Caskroom/xquartz/2.7.11
/usr/bin/xattr -p com.apple.quarantine /Users/administrator/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5bf53898\;Homebrew\\x20Cask\;6628C07A-139D-4315-9080-B9DE4B0A575A
==> Creating metadata directory /usr/local/Caskroom/xquartz/.metadata/2.7.11/20181126174511.631.
==> Creating metadata subdirectory /usr/local/Caskroom/xquartz/.metadata/2.7.11/20181126174511.631/Casks.
==> Installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x00007fb7426c3940>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for xquartz; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=administrator USER=administrator USERNAME=administrator /usr/sbin/installer -pkg /usr/local/Caskroom/xquartz/2.7.11/XQuartz.pkg -target / -verboseR
Password:
installer: Package name is XQuartz 2.7.11
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing XQuartz 2.7.11…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%7.424403
installer:PHASE:Writing files…
installer:%15.657996
installer:PHASE:Writing files…
installer:%21.833190
installer:PHASE:Writing files…
installer:%28.008384
installer:PHASE:Writing files…
installer:%30.066782
installer:PHASE:Writing files…
installer:%32.125181
installer:PHASE:Writing files…
installer:%34.183579
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:%36.241977
installer:PHASE:Writing files…
installer:%38.300375
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:%58.885949
installer:PHASE:Running package scripts…
installer:%63.944965
installer:PHASE:Moving items into place…
installer:%64.975656
installer:PHASE:Moving items into place…
installer:%66.013976
installer:PHASE:Moving items into place…
installer:%67.047973
installer:PHASE:Moving items into place…
installer:%68.072477
installer:PHASE:Moving items into place…
installer:%69.106462
installer:PHASE:Moving items into place…
installer:%83.908566
installer:PHASE:Running package scripts…
installer:%84.931672
installer:PHASE:Running package scripts…
installer:%85.643531
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:%86.077613
installer:PHASE:Writing package receipts…
installer:PHASE:Validating packages…
installer:%97.750000
installer:STATUS:Running installer actions…
installer:STATUS:
installer:PHASE:Finishing the Installation…
installer:STATUS:
installer:%100.000000
installer:PHASE:The software was successfully installed.
installer: The upgrade was successful.
==> Installing artifact of class Cask::Artifact::PostflightBlock
/usr/bin/defaults write com.apple.applescript ApplicationMap -dict-add X11 file://localhost/Applications/Utilities/XQuartz.app/
/bin/launchctl load /Library/LaunchAgents/org.macosforge.xquartz.startx.plist
Could not find domain for
==> Purging files for version 2.7.11 of Cask xquartz
Error: Failure while executing; `/bin/launchctl load /Library/LaunchAgents/org.macosforge.xquartz.startx.plist` exited with 112. Here's the output:
Could not find domain for


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/dsl/base.rb:14:in `system_command'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/xquartz.rb:22:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:39:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:39:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:22:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:122:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:11:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'

```

#### Output of `brew cask doctor`

```
administrator$ brew cask doctor
==> Homebrew Version
1.8.4-3-g6f0ef7d
==> macOS
10.13.6
==> SIP
Enabled
==> Java
1.8.0_151, 1.7.0_76
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4070 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.60.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"

```

#### Output of `brew tap`

```
 administrator$ brew tap
homebrew/cask
homebrew/core

```

**Comment by mi-hol** [comment]
# Details
1.  Original situation:
I tried to uninstall XQuartz but its not being removed
```
brew uninstall --force xquartz
administrator$ brew config                                                                      
HOMEBREW_VERSION: >=1.7.1 (shallow or no git repository)
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap ORIGIN: (none)
Core tap HEAD: (none)
Core tap last commit: never
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: N/A
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_144, 1.7.0_76
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.0
**XQuartz: 2.7.5** => /opt/X11
```
 fixes tried:
```
brew update-reset && brew update
brew config
HOMEBREW_VERSION: 1.8.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2063a8a4d849b00f279ee2dd26e9f38745382ffc
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e5def19d72af783c8c5e3e763afce0debb9dc51d
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_151, 1.7.0_76
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.0
**XQuartz: 2.7.11** => /opt/X11

**administrator$ brew uninstall xquartz
Error: No such keg: /usr/local/Cellar/xquartz**
administrator$ brew uninstall --force xquartz
ll /usr/local/Cellar/x*
ls: /usr/local/Cellar/x*: No such file or directory
administrator$ ll /usr/local/Cellar/*
/usr/local/Cellar/md5sha1sum:
total 0
drwxr-xr-x  7 administrator  admin  238 Jul 29  2015 0.9.5
drwxr-xr-x  3 administrator  admin  102 Jul 29  2015 .
drwxr-xr-x  5 administrator  admin  170 Jun 21 21:11 ..

/usr/local/Cellar/sloccount:
total 0
drwxr-xr-x  3 administrator  admin  102 Jul 29  2015 .
drwxr-xr-x  9 administrator  admin  306 Jul 29  2015 2.26
drwxr-xr-x  5 administrator  admin  170 Jun 21 21:11 ..

/usr/local/Cellar/openssl:
total 0
drwxr-xr-x   5 administrator  admin  170 Jun 21 21:11 ..
drwxr-xr-x  13 administrator  staff  442 Nov 26 16:26 1.0.2q
drwxr-xr-x   3 administrator  staff  102 Nov 26 16:27 .
```

**Comment by reitermarkus** [comment]
`xquartz` is a cask, so you need to run `brew cask uninstall --force xquartz`.
