### ISSUE TITLE
Java (openjdk-11.0.1) cask fails to install

### ISSUE THREAD

**Issue by remeika** [Homebrew/homebrew-cask#55533]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Java cask fails to install; `sudo mv` command fails because source file does not exist.

#### Command that failed

```
$ brew cask install java
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install java --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_osx-x64_bin.tar.gz
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.4-9-g30c90dc\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.1\)\ curl/7.54.0 --location --silent --head https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_osx-x64_bin.tar.gz
Already downloaded: /Users/james.remeika/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/james.remeika/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/james.remeika/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
==> /Users/james.remeika/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz is quarantined
==> Downloaded to -> /Users/james.remeika/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
==> Verifying SHA-256 checksum for Cask 'java'.
==> Installing Cask java
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Tar for /Users/james.remeika/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
tar xf /Users/james.remeika/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz -C /var/folders/zw/m5y1q0h94m915_0cgnrjvyfnzkhqr6/T/d20181129-49490-nukqtu
cp -pR /var/folders/zw/m5y1q0h94m915_0cgnrjvyfnzkhqr6/T/d20181129-49490-nukqtu/jdk-11.0.1.jdk/. /usr/local/Caskroom/java/11.0.1,13/jdk-11.0.1.jdk
chmod -Rf +w /var/folders/zw/m5y1q0h94m915_0cgnrjvyfnzkhqr6/T/d20181129-49490-nukqtu
==> Verifying Gatekeeper status of /Users/james.remeika/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/james.remeika/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
==> /Users/james.remeika/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz is quarantined
==> Propagating quarantine from /Users/james.remeika/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz to /usr/local/Caskroom/java/11.0.1,13
/usr/bin/xattr -p com.apple.quarantine /Users/james.remeika/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5c0058b1\;Homebrew\\x20Cask\;F52983AD-9C33-4C82-AD94-E9EDA9B4936B
==> Creating metadata directory /usr/local/Caskroom/java/.metadata/11.0.1,13/20181129212924.406.
==> Creating metadata subdirectory /usr/local/Caskroom/java/.metadata/11.0.1,13/20181129212924.406/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x0000000102d4a9d8>
==> Installing artifact of class Cask::Artifact::PostflightBlock
/usr/bin/sudo -E -- /bin/mv -f -- /usr/local/Caskroom/java/11.0.1,13/jdk-11.0.1.jdk /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk
mv: rename /usr/local/Caskroom/java/11.0.1,13/jdk-11.0.1.jdk to /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk: No such file or directory
==> Purging files for version 11.0.1,13 of Cask java
Error: Failure while executing; `/usr/bin/sudo -E -- /bin/mv -f -- /usr/local/Caskroom/java/11.0.1,13/jdk-11.0.1.jdk /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk` exited with 1. Here's the output:
mv: rename /usr/local/Caskroom/java/11.0.1,13/jdk-11.0.1.jdk to /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk: No such file or directory


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/dsl/base.rb:14:in `system_command'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/java.rb:10:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:39:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:39:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:22:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew Version
1.8.4-9-g30c90dc
==> macOS
10.14.1
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4071 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.60.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
homebrew/cask
homebrew/core
homebrew/versions
```

**Comment by unibravo** [comment]
Thanks for feedback. We have same problem.

**Comment by ran-dall** [comment]
@remeika @unibravo @Flinner It works for me just fine; but I'm on  High Sierra. 🤨

I read the writing on the wall the Mojava was going to be a problem (I do a fair amount of contract work for Intel and NVIDIA). 🤓

So I'm thinking this may be just a Mojave issue. 😢

**Output of command with `--force --verbose --debug`**
brew cask reinstall java --force --verbose --debug                                                                                 
==> Cask::Installer#reinstall
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_osx-x64_bin.tar.gz
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.4-17-g720df73\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_osx-x64_bin.tar.gz
Already downloaded: /Users/randall/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/randall/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/randall/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
==> /Users/randall/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz is quarantined
==> Downloaded to -> /Users/randall/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
==> Verifying SHA-256 checksum for Cask 'java'.
==> Uninstalling Cask java
==> Un-installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x00007fd27012b840>
==> Un-installing artifact of class Cask::Artifact::Uninstall
==> Running uninstall process for java; your password may be necessary
==> Removing files:
/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
==> Un-installing artifact of class Cask::Artifact::PostflightBlock
==> Purging files for version 11.0.1,13 of Cask java
==> Purging all staged versions of Cask java
==> Installing Cask java
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Tar for /Users/randall/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
tar xf /Users/randall/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz -C /var/folders/sv/cmvmg3h10bb03_7qqfr2m85w0000gn/T/d20181201-70764-r19mot
cp -pR /var/folders/sv/cmvmg3h10bb03_7qqfr2m85w0000gn/T/d20181201-70764-r19mot/jdk-11.0.1.jdk/. /usr/local/Caskroom/java/11.0.1,13/jdk-11.0.1.jdk
chmod -Rf +w /var/folders/sv/cmvmg3h10bb03_7qqfr2m85w0000gn/T/d20181201-70764-r19mot
==> Verifying Gatekeeper status of /Users/randall/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/randall/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
==> /Users/randall/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz is quarantined
==> Propagating quarantine from /Users/randall/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz to /usr/local/Caskroom/java/11.0.1,13
/usr/bin/xattr -p com.apple.quarantine /Users/randall/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5c02cdc2\;Homebrew\\x20Cask\;04B73A2C-EF7E-4041-A45F-C1BD12BA9F04
==> Creating metadata directory /usr/local/Caskroom/java/.metadata/11.0.1,13/20181201180918.417.
==> Creating metadata subdirectory /usr/local/Caskroom/java/.metadata/11.0.1,13/20181201180918.417/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x00007fd26fe7e0c0>
==> Installing artifact of class Cask::Artifact::PostflightBlock
/usr/bin/sudo -E -- /bin/mv -f -- /usr/local/Caskroom/java/11.0.1,13/jdk-11.0.1.jdk /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk
/usr/bin/sudo -E -- /bin/mkdir -p -- /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home/bundle/Libraries
/usr/bin/sudo -E -- /bin/ln -nsf -- /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home/lib/server/libjvm.dylib /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home/bundle/Libraries/libserver.dylib
🍺  java was successfully installed!

**Output of `brew cask doctor`**
==> Homebrew Version
1.8.4-17-g720df73
==> macOS
10.13.6
==> SIP
Enabled 
==> Java
11.0.1, 9, 1.8.0_192
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4071 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (209 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-eid (11 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1185 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (157 casks)
/usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk (4 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.60.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/(brew --prefix)/bin/fish"

**Output of `brew cask tap`**
adoptopenjdk/openjdk
brianmorton/cask-automation
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
mas-cli/tap

**Comment by ran-dall** [comment]
You guys could try the `adoptopenjdk` tap. I use `adoptopenjdk` versions and have Java disabled. <br>
![screen shot 2018-12-01 at 11 48 32 am](https://user-images.githubusercontent.com/17261190/49332267-0d619f80-f55f-11e8-8760-ce110c92b444.png)
<hr>

**So my ouput is of Java Versions is...**
```fish
    11.0.1, x86_64:	"AdoptOpenJDK 11.0.1"	/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.1.jdk/Contents/Home
    10.0.2, x86_64:	"AdoptOpenJDK 10"	/Library/Java/JavaVirtualMachines/adoptopenjdk-10.jdk/Contents/Home
    9, x86_64:	"AdoptOpenJDK 9"	/Library/Java/JavaVirtualMachines/adoptopenjdk-9.jdk/Contents/Home
    1.8.0_192, x86_64:	"AdoptOpenJDK 8"	/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.1.jdk/Contents/Home
```
<hr>
I know it's not relavent but in case anyone wondering how I make this work...<br>
<br>

**.bash_profile**
```bash
# Java
alias java8='export JAVA_HOME=$JAVA_8_HOME'
alias java9='export JAVA_HOME=$JAVA_9_HOME'
alias java10='export JAVA_HOME=$JAVA_10_HOME'
alias java11='export JAVA_HOME=$JAVA_11_HOME'
# default to Java 11
java11
```

**.bashrc**
```bash
# Java
export JAVA_8_HOME=$(/usr/libexec/java_home -v1.8)
export JAVA_9_HOME=$(/usr/libexec/java_home -v9)
export JAVA_10_HOME=$(/usr/libexec/java_home -v10)
export JAVA_11_HOME=$(/usr/libexec/java_home -v11)
```

**Comment by reitermarkus** [comment]
> mv: rename /usr/local/Caskroom/java/11.0.1,13/jdk-11.0.1.jdk to /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk: No such file or directory

That means `/Library/Java/JavaVirtualMachines` doesn't exist on your machine, so you'll have to create it. Note that this should exist on a clean install.
