### ISSUE TITLE
Download filezilla client failed with http2 (Error in the HTTP2 framing layer)

### ISSUE THREAD

**Issue by up9cloud** [Homebrew/homebrew-cask#55692]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Download filezilla client with http2 failed.

It's same thing as:
- #51568 (wget work because it's http1.1)
- #52149
- #53634 (I guess his newer curl has no HTTP2 feature)

I did some test, and it's my testing result

> Can reproduce only by the curl with HTTP2 feature

```console
$ /usr/bin/curl --version
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy
```

On first try, you'll get "Error in the HTTP2 framing layer" (run with `-v` to make sure it's http2 mode)

```console
$ /usr/bin/curl -q -v --show-error -fail --continue-at 0 --output filezilla.temp https://download.filezilla-project.org/client/FileZilla_3.38.1_macosx-x86.app.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 136.243.154.86...
* TCP_NODELAY set
*   Trying 2a01:4f8:171:1ce9::2...
* TCP_NODELAY set
* Immediate connect fail for 2a01:4f8:171:1ce9::2: No route to host
* Connected to download.filezilla-project.org (136.243.154.86) port 443 (#0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2844 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [589 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=download.filezilla-project.org
*  start date: Nov 17 11:06:53 2018 GMT
*  expire date: Feb 15 11:06:53 2019 GMT
*  subjectAltName: host "download.filezilla-project.org" matched cert's "download.filezilla-project.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fe24700a400)
> GET /client/FileZilla_3.38.1_macosx-x86.app.tar.bz2 HTTP/2
> Host: download.filezilla-project.org
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0< HTTP/2 200 
< date: Mon, 03 Dec 2018 18:14:23 GMT
< server: Apache
< strict-transport-security: max-age=315360000; includeSubDomains; preload
< last-modified: Sat, 27 Oct 2018 18:10:12 GMT
< etag: "a009f9-57939bf44ebd1"
< accept-ranges: bytes
< content-length: 10488313
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< x-frame-options: deny
< content-type: application/x-bzip2
< 
{ [1074 bytes data]
100 10.0M  100 10.0M    0     0   662k      0  0:00:15  0:00:15 --:--:-- 1532k
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
curl: (16) Error in the HTTP2 framing layer
```

Second try, you'll get 416.

```console
$ /usr/bin/curl -q --show-error -fail --continue-at - --output filezilla.temp https://download.filezilla-project.org/client/FileZilla_3.38.1_macosx-x86.app.tar.bz2
** Resuming transfer from byte position 10488703
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 416
```

Actually, no matter what protocol(http2 or http1.1) you using on the second try, always get 416.

So i guess their server might not support continue transfer...

```console
$ curl --version
curl 7.62.0 (x86_64-apple-darwin17.7.0) libcurl/7.62.0 SecureTransport zlib/1.2.11
Release-Date: 2018-10-31
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets

$ curl -q -v --show-error -fail --continue-at - --output filezilla.temp https://download.filezilla-project.org/client/FileZilla_3.38.1_macosx-x86.app.tar.bz2
** Resuming transfer from byte position 10488703
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 136.243.154.86...
* TCP_NODELAY set
*   Trying 2a01:4f8:171:1ce9::2...
* TCP_NODELAY set
* Immediate connect fail for 2a01:4f8:171:1ce9::2: No route to host
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to download.filezilla-project.org (136.243.154.86) port 443 (#0)
* ALPN, offering http/1.1
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: download.filezilla-project.org
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET /client/FileZilla_3.38.1_macosx-x86.app.tar.bz2 HTTP/1.1
> Host: download.filezilla-project.org
> Range: bytes=10488703-
> User-Agent: curl/7.62.0
> Accept: */*
> 
< HTTP/1.1 416 Requested Range Not Satisfiable
< Date: Mon, 03 Dec 2018 18:26:48 GMT
< Server: Apache
< Strict-Transport-Security: max-age=315360000; includeSubDomains; preload
< Strict-Transport-Security: max-age=315360000; includeSubDomains; preload
< Connection: close
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=iso-8859-1
* The requested URL returned error: 416
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
* Closing connection 0
curl: (22) The requested URL returned error: 416
```

#### Command that failed

```
brew cask upgrade filezilla
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask upgrade filezilla --verbose --debug
==> Upgrading 1 outdated package:
filezilla 3.34.0 -> 3.38.1
==> Started upgrade process for Cask filezilla
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.4\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.5\)\ curl/7.54.0 --location --silent --head https://download.filezilla-project.org/client/FileZilla_3.38.1_macosx-x86.app.tar.bz2
==> Downloading https://download.filezilla-project.org/client/FileZilla_3.38.1_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.4\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.5\)\ curl/7.54.0 --location --silent --head https://download.filezilla-project.org/client/FileZilla_3.38.1_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.4\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.5\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/up9cloud/Library/Caches/Homebrew/downloads/b66767e61713b0398985981c6cb8811aac34785259ab9da07c2cff38dabb8643--FileZilla_3.38.1_macosx-x86.app.tar.bz2.incomplete https://download.filezilla-project.org/client/FileZilla_3.38.1_macosx-x86.app.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.0M  100 10.0M    0     0   757k      0  0:00:13  0:00:13 --:--:-- 1774k
curl: (16) Error in the HTTP2 framing layer
==> Purging files for version 3.38.1 of Cask filezilla
Error: Download failed on Cask 'filezilla' with message: Download failed: https://download.filezilla-project.org/client/FileZilla_3.38.1_macosx-x86.app.tar.bz2
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:304:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:301:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:18:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:144:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:61:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:73:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:41:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

doesn't matter

```
{{replace this}}
```

#### Output of `brew tap`

doesn't matter

```
{{replace this}}
```

**Comment by up9cloud** [comment]
@victorpopkov why not just download the clean version and pass param --http1.1 to curl?

http1.1 works

**Comment by vitorgalvao** [comment]
@up9cloud It’s already removed anyway.

**Comment by up9cloud** [comment]
😢

thanks anyway
