### ISSUE TITLE
Can't brew cask install fork because of new version (checksums differ)

### ISSUE THREAD

**Issue by mxmlnglt** [Homebrew/homebrew-cask#55781]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Again, fork can't be installed because the checksum fails.
Tried and tried again, also did:
```
brew update-reset && brew update
```

```
$ brew cask install fork
==> Satisfying dependencies
==> Downloading https://git-fork.com/update/files/Fork.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'fork'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'fork' does not match.

Expected: 79dd7e72c8524a7b3c03e44e27dea2a1f7175a809c89b118a24cf5b4a150f82a
Actual:   df1f7d18eb8ff242dcc838ba7e0a9a7d14a5bb4c24e2eed66e3227b9132e8438
File:     /Users/mxmlnglt/Library/Caches/Homebrew/downloads/e5463240e5f27fd67002988efc23d693d5c4413f171b1967bca36ff93a574b28--Fork.dmg

To retry an incomplete download, remove the file above.
```

Deleted the file, retried the command, same problem.

Download URL is https://git-fork.com/update/files/Fork.dmg but no version number is available at https://git-fork.com/

Cask stanza URL is: https://git-fork.com/update/feed.xml
There is a Fork 1.0.72.2 version published (exactly today) on Wed, 5 Dec 2018 10:50:00 +0000
But download URL is the same for all versions…

Also:
$ brew cask _stanza version fork
gives 1.0.72.1

Seems like this isn't new, following the previous issues: https://github.com/Homebrew/homebrew-cask/issues?utf8=%E2%9C%93&q=%22Update+fork%22

#### Command that failed

```
brew cask install fork
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install fork --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.4-27-g81021e6\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.1\)\ curl/7.54.0 --location --silent --head https://git-fork.com/update/files/Fork.dmg
==> Downloading https://git-fork.com/update/files/Fork.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.4-27-g81021e6\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.1\)\ curl/7.54.0 --location --silent --head https://git-fork.com/update/files/Fork.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.4-27-g81021e6\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.1\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/mxmlnglt/Library/Caches/Homebrew/downloads/e5463240e5f27fd67002988efc23d693d5c4413f171b1967bca36ff93a574b28--Fork.dmg.incomplete https://git-fork.com/update/files/Fork.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 51.8M  100 51.8M    0     0  2807k      0  0:00:18  0:00:18 --:--:-- 3180k
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/mxmlnglt/Library/Caches/Homebrew/downloads/e5463240e5f27fd67002988efc23d693d5c4413f171b1967bca36ff93a574b28--Fork.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/mxmlnglt/Library/Caches/Homebrew/downloads/e5463240e5f27fd67002988efc23d693d5c4413f171b1967bca36ff93a574b28--Fork.dmg
==> /Users/mxmlnglt/Library/Caches/Homebrew/downloads/e5463240e5f27fd67002988efc23d693d5c4413f171b1967bca36ff93a574b28--Fork.dmg is not quarantined
==> Quarantining /Users/mxmlnglt/Library/Caches/Homebrew/downloads/e5463240e5f27fd67002988efc23d693d5c4413f171b1967bca36ff93a574b28--Fork.dmg
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/mxmlnglt/Library/Caches/Homebrew/downloads/e5463240e5f27fd67002988efc23d693d5c4413f171b1967bca36ff93a574b28--Fork.dmg https://git-fork.com/update/files/Fork.dmg https://git-fork.com/
==> Downloaded to -> /Users/mxmlnglt/Library/Caches/Homebrew/downloads/e5463240e5f27fd67002988efc23d693d5c4413f171b1967bca36ff93a574b28--Fork.dmg
==> Verifying SHA-256 checksum for Cask 'fork'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'fork' does not match.

Expected: 79dd7e72c8524a7b3c03e44e27dea2a1f7175a809c89b118a24cf5b4a150f82a
Actual:   df1f7d18eb8ff242dcc838ba7e0a9a7d14a5bb4c24e2eed66e3227b9132e8438
File:     /Users/mxmlnglt/Library/Caches/Homebrew/downloads/e5463240e5f27fd67002988efc23d693d5c4413f171b1967bca36ff93a574b28--Fork.dmg

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/verify.rb:21:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:157:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:89:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew Version
1.8.4-27-g81021e6
==> macOS
10.14.1
==> SIP
Enabled
==> Java
1.8.0_192
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4069 casks)
/usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk (4 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.60.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
adoptopenjdk/openjdk
homebrew/cask
homebrew/core
homebrew/services
```

**Comment by core-code** [comment]
you can fix this yourself by sending a pull request

the easiest way is to perform
`cask-repair fork
`
and entering the correct version (1.0.72.2)

see 
https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask

**Comment by ran-dall** [comment]
@mxmlnglt https://github.com/Homebrew/homebrew-cask/pull/55811 should have addressed this. **You can close this issue.**
