### ISSUE TITLE
Error - unable to install java8 on MacOs with brew cask

### ISSUE THREAD

**Issue by enima2684** [Homebrew/homebrew-cask#56252]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Error while installing java8

#### Command that failed

```
brew cask install java8
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing java8 means you have AGREED to the license at
  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.oracle.com/otn-pub/java/jdk/8u192-b12/750e1c8617c5452694857ad95c3ee230/jdk-8u192-macosx-x64.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.6\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.2\)\ curl/7.54.0 -b oraclelicense=accept-securebackup-cookie --location --silent --head https://download.oracle.com/otn-pub/java/jdk/8u192-b12/750e1c8617c5452694857ad95c3ee230/jdk-8u192-macosx-x64.dmg
Already downloaded: /Users/XX/Library/Caches/Homebrew/downloads/3461d31884a8cfa7c0f1932da32de0d422e01a3a91b44d6631f2ac50c5146c86--jdk-8u192-macosx-x64.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/XX/Library/Caches/Homebrew/downloads/3461d31884a8cfa7c0f1932da32de0d422e01a3a91b44d6631f2ac50c5146c86--jdk-8u192-macosx-x64.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/XX/Library/Caches/Homebrew/downloads/3461d31884a8cfa7c0f1932da32de0d422e01a3a91b44d6631f2ac50c5146c86--jdk-8u192-macosx-x64.dmg
==> /Users/XX/Library/Caches/Homebrew/downloads/3461d31884a8cfa7c0f1932da32de0d422e01a3a91b44d6631f2ac50c5146c86--jdk-8u192-macosx-x64.dmg is quarantined
==> Downloaded to -> /Users/XX/Library/Caches/Homebrew/downloads/3461d31884a8cfa7c0f1932da32de0d422e01a3a91b44d6631f2ac50c5146c86--jdk-8u192-macosx-x64.dmg
==> Verifying SHA-256 checksum for Cask 'java8'.
==> Installing Cask java8
==> Cask::Installer#stage
hdiutil imageinfo /Users/XX/Library/Caches/Homebrew/downloads/3461d31884a8cfa7c0f1932da32de0d422e01a3a91b44d6631f2ac50c5146c86--jdk-8u192-macosx-x64.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/XX/Library/Caches/Homebrew/downloads/3461d31884a8cfa7c0f1932da32de0d422e01a3a91b44d6631f2ac50c5146c86--jdk-8u192-macosx-x64.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/j3/62khp7ds0k50y_ysc13xzqfm4cr__2/T/d20181217-27988-s4qr03 /Users/XX/Library/Caches/Homebrew/downloads/3461d31884a8cfa7c0f1932da32de0d422e01a3a91b44d6631f2ac50c5146c86--jdk-8u192-macosx-x64.dmg
find . -print0
mkbom -s -i /var/folders/j3/62khp7ds0k50y_ysc13xzqfm4cr__2/T/20181217-27988-jcp7uw.list -- /var/folders/j3/62khp7ds0k50y_ysc13xzqfm4cr__2/T/20181217-27988-xnpyju.bom
ditto --bom /var/folders/j3/62khp7ds0k50y_ysc13xzqfm4cr__2/T/20181217-27988-xnpyju.bom -- /private/var/folders/j3/62khp7ds0k50y_ysc13xzqfm4cr__2/T/d20181217-27988-s4qr03/dmg.CTixwF /var/folders/j3/62khp7ds0k50y_ysc13xzqfm4cr__2/T/d20181217-27988-10zpobt
diskutil eject /private/var/folders/j3/62khp7ds0k50y_ysc13xzqfm4cr__2/T/d20181217-27988-s4qr03/dmg.CTixwF
chmod +rw /var/folders/j3/62khp7ds0k50y_ysc13xzqfm4cr__2/T/d20181217-27988-10zpobt/JDK 8 Update 192.pkg
cp -p /var/folders/j3/62khp7ds0k50y_ysc13xzqfm4cr__2/T/d20181217-27988-10zpobt/JDK 8 Update 192.pkg /usr/local/Caskroom/java8/1.8.0_192-b12,750e1c8617c5452694857ad95c3ee230/JDK 8 Update 192.pkg
==> Verifying Gatekeeper status of /Users/XX/Library/Caches/Homebrew/downloads/3461d31884a8cfa7c0f1932da32de0d422e01a3a91b44d6631f2ac50c5146c86--jdk-8u192-macosx-x64.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/XX/Library/Caches/Homebrew/downloads/3461d31884a8cfa7c0f1932da32de0d422e01a3a91b44d6631f2ac50c5146c86--jdk-8u192-macosx-x64.dmg
==> /Users/XX/Library/Caches/Homebrew/downloads/3461d31884a8cfa7c0f1932da32de0d422e01a3a91b44d6631f2ac50c5146c86--jdk-8u192-macosx-x64.dmg is quarantined
==> Propagating quarantine from /Users/XX/Library/Caches/Homebrew/downloads/3461d31884a8cfa7c0f1932da32de0d422e01a3a91b44d6631f2ac50c5146c86--jdk-8u192-macosx-x64.dmg to /usr/local/Caskroom/java8/1.8.0_192-b12,750e1c8617c5452694857ad95c3ee230
/usr/bin/xattr -p com.apple.quarantine /Users/XX/Library/Caches/Homebrew/downloads/3461d31884a8cfa7c0f1932da32de0d422e01a3a91b44d6631f2ac50c5146c86--jdk-8u192-macosx-x64.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5c178359\;Homebrew\\x20Cask\;2050EA16-76A1-42E4-B171-78F52B631D51
==> Creating metadata directory /usr/local/Caskroom/java8/.metadata/1.8.0_192-b12,750e1c8617c5452694857ad95c3ee230/20181217133356.943.
==> Creating metadata subdirectory /usr/local/Caskroom/java8/.metadata/1.8.0_192-b12,750e1c8617c5452694857ad95c3ee230/20181217133356.943/Casks.
==> Installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x0000000102185260>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for java8; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=XX USER=XX USERNAME=XX /usr/sbin/installer -pkg /usr/local/Caskroom/java8/1.8.0_192-b12,750e1c8617c5452694857ad95c3ee230/JDK\ 8\ Update\ 192.pkg -target / -verboseR
installer: Package name is JDK 8 Update 192
installer: Installing at base path /
installer:PHASE:Préparation à l’installation…
installer:PHASE:Préparation du disque…
installer:PHASE:Préparation de JDK 8 Update 192…
installer:PHASE:Attente de la fin des autres installations…
installer:PHASE:Configuration de l’installation…
installer:STATUS:
installer:%9.485976
installer:PHASE:Écriture des fichiers…
installer:%25.018483
installer:PHASE:Écriture des fichiers…
installer:%36.113131
installer:PHASE:Écriture des fichiers…
installer:%43.879384
installer:PHASE:Écriture des fichiers…
installer:%49.426708
installer:PHASE:Écriture des fichiers…
installer:%66.068679
installer:PHASE:Écriture des fichiers…
installer:%80.760509
installer:PHASE:Mise en place des éléments…
installer:%81.313973
installer:PHASE:Mise en place des éléments…
installer:%91.803975
installer:PHASE:Exécution des scripts du paquet…
installer:%92.363402
installer:PHASE:Exécution des scripts du paquet…
installer:PHASE:Validation des paquets…
installer:%97.750000
installer: The install failed (Le programme d’installation a rencontré une erreur qui a provoqué l’échec de l’installation. Contactez l’éditeur du logiciel pour obtenir de l’aide.)
==> Purging files for version 1.8.0_192-b12,750e1c8617c5452694857ad95c3ee230 of Cask java8
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=XX USER=XX USERNAME=XX /usr/sbin/installer -pkg /usr/local/Caskroom/java8/1.8.0_192-b12,750e1c8617c5452694857ad95c3ee230/JDK\ 8\ Update\ 192.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is JDK 8 Update 192
installer: Installing at base path /
installer:PHASE:Préparation à l’installation…
installer:PHASE:Préparation du disque…
installer:PHASE:Préparation de JDK 8 Update 192…
installer:PHASE:Attente de la fin des autres installations…
installer:PHASE:Configuration de l’installation…
installer:STATUS:
installer:%9.485976
installer:PHASE:Écriture des fichiers…
installer:%25.018483
installer:PHASE:Écriture des fichiers…
installer:%36.113131
installer:PHASE:Écriture des fichiers…
installer:%43.879384
installer:PHASE:Écriture des fichiers…
installer:%49.426708
installer:PHASE:Écriture des fichiers…
installer:%66.068679
installer:PHASE:Écriture des fichiers…
installer:%80.760509
installer:PHASE:Mise en place des éléments…
installer:%81.313973
installer:PHASE:Mise en place des éléments…
installer:%91.803975
installer:PHASE:Exécution des scripts du paquet…
installer:%92.363402
installer:PHASE:Exécution des scripts du paquet…
installer:PHASE:Validation des paquets…
installer:%97.750000
installer: The install failed (Le programme d’installation a rencontré une erreur qui a provoqué l’échec de l’installation. Contactez l’éditeur du logiciel pour obtenir de l’aide.)

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.8.6
==> macOS
10.14.2
==> SIP
Enabled
==> Java
11.0.1, 1.8.0_192, 1.8.0_181, 1.8.0_171, 1.8.0_161, 1.8.0_151
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4085 casks)
/usr/local/Homebrew/Library/Taps/phinze/homebrew-cask (4085 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (210 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.61.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
dart-lang/dart
heroku/brew
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
phinze/cask
sass/sass
```

**Comment by vitorgalvao** [comment]
Looks like nobody else is having this problem, so I’ll close the issue.

[Download is no longer working anyway](https://github.com/Homebrew/homebrew-cask/issues/57483).

**Comment by gopinaath** [comment]
I'm having similar issue

**Comment by vitorgalvao** [comment]
> I'm having similar issue

The cask has since changed to a different provider, so it’s not the same thing. Open an issue.

**Comment by rdavies3** [comment]
my colleague is having the issue, but when I cask reinstall it works fine.

**Comment by sasanrose** [comment]
Same problem here. Tried reinstalling as well but it did not work:

```
$ brew cask reinstall java8
==> Caveats
Installing java8 means you have AGREED to the license at
  https://www.oracle.com/technetwork/java/javase/terms/license/javase-license.html

==> Satisfying dependencies
==> Downloading https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-macosx-x64.dmg
Already downloaded: /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f55d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg
==> Verifying SHA-256 checksum for Cask 'java8'.
==> Installing Cask java8
==> Running installer for java8; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.                                                                                                                         installer: Package name is JDK 8 Update 202
installer: Installing at base path /
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 8u202,b08:1961070e4c9b4e26a04e7f5a083f551e of Cask java8
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=rose\\\ sasan USER=rose\\\ sasan USERNAME=rose\\\ sasan /usr/sbin/installer -pkg /usr/local/Caskroom/java8/8u202,b08:1961070e4c9b4e26a04e7f5a08
3f551e/JDK\ 8\ Update\ 202.pkg -target /` exited with 1. Here's the output:
installer: Package name is JDK 8 Update 202
installer: Installing at base path /
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:57:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:63:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:50:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:122:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:11:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by Soya-Onishi** [comment]
I'm having sasanrose's problem too.

**Comment by atljoseph** [comment]
one time tonight it installed java8, then the same command started giving errors. This is not fixed.

**Comment by vitorgalvao** [comment]
`java8` is gone, because Oracle has put it behind a login wall. Nothing we can do about it.
