### ISSUE TITLE
virtualbox Failing to install at Mojave

### ISSUE THREAD

**Issue by esoutyrina** [Homebrew/homebrew-cask#56426]
#### General troubleshooting steps

- [x ] I have retried my command with `--force` and the issue is still present.
- [ x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [ x] I ran `brew update-reset && brew update` and retried my command.
- [ x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x ] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

got clean system with Mojave installed

#### Command that failed

```
 brew cask install virtualbox --force --verbose --debug
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Caveats
To install and/or use virtualbox you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.virtualbox.org/virtualbox/5.2.22/VirtualBox-5.2.22-126460-OSX.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.6-14-ga2b4d4a\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.2\)\ curl/7.54.0 --location --silent --head https://download.virtualbox.org/virtualbox/5.2.22/VirtualBox-5.2.22-126460-OSX.dmg
Already downloaded: /Users/elenasoutyrina/Library/Caches/Homebrew/downloads/b96aa9054101d5e4edab07f1e40a970e3d0d182608ad14f14eb57422498d9427--VirtualBox-5.2.22-126460-OSX.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/elenasoutyrina/Library/Caches/Homebrew/downloads/b96aa9054101d5e4edab07f1e40a970e3d0d182608ad14f14eb57422498d9427--VirtualBox-5.2.22-126460-OSX.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/elenasoutyrina/Library/Caches/Homebrew/downloads/b96aa9054101d5e4edab07f1e40a970e3d0d182608ad14f14eb57422498d9427--VirtualBox-5.2.22-126460-OSX.dmg
==> /Users/elenasoutyrina/Library/Caches/Homebrew/downloads/b96aa9054101d5e4edab07f1e40a970e3d0d182608ad14f14eb57422498d9427--VirtualBox-5.2.22-126460-OSX.dmg is quarantined
==> Downloaded to -> /Users/elenasoutyrina/Library/Caches/Homebrew/downloads/b96aa9054101d5e4edab07f1e40a970e3d0d182608ad14f14eb57422498d9427--VirtualBox-5.2.22-126460-OSX.dmg
==> Verifying SHA-256 checksum for Cask 'virtualbox'.
==> Installing Cask virtualbox
==> Cask::Installer#stage
hdiutil imageinfo /Users/elenasoutyrina/Library/Caches/Homebrew/downloads/b96aa9054101d5e4edab07f1e40a970e3d0d182608ad14f14eb57422498d9427--VirtualBox-5.2.22-126460-OSX.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/elenasoutyrina/Library/Caches/Homebrew/downloads/b96aa9054101d5e4edab07f1e40a970e3d0d182608ad14f14eb57422498d9427--VirtualBox-5.2.22-126460-OSX.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/5v/bd36512j3kj_4gp6375fdxgh0000gp/T/d20181219-4521-1cnqul5 /Users/elenasoutyrina/Library/Caches/Homebrew/downloads/b96aa9054101d5e4edab07f1e40a970e3d0d182608ad14f14eb57422498d9427--VirtualBox-5.2.22-126460-OSX.dmg
find . -print0
mkbom -s -i /var/folders/5v/bd36512j3kj_4gp6375fdxgh0000gp/T/20181219-4521-1ajskl2.list -- /var/folders/5v/bd36512j3kj_4gp6375fdxgh0000gp/T/20181219-4521-bfsvzo.bom
ditto --bom /var/folders/5v/bd36512j3kj_4gp6375fdxgh0000gp/T/20181219-4521-bfsvzo.bom -- /private/var/folders/5v/bd36512j3kj_4gp6375fdxgh0000gp/T/d20181219-4521-1cnqul5/dmg.R9VfRX /var/folders/5v/bd36512j3kj_4gp6375fdxgh0000gp/T/d20181219-4521-speo3d
diskutil eject /private/var/folders/5v/bd36512j3kj_4gp6375fdxgh0000gp/T/d20181219-4521-1cnqul5/dmg.R9VfRX
cp -pR /var/folders/5v/bd36512j3kj_4gp6375fdxgh0000gp/T/d20181219-4521-speo3d/VirtualBox.pkg /usr/local/Caskroom/virtualbox/5.2.22,126460/VirtualBox.pkg
cp -pR /var/folders/5v/bd36512j3kj_4gp6375fdxgh0000gp/T/d20181219-4521-speo3d/VirtualBox_Uninstall.tool /usr/local/Caskroom/virtualbox/5.2.22,126460/VirtualBox_Uninstall.tool
cp -pR /var/folders/5v/bd36512j3kj_4gp6375fdxgh0000gp/T/d20181219-4521-speo3d/UserManual.pdf /usr/local/Caskroom/virtualbox/5.2.22,126460/UserManual.pdf
chmod -Rf +w /var/folders/5v/bd36512j3kj_4gp6375fdxgh0000gp/T/d20181219-4521-speo3d
==> Verifying Gatekeeper status of /Users/elenasoutyrina/Library/Caches/Homebrew/downloads/b96aa9054101d5e4edab07f1e40a970e3d0d182608ad14f14eb57422498d9427--VirtualBox-5.2.22-126460-OSX.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/elenasoutyrina/Library/Caches/Homebrew/downloads/b96aa9054101d5e4edab07f1e40a970e3d0d182608ad14f14eb57422498d9427--VirtualBox-5.2.22-126460-OSX.dmg
==> /Users/elenasoutyrina/Library/Caches/Homebrew/downloads/b96aa9054101d5e4edab07f1e40a970e3d0d182608ad14f14eb57422498d9427--VirtualBox-5.2.22-126460-OSX.dmg is quarantined
==> Propagating quarantine from /Users/elenasoutyrina/Library/Caches/Homebrew/downloads/b96aa9054101d5e4edab07f1e40a970e3d0d182608ad14f14eb57422498d9427--VirtualBox-5.2.22-126460-OSX.dmg to /usr/local/Caskroom/virtualbox/5.2.22,126460
/usr/bin/xattr -p com.apple.quarantine /Users/elenasoutyrina/Library/Caches/Homebrew/downloads/b96aa9054101d5e4edab07f1e40a970e3d0d182608ad14f14eb57422498d9427--VirtualBox-5.2.22-126460-OSX.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5c19a962\;Homebrew\\x20Cask\;2B67880D-6A14-4269-9AD3-D7B629760F63
==> Creating metadata directory /usr/local/Caskroom/virtualbox/.metadata/5.2.22,126460/20181219230532.156.
==> Creating metadata subdirectory /usr/local/Caskroom/virtualbox/.metadata/5.2.22,126460/20181219230532.156/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00007fccf9f03ac0>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=elenasoutyrina USER=elenasoutyrina USERNAME=elenasoutyrina /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/5.2.22,126460/VirtualBox.pkg -target / -verboseR
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%14.332662
installer:PHASE:Writing files…
installer:%52.239018
installer:PHASE:Moving items into place…
installer:PHASE:Validating packages…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 5.2.22,126460 of Cask virtualbox
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=elenasoutyrina USER=elenasoutyrina USERNAME=elenasoutyrina /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/5.2.22,126460/VirtualBox.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%14.332662
installer:PHASE:Writing files…
installer:%52.239018
installer:PHASE:Moving items into place…
installer:PHASE:Validating packages…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'```

#### Output of `brew cask doctor`

```
Your system is ready to brew
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

**Comment by esoutyrina** [comment]
permission issue
