### ISSUE TITLE
Cask Java fails to install

### ISSUE THREAD

**Issue by rr40** [Homebrew/homebrew-cask#56639]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Cask Java fails to install

#### Command that failed

```
brew cask install java
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_osx-x64_bin.tar.gz
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.6-38-g8842832\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_osx-x64_bin.tar.gz
Already downloaded: /Users/z/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/z/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/z/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
==> /Users/z/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz is quarantined
==> Downloaded to -> /Users/z/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
==> Verifying SHA-256 checksum for Cask 'java'.
==> Installing Cask java
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Tar for /Users/z/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
tar xf /Users/z/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz -C /var/folders/tn/1jz04wkn1wb7vk4fkhfbpg700000gn/T/d20181226-27124-f8gv64
cp -pR /var/folders/tn/1jz04wkn1wb7vk4fkhfbpg700000gn/T/d20181226-27124-f8gv64/jdk-11.0.1.jdk/. /usr/local/Caskroom/java/11.0.1,13/jdk-11.0.1.jdk
chmod -Rf +w /var/folders/tn/1jz04wkn1wb7vk4fkhfbpg700000gn/T/d20181226-27124-f8gv64
==> Verifying Gatekeeper status of /Users/z/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/z/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
==> /Users/z/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz is quarantined
==> Propagating quarantine from /Users/z/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz to /usr/local/Caskroom/java/11.0.1,13
/usr/bin/xattr -p com.apple.quarantine /Users/z/Library/Caches/Homebrew/downloads/b6a2bdcd379af44a3e5c6bdd8638c0647512ff59816806dd85111094acbb17dc--openjdk-11.0.1_osx-x64_bin.tar.gz
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5c233835\;Homebrew\\x20Cask\;F4DDB3E3-EECE-4FFD-9388-2863EC5D3C60
==> Creating metadata directory /usr/local/Caskroom/java/.metadata/11.0.1,13/20181226082144.850.
==> Creating metadata subdirectory /usr/local/Caskroom/java/.metadata/11.0.1,13/20181226082144.850/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x00007ff1c969cbf8>
==> Installing artifact of class Cask::Artifact::PostflightBlock
/usr/bin/sudo -E -- /bin/mv -f -- /usr/local/Caskroom/java/11.0.1,13/jdk-11.0.1.jdk /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk
mv: rename /usr/local/Caskroom/java/11.0.1,13/jdk-11.0.1.jdk to /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk: No such file or directory
==> Purging files for version 11.0.1,13 of Cask java
Error: Failure while executing; `/usr/bin/sudo -E -- /bin/mv -f -- /usr/local/Caskroom/java/11.0.1,13/jdk-11.0.1.jdk /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk` exited with 1. Here's the output:
mv: rename /usr/local/Caskroom/java/11.0.1,13/jdk-11.0.1.jdk to /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk: No such file or directory


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/dsl/base.rb:14:in `system_command'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/java.rb:10:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:39:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:39:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:22:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.8.6-38-g8842832
==> macOS
10.13.6
==> SIP
Disabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4082 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.61.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
homebrew/services
```

**Comment by vitorgalvao** [comment]
Problem looks to be that `/Library/Java/JavaVirtualMachines/` does not exist on your machine. We had another user with that same problem a while ago. Try creating that directory.

Since you seem to be the only one with this issue, I’ll close it now.
