### ISSUE TITLE
Vitamin-r has multiple appcast

### ISSUE THREAD

**Issue by mrvkino** [Homebrew/homebrew-cask#57238]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When searching for formulae or cask, doing a `brew cask audit` I get the following error:

```bash
> brew search pipenv
Error: Cask 'vitamin-r' definition is invalid: 'appcast' stanza may only appear once.
> brew cask audit
Error: Cask 'vitamin-r' definition is invalid: 'appcast' stanza may only appear once.
```

It seems the formulae for [Vitamin-r](https://github.com/Homebrew/homebrew-cask/blob/0d830e951d85c5d14d414aaa4bfcc633d2735e6e/Casks/vitamin-r.rb) has multiple appcast declaration.

#### Command that failed

```bash
> brew search pipenv
Error: Cask 'vitamin-r' definition is invalid: 'appcast' stanza may only appear once.
> brew cask audit
Error: Cask 'vitamin-r' definition is invalid: 'appcast' stanza may only appear once.
```

#### Output of command with `--force --verbose --debug`

```
>brew cask audit --debug
Error: Cask 'vitamin-r' definition is invalid: 'appcast' stanza may only appear once.
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:97:in `set_unique_stanza'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:177:in `appcast'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/vitamin-r.rb:13:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:42:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:42:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:33:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:33:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:77:in `cask'
/usr/local/Homebrew/Library/Homebrew/compat/cask/cask_loader.rb:17:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:123:in `cask'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/vitamin-r.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:21:in `block in each'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/audit.rb:12:in `to_a'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/audit.rb:12:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:49:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/audit.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:88:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:88:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.9.0
==> macOS
10.14.2
==> SIP
Enabled
==> Java
11.0.1
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4095 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (209 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1180 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (169 casks)
/usr/local/Homebrew/Library/Taps/rcmdnk/homebrew-rcmdnkcask (8 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.31.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.62.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/fish"
```

#### Output of `brew tap`

```
Updating Homebrew...
Fast-forwarded master to origin/master.
Fast-forwarded master to origin/master.
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask and homebrew/cask-drivers).
No changes to formulae.

caryll/tap
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/science
rcmdnk/rcmdnkcask
```

**Comment by kallookoo** [comment]
This 'appcast' is defined twice on this file:
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/vitamin-r.rb
after this commit: #57235

**Comment by kallookoo** [comment]
Already create a PR for its modification

**Comment by vitorgalvao** [comment]
Already fixed.
