### ISSUE TITLE
`check` doesn't find non-brew Google Chrome.app, downloads, then fails.

### ISSUE THREAD

**Issue by invisiblethreat** [Homebrew/homebrew-cask#57376]
#### General troubleshooting steps

- [NA] I have retried my command with `--force` and the issue is still present. `--force` clobbers the install.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When running `brew cask install google-chrome` it appears as if the [checks](https://github.com/Homebrew/homebrew-cask/blob/master/cmd/lib/check.rb#L3-L7) don't pick up the application(or the match for it being installed fails- Ruby is magic to me) and proceeds to download the `dmg`. The reason for filing this bug is that I have strong feeling that if the `--force` flag is not specified, the download should never occur, as the binary is found to already be installed. This is important to people on slow/expensive/metered/throttled links in my opinion. I do realize that this may be a bit of a corner-case, and would imagine that it would be prioritized as such.

#### Command that failed

```
brew cask install google-chrome
==> Satisfying dependencies
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'google-chrome'.
==> Installing Cask google-chrome
==> Purging files for version 71.0.3578.98 of Cask google-chrome
Error: It seems there is already an App at '/Applications/Google Chrome.app'.

```

#### Output of command with `--verbose --debug`

Please note, `--force` willfully clobbers a non-brew install of Google Chrome.

```
brew cask install google-chrome --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.9.1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.2\)\ curl/7.54.0 --location --silent --head https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
Already downloaded: /Users/swalsh/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/swalsh/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/swalsh/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> /Users/swalsh/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg is quarantined
==> Downloaded to -> /Users/swalsh/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> Verifying SHA-256 checksum for Cask 'google-chrome'.
==> Installing Cask google-chrome
==> Cask::Installer#stage
hdiutil imageinfo /Users/swalsh/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/swalsh/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/ld/hnhrnmwd19z1_xc7pbqrg6wr0000gn/T/d20190111-9203-hgsim0 /Users/swalsh/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
find . -print0
mkbom -s -i /var/folders/ld/hnhrnmwd19z1_xc7pbqrg6wr0000gn/T/20190111-9203-hpydcf.list -- /var/folders/ld/hnhrnmwd19z1_xc7pbqrg6wr0000gn/T/20190111-9203-japd5y.bom
ditto --bom /var/folders/ld/hnhrnmwd19z1_xc7pbqrg6wr0000gn/T/20190111-9203-japd5y.bom -- /private/var/folders/ld/hnhrnmwd19z1_xc7pbqrg6wr0000gn/T/d20190111-9203-hgsim0/dmg.Jon3Nu /var/folders/ld/hnhrnmwd19z1_xc7pbqrg6wr0000gn/T/d20190111-9203-3lck9o
diskutil eject /private/var/folders/ld/hnhrnmwd19z1_xc7pbqrg6wr0000gn/T/d20190111-9203-hgsim0/dmg.Jon3Nu
cp -pR /var/folders/ld/hnhrnmwd19z1_xc7pbqrg6wr0000gn/T/d20190111-9203-3lck9o/Google\ Chrome.app/. /usr/local/Caskroom/google-chrome/71.0.3578.98/Google\ Chrome.app
cp -pR /var/folders/ld/hnhrnmwd19z1_xc7pbqrg6wr0000gn/T/d20190111-9203-3lck9o/.keystone_install /usr/local/Caskroom/google-chrome/71.0.3578.98/.keystone_install
cp -pR /var/folders/ld/hnhrnmwd19z1_xc7pbqrg6wr0000gn/T/d20190111-9203-3lck9o/.keychain_reauthorize/. /usr/local/Caskroom/google-chrome/71.0.3578.98/.keychain_reauthorize
chmod -Rf +w /var/folders/ld/hnhrnmwd19z1_xc7pbqrg6wr0000gn/T/d20190111-9203-3lck9o
==> Verifying Gatekeeper status of /Users/swalsh/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/swalsh/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
==> /Users/swalsh/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg is quarantined
==> Propagating quarantine from /Users/swalsh/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg to /usr/local/Caskroom/google-chrome/71.0.3578.98
/usr/bin/xattr -p com.apple.quarantine /Users/swalsh/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5c3911b1\;Homebrew\\x20Cask\;300C0F22-CF62-46E4-AC9C-367AE0910BF1
==> Creating metadata directory /usr/local/Caskroom/google-chrome/.metadata/71.0.3578.98/20190111220703.777.
==> Creating metadata subdirectory /usr/local/Caskroom/google-chrome/.metadata/71.0.3578.98/20190111220703.777/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x0000000106ac2d88>
==> Installing artifact of class Cask::Artifact::App
==> Purging files for version 71.0.3578.98 of Cask google-chrome
Error: It seems there is already an App at '/Applications/Google Chrome.app'.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:32:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:11:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:88:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:88:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.9.1-2-g29017d5
==> macOS
10.14.2
==> SIP
Enabled
==> Java
1.8.0_102
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4098 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.31.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.62.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
go-delve/delve
homebrew/cask
homebrew/core
homebrew/versions
proxmark/proxmark3
ytsutano/toolbox
```

**Comment by vitorgalvao** [comment]
Feature, not bug.

If the app wasn’t installed by us, we won’t replace it, so as to not mess up your installs. Slow connections are irrelevant, here, because the software is already downloaded. So if you remove what you have and try to reinstall, we’ll just use the cached download.

**Comment by invisiblethreat** [comment]
My argument is that there shouldn't be anything download for an operation that can't succeed.

**Comment by vitorgalvao** [comment]
> My argument is that there shouldn't be anything download for an operation that can't succeed.

I get that, but the operation *can* succeed. Also, with your suggestion we’d have to run the check twice.

Simply put, this doesn’t affect enough people to be considered.
