### ISSUE TITLE
brew cask install parallels fails

### ISSUE THREAD

**Issue by core-code** [Homebrew/homebrew-cask#57388]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

brew cask install parallels fails

#### Command that failed

```
brew cask install parallels fails
```

#### Output of command with `--force --verbose --debug`

```
susi:~ work$ brew cask install --force --verbose --debug parallels
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.parallels.com/desktop/v14/14.1.0-45387/ParallelsDesktop-14.1.0-45387.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.9.1-10-g4f17e23\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://download.parallels.com/desktop/v14/14.1.0-45387/ParallelsDesktop-14.1.0-45387.dmg
Already downloaded: /Users/work/Library/Caches/Homebrew/downloads/aedff9ff202bfdf350a64ad7f5e17873c093d03e5d0e6ae7ae3cd2c221938bc4--ParallelsDesktop-14.1.0-45387.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/work/Library/Caches/Homebrew/downloads/aedff9ff202bfdf350a64ad7f5e17873c093d03e5d0e6ae7ae3cd2c221938bc4--ParallelsDesktop-14.1.0-45387.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/work/Library/Caches/Homebrew/downloads/aedff9ff202bfdf350a64ad7f5e17873c093d03e5d0e6ae7ae3cd2c221938bc4--ParallelsDesktop-14.1.0-45387.dmg
==> /Users/work/Library/Caches/Homebrew/downloads/aedff9ff202bfdf350a64ad7f5e17873c093d03e5d0e6ae7ae3cd2c221938bc4--ParallelsDesktop-14.1.0-45387.dmg is quarantined
==> Downloaded to -> /Users/work/Library/Caches/Homebrew/downloads/aedff9ff202bfdf350a64ad7f5e17873c093d03e5d0e6ae7ae3cd2c221938bc4--ParallelsDesktop-14.1.0-45387.dmg
==> Verifying SHA-256 checksum for Cask 'parallels'.
==> Installing Cask parallels
==> Cask::Installer#stage
hdiutil imageinfo /Users/work/Library/Caches/Homebrew/downloads/aedff9ff202bfdf350a64ad7f5e17873c093d03e5d0e6ae7ae3cd2c221938bc4--ParallelsDesktop-14.1.0-45387.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/work/Library/Caches/Homebrew/downloads/aedff9ff202bfdf350a64ad7f5e17873c093d03e5d0e6ae7ae3cd2c221938bc4--ParallelsDesktop-14.1.0-45387.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/cy/yf6lmsx936gfp47_49pbn1lc0000gp/T/d20190112-62767-1wguldv /Users/work/Library/Caches/Homebrew/downloads/aedff9ff202bfdf350a64ad7f5e17873c093d03e5d0e6ae7ae3cd2c221938bc4--ParallelsDesktop-14.1.0-45387.dmg
find . -print0
mkbom -s -i /var/folders/cy/yf6lmsx936gfp47_49pbn1lc0000gp/T/20190112-62767-1mhq4v1.list -- /var/folders/cy/yf6lmsx936gfp47_49pbn1lc0000gp/T/20190112-62767-1hvqhmg.bom
ditto --bom /var/folders/cy/yf6lmsx936gfp47_49pbn1lc0000gp/T/20190112-62767-1hvqhmg.bom -- /private/var/folders/cy/yf6lmsx936gfp47_49pbn1lc0000gp/T/d20190112-62767-1wguldv/dmg.osMywm /var/folders/cy/yf6lmsx936gfp47_49pbn1lc0000gp/T/d20190112-62767-1ixqsv0
ditto: /private/var/folders/cy/yf6lmsx936gfp47_49pbn1lc0000gp/T/d20190112-62767-1ixqsv0/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted
diskutil eject /private/var/folders/cy/yf6lmsx936gfp47_49pbn1lc0000gp/T/d20190112-62767-1wguldv/dmg.osMywm
==> Purging files for version 14.1.0-45387 of Cask parallels
Error: Failure while executing; `ditto --bom /var/folders/cy/yf6lmsx936gfp47_49pbn1lc0000gp/T/20190112-62767-1hvqhmg.bom -- /private/var/folders/cy/yf6lmsx936gfp47_49pbn1lc0000gp/T/d20190112-62767-1wguldv/dmg.osMywm /var/folders/cy/yf6lmsx936gfp47_49pbn1lc0000gp/T/d20190112-62767-1ixqsv0` exited with 1. Here's the output:
ditto: /private/var/folders/cy/yf6lmsx936gfp47_49pbn1lc0000gp/T/d20190112-62767-1ixqsv0/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:17:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:92:in `block in extract_to_dir'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tempfile.rb:295:in `open'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:80:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:120:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:121:in `block (2 levels) in extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:120:in `each'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:120:in `block in extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:184:in `block in mount'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:127:in `mount'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:117:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:120:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:127:in `block in extract_nestedly'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:124:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:184:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:72:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:94:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:88:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:88:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew Version
1.9.1-10-g4f17e23
==> macOS
10.13.6
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4096 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (209 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-eid (11 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1180 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (169 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.31.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.62.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
brew tap
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 4f17e2384 to bf4ac4bca.
No changes to formulae.

homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
vitorgalvao/tiny-scripts
```

**Comment by vitorgalvao** [comment]
What about the previous version? Does it work?

**Comment by core-code** [comment]
sorry only tried that but can investigate

**Comment by ran-dall** [comment]
@vitorgalvao The previous version [`14.0.1-45154`](https://github.com/core-code/homebrew-cask/blob/c0f6bad1e377de636dfae93dc9a79ddc775cb9db/Casks/parallels.rb) is working fine. The [other cask](https://github.com/Homebrew/homebrew-cask/pull/55270) fails the same way too.

```bash
brew cask install ~/Downloads/parallels.rb
==> Satisfying dependencies                                                                                                                                                            
==> Downloading https://download.parallels.com/desktop/v14/14.0.1-45154/ParallelsDesktop-14.0.1-45154.dmg                                                                              
######################################################################## 100.0%                                                                                                        
==> Verifying SHA-256 checksum for Cask 'parallels'.                                                                                                                                   
==> Installing Cask parallels                                                                                                                                                          
==> Moving App 'Parallels Desktop.app' to '/Applications/Parallels Desktop.app'.                                                                                                       
Password:                                                                                                                                                                              
Jan 12 16:00:46  pdfm-bootstrap[7474] <Info>: inittool[7461]: Current umask: 0022                                                                                                      
Jan 12 16:00:46  pdfm-bootstrap[7485] <Error>: inittool[7461]: '/Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service' - incorrect permissions (0755)                   
Jan 12 16:00:46  pdfm-bootstrap[7486] <Error>: inittool[7461]: Last bundle location file was not found                                                                                 
Jan 12 16:00:46  pdfm-bootstrap[7487] <Info>: inittool[7461]: Bundle '/Applications/Parallels Desktop.app' (14.0.1-45154) is not initialized: let's cook it                            
Jan 12 16:00:46  pdfm-bootstrap[7488] <Info>: inittool[7461]: Set bundle owners to 'root:wheel'                                                                                        
Jan 12 16:00:46  pdfm-bootstrap[7499] <Info>: inittool[7461]: Bootstrap actions                                                                                                        
Jan 12 16:00:46  pdfm-bootstrap[7503] <Info>: inittool[7461]: Starting bootstrap action 'install_safari_extensions' in background                                                      
Jan 12 16:00:46  pdfm-bootstrap[7505] <Info>: inittool[7461]: Starting bootstrap action 'reg_bundles' in background                                                                    
Jan 12 16:00:46  pdfm-bootstrap[7506] <Info>: inittool[7461]: Installing Safari extensions...                                                                                          
Jan 12 16:00:46  pdfm-bootstrap[7508] <Info>: inittool[7461]: Starting bootstrap action 'prlapps_folder_icon' in background                                                            
Jan 12 16:00:46  pdfm-bootstrap[7516] <Info>: inittool[7461]: Starting bootstrap action 'install_cli_links' in background                                                              
Jan 12 16:00:46  pdfm-bootstrap[7521] <Info>: inittool[7461]: Starting bootstrap action 'install_man_links' in background                                                              
Jan 12 16:00:46  pdfm-bootstrap[7524] <Info>: inittool[7461]: Starting bootstrap action 'install_sh_compl' in background                                                               
Jan 12 16:00:46  pdfm-bootstrap[7530] <Info>: inittool[7461]: Starting bootstrap action 'fix_library_parallels_dir_perms'                                                              
Jan 12 16:00:46  pdfm-bootstrap[7532] <Info>: inittool[7461]: Bash comletion helpers will be installed into '/usr/local/etc/bash_completion.d'                                         
Jan 12 16:00:46  pdfm-bootstrap[7535] <Info>: inittool[7461]: Fixing Library/Parallels permissions...                                                                                  
Jan 12 16:00:46  pdfm-bootstrap[7555] <Info>: inittool[7461]: Installing Safari extensions for draque...                                                                               
Jan 12 16:00:46  pdfm-bootstrap[7578] <Info>: inittool[7461]: Endinging bootstrap action 'fix_library_parallels_dir_perms' with exit code '0'                                          
Jan 12 16:00:46  pdfm-bootstrap[7579] <Info>: inittool[7461]: Starting bootstrap action 'setup_launchd_wrapper'                                                                        
Jan 12 16:00:46  pdfm-bootstrap[7591] <Info>: inittool[7461]: Endinging bootstrap action 'setup_launchd_wrapper' with exit code '0'                                                    
Jan 12 16:00:46  pdfm-bootstrap[7592] <Info>: inittool[7461]: Waiting background job 'install_safari_extensions' with pid 7504...                                                      
Jan 12 16:00:46  pdfm-bootstrap[7599] <Info>: inittool[7461]:   'install_safari_extensions' finished successfuly                                                                       
Jan 12 16:00:46  pdfm-bootstrap[7600] <Info>: inittool[7461]: Waiting background job 'reg_bundles' with pid 7507...                                                                    
Jan 12 16:00:46  pdfm-bootstrap[7601] <Info>: inittool[7461]:   'reg_bundles' finished successfuly                                                                                     
Jan 12 16:00:46  pdfm-bootstrap[7602] <Info>: inittool[7461]: Waiting background job 'prlapps_folder_icon' with pid 7515...                                                            
Jan 12 16:00:46  pdfm-bootstrap[7603] <Info>: inittool[7461]:   'prlapps_folder_icon' finished successfuly                                                                             
Jan 12 16:00:46  pdfm-bootstrap[7604] <Info>: inittool[7461]: Waiting background job 'install_cli_links' with pid 7520...                                                              
Jan 12 16:00:46  pdfm-bootstrap[7605] <Info>: inittool[7461]:   'install_cli_links' finished successfuly                                                                               
Jan 12 16:00:46  pdfm-bootstrap[7606] <Info>: inittool[7461]: Waiting background job 'install_man_links' with pid 7523...                                                              
Jan 12 16:00:46  pdfm-bootstrap[7607] <Info>: inittool[7461]:   'install_man_links' finished successfuly                                                                               
Jan 12 16:00:46  pdfm-bootstrap[7608] <Info>: inittool[7461]: Waiting background job 'install_sh_compl' with pid 7529...                                                               
Jan 12 16:00:46  pdfm-bootstrap[7609] <Info>: inittool[7461]:   'install_sh_compl' finished successfuly                                                                                
🍺  parallels was successfully installed!                                                                                                                                              
                                            
```

**Comment by vitorgalvao** [comment]
Reverting in https://github.com/Homebrew/homebrew-cask/pull/57392.

I don’t think anyone on the core team currently has VMs to test this, so no point in keeping the issue open. On the next Parallels update, let’s hope it has been fixed. If not, we’ll revisit then. If another user submits the update to this version, we’ll expect them to have a fix.
