### ISSUE TITLE
Telegram checksum fails for 4.9-155353

### ISSUE THREAD

**Issue by lawben** [Homebrew/homebrew-cask#57835]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Unable to install telegram using brew due to invalid checksum.
Current one (the one that is failing for me) is 4.9-155353

#### Command that failed

```
brew cask install telegram
```

#### Output of command with `--force --verbose --debug`

```
brew cask install telegram --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
/usr/bin/curl -q --show-error --user-agent Homebrew/1.9.2-87-g193af14\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --location --silent --head https://osx.telegram.org/updates/Telegram-4.9-155353.app.zip
==> Downloading https://osx.telegram.org/updates/Telegram-4.9-155353.app.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.9.2-87-g193af14\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/law/Library/Caches/Homebrew/downloads/eb877103473212769635857380cfb915988db436d1c3331536f0754e30d46271--Telegram-4.9-155353.app.zip.incomplete https://osx.telegram.org/updates/Telegram-4.9-155353.app.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.2M  100 24.2M    0     0  5914k      0  0:00:04  0:00:04 --:--:-- 5916k
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/law/Library/Caches/Homebrew/downloads/eb877103473212769635857380cfb915988db436d1c3331536f0754e30d46271--Telegram-4.9-155353.app.zip
/usr/bin/xattr -p com.apple.quarantine /Users/law/Library/Caches/Homebrew/downloads/eb877103473212769635857380cfb915988db436d1c3331536f0754e30d46271--Telegram-4.9-155353.app.zip
==> /Users/law/Library/Caches/Homebrew/downloads/eb877103473212769635857380cfb915988db436d1c3331536f0754e30d46271--Telegram-4.9-155353.app.zip is not quarantined
==> Quarantining /Users/law/Library/Caches/Homebrew/downloads/eb877103473212769635857380cfb915988db436d1c3331536f0754e30d46271--Telegram-4.9-155353.app.zip
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/law/Library/Caches/Homebrew/downloads/eb877103473212769635857380cfb915988db436d1c3331536f0754e30d46271--Telegram-4.9-155353.app.zip https://osx.telegram.org/updates/Telegram-4.9-155353.app.zip https://macos.telegram.org/
==> Downloaded to -> /Users/law/Library/Caches/Homebrew/downloads/eb877103473212769635857380cfb915988db436d1c3331536f0754e30d46271--Telegram-4.9-155353.app.zip
==> Verifying SHA-256 checksum for Cask 'telegram'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'telegram' does not match.

Expected: f4cc46107eee2d89d2a2c9a0ae544845a7b8276787acf4ecc6fe74b89e16df83
Actual:   7541645daf0e19f44ce50a315c610d874627eaa9540a4d0da8f1c6a002b1c9d1
File:     /Users/law/Library/Caches/Homebrew/downloads/eb877103473212769635857380cfb915988db436d1c3331536f0754e30d46271--Telegram-4.9-155353.app.zip

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/verify.rb:21:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:157:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:89:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by hyuraku** [comment]
Let me try to make PR to fix this issue.

**Comment by vitorgalvao** [comment]
> * [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.

You checked that box, yet that is *exactly* what the problem is. It says right there in the message you posted, and again in the reporting bugs messages you also checked as having read.
