### ISSUE TITLE
Download local by Flywheel error

### ISSUE THREAD

**Issue by Kmutahar** [Homebrew/homebrew-cask#57954]
#### General troubleshooting steps

- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Error: Failure while executing; `unzip -qq /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip -d /var/folders/76/rrz7wncx6l59l46brgfv7sz80000gn/T/d20190126-39830-qopm2q` exited with 9.

#### Command that failed

```
brew cask install local-by-flywheel
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
All Cask dependencies satisfied.
==> Downloading
==> Downloading https://local-by-flywheel-flywheel.netdna-ssl.com/releases/3-0-4/local-by-flywheel-3-0-4-mac.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.9.3-22-g0670282\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --location --silent --head https://local-by-flywheel-flywheel.netdna-ssl.com/releases/3-0-4/local-by-flywheel-3-0-4-mac.zip
Already downloaded: /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip
/usr/bin/xattr -p com.apple.quarantine /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip
==> /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip is quarantined
==> Downloaded to -> /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip
==> Verifying SHA-256 checksum for Cask 'local-by-flywheel'.
==> Installing Cask local-by-flywheel
==> Cask::Installer#stage
zipinfo -1 /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip
unzip /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip -d /var/folders/76/rrz7wncx6l59l46brgfv7sz80000gn/T/d20190126-40558-10yl46m
==> Purging files for version 3.0.4 of Cask local-by-flywheel
Error: Failure while executing; `unzip /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip -d /var/folders/76/rrz7wncx6l59l46brgfv7sz80000gn/T/d20190126-40558-10yl46m` exited with 9. Here's the output:
Archive:  /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip or
        /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip.zip, and cannot find /Users/kmutahar/Library/Caches/Homebrew/downloads/e3e70c1f2e15d08ccbf217b06a646602853abf9b5e11089867a1ab76e73dd038--local-by-flywheel-3-0-4-mac.zip.ZIP, period.


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:17:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/zip.rb:19:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/unpack_strategy/zip.rb:5:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:120:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:127:in `block in extract_nestedly'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:124:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:184:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:72:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:94:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.9.3-22-g0670282
==> macOS
10.14.3
==> SIP
Enabled (custom configuration)

configuration:
apple internal: disabled
kext signing: enabled
filesystem protections: disabled
debugging restrictions: enabled
dtrace restrictions: enabled
nvram protections: enabled
basesystem verification: enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4101 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (210 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-eid (11 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1176 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (172 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.31.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.63.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.6.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
vitorgalvao/tiny-scripts
```

**Comment by vitorgalvao** [comment]
Unfortunately, this cask is (now?) a [walled build](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) so [we will need to remove it](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#unofficial-vendorless-and-walled-builds).

**Comment by Kmutahar** [comment]
At least now we know thank you.

**Comment by vitorgalvao** [comment]
[@claui found the non-walled link](https://github.com/Homebrew/homebrew-cask/pull/57958#issuecomment-457872380), so reopening.

**Comment by vitorgalvao** [comment]
This has already been fixed.
