### ISSUE TITLE
brew search broken after latest update on 'valley' cask

### ISSUE THREAD

**Issue by vovkasm** [Homebrew/homebrew-cask#57995]
#### General troubleshooting steps

- [ ] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

```sh
brew search libreoffice
Error: Cask 'valley' definition is invalid: invalid 'depends_on macos' value: "mountain_lion"
```

brew search <anything> is broken with above error.

#### Command that failed

```
brew search libreoffice
```

#### Output of command with `--force --verbose --debug`

```
Usage: brew search, -S [options] (text|/text/)

 Perform a substring search of cask tokens and formula names for text. If text
 is surrounded with slashes, then it is interpreted as a regular expression.
 The search for text is extended online to homebrew/core and homebrew/cask.

 If no text is passed, display all locally available formulae (including tapped ones).
 No online search is performed.

        --casks                      Display all locally available casks
                                     (including tapped ones). No online search
                                     is performed.
        --desc                       search formulae with a description matching
                                     text and casks with a name matching
                                     text.
        --macports                   Search for text in the given package
                                     manager's list.
        --fink                       Search for text in the given package
                                     manager's list.
        --opensuse                   Search for text in the given package
                                     manager's list.
        --fedora                     Search for text in the given package
                                     manager's list.
        --debian                     Search for text in the given package
                                     manager's list.
        --ubuntu                     Search for text in the given package
                                     manager's list.
    -v, --verbose                    Make some output more verbose.
    -d, --debug                      Display any debugging information.
    -h, --help                       Show this message.
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cli_parser.rb:128:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:75:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.9.3-39-gd0202f6
==> macOS
10.13.6
==> SIP
Enabled
==> Java
1.8.0_151
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4102 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1176 casks)
/usr/local/Homebrew/Library/Taps/colindean/homebrew-fonts-nonfree (1 cask)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.31.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.63.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.6.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
HOMEBREW_CASK_OPTS="--appdir=/Applications"
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
colindean/fonts-nonfree
homebrew/cask
homebrew/cask-fonts
homebrew/core
```

**Comment by vovkasm** [comment]
It seems while I fill this absolutely useless (in this concrete case) bug-template, someone create similar bug report. So I wasted my time :-) This now looks like duplicate of #57994

**Comment by rhencke** [comment]
@vovkasm Still glad to see your report - glad it isn't just me experiencing it!

**Comment by vitorgalvao** [comment]
This has already been fixed.

**Comment by Dids** [comment]
Has this been globally fixed, or per cask?

I'm also seeing a very similar error when running any kind of `brew` action, and I have no idea where this `geneious` cask is even coming from, as Google didn't turn up any useful results.

```
Error: Cask 'geneious' definition is invalid: invalid 'depends_on macos' value: ":mountain_lion"
```

**Comment by vovkasm** [comment]
@Dids this needs per-cask fix. As I understand, currently in main cask repo all casks has been fixed.

**Comment by Dids** [comment]
@vovkasm Thanks for the confirmation! Found the culprit, and I'm guessing it's a removed cask since I couldn't find it on the GitHub repo:
```
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/geneious.rb
```
