### ISSUE TITLE
curl: (22) The requested URL returned error: 416

### ISSUE THREAD

**Issue by parithiban** [Homebrew/homebrew-cask#58191]
#### General troubleshooting steps

- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [X] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I am trying to automate my dev machine setup using ansible in mac os. I need to install virtualbox (5.2.22,126460) using homebrew cask. I used the following step to install it.
```
brew cask install --force https://raw.githubusercontent.com/Homebrew/homebrew-cask/eabf6ef195fcc22b08c4260b7d16b466bfdc2e7d/Casks/virtualbox.rb
```
This command works first time. But however if i run this second time it is throwing me the curl error. Suppose if i delete the cache file `virtualbox.rb` in `~/Library/Caches/Homebrew/Cask` then if i run this command then it is working fine. Also if i download that file into my local and run the `$ brew cask install virtualbox.rb` then it is working fine whenever i run it.

#### Command that failed

```
$ brew cask install --force https://raw.githubusercontent.com/Homebrew/homebrew-cask/eabf6ef195fcc22b08c4260b7d16b466bfdc2e7d/Casks/virtualbox.rb
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/eabf6ef195fcc22b08c4260b7d16b466bfdc2e7d/Casks/virtualbox.rb.
######################################################################## 100.0%
curl: (22) The requested URL returned error: 416
Error: Cask 'virtualbox' is unavailable: Failed to download https://raw.githubusercontent.com/Homebrew/homebrew-cask/eabf6ef195fcc22b08c4260b7d16b466bfdc2e7d/Casks/virtualbox.rb. Did you mean one of these?
virtualbox ✔                                                       virtualbox-beta                                                    virtualbox-extension-pack                                          virtualbox-extension-pack-beta
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install --force --verbose --debug https://raw.githubusercontent.com/Homebrew/homebrew-cask/eabf6ef195fcc22b08c4260b7d16b466bfdc2e7d/Casks/virtualbox.rb
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/eabf6ef195fcc22b08c4260b7d16b466bfdc2e7d/Casks/virtualbox.rb.
/usr/local/opt/curl/bin/curl -q --show-error --user-agent Homebrew/1.9.3-77-g2062c51\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.63.0 --location --range 0-1 --write-out \%\{http_code\} --output /dev/null https://raw.githubusercontent.com/Homebrew/homebrew-cask/eabf6ef195fcc22b08c4260b7d16b466bfdc2e7d/Casks/virtualbox.rb
/usr/local/opt/curl/bin/curl -q --show-error --user-agent Homebrew/1.9.3-77-g2062c51\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.63.0 --fail --location --remote-time --continue-at - --output /Users/parithibang/Library/Caches/Homebrew/Cask/virtualbox.rb https://raw.githubusercontent.com/Homebrew/homebrew-cask/eabf6ef195fcc22b08c4260b7d16b466bfdc2e7d/Casks/virtualbox.rb
** Resuming transfer from byte position 1577
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 416
Error: Cask 'virtualbox' is unavailable: Failed to download https://raw.githubusercontent.com/Homebrew/homebrew-cask/eabf6ef195fcc22b08c4260b7d16b466bfdc2e7d/Casks/virtualbox.rb. Did you mean one of these?
virtualbox                                                          virtualbox-beta                                                     virtualbox-extension-pack ✔                                         virtualbox-extension-pack-beta

/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:53:in `rescue in casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew Version
1.9.3-77-g2062c51
==> macOS
10.13.6
==> SIP
Disabled
==> Java
11.0.2, 9.0.1
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4104 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (210 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.32.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.63.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.6.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
brewsci/bio
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/dupes
homebrew/php
homebrew/services
homebrew/versions
```

**Comment by vitorgalvao** [comment]
1. [`curl` errors](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/curl_error.md).
2. We don’t support installing from a specific commit.
