### ISSUE TITLE
404 Not Found for java8

### ISSUE THREAD

**Issue by flaviogof** [Homebrew/homebrew-cask#58311]
#### General troubleshooting steps

- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [X] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Brew Cask cannot download Java 8. The Url is returning 404.

#### Command that failed

```
brew cask install java8
==> Satisfying dependencies
==> Downloading https://download.java.net/java/early_access/jdk8/b03/BCL/jdk-8u202-ea-bin-b03-macosx-x86_64-07_nov_2018.dmg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'java8' with message: Download failed: https://download.java.net/java/early_access/jdk8/b03/BCL/jdk-8u202-ea-bin-b03-macosx-x86_64-07_nov_2018.dmg
```

#### Output of command with `--force --verbose --debug`

```
brew cask install java8 --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
/usr/bin/curl -q --show-error --user-agent Homebrew/1.9.3\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --location --silent --head https://download.java.net/java/early_access/jdk8/b03/BCL/jdk-8u202-ea-bin-b03-macosx-x86_64-07_nov_2018.dmg
==> Downloading https://download.java.net/java/early_access/jdk8/b03/BCL/jdk-8u202-ea-bin-b03-macosx-x86_64-07_nov_2018.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.9.3\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/avenuecode/Library/Caches/Homebrew/downloads/533b819c9cf432b75dbb34e67b58b4b4a1aea57610334313d215558e3e5f4dfc--jdk-8u202-ea-bin-b03-macosx-x86_64-07_nov_2018.dmg.incomplete https://download.java.net/java/early_access/jdk8/b03/BCL/jdk-8u202-ea-bin-b03-macosx-x86_64-07_nov_2018.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'java8' with message: Download failed: https://download.java.net/java/early_access/jdk8/b03/BCL/jdk-8u202-ea-bin-b03-macosx-x86_64-07_nov_2018.dmg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:304:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:301:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:18:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:144:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:61:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:89:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew Version
1.9.3
==> macOS
10.14.3
==> SIP
Enabled
==> Java
11.0.2
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4104 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (210 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.31.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.63.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.6.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
brew tap
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by ixidion** [comment]
URL is: https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-macosx-x64.dmg

**Comment by flaviogof** [comment]
@reitermarkus please, check the comment above.

**Comment by Enrico204** [comment]
Apparently OpenJDK early access is "closed", so now Oracle JDK is the only one available (see https://jdk.java.net/8/ )

**Comment by vitorgalvao** [comment]
Fixed in https://github.com/Homebrew/homebrew-cask-versions/pull/6934
