### ISSUE TITLE
Soundflower install fails

### ISSUE THREAD

**Issue by crubier** [Homebrew/homebrew-cask#58390]
#### General troubleshooting steps

- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Soundflower install fails

#### Command that failed

```
brew cask install soundflower --force --verbose --debug
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Caveats
To install and/or use soundflower you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://github.com/mattingalls/Soundflower/releases/download/2.0b2/Soundflower-2.0b2.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.X.Y\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.2\)\ curl/7.54.0 --location --silent --head https://github.com/mattingalls/Soundflower/releases/download/2.0b2/Soundflower-2.0b2.dmg
Already downloaded: /Users/vincent/Library/Caches/Homebrew/downloads/a5a5db9c3329c09fec5184ebaadd43fc8129140211235c4e0b91d03b818421b9--Soundflower-2.0b2.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/vincent/Library/Caches/Homebrew/downloads/a5a5db9c3329c09fec5184ebaadd43fc8129140211235c4e0b91d03b818421b9--Soundflower-2.0b2.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/vincent/Library/Caches/Homebrew/downloads/a5a5db9c3329c09fec5184ebaadd43fc8129140211235c4e0b91d03b818421b9--Soundflower-2.0b2.dmg
==> /Users/vincent/Library/Caches/Homebrew/downloads/a5a5db9c3329c09fec5184ebaadd43fc8129140211235c4e0b91d03b818421b9--Soundflower-2.0b2.dmg is quarantined
==> Downloaded to -> /Users/vincent/Library/Caches/Homebrew/downloads/a5a5db9c3329c09fec5184ebaadd43fc8129140211235c4e0b91d03b818421b9--Soundflower-2.0b2.dmg
==> Verifying SHA-256 checksum for Cask 'soundflower'.
==> Installing Cask soundflower
==> Cask::Installer#stage
hdiutil imageinfo /Users/vincent/Library/Caches/Homebrew/downloads/a5a5db9c3329c09fec5184ebaadd43fc8129140211235c4e0b91d03b818421b9--Soundflower-2.0b2.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/vincent/Library/Caches/Homebrew/downloads/a5a5db9c3329c09fec5184ebaadd43fc8129140211235c4e0b91d03b818421b9--Soundflower-2.0b2.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/2g/yhlpschd00n71jykx6bgbp1w0000gn/T/d20190204-38632-1nadza5 /Users/vincent/Library/Caches/Homebrew/downloads/a5a5db9c3329c09fec5184ebaadd43fc8129140211235c4e0b91d03b818421b9--Soundflower-2.0b2.dmg
find . -print0
mkbom -s -i /var/folders/2g/yhlpschd00n71jykx6bgbp1w0000gn/T/20190204-38632-j0kvhe.list -- /var/folders/2g/yhlpschd00n71jykx6bgbp1w0000gn/T/20190204-38632-1m220tk.bom
ditto --bom /var/folders/2g/yhlpschd00n71jykx6bgbp1w0000gn/T/20190204-38632-1m220tk.bom -- /private/var/folders/2g/yhlpschd00n71jykx6bgbp1w0000gn/T/d20190204-38632-1nadza5/dmg.nQb5M1 /var/folders/2g/yhlpschd00n71jykx6bgbp1w0000gn/T/d20190204-38632-nttu3a
diskutil eject /private/var/folders/2g/yhlpschd00n71jykx6bgbp1w0000gn/T/d20190204-38632-1nadza5/dmg.nQb5M1
cp -pR /var/folders/2g/yhlpschd00n71jykx6bgbp1w0000gn/T/d20190204-38632-nttu3a/Soundflower.pkg /usr/local/Caskroom/soundflower/2.0b2/Soundflower.pkg
cp -pR /var/folders/2g/yhlpschd00n71jykx6bgbp1w0000gn/T/d20190204-38632-nttu3a/ReadMe.rtf /usr/local/Caskroom/soundflower/2.0b2/ReadMe.rtf
cp -pR /var/folders/2g/yhlpschd00n71jykx6bgbp1w0000gn/T/d20190204-38632-nttu3a/License.txt /usr/local/Caskroom/soundflower/2.0b2/License.txt
cp -pR /var/folders/2g/yhlpschd00n71jykx6bgbp1w0000gn/T/d20190204-38632-nttu3a/Uninstall\ Soundflower.scpt /usr/local/Caskroom/soundflower/2.0b2/Uninstall\ Soundflower.scpt
chmod -Rf +w /var/folders/2g/yhlpschd00n71jykx6bgbp1w0000gn/T/d20190204-38632-nttu3a
==> Verifying Gatekeeper status of /Users/vincent/Library/Caches/Homebrew/downloads/a5a5db9c3329c09fec5184ebaadd43fc8129140211235c4e0b91d03b818421b9--Soundflower-2.0b2.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/vincent/Library/Caches/Homebrew/downloads/a5a5db9c3329c09fec5184ebaadd43fc8129140211235c4e0b91d03b818421b9--Soundflower-2.0b2.dmg
==> /Users/vincent/Library/Caches/Homebrew/downloads/a5a5db9c3329c09fec5184ebaadd43fc8129140211235c4e0b91d03b818421b9--Soundflower-2.0b2.dmg is quarantined
==> Propagating quarantine from /Users/vincent/Library/Caches/Homebrew/downloads/a5a5db9c3329c09fec5184ebaadd43fc8129140211235c4e0b91d03b818421b9--Soundflower-2.0b2.dmg to /usr/local/Caskroom/soundflower/2.0b2
/usr/bin/xattr -p com.apple.quarantine /Users/vincent/Library/Caches/Homebrew/downloads/a5a5db9c3329c09fec5184ebaadd43fc8129140211235c4e0b91d03b818421b9--Soundflower-2.0b2.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5c587d84\;Homebrew\\x20Cask\;A9084FB2-B593-4EAE-AF33-78916AA6BC10
==> Creating metadata directory /usr/local/Caskroom/soundflower/.metadata/2.0b2/20190204180637.989.
==> Creating metadata subdirectory /usr/local/Caskroom/soundflower/.metadata/2.0b2/20190204180637.989/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00007f82069b4da0>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for soundflower; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=vincent USER=vincent USERNAME=vincent /usr/sbin/installer -pkg /usr/local/Caskroom/soundflower/2.0b2/Soundflower.pkg -target / -verboseR
installer: Package name is Soundflower
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Soundflower…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%2.229250
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 2.0b2 of Cask soundflower
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=vincent USER=vincent USERNAME=vincent /usr/sbin/installer -pkg /usr/local/Caskroom/soundflower/2.0b2/Soundflower.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Soundflower
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Soundflower…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%2.229250
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
>=1.7.1 (shallow or no git repository)
==> macOS
10.14.2
==> SIP
Enabled
==> Java
1.8.0_192
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4107 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (210 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.32.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.63.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.6.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/nokogiri-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/net-http-persistent-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/mime-types-data-3.2018.0812/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/domain_name-0.5.20180417/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.5
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"

```

#### Output of `brew tap`

```
brewsci/bio
homebrew/cask
homebrew/cask-versions
homebrew/core
osgeo/osgeo4mac

```

**Comment by crubier** [comment]
My bad, I didn't see the authorization request...
