### ISSUE TITLE
'brew cask list' reports "Unexpected method 'gpg' called on Cask gpgtools." 

### ISSUE THREAD

**Issue by orome** [Homebrew/homebrew-cask#58495]
#### General troubleshooting steps

- [x] I have retried my command with `--force`: _Results in "Error: invalid option: --force"_
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`brew cask list` reports "Unexpected method 'gpg' called on Cask gpgtools." 

#### Command that failed

```
brew cask list
```

#### Output of command with `--force --verbose --debug`

```
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cask/cmd/options.rb:63:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:41:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

#### Output of command with `--force --verbose --debug`

```
Warning: Unexpected method 'gpg' called on Cask gpgtools.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
araxis-merge                  google-cloud-sdk              julia                         qlprettypatch                 quicklook-csv
atom                          gpgtools                      qlmarkdown                    qlstephen                     quicklook-json
```

#### Output of `brew cask doctor`

```
>=1.7.1 (shallow or no git repository)
==> macOS
10.14.2
==> SIP
Enabled
==> Java
1.8.0_172
```

#### Output of `brew tap`

```
Updating Homebrew...
homebrew/boneyard
homebrew/cask
homebrew/core
homebrew/dupes
homebrew/python
homebrew/versions
wix/brew
```

**Comment by vitorgalvao** [comment]
That cask has been renamed. Please run `brew cask uninstall gpgtools && brew cask install gpg-suite`.

**Comment by orome** [comment]
@vitorgalvao That results in the following and produces the original error when `brew cask list` is subsequently run:

```
Warning: Unexpected method 'gpg' called on Cask gpgtools.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Warning: Unexpected method 'gpg' called on Cask gpgtools.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
==> Uninstalling Cask gpgtools
==> Running uninstall process for gpgtools; your password may be necessary
==> Removing launchctl service org.gpgtools.macgpg2.shutdown-gpg-agent
Password:
==> Removing launchctl service org.gpgtools.Libmacgpg.xpc
==> Removing launchctl service org.gpgtools.gpgmail.enable-bundles
==> Removing launchctl service org.gpgtools.gpgmail.user-uuid-patcher
==> Removing launchctl service org.gpgtools.gpgmail.uuid-patcher
==> Removing launchctl service org.gpgtools.macgpg2.fix
==> Removing launchctl service org.gpgtools.macgpg2.updater
==> Quitting application 'com.apple.mail'...
Application 'com.apple.mail' quit successfully.
==> Uninstalling packages:
org.gpgtools.gpgmail13.pkg
org.gpgtools.gpgkeychain.pkg
org.gpgtools.checkprivatekey.pkg
org.gpgtools.pinentry.pkg
org.gpgtools.gpgmail12.pkg
org.gpgtools.libmacgpg.xpc.pkg
org.gpgtools.gpgpreferences.pkg
org.gpgtools.pkg.version
org.gpgtools.gpgmail14.pkg
org.gpgtools.gpgmailloader.pkg
org.gpgtools.macgpg2.1.pkg
org.gpgtools.pkg.preinstall
org.gpgtools.macgpg2.pkg
org.gpgtools.pkg.gpgmail
org.gpgtools.key
org.gpgtools.updater.pkg
org.gpgtools.gpgservices.pkg
org.gpgtools.libmacgpgB.pkg
==> Removing files:
/Applications/GPG Keychain Access.app
/Applications/GPG Keychain.app
/usr/local/MacGPG2
/Library/Services/GPGServices.service
/Library/Mail/Bundles/GPGMail.mailbundle
/Library/PreferencePanes/GPGPreferences.prefPane
Error: Failure while executing; `/bin/bash -c \[\[\ \"\$\(/usr/bin/readlink\ /usr/local/bin/gpg2\)\"\ \ \ \ \ \ =\~\ MacGPG2\ \]\]\ \&\&\ /bin/rm\ --\ /usr/local/bin/gpg2` exited with 1.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/dsl/base.rb:14:in `system_command'
/usr/local/Caskroom/gpgtools/.metadata/2016.10_v2/20170101203456.540/Casks/gpgtools.rb:28:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:39:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:39:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:26:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:429:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:425:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:380:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'

```

**Comment by vitorgalvao** [comment]
`rm -rf "$(brew --prefix)/Caskroom/gpgtools" && brew cask install gpg-suite`.
