### ISSUE TITLE
the-unarchiver invalid

### ISSUE THREAD

**Issue by SheinH** [Homebrew/homebrew-cask#58683]
#### General troubleshooting steps

- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I have the unarchiver listed as installed. I wish to reinstall it but brew refuses to allow me to do that. Instead I get this error:

```
Error: Cask 'the-unarchiver' definition is invalid: invalid 'depends_on macos' value: ":lion"
```
![image](https://user-images.githubusercontent.com/5853497/52529834-a7646780-2cc7-11e9-853c-c25c4a824649.png)

#### Command that failed

```
brew cask reinstall the-unarchiver --force
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#reinstall
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.devmate.com/com.macpaw.site.theunarchiver/121/1549634528/TheUnarchiver-121.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.1-10-g7ce517c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --location --silent --head https://dl.devmate.com/com.macpaw.site.theunarchiver/121/1549634528/TheUnarchiver-121.zip
Already downloaded: /Users/shein/Library/Caches/Homebrew/downloads/0d45c0ff5054d70b9ccc562e8eb704e420b0fab5e3a84fc5b752524e979c9cdc--TheUnarchiver-121.zip
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/shein/Library/Caches/Homebrew/downloads/0d45c0ff5054d70b9ccc562e8eb704e420b0fab5e3a84fc5b752524e979c9cdc--TheUnarchiver-121.zip
/usr/bin/xattr -p com.apple.quarantine /Users/shein/Library/Caches/Homebrew/downloads/0d45c0ff5054d70b9ccc562e8eb704e420b0fab5e3a84fc5b752524e979c9cdc--TheUnarchiver-121.zip
==> /Users/shein/Library/Caches/Homebrew/downloads/0d45c0ff5054d70b9ccc562e8eb704e420b0fab5e3a84fc5b752524e979c9cdc--TheUnarchiver-121.zip is quarantined
==> Downloaded to -> /Users/shein/Library/Caches/Homebrew/downloads/0d45c0ff5054d70b9ccc562e8eb704e420b0fab5e3a84fc5b752524e979c9cdc--TheUnarchiver-121.zip
==> Verifying SHA-256 checksum for Cask 'the-unarchiver'.
Error: Cask 'the-unarchiver' definition is invalid: invalid 'depends_on macos' value: ":lion"
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:214:in `rescue in depends_on'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:211:in `depends_on'
/usr/local/Caskroom/the-unarchiver/.metadata/4.0.0,120:1528909123/20180830230039.837/Casks/the-unarchiver.rb:12:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:42:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:42:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:33:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:33:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:77:in `cask'
/usr/local/Caskroom/the-unarchiver/.metadata/4.0.0,120:1528909123/20180830230039.837/Casks/the-unarchiver.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:180:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:130:in `uninstall_existing_cask'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:122:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:11:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.0.1-10-g7ce517c
==> macOS
10.14.3
==> SIP
Enabled (custom configuration)

configuration:
apple internal: disabled
kext signing: disabled
filesystem protections: disabled
debugging restrictions: disabled
dtrace restrictions: disabled
nvram protections: disabled
basesystem verification: disabled
==> Java
11.0.2, 1.8.0_202
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4117 casks)
/usr/local/Homebrew/Library/Taps/sheinh/homebrew-marmaduke-chromium (5 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (211 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.32.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.63.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.6.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/nokogiri-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/net-http-persistent-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/mime-types-data-3.2018.0812/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/domain_name-0.5.20180417/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.5
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-versions
homebrew/core
sheinh/marmaduke-chromium
```

**Comment by reitermarkus** [comment]
See https://github.com/Homebrew/homebrew-cask/issues/58046.

**Comment by SheinH** [comment]
Thank you for the fix! @reitermarkus
