### ISSUE TITLE
brew cask install virtualbox

### ISSUE THREAD

**Issue by mekid** [Homebrew/homebrew-cask#59307]
#### General troubleshooting steps

- [x ] I have retried my command with `--force`.
- [ x] I ran `brew update-reset && brew update` and retried my command.
- [ x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [ ] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

{{replace this}}

#### Command that failed

```
brew cask install virtualbox
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Caveats
To install and/or use virtualbox you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.virtualbox.org/virtualbox/6.0.4/VirtualBox-6.0.4-128413-OSX.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.2-59-g0a6d1ef\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --location --silent --head https://download.virtualbox.org/virtualbox/6.0.4/VirtualBox-6.0.4-128413-OSX.dmg
Already downloaded: /Users/kouedrao/Library/Caches/Homebrew/downloads/adeb627f1d5404b725c0a572c11c4350352f849db7d8659b4b51745cb6537966--VirtualBox-6.0.4-128413-OSX.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/kouedrao/Library/Caches/Homebrew/downloads/adeb627f1d5404b725c0a572c11c4350352f849db7d8659b4b51745cb6537966--VirtualBox-6.0.4-128413-OSX.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/kouedrao/Library/Caches/Homebrew/downloads/adeb627f1d5404b725c0a572c11c4350352f849db7d8659b4b51745cb6537966--VirtualBox-6.0.4-128413-OSX.dmg
==> /Users/kouedrao/Library/Caches/Homebrew/downloads/adeb627f1d5404b725c0a572c11c4350352f849db7d8659b4b51745cb6537966--VirtualBox-6.0.4-128413-OSX.dmg is quarantined
==> Downloaded to -> /Users/kouedrao/Library/Caches/Homebrew/downloads/adeb627f1d5404b725c0a572c11c4350352f849db7d8659b4b51745cb6537966--VirtualBox-6.0.4-128413-OSX.dmg
==> Verifying SHA-256 checksum for Cask 'virtualbox'.
==> Installing Cask virtualbox
==> Cask::Installer#stage
hdiutil imageinfo /Users/kouedrao/Library/Caches/Homebrew/downloads/adeb627f1d5404b725c0a572c11c4350352f849db7d8659b4b51745cb6537966--VirtualBox-6.0.4-128413-OSX.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/kouedrao/Library/Caches/Homebrew/downloads/adeb627f1d5404b725c0a572c11c4350352f849db7d8659b4b51745cb6537966--VirtualBox-6.0.4-128413-OSX.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/y2/x7gg32xx3bsfdjh0bbfh6bcm0000gn/T/d20190222-40516-2a3yr0 /Users/kouedrao/Library/Caches/Homebrew/downloads/adeb627f1d5404b725c0a572c11c4350352f849db7d8659b4b51745cb6537966--VirtualBox-6.0.4-128413-OSX.dmg
find . -print0
mkbom -s -i /var/folders/y2/x7gg32xx3bsfdjh0bbfh6bcm0000gn/T/20190222-40516-9xj8oc.list -- /var/folders/y2/x7gg32xx3bsfdjh0bbfh6bcm0000gn/T/20190222-40516-14939sn.bom
ditto --bom /var/folders/y2/x7gg32xx3bsfdjh0bbfh6bcm0000gn/T/20190222-40516-14939sn.bom -- /private/var/folders/y2/x7gg32xx3bsfdjh0bbfh6bcm0000gn/T/d20190222-40516-2a3yr0/dmg.wbAdiy /var/folders/y2/x7gg32xx3bsfdjh0bbfh6bcm0000gn/T/d20190222-40516-1yohh2p
diskutil eject /private/var/folders/y2/x7gg32xx3bsfdjh0bbfh6bcm0000gn/T/d20190222-40516-2a3yr0/dmg.wbAdiy
cp -pR /var/folders/y2/x7gg32xx3bsfdjh0bbfh6bcm0000gn/T/d20190222-40516-1yohh2p/VirtualBox.pkg /usr/local/Caskroom/virtualbox/6.0.4,128413/VirtualBox.pkg
cp -pR /var/folders/y2/x7gg32xx3bsfdjh0bbfh6bcm0000gn/T/d20190222-40516-1yohh2p/VirtualBox_Uninstall.tool /usr/local/Caskroom/virtualbox/6.0.4,128413/VirtualBox_Uninstall.tool
cp -pR /var/folders/y2/x7gg32xx3bsfdjh0bbfh6bcm0000gn/T/d20190222-40516-1yohh2p/UserManual.pdf /usr/local/Caskroom/virtualbox/6.0.4,128413/UserManual.pdf
chmod -Rf +w /var/folders/y2/x7gg32xx3bsfdjh0bbfh6bcm0000gn/T/d20190222-40516-1yohh2p
==> Verifying Gatekeeper status of /Users/kouedrao/Library/Caches/Homebrew/downloads/adeb627f1d5404b725c0a572c11c4350352f849db7d8659b4b51745cb6537966--VirtualBox-6.0.4-128413-OSX.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/kouedrao/Library/Caches/Homebrew/downloads/adeb627f1d5404b725c0a572c11c4350352f849db7d8659b4b51745cb6537966--VirtualBox-6.0.4-128413-OSX.dmg
==> /Users/kouedrao/Library/Caches/Homebrew/downloads/adeb627f1d5404b725c0a572c11c4350352f849db7d8659b4b51745cb6537966--VirtualBox-6.0.4-128413-OSX.dmg is quarantined
==> Propagating quarantine from /Users/kouedrao/Library/Caches/Homebrew/downloads/adeb627f1d5404b725c0a572c11c4350352f849db7d8659b4b51745cb6537966--VirtualBox-6.0.4-128413-OSX.dmg to /usr/local/Caskroom/virtualbox/6.0.4,128413
/usr/bin/xattr -p com.apple.quarantine /Users/kouedrao/Library/Caches/Homebrew/downloads/adeb627f1d5404b725c0a572c11c4350352f849db7d8659b4b51745cb6537966--VirtualBox-6.0.4-128413-OSX.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5c6fbe0f\;Homebrew\\x20Cask\;14973A1E-EE4D-4646-8D27-8585726ED5E7
==> Creating metadata directory /usr/local/Caskroom/virtualbox/.metadata/6.0.4,128413/20190222092923.146.
==> Creating metadata subdirectory /usr/local/Caskroom/virtualbox/.metadata/6.0.4,128413/20190222092923.146/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00007f9640006788>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=kouedrao USER=kouedrao USERNAME=kouedrao /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/6.0.4,128413/VirtualBox.pkg -target / -verboseR
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%5.903723
installer:PHASE:Writing files…
installer:%12.388725
installer:PHASE:Writing files…
installer:%22.116229
installer:PHASE:Writing files…
installer:%41.571236
installer:PHASE:Writing files…
installer:%51.298739
installer:PHASE:Writing files…
installer:%64.291662
installer:PHASE:Running package scripts…
installer:%87.320571
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 6.0.4,128413 of Cask virtualbox
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=kouedrao USER=kouedrao USERNAME=kouedrao /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/6.0.4,128413/VirtualBox.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%5.903723
installer:PHASE:Writing files…
installer:%12.388725
installer:PHASE:Writing files…
installer:%22.116229
installer:PHASE:Writing files…
installer:%41.571236
installer:PHASE:Writing files…
installer:%51.298739
installer:PHASE:Writing files…
installer:%64.291662
installer:PHASE:Running package scripts…
installer:%87.320571
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:57:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:63:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:50:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.0.2-59-g0a6d1ef
==> macOS
10.14.3
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3980 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.32.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.65.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/psych-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/psych-3.1.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.6.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/nokogiri-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/net-http-persistent-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/mime-types-data-3.2018.0812/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/domain_name-0.5.20180417/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.5
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.12.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

**Comment by mekid** [comment]
Permission issue
