### ISSUE TITLE
Cask 'macports' is unreadable: undefined method `method_missing_message' for Utils:Module

### ISSUE THREAD

**Issue by faxotherapy** [Homebrew/homebrew-cask#59840]
#### General troubleshooting steps

- [x] I have retried my command with `--force`.
> My problematic command is `brew search firefox`
> Following this step, I have input: `brew search firefox --force`
> As a result, I got an error message: `Error: invalid option: --force` (at least, I follow your steps…)
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I'd like to perform a search using `brew search`
Examples:
```
brew search vienna
brew search ffmpeg
```

The issue is that no package name is returned after searching for it.

I followed [this guide](https://github.com/Homebrew/homebrew-cask/issues/58046) (similar bug), but it does not work.

#### Command that failed

```
$ brew search vienna
Warning: Cask 'macports' is unreadable: undefined method `method_missing_message' for Utils:Module
Did you mean?  method_missing
Error: Cask 'hopper-disassembler' definition is invalid: invalid 'depends_on macos' value: ":lion"

$ brew search ffmpeg
Warning: Cask 'macports' is unreadable: undefined method `method_missing_message' for Utils:Module
Did you mean?  method_missing
Error: Cask 'hopper-disassembler' definition is invalid: invalid 'depends_on macos' value: ":lion"

$brew search firefox
Warning: Cask 'macports' is unreadable: undefined method `method_missing_message' for Utils:Module
Did you mean?  method_missing
Error: Cask 'hopper-disassembler' definition is invalid: invalid 'depends_on macos' value: ":lion"
```

#### Output of command with `--force --verbose --debug`

```
$ brew search firefox --force --verbose --debug
Usage: brew search [options] [text|/text/]

 Perform a substring search of cask tokens and formula names for text. If text
 is surrounded with slashes, then it is interpreted as a regular expression.
 The search for text is extended online to homebrew/core and homebrew/cask.

 If no text is passed, display all locally available formulae (including tapped ones).
 No online search is performed.

        --casks                      Display all locally available casks
                                     (including tapped ones). No online search
                                     is performed.
        --desc                       search formulae with a description matching
                                     text and casks with a name matching
                                     text.
        --macports                   Search for text in the given package
                                     manager's list.
        --fink                       Search for text in the given package
                                     manager's list.
        --opensuse                   Search for text in the given package
                                     manager's list.
        --fedora                     Search for text in the given package
                                     manager's list.
        --debian                     Search for text in the given package
                                     manager's list.
        --ubuntu                     Search for text in the given package
                                     manager's list.
    -v, --verbose                    Make some output more verbose.
    -d, --debug                      Display any debugging information.
    -h, --help                       Show this message.
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cli_parser.rb:130:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:56:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew Version
2.0.3-16-g01bd14b
==> macOS
10.14.3
==> SIP
Disabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4020 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (193 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-cobertura-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.32.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.65.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/psych-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/psych-3.1.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.28.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.14.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2018.0812/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20180417/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.5
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.22/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.19.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.20.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.12.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
HOMEBREW_CASK_OPTS="--appdir=~/Applications/"
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
$ brew tap
homebrew/cask
homebrew/cask-versions
homebrew/core
yudai/gotty
```

**Comment by vitorgalvao** [comment]
None of those casks is valid anymore. Do

```
rm -rf "$(brew --prefix)/Caskroom/{hopper-disassembler,macports}
```

**Comment by faxotherapy** [comment]
I do apologise for insisting, but I still have the same issue. I have run
```
rm -rf "$(brew --prefix)/Caskroom/{hopper-disassembler,macports}"
```

I still have the following message when I perform a random search; example:
```
$ brew search --desc tmux
==> Formulae
clipper: Share macOS clipboard with tmux and other local and remote apps
overmind: Process manager for Procfile-based applications and tmux
rainbarf: CPU/RAM/battery stats chart bar for tmux (and GNU screen)
reattach-to-user-namespace: Reattach process (e.g., tmux) to background
tmux-mem-cpu-load: CPU, RAM memory, and load monitor for use with tmux
tmux-xpanes: Ultimate terminal divider powered by tmux
tmuxinator-completion: Shell completion for Tmuxinator
wemux: Enhances tmux's to provide multiuser terminal multiplexing

==> Casks
Warning: Cask 'macports' is unreadable: undefined method `method_missing_message' for Utils:Module
Did you mean?  method_missing
Error: Cask 'hopper-disassembler' definition is invalid: invalid 'depends_on macos' value: ":lion"
```

**Comment by reitermarkus** [comment]
Try running `brew update-reset`.

**Comment by faxotherapy** [comment]
Well, I'm afraid it's an insoluble problem. I might need to live with that. I can no longer perform a search of type of, for example, `brew search firefox` No result is returned, but the repetitive error message described above.

**Comment by vitorgalvao** [comment]
Last ditch effort:

```
brew cask uninstall --force hopper-disassembler
brew cask uninstall --force macports
rm -rf "$(brew --prefix)/Caskroom/hopper-disassembler
rm -rf "$(brew --prefix)/Caskroom/macports
```

**Comment by faxotherapy** [comment]
Just tried.
```
$ brew cask uninstall --force hopper-disassembler
Error: Cask 'hopper-disassembler' definition is invalid: invalid 'depends_on macos' value: ":lion"

$ brew cask uninstall --force macports
Warning: Unexpected method 'gpg' called on Cask macports.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
==> Uninstalling Cask macports
==> Uninstalling packages:
==> Purging files for version 2.4.4 of Cask macports

$ rm -rf "$(brew --prefix)/Caskroom/hopper-disassembler"

$ rm -rf "$(brew --prefix)/Caskroom/macports"

$ brew search --desc tmux
==> Formulae
clipper: Share macOS clipboard with tmux and other local and remote apps
overmind: Process manager for Procfile-based applications and tmux
rainbarf: CPU/RAM/battery stats chart bar for tmux (and GNU screen)
reattach-to-user-namespace: Reattach process (e.g., tmux) to background
tmux-mem-cpu-load: CPU, RAM memory, and load monitor for use with tmux
tmux-xpanes: Ultimate terminal divider powered by tmux
tmuxinator-completion: Shell completion for Tmuxinator
wemux: Enhances tmux's to provide multiuser terminal multiplexing

==> Casks
Warning: Cask 'macports' is unreadable: undefined method `method_missing_message' for Utils:Module
Did you mean?  method_missing
Error: Cask 'hopper-disassembler' definition is invalid: invalid 'depends_on macos' value: ":lion"
```
