### ISSUE TITLE
Error installing java8

### ISSUE THREAD

**Issue by sasanrose** [Homebrew/homebrew-cask#60099]
#### General troubleshooting steps

- [ x] I have retried my command with `--force`.
- [ x] I ran `brew update-reset && brew update` and retried my command.
- [ x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [ x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [ x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Error installing java8

#### Command that failed

```
brew cask install java8
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Caveats
Installing java8 means you have AGREED to the license at
  https://www.oracle.com/technetwork/java/javase/terms/license/javase-license.html

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-macosx-x64.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.3-30-g27ec98d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 -b oraclelicense=accept-securebackup-cookie --location --silent --head https://d
ownload.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-macosx-x64.dmg
Already downloaded: /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f55d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f55d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f55d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg
==> /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f55d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg is quarantined
==> Downloaded to -> /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f55d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg
==> Verifying SHA-256 checksum for Cask 'java8'.
==> Installing Cask java8
==> Cask::Installer#stage
hdiutil imageinfo /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f55d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f55d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/ws/h34q10lx21j5lzt6tffy4x8sl60ckw/T/d20190311-3834-1xx3t8d /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f5
5d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg
find . -print0
mkbom -s -i /var/folders/ws/h34q10lx21j5lzt6tffy4x8sl60ckw/T/20190311-3834-i2k5wf.list -- /var/folders/ws/h34q10lx21j5lzt6tffy4x8sl60ckw/T/20190311-3834-54a6ly.bom
ditto --bom /var/folders/ws/h34q10lx21j5lzt6tffy4x8sl60ckw/T/20190311-3834-54a6ly.bom -- /private/var/folders/ws/h34q10lx21j5lzt6tffy4x8sl60ckw/T/d20190311-3834-1xx3t8d/dmg.OObYef /var/folders/ws/h34q10lx21j5
lzt6tffy4x8sl60ckw/T/d20190311-3834-vgej58
diskutil eject /private/var/folders/ws/h34q10lx21j5lzt6tffy4x8sl60ckw/T/d20190311-3834-1xx3t8d/dmg.OObYef
chmod +rw /var/folders/ws/h34q10lx21j5lzt6tffy4x8sl60ckw/T/d20190311-3834-vgej58/JDK 8 Update 202.pkg
cp -p /var/folders/ws/h34q10lx21j5lzt6tffy4x8sl60ckw/T/d20190311-3834-vgej58/JDK 8 Update 202.pkg /usr/local/Caskroom/java8/8u202,b08:1961070e4c9b4e26a04e7f5a083f551e/JDK 8 Update 202.pkg
==> Verifying Gatekeeper status of /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f55d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f55d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg
==> /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f55d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg is quarantined
==> Propagating quarantine from /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f55d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg to /usr/local/Caskroom/java8/8u202,b08:1961070e4c9b4e26a04e7f5a083f551e                                                                                                                                                                 [50/1808]
/usr/bin/xattr -p com.apple.quarantine /Users/rose_sasan/Library/Caches/Homebrew/downloads/1609f66c9a467774f45f55d4258d9a7975ad5f4652f55871e789bc3c47821e06--jdk-8u202-macosx-x64.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5c85b95b\;Homebrew\\x20Cask\;618EAECA-7D7D-4F40-A41C-3C728F41EF17
==> Creating metadata directory /usr/local/Caskroom/java8/.metadata/8u202,b08:1961070e4c9b4e26a04e7f5a083f551e/20190311035341.593.
==> Creating metadata subdirectory /usr/local/Caskroom/java8/.metadata/8u202,b08:1961070e4c9b4e26a04e7f5a083f551e/20190311035341.593/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00007feb52ee5b70>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for java8; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=rose\\\ sasan USER=rose\\\ sasan USERNAME=rose\\\ sasan /usr/sbin/installer -pkg /usr/local/Caskroom/java8/8u202,b08:1961070e4c9b4e26a04e7f5a083f551e/JDK\ 8\ Update\ 202.pkg -t
arget / -verboseR
installer: Package name is JDK 8 Update 202
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing JDK 8 Update 202…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%12.561696
installer:PHASE:Writing files…
installer:%31.234910
installer:PHASE:Writing files…
installer:%41.120730
installer:PHASE:Writing files…
installer:%48.809701
installer:PHASE:Writing files…
installer:%67.482916
installer:PHASE:Writing files…
installer:%81.029884
installer:PHASE:Moving items into place…
installer:%91.699670
installer:PHASE:Running package scripts…
installer:%92.248797
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 8u202,b08:1961070e4c9b4e26a04e7f5a083f551e of Cask java8
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=rose\\\ sasan USER=rose\\\ sasan USERNAME=rose\\\ sasan /usr/sbin/installer -pkg /usr/local/Caskroom/java8/8u202,b08:1961070e4c9b4e26a04e7f5a08
3f551e/JDK\ 8\ Update\ 202.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is JDK 8 Update 202
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing JDK 8 Update 202…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%12.561696
installer:PHASE:Writing files…
installer:%31.234910
installer:PHASE:Writing files…
installer:%41.120730
installer:PHASE:Writing files…
installer:%48.809701
installer:PHASE:Writing files…
installer:%67.482916
installer:PHASE:Writing files…
installer:%81.029884
installer:PHASE:Moving items into place…
installer:%91.699670
installer:PHASE:Running package scripts…
installer:%92.248797
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:57:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:63:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:50:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.0.3-30-g27ec98d
==> macOS
10.14.3
==> SIP
Enabled
==> Java
11.0.2, 1.8.0_202
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3989 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (193 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-cobertura-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.32.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.65.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/psych-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/psych-3.1.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.28.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.14.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2018.0812/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20180417/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.5
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.22/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.19.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.20.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.12.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
caskroom/versions
homebrew/cask
homebrew/core
```

**Comment by mxavierx** [comment]
I'm also having this problem. I tried `brew cask install java`, `cask install caskroom/versions/java8` and some others but with no success. I was forced to install latest java version.
How do I install java 8 using brew?

**Comment by melvyn2** [comment]
I also have this issue.

**Comment by egd-io** [comment]
Java8 was removed from Homebrew on April 18, 2019 due to legal redistribution concerns. PR is [here](https://github.com/Homebrew/homebrew-cask-versions/pull/7261). Discussion explaining why is [here](https://github.com/Homebrew/homebrew-cask-versions/issues/7253). You can install it manually [here](https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html) and hope that your application upgrades to a newer java soon.
