### ISSUE TITLE
Wireshark 3.0.0 upgrade fails

### ISSUE THREAD

**Issue by remm** [Homebrew/homebrew-cask#60103]
#### General troubleshooting steps

- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Upgrade of wireshark fails with error 
Cask 'wireshark' definition is invalid: invalid 'depends_on macos' value: ":mountain_lion

#### Command that failed
```
brew cask upgrade
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 2 outdated packages:
Error: Cask 'wireshark' definition is invalid: invalid 'depends_on macos' value: ":mountain_lion"
```
#### Output of command with `--force --verbose --debug`

```
brew cask upgrade --force --verbose --debug
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 2 outdated packages:
Error: Cask 'wireshark' definition is invalid: invalid 'depends_on macos' value: ":mountain_lion"
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:211:in `rescue in depends_on'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:208:in `depends_on'
/usr/local/Caskroom/wireshark/.metadata/2.6.6/20190109095214.502/Casks/wireshark.rb:11:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:48:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:48:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:39:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:33:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:33:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:73:in `cask'
/usr/local/Caskroom/wireshark/.metadata/2.6.6/20190109095214.502/Casks/wireshark.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:176:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:38:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:34:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:161:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:161:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

#### Output of `brew tap`

```
brew tap
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
jesseduffield/lazygit
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/58046
