### ISSUE TITLE
JDownloader Fails Installation with a Startup Error

### ISSUE THREAD

**Issue by robertleeblairjr** [Homebrew/homebrew-cask#60626]
#### General troubleshooting steps

- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Attempting to install the cask jdownloader fails with the recently released version JDK 12 and gives a "Startup Error". Visiting the jdownloader homepage and installing with their latest provide macOS installer.dmg does not recognize the system java version 12 and instead installs JDK 8 in the application installation directory. Downloading the jdownloader installer.jar file and installing the application is successful and recognizes the system java version 12. This may be an issue with the jdownloader application which those developers would need to resolve. I just thought that I would report it to HomeBrew. I've already submitted a ticket directly to jdownloader's developers, as well.
<img width="931" alt="Screen Shot 2019-03-20 at 5 00 35 AM" src="https://user-images.githubusercontent.com/12276457/54679588-a8ae5e80-4ad5-11e9-83b9-75606a2bce7c.png">

#### Command that failed

```
brew cask install jdownloader
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Caveats
jdownloader requires Java 8. You can install it with

  brew cask install homebrew/cask-versions/java8

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://installer.jdownloader.org/clean/JD2Setup.dmg
/usr/bin/curl -q --show-error --user-agent Mozilla/5.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10_12_3\)\ AppleWebKit/602.4.8\ \(KHTML,\ like\ Gecko\)\ Version/10.0.3\ Safari/602.4.8 --location --silent --head http://installer.jdownloader.org/clean/JD2Setup.dmg
/usr/bin/curl -q --show-error --user-agent Mozilla/5.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10_12_3\)\ AppleWebKit/602.4.8\ \(KHTML,\ like\ Gecko\)\ Version/10.0.3\ Safari/602.4.8 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null http://installer.jdownloader.org/clean/JD2Setup.dmg
/usr/bin/curl -q --show-error --user-agent Mozilla/5.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10_12_3\)\ AppleWebKit/602.4.8\ \(KHTML,\ like\ Gecko\)\ Version/10.0.3\ Safari/602.4.8 --fail --location --remote-time --continue-at 0 --output /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg.incomplete http://installer.jdownloader.org/clean/JD2Setup.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5454k  100 5454k    0     0  1994k      0  0:00:02  0:00:02 --:--:-- 1994k
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg
==> /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg is not quarantined
==> Quarantining /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg http://installer.jdownloader.org/clean/JD2Setup.dmg http://jdownloader.org/
==> Downloaded to -> /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg
==> No SHA-256 checksum defined for Cask 'jdownloader', skipping verification.
==> Installing Cask jdownloader
==> Cask::Installer#stage
hdiutil imageinfo /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/cc/3p7cvn414sg8lsr7ph5dkrtr0000gn/T/d20190320-37438-zprx2m /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg
find . -print0
mkbom -s -i /var/folders/cc/3p7cvn414sg8lsr7ph5dkrtr0000gn/T/20190320-37438-1vbbzw1.list -- /var/folders/cc/3p7cvn414sg8lsr7ph5dkrtr0000gn/T/20190320-37438-10gxd6d.bom
ditto --bom /var/folders/cc/3p7cvn414sg8lsr7ph5dkrtr0000gn/T/20190320-37438-10gxd6d.bom -- /private/var/folders/cc/3p7cvn414sg8lsr7ph5dkrtr0000gn/T/d20190320-37438-zprx2m/dmg.vf2aCH /var/folders/cc/3p7cvn414sg8lsr7ph5dkrtr0000gn/T/d20190320-37438-11igat3
diskutil eject /private/var/folders/cc/3p7cvn414sg8lsr7ph5dkrtr0000gn/T/d20190320-37438-zprx2m/dmg.vf2aCH
cp -pR /var/folders/cc/3p7cvn414sg8lsr7ph5dkrtr0000gn/T/d20190320-37438-11igat3/JDownloader\ Installer.app/. /usr/local/Caskroom/jdownloader/latest/JDownloader\ Installer.app
chmod -Rf +w /var/folders/cc/3p7cvn414sg8lsr7ph5dkrtr0000gn/T/d20190320-37438-11igat3
==> Verifying Gatekeeper status of /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg
==> /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg is quarantined
==> Propagating quarantine from /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg to /usr/local/Caskroom/jdownloader/latest
/usr/bin/xattr -p com.apple.quarantine /Users/robert/Library/Caches/Homebrew/downloads/53eb50893fe352f66dded615b83802398af02cdf4d252f562dbbffc36970768d--JD2Setup.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5c921bd9\;Homebrew\\x20Cask\;6B42961A-3386-4139-A790-CAC650F437C6
==> Creating metadata directory /usr/local/Caskroom/jdownloader/.metadata/latest/20190320105426.570.
==> Creating metadata subdirectory /usr/local/Caskroom/jdownloader/.metadata/latest/20190320105426.570/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x00007ff0d9a77ac0>
==> Installing artifact of class Cask::Artifact::PreflightBlock
/usr/local/Caskroom/jdownloader/latest/JDownloader\ Installer.app/Contents/MacOS/JavaApplicationStub -dir /Applications -q -Dinstall4j.suppressStdout=true -Dinstall4j.debug=false -VcreateDesktopLinkAction\$Boolean=false -VaddToDockAction\$Boolean=false
==> Purging files for version latest of Cask jdownloader
Error: Failure while executing; `/usr/local/Caskroom/jdownloader/latest/JDownloader\ Installer.app/Contents/MacOS/JavaApplicationStub -dir /Applications -q -Dinstall4j.suppressStdout=true -Dinstall4j.debug=false -VcreateDesktopLinkAction\$Boolean=false -VaddToDockAction\$Boolean=false` exited with 1.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/dsl/base.rb:14:in `system_command'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/jdownloader.rb:11:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:39:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:39:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:22:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.0.5-10-g15495f0
==> macOS
10.14.3
==> SIP
Enabled
==> Java
12
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3993 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (195 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-cobertura-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.32.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.66.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/psych-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/psych-3.1.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.28.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.14.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2018.0812/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20180417/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.5
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.22/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.19.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.20.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.12.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/portable-ruby
```

**Comment by robertleeblairjr** [comment]
I just received a message from one of jdownloader's developers which is posted in the quotes.

> "Hi,

JDownloader itself supports Java 1.6 up to Java12 but Java9,10,11,12 are just experimental.
They are known to work. The installers (dmg) however are just supported up to Java8. I don't know
how this HomeBrew Cask works (it's not from us) but it shouldn't use the dmg installer at all but
should use the manual installation shown here, https://support.jdownloader.org/Knowledgebase/Article/View/52/0/install-jdownloader-on-nas-and-embedded-devices
I guess you should contact the author of the HomeBrew Cask and ask him either to switch to JDownloader.jar method
or he should contact us. I hope you understand that we can't provide support for 3rd party installers/installation ways

best regards
jiaz"

Their recommendation was for HomeBrew to use the manual method since cask is an unofficial installation method. The link and a screenshot attachment are below for reference.

[https://support.jdownloader.org/Knowledgebase/Article/View/52/0/install-jdownloader-on-nas-and-embedded-devices](url)

<img width="895" alt="Screen Shot 2019-03-20 at 6 16 34 AM" src="https://user-images.githubusercontent.com/12276457/54680564-2e330e00-4ad8-11e9-8be1-2baa6b6b61fe.png">

**Comment by vitorgalvao** [comment]
> Attempting to install the cask jdownloader fails with the recently released version JDK 12 and gives a "Startup Error".

The cask tells you right there at install time:

> jdownloader requires Java 8. You can install it with
>
>  brew cask install homebrew/cask-versions/java8

Which goes in line with the message from JDownloader’s developers:

> The installers (dmg) however are just supported up to Java8.

So please do instead what the cask asks.

**Comment by robertleeblairjr** [comment]
I'm aware that this was most likely incompatibility with the downloaded jdownloader installer file which was why I mentioned this in the initial ticket. However, the developers of the app recommended to use the other method for unofficial distribution so as to alleviate potential problems with installation. Hence, me mentioning all of this to begin with. Either way, I'll just stick with their recommended method of installation since the app functions absolutely fine with JDK 12.

**Comment by vitorgalvao** [comment]
> However, the developers of the app recommended to use the other method for unofficial distribution so as to alleviate potential problems with installation.

We used the old method, but since it required manual steps it was a worse experience, which is wh we adapted it. Unless we start seeing multiple users having problems with this method, it’s not worth it to change it back.

**Comment by robertleeblairjr** [comment]
It's cool. I was most certain that it was the installer failing but filed a ticket here since I set aside some time to submit one to the developer. Just wanted to ensure it wasn't anything brew related. Developer stated that it was surprising I've been able to install with the JDownloader.dmg up to JDK 11 because of install4jm. So, it won't be fixed until the developers patch the installers. The headless method installs but there is the caveat of creating an alias or other needed software links. This was the only app on my system which wasn't supporting installation or operation with any version greater than 8. Hence, the reason I had uninstalled 8 over a year ago and hadn't thought much of it. So, thanks for the reply.

**Comment by vitorgalvao** [comment]
> I was most certain that it was the installer failing but filed a ticket here since I set aside some time to submit one to the developer.

That was the right call. Ideally, we’d already be able to detect your installed Java version and not let you install JDownloader at all since it didn’t match, but we don’t have the functionality to do that yet.

**Comment by robertleeblairjr** [comment]
Sounds like a nice feature to add for checking dependencies. Here's a couple of links to installers, provided by the developer, which does have a check for current java version. The installer fails and outputs an error message if the supported version isn't installed. Have a good day and thanks for your help.

Checks for and uses system installed Java: https://mega.nz/#!nd800K7a!uvnqx5icsR_UHIheXhad3Q9BEYcsmGpFrHaIa77Abk8

Checks for and uses Apple installed Java:
https://mega.nz/#!KUck2IhB!GW4WlVGAug6-ayyYdqTAunKZ6mWOsHvNDsTXwJmuxOo

**Comment by vitorgalvao** [comment]
Thank you, but we can’t `curl` mega.nz links.
