### ISSUE TITLE
Wesnoth-1.14.6 cannot be upgraded or installed

### ISSUE THREAD

**Issue by mundschenk-at** [Homebrew/homebrew-cask#61186]
#### General troubleshooting steps

- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Upgrading `wesnoth` via `brew cask upgrade` fails, as does (re-)installing the cask.

#### Command that failed

```
brew cask install wesnoth
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.sourceforge.net/wesnoth/Wesnoth_1.14.6.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.6-62-g439283c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.4\)\ curl/7.54.0 --location --silent --head https://downloads.sourceforge.net/wesnoth/Wesnoth_1.14.6.dmg
Already downloaded: /Users/redacted/Library/Caches/Homebrew/downloads/3d1425812e2248df39c5dbe6e8bd5cbad620e9d0b9048465a6f2b5c9b698863f--Wesnoth_1.14.6.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/redacted/Library/Caches/Homebrew/downloads/3d1425812e2248df39c5dbe6e8bd5cbad620e9d0b9048465a6f2b5c9b698863f--Wesnoth_1.14.6.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/redacted/Library/Caches/Homebrew/downloads/3d1425812e2248df39c5dbe6e8bd5cbad620e9d0b9048465a6f2b5c9b698863f--Wesnoth_1.14.6.dmg
==> /Users/redacted/Library/Caches/Homebrew/downloads/3d1425812e2248df39c5dbe6e8bd5cbad620e9d0b9048465a6f2b5c9b698863f--Wesnoth_1.14.6.dmg is quarantined
==> Downloaded to -> /Users/redacted/Library/Caches/Homebrew/downloads/3d1425812e2248df39c5dbe6e8bd5cbad620e9d0b9048465a6f2b5c9b698863f--Wesnoth_1.14.6.dmg
==> Verifying SHA-256 checksum for Cask 'wesnoth'.
==> Installing Cask wesnoth
==> Cask::Installer#stage
hdiutil imageinfo /Users/redacted/Library/Caches/Homebrew/downloads/3d1425812e2248df39c5dbe6e8bd5cbad620e9d0b9048465a6f2b5c9b698863f--Wesnoth_1.14.6.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/redacted/Library/Caches/Homebrew/downloads/3d1425812e2248df39c5dbe6e8bd5cbad620e9d0b9048465a6f2b5c9b698863f--Wesnoth_1.14.6.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/s0/n55s6rc95ydfk_z2f9x99zqr0000gn/T/d20190331-14800-jbh9wk /Users/redacted/Library/Caches/Homebrew/downloads/3d1425812e2248df39c5dbe6e8bd5cbad620e9d0b9048465a6f2b5c9b698863f--Wesnoth_1.14.6.dmg
find . -print0
mkbom -s -i /var/folders/s0/n55s6rc95ydfk_z2f9x99zqr0000gn/T/20190331-14800-15gr9be.list -- /var/folders/s0/n55s6rc95ydfk_z2f9x99zqr0000gn/T/20190331-14800-1umr02v.bom
ditto --bom /var/folders/s0/n55s6rc95ydfk_z2f9x99zqr0000gn/T/20190331-14800-1umr02v.bom -- /private/var/folders/s0/n55s6rc95ydfk_z2f9x99zqr0000gn/T/d20190331-14800-jbh9wk/dmg.dAjJCS /var/folders/s0/n55s6rc95ydfk_z2f9x99zqr0000gn/T/d20190331-14800-1eiqdr0
diskutil eject /private/var/folders/s0/n55s6rc95ydfk_z2f9x99zqr0000gn/T/d20190331-14800-jbh9wk/dmg.dAjJCS
cp -pR /var/folders/s0/n55s6rc95ydfk_z2f9x99zqr0000gn/T/d20190331-14800-1eiqdr0/The\ Battle\ for\ Wesnoth.app/. /usr/local/Caskroom/wesnoth/1.14.6/The\ Battle\ for\ Wesnoth.app
cp -pR /var/folders/s0/n55s6rc95ydfk_z2f9x99zqr0000gn/T/d20190331-14800-1eiqdr0/.backgroundImage.tiff /usr/local/Caskroom/wesnoth/1.14.6/.backgroundImage.tiff
chmod -Rf +w /var/folders/s0/n55s6rc95ydfk_z2f9x99zqr0000gn/T/d20190331-14800-1eiqdr0
==> Verifying Gatekeeper status of /Users/redacted/Library/Caches/Homebrew/downloads/3d1425812e2248df39c5dbe6e8bd5cbad620e9d0b9048465a6f2b5c9b698863f--Wesnoth_1.14.6.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/redacted/Library/Caches/Homebrew/downloads/3d1425812e2248df39c5dbe6e8bd5cbad620e9d0b9048465a6f2b5c9b698863f--Wesnoth_1.14.6.dmg
==> /Users/redacted/Library/Caches/Homebrew/downloads/3d1425812e2248df39c5dbe6e8bd5cbad620e9d0b9048465a6f2b5c9b698863f--Wesnoth_1.14.6.dmg is quarantined
==> Propagating quarantine from /Users/redacted/Library/Caches/Homebrew/downloads/3d1425812e2248df39c5dbe6e8bd5cbad620e9d0b9048465a6f2b5c9b698863f--Wesnoth_1.14.6.dmg to /usr/local/Caskroom/wesnoth/1.14.6
/usr/bin/xattr -p com.apple.quarantine /Users/redacted/Library/Caches/Homebrew/downloads/3d1425812e2248df39c5dbe6e8bd5cbad620e9d0b9048465a6f2b5c9b698863f--Wesnoth_1.14.6.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5ca0f0ec\;Homebrew\\x20Cask\;BA24C48E-26B3-4D94-852D-4F948D402521
==> Creating metadata directory /usr/local/Caskroom/wesnoth/.metadata/1.14.6/20190331174408.763.
==> Creating metadata subdirectory /usr/local/Caskroom/wesnoth/.metadata/1.14.6/20190331174408.763/Casks.
==> Installing artifacts
==> 1 artifact/s defined
#<SortedSet:0x00007fe280bd7c10>
==> Installing artifact of class Cask::Artifact::App
==> Purging files for version 1.14.6 of Cask wesnoth
Error: It seems the App source '/usr/local/Caskroom/wesnoth/1.14.6/Wesnoth.app' is not there.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:39:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:11:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:211:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:202:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:161:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:161:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.0.6-62-g439283c
==> macOS
10.14.4
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4000 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-cobertura-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.32.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.66.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/psych-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/psych-3.1.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.28.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.16.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2018.0812/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20180417/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.5
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.22/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.19.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.20.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.12.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

**Comment by vitorgalvao** [comment]
[How to fix](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md).

**Comment by mundschenk-at** [comment]
Sorry, I missed that one (got distracted by the `Purging files for ...` line). Unfortunately, it looks like the app bundle got renamed, not moved, so (at least on a strict reading of the documentation), the cask would need a new token?

**Comment by vitorgalvao** [comment]
> the cask would need a new token?

Yes.

**Comment by jamebus** [comment]
Hi @mundschenk-at 

Yes, looks like new token should be thebattleforwesnoth

**Comment by core-code** [comment]
this is already fixed https://github.com/Homebrew/homebrew-cask/pull/61628

**Comment by mundschenk-at** [comment]
Will the new cask update the old one?

**Comment by vitorgalvao** [comment]
> Will the new cask update the old one?

No, because we don’t support renames. PRs for that are welcome.
