### ISSUE TITLE
Xquartz post-install defaults write fails

### ISSUE THREAD

**Issue by rgov** [Homebrew/homebrew-cask#62674]
#### General troubleshooting steps

- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Installing the XQuartz cask fails on a brand new macOS system (with Xcode, etc.).

#### Command that failed

```
brew cask install xquartz
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.1-104-g86822bc\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.4\)\ curl/7.54.0 --location --silent --head --request GET https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
Already downloaded: /Users/rzg/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/rzg/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/rzg/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> /Users/rzg/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg is quarantined
==> Downloaded to -> /Users/rzg/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> Verifying SHA-256 checksum for Cask 'xquartz'.
==> Installing Cask xquartz
==> Cask::Installer#stage
hdiutil imageinfo /Users/rzg/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/rzg/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/5c/dcdc8hpd1955xn3y6t1d4fbr0000gn/T/d20190501-33535-idwaxe /Users/rzg/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
find . -print0
mkbom -s -i /var/folders/5c/dcdc8hpd1955xn3y6t1d4fbr0000gn/T/20190501-33535-1ux424b.list -- /var/folders/5c/dcdc8hpd1955xn3y6t1d4fbr0000gn/T/20190501-33535-18jlu35.bom
ditto --bom /var/folders/5c/dcdc8hpd1955xn3y6t1d4fbr0000gn/T/20190501-33535-18jlu35.bom -- /private/var/folders/5c/dcdc8hpd1955xn3y6t1d4fbr0000gn/T/d20190501-33535-idwaxe/dmg.4qMHga /var/folders/5c/dcdc8hpd1955xn3y6t1d4fbr0000gn/T/d20190501-33535-ij31vz
diskutil eject /private/var/folders/5c/dcdc8hpd1955xn3y6t1d4fbr0000gn/T/d20190501-33535-idwaxe/dmg.4qMHga
chmod +rw /var/folders/5c/dcdc8hpd1955xn3y6t1d4fbr0000gn/T/d20190501-33535-ij31vz/XQuartz.pkg
cp -p /var/folders/5c/dcdc8hpd1955xn3y6t1d4fbr0000gn/T/d20190501-33535-ij31vz/XQuartz.pkg /usr/local/Caskroom/xquartz/2.7.11/XQuartz.pkg
==> Verifying Gatekeeper status of /Users/rzg/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/rzg/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> /Users/rzg/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg is quarantined
==> Propagating quarantine from /Users/rzg/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg to /usr/local/Caskroom/xquartz/2.7.11
/usr/bin/xattr -p com.apple.quarantine /Users/rzg/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5cca1276\;Homebrew\\x20Cask\;9A7AD80C-7417-4067-8AA0-991EFA270202
==> Creating metadata directory /usr/local/Caskroom/xquartz/.metadata/2.7.11/20190501215808.488.
==> Creating metadata subdirectory /usr/local/Caskroom/xquartz/.metadata/2.7.11/20190501215808.488/Casks.
==> Installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x00007f9417b89590>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for xquartz; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=rzg USER=rzg USERNAME=rzg /usr/sbin/installer -pkg /usr/local/Caskroom/xquartz/2.7.11/XQuartz.pkg -target / -verboseR
installer: Package name is XQuartz 2.7.11
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing XQuartz 2.7.11…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%5.366005
installer:PHASE:Writing files…
installer:%15.657996
installer:PHASE:Writing files…
installer:%28.008384
installer:PHASE:Writing files…
installer:%30.066782
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:%32.125181
installer:PHASE:Writing files…
installer:%36.241977
installer:PHASE:Writing files…
installer:%38.300375
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:%63.783936
installer:PHASE:Moving items into place…
installer:%64.813109
installer:PHASE:Moving items into place…
installer:%65.845731
installer:PHASE:Moving items into place…
installer:%66.879386
installer:PHASE:Moving items into place…
installer:%67.907424
installer:PHASE:Moving items into place…
installer:%68.938384
installer:PHASE:Moving items into place…
installer:%69.960038
installer:PHASE:Moving items into place…
installer:%70.995946
installer:PHASE:Moving items into place…
installer:%72.023795
installer:PHASE:Moving items into place…
installer:%73.054467
installer:PHASE:Moving items into place…
installer:%84.537898
installer:PHASE:Running package scripts…
installer:%85.567198
installer:PHASE:Running package scripts…
installer:%85.643531
installer:PHASE:Running package scripts…
[repeated many times]
installer:PHASE:Running package scripts…
installer:%86.036163
installer:PHASE:Writing package receipts…
installer:PHASE:Validating packages…
installer:%97.750000
installer:STATUS:Running installer actions…
installer:STATUS:
installer:PHASE:Finishing the Installation…
installer:STATUS:
installer:%100.000000
installer:PHASE:The software was successfully installed.
installer: The upgrade was successful.
==> Installing artifact of class Cask::Artifact::PostflightBlock
/usr/bin/defaults write com.apple.applescript ApplicationMap -dict-add X11 file://localhost/Applications/Utilities/XQuartz.app/
2019-05-01 17:59:33.285 defaults[34396:305869] Could not write domain com.apple.applescript; exiting
==> Purging files for version 2.7.11 of Cask xquartz
Error: Failure while executing; `/usr/bin/defaults write com.apple.applescript ApplicationMap -dict-add X11 file://localhost/Applications/Utilities/XQuartz.app/` exited with 1. Here's the output:
2019-05-01 17:59:33.285 defaults[34396:305869] Could not write domain com.apple.applescript; exiting

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:109:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:52:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/dsl/base.rb:16:in `system_command'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/xquartz.rb:19:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:41:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:41:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:24:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:214:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:205:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.1.1-104-g86822bc
==> macOS
10.14.4
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4019 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-cobertura-1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.32.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-performance-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.67.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/psych-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/psych-3.1.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.28.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.17.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2019.0331/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20180417/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.22/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.19.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.20.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.14.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

**Comment by rgov** [comment]
I'm pretty sure this would be the case if Terminal.app does not have Full Disk Access in the Security & Privacy prefpane.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/62707
