### ISSUE TITLE
more and more cask is asking sudo permissions

### ISSUE THREAD

**Issue by clouds56** [Homebrew/homebrew-cask#62739]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

more and more casks are requiring `sudo`, for example
```
==> Verifying SHA-256 checksum for Cask 'kicad'.
==> Uninstalling Cask kicad
==> Backing App 'bitmap2component.app' up to '/usr/local/Caskroom/kicad/5.1.2-1/KiCad/bitmap2component.app'.
==> Removing App '/Applications/KiCad/bitmap2component.app'.
==> Backing App 'eeschema.app' up to '/usr/local/Caskroom/kicad/5.1.2-1/KiCad/eeschema.app'.
==> Removing App '/Applications/KiCad/eeschema.app'.
==> Backing App 'gerbview.app' up to '/usr/local/Caskroom/kicad/5.1.2-1/KiCad/gerbview.app'.
==> Removing App '/Applications/KiCad/gerbview.app'.
==> Backing App 'pcb_calculator.app' up to '/usr/local/Caskroom/kicad/5.1.2-1/KiCad/pcb_calculator.app'.
==> Removing App '/Applications/KiCad/pcb_calculator.app'.
==> Backing App 'pcbnew.app' up to '/usr/local/Caskroom/kicad/5.1.2-1/KiCad/pcbnew.app'.
==> Removing App '/Applications/KiCad/pcbnew.app'.
==> Backing App 'pl_editor.app' up to '/usr/local/Caskroom/kicad/5.1.2-1/KiCad/pl_editor.app'.
==> Removing App '/Applications/KiCad/pl_editor.app'.
==> Backing Generic Artifact 'help' up to '/usr/local/Caskroom/kicad/5.1.2-1/kicad/help'.
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: 3 incorrect password attempts
Error: Failure while executing; `/usr/bin/sudo -E -- /bin/cp -pR /Library/Application\ Support/kicad/help /usr/local/Caskroom/kicad/5.1.2-1/kicad/help` exited with 1. Here's the output:
Sorry, try again.
Sorry, try again.
sudo: 3 incorrect password attempts
```
and for java
```
==> Verifying SHA-256 checksum for Cask 'java'.
==> Uninstalling Cask java
==> Backing Generic Artifact 'openjdk-12.0.1.jdk' up to '/usr/local/Caskroom/java/12.0.1,69cfe15208a647278a19ef0990eea691/jdk-12.0.1.jdk'.
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: 3 incorrect password attempts
Error: Failure while executing; `/usr/bin/sudo -E -- /bin/cp -pR /Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk /usr/local/Caskroom/java/12.0.1,69cfe15208a647278a19ef0990eea691/jdk-12.0.1.jdk` exited with 1. Here's the output:
Sorry, try again.
Sorry, try again.
sudo: 3 incorrect password attempts

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:109:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:52:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:80:in `move_back'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:17:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:453:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:449:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:398:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:137:in `uninstall_existing_cask'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:126:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:13:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:7:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:7:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

### I'm not saying the issue is about failures, the failure is intend, I'm saying about unintended sudo usage

I've checked `/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:80:in 'move_back'`, it is saying
```ruby
ohai "Backing #{self.class.english_name} '#{target.basename}' up to '#{source}'."
source.dirname.mkpath

# We need to preserve extended attributes between copies.
command.run!("/bin/cp", args: ["-pR", target, source], sudo: !target.parent.writable?)
```
I've checked with `irb` if `target.parent` not exists, the writable would always returns false
```
irb(main):001:0> require 'pathname'
=> true
irb(main):002:0> Pathname.new('/tmp/nonexists/a.txt')
=> #<Pathname:/tmp/nonexists/a.txt>
irb(main):003:0> Pathname.new('/tmp/nonexists/a.txt').parent.writable?
=> false
irb(main):004:0> Pathname.new('/tmp/nonexists/a.txt').parent.parent.writable?
=> true
```
So is it serious that we `source.dirname.mkpath` make path for source but not target here?

#### Command that failed

```
brew reinstall java
```

#### Output of command with `--force --verbose --debug`

```
# not applies
```

#### Output of `brew cask doctor`

```

==> Homebrew Version
2.1.1-112-g7da51b4
==> macOS
10.14.4
==> SIP
Enabled
==> Java
12.0.1, 1.8.0_181, 1.8.0_131
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4014 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (199 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (164 casks)
/usr/local/Homebrew/Library/Taps/fbsb/homebrew-flutter (1 cask)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-cobertura-1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.32.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-performance-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.67.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/psych-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/psych-3.1.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.28.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.17.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2019.0331/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20180417/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.22/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.19.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.20.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.14.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
dart-lang/dart
david0/audio
fbsb/flutter
homebrew/cask
homebrew/cask-drivers
homebrew/cask-versions
homebrew/core
homebrew/services
```

**Comment by clouds56** [comment]
Sorry for mixing the confusing source and target here, but the statement is still true, why I have to use `sudo` for almost every single cask

**Comment by vitorgalvao** [comment]
We only use `sudo` when necessary. We also don’t like to ask for it. If something needs `sudo`, it would also need it manually. Hence complain to upstream, not us.

**Comment by clouds56** [comment]
So if the `sudo` is necessary, shall we show more info when sudo is required?
1. is it only used in moving files? or would be used in some script?
2. could we revoke the sudo permission after the cask installed? e.g. when doing `brew cask upgrade`, I don't know the permission would be used in one cask or carried to next cask.

What I concern is some cask is installed without sudo and after some time it request it, [here's](https://github.com/Homebrew/homebrew-cask/commit/c210c1851eee0afa4ad95385c3fa586c4b089cb2) an example. (Note that without running the script, the cask is still functional.)

**Comment by vitorgalvao** [comment]
> shall we show more info when sudo is required?

We had an issue open about showing in `info` when a cask was going to need `sudo`. There was not enough interest in the feature.

> is it only used in moving files? or would be used in some script?

It’s in things like installing a `pkg`.

> could we revoke the sudo permission after the cask installed?

`sudo` is a system tool. We’re not going to mess around with it. If you want to change its timeout to always require a password, [do it](https://unix.stackexchange.com/questions/382060/change-default-sudo-password-timeout).

> [here's](https://github.com/Homebrew/homebrew-cask/commit/c210c1851eee0afa4ad95385c3fa586c4b089cb2) an example. (Note that without running the script, the cask is still functional.)

That’s an **uninstall** script.

**Comment by clouds56** [comment]
> That’s an uninstall script.

is there a way to uninstall/upgrade the package without invoke uninstall script? AFAIK, if uninstall script failed, it would also refuse to continue.

**Comment by vitorgalvao** [comment]
> is there a way to uninstall/upgrade the package without invoke uninstall script?

Do it manually. We won’t offer support there; you’re asking about uninstalling without using the system designed for that.

**Comment by clouds56** [comment]
Sounds like you are saying, we let you install the cask, and we know it doesn't require sudo to install, but once if you opt-in, you have to provide sudo to run a arbitrary **binary** that out of our control to opt-out. (It is wired, if the install procedure doesn't require sudo, why does the uninstall script has to provide sudo? How do you think it could change privileged things during install?)

> Hence complain to upstream, not us.

If this is the only answer, I doubt the security of any other cask that the repo provides. You are actually helping upstream to get unintended sudo permission.

> There was not enough interest in the feature.

If the users don't know an suspicious binary is running under sudo, they would never worry.

BTW, what's the procedure of manually uninstall? I could manually delete the app, but the homebrew thinks the cask is still present.

**Comment by clouds56** [comment]
And for this question

> is it only used in moving files? or would be used in some script?

I'm saying could you show every statement that invoking with sudo (even if I run with verbose, it would would show commands but never tell whether the command line is wrapping with sudo).

**Comment by vitorgalvao** [comment]
> I could manually delete the app, but the homebrew thinks the cask is still present.

Delete its directory under `$(brew --prefix)/Caskroom` and HBC will forget it.

> I'm saying could you show every statement that invoking with sudo

No, I could not, because I don’t recall them all off the top of my head and I’m not going to dig through the code to continue discussing this. Quite frankly, I’ve given this issue more support than it warrants. You can search old issues and our documentation for the answers.

> If this is the only answer, I doubt the security of any other cask that the repo provides.

Then please do stop using Homebrew Cask. We’re forward that there’s only so much we can do regarding security, and that the last line of defence is always the user.

You can either help us by testing *specific* things and fixing them (e.g. maybe that particular script doesn’t need `sudo` anymore) or you can ask upstream for changes so that `sudo` is never required. If you’re only going to keep complaining about the system in vague terms, I have better things to do with my free time on a Sunday.
