### ISSUE TITLE
Error: Unknown command: casc

### ISSUE THREAD

**Issue by narrowtux** [Homebrew/homebrew-cask#63355]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I can't install cascs because brew says it can't even find the `casc` command

#### Command that failed

```
brew casc install pdftotext
```

#### Output of command with `--force --verbose --debug`

```
Error: Unknown command: casc
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/utils.rb:67:in `exit'
/usr/local/Homebrew/Library/Homebrew/utils.rb:67:in `odie'
/usr/local/Homebrew/Library/Homebrew/brew.rb:114:in `<main>'
```

#### Output of `brew cask doctor`

```
Error: Unknown command: casc
```

#### Output of `brew tap`

```
caskformula/caskformula
cema-sp/tap
esphen/wsta
grafana/grafana
homebrew/cask
homebrew/core
homebrew/science
homebrew/services
mscharley/homebrew
timescale/tap
```

#### Output of `brew --version`

```
Homebrew 2.1.2-51-g3dc3ab9
Homebrew/homebrew-core (git revision 4f140c; last commit 2019-05-15)
Homebrew/homebrew-cask (git revision 2327b; last commit 2019-05-16)
```

**Comment by narrowtux** [comment]
mistyped cask as casc, very sorry
