### ISSUE TITLE
brew cask install virtualbox-extension-pack fails to update when installed and fails to install if removed

### ISSUE THREAD

**Issue by markyjackson-taulia** [Homebrew/homebrew-cask#63441]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

When running update for virtualbox-extension-pack it fails. It tried removing and reinstalling and it fails with the following error:
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=markyjackson USER=markyjackson USERNAME=markyjackson /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/6.0.8,130520/VirtualBox.pkg -target /` exited with 1. Here's the output:
installer: Package name is Oracle VM VirtualBox
installer: Upgrading at base path /
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:109:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:52:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:214:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:205:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:345:in `block in cask_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:338:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:338:in `cask_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:251:in `satisfy_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:63:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:94:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

#### Command that failed

```
brew cask install virtualbox-extension-pack
```

#### Output of command with `--force --verbose --debug`

```
(base) Markys-MBP-2:~ markyjackson$ brew cask install virtualbox-extension-pack --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Caveats
Installing virtualbox-extension-pack means you have AGREED to the license at:
  https://www.virtualbox.org/wiki/VirtualBox_PUEL

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Installing Cask dependencies: virtualbox
==> Cask::Installer#install
==> Printing caveats
==> Caveats
To install and/or use virtualbox you may need to enable its kernel extension in:
  System Preferences → Security & Privacy → General
For more information refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.virtualbox.org/virtualbox/6.0.8/VirtualBox-6.0.8-130520-OSX.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.2-58-ge098c37\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.5\)\ curl/7.54.0 --location --silent --head --request GET https://download.virtualbox.org/virtualbox/6.0.8/VirtualBox-6.0.8-130520-OSX.dmg
Already downloaded: /Users/markyjackson/Library/Caches/Homebrew/downloads/130d78b88001e8d144b4c39fedf0caa739515abf930f870f90f440eaf644ea8c--VirtualBox-6.0.8-130520-OSX.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/markyjackson/Library/Caches/Homebrew/downloads/130d78b88001e8d144b4c39fedf0caa739515abf930f870f90f440eaf644ea8c--VirtualBox-6.0.8-130520-OSX.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/markyjackson/Library/Caches/Homebrew/downloads/130d78b88001e8d144b4c39fedf0caa739515abf930f870f90f440eaf644ea8c--VirtualBox-6.0.8-130520-OSX.dmg
==> /Users/markyjackson/Library/Caches/Homebrew/downloads/130d78b88001e8d144b4c39fedf0caa739515abf930f870f90f440eaf644ea8c--VirtualBox-6.0.8-130520-OSX.dmg is quarantined
==> Downloaded to -> /Users/markyjackson/Library/Caches/Homebrew/downloads/130d78b88001e8d144b4c39fedf0caa739515abf930f870f90f440eaf644ea8c--VirtualBox-6.0.8-130520-OSX.dmg
==> Verifying SHA-256 checksum for Cask 'virtualbox'.
==> Installing Cask virtualbox
==> Cask::Installer#stage
hdiutil imageinfo /Users/markyjackson/Library/Caches/Homebrew/downloads/130d78b88001e8d144b4c39fedf0caa739515abf930f870f90f440eaf644ea8c--VirtualBox-6.0.8-130520-OSX.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/markyjackson/Library/Caches/Homebrew/downloads/130d78b88001e8d144b4c39fedf0caa739515abf930f870f90f440eaf644ea8c--VirtualBox-6.0.8-130520-OSX.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/z3/zchscg0n0v514p0981rmvyvc0000gn/T/d20190517-9535-11syjpi /Users/markyjackson/Library/Caches/Homebrew/downloads/130d78b88001e8d144b4c39fedf0caa739515abf930f870f90f440eaf644ea8c--VirtualBox-6.0.8-130520-OSX.dmg
find . -print0
mkbom -s -i /var/folders/z3/zchscg0n0v514p0981rmvyvc0000gn/T/20190517-9535-6j9nvm.list -- /var/folders/z3/zchscg0n0v514p0981rmvyvc0000gn/T/20190517-9535-11cn218.bom
ditto --bom /var/folders/z3/zchscg0n0v514p0981rmvyvc0000gn/T/20190517-9535-11cn218.bom -- /private/var/folders/z3/zchscg0n0v514p0981rmvyvc0000gn/T/d20190517-9535-11syjpi/dmg.4Juq8s /var/folders/z3/zchscg0n0v514p0981rmvyvc0000gn/T/d20190517-9535-nn3w9
diskutil eject /private/var/folders/z3/zchscg0n0v514p0981rmvyvc0000gn/T/d20190517-9535-11syjpi/dmg.4Juq8s
cp -pR /var/folders/z3/zchscg0n0v514p0981rmvyvc0000gn/T/d20190517-9535-nn3w9/VirtualBox.pkg /usr/local/Caskroom/virtualbox/6.0.8,130520/VirtualBox.pkg
cp -pR /var/folders/z3/zchscg0n0v514p0981rmvyvc0000gn/T/d20190517-9535-nn3w9/VirtualBox_Uninstall.tool /usr/local/Caskroom/virtualbox/6.0.8,130520/VirtualBox_Uninstall.tool
cp -pR /var/folders/z3/zchscg0n0v514p0981rmvyvc0000gn/T/d20190517-9535-nn3w9/UserManual.pdf /usr/local/Caskroom/virtualbox/6.0.8,130520/UserManual.pdf
chmod -Rf +w /var/folders/z3/zchscg0n0v514p0981rmvyvc0000gn/T/d20190517-9535-nn3w9
==> Verifying Gatekeeper status of /Users/markyjackson/Library/Caches/Homebrew/downloads/130d78b88001e8d144b4c39fedf0caa739515abf930f870f90f440eaf644ea8c--VirtualBox-6.0.8-130520-OSX.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/markyjackson/Library/Caches/Homebrew/downloads/130d78b88001e8d144b4c39fedf0caa739515abf930f870f90f440eaf644ea8c--VirtualBox-6.0.8-130520-OSX.dmg
==> /Users/markyjackson/Library/Caches/Homebrew/downloads/130d78b88001e8d144b4c39fedf0caa739515abf930f870f90f440eaf644ea8c--VirtualBox-6.0.8-130520-OSX.dmg is quarantined
==> Propagating quarantine from /Users/markyjackson/Library/Caches/Homebrew/downloads/130d78b88001e8d144b4c39fedf0caa739515abf930f870f90f440eaf644ea8c--VirtualBox-6.0.8-130520-OSX.dmg to /usr/local/Caskroom/virtualbox/6.0.8,130520
/usr/bin/xattr -p com.apple.quarantine /Users/markyjackson/Library/Caches/Homebrew/downloads/130d78b88001e8d144b4c39fedf0caa739515abf930f870f90f440eaf644ea8c--VirtualBox-6.0.8-130520-OSX.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5cdd6001\;Homebrew\\x20Cask\;C4B3DC4D-4B8F-4B50-BB1C-40080B5014E3
==> Creating metadata directory /usr/local/Caskroom/virtualbox/.metadata/6.0.8,130520/20190517133314.097.
==> Creating metadata subdirectory /usr/local/Caskroom/virtualbox/.metadata/6.0.8,130520/20190517133314.097/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00007f881c6963c8>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=markyjackson USER=markyjackson USERNAME=markyjackson /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/6.0.8,130520/VirtualBox.pkg -target / -verboseR
installer: Package name is Oracle VM VirtualBox
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%12.990501
installer:PHASE:Writing files…
installer:%36.889739
installer:PHASE:Writing files…
installer:%67.635607
installer:PHASE:Removing old files…
installer:%87.075853
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 6.0.8,130520 of Cask virtualbox
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=markyjackson USER=markyjackson USERNAME=markyjackson /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/6.0.8,130520/VirtualBox.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Oracle VM VirtualBox
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%12.990501
installer:PHASE:Writing files…
installer:%36.889739
installer:PHASE:Writing files…
installer:%67.635607
installer:PHASE:Removing old files…
installer:%87.075853
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:109:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:52:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:214:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:205:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:345:in `block in cask_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:338:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:338:in `cask_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:251:in `satisfy_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:63:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:94:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/markyjackson/anaconda3/bin/icu-config
  /Users/markyjackson/anaconda3/bin/krb5-config
  /Users/markyjackson/anaconda3/bin/freetype-config
  /Users/markyjackson/anaconda3/bin/xslt-config
  /Users/markyjackson/anaconda3/bin/libpng16-config
  /Users/markyjackson/anaconda3/bin/python3.7-config
  /Users/markyjackson/anaconda3/bin/libpng-config
  /Users/markyjackson/anaconda3/bin/xml2-config
  /Users/markyjackson/anaconda3/bin/python3.7m-config
  /Users/markyjackson/anaconda3/bin/python3-config
  /Users/markyjackson/anaconda3/bin/curl-config
  /Users/markyjackson/anaconda3/bin/ncursesw6-config
  /Users/markyjackson/anaconda3/bin/pcre-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  aws-iam-authenticator
  gnupg

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
```

#### Output of `brew tap`

```
buo/cask-upgrade
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
tsub/s3-edit
weaveworks/tap
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/63337
