### ISSUE TITLE
Metasploit [Broken link]

### ISSUE THREAD

**Issue by gabrielbcn** [Homebrew/homebrew-cask#64840]
#### Description of issue

Broken link in Metasploit cask (HTTP response 404 not found)

#### Command that failed

```
brew cask install metasploit
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nmap.rb
All Formula dependencies satisfied.
==> Downloading
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.5-13-g755123d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.5\)\ curl/7.54.0 --location --silent --head --request GET https://osx.metasploit.com/metasploit-framework-5.0.22\+20190514142852-1rapid7-1.pkg
==> Downloading https://osx.metasploit.com/metasploit-framework-5.0.22+20190514142852-1rapid7-1.pkg
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.5-13-g755123d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.5\)\ curl/7.54.0 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://osx.metasploit.com/metasploit-framework-5.0.22\+20190514142852-1rapid7-1.pkg
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.5-13-g755123d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.5\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/gabriel/Library/Caches/Homebrew/downloads/b43721869b8ed50834ccfd0be3d7da123e556a0344479fce5a6a14e7aa8f1601--metasploit-framework-5.0.22\ 20190514142852-1rapid7-1.pkg.incomplete https://osx.metasploit.com/metasploit-framework-5.0.22\+20190514142852-1rapid7-1.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'metasploit' with message: Download failed: https://osx.metasploit.com/metasploit-framework-5.0.22+20190514142852-1rapid7-1.pkg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:311:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:308:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:42:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:20:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:149:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:66:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:94:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:159:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:163:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:147:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/64846

**Comment by gabrielbcn** [comment]
Failing again. 

Download failed: https://osx.metasploit.com/metasploit-framework-5.0.46+20190902103422-1rapid7-1.pkg

Checked and the file doesn't exist.
