### ISSUE TITLE
Can't install intel-power-gadget due to not trusted certificate

### ISSUE THREAD

**Issue by petr-ujezdsky** [Homebrew/homebrew-cask#65484]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Cask `intel-power-gadget` can not be installed due to not trusted certificate.
```
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
```
I have not tried it with the `-allowUntrusted` because I am not sure if it has not been hijacked.

#### Command that failed

```
brew cask install intel-power-gadget
```

#### Output of command with `--force --verbose --debug`

```
brew cask install --force --verbose --debug intel-power-gadget
==> Cask::Installer#install
==> Printing caveats
==> Caveats
To install and/or use intel-power-gadget you may need to enable its kernel extension in:
  System Preferences → Security & Privacy → General
For more information refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://software.intel.com/file/778485/download
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.6-37-g686760d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.5\)\ curl/7.54.0 --location --silent --head --request GET https://software.intel.com/file/778485/download
Already downloaded: /Users/pujezdsky/Library/Caches/Homebrew/downloads/6b0022b514d275c9d0e38f06f24c10399fdcc02eec7c181d4940493d6f3c1b30--Intel® Power Gadget 3.5.5.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/pujezdsky/Library/Caches/Homebrew/downloads/6b0022b514d275c9d0e38f06f24c10399fdcc02eec7c181d4940493d6f3c1b30--Intel® Power Gadget 3.5.5.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/pujezdsky/Library/Caches/Homebrew/downloads/6b0022b514d275c9d0e38f06f24c10399fdcc02eec7c181d4940493d6f3c1b30--Intel\®\ Power\ Gadget\ 3.5.5.dmg
==> /Users/pujezdsky/Library/Caches/Homebrew/downloads/6b0022b514d275c9d0e38f06f24c10399fdcc02eec7c181d4940493d6f3c1b30--Intel® Power Gadget 3.5.5.dmg is quarantined
==> Downloaded to -> /Users/pujezdsky/Library/Caches/Homebrew/downloads/6b0022b514d275c9d0e38f06f24c10399fdcc02eec7c181d4940493d6f3c1b30--Intel® Power Gadget 3.5.5.dmg
==> Verifying SHA-256 checksum for Cask 'intel-power-gadget'.
==> Installing Cask intel-power-gadget
==> Cask::Installer#stage
hdiutil imageinfo /Users/pujezdsky/Library/Caches/Homebrew/downloads/6b0022b514d275c9d0e38f06f24c10399fdcc02eec7c181d4940493d6f3c1b30--Intel\®\ Power\ Gadget\ 3.5.5.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/pujezdsky/Library/Caches/Homebrew/downloads/6b0022b514d275c9d0e38f06f24c10399fdcc02eec7c181d4940493d6f3c1b30--Intel® Power Gadget 3.5.5.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/g6/yb59stqx0lx3qdb3j1gpkv8r0000gn/T/d20190628-68123-8s9oey /Users/pujezdsky/Library/Caches/Homebrew/downloads/6b0022b514d275c9d0e38f06f24c10399fdcc02eec7c181d4940493d6f3c1b30--Intel\®\ Power\ Gadget\ 3.5.5.dmg
find . -print0
mkbom -s -i /var/folders/g6/yb59stqx0lx3qdb3j1gpkv8r0000gn/T/20190628-68123-93wgyi.list -- /var/folders/g6/yb59stqx0lx3qdb3j1gpkv8r0000gn/T/20190628-68123-10tdjj8.bom
ditto --bom /var/folders/g6/yb59stqx0lx3qdb3j1gpkv8r0000gn/T/20190628-68123-10tdjj8.bom -- /private/var/folders/g6/yb59stqx0lx3qdb3j1gpkv8r0000gn/T/d20190628-68123-8s9oey/dmg.Q9yGhP /var/folders/g6/yb59stqx0lx3qdb3j1gpkv8r0000gn/T/d20190628-68123-cxnnto
diskutil eject /private/var/folders/g6/yb59stqx0lx3qdb3j1gpkv8r0000gn/T/d20190628-68123-8s9oey/dmg.Q9yGhP
cp -pR /var/folders/g6/yb59stqx0lx3qdb3j1gpkv8r0000gn/T/d20190628-68123-cxnnto/Install\ Intel\ Power\ Gadget.pkg /usr/local/Caskroom/intel-power-gadget/3.5.5,778485/Install\ Intel\ Power\ Gadget.pkg
cp -pR /var/folders/g6/yb59stqx0lx3qdb3j1gpkv8r0000gn/T/d20190628-68123-cxnnto/CorePlot-License.txt /usr/local/Caskroom/intel-power-gadget/3.5.5,778485/CorePlot-License.txt
cp -pR /var/folders/g6/yb59stqx0lx3qdb3j1gpkv8r0000gn/T/d20190628-68123-cxnnto/.apdisk /usr/local/Caskroom/intel-power-gadget/3.5.5,778485/.apdisk
chmod -Rf +w /var/folders/g6/yb59stqx0lx3qdb3j1gpkv8r0000gn/T/d20190628-68123-cxnnto
==> Verifying Gatekeeper status of /Users/pujezdsky/Library/Caches/Homebrew/downloads/6b0022b514d275c9d0e38f06f24c10399fdcc02eec7c181d4940493d6f3c1b30--Intel® Power Gadget 3.5.5.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/pujezdsky/Library/Caches/Homebrew/downloads/6b0022b514d275c9d0e38f06f24c10399fdcc02eec7c181d4940493d6f3c1b30--Intel\®\ Power\ Gadget\ 3.5.5.dmg
==> /Users/pujezdsky/Library/Caches/Homebrew/downloads/6b0022b514d275c9d0e38f06f24c10399fdcc02eec7c181d4940493d6f3c1b30--Intel® Power Gadget 3.5.5.dmg is quarantined
==> Propagating quarantine from /Users/pujezdsky/Library/Caches/Homebrew/downloads/6b0022b514d275c9d0e38f06f24c10399fdcc02eec7c181d4940493d6f3c1b30--Intel® Power Gadget 3.5.5.dmg to /usr/local/Caskroom/intel-power-gadget/3.5.5,778485
/usr/bin/xattr -p com.apple.quarantine /Users/pujezdsky/Library/Caches/Homebrew/downloads/6b0022b514d275c9d0e38f06f24c10399fdcc02eec7c181d4940493d6f3c1b30--Intel\®\ Power\ Gadget\ 3.5.5.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5d165902\;Homebrew\\x20Cask\;21F9BAB0-2CFB-42D5-8B56-5B9DCD8D8D05
==> Creating metadata directory /usr/local/Caskroom/intel-power-gadget/.metadata/3.5.5,778485/20190628183025.246.
==> Creating metadata subdirectory /usr/local/Caskroom/intel-power-gadget/.metadata/3.5.5,778485/20190628183025.246/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x00007fc9ed401960>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for intel-power-gadget; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=pujezdsky USER=pujezdsky USERNAME=pujezdsky /usr/sbin/installer -pkg /usr/local/Caskroom/intel-power-gadget/3.5.5,778485/Install\ Intel\ Power\ Gadget.pkg -target / -verboseR
installer: Package name is Intel® Power Gadget
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
==> Purging files for version 3.5.5,778485 of Cask intel-power-gadget
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=pujezdsky USER=pujezdsky USERNAME=pujezdsky /usr/sbin/installer -pkg /usr/local/Caskroom/intel-power-gadget/3.5.5,778485/Install\ Intel\ Power\ Gadget.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Intel® Power Gadget
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:109:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:52:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:214:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:205:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:159:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:168:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:168:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:147:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew Version
2.1.6-37-g686760d
==> macOS
10.14.5
==> SIP
Enabled
==> Java
12.0.1, 1.8.0_192, 1.6.0_65-b14-468
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3595 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-cobertura-1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.33.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-performance-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.72.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.29.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.17.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2019.0331/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20180417/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.15.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
brew tap
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
```

**Comment by vitorgalvao** [comment]
That cask has been giving problems for some time. Adding to that, we don’t allow untrusted `pkg`s in the main repos, so it seems like it’s time to remove it.

https://github.com/Homebrew/homebrew-cask/pull/65487

**Comment by core-code** [comment]
lets try this before deleting it:

https://github.com/Homebrew/homebrew-cask/pull/65513

**Comment by out0fmemory** [comment]
> lets try this before deleting it:
> 
> #65513

This new version CAN NOT use on 10.14.5, because this version can not load intel driver

**Comment by petr-ujezdsky** [comment]
I am on 10.14.5 and I can confirm that the app does not work.
`brew install` works but after starting the app I only get modal dialog saying "The power gadget driver is not currently loaded...". I have to enable some setting that does not exist for me.

see https://developer.apple.com/library/archive/technotes/tn2459/_index.html

**Comment by core-code** [comment]
could you please report those bugs upstream?

**Comment by petr-ujezdsky** [comment]
There is already a question on reddit
https://www.reddit.com/r/applehelp/comments/c783ct/cannot_load_intel_power_gadget_driver/?ref=readnext

The old (presumably) working version has now expired certificate (till 26.6.2019) which causes this `brew install` issue.
The new version seems to be incompatible.

Unfortunately I do not know where to submit the bug :(
Installers can be downloaded from https://software.intel.com/en-us/articles/intel-power-gadget

**Comment by core-code** [comment]
> Unfortunately I do not know where to submit the bug :(

it seems the only way is to leave a comment at the bottom of the page:
https://software.intel.com/en-us/articles/intel-power-gadget

**Comment by petr-ujezdsky** [comment]
Added comment, but it is under review :(
```
Your comment has been queued for review by site administrators and will be published after approval.
```

Now only time will tell...

**Comment by seognil** [comment]
@petr-ujezdsky 
I deal with it by manually install the previous version (end with https://github.com/Homebrew/homebrew-cask/pull/65513)
https://software.intel.com/file/778485/download

**Comment by petr-ujezdsky** [comment]
I can confirm that version `3.5.5 (3.5.5)` (see @seognil above)works if you accept the expired certificate.

The only thing we can do now is to wait for Intel to re-sign the app with up-to-date certificate.

**Comment by core-code** [comment]
and, like most companies they will do absolutely zero on this issue unless enough people complain to them about it. so please direct your feedback to their site and not here.
