### ISSUE TITLE
MacTeX-2019 install fails when installing .pkg.

### ISSUE THREAD

**Issue by Indego** [Homebrew/homebrew-cask#66836]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

MacTeX-2019 install fails when installing .pkg.
The installer does install properly when triggered manually through Finder, although homebrew does not then recognize it as homebrew package.

Might be related: the ChoiceChangeXML file does not exist.
`cat: /var/folders/jl/pkmcpxfn1n571cbkwpyp6rdh0000gp/T/choices20190726-62949-1aesz1a.xml: No such file or directory`

#### Command that failed

```
brew cask install mactex-no-gui --force --verbose --debug
```

#### Output of command with `--force --verbose --debug`

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
basex

==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ghostscript.rb
All Formula dependencies satisfied.
==> Downloading
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.8-13-g6db1c73\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.12.6\)\ curl/7.54.0 --location --silent --head --request GET http://mirror.ctan.org/systems/mac/mactex/mactex-20190508.pkg
==> Downloading http://mirror.ctan.org/systems/mac/mactex/mactex-20190508.pkg
==> Downloading from http://ctan.math.ca/tex-archive/systems/mac/mactex/mactex-20190508.pkg
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.8-13-g6db1c73\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.12.6\)\ curl/7.54.0 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null http://ctan.math.ca/tex-archive/systems/mac/mactex/mactex-20190508.pkg
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.8-13-g6db1c73\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.12.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg.incomplete http://ctan.math.ca/tex-archive/systems/mac/mactex/mactex-20190508.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3933M  100 3933M    0     0  3785k      0  0:17:43  0:17:43 --:--:-- 5184k
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg
/usr/bin/xattr -p com.apple.quarantine /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg
==> /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg is not quarantined
==> Quarantining /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg http://mirror.ctan.org/systems/mac/mactex/mactex-20190508.pkg https://www.tug.org/mactex/
==> Downloaded to -> /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg
==> Verifying SHA-256 checksum for Cask 'mactex-no-gui'.
==> Installing Cask mactex-no-gui
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Pkg for /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg
cp -p /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg /usr/local/Caskroom/mactex-no-gui/2019.0508/mactex-20190508.pkg
==> Verifying Gatekeeper status of /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg
/usr/bin/xattr -p com.apple.quarantine /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg
==> /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg is quarantined
==> Propagating quarantine from /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg to /usr/local/Caskroom/mactex-no-gui/2019.0508
/usr/bin/xattr -p com.apple.quarantine /Users/jessicawan/Library/Caches/Homebrew/downloads/7d0cf1b0723cc23ec79c7fde04a748da44108420ea800e0f4fa3eacc96bd6138--mactex-20190508.pkg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5d3b22a4\;Homebrew\\x20Cask\;6FE5CCCD-C048-492F-AE02-421D7806B8C5
==> Creating metadata directory /usr/local/Caskroom/mactex-no-gui/.metadata/2019.0508/20190726160209.131.
==> Creating metadata subdirectory /usr/local/Caskroom/mactex-no-gui/.metadata/2019.0508/20190726160209.131/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00007fe6793275f0>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for mactex-no-gui; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=jessicawan USER=jessicawan USERNAME=jessicawan /usr/sbin/installer -pkg /usr/local/Caskroom/mactex-no-gui/2019.0508/mactex-20190508.pkg -target / -verboseR -applyChoiceChangesXML /var/folders/jl/pkmcpxfn1n571cbkwpyp6rdh0000gp/T/choices20190726-62949-1aesz1a.xml
Password:
installer: Package name is MacTeX-2019
installer: choices changes file '/var/folders/jl/pkmcpxfn1n571cbkwpyp6rdh0000gp/T/choices20190726-62949-1aesz1a.xml' applied
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing MacTeX-2019…
installer: The install failed.
==> Purging files for version 2019.0508 of Cask mactex-no-gui
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=jessicawan USER=jessicawan USERNAME=jessicawan /usr/sbin/installer -pkg /usr/local/Caskroom/mactex-no-gui/2019.0508/mactex-20190508.pkg -target / -verboseR -applyChoiceChangesXML /var/folders/jl/pkmcpxfn1n571cbkwpyp6rdh0000gp/T/choices20190726-62949-1aesz1a.xml` exited with 1. Here's the output:
installer: Package name is MacTeX-2019
installer: choices changes file '/var/folders/jl/pkmcpxfn1n571cbkwpyp6rdh0000gp/T/choices20190726-62949-1aesz1a.xml' applied
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing MacTeX-2019…
installer: The install failed.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:111:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:52:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:71:in `block in with_choices_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tempfile.rb:295:in `open'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:67:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:214:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:205:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:159:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:168:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:168:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:147:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.1.8-13-g6db1c73
==> macOS
10.12.6
==> SIP
Enabled
==> Java
10.0.2, 1.6.0_65-b14-468
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3577 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (956 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (167 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-cobertura-1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.34.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-performance-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.73.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.29.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.17.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2019.0331/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.15.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin16
/Library/Ruby/Site/2.3.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin16
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/fish"
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
sass/sass
```

**Comment by aried3r** [comment]
I had the same problem recently, see https://github.com/Homebrew/homebrew-cask/issues/62647#issuecomment-517691113, however with enough disk space I was able to install MacTeX on macOS 10.14.6. I had about 8GB free and it failed, with ~12GB free it worked. Sadly the output of the installer isn't really helpful.

Maybe this is your issue, too?
