### ISSUE TITLE
Cask outdated faling 

### ISSUE THREAD

**Issue by JJGO** [Homebrew/homebrew-cask#67485]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Running `brew cask outdated` returns error 

```
Error: Cask 'hetimazipql' definition is invalid: invalid 'depends_on macos' value: ":mountain_lion"
```

#### Command that failed

```
brew cask outdated
```

#### Output of command with `--force --verbose --debug`

```
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cask/cmd/options.rb:65:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:43:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/outdated.rb:10:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:159:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:163:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:147:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/jjgo/.pyenv/shims/python2-config
  /Users/jjgo/.pyenv/shims/icu-config
  /Users/jjgo/.pyenv/shims/krb5-config
  /Users/jjgo/.pyenv/shims/libpng16-config
  /Users/jjgo/.pyenv/shims/python3.6m-config
  /Users/jjgo/.pyenv/shims/python3.7-config
  /Users/jjgo/.pyenv/shims/python2.7-config
  /Users/jjgo/.pyenv/shims/python3.7m-config
  /Users/jjgo/.pyenv/shims/powerline-config
  /Users/jjgo/.pyenv/shims/python-config
  /Users/jjgo/.pyenv/shims/python3-config
  /Users/jjgo/.pyenv/shims/ncursesw6-config
  /Users/jjgo/.pyenv/shims/pcre-config
  /Users/jjgo/.pyenv/shims/python3.6-config

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libdiskmgt.1.dylib
  /usr/local/lib/libnvpair.1.dylib
  /usr/local/lib/libuutil.1.dylib
  /usr/local/lib/libzfs.2.dylib
  /usr/local/lib/libzfs_core.1.dylib
  /usr/local/lib/libzpool.1.dylib

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libdiskmgt.la
  /usr/local/lib/libnvpair.la
  /usr/local/lib/libuutil.la
  /usr/local/lib/libzfs.la
  /usr/local/lib/libzfs_core.la
  /usr/local/lib/libzpool.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libdiskmgt.a
  /usr/local/lib/libnvpair.a
  /usr/local/lib/libuutil.a
  /usr/local/lib/libzfs.a
  /usr/local/lib/libzfs_core.a
  /usr/local/lib/libzpool.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  docker-machine
  joplin
  wine
  sshfs
  emacs
  mkvtoolnix
  docker-compose
```

#### Output of `brew tap`

```
caskformula/caskformula
cjbassi/gotop
colindean/fonts-nonfree
crisidev/chunkwm
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
koekeishiya/formulae
mscharley/homebrew
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/58046
