### ISSUE TITLE
$ brew cask install tuntap 

### ISSUE THREAD

**Issue by jmfayard** [Homebrew/homebrew-cask#68718]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Can not install tuntap http://tuntaposx.sourceforge.net/

#### Command that failed

```
brew cask install tuntap
```

Note: there is a caveat in the cask:

```
==> Caveats
To install and/or use tuntap you may need to enable its kernel extension in:
  System Preferences → Security & Privacy → General
For more information refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html
```

I followed the instruction but it didn't help. 

#### Output of command with `--force --verbose --debug`

```
brew cask install tuntap --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Caveats
To install and/or use tuntap you may need to enable its kernel extension in:
  System Preferences → Security & Privacy → General
For more information refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.sourceforge.net/tuntaposx/tuntap/20150118/tuntap_20150118.tar.gz
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.11-36-g7dd0466\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.5\)\ curl/7.54.0 --location --silent --head --request GET https://downloads.sourceforge.net/tuntaposx/tuntap/20150118/tuntap_20150118.tar.gz
Already downloaded: /Users/jmfayard/Library/Caches/Homebrew/downloads/0f08fbfcac9a00fd040db3d176fa26ebe155d7c8f36a19c538a75e6ddee28ff7--tuntap_20150118.tar.gz
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/jmfayard/Library/Caches/Homebrew/downloads/0f08fbfcac9a00fd040db3d176fa26ebe155d7c8f36a19c538a75e6ddee28ff7--tuntap_20150118.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/jmfayard/Library/Caches/Homebrew/downloads/0f08fbfcac9a00fd040db3d176fa26ebe155d7c8f36a19c538a75e6ddee28ff7--tuntap_20150118.tar.gz
==> /Users/jmfayard/Library/Caches/Homebrew/downloads/0f08fbfcac9a00fd040db3d176fa26ebe155d7c8f36a19c538a75e6ddee28ff7--tuntap_20150118.tar.gz is quarantined
==> Downloaded to -> /Users/jmfayard/Library/Caches/Homebrew/downloads/0f08fbfcac9a00fd040db3d176fa26ebe155d7c8f36a19c538a75e6ddee28ff7--tuntap_20150118.tar.gz
==> Verifying SHA-256 checksum for Cask 'tuntap'.
==> Installing Cask tuntap
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Tar for /Users/jmfayard/Library/Caches/Homebrew/downloads/0f08fbfcac9a00fd040db3d176fa26ebe155d7c8f36a19c538a75e6ddee28ff7--tuntap_20150118.tar.gz
tar xof /Users/jmfayard/Library/Caches/Homebrew/downloads/0f08fbfcac9a00fd040db3d176fa26ebe155d7c8f36a19c538a75e6ddee28ff7--tuntap_20150118.tar.gz -C /var/folders/f4/1h1ggk816rl9t7xlcqv483nr0000gn/T/d20190906-16455-f4md4d
cp -pR /var/folders/f4/1h1ggk816rl9t7xlcqv483nr0000gn/T/d20190906-16455-f4md4d/README.installer /usr/local/Caskroom/tuntap/20150118/README.installer
cp -pR /var/folders/f4/1h1ggk816rl9t7xlcqv483nr0000gn/T/d20190906-16455-f4md4d/README /usr/local/Caskroom/tuntap/20150118/README
cp -pR /var/folders/f4/1h1ggk816rl9t7xlcqv483nr0000gn/T/d20190906-16455-f4md4d/tuntap_20150118.pkg /usr/local/Caskroom/tuntap/20150118/tuntap_20150118.pkg
chmod -Rf +w /var/folders/f4/1h1ggk816rl9t7xlcqv483nr0000gn/T/d20190906-16455-f4md4d
==> Verifying Gatekeeper status of /Users/jmfayard/Library/Caches/Homebrew/downloads/0f08fbfcac9a00fd040db3d176fa26ebe155d7c8f36a19c538a75e6ddee28ff7--tuntap_20150118.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/jmfayard/Library/Caches/Homebrew/downloads/0f08fbfcac9a00fd040db3d176fa26ebe155d7c8f36a19c538a75e6ddee28ff7--tuntap_20150118.tar.gz
==> /Users/jmfayard/Library/Caches/Homebrew/downloads/0f08fbfcac9a00fd040db3d176fa26ebe155d7c8f36a19c538a75e6ddee28ff7--tuntap_20150118.tar.gz is quarantined
==> Propagating quarantine from /Users/jmfayard/Library/Caches/Homebrew/downloads/0f08fbfcac9a00fd040db3d176fa26ebe155d7c8f36a19c538a75e6ddee28ff7--tuntap_20150118.tar.gz to /usr/local/Caskroom/tuntap/20150118
/usr/bin/xattr -p com.apple.quarantine /Users/jmfayard/Library/Caches/Homebrew/downloads/0f08fbfcac9a00fd040db3d176fa26ebe155d7c8f36a19c538a75e6ddee28ff7--tuntap_20150118.tar.gz
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5d7245d5\;Homebrew\\x20Cask\;685501D3-158B-4224-B313-2368343D971A
==> Creating metadata directory /usr/local/Caskroom/tuntap/.metadata/20150118/20190906115215.701.
==> Creating metadata subdirectory /usr/local/Caskroom/tuntap/.metadata/20150118/20190906115215.701/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x00007fea07a761f8>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for tuntap; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=jmfayard USER=jmfayard USERNAME=jmfayard /usr/sbin/installer -pkg /usr/local/Caskroom/tuntap/20150118/tuntap_20150118.pkg -target / -verboseR
Password:
installer: Package name is TunTap Installer package
installer: Installing at base path /
installer:PHASE:Installation vorbereiten …
installer:PHASE:Volume vorbereiten …
installer:PHASE:„TunTap Installer package“ vorbereiten …
installer:PHASE:Warten, bis andere Installationen abgeschlossen werden …
installer:PHASE:Installation konfigurieren …
installer:STATUS:
installer:%56.682263
installer:PHASE:Paketskripte ausführen …
installer:%57.993850
installer:PHASE:Paketskripte ausführen …
installer:PHASE:Pakete überprüfen …
installer:%97.750000
installer: The install failed (Die Installation ist aufgrund eines Fehlers fehlgeschlagen. Wende dich an den Hersteller der Software.)
==> Purging files for version 20150118 of Cask tuntap
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=jmfayard USER=jmfayard USERNAME=jmfayard /usr/sbin/installer -pkg /usr/local/Caskroom/tuntap/20150118/tuntap_20150118.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is TunTap Installer package
installer: Installing at base path /
installer:PHASE:Installation vorbereiten …
installer:PHASE:Volume vorbereiten …
installer:PHASE:„TunTap Installer package“ vorbereiten …
installer:PHASE:Warten, bis andere Installationen abgeschlossen werden …
installer:PHASE:Installation konfigurieren …
installer:STATUS:
installer:%56.682263
installer:PHASE:Paketskripte ausführen …
installer:%57.993850
installer:PHASE:Paketskripte ausführen …
installer:PHASE:Pakete überprüfen …
installer:%97.750000
installer: The install failed (Die Installation ist aufgrund eines Fehlers fehlgeschlagen. Wende dich an den Hersteller der Software.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:111:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:52:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:214:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:205:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.1.11-36-g7dd0466
==> macOS
10.14.5
==> SIP
Enabled
==> Java
1.8.0_211
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3525 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-cobertura-1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.35.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-performance-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.74.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.29.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.17.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2019.0331/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.15.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
homebrew/services
```

**Comment by jmfayard** [comment]
Note that downloading the pkg manually and installing also fails

![image](https://user-images.githubusercontent.com/459464/64426220-4e6a7f80-d0ae-11e9-8039-9aed8c246cf0.png)

**Comment by reitermarkus** [comment]
> Note that downloading the pkg manually and installing also fails

Then this isn't an issue with the cask. As the error message says: Contact the software manufacturer for assistance.
