### ISSUE TITLE
Can't install last JDK

### ISSUE THREAD

**Issue by Agrassx** [Homebrew/homebrew-cask#68927]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

`brew cask install java` don't work
requested permission's

#### Command that failed

```
brew cask install java
```

#### Output of command with `--force --verbose --debug`

```
brew cask install java --force --verbose --debug 
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.java.net/java/GA/jdk12.0.2/e482c34c86bd4bf8b56c0b35558996b9/10/GPL/openjdk-12.0.2_osx-x64_bin.tar.gz
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.11-53-g26e64bd\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --location --silent --head --request GET https://download.java.net/java/GA/jdk12.0.2/e482c34c86bd4bf8b56c0b35558996b9/10/GPL/openjdk-12.0.2_osx-x64_bin.tar.gz
Already downloaded: /Users/agrass/Library/Caches/Homebrew/downloads/0c063c1db55c4b1323810e59dca242bbd1bedc828894003511e13362cc81291b--openjdk-12.0.2_osx-x64_bin.tar.gz
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/agrass/Library/Caches/Homebrew/downloads/0c063c1db55c4b1323810e59dca242bbd1bedc828894003511e13362cc81291b--openjdk-12.0.2_osx-x64_bin.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/agrass/Library/Caches/Homebrew/downloads/0c063c1db55c4b1323810e59dca242bbd1bedc828894003511e13362cc81291b--openjdk-12.0.2_osx-x64_bin.tar.gz
==> /Users/agrass/Library/Caches/Homebrew/downloads/0c063c1db55c4b1323810e59dca242bbd1bedc828894003511e13362cc81291b--openjdk-12.0.2_osx-x64_bin.tar.gz is quarantined
==> Downloaded to -> /Users/agrass/Library/Caches/Homebrew/downloads/0c063c1db55c4b1323810e59dca242bbd1bedc828894003511e13362cc81291b--openjdk-12.0.2_osx-x64_bin.tar.gz
==> Verifying SHA-256 checksum for Cask 'java'.
==> Installing Cask java
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Tar for /Users/agrass/Library/Caches/Homebrew/downloads/0c063c1db55c4b1323810e59dca242bbd1bedc828894003511e13362cc81291b--openjdk-12.0.2_osx-x64_bin.tar.gz
tar xof /Users/agrass/Library/Caches/Homebrew/downloads/0c063c1db55c4b1323810e59dca242bbd1bedc828894003511e13362cc81291b--openjdk-12.0.2_osx-x64_bin.tar.gz -C /var/folders/b4/0n7185qn2bqc0n1qx7pb80qr0000gn/T/d20190911-91602-pfv8m
==> Purging files for version 12.0.2,10:e482c34c86bd4bf8b56c0b35558996b9 of Cask java
Error: Permission denied @ dir_s_mkdir - /usr/local/Caskroom/java
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:254:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:254:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:226:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:226:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:211:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:576:in `mkpath'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:122:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:143:in `block in extract_nestedly'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:127:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:189:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:77:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
 brew doctor 
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Xcode alone is not sufficient on Mojave.
Install the Command Line Tools:
  xcode-select --install
```

#### Output of `brew tap`

```
brew tap
adoptopenjdk/openjdk
caskroom/versions
homebrew/cask
homebrew/core
```

**Comment by romainstuder** [comment]
Hi! It works on my laptop (Mojave). It seems Ruby is the problem. Have you installed the xcode tools as suggested?
`xcode-select --install`

You may need to use an other option if it doesn't work, by running this command:
`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave

**Comment by GxvgiuU** [comment]
I run into the same problem (Error: Permission denied @ dir_s_mkdir) and `brew cask doctor` (rather than `brew doctor` listed above) gave hints like
```
Cask's Doctor Checkup: failed
 - The staging path /usr/local/Caskroom is not writable by the current user.
 - To fix, run 'sudo chown -R $(whoami):staff /usr/local/Caskroom'
```

**Comment by romainstuder** [comment]
I didn't know there is separate doctor for cask. Could you then try the suggested command: `'sudo chown -R $(whoami):staff /usr/local/Caskroom'` ? And retry `brew doctor`, and if it is ok, then `brew cask install java`?
