### ISSUE TITLE
Installation of SquirelSQL fails

### ISSUE THREAD

**Issue by kaspermalfroid** [Homebrew/homebrew-cask#69419]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I am unable to install squirrelsql

#### Command that failed

```
brew cask install squirrelsql
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Caveats
squirrelsql requires Java 8+. You can install the latest version with:
  brew cask install adoptopenjdk

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.sourceforge.net/squirrel-sql/1-stable/3.8.1/squirrel-sql-3.8.1-MACOSX-install.jar
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.11-100-g6a7288e\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --location --silent --head --request GET https://downloads.sourceforge.net/squirrel-sql/1-stable/3.8.1/squirrel-sql-3.8.1-MACOSX-install.jar
Already downloaded: /Users/malfroid/Library/Caches/Homebrew/downloads/82a886f54ec0068e042ce90f4973dd98f553547de9bb003f1aa9db002f0669e0--squirrel-sql-3.8.1-MACOSX-install.jar
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/malfroid/Library/Caches/Homebrew/downloads/82a886f54ec0068e042ce90f4973dd98f553547de9bb003f1aa9db002f0669e0--squirrel-sql-3.8.1-MACOSX-install.jar
/usr/bin/xattr -p com.apple.quarantine /Users/malfroid/Library/Caches/Homebrew/downloads/82a886f54ec0068e042ce90f4973dd98f553547de9bb003f1aa9db002f0669e0--squirrel-sql-3.8.1-MACOSX-install.jar
==> /Users/malfroid/Library/Caches/Homebrew/downloads/82a886f54ec0068e042ce90f4973dd98f553547de9bb003f1aa9db002f0669e0--squirrel-sql-3.8.1-MACOSX-install.jar is quarantined
==> Downloaded to -> /Users/malfroid/Library/Caches/Homebrew/downloads/82a886f54ec0068e042ce90f4973dd98f553547de9bb003f1aa9db002f0669e0--squirrel-sql-3.8.1-MACOSX-install.jar
==> Verifying SHA-256 checksum for Cask 'squirrelsql'.
==> Installing Cask squirrelsql
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Uncompressed for /Users/malfroid/Library/Caches/Homebrew/downloads/82a886f54ec0068e042ce90f4973dd98f553547de9bb003f1aa9db002f0669e0--squirrel-sql-3.8.1-MACOSX-install.jar
cp -p /Users/malfroid/Library/Caches/Homebrew/downloads/82a886f54ec0068e042ce90f4973dd98f553547de9bb003f1aa9db002f0669e0--squirrel-sql-3.8.1-MACOSX-install.jar /usr/local/Caskroom/squirrelsql/3.8.1/squirrel-sql-3.8.1-MACOSX-install.jar
==> Verifying Gatekeeper status of /Users/malfroid/Library/Caches/Homebrew/downloads/82a886f54ec0068e042ce90f4973dd98f553547de9bb003f1aa9db002f0669e0--squirrel-sql-3.8.1-MACOSX-install.jar
/usr/bin/xattr -p com.apple.quarantine /Users/malfroid/Library/Caches/Homebrew/downloads/82a886f54ec0068e042ce90f4973dd98f553547de9bb003f1aa9db002f0669e0--squirrel-sql-3.8.1-MACOSX-install.jar
==> /Users/malfroid/Library/Caches/Homebrew/downloads/82a886f54ec0068e042ce90f4973dd98f553547de9bb003f1aa9db002f0669e0--squirrel-sql-3.8.1-MACOSX-install.jar is quarantined
==> Propagating quarantine from /Users/malfroid/Library/Caches/Homebrew/downloads/82a886f54ec0068e042ce90f4973dd98f553547de9bb003f1aa9db002f0669e0--squirrel-sql-3.8.1-MACOSX-install.jar to /usr/local/Caskroom/squirrelsql/3.8.1
/usr/bin/xattr -p com.apple.quarantine /Users/malfroid/Library/Caches/Homebrew/downloads/82a886f54ec0068e042ce90f4973dd98f553547de9bb003f1aa9db002f0669e0--squirrel-sql-3.8.1-MACOSX-install.jar
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5d8485c1\;Homebrew\\x20Cask\;C1D041D4-269D-4D3C-9513-4740E14D4B81
==> Creating metadata directory /usr/local/Caskroom/squirrelsql/.metadata/3.8.1/20190920092905.671.
==> Creating metadata subdirectory /usr/local/Caskroom/squirrelsql/.metadata/3.8.1/20190920092905.671/Casks.
==> Installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x00007fbfbf23a3a8>
==> Installing artifact of class Cask::Artifact::PreflightBlock
==> Installing artifact of class Cask::Artifact::PostflightBlock
/usr/bin/java -jar /usr/local/Caskroom/squirrelsql/3.8.1/squirrel-sql-3.8.1-MACOSX-install.jar /usr/local/Caskroom/squirrelsql/3.8.1/install-options.xml
[ ERROR: Could not create directory
/Applications/SQuirreLSQL.app/Contents/MacOS ]
com.izforge.izpack.installer.InstallerException: Unpack failed (xml line 48)
com.izforge.izpack.installer.InstallerException: Unpack failed (xml line 48)
	at com.izforge.izpack.panels.InstallPanelAutomationHelper.runAutomated(Unknown Source)
	at com.izforge.izpack.installer.AutomatedInstaller.installPanel(Unknown Source)
	at com.izforge.izpack.installer.AutomatedInstaller.doInstall(Unknown Source)
	at com.izforge.izpack.installer.Installer.main(Unknown Source)
==> Reverting installation of artifact of class Cask::Artifact::PreflightBlock
==> Purging files for version 3.8.1 of Cask squirrelsql
Error: Failure while executing; `/usr/bin/java -jar /usr/local/Caskroom/squirrelsql/3.8.1/squirrel-sql-3.8.1-MACOSX-install.jar /usr/local/Caskroom/squirrelsql/3.8.1/install-options.xml` exited with 1. Here's the output:
[ Starting automated installation ]
Read pack list from xml definition.
Try to add to selection [Name: Base and Index: 0]
Try to add to selection [Name: Standard and Index: 1]
Try to add to selection [Name: Optional Plugin - Greenplum and Index: 2]
Try to add to selection [Name: Optional Plugin - WIKI table configurations and Index: 3]
Try to add to selection [Name: Optional Plugin - Swing Violation Dedector and Index: 4]
Try to add to selection [Name: Optional Plugin - Multi Source and Index: 5]
Try to add to selection [Name: Optional Plugin - Vertica and Index: 6]
Try to add to selection [Name: Optional Plugin - Data import and Index: 7]
Try to add to selection [Name: Optional Plugin - DB2 and Index: 8]
Try to add to selection [Name: Optional Plugin - Derby and Index: 9]
Try to add to selection [Name: Optional Plugin - Firebird  and Index: 10]
Try to add to selection [Name: Optional Plugin - Hibernate and Index: 11]
Try to add to selection [Name: Optional Plugin - H2  and Index: 12]
Try to add to selection [Name: Optional Plugin - Informix  and Index: 13]
Try to add to selection [Name: Optional Plugin - Microsoft SQL Server  and Index: 14]
Try to add to selection [Name: Optional Plugin - MySQL  and Index: 15]
Try to add to selection [Name: Optional Plugin - Netezza  and Index: 16]
Try to add to selection [Name: Optional Plugin - Oracle and Index: 17]
Try to add to selection [Name: Optional Plugin - PostgreSQL  and Index: 18]
Try to add to selection [Name: Optional Plugin - Session Scripts and Index: 19]
Try to add to selection [Name: Optional Plugin - Smart Tools  and Index: 20]
Try to add to selection [Name: Optional Plugin - SQL Parametrisation  and Index: 21]
Try to add to selection [Name: Optional Plugin - SQL Replace  and Index: 22]
Try to add to selection [Name: Optional Plugin - SQL Validator  and Index: 23]
Try to add to selection [Name: Optional Plugin - Sybase  and Index: 24]
Try to add to selection [Name: Optional Plugin - Internationalization  and Index: 25]
Try to add to selection [Name: Optional Translation - Brazilian Portuguese and Index: 26]
Try to add to selection [Name: Optional Translation - Bulgarian and Index: 27]
Try to add to selection [Name: Optional Translation - Czech and Index: 28]
Try to add to selection [Name: Optional Translation - Simplified Chinese and Index: 29]
Try to add to selection [Name: Optional Translation - French and Index: 30]
Try to add to selection [Name: Optional Translation - German and Index: 31]
Try to add to selection [Name: Optional Translation - Italian and Index: 32]
Try to add to selection [Name: Optional Translation - Japanese and Index: 33]
Try to add to selection [Name: Optional Translation - Korean and Index: 34]
Try to add to selection [Name: Optional Translation - Polish and Index: 35]
Try to add to selection [Name: Optional Translation - Russian and Index: 36]
Try to add to selection [Name: Optional Translation - Spanish and Index: 37]
Modify pack selection.
Pack [Name: Optional Plugin - Greenplum and Index: 2] added to selection.
Pack [Name: Optional Plugin - WIKI table configurations and Index: 3] added to selection.
Pack [Name: Optional Plugin - Swing Violation Dedector and Index: 4] added to selection.
Pack [Name: Optional Plugin - Multi Source and Index: 5] added to selection.
Pack [Name: Optional Plugin - Vertica and Index: 6] added to selection.
Pack [Name: Optional Plugin - Data import and Index: 7] added to selection.
Pack [Name: Optional Plugin - DB2 and Index: 8] added to selection.
Pack [Name: Optional Plugin - Derby and Index: 9] added to selection.
Pack [Name: Optional Plugin - Firebird  and Index: 10] added to selection.
Pack [Name: Optional Plugin - Hibernate and Index: 11] added to selection.
Pack [Name: Optional Plugin - H2  and Index: 12] added to selection.
Pack [Name: Optional Plugin - Informix  and Index: 13] added to selection.
Pack [Name: Optional Plugin - Microsoft SQL Server  and Index: 14] added to selection.
Pack [Name: Optional Plugin - MySQL  and Index: 15] added to selection.
Pack [Name: Optional Plugin - Netezza  and Index: 16] added to selection.
Pack [Name: Optional Plugin - Oracle and Index: 17] added to selection.
Pack [Name: Optional Plugin - PostgreSQL  and Index: 18] added to selection.
Pack [Name: Optional Plugin - Session Scripts and Index: 19] added to selection.
Pack [Name: Optional Plugin - Smart Tools  and Index: 20] added to selection.
Pack [Name: Optional Plugin - SQL Parametrisation  and Index: 21] added to selection.
Pack [Name: Optional Plugin - SQL Replace  and Index: 22] added to selection.
Pack [Name: Optional Plugin - SQL Validator  and Index: 23] added to selection.
Pack [Name: Optional Plugin - Sybase  and Index: 24] added to selection.
Pack [Name: Optional Plugin - Internationalization  and Index: 25] added to selection.
Pack [Name: Optional Translation - Brazilian Portuguese and Index: 26] added to selection.
Pack [Name: Optional Translation - Bulgarian and Index: 27] added to selection.
Pack [Name: Optional Translation - Czech and Index: 28] added to selection.
Pack [Name: Optional Translation - Simplified Chinese and Index: 29] added to selection.
Pack [Name: Optional Translation - French and Index: 30] added to selection.
Pack [Name: Optional Translation - German and Index: 31] added to selection.
Pack [Name: Optional Translation - Italian and Index: 32] added to selection.
Pack [Name: Optional Translation - Japanese and Index: 33] added to selection.
Pack [Name: Optional Translation - Korean and Index: 34] added to selection.
Pack [Name: Optional Translation - Polish and Index: 35] added to selection.
Pack [Name: Optional Translation - Russian and Index: 36] added to selection.
Pack [Name: Optional Translation - Spanish and Index: 37] added to selection.
[ Starting to unpack ]
[ Processing package: Base (1/38) ]
[ ERROR: Could not create directory
[ Unpacking finished ]
/Applications/SQuirreLSQL.app/Contents/MacOS ]
com.izforge.izpack.installer.InstallerException: Unpack failed (xml line 48)
com.izforge.izpack.installer.InstallerException: Unpack failed (xml line 48)
	at com.izforge.izpack.panels.InstallPanelAutomationHelper.runAutomated(Unknown Source)
	at com.izforge.izpack.installer.AutomatedInstaller.installPanel(Unknown Source)
[ Automated installation FAILED! ]
	at com.izforge.izpack.installer.AutomatedInstaller.doInstall(Unknown Source)
	at com.izforge.izpack.installer.Installer.main(Unknown Source)

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:111:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:52:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/dsl/base.rb:16:in `system_command'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/squirrelsql.rb:74:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:41:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:41:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:24:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:214:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:205:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.1.11-100-g6a7288e
==> macOS
10.14.6
==> SIP
Enabled
==> Java
12.0.2, 12.0.1, 12, 11.0.2, 11.0.1, 1.8.0_202
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3539 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (140 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (162 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-cobertura-1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.35.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-performance-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.74.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.29.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.17.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2019.0331/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.15.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/fish"
```

#### Output of `brew tap`

```
buo/cask-upgrade
caskroom/versions
domt4/autoupdate
homebrew/cask
homebrew/cask-drivers
homebrew/core
```

**Comment by vitorgalvao** [comment]
Unpopular cask, not many reports of this issue. Going to close, but we’ll take a PR to fix the problem.

```
squirrelsql (added 1315 days ago)
30 days: 46 (#1082)
90 days: 163 (#988)
365 days: 788 (#818)
```
