### ISSUE TITLE
Cask 'sequel-pro' definition is invalid: invalid 'depends_on macos' value: ">= :leopard"

### ISSUE THREAD

**Issue by vfilimonov** [Homebrew/homebrew-cask#70197]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

When trying to uninstall Cask `sequel-pro` an error is raised:
```
$ brew cask uninstall sequel-pro
Error: Cask 'sequel-pro' definition is invalid: invalid 'depends_on macos' value: ">= :leopard"
```

#### Command that failed

```
brew cask uninstall sequel-pro
```

#### Output of command with `--force --verbose --debug`

```
==> Uninstalling Cask sequel-pro
Error: Cask 'sequel-pro' definition is invalid: invalid 'depends_on macos' value: ">= :leopard"
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:213:in `rescue in depends_on'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:210:in `depends_on'
/usr/local/Caskroom/sequel-pro/.metadata/1.1.2/20180403203541.551/Casks/sequel-pro.rb:12:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:50:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:50:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:41:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:35:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:35:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:75:in `cask'
/usr/local/Caskroom/sequel-pro/.metadata/1.1.2/20180403203541.551/Casks/sequel-pro.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:62:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:62:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:178:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
homebrew/services
mpv-player/mpv
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/58046

**Comment by vitorgalvao** [comment]
> `mpv-player/mpv``

You should `untap` that. It’s been deprecated for years.

**Comment by vfilimonov** [comment]
Thanks a lot, @vitorgalvao!

I thought it's `sequel-pro`-specific issue, perhaps that's why my search did not find this solution.
