### ISSUE TITLE
x-lite install error No such file or directory @ realpath_rec

### ISSUE THREAD

**Issue by tiiiecherle** [Homebrew/homebrew-cask#70353]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

x-lite installation/update fails with error "No such file or directory @ realpath_rec"
The same error occurs on 10.14.6 and 10.15.0.
a similar output error (I don't know if for the same reason) happens when installing disk-inventory-x

#### Command that failed

```
brew cask install --force x-lite
```
and
```
brew cask install --force disk-inventory-x
```

#### Output of command with `--force --verbose --debug`

```
brew cask install --force x-lite --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://counterpath.s3.amazonaws.com/downloads/X-Lite_5.7.0_100772.dmg
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.13\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15\)\ curl/7.64.1 --location --silent --head --request GET https://counterpath.s3.amazonaws.com/downloads/X-Lite_5.7.0_100772.dmg
Already downloaded: /Users/tom/Library/Caches/Homebrew/downloads/c2344d83b77e3db275a13d2225959101916dfb60934f6dc8a01cf273ce991b3f--X-Lite_5.7.0_100772.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/tom/Library/Caches/Homebrew/downloads/c2344d83b77e3db275a13d2225959101916dfb60934f6dc8a01cf273ce991b3f--X-Lite_5.7.0_100772.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/tom/Library/Caches/Homebrew/downloads/c2344d83b77e3db275a13d2225959101916dfb60934f6dc8a01cf273ce991b3f--X-Lite_5.7.0_100772.dmg
==> /Users/tom/Library/Caches/Homebrew/downloads/c2344d83b77e3db275a13d2225959101916dfb60934f6dc8a01cf273ce991b3f--X-Lite_5.7.0_100772.dmg is quarantined
==> Downloaded to -> /Users/tom/Library/Caches/Homebrew/downloads/c2344d83b77e3db275a13d2225959101916dfb60934f6dc8a01cf273ce991b3f--X-Lite_5.7.0_100772.dmg
==> Verifying SHA-256 checksum for Cask 'x-lite'.
==> Installing Cask x-lite
==> Cask::Installer#stage
hdiutil imageinfo /Users/tom/Library/Caches/Homebrew/downloads/c2344d83b77e3db275a13d2225959101916dfb60934f6dc8a01cf273ce991b3f--X-Lite_5.7.0_100772.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/tom/Library/Caches/Homebrew/downloads/c2344d83b77e3db275a13d2225959101916dfb60934f6dc8a01cf273ce991b3f--X-Lite_5.7.0_100772.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/cn/vz59zns57kbdrvrwwr1qrrwr0000gn/T/d20191009-28801-3691ew /Users/tom/Library/Caches/Homebrew/downloads/c2344d83b77e3db275a13d2225959101916dfb60934f6dc8a01cf273ce991b3f--X-Lite_5.7.0_100772.dmg
find . -print0
diskutil eject /private/var/folders/cn/vz59zns57kbdrvrwwr1qrrwr0000gn/T/d20191009-28801-3691ew/dmg.cRGyPa
==> Purging files for version 5.7.0_100772 of Cask x-lite
Error: No such file or directory @ realpath_rec - /private/var/folders/cn/vz59zns57kbdrvrwwr1qrrwr0000gn/T/d20191009-28801-3691ew/dmg.cRGyPa/X-Lite.app/Contents/Frameworks/CPCAPI2.framework/Versions/A/Modules
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:32:in `realpath'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:32:in `realpath'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:32:in `system_dir_symlink?'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:44:in `block in bom'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:44:in `reject'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:44:in `bom'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:86:in `block (2 levels) in extract_to_dir'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:85:in `block in extract_to_dir'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:82:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:123:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:123:in `block (2 levels) in extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:122:in `each'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:122:in `block in extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:186:in `block in mount'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:129:in `mount'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:119:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:123:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:130:in `block in extract_nestedly'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:127:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:189:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:77:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew Version
2.1.13
==> macOS
10.15
==> SIP
Unknown (custom configuration)

configuration:
apple internal: disabled
kext signing: enabled
filesystem protections: disabled
debugging restrictions: disabled
dtrace restrictions: enabled
nvram protections: enabled
basesystem verification: enabled
==> Java
13
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3471 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (163 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (934 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (132 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.36.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-performance-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.75.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-19/2.6.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.29.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.17.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-19/2.6.0/nokogiri-1.10.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2019.0904/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-19/2.6.0/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.15.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.12.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
brew tap
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
vitorgalvao/tiny-scripts
```

**Comment by drpaulatkinson** [comment]
I think I'm getting the same error trying to install dropbox in macOS 10.15

```
~ % brew cask install dropbox --force
==> Satisfying dependencies
==> Downloading https://www.dropbox.com/download?plat=mac&full=1
Already downloaded: /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox 82.4.155.dmg
==> No SHA-256 checksum defined for Cask 'dropbox', skipping verification.
==> Installing Cask dropbox
==> Purging files for version latest of Cask dropbox
Error: No such file or directory @ realpath_rec - /private/var/folders/yl/j0w4q5qn233gckf2tmf2rlqw0000gn/T/d20191009-15485-ac58rm/dmg.YwMPCZ/Dropbox.app/Contents/Frameworks/Tungsten.framework/Versions/A/Frameworks/Chromium Embedded Framework.framework/Versions/A/Libraries
```
