### ISSUE TITLE
"Operation not permitted" zapping google-chrome on Catalina

### ISSUE THREAD

**Issue by alexozwald** [Homebrew/homebrew-cask#70622]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Cannot zap google chrome (which had issues updating itself) after updating to macOS Catalina.

#### Command that failed

```
brew cask zap google-chrome
```

#### Output of command with `--force --verbose --debug`

```
==> Zapping Cask google-chrome
==> Implied "brew cask uninstall google-chrome"
==> Uninstalling artifacts
==> 3 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007f9cd3244c18 @cask=#<Cask::Cask:0x00007f9cd31d0840 @token="google-chrome", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/google-chrome.rb>, @tap=#<Tap:0x00007f9cd31cc3d0 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007f9cd31d0750@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/google-chrome.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/google-chrome>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/google-chrome/.metadata>, @config=#<Cask::Config:0x00007f9cd31dda68 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/alexozwald/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/alexozwald/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/alexozwald/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/alexozwald/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/alexozwald/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/alexozwald/Library/Services>, :input_methoddir=>#<Pathname:/Users/alexozwald/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/alexozwald/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/alexozwald/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/alexozwald/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/alexozwald/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/alexozwald/Library/Screen Savers>}, @env={}, @explicit={}>, @dsl=#<Cask::DSL:0x00007f9cd31d7e60 @cask=#<Cask::Cask:0x00007f9cd31d0840 ...>, @token="google-chrome", @version="77.0.3865.120", @sha256="7d243e427e3d16159a7cb083c9e5354b1d75526a23527060c13bb18a43369966", @url=#<URL:0x00007f9cd31d7898 @uri=#<URI::HTTPS https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007f9cd31d7410 @uri=#<URI::HTTPS https://omahaproxy.appspot.com/history?os=mac;channel=stable>, @parameters={}>, @name=["Google Chrome"], @homepage="https://www.google.com/chrome/", @auto_updates=true, @conflicts_with={:cask=>#<Set: {"google-chrome-beta", "google-chrome-dev"}>}, @depends_on={:macos=>#<MacOSRequirement: "macos" []>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/google-chrome/77.0.3865.120>, @language=nil>>, @directives={:launchctl=>["com.google.keystone.agent", "com.google.keystone.daemon"], :signal=>[]}>, #<Cask::Artifact::App:0x00007f9cd3246900 @cask=#<Cask::Cask:0x00007f9cd31d0840 @token="google-chrome", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/google-chrome.rb>, @tap=#<Tap:0x00007f9cd31cc3d0 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007f9cd31d0750@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/google-chrome.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/google-chrome>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/google-chrome/.metadata>, @config=#<Cask::Config:0x00007f9cd31dda68 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/alexozwald/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/alexozwald/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/alexozwald/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/alexozwald/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/alexozwald/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/alexozwald/Library/Services>, :input_methoddir=>#<Pathname:/Users/alexozwald/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/alexozwald/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/alexozwald/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/alexozwald/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/alexozwald/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/alexozwald/Library/Screen Savers>}, @env={}, @explicit={}>, @dsl=#<Cask::DSL:0x00007f9cd31d7e60 @cask=#<Cask::Cask:0x00007f9cd31d0840 ...>, @token="google-chrome", @version="77.0.3865.120", @sha256="7d243e427e3d16159a7cb083c9e5354b1d75526a23527060c13bb18a43369966", @url=#<URL:0x00007f9cd31d7898 @uri=#<URI::HTTPS https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007f9cd31d7410 @uri=#<URI::HTTPS https://omahaproxy.appspot.com/history?os=mac;channel=stable>, @parameters={}>, @name=["Google Chrome"], @homepage="https://www.google.com/chrome/", @auto_updates=true, @conflicts_with={:cask=>#<Set: {"google-chrome-beta", "google-chrome-dev"}>}, @depends_on={:macos=>#<MacOSRequirement: "macos" []>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/google-chrome/77.0.3865.120>, @language=nil>>, @source_string="Google Chrome.app", @target_string="", @source=#<Pathname:/usr/local/Caskroom/google-chrome/77.0.3865.120/Google Chrome.app>, @target=#<Pathname:/Applications/Google Chrome.app>>, #<Cask::Artifact::Zap:0x00007f9cd324d6d8 @cask=#<Cask::Cask:0x00007f9cd31d0840 @token="google-chrome", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/google-chrome.rb>, @tap=#<Tap:0x00007f9cd31cc3d0 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007f9cd31d0750@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/google-chrome.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/google-chrome>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/google-chrome/.metadata>, @config=#<Cask::Config:0x00007f9cd31dda68 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/alexozwald/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/alexozwald/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/alexozwald/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/alexozwald/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/alexozwald/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/alexozwald/Library/Services>, :input_methoddir=>#<Pathname:/Users/alexozwald/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/alexozwald/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/alexozwald/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/alexozwald/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/alexozwald/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/alexozwald/Library/Screen Savers>}, @env={}, @explicit={}>, @dsl=#<Cask::DSL:0x00007f9cd31d7e60 @cask=#<Cask::Cask:0x00007f9cd31d0840 ...>, @token="google-chrome", @version="77.0.3865.120", @sha256="7d243e427e3d16159a7cb083c9e5354b1d75526a23527060c13bb18a43369966", @url=#<URL:0x00007f9cd31d7898 @uri=#<URI::HTTPS https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007f9cd31d7410 @uri=#<URI::HTTPS https://omahaproxy.appspot.com/history?os=mac;channel=stable>, @parameters={}>, @name=["Google Chrome"], @homepage="https://www.google.com/chrome/", @auto_updates=true, @conflicts_with={:cask=>#<Set: {"google-chrome-beta", "google-chrome-dev"}>}, @depends_on={:macos=>#<MacOSRequirement: "macos" []>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/google-chrome/77.0.3865.120>, @language=nil>>, @directives={:trash=>["/Library/Caches/com.google.SoftwareUpdate.*", "/Library/Google/Google Chrome Brand.plist", "/Library/Google/GoogleSoftwareUpdate", "~/Library/Application Support/Google/Chrome", "~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.google.chrome.app.*.sfl*", "~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.google.chrome.sfl*", "~/Library/Caches/Google/Chrome", "~/Library/Caches/com.google.Chrome", "~/Library/Caches/com.google.Chrome.helper.*", "~/Library/Caches/com.google.Keystone", "~/Library/Caches/com.google.Keystone.Agent", "~/Library/Caches/com.google.SoftwareUpdate", "~/Library/Google/Google Chrome Brand.plist", "~/Library/Google/GoogleSoftwareUpdate", "~/Library/LaunchAgents/com.google.keystone.agent.plist", "~/Library/Logs/GoogleSoftwareUpdateAgent.log", "~/Library/Preferences/com.google.Chrome.plist", "~/Library/Preferences/com.google.Keystone.Agent.plist", "~/Library/Saved Application State/com.google.Chrome.app.*.savedState", "~/Library/Saved Application State/com.google.Chrome.savedState", "~/Library/WebKit/com.google.Chrome"], :rmdir=>["/Library/Google", "~/Library/Application Support/Google", "~/Library/Caches/Google", "~/Library/Google"], :signal=>[]}>}>
==> Uninstalling artifact of class Cask::Artifact::Uninstall
==> Removing launchctl service com.google.keystone.agent
/bin/launchctl list com.google.keystone.agent
/usr/bin/sudo -E -- /bin/launchctl list com.google.keystone.agent
Password:
==> Removing launchctl service com.google.keystone.daemon
/bin/launchctl list com.google.keystone.daemon
/usr/bin/sudo -E -- /bin/launchctl list com.google.keystone.daemon
==> Uninstalling artifact of class Cask::Artifact::App
==> Backing App 'Google Chrome.app' up to '/usr/local/Caskroom/google-chrome/77.0.3865.120/Google Chrome.app'.
/bin/cp -pR /Applications/Google\ Chrome.app /usr/local/Caskroom/google-chrome/77.0.3865.120/Google\ Chrome.app
==> Removing App '/Applications/Google Chrome.app'.
==> Post-uninstalling artifact of class Cask::Artifact::Uninstall
==> Dispatching zap stanza
Error: Operation not permitted - /Users/alexozwald/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:333:in `glob'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:333:in `glob'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:333:in `block in each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:318:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:318:in `each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:355:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:355:in `to_a'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:355:in `uninstall_trash'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:70:in `dispatch_uninstall_directive'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:61:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:60:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:60:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/zap.rb:9:in `zap_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:452:in `block in zap'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:451:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:451:in `zap'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.1.13-45-g70f232a
==> macOS
10.15
==> SIP
Enabled
==> Java
13
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3470 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (934 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.36.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.75.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.6.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.29.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.18.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/nokogiri-1.10.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.12.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/zsh"

```

#### Output of `brew tap`

```
getantibody/tap
homebrew/cask
homebrew/cask-fonts
homebrew/core
```

**Comment by amyspark** [comment]
This is a known issue with Catalina. It now default-denies all access to preference folders like this one.
Please go to System Preferences, tab "Privacy" and allow total disk access to Terminal.

**Comment by alexozwald** [comment]
This solved everything just great. Thank you :)

**Comment by jpeacock29** [comment]
For completeness: Open "System Preferences", click "Security & Privacy", navigate to the "Privacy" tab, select "Full Disk Access" from the menu on the left, click the lock in the lower left hand corner and enter your password when prompted, check "Terminal" to allow it full disk access, and quit Terminal when prompted.
