### ISSUE TITLE
adoptopenjdk-13 failing to install with permission errors

### ISSUE THREAD

**Issue by edgeyaph** [Homebrew/homebrew-cask#70660]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Installing the adoptopenjdk cask fails with a permission error of 'Error: Permission denied @ realpath_rec - /Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk'.

#### Command that failed

```
brew cask install adoptopenjdk
```

#### Output of command with `--force --verbose --debug`

```
taiga:~ ryu$ brew cask install --force --verbose --debug adoptopenjdk
==> Cask::Installer#install
==> Printing caveats
==> Caveats
More versions are available in the AdoptOpenJDK tap:
  https://github.com/AdoptOpenJDK/homebrew-openjdk

  brew tap adoptopenjdk/openjdk

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13%2B33/OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.13-45-g70f232a\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --location --silent --head --request GET https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13\%2B33/OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz
Already downloaded: /Users/ryu/Library/Caches/Homebrew/downloads/94102c3f27a628fcb22616a9fc1e34c9344941d9d939a32d3ca577b6cb713894--OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/ryu/Library/Caches/Homebrew/downloads/94102c3f27a628fcb22616a9fc1e34c9344941d9d939a32d3ca577b6cb713894--OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/ryu/Library/Caches/Homebrew/downloads/94102c3f27a628fcb22616a9fc1e34c9344941d9d939a32d3ca577b6cb713894--OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz
==> /Users/ryu/Library/Caches/Homebrew/downloads/94102c3f27a628fcb22616a9fc1e34c9344941d9d939a32d3ca577b6cb713894--OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz is quarantined
==> Downloaded to -> /Users/ryu/Library/Caches/Homebrew/downloads/94102c3f27a628fcb22616a9fc1e34c9344941d9d939a32d3ca577b6cb713894--OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz
==> Verifying SHA-256 checksum for Cask 'adoptopenjdk'.
==> Installing Cask adoptopenjdk
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Tar for /Users/ryu/Library/Caches/Homebrew/downloads/94102c3f27a628fcb22616a9fc1e34c9344941d9d939a32d3ca577b6cb713894--OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz
tar xof /Users/ryu/Library/Caches/Homebrew/downloads/94102c3f27a628fcb22616a9fc1e34c9344941d9d939a32d3ca577b6cb713894--OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz -C /var/folders/2n/h0cm56zj2bn1km68f3kwks4h0000gn/T/d20191011-83444-p4yiva
cp -pR /var/folders/2n/h0cm56zj2bn1km68f3kwks4h0000gn/T/d20191011-83444-p4yiva/jdk-13\+33/. /usr/local/Caskroom/adoptopenjdk/13,33/jdk-13\+33
chmod -Rf +w /var/folders/2n/h0cm56zj2bn1km68f3kwks4h0000gn/T/d20191011-83444-p4yiva
==> Verifying Gatekeeper status of /Users/ryu/Library/Caches/Homebrew/downloads/94102c3f27a628fcb22616a9fc1e34c9344941d9d939a32d3ca577b6cb713894--OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/ryu/Library/Caches/Homebrew/downloads/94102c3f27a628fcb22616a9fc1e34c9344941d9d939a32d3ca577b6cb713894--OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz
==> /Users/ryu/Library/Caches/Homebrew/downloads/94102c3f27a628fcb22616a9fc1e34c9344941d9d939a32d3ca577b6cb713894--OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz is quarantined
==> Propagating quarantine from /Users/ryu/Library/Caches/Homebrew/downloads/94102c3f27a628fcb22616a9fc1e34c9344941d9d939a32d3ca577b6cb713894--OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz to /usr/local/Caskroom/adoptopenjdk/13,33
/usr/bin/xattr -p com.apple.quarantine /Users/ryu/Library/Caches/Homebrew/downloads/94102c3f27a628fcb22616a9fc1e34c9344941d9d939a32d3ca577b6cb713894--OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5da140f1\;Homebrew\\x20Cask\;1E80A35F-A6F0-47D5-8412-C20D42D616E8
==> Creating metadata directory /usr/local/Caskroom/adoptopenjdk/.metadata/13,33/20191012044717.109.
==> Creating metadata subdirectory /usr/local/Caskroom/adoptopenjdk/.metadata/13,33/20191012044717.109/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007f9aea29d6c8 @cask=#<Cask::Cask:0x00007f9aea3a6420 @token="adoptopenjdk", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/adoptopenjdk.rb>, @tap=#<Tap:0x00007f9aea3958a0 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007f9aea3a6380@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/adoptopenjdk.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/adoptopenjdk>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/adoptopenjdk/.metadata>, @config=#<Cask::Config:0x00007f9aea296698 @explicit={}>, @dsl=#<Cask::DSL:0x00007f9aea296468 @cask=#<Cask::Cask:0x00007f9aea3a6420 ...>, @token="adoptopenjdk", @version="13,33", @sha256="f948be96daba250b6695e22cb51372d2ba3060e4d778dd09c89548889783099f", @url=#<URL:0x00007f9aea294848 @uri=#<URI::HTTPS https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13%2B33/OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007f9aea294028 @uri=#<URI::HTTPS https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/latest>, @parameters={}>, @name=["AdoptOpenJDK Java Development Kit"], @homepage="https://adoptopenjdk.net/", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/adoptopenjdk/13,33>, @caveats=#<Cask::DSL::Caveats:0x00007f9aea29d0b0 @cask=#<Cask::Cask:0x00007f9aea3a6420 ...>, @command=SystemCommand, @built_in_caveats={}, @custom_caveats=["More versions are available in the AdoptOpenJDK tap:\n  \e[4mhttps://github.com/AdoptOpenJDK/homebrew-openjdk\e[24m\n\n  brew tap adoptopenjdk/openjdk\n"]>, @language=nil>>, @directives={:rmdir=>"/Library/Java/JavaVirtualMachines", :signal=>[]}>, #<Cask::Artifact::Artifact:0x00007f9aea29eca8 @cask=#<Cask::Cask:0x00007f9aea3a6420 @token="adoptopenjdk", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/adoptopenjdk.rb>, @tap=#<Tap:0x00007f9aea3958a0 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007f9aea3a6380@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/adoptopenjdk.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/adoptopenjdk>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/adoptopenjdk/.metadata>, @config=#<Cask::Config:0x00007f9aea296698 @explicit={}>, @dsl=#<Cask::DSL:0x00007f9aea296468 @cask=#<Cask::Cask:0x00007f9aea3a6420 ...>, @token="adoptopenjdk", @version="13,33", @sha256="f948be96daba250b6695e22cb51372d2ba3060e4d778dd09c89548889783099f", @url=#<URL:0x00007f9aea294848 @uri=#<URI::HTTPS https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13%2B33/OpenJDK13U-jdk_x64_mac_hotspot_13_33.tar.gz>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007f9aea294028 @uri=#<URI::HTTPS https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/latest>, @parameters={}>, @name=["AdoptOpenJDK Java Development Kit"], @homepage="https://adoptopenjdk.net/", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/adoptopenjdk/13,33>, @caveats=#<Cask::DSL::Caveats:0x00007f9aea29d0b0 @cask=#<Cask::Cask:0x00007f9aea3a6420 ...>, @command=SystemCommand, @built_in_caveats={}, @custom_caveats=["More versions are available in the AdoptOpenJDK tap:\n  \e[4mhttps://github.com/AdoptOpenJDK/homebrew-openjdk\e[24m\n\n  brew tap adoptopenjdk/openjdk\n"]>, @language=nil>>, @source_string="jdk-13+33", @target_string="/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk", @source=#<Pathname:/usr/local/Caskroom/adoptopenjdk/13,33/jdk-13+33>, @target=#<Pathname:/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk>>}>
==> Installing artifact of class Cask::Artifact::Artifact
==> Moving Generic Artifact 'jdk-13+33' to '/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk'.
/usr/bin/sudo -E -- /bin/mkdir -p /Library/Java/JavaVirtualMachines
/usr/bin/sudo -E -- /bin/mv /usr/local/Caskroom/adoptopenjdk/13,33/jdk-13\+33 /Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
/usr/bin/xattr -p com.apple.metadata:kMDItemAlternateNames /Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk
==> Existing metadata is: ''
==> Purging files for version 13,33 of Cask adoptopenjdk
Error: Permission denied @ realpath_rec - /Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/artifact/relocated.rb:73:in `realpath'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/relocated.rb:73:in `realpath'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/relocated.rb:73:in `add_altname_metadata'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:57:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:13:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:214:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:205:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
taiga:~ ryu$ brew cask doctor
==> Homebrew Version
2.1.13-45-g70f232a
==> macOS
10.14.6
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3470 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.36.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.75.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.6.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.29.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.18.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/nokogiri-1.10.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.12.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
taiga:~ ryu$ brew tap
homebrew/cask
homebrew/core
```

**Comment by reitermarkus** [comment]
May also be the same issue as https://github.com/Homebrew/homebrew-cask/issues/70622#issuecomment-541324125.

Have you allowed Full Disk Access for Terminal?

**Comment by hhimanshu** [comment]
How did you fix this issue?

**Comment by hhimanshu** [comment]
https://github.com/Homebrew/homebrew-cask/issues/69422#issuecomment-552655311 has helped me fix it
