### ISSUE TITLE
brew cask zap firefox fails

### ISSUE THREAD

**Issue by marcfrederick** [Homebrew/homebrew-cask#70677]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The `firefox` zap stanza leads to a crash.

#### Command that failed

```
brew cask zap firefox
```

#### Output of command with `--force --verbose --debug`

```
==> Zapping Cask firefox
==> Implied "brew cask uninstall firefox"
==> Uninstalling artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::App:0x00007f8b131eb8b0 @cask=#<Cask::Cask:0x00007f8b12b1e410 @token="firefox", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb>, @tap=#<Tap:0x00007f8b12afd738 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007f8b12b1e320@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/firefox>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/firefox/.metadata>, @config=#<Cask::Config:0x00007f8b12b26d18 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/<username>/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/<username>/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/<username>/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/<username>/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/<username>/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/<username>/Library/Services>, :input_methoddir=>#<Pathname:/Users/<username>/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/<username>/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/<username>/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/<username>/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/<username>/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/<username>/Library/Screen Savers>}, @env={}, @explicit={}>, @dsl=#<Cask::DSL:0x00007f8b12b24810 @cask=#<Cask::Cask:0x00007f8b12b1e410 ...>, @token="firefox", @version="69.0.3", @language_blocks={["cs"]=>#<Proc:0x00007f8b12b24568@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:4>, ["de"]=>#<Proc:0x00007f8b12b244a0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:9>, ["en-GB"]=>#<Proc:0x00007f8b12b24428@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:14>, ["en"]=>#<Proc:0x00007f8b12b243b0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:19>, ["eo"]=>#<Proc:0x00007f8b12b24338@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:24>, ["es-AR"]=>#<Proc:0x00007f8b12b24298@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:29>, ["es-CL"]=>#<Proc:0x00007f8b12b24220@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:34>, ["es-ES"]=>#<Proc:0x00007f8b12b241a8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:39>, ["fi"]=>#<Proc:0x00007f8b12b24130@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:44>, ["fr"]=>#<Proc:0x00007f8b12b24090@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:49>, ["gl"]=>#<Proc:0x00007f8b12b24018@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:54>, ["in"]=>#<Proc:0x00007f8b12b2ff80@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:59>, ["it"]=>#<Proc:0x00007f8b12b2ff08@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:64>, ["ja"]=>#<Proc:0x00007f8b12b2fe68@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:69>, ["ko"]=>#<Proc:0x00007f8b12b2fdc8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:74>, ["nl"]=>#<Proc:0x00007f8b12b2fc10@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:79>, ["pl"]=>#<Proc:0x00007f8b12b2fb20@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:84>, ["pt-BR"]=>#<Proc:0x00007f8b12b2fa30@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:89>, ["pt"]=>#<Proc:0x00007f8b12b2f8f0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:94>, ["ru"]=>#<Proc:0x00007f8b12b2f850@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:99>, ["tr"]=>#<Proc:0x00007f8b12b2f710@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:104>, ["uk"]=>#<Proc:0x00007f8b12b2f620@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:109>, ["zh-TW"]=>#<Proc:0x00007f8b12b2f4b8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:114>, ["zh"]=>#<Proc:0x00007f8b12b2f350@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:119>}, @sha256="6711c99b1a5aa3460f0cf1566dbd5625a4c6f96ea37c07821d79ffa94c21f20c", @language="en-US", @url=#<URL:0x00007f8b12b5e510 @uri=#<URI::HTTPS https://download-installer.cdn.mozilla.net/pub/firefox/releases/69.0.3/mac/en-US/Firefox%2069.0.3.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007f8b12b5e150 @uri=#<URI::HTTPS https://www.macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://download.mozilla.org/%3Fproduct=firefox-latest-ssl%26os=osx>, @parameters={}>, @name=["Mozilla Firefox"], @homepage="https://www.mozilla.org/firefox/", @auto_updates=true, @conflicts_with={:cask=>#<Set: {"firefox-beta", "firefox-esr"}>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/firefox/69.0.3>>>, @source_string="Firefox.app", @target_string="", @source=#<Pathname:/usr/local/Caskroom/firefox/69.0.3/Firefox.app>, @target=#<Pathname:/Applications/Firefox.app>>, #<Cask::Artifact::Zap:0x00007f8b131e80c0 @cask=#<Cask::Cask:0x00007f8b12b1e410 @token="firefox", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb>, @tap=#<Tap:0x00007f8b12afd738 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007f8b12b1e320@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/firefox>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/firefox/.metadata>, @config=#<Cask::Config:0x00007f8b12b26d18 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/<username>/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/<username>/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/<username>/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/<username>/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/<username>/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/<username>/Library/Services>, :input_methoddir=>#<Pathname:/Users/<username>/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/<username>/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/<username>/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/<username>/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/<username>/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/<username>/Library/Screen Savers>}, @env={}, @explicit={}>, @dsl=#<Cask::DSL:0x00007f8b12b24810 @cask=#<Cask::Cask:0x00007f8b12b1e410 ...>, @token="firefox", @version="69.0.3", @language_blocks={["cs"]=>#<Proc:0x00007f8b12b24568@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:4>, ["de"]=>#<Proc:0x00007f8b12b244a0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:9>, ["en-GB"]=>#<Proc:0x00007f8b12b24428@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:14>, ["en"]=>#<Proc:0x00007f8b12b243b0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:19>, ["eo"]=>#<Proc:0x00007f8b12b24338@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:24>, ["es-AR"]=>#<Proc:0x00007f8b12b24298@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:29>, ["es-CL"]=>#<Proc:0x00007f8b12b24220@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:34>, ["es-ES"]=>#<Proc:0x00007f8b12b241a8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:39>, ["fi"]=>#<Proc:0x00007f8b12b24130@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:44>, ["fr"]=>#<Proc:0x00007f8b12b24090@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:49>, ["gl"]=>#<Proc:0x00007f8b12b24018@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:54>, ["in"]=>#<Proc:0x00007f8b12b2ff80@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:59>, ["it"]=>#<Proc:0x00007f8b12b2ff08@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:64>, ["ja"]=>#<Proc:0x00007f8b12b2fe68@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:69>, ["ko"]=>#<Proc:0x00007f8b12b2fdc8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:74>, ["nl"]=>#<Proc:0x00007f8b12b2fc10@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:79>, ["pl"]=>#<Proc:0x00007f8b12b2fb20@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:84>, ["pt-BR"]=>#<Proc:0x00007f8b12b2fa30@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:89>, ["pt"]=>#<Proc:0x00007f8b12b2f8f0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:94>, ["ru"]=>#<Proc:0x00007f8b12b2f850@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:99>, ["tr"]=>#<Proc:0x00007f8b12b2f710@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:104>, ["uk"]=>#<Proc:0x00007f8b12b2f620@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:109>, ["zh-TW"]=>#<Proc:0x00007f8b12b2f4b8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:114>, ["zh"]=>#<Proc:0x00007f8b12b2f350@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:119>}, @sha256="6711c99b1a5aa3460f0cf1566dbd5625a4c6f96ea37c07821d79ffa94c21f20c", @language="en-US", @url=#<URL:0x00007f8b12b5e510 @uri=#<URI::HTTPS https://download-installer.cdn.mozilla.net/pub/firefox/releases/69.0.3/mac/en-US/Firefox%2069.0.3.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007f8b12b5e150 @uri=#<URI::HTTPS https://www.macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://download.mozilla.org/%3Fproduct=firefox-latest-ssl%26os=osx>, @parameters={}>, @name=["Mozilla Firefox"], @homepage="https://www.mozilla.org/firefox/", @auto_updates=true, @conflicts_with={:cask=>#<Set: {"firefox-beta", "firefox-esr"}>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/firefox/69.0.3>>>, @directives={:trash=>["/Library/Logs/DiagnosticReports/firefox_*", "~/Library/Application Support/Firefox", "~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/org.mozilla.firefox.sfl*", "~/Library/Caches/Firefox", "~/Library/Caches/Mozilla/updates/Applications/Firefox", "~/Library/Preferences/org.mozilla.firefox.plist"], :rmdir=>["~/Library/Application Support/Mozilla", "~/Library/Caches/Mozilla/updates/Applications", "~/Library/Caches/Mozilla/updates", "~/Library/Caches/Mozilla"], :signal=>[]}>}>
==> Uninstalling artifact of class Cask::Artifact::App
==> Dispatching zap stanza
Error: Operation not permitted - /Users/<username>/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:333:in `glob'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:333:in `glob'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:333:in `block in each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:318:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:318:in `each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:355:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:355:in `to_a'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:355:in `uninstall_trash'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:70:in `dispatch_uninstall_directive'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:61:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:60:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:60:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/zap.rb:9:in `zap_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:452:in `block in zap'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:451:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:451:in `zap'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.1.13-49-g966e7ab
==> macOS
10.15
==> SIP
Enabled
==> Java
13
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3470 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.36.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.75.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.6.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.29.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.18.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/nokogiri-1.10.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.12.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
derailed/k9s
homebrew/cask
homebrew/core
homebrew/services
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/70622#issuecomment-541324125
