### ISSUE TITLE
Cannot install meld on Mojave 10.14.6 due to quarantine

### ISSUE THREAD

**Issue by HarrisonMc555** [Homebrew/homebrew-cask#70813]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Attempting to install meld fails due to quarantine.

#### Command that failed

```
brew cask install meld
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://github.com/yousseb/meld/releases/download/osx-15/meldmerge.dmg
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.14-23-g8fa65aa\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --location --silent --head --request GET https://github.com/yousseb/meld/releases/download/osx-15/meldmerge.dmg
Already downloaded: /Users/myusername/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/myusername/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/myusername/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg
==> /Users/myusername/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg is quarantined
==> Downloaded to -> /Users/myusername/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg
==> Verifying SHA-256 checksum for Cask 'meld'.
==> Installing Cask meld
==> Cask::Installer#stage
hdiutil imageinfo -format /Users/myusername/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/myusername/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/ww/p9764btd34d_13297hdw08mm0000gn/T/d20191014-55058-avzl2n /Users/myusername/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg
find . -print0
mkbom -s -i /var/folders/ww/p9764btd34d_13297hdw08mm0000gn/T/20191014-55058-zvhwli.list -- /var/folders/ww/p9764btd34d_13297hdw08mm0000gn/T/20191014-55058-aebe3d.bom
ditto --bom /var/folders/ww/p9764btd34d_13297hdw08mm0000gn/T/20191014-55058-aebe3d.bom -- /private/var/folders/ww/p9764btd34d_13297hdw08mm0000gn/T/d20191014-55058-avzl2n/dmg.I9BIej /var/folders/ww/p9764btd34d_13297hdw08mm0000gn/T/d20191014-55058-11ncleg
diskutil eject /private/var/folders/ww/p9764btd34d_13297hdw08mm0000gn/T/d20191014-55058-avzl2n/dmg.I9BIej
cp -pR /var/folders/ww/p9764btd34d_13297hdw08mm0000gn/T/d20191014-55058-11ncleg/Meld.app/. /usr/local/Caskroom/meld/3.19.2-r6,osx-15/Meld.app
chmod -Rf +w /var/folders/ww/p9764btd34d_13297hdw08mm0000gn/T/d20191014-55058-11ncleg
==> Verifying Gatekeeper status of /Users/myusername/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/myusername/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg
==> /Users/myusername/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg is quarantined
==> Propagating quarantine from /Users/myusername/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg to /usr/local/Caskroom/meld/3.19.2-r6,osx-15
/usr/bin/xattr -p com.apple.quarantine /Users/myusername/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5da4e6eb\;Homebrew\\x20Cask\;DF26482A-0A3D-4C6A-BF16-EF84258574BE
Error: Failed to quarantine one or more files within /usr/local/Caskroom/meld/3.19.2-r6,osx-15. Here's the reason:
xattr: [Errno 1] Operation not permitted: '/usr/local/Caskroom/meld/3.19.2-r6,osx-15/Meld.app/Contents/Frameworks/Foundation.framework'
xattr: [Errno 1] Operation not permitted: '/usr/local/Caskroom/meld/3.19.2-r6,osx-15/Meld.app/Contents/Frameworks/CoreFoundation.framework'
/usr/local/Homebrew/Library/Homebrew/cask/quarantine.rb:165:in `propagate'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:193:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:77:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
==> Purging files for version 3.19.2-r6,osx-15 of Cask meld
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.1.14-23-g8fa65aa
==> macOS
10.14.6
==> SIP
Enabled
==> Java
1.8.0_211
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3475 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (135 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (934 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3475 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.36.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.75.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.6.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.29.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.18.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/nokogiri-1.10.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.12.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
caskroom/cask
caskroom/drivers
caskroom/fonts
homebrew/cask
homebrew/core
homebrew/services
```

#### System Details

  - OS: macOS Mojave 10.14.6
  - Bash: 5.0.7(1)-release

#### Additional Details

  - The command appears to work with no issues with the `--no-quarantine` option.
  - Despite the similarity in command and date when reported, this appears to be wholly distinct from #70530.
  - This seems to support the discussion in #70798, although this appears in Mojave, not Catalina, like most of the discussion there seems to be revolving around.

**Comment by reitermarkus** [comment]
Not related to this error, but please run `brew untap caskroom/cask caskroom/drivers caskroom/fonts`.

**Comment by HarrisonMc555** [comment]
This fixed it, thanks @reitermarkus!

**Comment by omarzina** [comment]
To whoever ended here from google, 
My error was:
```
➜  ~ brew cask install meld --force
==> Satisfying dependencies
==> Downloading https://github.com/yousseb/meld/releases/download/osx-15/meldmerge.dmg
Already downloaded: /Users/omarzina/Library/Caches/Homebrew/downloads/514fda525358c0c98772aafabd75166852b75a26bf51da1fb5cd9d49071acfb8--meldmerge.dmg
==> Verifying SHA-256 checksum for Cask 'meld'.
==> Installing Cask meld
==> Purging files for version 3.19.2-r6,osx-15 of Cask meld
Error: Failed to quarantine one or more files within /usr/local/Caskroom/meld/3.19.2-r6,osx-15. Here's the reason:
xattr: No such file: /usr/local/Caskroom/meld/3.19.2-r6,osx-15/Meld.app/Contents/Resources/lib/python3.6/config
xattr: [Errno 1] Operation not permitted: '/usr/local/Caskroom/meld/3.19.2-r6,osx-15/Meld.app/Contents/Frameworks/Foundation.framework'
xattr: [Errno 1] Operation not permitted: '/usr/local/Caskroom/meld/3.19.2-r6,osx-15/Meld.app/Contents/Frameworks/CoreFoundation.framework'
```

And running `brew update-reset && brew update` solved it
