### ISSUE TITLE
brew cask doctor Error: undefined method `first' on Catalina

### ISSUE THREAD

**Issue by cpeterso** [Homebrew/homebrew-cask#71209]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

After updating to macOS 10.15 Catalina, `brew cask doctor` fails with the following Python error:

```
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/wheel-0.29.0.dist-info'
Error: undefined method `first' for #<String:0x00007fc6ea8aa5d0>
```

#### Command that failed

```
brew cask doctor
```

#### Output of command with `--force --verbose --debug`

```
% brew cask doctor --force --verbose --debug
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cask/cmd/options.rb:65:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:43:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/doctor.rb:12:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
% brew cask doctor --force --verbose --debug
==> Homebrew Version
2.1.15-9-ge985986
==> macOS
10.15
==> SIP
Enabled
==> Java
1.8.0_202, 1.8.0_162, 1.8.0_144, 1.8.0_92, 1.7.0_15
==> xattr issues
Traceback (most recent call last):
  File "/usr/bin/xattr", line 8, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 574, in _build_master
    ws = cls()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2056, in find_on_path
    for dist in factory(fullpath):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2118, in distributions_from_metadata
    if len(os.listdir(path)) == 0:
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/wheel-0.29.0.dist-info'
Error: undefined method `first' for #<String:0x00007fcb3612a828>
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/cmd/doctor.rb:144:in `check_xattr'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/doctor.rb:28:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew tap`

```
% brew tap
caskroom/versions
homebrew/cask
homebrew/core
```

**Comment by reitermarkus** [comment]
Not related to this issue, but run `brew untap caskroom/versions` and `brew tap homebrew/cask-versions`.
