### ISSUE TITLE
Multiple CI builds failing due to `magic_number'

### ISSUE THREAD

**Issue by docquantum** [Homebrew/homebrew-cask#71901]
brew cask ci for multiple cask updates fails due to `magic_number' after passing audits.

As an example from a recent pull request:

```
$ brew cask ci
==> brew cask style tales-of-majeyal ✔ ...
==> brew cask audit tales-of-majeyal ✔ ...

Error: undefined method `magic_number' for nil:NilClass
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/tar.rb:20:in `can_extract?'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:90:in `block in from_magic'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:90:in `each'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:90:in `find'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:90:in `from_magic'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:101:in `detect'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:170:in `primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:315:in `collect_cask_and_formula_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:329:in `missing_cask_and_formula_dependencies'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/cmd/brewcask-ci.rb:105:in `block in run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/cmd/brewcask-ci.rb:51:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/cmd/brewcask-ci.rb:51:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:112:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by reitermarkus** [comment]
Should be fixed again.
