### ISSUE TITLE
parallels: No such file or directory @ rb_file_s_rename

### ISSUE THREAD

**Issue by kbluck** [Homebrew/homebrew-cask#72172]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Upgrading Parallels cask fails with error:
`No such file or directory @ rb_file_s_rename`

#### Command that failed

```
brew cask upgrade parallels
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask upgrade parallels --force --verbose --debug
==> Upgrading 1 outdated package:
parallels 15.0.0-46967 -> 15.1.1-47117
==> Started upgrade process for Cask parallels
==> Upgrading parallels
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://download.parallels.com/desktop/v15/15.1.1-47117/ParallelsDesktop-15.1.1-47117.dmg
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.16-30-g4873c49\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --location --silent --head --request GET https://download.parallels.com/desktop/v15/15.1.1-47117/ParallelsDesktop-15.1.1-47117.dmg
Already downloaded: /Users/kbluck/Library/Caches/Homebrew/downloads/47fe3d194dea9da6721e8cae892ca128c130e31889c2a686f5d806bf9cb9f100--ParallelsDesktop-15.1.1-47117.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/kbluck/Library/Caches/Homebrew/downloads/47fe3d194dea9da6721e8cae892ca128c130e31889c2a686f5d806bf9cb9f100--ParallelsDesktop-15.1.1-47117.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/kbluck/Library/Caches/Homebrew/downloads/47fe3d194dea9da6721e8cae892ca128c130e31889c2a686f5d806bf9cb9f100--ParallelsDesktop-15.1.1-47117.dmg
==> /Users/kbluck/Library/Caches/Homebrew/downloads/47fe3d194dea9da6721e8cae892ca128c130e31889c2a686f5d806bf9cb9f100--ParallelsDesktop-15.1.1-47117.dmg is quarantined
==> Downloaded to -> /Users/kbluck/Library/Caches/Homebrew/downloads/47fe3d194dea9da6721e8cae892ca128c130e31889c2a686f5d806bf9cb9f100--ParallelsDesktop-15.1.1-47117.dmg
==> Verifying SHA-256 checksum for Cask 'parallels'.
==> Uninstalling artifacts
==> 4 artifact/s defined
#<SortedSet: {#<Cask::Artifact::PreflightBlock:0x00007fa1459090f0 @cask=#<Cask::Cask:0x00007fa1458d1df8 @token="parallels", @sourcefile_path=#<Pathname:/usr/local/Caskroom/parallels/.metadata/15.0.0-46967.upgrading/20190821153006.821/Casks/parallels.rb>, @tap=nil, @block=#<Proc:0x00007fa1458d1cb8@/usr/local/Caskroom/parallels/.metadata/15.0.0-46967.upgrading/20190821153006.821/Casks/parallels.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/parallels>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/parallels/.metadata>, @config=#<Cask::Config:0x00007fa1458fb6d0 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/kbluck/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/kbluck/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/kbluck/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/kbluck/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/kbluck/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/kbluck/Library/Services>, :input_methoddir=>#<Pathname:/Users/kbluck/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/kbluck/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/kbluck/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/kbluck/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/kbluck/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/kbluck/Library/Screen Savers>}, @env={}, @explicit={}>, @dsl=#<Cask::DSL:0x00007fa1458f84d0 @cask=#<Cask::Cask:0x00007fa1458d1df8 ...>, @token="parallels", @version="15.0.0-46967", @sha256="ed8b991bbbb70142ced8ba450273118e613fcd9b692d00ef75ef8db0b046aa6c", @url=#<URL:0x00007fa14590b788 @uri=#<URI::HTTPS https://download.parallels.com/desktop/v15/15.0.0-46967/ParallelsDesktop-15.0.0-46967.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fa14590b1e8 @uri=#<URI::HTTPS https://kb.parallels.com/eu/124724>, @parameters={}>, @name=["Parallels Desktop"], @homepage="https://www.parallels.com/products/desktop/", @auto_updates=true, @depends_on={:macos=>#<MacOSRequirement: "macos" []>}, @container=#<Cask::DSL::Container:0x00007fa1459097a8 @pairs={:type=>:naked}, @type=:naked>, @artifacts=#<SortedSet: {...}>, @language=nil>>, @directives={:preflight=>#<Proc:0x00007fa145909230@/usr/local/Caskroom/parallels/.metadata/15.0.0-46967.upgrading/20190821153006.821/Casks/parallels.rb:16>}>, #<Cask::Artifact::PreflightBlock:0x00007fa145908f88 @cask=#<Cask::Cask:0x00007fa1458d1df8 @token="parallels", @sourcefile_path=#<Pathname:/usr/local/Caskroom/parallels/.metadata/15.0.0-46967.upgrading/20190821153006.821/Casks/parallels.rb>, @tap=nil, @block=#<Proc:0x00007fa1458d1cb8@/usr/local/Caskroom/parallels/.metadata/15.0.0-46967.upgrading/20190821153006.821/Casks/parallels.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/parallels>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/parallels/.metadata>, @config=#<Cask::Config:0x00007fa1458fb6d0 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/kbluck/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/kbluck/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/kbluck/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/kbluck/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/kbluck/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/kbluck/Library/Services>, :input_methoddir=>#<Pathname:/Users/kbluck/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/kbluck/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/kbluck/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/kbluck/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/kbluck/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/kbluck/Library/Screen Savers>}, @env={}, @explicit={}>, @dsl=#<Cask::DSL:0x00007fa1458f84d0 @cask=#<Cask::Cask:0x00007fa1458d1df8 ...>, @token="parallels", @version="15.0.0-46967", @sha256="ed8b991bbbb70142ced8ba450273118e613fcd9b692d00ef75ef8db0b046aa6c", @url=#<URL:0x00007fa14590b788 @uri=#<URI::HTTPS https://download.parallels.com/desktop/v15/15.0.0-46967/ParallelsDesktop-15.0.0-46967.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fa14590b1e8 @uri=#<URI::HTTPS https://kb.parallels.com/eu/124724>, @parameters={}>, @name=["Parallels Desktop"], @homepage="https://www.parallels.com/products/desktop/", @auto_updates=true, @depends_on={:macos=>#<MacOSRequirement: "macos" []>}, @container=#<Cask::DSL::Container:0x00007fa1459097a8 @pairs={:type=>:naked}, @type=:naked>, @artifacts=#<SortedSet: {...}>, @language=nil>>, @directives={:uninstall_preflight=>#<Proc:0x00007fa145908fd8@/usr/local/Caskroom/parallels/.metadata/15.0.0-46967.upgrading/20190821153006.821/Casks/parallels.rb:26>}>, #<Cask::Artifact::Uninstall:0x00007fa1459085b0 @cask=#<Cask::Cask:0x00007fa1458d1df8 @token="parallels", @sourcefile_path=#<Pathname:/usr/local/Caskroom/parallels/.metadata/15.0.0-46967.upgrading/20190821153006.821/Casks/parallels.rb>, @tap=nil, @block=#<Proc:0x00007fa1458d1cb8@/usr/local/Caskroom/parallels/.metadata/15.0.0-46967.upgrading/20190821153006.821/Casks/parallels.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/parallels>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/parallels/.metadata>, @config=#<Cask::Config:0x00007fa1458fb6d0 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/kbluck/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/kbluck/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/kbluck/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/kbluck/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/kbluck/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/kbluck/Library/Services>, :input_methoddir=>#<Pathname:/Users/kbluck/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/kbluck/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/kbluck/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/kbluck/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/kbluck/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/kbluck/Library/Screen Savers>}, @env={}, @explicit={}>, @dsl=#<Cask::DSL:0x00007fa1458f84d0 @cask=#<Cask::Cask:0x00007fa1458d1df8 ...>, @token="parallels", @version="15.0.0-46967", @sha256="ed8b991bbbb70142ced8ba450273118e613fcd9b692d00ef75ef8db0b046aa6c", @url=#<URL:0x00007fa14590b788 @uri=#<URI::HTTPS https://download.parallels.com/desktop/v15/15.0.0-46967/ParallelsDesktop-15.0.0-46967.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fa14590b1e8 @uri=#<URI::HTTPS https://kb.parallels.com/eu/124724>, @parameters={}>, @name=["Parallels Desktop"], @homepage="https://www.parallels.com/products/desktop/", @auto_updates=true, @depends_on={:macos=>#<MacOSRequirement: "macos" []>}, @container=#<Cask::DSL::Container:0x00007fa1459097a8 @pairs={:type=>:naked}, @type=:naked>, @artifacts=#<SortedSet: {...}>, @language=nil>>, @directives={:delete=>["/usr/local/bin/prl_convert", "/usr/local/bin/prl_disk_tool", "/usr/local/bin/prl_perf_ctl", "/usr/local/bin/prlcore2dmp", "/usr/local/bin/prlctl", "/usr/local/bin/prlexec", "/usr/local/bin/prlsrvctl", "/Applications/Parallels Desktop.app", "/Applications/Parallels Desktop.app/Contents/Applications/Parallels Link.app", "/Applications/Parallels Desktop.app/Contents/Applications/Parallels Mounter.app", "/Applications/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app", "/Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app", "/Applications/Parallels Desktop.app/Contents/MacOS/Parallels VM.app"], :signal=>[]}>, #<Cask::Artifact::Zap:0x00007fa14591bac0 @cask=#<Cask::Cask:0x00007fa1458d1df8 @token="parallels", @sourcefile_path=#<Pathname:/usr/local/Caskroom/parallels/.metadata/15.0.0-46967.upgrading/20190821153006.821/Casks/parallels.rb>, @tap=nil, @block=#<Proc:0x00007fa1458d1cb8@/usr/local/Caskroom/parallels/.metadata/15.0.0-46967.upgrading/20190821153006.821/Casks/parallels.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/parallels>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/parallels/.metadata>, @config=#<Cask::Config:0x00007fa1458fb6d0 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/kbluck/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/kbluck/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/kbluck/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/kbluck/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/kbluck/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/kbluck/Library/Services>, :input_methoddir=>#<Pathname:/Users/kbluck/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/kbluck/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/kbluck/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/kbluck/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/kbluck/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/kbluck/Library/Screen Savers>}, @env={}, @explicit={}>, @dsl=#<Cask::DSL:0x00007fa1458f84d0 @cask=#<Cask::Cask:0x00007fa1458d1df8 ...>, @token="parallels", @version="15.0.0-46967", @sha256="ed8b991bbbb70142ced8ba450273118e613fcd9b692d00ef75ef8db0b046aa6c", @url=#<URL:0x00007fa14590b788 @uri=#<URI::HTTPS https://download.parallels.com/desktop/v15/15.0.0-46967/ParallelsDesktop-15.0.0-46967.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fa14590b1e8 @uri=#<URI::HTTPS https://kb.parallels.com/eu/124724>, @parameters={}>, @name=["Parallels Desktop"], @homepage="https://www.parallels.com/products/desktop/", @auto_updates=true, @depends_on={:macos=>#<MacOSRequirement: "macos" []>}, @container=#<Cask::DSL::Container:0x00007fa1459097a8 @pairs={:type=>:naked}, @type=:naked>, @artifacts=#<SortedSet: {...}>, @language=nil>>, @directives={:trash=>["~/.parallels_settings", "~/Library/Caches/com.parallels.desktop.console", "~/Library/Preferences/com.parallels.desktop.console.LSSharedFileList.plist", "~/Library/Preferences/com.parallels.desktop.console.plist", "~/Library/Preferences/com.parallels.Parallels Desktop Statistics.plist", "~/Library/Preferences/com.parallels.Parallels Desktop.plist", "~/Library/Preferences/com.parallels.Parallels.plist"], :signal=>[]}>}>
==> Uninstalling artifact of class Cask::Artifact::PreflightBlock
==> Uninstalling artifact of class Cask::Artifact::PreflightBlock
==> Uninstalling artifact of class Cask::Artifact::Uninstall
==> Removing files:
/usr/local/bin/prl_convert
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/usr/local/bin/prl_disk_tool
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/usr/local/bin/prl_perf_ctl
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/usr/local/bin/prlcore2dmp
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/usr/local/bin/prlctl
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/usr/local/bin/prlexec
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/usr/local/bin/prlsrvctl
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Applications/Parallels Desktop.app
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Applications/Parallels Desktop.app/Contents/Applications/Parallels Link.app
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Applications/Parallels Desktop.app/Contents/Applications/Parallels Mounter.app
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Applications/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
/Applications/Parallels Desktop.app/Contents/MacOS/Parallels VM.app
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
==> Post-uninstalling artifact of class Cask::Artifact::Uninstall
Error: No such file or directory @ rb_file_s_rename - (/usr/local/Caskroom/parallels/15.0.0-46967, /usr/local/Caskroom/parallels/15.0.0-46967.upgrading)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:416:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:416:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:416:in `backup'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:412:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:94:in `upgrade_cask'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:48:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:47:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:47:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew Version
2.1.16-30-g4873c49
==> macOS
10.14.6
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3498 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (136 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.36.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.76.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.6.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.29.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.18.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/nokogiri-1.10.5
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
bramstein/webfonttools
homebrew/cask
homebrew/cask-drivers
homebrew/core
```

**Comment by vitorgalvao** [comment]
Since we don’t have other reports (it’s a popular cask), assuming as a problem in your setup.
