### ISSUE TITLE
Archi URL is wrong

### ISSUE THREAD

**Issue by gguiesi** [Homebrew/homebrew-cask#72475]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The link for archi is returning 404. The script URL is https://www.archimatetool.com/downloads/4.6.0/Archi-Mac-4.6.0.zip but the correct is https://www.archimatetool.com/downloads/20191111/Archi-Linux64-4.6.0.tgz

#### Command that failed

```
brew cask install archi
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.16-48-ga6f244d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.1\)\ curl/7.64.1 --location --silent --head --request GET https://www.archimatetool.com/downloads/460/Archi-Mac-4.6.0.zip
==> Downloading https://www.archimatetool.com/downloads/460/Archi-Mac-4.6.0.zip
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.16-48-ga6f244d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.1\)\ curl/7.64.1 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://www.archimatetool.com/downloads/460/Archi-Mac-4.6.0.zip
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.16-48-ga6f244d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.1\)\ curl/7.64.1 --fail --location --remote-time --continue-at 0 --output /Users/geraldojunior/Library/Caches/Homebrew/downloads/76a291f19cd0fee6a666554a8f109fe4095b9e5948ace544f5bdfba9e244de4c--Archi-Mac-4.6.0.zip.incomplete https://www.archimatetool.com/downloads/460/Archi-Mac-4.6.0.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
Error: Download failed on Cask 'archi' with message: Download failed: https://www.archimatetool.com/downloads/460/Archi-Mac-4.6.0.zip
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:311:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:308:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:42:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:20:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:152:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:127:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:13:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:7:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:7:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
Your system is ready to brew.
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

**Comment by core-code** [comment]
thanks for reporting this issue

> but the correct is https://www.archimatetool.com/downloads/20191111/Archi-Linux64-4.6.0.tgz

no, this is the Linux version ;-)

i've submitted a PR to fix this here https://github.com/Homebrew/homebrew-cask/pull/73187
