### ISSUE TITLE
Unable to install or upgrade Java JDK: Error: Permission denied

### ISSUE THREAD

**Issue by LordGordonQ** [Homebrew/homebrew-cask#72879]
#### General troubleshooting steps

- [ ✔️ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ✔️ ] I have retried my command with `--force`.
- [ ✔️ ] I ran `brew update-reset && brew update` and retried my command.
- [ ✔️ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ✔️ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ✔️ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I attempted to upgrade Java and I got an error. I removed java (`brew cask uninstall java`) and tried to install it again.

#### Command that failed

```
brew cask install java
```

#### Output of command `brew cask install java --force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://download.java.net/java/GA/jdk13.0.1/cec27d702aa74d5a8630c65ae61e4305/9/GPL/openjdk-13.0.1_osx-x64_bin.tar.gz
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.16\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --location --silent --head --request GET https://download.java.net/java/GA/jdk13.0.1/cec27d702aa74d5a8630c65ae61e4305/9/GPL/openjdk-13.0.1_osx-x64_bin.tar.gz
Already downloaded: /Users/lordgordon/Library/Caches/Homebrew/downloads/ddb80fa87a726f0e3ce87cbbe314297309c3a3ae1198e79926d0aac3b3054f51--openjdk-13.0.1_osx-x64_bin.tar.gz
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/lordgordon/Library/Caches/Homebrew/downloads/ddb80fa87a726f0e3ce87cbbe314297309c3a3ae1198e79926d0aac3b3054f51--openjdk-13.0.1_osx-x64_bin.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/lordgordon/Library/Caches/Homebrew/downloads/ddb80fa87a726f0e3ce87cbbe314297309c3a3ae1198e79926d0aac3b3054f51--openjdk-13.0.1_osx-x64_bin.tar.gz
==> /Users/lordgordon/Library/Caches/Homebrew/downloads/ddb80fa87a726f0e3ce87cbbe314297309c3a3ae1198e79926d0aac3b3054f51--openjdk-13.0.1_osx-x64_bin.tar.gz is quarantined
==> Downloaded to -> /Users/lordgordon/Library/Caches/Homebrew/downloads/ddb80fa87a726f0e3ce87cbbe314297309c3a3ae1198e79926d0aac3b3054f51--openjdk-13.0.1_osx-x64_bin.tar.gz
==> Verifying SHA-256 checksum for Cask 'java'.
tar tf /Users/lordgordon/Library/Caches/Homebrew/downloads/ddb80fa87a726f0e3ce87cbbe314297309c3a3ae1198e79926d0aac3b3054f51--openjdk-13.0.1_osx-x64_bin.tar.gz
==> Installing Cask java
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Tar for /Users/lordgordon/Library/Caches/Homebrew/downloads/ddb80fa87a726f0e3ce87cbbe314297309c3a3ae1198e79926d0aac3b3054f51--openjdk-13.0.1_osx-x64_bin.tar.gz
tar xof /Users/lordgordon/Library/Caches/Homebrew/downloads/ddb80fa87a726f0e3ce87cbbe314297309c3a3ae1198e79926d0aac3b3054f51--openjdk-13.0.1_osx-x64_bin.tar.gz -C /var/folders/r5/pjvpmqts7vn_r9_wcd1225yr0000gn/T/d20191120-94749-16nl1g2
cp -pR /var/folders/r5/pjvpmqts7vn_r9_wcd1225yr0000gn/T/d20191120-94749-16nl1g2/jdk-13.0.1.jdk/. /usr/local/Caskroom/java/13.0.1,9:cec27d702aa74d5a8630c65ae61e4305/jdk-13.0.1.jdk
chmod -Rf +w /var/folders/r5/pjvpmqts7vn_r9_wcd1225yr0000gn/T/d20191120-94749-16nl1g2
==> Verifying Gatekeeper status of /Users/lordgordon/Library/Caches/Homebrew/downloads/ddb80fa87a726f0e3ce87cbbe314297309c3a3ae1198e79926d0aac3b3054f51--openjdk-13.0.1_osx-x64_bin.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/lordgordon/Library/Caches/Homebrew/downloads/ddb80fa87a726f0e3ce87cbbe314297309c3a3ae1198e79926d0aac3b3054f51--openjdk-13.0.1_osx-x64_bin.tar.gz
==> /Users/lordgordon/Library/Caches/Homebrew/downloads/ddb80fa87a726f0e3ce87cbbe314297309c3a3ae1198e79926d0aac3b3054f51--openjdk-13.0.1_osx-x64_bin.tar.gz is quarantined
==> Propagating quarantine from /Users/lordgordon/Library/Caches/Homebrew/downloads/ddb80fa87a726f0e3ce87cbbe314297309c3a3ae1198e79926d0aac3b3054f51--openjdk-13.0.1_osx-x64_bin.tar.gz to /usr/local/Caskroom/java/13.0.1,9:cec27d702aa74d5a8630c65ae61e4305
/usr/bin/xattr -p com.apple.quarantine /Users/lordgordon/Library/Caches/Homebrew/downloads/ddb80fa87a726f0e3ce87cbbe314297309c3a3ae1198e79926d0aac3b3054f51--openjdk-13.0.1_osx-x64_bin.tar.gz
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5dd4f5c0\;Homebrew\\x20Cask\;D079150C-5F29-48DC-A155-0310E97FFF53
==> Creating metadata directory /usr/local/Caskroom/java/.metadata/13.0.1,9:cec27d702aa74d5a8630c65ae61e4305/20191120083312.076.
==> Creating metadata subdirectory /usr/local/Caskroom/java/.metadata/13.0.1,9:cec27d702aa74d5a8630c65ae61e4305/20191120083312.076/Casks.
==> Installing artifacts
==> 1 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Artifact:0x00007fd12b8945c8 @cask=#<Cask::Cask:0x00007fd12b335be0 @token="java", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/java.rb>, @tap=#<Tap:0x00007fd12b324b38 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fd12b335b40@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/java.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/java>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/java/.metadata>, @config=#<Cask::Config:0x00007fd12b897a70 @explicit={}>, @dsl=#<Cask::DSL:0x00007fd12b897750 @cask=#<Cask::Cask:0x00007fd12b335be0 ...>, @token="java", @version="13.0.1,9:cec27d702aa74d5a8630c65ae61e4305", @sha256="593c5c9dc0978db21b06d6219dc8584b76a59c79d57e6ec1b28ad0d848a7713f", @url=#<URL:0x00007fd12b896378 @uri=#<URI::HTTPS https://download.java.net/java/GA/jdk13.0.1/cec27d702aa74d5a8630c65ae61e4305/9/GPL/openjdk-13.0.1_osx-x64_bin.tar.gz>, @user_agent=:default, @specs={}>, @name=["OpenJDK Java Development Kit"], @homepage="https://openjdk.java.net/", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/java/13.0.1,9:cec27d702aa74d5a8630c65ae61e4305>, @language=nil>>, @source_string="jdk-13.0.1.jdk", @target_string="/Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk", @source=#<Pathname:/usr/local/Caskroom/java/13.0.1,9:cec27d702aa74d5a8630c65ae61e4305/jdk-13.0.1.jdk>, @target=#<Pathname:/Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk>>}>
==> Installing artifact of class Cask::Artifact::Artifact
==> Moving Generic Artifact 'jdk-13.0.1.jdk' to '/Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk'.
/usr/bin/sudo -E -- /bin/mkdir -p /Library/Java/JavaVirtualMachines
/usr/bin/sudo -E -- /bin/mv /usr/local/Caskroom/java/13.0.1,9:cec27d702aa74d5a8630c65ae61e4305/jdk-13.0.1.jdk /Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
/usr/bin/xattr -p com.apple.metadata:kMDItemAlternateNames /Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk
==> Existing metadata is: ''
==> Purging files for version 13.0.1,9:cec27d702aa74d5a8630c65ae61e4305 of Cask java
Error: Permission denied @ realpath_rec - /Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/artifact/relocated.rb:73:in `realpath'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/relocated.rb:73:in `realpath'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/relocated.rb:73:in `add_altname_metadata'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:59:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:13:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:220:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:211:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.1.16
==> macOS
10.14.6
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3463 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (160 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (939 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.36.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.75.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.6.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.29.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.18.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/nokogiri-1.10.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.12.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
```

**Comment by LordGordonQ** [comment]
So far, the only workaround I found is to manually fix the permissions of `/Library/Java/JavaVirtualMachines` with:

```
sudo chmod o+rx /Library/Java/JavaVirtualMachines
```

This way Java works, yet brew is unable to recognize it as installed.

**Comment by vitorgalvao** [comment]
[`java` is being moved](https://github.com/Homebrew/homebrew-cask/pull/72284) and nobody else seems to be having the issue, so no point in looking into this now.

**Comment by brasilikum** [comment]
I have this issue

**Comment by joewiz** [comment]
I have this issue
