### ISSUE TITLE
Fix Powershell Cask dependency for openssl@1.1

### ISSUE THREAD

**Issue by gairys** [Homebrew/homebrew-cask#73003]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

powershell.rb has a dependency on 'openssl'. OpenSSL in brew has been removed and replaced with 'openssl@1.1'. Editing the powershell.rb file resolves the issue.

Initial attempt:
```bash
% brew cask install powershell
==> Downloading https://github.com/PowerShell/PowerShell/releases/download/v6.2.
Already downloaded: /Users/myuser/Library/Caches/Homebrew/downloads/8f038fec01ae8495ce2126bd25251e4a4aa8a4a2a504de07b51cf1faefc29840--powershell-6.2.3-osx-x64.pkg
==> Verifying SHA-256 checksum for Cask 'powershell'.
Error: No available formula with the name "openssl" 
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/formulary.rb:286:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:317:in `factory'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1479:in `[]'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:289:in `block in graph_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:289:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:289:in `graph_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:314:in `collect_cask_and_formula_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:341:in `cask_and_formula_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:255:in `satisfy_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:67:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:92:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

Verifying issue:
```bash
% brew update
Already up-to-date.

% brew doctor
Your system is ready to brew.

% brew install openssl
Error: No available formula with the name "openssl" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

openssl was deleted from homebrew/core in commit 0349a7c:
  openssl: delete (https://github.com/Homebrew/homebrew-core/issues/46876)

% brew install openssl@1.1
Warning: openssl@1.1 1.1.1d is already installed and up-to-date
```

Changed line 10 of powershell.rb from `  depends_on formula: 'openssl` to `  depends_on formula: 'openssl@1.1'`

Successful install after change:
```bash
% brew cask install powershell
==> Downloading https://github.com/PowerShell/PowerShell/releases/download/v6.2.3/powershell-6.2.3-osx-x
Already downloaded: /Users/myuser/Library/Caches/Homebrew/downloads/8f038fec01ae8495ce2126bd25251e4a4aa8a4a2a504de07b51cf1faefc29840--powershell-6.2.3-osx-x64.pkg
==> Verifying SHA-256 checksum for Cask 'powershell'.
All Formula dependencies satisfied.
==> Installing Cask powershell
==> Running installer for powershell; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
installer: Package name is PowerShell - 6.2.3
installer: Installing at base path /
installer: The install was successful.
🍺  powershell was successfully installed!
```

**Comment by gairys** [comment]
This is my first issue filed in Github, so my apologizes if I did this incorrectly.

**Comment by ran-dall** [comment]
@gairys 👋 Welcome to **GitHub** and **HBC**! This LGTM 🤘

**Comment by reitermarkus** [comment]
Should be fixed by https://github.com/Homebrew/homebrew-core/pull/47034.
