### ISSUE TITLE
cask style checks failing

### ISSUE THREAD

**Issue by leipert** [Homebrew/homebrew-cask#73411]
For example: https://github.com/Homebrew/homebrew-cask/pull/73410

It started failing since yesterday 15.35 UTC yesterday.

```
Error: Failure while executing; `/usr/bin/env XDG_CACHE_HOME=/Users/runner/Library/Caches/Homebrew/style /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby -W0 -S rubocop --force-exclusion --config /usr/local/Homebrew/Library/.rubocop_cask.yml --format json -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/goland.rb` exited with 2.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/style.rb:44:in `rubocop'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/cmd/brewcask-ci.rb:62:in `rescue in block (2 levels) in run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/cmd/brewcask-ci.rb:55:in `block (2 levels) in run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/cmd/brewcask-ci.rb:231:in `step'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/cmd/brewcask-ci.rb:54:in `block in run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/cmd/brewcask-ci.rb:51:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/cmd/brewcask-ci.rb:51:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:112:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
##[error]Process completed with exit code 1.
```

**Comment by leipert** [comment]
Was also able to reproduce locally:

- `brew cask style rubymine` 
- `brew cask style firefox`

```
Error: Failure while executing; `/usr/bin/env XDG_CACHE_HOME=/Users/leipert/Library/Caches/Homebrew/style /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby -W0 -S rubocop --force-exclusion --config /usr/local/Homebrew/Library/.rubocop_cask.yml --parallel --format simple --color -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb` exited with 2.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/style.rb:44:in `rubocop'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/style.rb:54:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by leipert** [comment]
Ah, could it have been caused by: https://github.com/Homebrew/brew/pull/6789

cc/ @MikeMcQuaid

**Comment by ran-dall** [comment]
@leipert We've been tracking the issue since yesterday here: https://github.com/Homebrew/homebrew-cask/pull/73391

**Comment by leipert** [comment]
Ah, sorry. Haven't found it in the PRs.
