### ISSUE TITLE
Uninstalling box-sync fails without --force

### ISSUE THREAD

**Issue by onlynone** [Homebrew/homebrew-cask#73764]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Uninstalling `box-sync` fails

#### Command that failed

```
$ brew cask uninstall box-sync
==> Uninstalling Cask box-sync
==> Removing files:
/Library/PrivilegedHelperTools/com.box.sync.iconhelper
Password:
/Library/PrivilegedHelperTools/com.box.sync.bootstrapper
==> Backing App 'Box Sync.app' up to '/usr/local/Caskroom/box-sync/latest/Box Sync.app'.
==> Removing App '/Applications/Box Sync.app'.
Error: Directory not empty @ dir_s_rmdir - /Applications/Box Sync.app
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:1431:in `rmdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:1431:in `block in remove_dir1'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:1442:in `platform_support'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:1430:in `remove_dir1'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:1423:in `remove'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:760:in `block in remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:1480:in `ensure in postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:1480:in `postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:758:in `remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:610:in `block in rm_r'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:606:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:606:in `rm_r'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/pathname.rb:589:in `rmtree'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:96:in `delete'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:86:in `move_back'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:17:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:454:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:450:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:399:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:24:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

Running the same command again gives:

```
$ brew cask uninstall box-sync
==> Uninstalling Cask box-sync
==> Removing files:
/Library/PrivilegedHelperTools/com.box.sync.iconhelper
/Library/PrivilegedHelperTools/com.box.sync.bootstrapper
Error: It seems there is already an App at '/usr/local/Caskroom/box-sync/latest/Box Sync.app'.
```

And a third time with `--force` as suggested:

```
brew cask uninstall --force box-sync
==> Uninstalling Cask box-sync
==> Removing files:
/Library/PrivilegedHelperTools/com.box.sync.iconhelper
/Library/PrivilegedHelperTools/com.box.sync.bootstrapper
Warning: It seems there is already an App at '/usr/local/Caskroom/box-sync/latest/Box Sync.app'; overwriting.
==> Removing App '/usr/local/Caskroom/box-sync/latest/Box Sync.app'.
==> Backing App 'Box Sync.app' up to '/usr/local/Caskroom/box-sync/latest/Box Sync.app'.
==> Removing App '/Applications/Box Sync.app'.
chmod: Unable to change file mode on /Applications/Box Sync.app/Contents/_CodeSignature/CodeResources: Operation not permitted
chmod: Unable to change file mode on /Applications/Box Sync.app/Contents/Plugins/FinderSyncExt.appex/Contents/_CodeSignature/CodeResources: Operation not permitted
chmod: Unable to change file mode on /Applications/Box Sync.app/Contents/Plugins/FinderSyncExt.appex/Contents/Resources/Synced.icns: Operation not permitted
[... snip a whole bunch of these ...]
chmod: Unable to change file mode on /Applications/Box Sync.app/Contents/Frameworks/Python.framework/Versions/2.7/Resources/Info.plist: Operation not permitted
chmod: Unable to change file mode on /Applications/Box Sync.app/Contents/Info.plist: Operation not permitted
chmod: Unable to change file mode on /Applications/Box Sync.app/Contents/PkgInfo: Operation not permitted
==> Using sudo to gain ownership of path '/Applications/Box Sync.app'
==> Purging files for version latest of Cask box-sync
```

#### Output of command with `--force --verbose --debug`

N/A -- never got to try with all those options because it finally seemed to remove everything with with `--force` from above.

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.0-65-g2b34c10
==> macOS
10.14.3
==> SIP
Enabled
==> Java
12.0.2, 1.8.0_232, 1.6.0_65-b14-468
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3478 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (160 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
codekitchen/dinghy
go-delve/delve
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
johanhaleby/kubetail
onlynone/custom
```

**Comment by vitorgalvao** [comment]
Can’t reproduce and no one else has reported the issue, so it seems to be something in your setup.
