### ISSUE TITLE
screaming-frog-seo-spider is outdated - new version 12.4 is available

### ISSUE THREAD

**Issue by phschaer** [Homebrew/homebrew-cask#74431]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

screaming-frog-seo-spider is outdated - new version 12.4 is available

#### Command that failed

```
brew cask install screaming-frog-seo-spider
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Caveats
screaming-frog-seo-spider requires Java 7+. You can install the latest version with:
  brew cask install adoptopenjdk

==> Cask::Installer#fetch
==> Downloading
==> Downloading https://download.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-12.3.dmg
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.2\)\ curl/7.64.1 --location --silent --head --request GET https://download.screamingfrog.co.uk/products/seo-spider/ScreamingFrogSEOSpider-12.3.dmg
Already downloaded: /Users/schaer/Library/Caches/Homebrew/downloads/f3d3eb041eec65bf89713fa36ee3f388b7e31927baa68ceb58635d9c2fe2ea01--ScreamingFrogSEOSpider-12.4.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/schaer/Library/Caches/Homebrew/downloads/f3d3eb041eec65bf89713fa36ee3f388b7e31927baa68ceb58635d9c2fe2ea01--ScreamingFrogSEOSpider-12.4.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/schaer/Library/Caches/Homebrew/downloads/f3d3eb041eec65bf89713fa36ee3f388b7e31927baa68ceb58635d9c2fe2ea01--ScreamingFrogSEOSpider-12.4.dmg
==> /Users/schaer/Library/Caches/Homebrew/downloads/f3d3eb041eec65bf89713fa36ee3f388b7e31927baa68ceb58635d9c2fe2ea01--ScreamingFrogSEOSpider-12.4.dmg is quarantined
==> Downloaded to -> /Users/schaer/Library/Caches/Homebrew/downloads/f3d3eb041eec65bf89713fa36ee3f388b7e31927baa68ceb58635d9c2fe2ea01--ScreamingFrogSEOSpider-12.4.dmg
==> Verifying SHA-256 checksum for Cask 'screaming-frog-seo-spider'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'screaming-frog-seo-spider' does not match.
Expected: 446e907954a7abfaeb341b57a6aacc57f0b416fe2c4db3ee13abb1ab52a47f50
  Actual: 0a00bb6fca07687a5d61d98f8cbbe394378c7cea22515d33a7aab68f3db059d2
    File: /Users/schaer/Library/Caches/Homebrew/downloads/f3d3eb041eec65bf89713fa36ee3f388b7e31927baa68ceb58635d9c2fe2ea01--ScreamingFrogSEOSpider-12.4.dmg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
/usr/local/Homebrew/Library/Homebrew/cask/verify.rb:23:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:165:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:63:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
schaer@touchbot:~$
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/74472
