### ISSUE TITLE
amazon-music does not install

### ISSUE THREAD

**Issue by alexreg** [Homebrew/homebrew-cask#74721]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The `amazon-music` cask fails to install:
* `an error occurred while attempting to obtain endpoint for listener`
* `Error changing permissions to 040755 in /Applications/Amazon Music.app`

#### Command that failed

```
brew cask install amazon-music
```

#### Output of command with `--force --verbose --debug`

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Cask::Installer#install
==> Printing caveats
==> Caveats
If the app will not launch after installation, try

  brew cask zap amazon-music
  brew cask install amazon-music

then re-launch the app.

==> Cask::Installer#fetch
==> Downloading
==> Downloading https://images-na.ssl-images-amazon.com/images/G/01/digital/music/morpho/installers/20191210/0817399808/AmazonMusicInstaller.dmg
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.2\)\ curl/7.64.1 --location --silent --head --request GET https://images-na.ssl-images-amazon.com/images/G/01/digital/music/morpho/installers/20191210/0817399808/AmazonMusicInstaller.dmg
Already downloaded: /Library/Caches/Homebrew/downloads/6383b292188f1df72adf7f69ec79a25642204d79715a314306367982220f9774--AmazonMusicInstaller.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Library/Caches/Homebrew/downloads/6383b292188f1df72adf7f69ec79a25642204d79715a314306367982220f9774--AmazonMusicInstaller.dmg
/usr/bin/xattr -p com.apple.quarantine /Library/Caches/Homebrew/downloads/6383b292188f1df72adf7f69ec79a25642204d79715a314306367982220f9774--AmazonMusicInstaller.dmg
==> /Library/Caches/Homebrew/downloads/6383b292188f1df72adf7f69ec79a25642204d79715a314306367982220f9774--AmazonMusicInstaller.dmg is quarantined
==> Downloaded to -> /Library/Caches/Homebrew/downloads/6383b292188f1df72adf7f69ec79a25642204d79715a314306367982220f9774--AmazonMusicInstaller.dmg
==> Verifying SHA-256 checksum for Cask 'amazon-music'.
hdiutil imageinfo -format /Library/Caches/Homebrew/downloads/6383b292188f1df72adf7f69ec79a25642204d79715a314306367982220f9774--AmazonMusicInstaller.dmg
==> Installing Cask amazon-music
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Library/Caches/Homebrew/downloads/6383b292188f1df72adf7f69ec79a25642204d79715a314306367982220f9774--AmazonMusicInstaller.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/d20191223-35586-1eo5tnj /Library/Caches/Homebrew/downloads/6383b292188f1df72adf7f69ec79a25642204d79715a314306367982220f9774--AmazonMusicInstaller.dmg
find . -print0
mkbom -s -i /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/20191223-35586-1hk24eu.list -- /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/20191223-35586-1ecceb5.bom
ditto --bom /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/20191223-35586-1ecceb5.bom -- /private/var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/d20191223-35586-1eo5tnj/dmg.mWREt3 /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/d20191223-35586-1bncb9i
diskutil eject /private/var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/d20191223-35586-1eo5tnj/dmg.mWREt3
cp -pR /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/d20191223-35586-1bncb9i/Amazon\ Music\ Installer.app/. /usr/local/Caskroom/amazon-music/7.9.0,20191210:0817399808/Amazon\ Music\ Installer.app
chmod -Rf +w /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/d20191223-35586-1bncb9i
==> Verifying Gatekeeper status of /Library/Caches/Homebrew/downloads/6383b292188f1df72adf7f69ec79a25642204d79715a314306367982220f9774--AmazonMusicInstaller.dmg
/usr/bin/xattr -p com.apple.quarantine /Library/Caches/Homebrew/downloads/6383b292188f1df72adf7f69ec79a25642204d79715a314306367982220f9774--AmazonMusicInstaller.dmg
==> /Library/Caches/Homebrew/downloads/6383b292188f1df72adf7f69ec79a25642204d79715a314306367982220f9774--AmazonMusicInstaller.dmg is quarantined
==> Propagating quarantine from /Library/Caches/Homebrew/downloads/6383b292188f1df72adf7f69ec79a25642204d79715a314306367982220f9774--AmazonMusicInstaller.dmg to /usr/local/Caskroom/amazon-music/7.9.0,20191210:0817399808
/usr/bin/xattr -p com.apple.quarantine /Library/Caches/Homebrew/downloads/6383b292188f1df72adf7f69ec79a25642204d79715a314306367982220f9774--AmazonMusicInstaller.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5e0101cd\;Homebrew\\x20Cask\;1BF583A4-18F5-4D7F-ADE1-1878B5B541C2
==> Creating metadata directory /usr/local/Caskroom/amazon-music/.metadata/7.9.0,20191210:0817399808/20191223190633.276.
==> Creating metadata subdirectory /usr/local/Caskroom/amazon-music/.metadata/7.9.0,20191210:0817399808/20191223190633.276/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fb12990c068 @cask=#<Cask::Cask:0x00007fb1108f9198 @token="amazon-music", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/amazon-music.rb>, @tap=#<Tap:0x00007fb1288275b8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fb1108f8f90@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/amazon-music.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/amazon-music>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/amazon-music/.metadata>, @config=#<Cask::Config:0x00007fb1299079f0 @explicit={}>, @dsl=#<Cask::DSL:0x00007fb1299075b8 @cask=#<Cask::Cask:0x00007fb1108f9198 ...>, @token="amazon-music", @version="7.9.0,20191210:0817399808", @sha256="bbb89096aac3245ef08c59ef277611f137da4a5137f33cb528d9e56058deebd8", @url=#<URL:0x00007fb129906898 @uri=#<URI::HTTPS https://images-na.ssl-images-amazon.com/images/G/01/digital/music/morpho/installers/20191210/0817399808/AmazonMusicInstaller.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fb12990e688 @uri=#<URI::HTTPS https://www.amazon.com/gp/dmusic/desktop/downloadPlayer>, @parameters={:configuration=>"20191210/0817399808"}, @configuration="20191210/0817399808">, @name=["Amazon Music"], @homepage="https://www.amazon.com/musicapps", @auto_updates=true, @artifacts=#<SortedSet: {...}>, @caveats=#<Cask::DSL::Caveats:0x00007fb129917760 @cask=#<Cask::Cask:0x00007fb1108f9198 ...>, @command=SystemCommand, @built_in_caveats={}, @custom_caveats=["If the app will not launch after installation, try\n\n  brew cask zap amazon-music\n  brew cask install amazon-music\n\nthen re-launch the app.\n"]>, @language=nil>>, @directives={:quit=>["com.amazon.music", "com.amazon.music-renderer"], :delete=>"/Applications/Amazon Music.app", :launchctl=>["com.amazon.music", "com.amazon.music.startup"], :signal=>[]}>, #<Cask::Artifact::Installer:0x00007fb12990cd38 @cask=#<Cask::Cask:0x00007fb1108f9198 @token="amazon-music", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/amazon-music.rb>, @tap=#<Tap:0x00007fb1288275b8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fb1108f8f90@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/amazon-music.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/amazon-music>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/amazon-music/.metadata>, @config=#<Cask::Config:0x00007fb1299079f0 @explicit={}>, @dsl=#<Cask::DSL:0x00007fb1299075b8 @cask=#<Cask::Cask:0x00007fb1108f9198 ...>, @token="amazon-music", @version="7.9.0,20191210:0817399808", @sha256="bbb89096aac3245ef08c59ef277611f137da4a5137f33cb528d9e56058deebd8", @url=#<URL:0x00007fb129906898 @uri=#<URI::HTTPS https://images-na.ssl-images-amazon.com/images/G/01/digital/music/morpho/installers/20191210/0817399808/AmazonMusicInstaller.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fb12990e688 @uri=#<URI::HTTPS https://www.amazon.com/gp/dmusic/desktop/downloadPlayer>, @parameters={:configuration=>"20191210/0817399808"}, @configuration="20191210/0817399808">, @name=["Amazon Music"], @homepage="https://www.amazon.com/musicapps", @auto_updates=true, @artifacts=#<SortedSet: {...}>, @caveats=#<Cask::DSL::Caveats:0x00007fb129917760 @cask=#<Cask::Cask:0x00007fb1108f9198 ...>, @command=SystemCommand, @built_in_caveats={}, @custom_caveats=["If the app will not launch after installation, try\n\n  brew cask zap amazon-music\n  brew cask install amazon-music\n\nthen re-launch the app.\n"]>, @language=nil>>, @args={:must_succeed=>true, :sudo=>false, :print_stdout=>true}, @path=#<Pathname:Amazon Music Installer.app/Contents/MacOS/installbuilder.sh>>, #<Cask::Artifact::Zap:0x00007fb129917aa8 @cask=#<Cask::Cask:0x00007fb1108f9198 @token="amazon-music", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/amazon-music.rb>, @tap=#<Tap:0x00007fb1288275b8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fb1108f8f90@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/amazon-music.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/amazon-music>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/amazon-music/.metadata>, @config=#<Cask::Config:0x00007fb1299079f0 @explicit={}>, @dsl=#<Cask::DSL:0x00007fb1299075b8 @cask=#<Cask::Cask:0x00007fb1108f9198 ...>, @token="amazon-music", @version="7.9.0,20191210:0817399808", @sha256="bbb89096aac3245ef08c59ef277611f137da4a5137f33cb528d9e56058deebd8", @url=#<URL:0x00007fb129906898 @uri=#<URI::HTTPS https://images-na.ssl-images-amazon.com/images/G/01/digital/music/morpho/installers/20191210/0817399808/AmazonMusicInstaller.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fb12990e688 @uri=#<URI::HTTPS https://www.amazon.com/gp/dmusic/desktop/downloadPlayer>, @parameters={:configuration=>"20191210/0817399808"}, @configuration="20191210/0817399808">, @name=["Amazon Music"], @homepage="https://www.amazon.com/musicapps", @auto_updates=true, @artifacts=#<SortedSet: {...}>, @caveats=#<Cask::DSL::Caveats:0x00007fb129917760 @cask=#<Cask::Cask:0x00007fb1108f9198 ...>, @command=SystemCommand, @built_in_caveats={}, @custom_caveats=["If the app will not launch after installation, try\n\n  brew cask zap amazon-music\n  brew cask install amazon-music\n\nthen re-launch the app.\n"]>, @language=nil>>, @directives={:trash=>["~/Library/Preferences/com.amazon.music.plist", "~/Library/Application Support/Amazon Music"], :signal=>[]}>}>
==> Installing artifact of class Cask::Artifact::Installer
==> Running installer script 'Amazon Music Installer.app/Contents/MacOS/installbuilder.sh'
/usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/amazon-music/7.9.0,20191210:0817399808/Amazon\ Music\ Installer.app/Contents/MacOS/installbuilder.sh
2019-12-23 19:06:38.623 osx-x86_64[36524:703386] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
2019-12-23 19:06:48.709 osx-x86_64[36524:703440] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'HostCallsAuxiliary': Connection interrupted
Error: Failure while executing; `/usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/amazon-music/7.9.0,20191210:0817399808/Amazon\ Music\ Installer.app/Contents/MacOS/installbuilder.sh` exited with 1. Here's the output:
Error running launchctl remove com.amazon.music : child process exited abnormally
Error running launchctl remove com.amazon.cloud-player : child process exited abnormally
2019-12-23 19:06:38.623 osx-x86_64[36524:703386] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted
2019-12-23 19:06:48.709 osx-x86_64[36524:703440] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'HostCallsAuxiliary': Connection interrupted
Error changing permissions to 040755 in /Applications/Amazon Music.app
Abort
There has been an error.
Unable to set permissions
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/installer.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error running launchctl remove com.amazon.music : child process exited abnormally
Error running launchctl remove com.amazon.cloud-player : child process exited abnormally
Error changing permissions to 040755 in /Applications/Amazon Music.app
Abort
There has been an error.
Unable to set permissions
==> Purging files for version 7.9.0,20191210:0817399808 of Cask amazon-music
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.2
==> macOS
10.15.2
==> SIP
Unknown (custom configuration)

configuration:
apple internal: disabled
kext signing: enabled
filesystem protections: disabled
debugging restrictions: disabled
dtrace restrictions: enabled
nvram protections: enabled
basesystem verification: enabled
==> Java
1.8.0_60
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3493 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (138 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.37.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.78.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.6.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.30.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.19.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/nokogiri-1.10.7
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.22.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/json-2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
alexreg/utilities
brewsci/bio
eblot/armeabi
homebrew/cask
homebrew/cask-drivers
homebrew/core
homebrew/services
sbdchd/skim
teamookla/speedtest
```

**Comment by vitorgalvao** [comment]
It’s not us trying to change permissions, [it’s them](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/amazon-music.rb#L14L16).

You need to report this upstream.

**Comment by alexreg** [comment]
Ah okay, will do, cheers.
