### ISSUE TITLE
 Error: Failure while executing, when installing Mono Framework MDK

### ISSUE THREAD

**Issue by indrayudhistira** [Homebrew/homebrew-cask#74926]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I get the following error when installing mono-mdk using brew cask

installer: Package name is Mono Framework
installer: Installing at base path /
installer: The install failed..
==> Purging files for version 6.6.0.161 of Cask mono-mdk
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=xyz USER=xyz USERNAME=xyz /usr/sbin/installer -pkg /usr/local/Caskroom/mono-mdk/6.6.0.161/MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg -target /` exited with 1. Here's the output:
installer: Package name is Mono Framework
installer: Installing at base path /
installer: The install failed..

#### Command that failed

```
brew cask install mono-mdk
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Caveats
Installing mono-mdk removes mono and mono dependant formula binaries in
/usr/local/bin and adds mono-mdk to /private/etc/paths.d/
You may want to:

  brew unlink {formula} && brew link {formula}

and/or remove /private/etc/paths.d/mono-commands

==> Cask::Installer#fetch
==> Downloading
==> Downloading https://download.mono-project.com/archive/6.6.0/macos-10-universal/MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.2-18-ge7a2fde\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.1\)\ curl/7.64.1 --location --silent --head --request GET https://download.mono-project.com/archive/6.6.0/macos-10-universal/MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg
Already downloaded: /Users/xyz/Library/Caches/Homebrew/downloads/cbb40eca8b265c94df07bd628367fa280c2a50c1ae34534842384cf1c9c12680--MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/xyz/Library/Caches/Homebrew/downloads/cbb40eca8b265c94df07bd628367fa280c2a50c1ae34534842384cf1c9c12680--MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg
/usr/bin/xattr -p com.apple.quarantine /Users/xyz/Library/Caches/Homebrew/downloads/cbb40eca8b265c94df07bd628367fa280c2a50c1ae34534842384cf1c9c12680--MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg
==> /Users/xyz/Library/Caches/Homebrew/downloads/cbb40eca8b265c94df07bd628367fa280c2a50c1ae34534842384cf1c9c12680--MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg is quarantined
==> Downloaded to -> /Users/xyz/Library/Caches/Homebrew/downloads/cbb40eca8b265c94df07bd628367fa280c2a50c1ae34534842384cf1c9c12680--MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg
==> Verifying SHA-256 checksum for Cask 'mono-mdk'.
==> Installing Cask mono-mdk
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Pkg for /Users/xyz/Library/Caches/Homebrew/downloads/cbb40eca8b265c94df07bd628367fa280c2a50c1ae34534842384cf1c9c12680--MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg
cp -p /Users/xyz/Library/Caches/Homebrew/downloads/cbb40eca8b265c94df07bd628367fa280c2a50c1ae34534842384cf1c9c12680--MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg /usr/local/Caskroom/mono-mdk/6.6.0.161/MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg
==> Verifying Gatekeeper status of /Users/xyz/Library/Caches/Homebrew/downloads/cbb40eca8b265c94df07bd628367fa280c2a50c1ae34534842384cf1c9c12680--MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg
/usr/bin/xattr -p com.apple.quarantine /Users/xyz/Library/Caches/Homebrew/downloads/cbb40eca8b265c94df07bd628367fa280c2a50c1ae34534842384cf1c9c12680--MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg
==> /Users/xyz/Library/Caches/Homebrew/downloads/cbb40eca8b265c94df07bd628367fa280c2a50c1ae34534842384cf1c9c12680--MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg is quarantined
==> Propagating quarantine from /Users/xyz/Library/Caches/Homebrew/downloads/cbb40eca8b265c94df07bd628367fa280c2a50c1ae34534842384cf1c9c12680--MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg to /usr/local/Caskroom/mono-mdk/6.6.0.161
/usr/bin/xattr -p com.apple.quarantine /Users/xyz/Library/Caches/Homebrew/downloads/cbb40eca8b265c94df07bd628367fa280c2a50c1ae34534842384cf1c9c12680--MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5e091d87\;Homebrew\\x20Cask\;3E874041-07E4-4041-9B8C-5967BF3EBBE9
==> Creating metadata directory /usr/local/Caskroom/mono-mdk/.metadata/6.6.0.161/20191229222006.061.
==> Creating metadata subdirectory /usr/local/Caskroom/mono-mdk/.metadata/6.6.0.161/20191229222006.061/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fa93d26ba40 @cask=#<Cask::Cask:0x00007fa93d230b20 @token="mono-mdk", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/mono-mdk.rb>, @tap=#<Tap:0x00007fa93d47b0d8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fa93d2303c8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/mono-mdk.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/mono-mdk>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/mono-mdk/.metadata>, @config=#<Cask::Config:0x00007fa93d253468 @explicit={}>, @dsl=#<Cask::DSL:0x00007fa93d253080 @cask=#<Cask::Cask:0x00007fa93d230b20 ...>, @token="mono-mdk", @version="6.6.0.161", @sha256="8f0b7f6a34321fc4c46e9e6d7ad83c73ae009289fb689ac9f846eebb51146a6e", @url=#<URL:0x00007fa93d25b910 @uri=#<URI::HTTPS https://download.mono-project.com/archive/6.6.0/macos-10-universal/MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fa93d25ad08 @uri=#<URI::HTTPS https://www.mono-project.com/download/stable/>, @parameters={}>, @name=["Mono"], @homepage="https://www.mono-project.com/", @conflicts_with={:cask=>#<Set: {"mono-mdk516"}>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/mono-mdk/6.6.0.161>, @caveats=#<Cask::DSL::Caveats:0x00007fa93d26b1a8 @cask=#<Cask::Cask:0x00007fa93d230b20 ...>, @command=SystemCommand, @built_in_caveats={}, @custom_caveats=["Installing mono-mdk removes mono and mono dependant formula binaries in\n/usr/local/bin and adds mono-mdk to /private/etc/paths.d/\nYou may want to:\n\n  brew unlink {formula} && brew link {formula}\n\nand/or remove /private/etc/paths.d/mono-commands\n"]>, @language=nil>>, @directives={:delete=>["/Library/Frameworks/Mono.framework/Versions/6.6.0", "/private/etc/paths.d/mono-commands"], :pkgutil=>"com.xamarin.mono-*", :rmdir=>["/Library/Frameworks/Mono.framework/Versions", "/Library/Frameworks/Mono.framework"], :signal=>[]}>, #<Cask::Artifact::Pkg:0x00007fa93d259318 @cask=#<Cask::Cask:0x00007fa93d230b20 @token="mono-mdk", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/mono-mdk.rb>, @tap=#<Tap:0x00007fa93d47b0d8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fa93d2303c8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/mono-mdk.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/mono-mdk>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/mono-mdk/.metadata>, @config=#<Cask::Config:0x00007fa93d253468 @explicit={}>, @dsl=#<Cask::DSL:0x00007fa93d253080 @cask=#<Cask::Cask:0x00007fa93d230b20 ...>, @token="mono-mdk", @version="6.6.0.161", @sha256="8f0b7f6a34321fc4c46e9e6d7ad83c73ae009289fb689ac9f846eebb51146a6e", @url=#<URL:0x00007fa93d25b910 @uri=#<URI::HTTPS https://download.mono-project.com/archive/6.6.0/macos-10-universal/MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fa93d25ad08 @uri=#<URI::HTTPS https://www.mono-project.com/download/stable/>, @parameters={}>, @name=["Mono"], @homepage="https://www.mono-project.com/", @conflicts_with={:cask=>#<Set: {"mono-mdk516"}>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/mono-mdk/6.6.0.161>, @caveats=#<Cask::DSL::Caveats:0x00007fa93d26b1a8 @cask=#<Cask::Cask:0x00007fa93d230b20 ...>, @command=SystemCommand, @built_in_caveats={}, @custom_caveats=["Installing mono-mdk removes mono and mono dependant formula binaries in\n/usr/local/bin and adds mono-mdk to /private/etc/paths.d/\nYou may want to:\n\n  brew unlink {formula} && brew link {formula}\n\nand/or remove /private/etc/paths.d/mono-commands\n"]>, @language=nil>>, @path=#<Pathname:/usr/local/Caskroom/mono-mdk/6.6.0.161/MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg>, @stanza_options={}>}>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for mono-mdk; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- /usr/bin/env LOGNAME=xyz USER=xyz USERNAME=xyz /usr/sbin/installer -pkg /usr/local/Caskroom/mono-mdk/6.6.0.161/MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg -target / -verboseR
Password:
installer: Package name is Mono Framework
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Mono Framework…
installer: The install failed..
==> Purging files for version 6.6.0.161 of Cask mono-mdk
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=xyz USER=xyz USERNAME=xyz /usr/sbin/installer -pkg /usr/local/Caskroom/mono-mdk/6.6.0.161/MonoFramework-MDK-6.6.0.161.macos10.xamarin.universal.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Mono Framework
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Mono Framework…
installer: The install failed..
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.2-18-ge7a2fde
==> macOS
10.15.1
==> SIP
Enabled
==> Java
13.0.1
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3494 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (940 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.37.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.78.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.6.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.30.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.19.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/nokogiri-1.10.7
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.22.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/json-2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"

```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-fonts
homebrew/core
homebrew/services
```

**Comment by vitorgalvao** [comment]
No further reports on this, and those casks have been updated multiple times since. Might be an issue on your setup.
