### ISSUE TITLE
Failed to install osxfuse

### ISSUE THREAD

**Issue by yanan-xu** [Homebrew/homebrew-cask#75032]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Failed to install osxfuse

#### Command that failed

```
brew cask install osxfuse
```

#### Output of command with `--force --verbose --debug`

```
Updating Homebrew...
==> Cask::Installer#install
==> Printing caveats
==> Caveats
To install and/or use osxfuse you may need to enable its kernel extension in:
  System Preferences → Security & Privacy → General
For more information refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

You must reboot for the installation of osxfuse to take effect.

==> Cask::Installer#fetch
==> Downloading
==> Downloading https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.10.4/osxfuse-3.10.4.dmg
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.2-50-gc0b9167\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.5\)\ curl/7.54.0 --location --silent --head --request GET https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.10.4/osxfuse-3.10.4.dmg
Already downloaded: /Users/today/Library/Caches/Homebrew/downloads/a5fee26664be1070115bfdfb1169a177255c45b9782c48f9bcc16a4da12cae8c--osxfuse-3.10.4.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/today/Library/Caches/Homebrew/downloads/a5fee26664be1070115bfdfb1169a177255c45b9782c48f9bcc16a4da12cae8c--osxfuse-3.10.4.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/today/Library/Caches/Homebrew/downloads/a5fee26664be1070115bfdfb1169a177255c45b9782c48f9bcc16a4da12cae8c--osxfuse-3.10.4.dmg
==> /Users/today/Library/Caches/Homebrew/downloads/a5fee26664be1070115bfdfb1169a177255c45b9782c48f9bcc16a4da12cae8c--osxfuse-3.10.4.dmg is quarantined
==> Downloaded to -> /Users/today/Library/Caches/Homebrew/downloads/a5fee26664be1070115bfdfb1169a177255c45b9782c48f9bcc16a4da12cae8c--osxfuse-3.10.4.dmg
==> Verifying SHA-256 checksum for Cask 'osxfuse'.
hdiutil imageinfo -format /Users/today/Library/Caches/Homebrew/downloads/a5fee26664be1070115bfdfb1169a177255c45b9782c48f9bcc16a4da12cae8c--osxfuse-3.10.4.dmg
==> Installing Cask osxfuse
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/today/Library/Caches/Homebrew/downloads/a5fee26664be1070115bfdfb1169a177255c45b9782c48f9bcc16a4da12cae8c--osxfuse-3.10.4.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/yd/c_jj32dx4ml1tzqtn5gc93x80000gp/T/d20200103-43449-1szgvw3 /Users/today/Library/Caches/Homebrew/downloads/a5fee26664be1070115bfdfb1169a177255c45b9782c48f9bcc16a4da12cae8c--osxfuse-3.10.4.dmg
find . -print0
mkbom -s -i /var/folders/yd/c_jj32dx4ml1tzqtn5gc93x80000gp/T/20200103-43449-lt8jvf.list -- /var/folders/yd/c_jj32dx4ml1tzqtn5gc93x80000gp/T/20200103-43449-1ilredn.bom
ditto --bom /var/folders/yd/c_jj32dx4ml1tzqtn5gc93x80000gp/T/20200103-43449-1ilredn.bom -- /private/var/folders/yd/c_jj32dx4ml1tzqtn5gc93x80000gp/T/d20200103-43449-1szgvw3/dmg.2QwEKn /var/folders/yd/c_jj32dx4ml1tzqtn5gc93x80000gp/T/d20200103-43449-v139vm
diskutil eject /private/var/folders/yd/c_jj32dx4ml1tzqtn5gc93x80000gp/T/d20200103-43449-1szgvw3/dmg.2QwEKn
cp -pR /var/folders/yd/c_jj32dx4ml1tzqtn5gc93x80000gp/T/d20200103-43449-v139vm/.engine_install /usr/local/Caskroom/osxfuse/3.10.4/.engine_install
cp -pR /var/folders/yd/c_jj32dx4ml1tzqtn5gc93x80000gp/T/d20200103-43449-v139vm/FUSE\ for\ macOS.pkg /usr/local/Caskroom/osxfuse/3.10.4/FUSE\ for\ macOS.pkg
cp -pR /var/folders/yd/c_jj32dx4ml1tzqtn5gc93x80000gp/T/d20200103-43449-v139vm/License.rtf /usr/local/Caskroom/osxfuse/3.10.4/License.rtf
cp -pR /var/folders/yd/c_jj32dx4ml1tzqtn5gc93x80000gp/T/d20200103-43449-v139vm/.Background/. /usr/local/Caskroom/osxfuse/3.10.4/.Background
cp -pR /var/folders/yd/c_jj32dx4ml1tzqtn5gc93x80000gp/T/d20200103-43449-v139vm/Extras/. /usr/local/Caskroom/osxfuse/3.10.4/Extras
chmod -Rf +w /var/folders/yd/c_jj32dx4ml1tzqtn5gc93x80000gp/T/d20200103-43449-v139vm
==> Verifying Gatekeeper status of /Users/today/Library/Caches/Homebrew/downloads/a5fee26664be1070115bfdfb1169a177255c45b9782c48f9bcc16a4da12cae8c--osxfuse-3.10.4.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/today/Library/Caches/Homebrew/downloads/a5fee26664be1070115bfdfb1169a177255c45b9782c48f9bcc16a4da12cae8c--osxfuse-3.10.4.dmg
==> /Users/today/Library/Caches/Homebrew/downloads/a5fee26664be1070115bfdfb1169a177255c45b9782c48f9bcc16a4da12cae8c--osxfuse-3.10.4.dmg is quarantined
==> Propagating quarantine from /Users/today/Library/Caches/Homebrew/downloads/a5fee26664be1070115bfdfb1169a177255c45b9782c48f9bcc16a4da12cae8c--osxfuse-3.10.4.dmg to /usr/local/Caskroom/osxfuse/3.10.4
/usr/bin/xattr -p com.apple.quarantine /Users/today/Library/Caches/Homebrew/downloads/a5fee26664be1070115bfdfb1169a177255c45b9782c48f9bcc16a4da12cae8c--osxfuse-3.10.4.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5e0ee018\;Homebrew\\x20Cask\;5A3B6910-0274-43FF-A0F1-968C8440DEE8
==> Creating metadata directory /usr/local/Caskroom/osxfuse/.metadata/3.10.4/20200103071625.184.
==> Creating metadata subdirectory /usr/local/Caskroom/osxfuse/.metadata/3.10.4/20200103071625.184/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007ff1c617ada8 @cask=#<Cask::Cask:0x00007ff1c611b7e0 @token="osxfuse", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/osxfuse.rb>, @tap=#<Tap:0x00007ff1c60a3420 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007ff1c611b678@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/osxfuse.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/osxfuse>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/osxfuse/.metadata>, @config=#<Cask::Config:0x00007ff1c616a340 @explicit={}>, @dsl=#<Cask::DSL:0x00007ff1c616a098 @cask=#<Cask::Cask:0x00007ff1c611b7e0 ...>, @token="osxfuse", @version="3.10.4", @sha256="654da9e58b622e24d65ffb9f7180c50f518cfa8c07e48d883d6761dbcd11787c", @url=#<URL:0x00007ff1c6169918 @uri=#<URI::HTTPS https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.10.4/osxfuse-3.10.4.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007ff1c6169378 @uri=#<URI::HTTPS https://github.com/osxfuse/osxfuse/releases.atom>, @parameters={}>, @name=["OSXFUSE"], @homepage="https://osxfuse.github.io/", @auto_updates=true, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/osxfuse/3.10.4>, @caveats=#<Cask::DSL::Caveats:0x00007ff1c617a9c0 @cask=#<Cask::Cask:0x00007ff1c611b7e0 ...>, @command=SystemCommand, @built_in_caveats={[:kext]=>"To install and/or use osxfuse you may need to enable its kernel extension in:\n  System Preferences → Security & Privacy → General\nFor more information refer to vendor documentation or this Apple Technical Note:\n  \e[4mhttps://developer.apple.com/library/content/technotes/tn2459/_index.html\e[24m\n", [:reboot]=>"You must reboot for the installation of osxfuse to take effect.\n"}, @custom_caveats=[]>, @language=nil>>, @directives={:pkgutil=>["com.github.osxfuse.pkg.Core", "com.github.osxfuse.pkg.MacFUSE", "com.github.osxfuse.pkg.PrefPane"], :kext=>"com.github.osxfuse.filesystems.osxfusefs", :signal=>[]}>, #<Cask::Artifact::Pkg:0x00007ff1c61687e8 @cask=#<Cask::Cask:0x00007ff1c611b7e0 @token="osxfuse", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/osxfuse.rb>, @tap=#<Tap:0x00007ff1c60a3420 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007ff1c611b678@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/osxfuse.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/osxfuse>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/osxfuse/.metadata>, @config=#<Cask::Config:0x00007ff1c616a340 @explicit={}>, @dsl=#<Cask::DSL:0x00007ff1c616a098 @cask=#<Cask::Cask:0x00007ff1c611b7e0 ...>, @token="osxfuse", @version="3.10.4", @sha256="654da9e58b622e24d65ffb9f7180c50f518cfa8c07e48d883d6761dbcd11787c", @url=#<URL:0x00007ff1c6169918 @uri=#<URI::HTTPS https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.10.4/osxfuse-3.10.4.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007ff1c6169378 @uri=#<URI::HTTPS https://github.com/osxfuse/osxfuse/releases.atom>, @parameters={}>, @name=["OSXFUSE"], @homepage="https://osxfuse.github.io/", @auto_updates=true, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/osxfuse/3.10.4>, @caveats=#<Cask::DSL::Caveats:0x00007ff1c617a9c0 @cask=#<Cask::Cask:0x00007ff1c611b7e0 ...>, @command=SystemCommand, @built_in_caveats={[:kext]=>"To install and/or use osxfuse you may need to enable its kernel extension in:\n  System Preferences → Security & Privacy → General\nFor more information refer to vendor documentation or this Apple Technical Note:\n  \e[4mhttps://developer.apple.com/library/content/technotes/tn2459/_index.html\e[24m\n", [:reboot]=>"You must reboot for the installation of osxfuse to take effect.\n"}, @custom_caveats=[]>, @language=nil>>, @path=#<Pathname:/usr/local/Caskroom/osxfuse/3.10.4/Extras/FUSE for macOS 3.10.4.pkg>, @stanza_options={}>, #<Cask::Artifact::PostflightBlock:0x00007ff1c617b3c0 @cask=#<Cask::Cask:0x00007ff1c611b7e0 @token="osxfuse", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/osxfuse.rb>, @tap=#<Tap:0x00007ff1c60a3420 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007ff1c611b678@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/osxfuse.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/osxfuse>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/osxfuse/.metadata>, @config=#<Cask::Config:0x00007ff1c616a340 @explicit={}>, @dsl=#<Cask::DSL:0x00007ff1c616a098 @cask=#<Cask::Cask:0x00007ff1c611b7e0 ...>, @token="osxfuse", @version="3.10.4", @sha256="654da9e58b622e24d65ffb9f7180c50f518cfa8c07e48d883d6761dbcd11787c", @url=#<URL:0x00007ff1c6169918 @uri=#<URI::HTTPS https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.10.4/osxfuse-3.10.4.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007ff1c6169378 @uri=#<URI::HTTPS https://github.com/osxfuse/osxfuse/releases.atom>, @parameters={}>, @name=["OSXFUSE"], @homepage="https://osxfuse.github.io/", @auto_updates=true, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/osxfuse/3.10.4>, @caveats=#<Cask::DSL::Caveats:0x00007ff1c617a9c0 @cask=#<Cask::Cask:0x00007ff1c611b7e0 ...>, @command=SystemCommand, @built_in_caveats={[:kext]=>"To install and/or use osxfuse you may need to enable its kernel extension in:\n  System Preferences → Security & Privacy → General\nFor more information refer to vendor documentation or this Apple Technical Note:\n  \e[4mhttps://developer.apple.com/library/content/technotes/tn2459/_index.html\e[24m\n", [:reboot]=>"You must reboot for the installation of osxfuse to take effect.\n"}, @custom_caveats=[]>, @language=nil>>, @directives={:postflight=>#<Proc:0x00007ff1c617b4b0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/osxfuse.rb:15>}>}>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for osxfuse; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- /usr/bin/env LOGNAME=today USER=today USERNAME=today /usr/sbin/installer -pkg /usr/local/Caskroom/osxfuse/3.10.4/Extras/FUSE\ for\ macOS\ 3.10.4.pkg -target / -verboseR
Password:
installer: Package name is FUSE for macOS
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing FUSE for macOS…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%2.229250
installer:PHASE:Validating packages…
installer:%97.750000
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 3.10.4 of Cask osxfuse
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=today USER=today USERNAME=today /usr/sbin/installer -pkg /usr/local/Caskroom/osxfuse/3.10.4/Extras/FUSE\ for\ macOS\ 3.10.4.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is FUSE for macOS
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing FUSE for macOS…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%2.229250
installer:PHASE:Validating packages…
installer:%97.750000
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.2-50-gc0b9167
==> macOS
10.14.5
==> SIP
Enabled
==> Java
1.8.0_222
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3498 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (160 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (940 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (139 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.37.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.78.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.6.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.30.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.19.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/nokogiri-1.10.7
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.22.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/json-2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
vitorgalvao/tiny-scripts
```

**Comment by vitorgalvao** [comment]
Have you tried installing it manually? Did it succeed?

**Comment by yanan-xu** [comment]
I just tried manually installing, it hung on `Validating packages` for 1 hour, then I stopped it.

**Comment by vitorgalvao** [comment]
Then it’s either an issue with osxfuse or (how it interacts with) your setup. Please report that upstream.
