### ISSUE TITLE
“X” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by guandalf** [Homebrew/homebrew-cask#75296]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Trying to install burp suite quits unsuccessfully with:
“Burp Suite Community Edition Installer” can’t be opened because Apple cannot check it for malicious software.

#### Command that failed

```
brew cask install burp-suite
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://portswigger.net/burp/releases/download?product=community&version=2.1.07&type=macosx
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.2-65-gbcb8f4d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.2\)\ curl/7.64.1 --location --silent --head --request GET https://portswigger.net/burp/releases/download\?product=community\&version=2.1.07\&type=macosx
Already downloaded: /Users/guandalf/Library/Caches/Homebrew/downloads/b0e620fb88cfc86361ad2a43b07a6091dc447a14d10682a27ccf9290fb6455b3--burpsuite_community_macos_v2_1_07.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/guandalf/Library/Caches/Homebrew/downloads/b0e620fb88cfc86361ad2a43b07a6091dc447a14d10682a27ccf9290fb6455b3--burpsuite_community_macos_v2_1_07.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/guandalf/Library/Caches/Homebrew/downloads/b0e620fb88cfc86361ad2a43b07a6091dc447a14d10682a27ccf9290fb6455b3--burpsuite_community_macos_v2_1_07.dmg
==> /Users/guandalf/Library/Caches/Homebrew/downloads/b0e620fb88cfc86361ad2a43b07a6091dc447a14d10682a27ccf9290fb6455b3--burpsuite_community_macos_v2_1_07.dmg is quarantined
==> Downloaded to -> /Users/guandalf/Library/Caches/Homebrew/downloads/b0e620fb88cfc86361ad2a43b07a6091dc447a14d10682a27ccf9290fb6455b3--burpsuite_community_macos_v2_1_07.dmg
==> Verifying SHA-256 checksum for Cask 'burp-suite'.
hdiutil imageinfo -format /Users/guandalf/Library/Caches/Homebrew/downloads/b0e620fb88cfc86361ad2a43b07a6091dc447a14d10682a27ccf9290fb6455b3--burpsuite_community_macos_v2_1_07.dmg
==> Installing Cask burp-suite
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/guandalf/Library/Caches/Homebrew/downloads/b0e620fb88cfc86361ad2a43b07a6091dc447a14d10682a27ccf9290fb6455b3--burpsuite_community_macos_v2_1_07.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/mb/nxlbj61n2sdgg8tvr_yc45b40000gn/T/d20200109-12285-1tl0n8k /Users/guandalf/Library/Caches/Homebrew/downloads/b0e620fb88cfc86361ad2a43b07a6091dc447a14d10682a27ccf9290fb6455b3--burpsuite_community_macos_v2_1_07.dmg
find . -print0
mkbom -s -i /var/folders/mb/nxlbj61n2sdgg8tvr_yc45b40000gn/T/20200109-12285-1axuh0p.list -- /var/folders/mb/nxlbj61n2sdgg8tvr_yc45b40000gn/T/20200109-12285-1f7cbxb.bom
ditto --bom /var/folders/mb/nxlbj61n2sdgg8tvr_yc45b40000gn/T/20200109-12285-1f7cbxb.bom -- /private/var/folders/mb/nxlbj61n2sdgg8tvr_yc45b40000gn/T/d20200109-12285-1tl0n8k/dmg.QCZT8w /var/folders/mb/nxlbj61n2sdgg8tvr_yc45b40000gn/T/d20200109-12285-ems6tz
diskutil eject /private/var/folders/mb/nxlbj61n2sdgg8tvr_yc45b40000gn/T/d20200109-12285-1tl0n8k/dmg.QCZT8w
cp -pR /var/folders/mb/nxlbj61n2sdgg8tvr_yc45b40000gn/T/d20200109-12285-ems6tz/Burp\ Suite\ Community\ Edition\ Installer.app/. /usr/local/Caskroom/burp-suite/2.1.07/Burp\ Suite\ Community\ Edition\ Installer.app
chmod -Rf +w /var/folders/mb/nxlbj61n2sdgg8tvr_yc45b40000gn/T/d20200109-12285-ems6tz
==> Verifying Gatekeeper status of /Users/guandalf/Library/Caches/Homebrew/downloads/b0e620fb88cfc86361ad2a43b07a6091dc447a14d10682a27ccf9290fb6455b3--burpsuite_community_macos_v2_1_07.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/guandalf/Library/Caches/Homebrew/downloads/b0e620fb88cfc86361ad2a43b07a6091dc447a14d10682a27ccf9290fb6455b3--burpsuite_community_macos_v2_1_07.dmg
==> /Users/guandalf/Library/Caches/Homebrew/downloads/b0e620fb88cfc86361ad2a43b07a6091dc447a14d10682a27ccf9290fb6455b3--burpsuite_community_macos_v2_1_07.dmg is quarantined
==> Propagating quarantine from /Users/guandalf/Library/Caches/Homebrew/downloads/b0e620fb88cfc86361ad2a43b07a6091dc447a14d10682a27ccf9290fb6455b3--burpsuite_community_macos_v2_1_07.dmg to /usr/local/Caskroom/burp-suite/2.1.07
/usr/bin/xattr -p com.apple.quarantine /Users/guandalf/Library/Caches/Homebrew/downloads/b0e620fb88cfc86361ad2a43b07a6091dc447a14d10682a27ccf9290fb6455b3--burpsuite_community_macos_v2_1_07.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5e171ca2\;Homebrew\\x20Cask\;0B9C486A-2BE6-4178-A5E5-A80287EE7DD9
==> Creating metadata directory /usr/local/Caskroom/burp-suite/.metadata/2.1.07/20200109124759.620.
==> Creating metadata subdirectory /usr/local/Caskroom/burp-suite/.metadata/2.1.07/20200109124759.620/Casks.
==> Installing artifacts
==> 4 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fdb3fa751a8 @cask=#<Cask::Cask:0x00007fdb3d9fea50 @token="burp-suite", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/burp-suite.rb>, @tap=#<Tap:0x00007fdb3d9d78d8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fdb3d9fe960@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/burp-suite.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/burp-suite>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/burp-suite/.metadata>, @config=#<Cask::Config:0x00007fdb3fa767d8 @explicit={}>, @dsl=#<Cask::DSL:0x00007fdb3fa76670 @cask=#<Cask::Cask:0x00007fdb3d9fea50 ...>, @token="burp-suite", @version="2.1.07", @sha256="6212892e0a775d04514401449dec0eb18c96c92d5ae1ea5a2e00160be0af1299", @url=#<URL:0x00007fdb3fa76300 @uri=#<URI::HTTPS https://portswigger.net/burp/releases/download?product=community&version=2.1.07&type=macosx>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fdb3fa75f68 @uri=#<URI::HTTPS https://portswigger.net/burp/communitydownload>, @parameters={}>, @name=["Burp Suite"], @homepage="https://portswigger.net/burp/", @artifacts=#<SortedSet: {...}>, @language=nil>>, @directives={:delete=>"/Applications/Burp Suite Community Edition.app", :signal=>[]}>, #<Cask::Artifact::Installer:0x00007fdb3fa757c0 @cask=#<Cask::Cask:0x00007fdb3d9fea50 @token="burp-suite", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/burp-suite.rb>, @tap=#<Tap:0x00007fdb3d9d78d8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fdb3d9fe960@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/burp-suite.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/burp-suite>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/burp-suite/.metadata>, @config=#<Cask::Config:0x00007fdb3fa767d8 @explicit={}>, @dsl=#<Cask::DSL:0x00007fdb3fa76670 @cask=#<Cask::Cask:0x00007fdb3d9fea50 ...>, @token="burp-suite", @version="2.1.07", @sha256="6212892e0a775d04514401449dec0eb18c96c92d5ae1ea5a2e00160be0af1299", @url=#<URL:0x00007fdb3fa76300 @uri=#<URI::HTTPS https://portswigger.net/burp/releases/download?product=community&version=2.1.07&type=macosx>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fdb3fa75f68 @uri=#<URI::HTTPS https://portswigger.net/burp/communitydownload>, @parameters={}>, @name=["Burp Suite"], @homepage="https://portswigger.net/burp/", @artifacts=#<SortedSet: {...}>, @language=nil>>, @args={:must_succeed=>true, :sudo=>true, :args=>["-q"], :print_stdout=>true}, @path=#<Pathname:Burp Suite Community Edition Installer.app/Contents/MacOS/JavaApplicationStub>>, #<Cask::Artifact::PostflightBlock:0x00007fdb3fa75478 @cask=#<Cask::Cask:0x00007fdb3d9fea50 @token="burp-suite", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/burp-suite.rb>, @tap=#<Tap:0x00007fdb3d9d78d8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fdb3d9fe960@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/burp-suite.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/burp-suite>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/burp-suite/.metadata>, @config=#<Cask::Config:0x00007fdb3fa767d8 @explicit={}>, @dsl=#<Cask::DSL:0x00007fdb3fa76670 @cask=#<Cask::Cask:0x00007fdb3d9fea50 ...>, @token="burp-suite", @version="2.1.07", @sha256="6212892e0a775d04514401449dec0eb18c96c92d5ae1ea5a2e00160be0af1299", @url=#<URL:0x00007fdb3fa76300 @uri=#<URI::HTTPS https://portswigger.net/burp/releases/download?product=community&version=2.1.07&type=macosx>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fdb3fa75f68 @uri=#<URI::HTTPS https://portswigger.net/burp/communitydownload>, @parameters={}>, @name=["Burp Suite"], @homepage="https://portswigger.net/burp/", @artifacts=#<SortedSet: {...}>, @language=nil>>, @directives={:postflight=>#<Proc:0x00007fdb3fa754c8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/burp-suite.rb:16>}>, #<Cask::Artifact::Zap:0x00007fdb3fa74cf8 @cask=#<Cask::Cask:0x00007fdb3d9fea50 @token="burp-suite", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/burp-suite.rb>, @tap=#<Tap:0x00007fdb3d9d78d8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fdb3d9fe960@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/burp-suite.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/burp-suite>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/burp-suite/.metadata>, @config=#<Cask::Config:0x00007fdb3fa767d8 @explicit={}>, @dsl=#<Cask::DSL:0x00007fdb3fa76670 @cask=#<Cask::Cask:0x00007fdb3d9fea50 ...>, @token="burp-suite", @version="2.1.07", @sha256="6212892e0a775d04514401449dec0eb18c96c92d5ae1ea5a2e00160be0af1299", @url=#<URL:0x00007fdb3fa76300 @uri=#<URI::HTTPS https://portswigger.net/burp/releases/download?product=community&version=2.1.07&type=macosx>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fdb3fa75f68 @uri=#<URI::HTTPS https://portswigger.net/burp/communitydownload>, @parameters={}>, @name=["Burp Suite"], @homepage="https://portswigger.net/burp/", @artifacts=#<SortedSet: {...}>, @language=nil>>, @directives={:trash=>"~/.BurpSuite", :signal=>[]}>}>
==> Installing artifact of class Cask::Artifact::Installer
==> Running installer script 'Burp Suite Community Edition Installer.app/Contents/MacOS/JavaApplicationStub'
/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/burp-suite/2.1.07/Burp\ Suite\ Community\ Edition\ Installer.app/Contents/MacOS/JavaApplicationStub -q
==> Purging files for version 2.1.07 of Cask burp-suite
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/burp-suite/2.1.07/Burp\ Suite\ Community\ Edition\ Installer.app/Contents/MacOS/JavaApplicationStub -q` exited with .
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/installer.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.2-65-gbcb8f4d
==> macOS
10.15.2
==> SIP
Enabled
==> Java
1.8.0_232
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3504 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (160 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (940 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (140 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.37.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.79.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.7.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.30.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.19.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/nokogiri-1.10.7
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.23.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../../../../../../../../Library/Ruby/Gems/2.6.0/gems/sync-0.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/json-2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
heroku/brew
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
vitorgalvao/tiny-scripts
```

**Comment by guandalf** [comment]
Same issue is on manual installation.

**Comment by corporate-gadfly** [comment]
Just curious, if this is a candidate for reopening? During manual install, I'm able to proceed by pressing "Open anyway".
<img width="675" alt="image" src="https://user-images.githubusercontent.com/1200537/73761467-e7282880-473c-11ea-9879-a89e3eb8052d.png">

**Comment by vitorgalvao** [comment]
> Just curious, if this is a candidate for reopening?

No. This is not an issue with Homebrew Cask.
