### ISSUE TITLE
microsoft-azure-storage-explorer: Error installing 

### ISSUE THREAD

**Issue by pauldaustin** [Homebrew/homebrew-cask#76525]
#### General troubleshooting steps

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Error installing microsoft-azure-storage-explorer

#### Command that failed

```
brew cask install --force --verbose --debug  microsoft-azure-storage-explorer
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://download.microsoft.com/download/A/E/3/AE32C485-B62B-4437-92F7-8B6B2C48CB40/StorageExplorer_signed.zip
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.4\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.2\)\ curl/7.64.1 --location --silent --head --request GET https://download.microsoft.com/download/A/E/3/AE32C485-B62B-4437-92F7-8B6B2C48CB40/StorageExplorer_signed.zip
Already downloaded: /Users/paustin/Library/Caches/Homebrew/downloads/82e8d0c920ce3bc4988fe8ba2334acb0c3cab97417807b7d97c7183b98904e07--StorageExplorer_signed.zip
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/paustin/Library/Caches/Homebrew/downloads/82e8d0c920ce3bc4988fe8ba2334acb0c3cab97417807b7d97c7183b98904e07--StorageExplorer_signed.zip
/usr/bin/xattr -p com.apple.quarantine /Users/paustin/Library/Caches/Homebrew/downloads/82e8d0c920ce3bc4988fe8ba2334acb0c3cab97417807b7d97c7183b98904e07--StorageExplorer_signed.zip
==> /Users/paustin/Library/Caches/Homebrew/downloads/82e8d0c920ce3bc4988fe8ba2334acb0c3cab97417807b7d97c7183b98904e07--StorageExplorer_signed.zip is quarantined
==> Downloaded to -> /Users/paustin/Library/Caches/Homebrew/downloads/82e8d0c920ce3bc4988fe8ba2334acb0c3cab97417807b7d97c7183b98904e07--StorageExplorer_signed.zip
==> No SHA-256 checksum defined for Cask 'microsoft-azure-storage-explorer', skipping verification.
zipinfo -1 /Users/paustin/Library/Caches/Homebrew/downloads/82e8d0c920ce3bc4988fe8ba2334acb0c3cab97417807b7d97c7183b98904e07--StorageExplorer_signed.zip
==> Installing Cask microsoft-azure-storage-explorer
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/paustin/Library/Caches/Homebrew/downloads/82e8d0c920ce3bc4988fe8ba2334acb0c3cab97417807b7d97c7183b98904e07--StorageExplorer_signed.zip
zipinfo -1 /Users/paustin/Library/Caches/Homebrew/downloads/82e8d0c920ce3bc4988fe8ba2334acb0c3cab97417807b7d97c7183b98904e07--StorageExplorer_signed.zip
unzip -o /Users/paustin/Library/Caches/Homebrew/downloads/82e8d0c920ce3bc4988fe8ba2334acb0c3cab97417807b7d97c7183b98904e07--StorageExplorer_signed.zip -d /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul
cp -pR /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft\ Azure\ Storage\ Explorer.app/. /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft\ Azure\ Storage\ Explorer.app
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Electron Framework.framework/Resources with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Electron Framework.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Electron Framework.framework/Versions/Current with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Electron Framework.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Electron Framework.framework/Libraries with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Electron Framework.framework/Libraries
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Resources with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Versions/Current with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Headers with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Headers
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Modules with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Modules
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Resources with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Versions/Current with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Headers with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Headers
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Modules with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Modules
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Resources with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Versions/Current with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Headers with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Headers
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Modules with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Modules
==> Purging files for version latest of Cask microsoft-azure-storage-explorer
Error: Failure while executing; `cp -pR /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft\ Azure\ Storage\ Explorer.app/. /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft\ Azure\ Storage\ Explorer.app` exited with 1. Here's the output:
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Electron Framework.framework/Resources with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Electron Framework.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Electron Framework.framework/Versions/Current with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Electron Framework.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Electron Framework.framework/Libraries with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Electron Framework.framework/Libraries
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Resources with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Versions/Current with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Headers with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Headers
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Modules with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Squirrel.framework/Modules
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Resources with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Versions/Current with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Headers with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Headers
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Modules with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/ReactiveCocoa.framework/Modules
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Resources with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Versions/Current with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Headers with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Headers
cp: cannot overwrite directory /usr/local/Caskroom/microsoft-azure-storage-explorer/latest/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Modules with non-directory /var/folders/ch/kvz5zdk5405dp7lhznkfwtf00000gn/T/d20200201-3879-bf0qul/Microsoft Azure Storage Explorer.app/./Contents/Frameworks/Mantle.framework/Modules

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:19:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/directory.rb:21:in `block in extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/directory.rb:20:in `each'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/directory.rb:20:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:123:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:143:in `block in extract_nestedly'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:127:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:193:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:73:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.4
==> macOS
10.15.2
==> SIP
Enabled
==> Java
11.0.5, 1.8.0_242
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3521 casks)
/usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk (26 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.37.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.79.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.7.0.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.30.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.19.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/nokogiri-1.10.7
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.24.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../../../../../../../../Library/Ruby/Gems/2.6.0/gems/sync-0.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/json-2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
adoptopenjdk/openjdk
homebrew/cask
homebrew/core
homebrew/services
openresty/brew
openresty/nginx
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/76695
