### ISSUE TITLE
failed to install veracrypt

### ISSUE THREAD

**Issue by MartinP7r** [Homebrew/homebrew-cask#76798]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

failed to install cask veracrypt

#### Command that failed

```
brew cask install veracrypt
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://launchpad.net/veracrypt/trunk/1.24-update4/+download/VeraCrypt_1.24-Update4.dmg
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.5-28-gb8c2e96\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.2\)\ curl/7.64.1 --location --silent --head --request GET https://launchpad.net/veracrypt/trunk/1.24-update4/\+download/VeraCrypt_1.24-Update4.dmg
Already downloaded: /Users/cyrus/Library/Caches/Homebrew/downloads/e2e772e3ff914e6da10346af31541106f84a1ed57d67a051a5570804c70e0cd9--VeraCrypt_1.24-Update4.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/cyrus/Library/Caches/Homebrew/downloads/e2e772e3ff914e6da10346af31541106f84a1ed57d67a051a5570804c70e0cd9--VeraCrypt_1.24-Update4.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/cyrus/Library/Caches/Homebrew/downloads/e2e772e3ff914e6da10346af31541106f84a1ed57d67a051a5570804c70e0cd9--VeraCrypt_1.24-Update4.dmg
==> /Users/cyrus/Library/Caches/Homebrew/downloads/e2e772e3ff914e6da10346af31541106f84a1ed57d67a051a5570804c70e0cd9--VeraCrypt_1.24-Update4.dmg is quarantined
==> Downloaded to -> /Users/cyrus/Library/Caches/Homebrew/downloads/e2e772e3ff914e6da10346af31541106f84a1ed57d67a051a5570804c70e0cd9--VeraCrypt_1.24-Update4.dmg
==> Verifying SHA-256 checksum for Cask 'veracrypt'.
hdiutil imageinfo -format /Users/cyrus/Library/Caches/Homebrew/downloads/e2e772e3ff914e6da10346af31541106f84a1ed57d67a051a5570804c70e0cd9--VeraCrypt_1.24-Update4.dmg
All Formula dependencies satisfied.
==> Installing Cask veracrypt
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/cyrus/Library/Caches/Homebrew/downloads/e2e772e3ff914e6da10346af31541106f84a1ed57d67a051a5570804c70e0cd9--VeraCrypt_1.24-Update4.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/dv/7qg2gxfn4ls4gz7grg72_xrc0000gn/T/d20200208-79554-16uvt1g /Users/cyrus/Library/Caches/Homebrew/downloads/e2e772e3ff914e6da10346af31541106f84a1ed57d67a051a5570804c70e0cd9--VeraCrypt_1.24-Update4.dmg
find . -print0
mkbom -s -i /var/folders/dv/7qg2gxfn4ls4gz7grg72_xrc0000gn/T/20200208-79554-whabb5.list -- /var/folders/dv/7qg2gxfn4ls4gz7grg72_xrc0000gn/T/20200208-79554-1vs0u2l.bom
ditto --bom /var/folders/dv/7qg2gxfn4ls4gz7grg72_xrc0000gn/T/20200208-79554-1vs0u2l.bom -- /private/var/folders/dv/7qg2gxfn4ls4gz7grg72_xrc0000gn/T/d20200208-79554-16uvt1g/dmg.FCsLs3 /var/folders/dv/7qg2gxfn4ls4gz7grg72_xrc0000gn/T/d20200208-79554-155dwwp
diskutil eject /private/var/folders/dv/7qg2gxfn4ls4gz7grg72_xrc0000gn/T/d20200208-79554-16uvt1g/dmg.FCsLs3
cp -pR /var/folders/dv/7qg2gxfn4ls4gz7grg72_xrc0000gn/T/d20200208-79554-155dwwp/.engine_install /usr/local/Caskroom/veracrypt/1.24-Update4/.engine_install
cp -pR /var/folders/dv/7qg2gxfn4ls4gz7grg72_xrc0000gn/T/d20200208-79554-155dwwp/VeraCrypt_Installer.pkg /usr/local/Caskroom/veracrypt/1.24-Update4/VeraCrypt_Installer.pkg
chmod -Rf +w /var/folders/dv/7qg2gxfn4ls4gz7grg72_xrc0000gn/T/d20200208-79554-155dwwp
==> Verifying Gatekeeper status of /Users/cyrus/Library/Caches/Homebrew/downloads/e2e772e3ff914e6da10346af31541106f84a1ed57d67a051a5570804c70e0cd9--VeraCrypt_1.24-Update4.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/cyrus/Library/Caches/Homebrew/downloads/e2e772e3ff914e6da10346af31541106f84a1ed57d67a051a5570804c70e0cd9--VeraCrypt_1.24-Update4.dmg
==> /Users/cyrus/Library/Caches/Homebrew/downloads/e2e772e3ff914e6da10346af31541106f84a1ed57d67a051a5570804c70e0cd9--VeraCrypt_1.24-Update4.dmg is quarantined
==> Propagating quarantine from /Users/cyrus/Library/Caches/Homebrew/downloads/e2e772e3ff914e6da10346af31541106f84a1ed57d67a051a5570804c70e0cd9--VeraCrypt_1.24-Update4.dmg to /usr/local/Caskroom/veracrypt/1.24-Update4
/usr/bin/xattr -p com.apple.quarantine /Users/cyrus/Library/Caches/Homebrew/downloads/e2e772e3ff914e6da10346af31541106f84a1ed57d67a051a5570804c70e0cd9--VeraCrypt_1.24-Update4.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5e3e3d0e\;Homebrew\\x20Cask\;661AF82A-20EC-4E85-B860-C5C1F9A6597C
==> Creating metadata directory /usr/local/Caskroom/veracrypt/.metadata/1.24-Update4/20200208054332.128.
==> Creating metadata subdirectory /usr/local/Caskroom/veracrypt/.metadata/1.24-Update4/20200208054332.128/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fb78c9028d8 @cask=#<Cask::Cask:0x00007fb78d11c1b8 @token="veracrypt", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/veracrypt.rb>, @tap=#<Tap:0x00007fb78b95fcc8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fb78c883b78@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/veracrypt.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/veracrypt>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/veracrypt/.metadata>, @config=#<Cask::Config:0x00007fb78d2162a8 @explicit={}>, @dsl=#<Cask::DSL:0x00007fb78d216078 @cask=#<Cask::Cask:0x00007fb78d11c1b8 ...>, @token="veracrypt", @version="1.24-Update4", @sha256="e84d3836d46612783248bb70225791374b7c3b68e32d1171159ed4dcf1fd3624", @url=#<URL:0x00007fb78d215b28 @uri=#<URI::HTTPS https://launchpad.net/veracrypt/trunk/1.24-update4/+download/VeraCrypt_1.24-Update4.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fb78d215010 @uri=#<URI::HTTPS https://github.com/veracrypt/VeraCrypt/releases.atom>, @parameters={}>, @name=["VeraCrypt"], @homepage="https://www.veracrypt.fr/", @depends_on={:cask=>["osxfuse"]}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/veracrypt/1.24-Update4>, @language=nil>>, @directives={:pkgutil=>"com.idrix.pkg.veracrypt", :signal=>[]}>, #<Cask::Artifact::Pkg:0x00007fb78c903eb8 @cask=#<Cask::Cask:0x00007fb78d11c1b8 @token="veracrypt", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/veracrypt.rb>, @tap=#<Tap:0x00007fb78b95fcc8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fb78c883b78@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/veracrypt.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/veracrypt>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/veracrypt/.metadata>, @config=#<Cask::Config:0x00007fb78d2162a8 @explicit={}>, @dsl=#<Cask::DSL:0x00007fb78d216078 @cask=#<Cask::Cask:0x00007fb78d11c1b8 ...>, @token="veracrypt", @version="1.24-Update4", @sha256="e84d3836d46612783248bb70225791374b7c3b68e32d1171159ed4dcf1fd3624", @url=#<URL:0x00007fb78d215b28 @uri=#<URI::HTTPS https://launchpad.net/veracrypt/trunk/1.24-update4/+download/VeraCrypt_1.24-Update4.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fb78d215010 @uri=#<URI::HTTPS https://github.com/veracrypt/VeraCrypt/releases.atom>, @parameters={}>, @name=["VeraCrypt"], @homepage="https://www.veracrypt.fr/", @depends_on={:cask=>["osxfuse"]}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/veracrypt/1.24-Update4>, @language=nil>>, @path=#<Pathname:/usr/local/Caskroom/veracrypt/1.24-Update4/VeraCrypt_Installer.pkg>, @stanza_options={}>}>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for veracrypt; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- /usr/bin/env LOGNAME=cyrus USER=cyrus USERNAME=cyrus /usr/sbin/installer -pkg /usr/local/Caskroom/veracrypt/1.24-Update4/VeraCrypt_Installer.pkg -target / -verboseR
Password:
installer: Error -
==> Purging files for version 1.24-Update4 of Cask veracrypt
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=cyrus USER=cyrus USERNAME=cyrus /usr/sbin/installer -pkg /usr/local/Caskroom/veracrypt/1.24-Update4/VeraCrypt_Installer.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Error -

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.5-28-gb8c2e96
==> macOS
10.15.2
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3526 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (163 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (945 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.37.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.79.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.7.0.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.30.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.19.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/nokogiri-1.10.7
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.24.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../../../../../../../../Library/Ruby/Gems/2.6.0/gems/sync-0.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/json-2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
buo/cask-upgrade
domt4/autoupdate
heroku/brew
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
vapor/tap
```

**Comment by vitorgalvao** [comment]
Have you tried running their installer manually?

**Comment by MartinP7r** [comment]
Sorry to keep you waiting. I did and I researched some more and found that my fuse installation was broken. After reinstalling FUSE, VeraCrypt also worked via homebrew.
