### ISSUE TITLE
SUDO_ASKPASS doesn't seem to work with brew cask (re)install

### ISSUE THREAD

**Issue by Cyberbeni** [Homebrew/homebrew-cask#77258]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

SUDO_ASKPASS doesn't seem to work with brew cask reinstall (it worked for installing home-brew in the same script)
in my main script, I use `export EXPORTED_PASSWORD=$PASSWORD`
and in my askpass file I simply `echo $EXPORTED_PASSWORD`

#### Command that failed

```
brew cask reinstall microsoft-edge
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#reinstall
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdge-80.0.361.54.pkg
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.6\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.3\)\ curl/7.64.1 --location --silent --head --request GET https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdge-80.0.361.54.pkg
Already downloaded: /Users/benedek.kozma/Library/Caches/Homebrew/downloads/8a2da77896bbdb5c02fee40b5800f078d8a7f34426e10272e84eb233fbaf372f--MicrosoftEdge-80.0.361.54.pkg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/benedek.kozma/Library/Caches/Homebrew/downloads/8a2da77896bbdb5c02fee40b5800f078d8a7f34426e10272e84eb233fbaf372f--MicrosoftEdge-80.0.361.54.pkg
/usr/bin/xattr -p com.apple.quarantine /Users/benedek.kozma/Library/Caches/Homebrew/downloads/8a2da77896bbdb5c02fee40b5800f078d8a7f34426e10272e84eb233fbaf372f--MicrosoftEdge-80.0.361.54.pkg
==> /Users/benedek.kozma/Library/Caches/Homebrew/downloads/8a2da77896bbdb5c02fee40b5800f078d8a7f34426e10272e84eb233fbaf372f--MicrosoftEdge-80.0.361.54.pkg is quarantined
==> Downloaded to -> /Users/benedek.kozma/Library/Caches/Homebrew/downloads/8a2da77896bbdb5c02fee40b5800f078d8a7f34426e10272e84eb233fbaf372f--MicrosoftEdge-80.0.361.54.pkg
==> Verifying SHA-256 checksum for Cask 'microsoft-edge'.
==> Installing Cask microsoft-edge
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Pkg for /Users/benedek.kozma/Library/Caches/Homebrew/downloads/8a2da77896bbdb5c02fee40b5800f078d8a7f34426e10272e84eb233fbaf372f--MicrosoftEdge-80.0.361.54.pkg
cp -p /Users/benedek.kozma/Library/Caches/Homebrew/downloads/8a2da77896bbdb5c02fee40b5800f078d8a7f34426e10272e84eb233fbaf372f--MicrosoftEdge-80.0.361.54.pkg /usr/local/Caskroom/microsoft-edge/80.0.361.54/MicrosoftEdge-80.0.361.54.pkg
==> Verifying Gatekeeper status of /Users/benedek.kozma/Library/Caches/Homebrew/downloads/8a2da77896bbdb5c02fee40b5800f078d8a7f34426e10272e84eb233fbaf372f--MicrosoftEdge-80.0.361.54.pkg
/usr/bin/xattr -p com.apple.quarantine /Users/benedek.kozma/Library/Caches/Homebrew/downloads/8a2da77896bbdb5c02fee40b5800f078d8a7f34426e10272e84eb233fbaf372f--MicrosoftEdge-80.0.361.54.pkg
==> /Users/benedek.kozma/Library/Caches/Homebrew/downloads/8a2da77896bbdb5c02fee40b5800f078d8a7f34426e10272e84eb233fbaf372f--MicrosoftEdge-80.0.361.54.pkg is quarantined
==> Propagating quarantine from /Users/benedek.kozma/Library/Caches/Homebrew/downloads/8a2da77896bbdb5c02fee40b5800f078d8a7f34426e10272e84eb233fbaf372f--MicrosoftEdge-80.0.361.54.pkg to /usr/local/Caskroom/microsoft-edge/80.0.361.54
/usr/bin/xattr -p com.apple.quarantine /Users/benedek.kozma/Library/Caches/Homebrew/downloads/8a2da77896bbdb5c02fee40b5800f078d8a7f34426e10272e84eb233fbaf372f--MicrosoftEdge-80.0.361.54.pkg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5e4b909a\;Homebrew\\x20Cask\;035DEF0D-A37C-4D83-9D75-8ED6E02421DB
==> Creating metadata directory /usr/local/Caskroom/microsoft-edge/.metadata/80.0.361.54/20200218114119.282.
==> Creating metadata subdirectory /usr/local/Caskroom/microsoft-edge/.metadata/80.0.361.54/20200218114119.282/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fdfca2a89b8 @cask=#<Cask::Cask:0x00007fdfca132c28 @token="microsoft-edge", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/microsoft-edge.rb>, @tap=#<Tap:0x00007fdfca9c1588 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fdfca132b10@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/microsoft-edge.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/microsoft-edge>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/microsoft-edge/.metadata>, @config=#<Cask::Config:0x00007fdfca2998f0 @explicit={}>, @dsl=#<Cask::DSL:0x00007fdfca2995a8 @cask=#<Cask::Cask:0x00007fdfca132c28 ...>, @token="microsoft-edge", @version="80.0.361.54", @sha256="c45b97fa4f470cb91b927835b69b0af7655dfc9f13bd8bd498648ea003cad797", @url=#<URL:0x00007fdfca299080 @uri=#<URI::HTTPS https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdge-80.0.361.54.pkg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fdfca298068 @uri=#<URI::HTTPS https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://go.microsoft.com/fwlink/?linkid=2069148>, @parameters={}>, @name=["Microsoft Edge"], @homepage="https://www.microsoft.com/edge", @auto_updates=true, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/microsoft-edge/80.0.361.54>, @language=nil>>, @directives={:pkgutil=>"com.microsoft.edgemac", :rmdir=>"/Library/Application Support/Microsoft", :signal=>[]}>, #<Cask::Artifact::Pkg:0x00007fdfca2aa790 @cask=#<Cask::Cask:0x00007fdfca132c28 @token="microsoft-edge", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/microsoft-edge.rb>, @tap=#<Tap:0x00007fdfca9c1588 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fdfca132b10@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/microsoft-edge.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/microsoft-edge>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/microsoft-edge/.metadata>, @config=#<Cask::Config:0x00007fdfca2998f0 @explicit={}>, @dsl=#<Cask::DSL:0x00007fdfca2995a8 @cask=#<Cask::Cask:0x00007fdfca132c28 ...>, @token="microsoft-edge", @version="80.0.361.54", @sha256="c45b97fa4f470cb91b927835b69b0af7655dfc9f13bd8bd498648ea003cad797", @url=#<URL:0x00007fdfca299080 @uri=#<URI::HTTPS https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdge-80.0.361.54.pkg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fdfca298068 @uri=#<URI::HTTPS https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://go.microsoft.com/fwlink/?linkid=2069148>, @parameters={}>, @name=["Microsoft Edge"], @homepage="https://www.microsoft.com/edge", @auto_updates=true, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/microsoft-edge/80.0.361.54>, @language=nil>>, @path=#<Pathname:/usr/local/Caskroom/microsoft-edge/80.0.361.54/MicrosoftEdge-80.0.361.54.pkg>, @stanza_options={}>, #<Cask::Artifact::Zap:0x00007fdfca2a82b0 @cask=#<Cask::Cask:0x00007fdfca132c28 @token="microsoft-edge", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/microsoft-edge.rb>, @tap=#<Tap:0x00007fdfca9c1588 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fdfca132b10@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/microsoft-edge.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/microsoft-edge>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/microsoft-edge/.metadata>, @config=#<Cask::Config:0x00007fdfca2998f0 @explicit={}>, @dsl=#<Cask::DSL:0x00007fdfca2995a8 @cask=#<Cask::Cask:0x00007fdfca132c28 ...>, @token="microsoft-edge", @version="80.0.361.54", @sha256="c45b97fa4f470cb91b927835b69b0af7655dfc9f13bd8bd498648ea003cad797", @url=#<URL:0x00007fdfca299080 @uri=#<URI::HTTPS https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdge-80.0.361.54.pkg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fdfca298068 @uri=#<URI::HTTPS https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://go.microsoft.com/fwlink/?linkid=2069148>, @parameters={}>, @name=["Microsoft Edge"], @homepage="https://www.microsoft.com/edge", @auto_updates=true, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/microsoft-edge/80.0.361.54>, @language=nil>>, @directives={:launchctl=>["com.microsoft.autoupdate.helper", "com.microsoft.update.agent"], :pkgutil=>"com.microsoft.package.Microsoft_AutoUpdate.app", :delete=>"/Library/PrivilegedHelperTools/com.microsoft.autoupdate.helper", :trash=>["~/Library/Preferences/com.microsoft.edgemac.plist", "/Library/Application Support/Microsoft", "~/Library/Application Support/Microsoft Edge"], :signal=>[]}>}>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for microsoft-edge; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -A -E -- /usr/bin/env LOGNAME=benedek.kozma USER=benedek.kozma USERNAME=benedek.kozma /usr/sbin/installer -pkg /usr/local/Caskroom/microsoft-edge/80.0.361.54/MicrosoftEdge-80.0.361.54.pkg -target / -verboseR
Sorry, try again.
Sorry, try again.
sudo: 3 incorrect password attempts
==> Purging files for version 80.0.361.54 of Cask microsoft-edge
Error: Failure while executing; `/usr/bin/sudo -A -E -- /usr/bin/env LOGNAME=benedek.kozma USER=benedek.kozma USERNAME=benedek.kozma /usr/sbin/installer -pkg /usr/local/Caskroom/microsoft-edge/80.0.361.54/MicrosoftEdge-80.0.361.54.pkg -target / -verboseR` exited with 1. Here's the output:
sudo: 3 incorrect password attempts

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:127:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:13:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:7:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:7:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.6
==> macOS
10.15.3
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3536 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (946 casks)
/usr/local/Homebrew/Library/Taps/cyberbeni/homebrew-brews (1 cask)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.38.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.79.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.7.0.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.31.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.19.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/nokogiri-1.10.8
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.24.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../../../../../../../../Library/Ruby/Gems/2.6.0/gems/sync-0.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/json-2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.14.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
cyberbeni/brews
homebrew/cask
homebrew/cask-fonts
homebrew/core
microsoft/mssql-release
mono0926/license-plist
```

**Comment by reitermarkus** [comment]
Maybe try `printf '%s' "$EXPORTED_PASSWORD"`?

**Comment by Cyberbeni** [comment]
The printf version needs a newline at the end or it will report "no password was provided" and it still reports the same "3 incorrect password attempts" with newline at the end

**Comment by Cyberbeni** [comment]
Executing `/usr/bin/sudo -A -E -- /usr/bin/env LOGNAME=benedek.kozma USER=benedek.kozma USERNAME=benedek.kozma /usr/sbin/installer -pkg /usr/local/Caskroom/microsoft-edge/80.0.361.54/MicrosoftEdge-80.0.361.54.pkg -target / -verboseR` with a different pkg path (inside my Downloads dir) manually works without a problem
brew cask (re)install fails on both my personal and my corporate Macs (both running the latest update of macOS Catalina), so it's probably reproducible

If I put this inside printpassword.sh
```
echo $PASSWORD | sudo -Skv -p "" > /dev/null 2>&1
echo "$EXPORTED_PASSWORD"
```
Then it will print 5 `Sorry, try again.`s and a `sudo: 3 incorrect password attempts`
But if I go for
```
echo $PASSWORD | sudo -Skv -u benedek.kozma -p "" > /dev/null 2>&1
echo "$EXPORTED_PASSWORD"
```
Then I only get the same 2 `Sorry, try again.`s as originally which makes me believe that it is asking for the wrong user's password.

And then if I don't specify SUDO_ASKPASS then the only change is that sudo won't have the -A flag but it will accept my password.

I guess this is also an issue for feedbackassistant.apple.com then?

**Comment by Cyberbeni** [comment]
Now that I installed it once, if I delete the app manually and run brew cask reinstall, it is failing at
```
==> Uninstalling packages:
com.microsoft.edgemac
Sorry, try again.
Sorry, try again.
sudo: 3 incorrect password attempts
Error: Failure while executing; `/usr/bin/sudo -A -E -- /usr/sbin/pkgutil --forget com.microsoft.edgemac` exited with 1. Here's the output:
sudo: 3 incorrect password attempts
```

If I put `echo `whoami` > /Users/Shared/who.txt` inside printpassword.sh, it puts the correct user inside the output file

**Comment by Cyberbeni** [comment]
Ah, the EXPORTED_PASSWORD env var gets cleared when running brew cask install, that's why I get incorrect password message, it just prints a newline

**Comment by reitermarkus** [comment]
Yeah, the environment is filtered. You should probably not store the password in a variable at all, that's the reason `SUDO_ASKPASS` exists in the first place. Take a look at how I do it: https://github.com/reitermarkus/dotfiles/blob/d72df6a7a1b4522e53391d81df4750c78ca02082/.sh#L59-L87

If you absolutely want to use a variable, you can prefix it with `HOMEBREW_` and it will be passed through.

**Comment by Cyberbeni** [comment]
Isn't having SUDO_ASKPASS unconditionally printing the password basically the same as having it in an env var? Storing it in the keychain just adds the possibility that it doesn't get cleaned up because of power outage or other unexpected event.

**Comment by reitermarkus** [comment]
You're right, I think it's mainly a deterrent to avoid using variables as command arguments. Either way, it's up to you where you want to store your password.

**Comment by vitorgalvao** [comment]
@reitermarkus You don’t need to store the `read` answer in a `P` variable. If you don’t give any variable name, the answer will be stored in an auto-generated `REPLY` variable.

For reference, here’s my method:

```bash
declare -rx SUDO_ASKPASS="$(
  script="$(mktemp).scpt"

  echo '#!/usr/bin/osascript
    return text returned of (display dialog "Insert your password" with title "Administrator password needed" default answer "" buttons {"Cancel", "OK"} default button "OK" with hidden answer)
  ' > "${script}"
  chmod 500 "${script}"

  echo "${script}"
)"
```

`declare -rx` marks `SUDO_ASKPASS` as both `readonly` and `export`, while `chmod 500` (equivalent to `chmod u=rx,g=,o=`) marks the script it creates as only readable and executable (not even writable) only by its owner.

When invoked, it’ll show a small GUI prompt (so it even works on background scripts) asking for your password.

**Comment by reitermarkus** [comment]
Thanks @vitorgalvao, didn't know about `REPLY`. https://github.com/reitermarkus/dotfiles/commit/3219808b4e8379057dcb3dde984d655c6d094ac8
