### ISSUE TITLE
Path-Finder.rb Checksum error what can I do it?

### ISSUE THREAD

**Issue by Andware** [Homebrew/homebrew-cask#77800]
I have problems with install Path-Finder. It is coming an Checksum error. How to update this?

#### General troubleshooting step
> brew cask install path-finder --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.6-54-ge88eea6\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.3\)\ curl/7.64.1 --location --silent --head --request GET https://get.cocoatech.com/PF9.dmg
==> Downloading https://get.cocoatech.com/PF9.dmg
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.6-54-ge88eea6\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.3\)\ curl/7.64.1 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://get.cocoatech.com/PF9.dmg
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.6-54-ge88eea6\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.3\)\ curl/7.64.1 --fail --progress-bar --location --remote-time --continue-at 0 --output /Users/itceanmu/Library/Caches/Homebrew/downloads/0e5d9c96445528326786025ac002135bce5bf11a66394d09165b6153c0d6ec6c--PF9.dmg.incomplete https://get.cocoatech.com/PF9.dmg
######################################################################## 100.0%
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/itceanmu/Library/Caches/Homebrew/downloads/0e5d9c96445528326786025ac002135bce5bf11a66394d09165b6153c0d6ec6c--PF9.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/itceanmu/Library/Caches/Homebrew/downloads/0e5d9c96445528326786025ac002135bce5bf11a66394d09165b6153c0d6ec6c--PF9.dmg
==> /Users/itceanmu/Library/Caches/Homebrew/downloads/0e5d9c96445528326786025ac002135bce5bf11a66394d09165b6153c0d6ec6c--PF9.dmg is not quarantined
==> Quarantining /Users/itceanmu/Library/Caches/Homebrew/downloads/0e5d9c96445528326786025ac002135bce5bf11a66394d09165b6153c0d6ec6c--PF9.dmg
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/itceanmu/Library/Caches/Homebrew/downloads/0e5d9c96445528326786025ac002135bce5bf11a66394d09165b6153c0d6ec6c--PF9.dmg https://get.cocoatech.com/PF9.dmg https://cocoatech.com/
==> Downloaded to -> /Users/itceanmu/Library/Caches/Homebrew/downloads/0e5d9c96445528326786025ac002135bce5bf11a66394d09165b6153c0d6ec6c--PF9.dmg
==> Verifying SHA-256 checksum for Cask 'path-finder'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'path-finder' does not match.
Expected: c4ecd744dec73f50bf28e3f1d0d816a7f63e6ef4d73d952638010e838066f746
  Actual: 982d42ab103cae693e5939ab4e9a0c83793a85b10a3e2dfb0f82f88f6a0f28b3
    File: /Users/itceanmu/Library/Caches/Homebrew/downloads/0e5d9c96445528326786025ac002135bce5bf11a66394d09165b6153c0d6ec6c--PF9.dmg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
/usr/local/Homebrew/Library/Homebrew/cask/verify.rb:23:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:165:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:63:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'s

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

{{replace this}}

#### Command that failed

```
{{replace this}}
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by Andware** [comment]
Thanks
