### ISSUE TITLE
Operation not permitted error when zapping Thunderbird

### ISSUE THREAD

**Issue by dkav** [Homebrew/homebrew-cask#78069]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Tried to zap Thunderbird. Failed with error:

`Error: Operation not permitted - /Users/dkav/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments`

#### Command that failed

```
brew cask zap thunderbird
```

#### Output of command with `--force --verbose --debug`

```
==> Zapping Cask thunderbird
==> Implied "brew cask uninstall thunderbird"
==> Uninstalling artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::App:0x00007faae1b25118 @cask=#<Cask::Cask:0x00007faae1a7fec0 @token="thunderbird", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb>, @tap=#<Tap:0x00007faae1a44e60 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007faae1a7fd80@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/thunderbird>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/thunderbird/.metadata>, @config=#<Cask::Config:0x00007faae1a7d170 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/dkav/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/dkav/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/dkav/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/dkav/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/dkav/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/dkav/Library/Services>, :input_methoddir=>#<Pathname:/Users/dkav/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/dkav/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/dkav/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/dkav/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/dkav/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/dkav/Library/Screen Savers>}, @env={}, @explicit={}>, @dsl=#<Cask::DSL:0x00007faae1a85f50 @cask=#<Cask::Cask:0x00007faae1a7fec0 ...>, @token="thunderbird", @version="68.5.0", @language_blocks={["cs"]=>#<Proc:0x00007faae1a85b18@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:4>, ["de"]=>#<Proc:0x00007faae1a85a50@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:9>, ["en-GB"]=>#<Proc:0x00007faae1a859d8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:14>, ["en"]=>#<Proc:0x00007faae1a858c0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:19>, ["fr"]=>#<Proc:0x00007faae1a85820@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:24>, ["gl"]=>#<Proc:0x00007faae1a856b8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:29>, ["it"]=>#<Proc:0x00007faae1a85578@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:34>, ["ja"]=>#<Proc:0x00007faae1a854d8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:39>, ["nl"]=>#<Proc:0x00007faae1a853e8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:44>, ["pl"]=>#<Proc:0x00007faae1a852f8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:49>, ["pt"]=>#<Proc:0x00007faae1a851b8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:54>, ["pt-BR"]=>#<Proc:0x00007faae1a85140@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:59>, ["ru"]=>#<Proc:0x00007faae1a850a0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:64>, ["uk"]=>#<Proc:0x00007faae1a85000@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:69>, ["zh-TW"]=>#<Proc:0x00007faae1a84f38@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:74>, ["zh"]=>#<Proc:0x00007faae1a84e70@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:79>}, @sha256="d720d164e5dc0cafdc8fb48452acc5ad394b0b0728d308171f3567fc5d06c403", @language="en-US", @url=#<URL:0x00007faae1af6d40 @uri=#<URI::HTTPS https://ftp.mozilla.org/pub/thunderbird/releases/68.5.0/mac/en-US/Thunderbird%2068.5.0.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007faae1af6340 @uri=#<URI::HTTPS https://www.thunderbird.net/en-US/thunderbird/releases/>, @parameters={}>, @name=["Mozilla Thunderbird"], @homepage="https://www.mozilla.org/thunderbird/", @auto_updates=true, @conflicts_with={:cask=>#<Set: {"thunderbird-beta"}>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/thunderbird/68.5.0>>>, @source_string="Thunderbird.app", @target_string="", @source=#<Pathname:/usr/local/Caskroom/thunderbird/68.5.0/Thunderbird.app>, @target=#<Pathname:/Applications/Thunderbird.app>>, #<Cask::Artifact::Zap:0x00007faae1b34b68 @cask=#<Cask::Cask:0x00007faae1a7fec0 @token="thunderbird", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb>, @tap=#<Tap:0x00007faae1a44e60 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007faae1a7fd80@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/thunderbird>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/thunderbird/.metadata>, @config=#<Cask::Config:0x00007faae1a7d170 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/dkav/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/dkav/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/dkav/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/dkav/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/dkav/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/dkav/Library/Services>, :input_methoddir=>#<Pathname:/Users/dkav/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/dkav/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/dkav/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/dkav/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/dkav/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/dkav/Library/Screen Savers>}, @env={}, @explicit={}>, @dsl=#<Cask::DSL:0x00007faae1a85f50 @cask=#<Cask::Cask:0x00007faae1a7fec0 ...>, @token="thunderbird", @version="68.5.0", @language_blocks={["cs"]=>#<Proc:0x00007faae1a85b18@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:4>, ["de"]=>#<Proc:0x00007faae1a85a50@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:9>, ["en-GB"]=>#<Proc:0x00007faae1a859d8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:14>, ["en"]=>#<Proc:0x00007faae1a858c0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:19>, ["fr"]=>#<Proc:0x00007faae1a85820@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:24>, ["gl"]=>#<Proc:0x00007faae1a856b8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:29>, ["it"]=>#<Proc:0x00007faae1a85578@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:34>, ["ja"]=>#<Proc:0x00007faae1a854d8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:39>, ["nl"]=>#<Proc:0x00007faae1a853e8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:44>, ["pl"]=>#<Proc:0x00007faae1a852f8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:49>, ["pt"]=>#<Proc:0x00007faae1a851b8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:54>, ["pt-BR"]=>#<Proc:0x00007faae1a85140@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:59>, ["ru"]=>#<Proc:0x00007faae1a850a0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:64>, ["uk"]=>#<Proc:0x00007faae1a85000@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:69>, ["zh-TW"]=>#<Proc:0x00007faae1a84f38@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:74>, ["zh"]=>#<Proc:0x00007faae1a84e70@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/thunderbird.rb:79>}, @sha256="d720d164e5dc0cafdc8fb48452acc5ad394b0b0728d308171f3567fc5d06c403", @language="en-US", @url=#<URL:0x00007faae1af6d40 @uri=#<URI::HTTPS https://ftp.mozilla.org/pub/thunderbird/releases/68.5.0/mac/en-US/Thunderbird%2068.5.0.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007faae1af6340 @uri=#<URI::HTTPS https://www.thunderbird.net/en-US/thunderbird/releases/>, @parameters={}>, @name=["Mozilla Thunderbird"], @homepage="https://www.mozilla.org/thunderbird/", @auto_updates=true, @conflicts_with={:cask=>#<Set: {"thunderbird-beta"}>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/thunderbird/68.5.0>>>, @directives={:trash=>["~/Library/Thunderbird", "~/Library/Caches/Thunderbird", "~/Library/Saved Application State/org.mozilla.thunderbird.savedState", "~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/org.mozilla.thunderbird.sfl*", "~/Library/Preferences/org.mozilla.thunderbird.plist"], :signal=>[]}>}>
==> Uninstalling artifact of class Cask::Artifact::App
==> Backing App 'Thunderbird.app' up to '/usr/local/Caskroom/thunderbird/68.5.0/Thunderbird.app'.
/bin/cp -pR /Applications/Thunderbird.app /usr/local/Caskroom/thunderbird/68.5.0/Thunderbird.app
==> Removing App '/Applications/Thunderbird.app'.
==> Dispatching zap stanza
Error: Operation not permitted - /Users/dkav/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:329:in `glob'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:329:in `glob'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:329:in `block in each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:314:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:314:in `each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:351:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:351:in `to_a'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:351:in `uninstall_trash'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:68:in `dispatch_uninstall_directive'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:59:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:58:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:58:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/zap.rb:9:in `zap_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:475:in `block in zap'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:474:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:474:in `zap'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.7-29-gfab4a48
==> macOS
10.15.3
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3542 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.38.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.80.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.7.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.31.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.19.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/nokogiri-1.10.9
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.24.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../../../../../../../../Library/Ruby/Gems/2.6.0/gems/sync-0.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/json-2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.14.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/core
martido/graph
universal-ctags/universal-ctags
vitorgalvao/tiny-scripts
```

**Comment by dkav** [comment]
As noted elsewhere (https://github.com/Homebrew/homebrew-cask/issues/70511#issuecomment-541324220) this is a known issue with Catalina.  Go to System Preferences, tab "Privacy" and allow total disk access to Terminal to resolve the issue.
