### ISSUE TITLE
cask gqrx error install

### ISSUE THREAD

**Issue by ah1102** [Homebrew/homebrew-cask#78282]
Error: Failure while executing; `/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames \(\"gqrx\"\) /usr/local/Caskroom/gqrx/2.11.5/gqrx.wrapper.sh` exited with 127. Here's the output:
No such file or directory - /usr/bin/xattr

**Log:**
```
Apple@iMac-Apple ~ % brew cask install gqrx
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
fastlane                                 v8
==> Updated Casks
homebrew/cask/cctalk

==> Downloading https://github.com/csete/gqrx/releases/download/v2.11.5/Gqrx-2.1
Already downloaded: /Users/Apple/Library/Caches/Homebrew/downloads/21e7343a967187ddb56723d54f5f726bf378704c3486520fb34618ba61a4032d--Gqrx-2.11.5.dmg
==> Verifying SHA-256 checksum for Cask 'gqrx'.
==> Installing Cask gqrx
==> Moving App 'Gqrx.app' to '/Applications/Gqrx.app'.
==> Linking Binary 'airspy_info' to '/usr/local/bin/airspy_info'.
==> Linking Binary 'airspy_spiflash' to '/usr/local/bin/airspy_spiflash'.
==> Linking Binary 'hackrf_cpldjtag' to '/usr/local/bin/hackrf_cpldjtag'.
==> Linking Binary 'hackrf_debug' to '/usr/local/bin/hackrf_debug'.
==> Linking Binary 'hackrf_info' to '/usr/local/bin/hackrf_info'.
==> Linking Binary 'hackrf_spiflash' to '/usr/local/bin/hackrf_spiflash'.
==> Linking Binary 'hackrf_transfer' to '/usr/local/bin/hackrf_transfer'.
==> Linking Binary 'rtl_adsb' to '/usr/local/bin/rtl_adsb'.
==> Linking Binary 'rtl_eeprom' to '/usr/local/bin/rtl_eeprom'.
==> Linking Binary 'rtl_fm' to '/usr/local/bin/rtl_fm'.
==> Linking Binary 'rtl_power' to '/usr/local/bin/rtl_power'.
==> Linking Binary 'rtl_sdr' to '/usr/local/bin/rtl_sdr'.
==> Linking Binary 'rtl_tcp' to '/usr/local/bin/rtl_tcp'.
==> Linking Binary 'rtl_test' to '/usr/local/bin/rtl_test'.
==> Linking Binary 'SoapySDRUtil' to '/usr/local/bin/soapysdrutil'.
==> Linking Binary 'volk_profile' to '/usr/local/bin/volk_profile'.
==> Linking Binary 'gqrx.wrapper.sh' to '/usr/local/bin/gqrx'.
==> Unlinking Binary '/usr/local/bin/volk_profile'.
==> Unlinking Binary '/usr/local/bin/soapysdrutil'.
==> Unlinking Binary '/usr/local/bin/rtl_test'.
==> Unlinking Binary '/usr/local/bin/rtl_tcp'.
==> Unlinking Binary '/usr/local/bin/rtl_sdr'.
==> Unlinking Binary '/usr/local/bin/rtl_power'.
==> Unlinking Binary '/usr/local/bin/rtl_fm'.
==> Unlinking Binary '/usr/local/bin/rtl_eeprom'.
==> Unlinking Binary '/usr/local/bin/rtl_adsb'.
==> Unlinking Binary '/usr/local/bin/hackrf_transfer'.
==> Unlinking Binary '/usr/local/bin/hackrf_spiflash'.
==> Unlinking Binary '/usr/local/bin/hackrf_info'.
==> Unlinking Binary '/usr/local/bin/hackrf_debug'.
==> Unlinking Binary '/usr/local/bin/hackrf_cpldjtag'.
==> Unlinking Binary '/usr/local/bin/airspy_spiflash'.
==> Unlinking Binary '/usr/local/bin/airspy_info'.
==> Backing App 'Gqrx.app' up to '/usr/local/Caskroom/gqrx/2.11.5/Gqrx.app'.
==> Removing App '/Applications/Gqrx.app'.
==> Purging files for version 2.11.5 of Cask gqrx
Error: Failure while executing; `/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames \(\"gqrx\"\) /usr/local/Caskroom/gqrx/2.11.5/gqrx.wrapper.sh` exited with 127. Here's the output:
No such file or directory - /usr/bin/xattr
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/relocated.rb:75:in `add_altname_metadata'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:67:in `create_filesystem_link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:54:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/binary.rb:9:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:17:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
