### ISSUE TITLE
Can't install lazarus cask

### ISSUE THREAD

**Issue by m33m33** [Homebrew/homebrew-cask#78679]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Can't install lazarus cask

- macOS is up to date (no update pending)
- homebrew clean install (ran a full uninstall script, then fresh install again)
- others brew packages and casks do works fine

#### Command that failed

```
brew cask install lazarus
```

#### Output of command with `--force --verbose --debug`

```
brew cask install lazarus --force --verbose --debug 
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://downloads.sourceforge.net/lazarus/lazarus-2.0.6-i686-macosx.dmg
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.10-52-ga401c1c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.3\)\ curl/7.64.1 --location --silent --head --request GET https://downloads.sourceforge.net/lazarus/lazarus-2.0.6-i686-macosx.dmg
Already downloaded: /Users/ml/Library/Caches/Homebrew/downloads/ed5ada69c3ac136c4fc4d2bad57f11a2ab9da9c7da8cd6f7f26ffa2cd685254f--lazarus-2.0.6-i686-macosx.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/ml/Library/Caches/Homebrew/downloads/ed5ada69c3ac136c4fc4d2bad57f11a2ab9da9c7da8cd6f7f26ffa2cd685254f--lazarus-2.0.6-i686-macosx.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/ml/Library/Caches/Homebrew/downloads/ed5ada69c3ac136c4fc4d2bad57f11a2ab9da9c7da8cd6f7f26ffa2cd685254f--lazarus-2.0.6-i686-macosx.dmg
==> /Users/ml/Library/Caches/Homebrew/downloads/ed5ada69c3ac136c4fc4d2bad57f11a2ab9da9c7da8cd6f7f26ffa2cd685254f--lazarus-2.0.6-i686-macosx.dmg is quarantined
==> Downloaded to -> /Users/ml/Library/Caches/Homebrew/downloads/ed5ada69c3ac136c4fc4d2bad57f11a2ab9da9c7da8cd6f7f26ffa2cd685254f--lazarus-2.0.6-i686-macosx.dmg
==> Verifying SHA-256 checksum for Cask 'lazarus'.
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fpc.rb
hdiutil imageinfo -format /Users/ml/Library/Caches/Homebrew/downloads/ed5ada69c3ac136c4fc4d2bad57f11a2ab9da9c7da8cd6f7f26ffa2cd685254f--lazarus-2.0.6-i686-macosx.dmg
All Formula dependencies satisfied.
==> Installing Cask lazarus
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/ml/Library/Caches/Homebrew/downloads/ed5ada69c3ac136c4fc4d2bad57f11a2ab9da9c7da8cd6f7f26ffa2cd685254f--lazarus-2.0.6-i686-macosx.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/sh/z1zpl4fj58lb8c7nqk7fmycc0000gn/T/d20200314-63140-flf27a /Users/ml/Library/Caches/Homebrew/downloads/ed5ada69c3ac136c4fc4d2bad57f11a2ab9da9c7da8cd6f7f26ffa2cd685254f--lazarus-2.0.6-i686-macosx.dmg
find . -print0
mkbom -s -i /var/folders/sh/z1zpl4fj58lb8c7nqk7fmycc0000gn/T/20200314-63140-yf1o6t.list -- /var/folders/sh/z1zpl4fj58lb8c7nqk7fmycc0000gn/T/20200314-63140-1k2eqnt.bom
ditto --bom /var/folders/sh/z1zpl4fj58lb8c7nqk7fmycc0000gn/T/20200314-63140-1k2eqnt.bom -- /private/var/folders/sh/z1zpl4fj58lb8c7nqk7fmycc0000gn/T/d20200314-63140-flf27a/dmg.ebmk5c /var/folders/sh/z1zpl4fj58lb8c7nqk7fmycc0000gn/T/d20200314-63140-duemyc
diskutil eject /private/var/folders/sh/z1zpl4fj58lb8c7nqk7fmycc0000gn/T/d20200314-63140-flf27a/dmg.ebmk5c
cp -pR /var/folders/sh/z1zpl4fj58lb8c7nqk7fmycc0000gn/T/d20200314-63140-duemyc/lazarus.pkg/. /usr/local/Caskroom/lazarus/2.0.6/lazarus.pkg
chmod -Rf +w /var/folders/sh/z1zpl4fj58lb8c7nqk7fmycc0000gn/T/d20200314-63140-duemyc
==> Verifying Gatekeeper status of /Users/ml/Library/Caches/Homebrew/downloads/ed5ada69c3ac136c4fc4d2bad57f11a2ab9da9c7da8cd6f7f26ffa2cd685254f--lazarus-2.0.6-i686-macosx.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/ml/Library/Caches/Homebrew/downloads/ed5ada69c3ac136c4fc4d2bad57f11a2ab9da9c7da8cd6f7f26ffa2cd685254f--lazarus-2.0.6-i686-macosx.dmg
==> /Users/ml/Library/Caches/Homebrew/downloads/ed5ada69c3ac136c4fc4d2bad57f11a2ab9da9c7da8cd6f7f26ffa2cd685254f--lazarus-2.0.6-i686-macosx.dmg is quarantined
==> Propagating quarantine from /Users/ml/Library/Caches/Homebrew/downloads/ed5ada69c3ac136c4fc4d2bad57f11a2ab9da9c7da8cd6f7f26ffa2cd685254f--lazarus-2.0.6-i686-macosx.dmg to /usr/local/Caskroom/lazarus/2.0.6
/usr/bin/xattr -p com.apple.quarantine /Users/ml/Library/Caches/Homebrew/downloads/ed5ada69c3ac136c4fc4d2bad57f11a2ab9da9c7da8cd6f7f26ffa2cd685254f--lazarus-2.0.6-i686-macosx.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5e6d33c0\;Homebrew\\x20Cask\;12569A5E-259F-4062-A302-1D63B7B0CE01
==> Creating metadata directory /usr/local/Caskroom/lazarus/.metadata/2.0.6/20200314195601.035.
==> Creating metadata subdirectory /usr/local/Caskroom/lazarus/.metadata/2.0.6/20200314195601.035/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007f98d7189dc8 @cask=#<Cask::Cask:0x00007f98d6931270 @token="lazarus", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/lazarus.rb>, @tap=#<Tap:0x00007f98d7973188 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007f98d69310e0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/lazarus.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/lazarus>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/lazarus/.metadata>, @config=#<Cask::Config:0x00007f98d718bd80 @explicit={}>, @dsl=#<Cask::DSL:0x00007f98d718bc18 @cask=#<Cask::Cask:0x00007f98d6931270 ...>, @token="lazarus", @version="2.0.6", @sha256="e78388aad925b5343b551401fa85e22ca63b152c3694e345ef6ddd7c37ba0e7d", @url=#<URL:0x00007f98d718b8a8 @uri=#<URI::HTTPS https://downloads.sourceforge.net/lazarus/lazarus-2.0.6-i686-macosx.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007f98d718b588 @uri=#<URI::HTTPS https://sourceforge.net/projects/lazarus/rss>, @parameters={}>, @name=["Lazarus"], @homepage="https://www.lazarus-ide.org/", @depends_on={:formula=>["fpc"], :cask=>["fpcsrc"]}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/lazarus/2.0.6>, @language=nil>>, @directives={:pkgutil=>"org.freepascal.lazarus.www", :signal=>[]}>, #<Cask::Artifact::Pkg:0x00007f98d718ab10 @cask=#<Cask::Cask:0x00007f98d6931270 @token="lazarus", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/lazarus.rb>, @tap=#<Tap:0x00007f98d7973188 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007f98d69310e0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/lazarus.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/lazarus>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/lazarus/.metadata>, @config=#<Cask::Config:0x00007f98d718bd80 @explicit={}>, @dsl=#<Cask::DSL:0x00007f98d718bc18 @cask=#<Cask::Cask:0x00007f98d6931270 ...>, @token="lazarus", @version="2.0.6", @sha256="e78388aad925b5343b551401fa85e22ca63b152c3694e345ef6ddd7c37ba0e7d", @url=#<URL:0x00007f98d718b8a8 @uri=#<URI::HTTPS https://downloads.sourceforge.net/lazarus/lazarus-2.0.6-i686-macosx.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007f98d718b588 @uri=#<URI::HTTPS https://sourceforge.net/projects/lazarus/rss>, @parameters={}>, @name=["Lazarus"], @homepage="https://www.lazarus-ide.org/", @depends_on={:formula=>["fpc"], :cask=>["fpcsrc"]}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/lazarus/2.0.6>, @language=nil>>, @path=#<Pathname:/usr/local/Caskroom/lazarus/2.0.6/lazarus.pkg>, @stanza_options={}>}>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for lazarus; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- /usr/bin/env LOGNAME=ml USER=ml USERNAME=ml /usr/sbin/installer -pkg /usr/local/Caskroom/lazarus/2.0.6/lazarus.pkg -target / -verboseR
installer: Package name is Lazarus
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Lazarus…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%3.175000
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)
==> Purging files for version 2.0.6 of Cask lazarus
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=ml USER=ml USERNAME=ml /usr/sbin/installer -pkg /usr/local/Caskroom/lazarus/2.0.6/lazarus.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Lazarus
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Lazarus…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%3.175000
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew Version
2.2.10-52-ga401c1c
==> macOS
10.15.3
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3490 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.38.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.80.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.7.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.31.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.19.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/nokogiri-1.10.9
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.24.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../../../../../../../../Library/Ruby/Gems/2.6.0/gems/sync-0.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/json-2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.14.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
brew tap
homebrew/cask
homebrew/core
```

**Comment by m33m33** [comment]
My guess it that brew chooses a 32b version of lazarus (lazarus-2.0.6-i686-macosx.dmg) instead of 64b.

The dmg file should be like LazarusIDE-2.0.6-macos-x86_64.pkg

At least, installing LazarusIDE-2.0.6-macos-x86_64.pkg from sourceforge works well.

**Comment by reitermarkus** [comment]
> At least, installing LazarusIDE-2.0.6-macos-x86_64.pkg from sourceforge works well.

Could you submit an update for the cask to use this version?

**Comment by m33m33** [comment]
Ok

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by m33m33** [comment]
Done

**Comment by m33m33** [comment]
Checks passed
Someone should merge the pull request now

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/78701.
