### ISSUE TITLE
idafree: 7.0 fails on Catalina (likely quarantine issue)

### ISSUE THREAD

**Issue by hamiltont** [Homebrew/homebrew-cask#78946]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Tried to install idafree. Downloads OK, passes checksum OK. Unable to run the installer because `“idafree70_mac” can’t be opened because Apple cannot check it for malicious software.`

#### Command that failed

```
brew cask install idafree
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install idafree --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://out7.hex-rays.com/files/idafree70_mac.zip
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.10-79-g5518f27\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.3\)\ curl/7.64.1 --location --silent --head --request GET https://out7.hex-rays.com/files/idafree70_mac.zip
Already downloaded: /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip
/usr/bin/xattr -p com.apple.quarantine /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip
==> /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip is quarantined
==> Downloaded to -> /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip
==> Verifying SHA-256 checksum for Cask 'idafree'.
zipinfo -1 /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip
==> Installing Cask idafree
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip
zipinfo -1 /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip
unzip -o /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip -d /var/folders/6z/g0gkmzrn3nd74j547t0t6z0w0000gn/T/d20200320-81260-1ck81f2
cp -pR /var/folders/6z/g0gkmzrn3nd74j547t0t6z0w0000gn/T/d20200320-81260-1ck81f2/idafree70_mac.app/. /usr/local/Caskroom/idafree/7.0/idafree70_mac.app
chmod -Rf +w /var/folders/6z/g0gkmzrn3nd74j547t0t6z0w0000gn/T/d20200320-81260-1ck81f2
==> Verifying Gatekeeper status of /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip
/usr/bin/xattr -p com.apple.quarantine /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip
==> /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip is quarantined
==> Propagating quarantine from /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip to /usr/local/Caskroom/idafree/7.0
/usr/bin/xattr -p com.apple.quarantine /Users/hamiltont/Library/Caches/Homebrew/downloads/cc53535374d9680ef0f99acc2965e4903e9b85acb03bd7327e6a5abdd9da1d96--idafree70_mac.zip
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5e7321db\;Homebrew\\x20Cask\;F87C388D-ACAD-404E-A679-89782074749D
==> Creating metadata directory /usr/local/Caskroom/idafree/.metadata/7.0/20200320061743.728.
==> Creating metadata subdirectory /usr/local/Caskroom/idafree/.metadata/7.0/20200320061743.728/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fc51e92b798 @cask=#<Cask::Cask:0x00007fc51d1df8f0 @token="idafree", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/idafree.rb>, @tap=#<Tap:0x00007fc51e881248 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fc51d1df7b0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/idafree.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/idafree>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/idafree/.metadata>, @config=#<Cask::Config:0x00007fc51d2accb0 @explicit={}>, @dsl=#<Cask::DSL:0x00007fc51d2acb48 @cask=#<Cask::Cask:0x00007fc51d1df8f0 ...>, @token="idafree", @version="7.0", @sha256="77a4557e7104dc9c7e3957558ce4879182e09f3739f870e4e6e82795dc56b257", @url=#<URL:0x00007fc51d2ac738 @uri=#<URI::HTTPS https://out7.hex-rays.com/files/idafree70_mac.zip>, @user_agent=:default, @specs={}>, @name=["IDA Free"], @homepage="https://www.hex-rays.com/index.shtml", @artifacts=#<SortedSet: {...}>, @language=nil>>, @directives={:script=>{:executable=>"/Applications/IDA Freeware 7.0/uninstall.app/Contents/MacOS/installbuilder.sh", :args=>["--mode", "unattended"], :sudo=>true}, :signal=>[]}>, #<Cask::Artifact::Installer:0x00007fc51e92bdb0 @cask=#<Cask::Cask:0x00007fc51d1df8f0 @token="idafree", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/idafree.rb>, @tap=#<Tap:0x00007fc51e881248 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fc51d1df7b0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/idafree.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/idafree>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/idafree/.metadata>, @config=#<Cask::Config:0x00007fc51d2accb0 @explicit={}>, @dsl=#<Cask::DSL:0x00007fc51d2acb48 @cask=#<Cask::Cask:0x00007fc51d1df8f0 ...>, @token="idafree", @version="7.0", @sha256="77a4557e7104dc9c7e3957558ce4879182e09f3739f870e4e6e82795dc56b257", @url=#<URL:0x00007fc51d2ac738 @uri=#<URI::HTTPS https://out7.hex-rays.com/files/idafree70_mac.zip>, @user_agent=:default, @specs={}>, @name=["IDA Free"], @homepage="https://www.hex-rays.com/index.shtml", @artifacts=#<SortedSet: {...}>, @language=nil>>, @args={:must_succeed=>true, :sudo=>false, :args=>["--mode", "unattended", "--installpassword", ""], :print_stdout=>true}, @path=#<Pathname:idafree70_mac.app/Contents/MacOS/installbuilder.sh>>}>
==> Installing artifact of class Cask::Artifact::Installer
==> Running installer script 'idafree70_mac.app/Contents/MacOS/installb
/usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/idafree/7.0/idafree70_mac.app/Contents/MacOS/installbuilder.sh --mode unattended --installpassword ''

MAC DIALOG SHOWS HERE - OPTIONS ARE 'Show in Finder' and 'OK'. I chose OK

==> Purging files for version 7.0 of Cask idafree
Error: Failure while executing; `/usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/idafree/7.0/idafree70_mac.app/Contents/MacOS/installbuilder.sh --mode unattended --installpassword ''` exited with .
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/installer.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
~$
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew Version
2.2.10-79-g5518f27
==> macOS
10.15.3
==> SIP
Enabled
==> Java
14
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3498 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.38.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.80.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.7.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.32.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.19.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/nokogiri-1.10.9
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.24.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../../../../../../../../Library/Ruby/Gems/2.6.0/gems/sync-0.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/json-2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.14.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/bash"
 ~$
```

#### Output of `brew tap`

```
$ brew tap
homebrew/bundle
homebrew/cask
homebrew/core
jesseduffield/lazydocker
 ~$
```

**Comment by vitorgalvao** [comment]
Another one for https://github.com/Homebrew/homebrew-cask/issues/70798.

**Comment by vitorgalvao** [comment]
Another one for https://github.com/Homebrew/homebrew-cask/issues/70798.
