### ISSUE TITLE
Unable to update or install torguard v3.98.4 via home brew

### ISSUE THREAD

**Issue by nar3nd3r** [Homebrew/homebrew-cask#80086]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Unable to update or install TorGuard v3.98.4 via home brew, error snapshot is shown below, Most likely issue with file system as shown in error description.

> installer: Cannot install on volume / because it is disabled.
> installer: The version of macOS is too new.

#### Command that failed

```
❯ brew cask install torguard
==> Downloading https://updates.torguard.biz/Software/MacOSX/TorGuard-v3.98.4.dmg
Already downloaded: /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg
==> Verifying SHA-256 checksum for Cask 'torguard'.
==> Installing Cask torguard
==> Running installer for torguard; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Cannot install on volume / because it is disabled.
installer: The version of macOS is too new.
==> Purging files for version 3.98.4 of Cask torguard
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=narender USER=narender USERNAME=narender /usr/sbin/installer -pkg /usr/local/Caskroom/torguard/3.98.4/Install\ TorGuard.pkg -target /` exited with 1. Here's the output:
installer: Cannot install on volume / because it is disabled.
installer: The version of macOS is too new.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
❯
```

#### Output of command with `--force --verbose --debug`

```
❯ brew cask install torguard --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://updates.torguard.biz/Software/MacOSX/TorGuard-v3.98.4.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.2.11-134-g8fe74f9\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.4\)\ curl/7.64.1 --retry 3 --location --silent --head --request GET https://updates.torguard.biz/Software/MacOSX/TorGuard-v3.98.4.dmg
Already downloaded: /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg
==> /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg is quarantined
==> Downloaded to -> /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg
==> Verifying SHA-256 checksum for Cask 'torguard'.
tar tf /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg
hdiutil imageinfo -format /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg
==> Installing Cask torguard
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/t9/mb_lkbnn2fg5n8w_2txlwc600000gn/T/d20200405-23571-13v9agh /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg
find . -print0
mkbom -s -i /var/folders/t9/mb_lkbnn2fg5n8w_2txlwc600000gn/T/20200405-23571-1vt0zba.list -- /var/folders/t9/mb_lkbnn2fg5n8w_2txlwc600000gn/T/20200405-23571-1v8ulzo.bom
ditto --bom /var/folders/t9/mb_lkbnn2fg5n8w_2txlwc600000gn/T/20200405-23571-1v8ulzo.bom -- /private/var/folders/t9/mb_lkbnn2fg5n8w_2txlwc600000gn/T/d20200405-23571-13v9agh/dmg.PuyDiq /var/folders/t9/mb_lkbnn2fg5n8w_2txlwc600000gn/T/d20200405-23571-ritw79
diskutil eject /private/var/folders/t9/mb_lkbnn2fg5n8w_2txlwc600000gn/T/d20200405-23571-13v9agh/dmg.PuyDiq
chmod +rw /var/folders/t9/mb_lkbnn2fg5n8w_2txlwc600000gn/T/d20200405-23571-ritw79/Install TorGuard.pkg
cp -p /var/folders/t9/mb_lkbnn2fg5n8w_2txlwc600000gn/T/d20200405-23571-ritw79/Install TorGuard.pkg /usr/local/Caskroom/torguard/3.98.4/Install TorGuard.pkg
==> Verifying Gatekeeper status of /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg
==> /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg is quarantined
==> Propagating quarantine from /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg to /usr/local/Caskroom/torguard/3.98.4
/usr/bin/xattr -p com.apple.quarantine /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5e8a9587\;Homebrew\\x20Cask\;60254CEA-3BDA-41ED-A4F0-3B9B2F6EC526
==> Creating metadata directory /usr/local/Caskroom/torguard/.metadata/3.98.4/20200406023957.137.
==> Creating metadata subdirectory /usr/local/Caskroom/torguard/.metadata/3.98.4/20200406023957.137/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fa5da8fa958 @cask=#<Cask::Cask:0x00007fa5db9e1d70 @token="torguard", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/torguard.rb>, @tap=#<Tap:0x00007fa5db250660 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fa5db9e1cd0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/torguard.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/torguard>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/torguard/.metadata>, @config=#<Cask::Config:0x00007fa5db9c9428 @explicit={}>, @dsl=#<Cask::DSL:0x00007fa5db9c92c0 @cask=#<Cask::Cask:0x00007fa5db9e1d70 ...>, @token="torguard", @version="3.98.4", @sha256="98eb3f5aefdfea8f1d01a96e1df6432cb9b1e8e0398672a2acf80c9e303abca4", @url=#<URL:0x00007fa5db9c8f00 @uri=#<URI::HTTPS https://updates.torguard.biz/Software/MacOSX/TorGuard-v3.98.4.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fa5db9c8b90 @uri=#<URI::HTTPS https://updates.torguard.biz/Software/MacOSX/checksums.sha256>, @parameters={}>, @name=["TorGuard"], @homepage="https://torguard.net/", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/torguard/3.98.4>, @language=nil>>, @directives={:pkgutil=>"net.torguard.TorGuardDesktopQt", :delete=>"/Applications/TorGuard.app", :signal=>[]}>, #<Cask::Artifact::Pkg:0x00007fa5da8fbda8 @cask=#<Cask::Cask:0x00007fa5db9e1d70 @token="torguard", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/torguard.rb>, @tap=#<Tap:0x00007fa5db250660 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fa5db9e1cd0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/torguard.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/torguard>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/torguard/.metadata>, @config=#<Cask::Config:0x00007fa5db9c9428 @explicit={}>, @dsl=#<Cask::DSL:0x00007fa5db9c92c0 @cask=#<Cask::Cask:0x00007fa5db9e1d70 ...>, @token="torguard", @version="3.98.4", @sha256="98eb3f5aefdfea8f1d01a96e1df6432cb9b1e8e0398672a2acf80c9e303abca4", @url=#<URL:0x00007fa5db9c8f00 @uri=#<URI::HTTPS https://updates.torguard.biz/Software/MacOSX/TorGuard-v3.98.4.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fa5db9c8b90 @uri=#<URI::HTTPS https://updates.torguard.biz/Software/MacOSX/checksums.sha256>, @parameters={}>, @name=["TorGuard"], @homepage="https://torguard.net/", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/torguard/3.98.4>, @language=nil>>, @path=#<Pathname:/usr/local/Caskroom/torguard/3.98.4/Install TorGuard.pkg>, @stanza_options={}>, #<Cask::Artifact::Zap:0x00007fa5da8fa250 @cask=#<Cask::Cask:0x00007fa5db9e1d70 @token="torguard", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/torguard.rb>, @tap=#<Tap:0x00007fa5db250660 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fa5db9e1cd0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/torguard.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/torguard>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/torguard/.metadata>, @config=#<Cask::Config:0x00007fa5db9c9428 @explicit={}>, @dsl=#<Cask::DSL:0x00007fa5db9c92c0 @cask=#<Cask::Cask:0x00007fa5db9e1d70 ...>, @token="torguard", @version="3.98.4", @sha256="98eb3f5aefdfea8f1d01a96e1df6432cb9b1e8e0398672a2acf80c9e303abca4", @url=#<URL:0x00007fa5db9c8f00 @uri=#<URI::HTTPS https://updates.torguard.biz/Software/MacOSX/TorGuard-v3.98.4.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fa5db9c8b90 @uri=#<URI::HTTPS https://updates.torguard.biz/Software/MacOSX/checksums.sha256>, @parameters={}>, @name=["TorGuard"], @homepage="https://torguard.net/", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/torguard/3.98.4>, @language=nil>>, @directives={:trash=>["~/Library/Preferences/net.torguard.TorGuard*.plist", "~/Library/Saved Application State/net.torguard.TorGuardDesktopQt.savedState"], :signal=>[]}>}>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for torguard; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- /usr/bin/env LOGNAME=narender USER=narender USERNAME=narender /usr/sbin/installer -pkg /usr/local/Caskroom/torguard/3.98.4/Install\ TorGuard.pkg -target / -verboseR
installer: Cannot install on volume / because it is disabled.
installer: The version of macOS is too new.
==> Purging files for version 3.98.4 of Cask torguard
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=narender USER=narender USERNAME=narender /usr/sbin/installer -pkg /usr/local/Caskroom/torguard/3.98.4/Install\ TorGuard.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Cannot install on volume / because it is disabled.
installer: The version of macOS is too new.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

#### Output of `brew cask doctor`

```
❯ brew cask doctor
==> Homebrew Version
2.2.11-134-g8fe74f9
==> macOS
10.15.4
==> SIP
Enabled
==> Java
14
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3512 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (948 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.38.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
❯ brew tap
buo/cask-upgrade
homebrew/cask
homebrew/cask-fonts
homebrew/core
homebrew/services
mongodb/brew
```

**Comment by vitorgalvao** [comment]
What happens if try to install the pkg manually?

**Comment by nar3nd3r** [comment]
I see this (on manual installation)

![Screenshot 2020-04-05 at 11 28 29 PM](https://user-images.githubusercontent.com/39687188/78520653-58b04180-7795-11ea-9262-9f65cb6b8bbe.png)

**Comment by vitorgalvao** [comment]
Then the issue is on their side. You need to complain to them, not us. Seems like this may not run on Catalina.

**Comment by nar3nd3r** [comment]
Cool, thanks @vitorgalvao

**Comment by vitorgalvao** [comment]
In the meantime, I’m making it so the cask does not try to install on Catalina: https://github.com/Homebrew/homebrew-cask/pull/80090.

**Comment by nar3nd3r** [comment]
Sure, but there does exist one already.

```
❯ brew cask info torguard
torguard: 3.98.4
https://torguard.net/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/torguard.rb
==> Name
TorGuard
==> Artifacts
Install TorGuard.pkg (Pkg)
❯ 
```

not sure, if that something could be blocked as well, by the way, can I install an older version of this cask. (am not sure, if there's a way to do that).

**Comment by vitorgalvao** [comment]
Looks like the installer is failing on previous versions as well. Looks like their pre-install script sis borked and not checking for macOS versions accurately. Going to revert the cask.

**Comment by nar3nd3r** [comment]
Thanks, I appreciate it. I can confirm the revert of this cask.

```
❯ brew cask info torguard
torguard: 3.98.2
https://torguard.net/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/torguard.rb
==> Name
TorGuard
==> Artifacts
Install TorGuard.pkg (Pkg)
```

and install it of course :)

```
❯ brew cask install torguard
==> Downloading https://updates.torguard.biz/Software/MacOSX/TorGuard-v3.98.2.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'torguard'.
==> Installing Cask torguard
==> Running installer for torguard; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is TorGuard
installer: Installing at base path /
installer: The install was successful.
🍺  torguard was successfully installed!
```

Cheers!
