### ISSUE TITLE
Unable to update or install torguard v3.98.4 via home brew

### ISSUE THREAD

**Issue by nar3nd3r** [Homebrew/homebrew-cask#80085]
My apologies for being direct here. I'm Unable to update or install torguard v3.98.4 via home brew, error snapshot is shown below.

**OS: mac OS Catalina 10.15.4 (19E266)**

```
❯ brew cask install torguard
==> Downloading https://updates.torguard.biz/Software/MacOSX/TorGuard-v3.98.4.dmg
Already downloaded: /Users/narender/Library/Caches/Homebrew/downloads/14842051e2f7282c9da014709b21d68c9a96fbc05b2b650242977ad99bf190cd--TorGuard-v3.98.4.dmg
==> Verifying SHA-256 checksum for Cask 'torguard'.
==> Installing Cask torguard
==> Running installer for torguard; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Cannot install on volume / because it is disabled.
installer: The version of macOS is too new.
==> Purging files for version 3.98.4 of Cask torguard
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=narender USER=narender USERNAME=narender /usr/sbin/installer -pkg /usr/local/Caskroom/torguard/3.98.4/Install\ TorGuard.pkg -target /` exited with 1. Here's the output:
installer: Cannot install on volume / because it is disabled.
installer: The version of macOS is too new.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
❯
```

Am I missing something, appreciate a quick guidance here.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
