### ISSUE TITLE
brew cask zap firefox fails

### ISSUE THREAD

**Issue by alexbool** [Homebrew/homebrew-cask#80369]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

`brew cask zap firefox` command fails with the following message:
```
==> Implied "brew cask uninstall firefox"
==> Backing App 'Firefox.app' up to '/usr/local/Caskroom/firefox/75.0/Firefox.app'.
==> Removing App '/Applications/Firefox.app'.
==> Dispatching zap stanza
Error: Operation not permitted - /Users/alexbool/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:329:in `glob'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:329:in `glob'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:329:in `block in each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:314:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:314:in `each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:351:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:351:in `to_a'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:351:in `uninstall_trash'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:68:in `dispatch_uninstall_directive'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:59:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:58:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:58:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/zap.rb:9:in `zap_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:475:in `block in zap'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:474:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:474:in `zap'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:159:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

#### Command that failed

```
brew cask zap firefox
```

#### Output of command with `--force --verbose --debug`

```
==> Zapping Cask firefox
==> Implied "brew cask uninstall firefox"
==> Uninstalling artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::App:0x00007feaf00cd9c8 @cask=#<Cask::Cask:0x00007feaef19e150 @token="firefox", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb>, @tap=#<Tap:0x00007feaef94fca0 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007feaef19e038@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/firefox>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/firefox/.metadata>, @config=#<Cask::Config:0x00007feaef1a6a80 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/alexbool/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/alexbool/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/alexbool/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/alexbool/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/alexbool/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/alexbool/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/alexbool/Library/Services>, :input_methoddir=>#<Pathname:/Users/alexbool/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/alexbool/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/alexbool/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/alexbool/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/alexbool/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/alexbool/Library/Screen Savers>}, @env={}, @explicit={}>, @dsl=#<Cask::DSL:0x00007feaef1af608 @cask=#<Cask::Cask:0x00007feaef19e150 ...>, @token="firefox", @version="75.0", @language_blocks={["cs"]=>#<Proc:0x00007feaef1af2e8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:4>, ["de"]=>#<Proc:0x00007feaef1af220@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:9>, ["en-GB"]=>#<Proc:0x00007feaef1af130@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:14>, ["en"]=>#<Proc:0x00007feaef1af090@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:19>, ["eo"]=>#<Proc:0x00007feaef1aef50@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:24>, ["es-AR"]=>#<Proc:0x00007feaef1aed70@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:29>, ["es-CL"]=>#<Proc:0x00007feaef1aeaf0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:34>, ["es-ES"]=>#<Proc:0x00007feaef1ae9d8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:39>, ["fi"]=>#<Proc:0x00007feaef1ae4b0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:44>, ["fr"]=>#<Proc:0x00007feaef1adc40@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:49>, ["gl"]=>#<Proc:0x00007feaef1ad600@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:54>, ["in"]=>#<Proc:0x00007feaef1b7880@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:59>, ["it"]=>#<Proc:0x00007feaef1b7740@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:64>, ["ja"]=>#<Proc:0x00007feaef1b7178@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:69>, ["ko"]=>#<Proc:0x00007feaef1b6f48@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:74>, ["nl"]=>#<Proc:0x00007feaef1b6e30@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:79>, ["pl"]=>#<Proc:0x00007feaef1b6b38@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:84>, ["pt-BR"]=>#<Proc:0x00007feaef1b6840@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:89>, ["pt"]=>#<Proc:0x00007feaef1b6700@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:94>, ["ru"]=>#<Proc:0x00007feaef1b6610@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:99>, ["tr"]=>#<Proc:0x00007feaef1b6458@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:104>, ["uk"]=>#<Proc:0x00007feaef1b63e0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:109>, ["zh-TW"]=>#<Proc:0x00007feaef1b6368@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:114>, ["zh"]=>#<Proc:0x00007feaef1b62f0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:119>}, @sha256="0c32745905ee818b635c785466c53c66220c9c0d3fc56dc6613456edb0da03ae", @language="en-US", @url=#<URL:0x00007feaef98ece8 @uri=#<URI::HTTPS https://download-installer.cdn.mozilla.net/pub/firefox/releases/75.0/mac/en-US/Firefox%2075.0.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007feaef997690 @uri=#<URI::HTTPS https://www.macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://download.mozilla.org/%3Fproduct=firefox-latest-ssl%26os=osx>, @parameters={}>, @name=["Mozilla Firefox"], @homepage="https://www.mozilla.org/firefox/", @auto_updates=true, @conflicts_with={:cask=>#<Set: {"firefox-beta", "firefox-esr"}>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/firefox/75.0>>>, @source_string="Firefox.app", @target_string="", @source=#<Pathname:/usr/local/Caskroom/firefox/75.0/Firefox.app>, @target=#<Pathname:/Applications/Firefox.app>>, #<Cask::Artifact::Zap:0x00007feaee906178 @cask=#<Cask::Cask:0x00007feaef19e150 @token="firefox", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb>, @tap=#<Tap:0x00007feaef94fca0 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007feaef19e038@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/firefox>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/firefox/.metadata>, @config=#<Cask::Config:0x00007feaef1a6a80 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/alexbool/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/alexbool/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/alexbool/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/alexbool/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/alexbool/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/alexbool/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/alexbool/Library/Services>, :input_methoddir=>#<Pathname:/Users/alexbool/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/alexbool/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/alexbool/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/alexbool/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/alexbool/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/alexbool/Library/Screen Savers>}, @env={}, @explicit={}>, @dsl=#<Cask::DSL:0x00007feaef1af608 @cask=#<Cask::Cask:0x00007feaef19e150 ...>, @token="firefox", @version="75.0", @language_blocks={["cs"]=>#<Proc:0x00007feaef1af2e8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:4>, ["de"]=>#<Proc:0x00007feaef1af220@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:9>, ["en-GB"]=>#<Proc:0x00007feaef1af130@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:14>, ["en"]=>#<Proc:0x00007feaef1af090@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:19>, ["eo"]=>#<Proc:0x00007feaef1aef50@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:24>, ["es-AR"]=>#<Proc:0x00007feaef1aed70@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:29>, ["es-CL"]=>#<Proc:0x00007feaef1aeaf0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:34>, ["es-ES"]=>#<Proc:0x00007feaef1ae9d8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:39>, ["fi"]=>#<Proc:0x00007feaef1ae4b0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:44>, ["fr"]=>#<Proc:0x00007feaef1adc40@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:49>, ["gl"]=>#<Proc:0x00007feaef1ad600@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:54>, ["in"]=>#<Proc:0x00007feaef1b7880@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:59>, ["it"]=>#<Proc:0x00007feaef1b7740@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:64>, ["ja"]=>#<Proc:0x00007feaef1b7178@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:69>, ["ko"]=>#<Proc:0x00007feaef1b6f48@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:74>, ["nl"]=>#<Proc:0x00007feaef1b6e30@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:79>, ["pl"]=>#<Proc:0x00007feaef1b6b38@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:84>, ["pt-BR"]=>#<Proc:0x00007feaef1b6840@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:89>, ["pt"]=>#<Proc:0x00007feaef1b6700@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:94>, ["ru"]=>#<Proc:0x00007feaef1b6610@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:99>, ["tr"]=>#<Proc:0x00007feaef1b6458@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:104>, ["uk"]=>#<Proc:0x00007feaef1b63e0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:109>, ["zh-TW"]=>#<Proc:0x00007feaef1b6368@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:114>, ["zh"]=>#<Proc:0x00007feaef1b62f0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb:119>}, @sha256="0c32745905ee818b635c785466c53c66220c9c0d3fc56dc6613456edb0da03ae", @language="en-US", @url=#<URL:0x00007feaef98ece8 @uri=#<URI::HTTPS https://download-installer.cdn.mozilla.net/pub/firefox/releases/75.0/mac/en-US/Firefox%2075.0.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007feaef997690 @uri=#<URI::HTTPS https://www.macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://download.mozilla.org/%3Fproduct=firefox-latest-ssl%26os=osx>, @parameters={}>, @name=["Mozilla Firefox"], @homepage="https://www.mozilla.org/firefox/", @auto_updates=true, @conflicts_with={:cask=>#<Set: {"firefox-beta", "firefox-esr"}>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/firefox/75.0>>>, @directives={:trash=>["/Library/Logs/DiagnosticReports/firefox_*", "~/Library/Application Support/Firefox", "~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/org.mozilla.firefox.sfl*", "~/Library/Caches/Firefox", "~/Library/Caches/Mozilla/updates/Applications/Firefox", "~/Library/Preferences/org.mozilla.firefox.plist"], :rmdir=>["~/Library/Application Support/Mozilla", "~/Library/Caches/Mozilla/updates/Applications", "~/Library/Caches/Mozilla/updates", "~/Library/Caches/Mozilla"], :signal=>[]}>}>
==> Uninstalling artifact of class Cask::Artifact::App
==> Dispatching zap stanza
Error: Operation not permitted - /Users/alexbool/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:329:in `glob'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:329:in `glob'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:329:in `block in each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:314:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:314:in `each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:351:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:351:in `to_a'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:351:in `uninstall_trash'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:68:in `dispatch_uninstall_directive'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:59:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:58:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:58:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/zap.rb:9:in `zap_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:475:in `block in zap'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:474:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:474:in `zap'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/zap.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:159:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:168:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:168:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:147:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.12-18-g740e024
==> macOS
10.15.4
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3520 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (156 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.38.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by asegarra** [comment]
You need to go to Security & Privacy and give terminal full disk access. Unfortunately then you might hit this bug #79684 with the zap command.

**Comment by alexbool** [comment]
Thanks, I gave Terminal full disk access permission, and it worked!

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/issues/80835.
