### ISSUE TITLE
Macdown fail to install with a cp error

### ISSUE THREAD

**Issue by ydesgagn** [Homebrew/homebrew-cask#80452]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Macdown refuse to install with error:

Error: Failure while executing; `cp -pR /var/folders/pn/bg63s1ns0pq1_9zv54z5dh9c0000gn/T/d20200411-66611-1utm9sd/MacDown.app/. /usr/local/Caskroom/macdown/0.7.3/MacDown.app` exited with 1. Here's the output:
cp: /var/folders/pn/bg63s1ns0pq1_9zv54z5dh9c0000gn/T/d20200411-66611-1utm9sd/MacDown.app/./Contents/_CodeSignature: Permission denied

#### Command that failed

```
brew cask install macdown
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://github.com/MacDownApp/macdown/releases/download/v0.7.3/MacDown.app.zip
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.2.12-32-gc45116e\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.4\)\ curl/7.64.1 --retry 3 --location --silent --head --request GET https://github.com/MacDownApp/macdown/releases/download/v0.7.3/MacDown.app.zip
Already downloaded: /Users/yves/Library/Caches/Homebrew/downloads/52bbe608e0e7c436a76455a61fb2bea9dac81365b5da23f0acfa680b4819f266--MacDown.app.zip
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/yves/Library/Caches/Homebrew/downloads/52bbe608e0e7c436a76455a61fb2bea9dac81365b5da23f0acfa680b4819f266--MacDown.app.zip
/usr/bin/xattr -p com.apple.quarantine /Users/yves/Library/Caches/Homebrew/downloads/52bbe608e0e7c436a76455a61fb2bea9dac81365b5da23f0acfa680b4819f266--MacDown.app.zip
==> /Users/yves/Library/Caches/Homebrew/downloads/52bbe608e0e7c436a76455a61fb2bea9dac81365b5da23f0acfa680b4819f266--MacDown.app.zip is quarantined
==> Downloaded to -> /Users/yves/Library/Caches/Homebrew/downloads/52bbe608e0e7c436a76455a61fb2bea9dac81365b5da23f0acfa680b4819f266--MacDown.app.zip
==> Verifying SHA-256 checksum for Cask 'macdown'.
zipinfo -1 /Users/yves/Library/Caches/Homebrew/downloads/52bbe608e0e7c436a76455a61fb2bea9dac81365b5da23f0acfa680b4819f266--MacDown.app.zip
==> Installing Cask macdown
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/yves/Library/Caches/Homebrew/downloads/52bbe608e0e7c436a76455a61fb2bea9dac81365b5da23f0acfa680b4819f266--MacDown.app.zip
zipinfo -1 /Users/yves/Library/Caches/Homebrew/downloads/52bbe608e0e7c436a76455a61fb2bea9dac81365b5da23f0acfa680b4819f266--MacDown.app.zip
unzip -o /Users/yves/Library/Caches/Homebrew/downloads/52bbe608e0e7c436a76455a61fb2bea9dac81365b5da23f0acfa680b4819f266--MacDown.app.zip -d /var/folders/pn/bg63s1ns0pq1_9zv54z5dh9c0000gn/T/d20200411-68042-1gumk98
cp -pR /var/folders/pn/bg63s1ns0pq1_9zv54z5dh9c0000gn/T/d20200411-68042-1gumk98/MacDown.app/. /usr/local/Caskroom/macdown/0.7.3/MacDown.app
cp: /var/folders/pn/bg63s1ns0pq1_9zv54z5dh9c0000gn/T/d20200411-68042-1gumk98/MacDown.app/./Contents/_CodeSignature: Permission denied
==> Purging files for version 0.7.3 of Cask macdown
Error: Failure while executing; `cp -pR /var/folders/pn/bg63s1ns0pq1_9zv54z5dh9c0000gn/T/d20200411-68042-1gumk98/MacDown.app/. /usr/local/Caskroom/macdown/0.7.3/MacDown.app` exited with 1. Here's the output:
cp: /var/folders/pn/bg63s1ns0pq1_9zv54z5dh9c0000gn/T/d20200411-68042-1gumk98/MacDown.app/./Contents/_CodeSignature: Permission denied

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:19:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/directory.rb:21:in `block in extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/directory.rb:20:in `each'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/directory.rb:20:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:123:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:143:in `block in extract_nestedly'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:127:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:193:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:73:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:159:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:168:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:168:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:147:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.12-32-gc45116e
==> macOS
10.15.4
==> SIP
Enabled
==> Java
14, 13.0.2, 13.0.1
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3523 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (156 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (948 casks)
/usr/local/Homebrew/Library/Taps/ugroupmedia/homebrew-pnp (2 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.38.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
buo/cask-upgrade
dart-lang/dart
denji/nginx
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/command-not-found
homebrew/core
homebrew/services
osx-cross/arm
osx-cross/avr
sambadevi/powerlevel9k
ugroupmedia/pnp
ydesgagn/atmel
```

**Comment by ran-dall** [comment]
@ydesgagn This is an upstream problem that we already tried to fix (#79916). It has already been reported to upstream. There's not much else we can do about it at the moment.
