### ISSUE TITLE
brew cask install eqmac fails on broken dmg link 

### ISSUE THREAD

**Issue by gigajosh** [Homebrew/homebrew-cask#81407]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Brew cask install of application eqMac fails because the dmg file URL it is using appears to be broken. Homebrew is using: https://github.com/bitgapp/eqMac/releases/download/V2.2/eqMac2.dmg, but the dmg it needs is (now): https://github.com/bitgapp/eqMac/releases/download/V0.0.0/eqMac2.dmg

#### Command that failed

```
brew cask install eqmac
```

#### Output of command with `--force --verbose --debug`

```
Updating Homebrew...
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.2.13-151-gbdc7ebf\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --retry 3 --location --silent --head --request GET https://github.com/bitgapp/eqMac/releases/download/V2.2/eqMac2.dmg
==> Downloading https://github.com/bitgapp/eqMac/releases/download/V2.2/eqMac2.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.2.13-151-gbdc7ebf\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --retry 3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://github.com/bitgapp/eqMac/releases/download/V2.2/eqMac2.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.2.13-151-gbdc7ebf\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --progress-bar --retry 3 --location --remote-time --continue-at 0 --output /Users/josh/Library/Caches/Homebrew/downloads/7cb4eb05a794f9c993da69b02d8b6265720e9b3f272be1f91a242d797bd27149--eqMac2.dmg.incomplete https://github.com/bitgapp/eqMac/releases/download/V2.2/eqMac2.dmg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'eqmac' with message: Download failed: https://github.com/bitgapp/eqMac/releases/download/V2.2/eqMac2.dmg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:311:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:308:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:42:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:20:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:152:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:150:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:140:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.13-151-gbdc7ebf
==> macOS
10.13.6
==> SIP
Enabled
==> Java
11.0.1, 1.8.0_191
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3538 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.38.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/81352
