### ISSUE TITLE
MySQL Utilites does not install on Catalina

### ISSUE THREAD

**Issue by mjhorninger** [Homebrew/homebrew-cask#81661]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

mysql-utilities throws an exception when trying to install on Catalina

#### Command that failed

```
brew cask install mysql-utilities
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://downloads.mysql.com/archives/get/p/30/file/mysql-utilities-1.6.5-macos10.12.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.2.14-14-g0404ce2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.4\)\ curl/7.64.1 --retry 3 --location --silent --head --request GET https://downloads.mysql.com/archives/get/p/30/file/mysql-utilities-1.6.5-macos10.12.dmg
Already downloaded: /Users/markh/Library/Caches/Homebrew/downloads/46edd548d6236119476676b49926a944f8ff67a2bc8a24bf1295b1a6c0cd9a5c--mysql-utilities-1.6.5-macos10.12.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/markh/Library/Caches/Homebrew/downloads/46edd548d6236119476676b49926a944f8ff67a2bc8a24bf1295b1a6c0cd9a5c--mysql-utilities-1.6.5-macos10.12.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/markh/Library/Caches/Homebrew/downloads/46edd548d6236119476676b49926a944f8ff67a2bc8a24bf1295b1a6c0cd9a5c--mysql-utilities-1.6.5-macos10.12.dmg
==> /Users/markh/Library/Caches/Homebrew/downloads/46edd548d6236119476676b49926a944f8ff67a2bc8a24bf1295b1a6c0cd9a5c--mysql-utilities-1.6.5-macos10.12.dmg is quarantined
==> Downloaded to -> /Users/markh/Library/Caches/Homebrew/downloads/46edd548d6236119476676b49926a944f8ff67a2bc8a24bf1295b1a6c0cd9a5c--mysql-utilities-1.6.5-macos10.12.dmg
==> Verifying SHA-256 checksum for Cask 'mysql-utilities'.
hdiutil imageinfo -format /Users/markh/Library/Caches/Homebrew/downloads/46edd548d6236119476676b49926a944f8ff67a2bc8a24bf1295b1a6c0cd9a5c--mysql-utilities-1.6.5-macos10.12.dmg
==> Installing Cask mysql-utilities
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/markh/Library/Caches/Homebrew/downloads/46edd548d6236119476676b49926a944f8ff67a2bc8a24bf1295b1a6c0cd9a5c--mysql-utilities-1.6.5-macos10.12.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/1v/cbbk39bn3295_9thfwr99hm40000gn/T/d20200430-65535-1d7bk6p /Users/markh/Library/Caches/Homebrew/downloads/46edd548d6236119476676b49926a944f8ff67a2bc8a24bf1295b1a6c0cd9a5c--mysql-utilities-1.6.5-macos10.12.dmg
find . -print0
mkbom -s -i /var/folders/1v/cbbk39bn3295_9thfwr99hm40000gn/T/20200430-65535-1l0bto4.list -- /var/folders/1v/cbbk39bn3295_9thfwr99hm40000gn/T/20200430-65535-6qamdu.bom
ditto --bom /var/folders/1v/cbbk39bn3295_9thfwr99hm40000gn/T/20200430-65535-6qamdu.bom -- /private/var/folders/1v/cbbk39bn3295_9thfwr99hm40000gn/T/d20200430-65535-1d7bk6p/dmg.kvtIdd /var/folders/1v/cbbk39bn3295_9thfwr99hm40000gn/T/d20200430-65535-odn76p
diskutil eject /private/var/folders/1v/cbbk39bn3295_9thfwr99hm40000gn/T/d20200430-65535-1d7bk6p/dmg.kvtIdd
chmod +rw /var/folders/1v/cbbk39bn3295_9thfwr99hm40000gn/T/d20200430-65535-odn76p/mysql-utilities-1.6.5.pkg
cp -p /var/folders/1v/cbbk39bn3295_9thfwr99hm40000gn/T/d20200430-65535-odn76p/mysql-utilities-1.6.5.pkg /usr/local/Caskroom/mysql-utilities/1.6.5/mysql-utilities-1.6.5.pkg
==> Verifying Gatekeeper status of /Users/markh/Library/Caches/Homebrew/downloads/46edd548d6236119476676b49926a944f8ff67a2bc8a24bf1295b1a6c0cd9a5c--mysql-utilities-1.6.5-macos10.12.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/markh/Library/Caches/Homebrew/downloads/46edd548d6236119476676b49926a944f8ff67a2bc8a24bf1295b1a6c0cd9a5c--mysql-utilities-1.6.5-macos10.12.dmg
==> /Users/markh/Library/Caches/Homebrew/downloads/46edd548d6236119476676b49926a944f8ff67a2bc8a24bf1295b1a6c0cd9a5c--mysql-utilities-1.6.5-macos10.12.dmg is quarantined
==> Propagating quarantine from /Users/markh/Library/Caches/Homebrew/downloads/46edd548d6236119476676b49926a944f8ff67a2bc8a24bf1295b1a6c0cd9a5c--mysql-utilities-1.6.5-macos10.12.dmg to /usr/local/Caskroom/mysql-utilities/1.6.5
/usr/bin/xattr -p com.apple.quarantine /Users/markh/Library/Caches/Homebrew/downloads/46edd548d6236119476676b49926a944f8ff67a2bc8a24bf1295b1a6c0cd9a5c--mysql-utilities-1.6.5-macos10.12.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5ea9d6c5\;Homebrew\\x20Cask\;B84FEC27-63E9-4400-9159-3844BB729869
==> Creating metadata directory /usr/local/Caskroom/mysql-utilities/.metadata/1.6.5/20200430140720.464.
==> Creating metadata subdirectory /usr/local/Caskroom/mysql-utilities/.metadata/1.6.5/20200430140720.464/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fd0702849f0 @cask=#<Cask::Cask:0x00007fd06f876328 @token="mysql-utilities", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/mysql-utilities.rb>, @tap=#<Tap:0x00007fd06f1cd878 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fd06f8760a8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/mysql-utilities.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/mysql-utilities>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/mysql-utilities/.metadata>, @config=#<Cask::Config:0x00007fd06f87d268 @explicit={}>, @dsl=#<Cask::DSL:0x00007fd06f87d0b0 @cask=#<Cask::Cask:0x00007fd06f876328 ...>, @token="mysql-utilities", @version="1.6.5", @sha256="114658256e846b4eeff141065e18ef3f779bcbe59e5d2828ab920d905e693db7", @url=#<URL:0x00007fd06f87cd18 @uri=#<URI::HTTPS https://downloads.mysql.com/archives/get/p/30/file/mysql-utilities-1.6.5-macos10.12.dmg>, @user_agent=:default, @specs={}>, @name=["MySQL Utilities"], @homepage="https://dev.mysql.com/downloads/utilities/", @depends_on={:macos=>#<MacOSRequirement: [] version>=10.12>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/mysql-utilities/1.6.5>, @language=nil>>, @directives={:pkgutil=>"com.oracle.mysql.utilities", :signal=>[]}>, #<Cask::Artifact::Pkg:0x00007fd070286db8 @cask=#<Cask::Cask:0x00007fd06f876328 @token="mysql-utilities", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/mysql-utilities.rb>, @tap=#<Tap:0x00007fd06f1cd878 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fd06f8760a8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/mysql-utilities.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/mysql-utilities>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/mysql-utilities/.metadata>, @config=#<Cask::Config:0x00007fd06f87d268 @explicit={}>, @dsl=#<Cask::DSL:0x00007fd06f87d0b0 @cask=#<Cask::Cask:0x00007fd06f876328 ...>, @token="mysql-utilities", @version="1.6.5", @sha256="114658256e846b4eeff141065e18ef3f779bcbe59e5d2828ab920d905e693db7", @url=#<URL:0x00007fd06f87cd18 @uri=#<URI::HTTPS https://downloads.mysql.com/archives/get/p/30/file/mysql-utilities-1.6.5-macos10.12.dmg>, @user_agent=:default, @specs={}>, @name=["MySQL Utilities"], @homepage="https://dev.mysql.com/downloads/utilities/", @depends_on={:macos=>#<MacOSRequirement: [] version>=10.12>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/mysql-utilities/1.6.5>, @language=nil>>, @path=#<Pathname:/usr/local/Caskroom/mysql-utilities/1.6.5/mysql-utilities-1.6.5.pkg>, @stanza_options={}>}>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for mysql-utilities; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- /usr/bin/env LOGNAME=markh USER=markh USERNAME=markh /usr/sbin/installer -pkg /usr/local/Caskroom/mysql-utilities/1.6.5/mysql-utilities-1.6.5.pkg -target / -verboseR
Password:
installer: Package name is MySQL Utilities 1.6.5.
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing MySQL Utilities 1.6.5.…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)
==> Purging files for version 1.6.5 of Cask mysql-utilities
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=markh USER=markh USERNAME=markh /usr/sbin/installer -pkg /usr/local/Caskroom/mysql-utilities/1.6.5/mysql-utilities-1.6.5.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is MySQL Utilities 1.6.5.
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing MySQL Utilities 1.6.5.…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:150:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:140:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.14-14-g0404ce2
==> macOS
10.15.4
==> SIP
Enabled
==> Java
14, 13.0.2, 1.8.0_171
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3539 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3539 casks)
/usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk (32 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.38.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
adoptopenjdk/openjdk
caskroom/cask
exolnet/deprecated
henkrehorst/php
homebrew/cask
homebrew/core
homebrew/services
```

**Comment by miccal** [comment]
@mjhorninger do you get the same error if you run the command `brew cask install mysql-utilities --no-quarantine`?

**Comment by mjhorninger** [comment]
@miccal I get nearly identical output when I run with the --no-quarantine switch.

**Comment by miccal** [comment]
@mjhorninger how about if you download and install the `pkg` manually, does the install succeed?

**Comment by cbornhoft** [comment]
@miccal I rann into this exact issue yesterday. To answer your question, no it does not install from the pkg either. So it appears that 10.14 is the last version able to install just the utilities, without Workbench.

**Comment by miccal** [comment]
Thank you @cbornhoft for the information.

@vitorgalvao should `depends_on macos: '<= :mojave'` be added to `mysql-utilities`?

**Comment by vitorgalvao** [comment]
> should `depends_on macos: '<= :mojave'` be added to `mysql-utilities`?

Looks like it.
