### ISSUE TITLE
Installing cask lego-digital-designer fails

### ISSUE THREAD

**Issue by The-Judge** [Homebrew/homebrew-cask#83898]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I'm trying to install cask lego-digital-designer, which fails with none of the listed commonly known issues and is not fixed using the proposed fixing commands.

#### Command that failed

```
brew cask install lego-digital-designer
```

#### Output of command with `--force --verbose --debug`

```
~ $ brew cask install --force --verbose --debug lego-digital-designer
Updating Homebrew...
==> Downloading https://www.lego.com/assets/franchisesites/ldd/installer/SetupLDD-MAC-4_3_11.zip
Already downloaded: /Users/marcrichter/Library/Caches/Homebrew/downloads/890b9e0176365cc6a61edfe26b99cb37d012699989b61cd9971e539b68b0f811--SetupLDD-MAC-4_3_11.zip
==> Verifying SHA-256 checksum for Cask 'lego-digital-designer'.
==> Installing Cask lego-digital-designer
unzip -o /Users/marcrichter/Library/Caches/Homebrew/downloads/890b9e0176365cc6a61edfe26b99cb37d012699989b61cd9971e539b68b0f811--SetupLDD-MAC-4_3_11.zip -d /var/folders/fn/vyh4bf7n1l73k4pfypqdp2tm0000gp/T/d20200606-51448-q265fl
chmod +rw /var/folders/fn/vyh4bf7n1l73k4pfypqdp2tm0000gp/T/d20200606-51448-q265fl/LDD.pkg
cp -p /var/folders/fn/vyh4bf7n1l73k4pfypqdp2tm0000gp/T/d20200606-51448-q265fl/LDD.pkg /usr/local/Caskroom/lego-digital-designer/4.3.11/LDD.pkg
==> Running installer for lego-digital-designer; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is LEGO Digital Designer
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing LEGO Digital Designer…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)
==> Purging files for version 4.3.11 of Cask lego-digital-designer
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=marcrichter USER=marcrichter USERNAME=marcrichter /usr/sbin/installer -pkg /usr/local/Caskroom/lego-digital-designer/4.3.11/LDD.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is LEGO Digital Designer
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing LEGO Digital Designer…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. The package is attempting to install content to the system volume.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:150:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

#### Output of `brew cask doctor`

```
~ $ brew cask doctor
==> Homebrew Version
2.3.0-58-gaff92b3
==> macOS
10.15.5
==> SIP
Enabled
==> Java
14.0.1, 12.0.1, 1.8.0_252
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3570 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (153 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (149 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.39.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
~ $ brew tap
cloudfoundry/tap
heroku/brew
homebrew/cask
homebrew/cask-drivers
homebrew/cask-versions
homebrew/core
homebrew/services
```

**Comment by miccal** [comment]
Is the install successful if you install the `pkg` file manually?

**Comment by The-Judge** [comment]
No, it says:

<img width="732" alt="Screenshot 2020-06-09 at 00 09 10" src="https://user-images.githubusercontent.com/904987/84085275-8019c980-a9e5-11ea-89ff-193fcd4d6ce0.png">

IDK if apps, which aren't supported by the upstream installer in certain OS versions anymore, have to leave from homebrew or need to be marked to require a maximal version of MacOSX or anything - I do not expect this to magically work now - just meant to support cleaning up the homebrew environment :)

**Comment by miccal** [comment]
@vitorgalvao another that may need a `depends_on macos: '<= :mojave'`, although from the `homepage` it says MacOS 10.10 or higher:

<img width="545" alt="Screen Shot 2020-06-09 at 07 56 52" src="https://user-images.githubusercontent.com/6127163/84091415-e541df00-aa26-11ea-8c3c-6dd6aa3fc0ac.png">

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/84038
