### ISSUE TITLE
Error installing Virtualbox

### ISSUE THREAD

**Issue by Tcharl** [Homebrew/homebrew-cask#84525]
#### General troubleshooting steps

- [x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [ x] I ran `brew update-reset && brew update` and retried my command.
- [x ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Installing Virtualbox is failing

#### Command that failed

```
brew cask install virtualbox
```

#### Output of command with `--force --verbose --debug`

```
─ brew cask install virtualbox --force --verbose --debug
==> Caveats
virtualbox requires a kernel extension to work.
If the installation fails, retry after you enable it in:
  System Preferences → Security & Privacy → General

For more information, refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Downloading https://download.virtualbox.org/virtualbox/6.1.10/VirtualBox-6.1.10-138449-OSX.dmg
Already downloaded: /Users/charliemordant/Library/Caches/Homebrew/downloads/c72755717cb8af08f2e891092c51aa581f21d88c8c72b7682037fc679e0e6c04--VirtualBox-6.1.10-138449-OSX.dmg
==> Verifying SHA-256 checksum for Cask 'virtualbox'.
==> Installing Cask virtualbox
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/d20200617-29434-fpqsmz /Users/charliemordant/Library/Caches/Homebrew/downloads/c72755717cb8af08f2e891092c51aa581f21d88c8c72b7682037fc679e0e6c04--VirtualBox-6.1.10-138449-OSX.dmg
mkbom -s -i /var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/20200617-29434-168rsbs.list -- /var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/20200617-29434-cdmak2.bom
ditto --bom /var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/20200617-29434-cdmak2.bom -- /private/var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/d20200617-29434-fpqsmz/dmg.D7xUMX /var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/d20200617-29434-1n5xk1o
diskutil eject /private/var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/d20200617-29434-fpqsmz/dmg.D7xUMX
cp -pR /var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/d20200617-29434-1n5xk1o/VirtualBox.pkg /usr/local/Caskroom/virtualbox/6.1.10,138449/VirtualBox.pkg
cp -pR /var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/d20200617-29434-1n5xk1o/VirtualBox_Uninstall.tool /usr/local/Caskroom/virtualbox/6.1.10,138449/VirtualBox_Uninstall.tool
cp -pR /var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/d20200617-29434-1n5xk1o/UserManual.pdf /usr/local/Caskroom/virtualbox/6.1.10,138449/UserManual.pdf
chmod -Rf +w /var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/d20200617-29434-1n5xk1o
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is Oracle VM VirtualBox
installer: choices changes file '/var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/choices20200617-29434-h0ckvi.xml' applied
installer: Upgrading at base path /
installer:PHASE:Préparation à l’installation…
installer:PHASE:Préparation du disque…
installer:PHASE:Préparation de Oracle VM VirtualBox…
installer:PHASE:Attente de la fin des autres installations…
installer:PHASE:Configuration de l’installation…
installer:STATUS:
installer:%8.209987
installer:PHASE:Écriture des fichiers…
installer:%33.474082
installer:PHASE:Écriture des fichiers…
installer:%69.614319
installer:PHASE:Mise en place des éléments…
installer:%88.432654
installer:PHASE:Exécution des scripts du paquet…
installer:PHASE:Validation des paquets…
installer:%97.750000
installer: The upgrade failed. (Le programme d’installation a rencontré une erreur qui a provoqué l’échec de l’installation. Contactez l’éditeur du logiciel pour obtenir de l’aide. Une erreur s’est produite pendant l’exécution des scripts du paquet « VirtualBox.pkg ».)
==> Purging files for version 6.1.10,138449 of Cask virtualbox
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=charliemordant USER=charliemordant USERNAME=charliemordant /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/6.1.10,138449/VirtualBox.pkg -target / -verboseR -applyChoiceChangesXML /var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/choices20200617-29434-h0ckvi.xml` exited with 1. Here's the output:
installer: Package name is Oracle VM VirtualBox
installer: choices changes file '/var/folders/_y/sqwckzt1145390fxwmvb8c6r0000gn/T/choices20200617-29434-h0ckvi.xml' applied
installer: Upgrading at base path /
installer:PHASE:Préparation à l’installation…
installer:PHASE:Préparation du disque…
installer:PHASE:Préparation de Oracle VM VirtualBox…
installer:PHASE:Attente de la fin des autres installations…
installer:PHASE:Configuration de l’installation…
installer:STATUS:
installer:%8.209987
installer:PHASE:Écriture des fichiers…
installer:%33.474082
installer:PHASE:Écriture des fichiers…
installer:%69.614319
installer:PHASE:Mise en place des éléments…
installer:%88.432654
installer:PHASE:Exécution des scripts du paquet…
installer:PHASE:Validation des paquets…
installer:%97.750000
installer: The upgrade failed. (Le programme d’installation a rencontré une erreur qui a provoqué l’échec de l’installation. Contactez l’éditeur du logiciel pour obtenir de l’aide. Une erreur s’est produite pendant l’exécution des scripts du paquet « VirtualBox.pkg ».)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:70:in `block in with_choices_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:67:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:150:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.4.0-55-g94dbdaa
==> macOS
10.15.5
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3583 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1508 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.40.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
╰─ brew tap
atlassian/tap
buo/cask-upgrade
homebrew/cask
homebrew/cask-fonts
homebrew/core
homebrew/services
nektos/tap
```

**Comment by vitorgalvao** [comment]
> virtualbox requires a kernel extension to work.
If the installation fails, retry after you enable it in:
  System Preferences → Security & Privacy → General
>
> For more information, refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

Have you done that?

**Comment by Tcharl** [comment]
Yes I did

**Comment by vitorgalvao** [comment]
Can you install it manually?

**Comment by Tcharl** [comment]
Of course

**Comment by vitorgalvao** [comment]
> Of course

Were it “of course”, I wouldn’t have needed to ask the question. There are plenty of cases where the software is borked upstream and even a manual install doesn’t work.

*Have you tried it*, or are you *assuming* it works?

So far you’re the only report of this, which for such a popular software usually means the problem is likely on your setup, not Homebrew Cask. We need as much information as we can get.

**Comment by Tcharl** [comment]
Sure sure, sorry for the remark, I wouldn't have posted the ticket in that case.

**Comment by vitorgalvao** [comment]
I’ve just tried it on a clean VM and was unable to reproduce. Unless we get further reports on this, will have to consider it an issue on your side. Without working reproduction steps we can’t diagnose this.

**Comment by Tcharl** [comment]
If it works on your side it should come from my side...
Sorry for the inconvenience, I'll persist to identify what's going on...

Thank you very much for your time
