### ISSUE TITLE
Installing screenflow fails

### ISSUE THREAD

**Issue by 454de6e** [Homebrew/homebrew-cask#84783]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I tried to install the screenflow cask v9.0.4.

#### Command that failed

```
brew cask install screenflow
```

#### Output of command with `--force --verbose --debug`

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
netron

==> Downloading https://www.telestream.net/download-files/screenflow/9-0/ScreenFlow-9.0.4.dmg
Already downloaded: /Users/thilo/Library/Caches/Homebrew/downloads/77a12538df0fb2bd3079b39a461ccea88d2b9481a1c6afe4169bd4a9a0ff34b2--ScreenFlow-9.0.4.dmg
==> Verifying SHA-256 checksum for Cask 'screenflow'.
==> Installing Cask screenflow
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/6n/wt571hm916gd_sw1kmw45x2r0000gn/T/d20200621-4072-1rbyqll /Users/thilo/Library/Caches/Homebrew/downloads/77a12538df0fb2bd3079b39a461ccea88d2b9481a1c6afe4169bd4a9a0ff34b2--ScreenFlow-9.0.4.dmg
hdiutil convert -format UDTO -o /var/folders/6n/wt571hm916gd_sw1kmw45x2r0000gn/T/d20200621-4072-1rbyqll/77a12538df0fb2bd3079b39a461ccea88d2b9481a1c6afe4169bd4a9a0ff34b2--ScreenFlow-9.0.4.cdr /Users/thilo/Library/Caches/Homebrew/downloads/77a12538df0fb2bd3079b39a461ccea88d2b9481a1c6afe4169bd4a9a0ff34b2--ScreenFlow-9.0.4.dmg
hdiutil: convert failed - image not recognized
==> Purging files for version 9.0.4 of Cask screenflow
Error: Failure while executing; `hdiutil convert -format UDTO -o /var/folders/6n/wt571hm916gd_sw1kmw45x2r0000gn/T/d20200621-4072-1rbyqll/77a12538df0fb2bd3079b39a461ccea88d2b9481a1c6afe4169bd4a9a0ff34b2--ScreenFlow-9.0.4.cdr /Users/thilo/Library/Caches/Homebrew/downloads/77a12538df0fb2bd3079b39a461ccea88d2b9481a1c6afe4169bd4a9a0ff34b2--ScreenFlow-9.0.4.dmg` exited with 1. Here's the output:
hdiutil: convert failed - image not recognized

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:19:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:148:in `block in mount'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:126:in `mount'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:116:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:123:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:130:in `block in extract_nestedly'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:127:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:193:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:73:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:150:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.4.0-93-g634c457
==> macOS
10.15.5
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3586 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.40.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
github/gh
homebrew/bundle
homebrew/cask
homebrew/core
homebrew/services
```

**Comment by miccal** [comment]
This same error was in the logs for https://github.com/Homebrew/homebrew-cask/pull/84694:
```
Error: Failure while executing; `hdiutil convert -format UDTO -o /private/tmp/d20200619-3595-hm6u5m/77a12538df0fb2bd3079b39a461ccea88d2b9481a1c6afe4169bd4a9a0ff34b2--ScreenFlow-9.0.4.cdr /Users/travis/Library/Caches/Homebrew/downloads/77a12538df0fb2bd3079b39a461ccea88d2b9481a1c6afe4169bd4a9a0ff34b2--ScreenFlow-9.0.4.dmg` exited with 1. Here's the output:
230hdiutil: convert failed - image not recognized
```
I assume it has something to do withe the license agreement when you open the `dmg`.

Ping @ran-dall.

**Comment by 454de6e** [comment]
Today there is also a checksum mismatch:

```
==> Downloading https://www.telestream.net/download-files/screenflow/9-0/ScreenFlow-9.0.4.dmg
Already downloaded: /Users/thilo/Library/Caches/Homebrew/downloads/77a12538df0fb2bd3079b39a461ccea88d2b9481a1c6afe4169bd4a9a0ff34b2--ScreenFlow-9.0.4.dmg
==> Verifying SHA-256 checksum for Cask 'screenflow'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'screenflow' does not match.
Expected: 6e54638252c59ba707457d1be954e315c155d63d87291bc45054f77d76419d99
  Actual: 8bd025c385f58b1c1675a4095fa7dd6d30d2bb500803c2d206320a9eada82eaf
    File: /Users/thilo/Library/Caches/Homebrew/downloads/77a12538df0fb2bd3079b39a461ccea88d2b9481a1c6afe4169bd4a9a0ff34b2--ScreenFlow-9.0.4.dmg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
```

**Comment by ran-dall** [comment]
Thanks @miccal; I'll look into it.

**Comment by ran-dall** [comment]
It must have been an issue in the installer cause it does appear they updated in place and it works now. #84840 will close this.

```
brew cask reinstall https://raw.githubusercontent.com/ran-dall/homebrew-cask/cask_repair_update-screenflow/Casks/screenflow.rb
==> Downloading https://raw.githubusercontent.com/ran-dall/homebrew-cask/cask_repair_update-screenflow/Casks/scre
######################################################################## 100.0%
==> Downloading https://www.telestream.net/download-files/screenflow/9-0/ScreenFlow-9.0.4.dmg
Already downloaded: /Users/randall/Library/Caches/Homebrew/downloads/77a12538df0fb2bd3079b39a461ccea88d2b9481a1c6afe4169bd4a9a0ff34b2--ScreenFlow-9.0.4.dmg
==> Verifying SHA-256 checksum for Cask 'screenflow'.
==> Installing Cask screenflow
==> Moving App 'ScreenFlow.app' to '/Applications/ScreenFlow.app'.
🍺  screenflow was successfully installed!
```
