### ISSUE TITLE
Failed to install VirtualBox on macOS 11 Big Sur 

### ISSUE THREAD

**Issue by skhaz** [Homebrew/homebrew-cask#85435]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Failed to install VirtualBox on Big Sur

#### Command that failed

```
$ brew cask --force --verbose --debug reinstall virtualbox
```

#### Output of command with `--force --verbose --debug`

```
==> Caveats
virtualbox requires a kernel extension to work.
If the installation fails, retry after you enable it in:
  System Preferences → Security & Privacy → General

For more information, refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Downloading https://download.virtualbox.org/virtualbox/6.1.10/VirtualBox-6.1.10-138449-OSX.dmg
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/c72755717cb8af08f2e891092c51aa581f21d88c8c72b7682037fc679e0e6c04--VirtualBox-6.1.10-138449-OSX.dmg
==> Verifying SHA-256 checksum for Cask 'virtualbox'.
==> Installing Cask virtualbox
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/d20200705-944-j9var4 /Users/user/Library/Caches/Homebrew/downloads/c72755717cb8af08f2e891092c51aa581f21d88c8c72b7682037fc679e0e6c04--VirtualBox-6.1.10-138449-OSX.dmg
mkbom -s -i /var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/20200705-944-1h1vqu2.list -- /var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/20200705-944-cg936n.bom
ditto --bom /var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/20200705-944-cg936n.bom -- /private/var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/d20200705-944-j9var4/dmg.YeuNW3 /var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/d20200705-944-tq6din
diskutil eject /private/var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/d20200705-944-j9var4/dmg.YeuNW3
cp -pR /var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/d20200705-944-tq6din/VirtualBox.pkg /usr/local/Caskroom/virtualbox/6.1.10,138449/VirtualBox.pkg
cp -pR /var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/d20200705-944-tq6din/VirtualBox_Uninstall.tool /usr/local/Caskroom/virtualbox/6.1.10,138449/VirtualBox_Uninstall.tool
cp -pR /var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/d20200705-944-tq6din/UserManual.pdf /usr/local/Caskroom/virtualbox/6.1.10,138449/UserManual.pdf
chmod -Rf +w /var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/d20200705-944-tq6din
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is Oracle VM VirtualBox
installer: choices changes file '/var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/choices20200705-944-yvlkw0.xml' applied
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%6.405409
installer:PHASE:Writing files…
installer:%19.037456
installer:PHASE:Writing files…
installer:%62.410068
installer:PHASE:Running package scripts…
installer:%63.320791
installer:PHASE:Running package scripts…
installer:%68.106141
installer:PHASE:Registering package with system…
installer:%87.991483
installer:PHASE:Running package scripts…
installer:%88.902821
installer:PHASE:Running package scripts…
installer:%89.799508
installer:PHASE:Running package scripts…
installer:%90.699475
installer:PHASE:Running package scripts…
installer:%91.605934
installer:PHASE:Running package scripts…
installer:%92.122874
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “VirtualBox.pkg”.)
==> Purging files for version 6.1.10,138449 of Cask virtualbox
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=user USER=user USERNAME=user /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/6.1.10,138449/VirtualBox.pkg -target / -verboseR -applyChoiceChangesXML /var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/choices20200705-944-yvlkw0.xml` exited with 1. Here's the output:
installer: Package name is Oracle VM VirtualBox
installer: choices changes file '/var/folders/zh/jsc9rs7n1k30fg0hyvmgrt280000gn/T/choices20200705-944-yvlkw0.xml' applied
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%6.405409
installer:PHASE:Writing files…
installer:%19.037456
installer:PHASE:Writing files…
installer:%62.410068
installer:PHASE:Running package scripts…
installer:%63.320791
installer:PHASE:Running package scripts…
installer:%68.106141
installer:PHASE:Registering package with system…
installer:%87.991483
installer:PHASE:Running package scripts…
installer:%88.902821
installer:PHASE:Running package scripts…
installer:%89.799508
installer:PHASE:Running package scripts…
installer:%90.699475
installer:PHASE:Running package scripts…
installer:%91.605934
installer:PHASE:Running package scripts…
installer:%92.122874
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “VirtualBox.pkg”.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:70:in `block in with_choices_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:67:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:127:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:13:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:7:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:7:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:150:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.4.3
==> macOS
10.16
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3604 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.40.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

#### Extra information

When I start some VM I got this error on VirtualBox

<img width="532" alt="Screen Shot 2020-07-05 at 19 04 58" src="https://user-images.githubusercontent.com/46259/86543164-6f7c4680-bef2-11ea-9991-a7aa25af94ef.png">

**Comment by vitorgalvao** [comment]
We’re not supporting Big Sur yet. At this point It’s more likely the issue is with Virtualbox than with HBC.
