### ISSUE TITLE
Anaconda install fails with no error message

### ISSUE THREAD

**Issue by wrmarchetto** [Homebrew/homebrew-cask#86008]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Installing anaconda (and miniconda) fails without reporting any useful error message.

#### Command that failed

```
brew cask install anaconda
```

#### Output of command with `--force --verbose --debug`

```
➜ brew cask install anaconda --force --verbose --debug
==> Caveats
Cask anaconda installs files under /usr/local. The presence of such
files can cause warnings when running `brew doctor`, which is considered
to be a bug in Homebrew Cask.

==> Downloading https://repo.anaconda.com/archive/Anaconda3-2020.02-MacOSX-x86_64.sh
Already downloaded: /Users/wmarche/Library/Caches/Homebrew/downloads/83f65b1b3e63e584c1259ea478ed5e171c7b65ae7358bb80a821f6a222dad6fe--Anaconda3-2020.02-MacOSX-x86_64.sh
==> Verifying SHA-256 checksum for Cask 'anaconda'.
==> Installing Cask anaconda
cp -p /Users/wmarche/Library/Caches/Homebrew/downloads/83f65b1b3e63e584c1259ea478ed5e171c7b65ae7358bb80a821f6a222dad6fe--Anaconda3-2020.02-MacOSX-x86_64.sh /usr/local/Caskroom/anaconda/2020.02/Anaconda3-2020.02-MacOSX-x86_64.sh
==> Running installer script 'Anaconda3-2020.02-MacOSX-x86_64.sh'
PREFIX=/usr/local/anaconda3
Unpacking payload ...
==> Purging files for version 2020.02 of Cask anaconda
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/anaconda/2020.02/Anaconda3-2020.02-MacOSX-x86_64.sh -b -p /usr/local/anaconda3` exited with 1. Here's the output:
PREFIX=/usr/local/anaconda3
Unpacking payload ...

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/installer.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:150:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
```

#### Output of `brew cask doctor`

```
➜ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/iverilog/_pli_types.h
  /usr/local/include/iverilog/acc_user.h
  /usr/local/include/iverilog/ivl_target.h
  /usr/local/include/iverilog/sv_vpi_user.h
  /usr/local/include/iverilog/veriuser.h
  /usr/local/include/iverilog/vpi_user.h

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libveriuser.a
  /usr/local/lib/libvpi.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  maven

Warning: Your Xcode (10.3) is outdated.
Please update to Xcode 11.3.1 (or delete it).
Xcode can be updated from the App Store.
```

#### Output of `brew tap`

```
➜ brew tap
homebrew/cask
homebrew/core
jcgay/jcgay
```

**Comment by miccal** [comment]
Possibly related to the points raised in https://github.com/Homebrew/homebrew-cask/pull/85456

**Comment by vitorgalvao** [comment]
Can’t reproduce on a clean VM. You should try to fix the `brew cask doctor` errors starting with the last one.
