### ISSUE TITLE
soapui 5.6.0 fails to install

### ISSUE THREAD

**Issue by jyeary** [Homebrew/homebrew-cask#86020]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The SOAP UI installation failed to install with the follwing response: “SoapUI 5.6.0 Installer” can’t be opened because Apple cannot check it for malicious software.

#### Command that failed

```
brew cask upgrade soapui
```

#### Output of command with `--force --verbose --debug`

```
==> Upgrading 1 outdated package:
soapui 5.5.0 -> 5.6.0
==> Upgrading soapui
==> Downloading https://s3.amazonaws.com/downloads.eviware/soapuios/5.6.0/SoapUI-5.6.0.dmg
Already downloaded: /Users/jyeary/Library/Caches/Homebrew/downloads/8d6096e0c19a7145887d9cd8cf23793653cc40f942d3e7ed0b13dbb7fafd9428--SoapUI-5.6.0.dmg
==> Verifying SHA-256 checksum for Cask 'soapui'.
==> Trashing files:
/Applications/SoapUI-5.5.0.app
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/bh/wpny4jt91dx10ybn6x3jpbbr0000gn/T/d20200715-13870-wiyss0 /Users/jyeary/Library/Caches/Homebrew/downloads/8d6096e0c19a7145887d9cd8cf23793653cc40f942d3e7ed0b13dbb7fafd9428--SoapUI-5.6.0.dmg
mkbom -s -i /var/folders/bh/wpny4jt91dx10ybn6x3jpbbr0000gn/T/20200715-13870-envwcq.list -- /var/folders/bh/wpny4jt91dx10ybn6x3jpbbr0000gn/T/20200715-13870-jco09y.bom
ditto --bom /var/folders/bh/wpny4jt91dx10ybn6x3jpbbr0000gn/T/20200715-13870-jco09y.bom -- /private/var/folders/bh/wpny4jt91dx10ybn6x3jpbbr0000gn/T/d20200715-13870-wiyss0/dmg.Ltokbw /var/folders/bh/wpny4jt91dx10ybn6x3jpbbr0000gn/T/d20200715-13870-1dmivkj
diskutil eject /private/var/folders/bh/wpny4jt91dx10ybn6x3jpbbr0000gn/T/d20200715-13870-wiyss0/dmg.Ltokbw
cp -pR /var/folders/bh/wpny4jt91dx10ybn6x3jpbbr0000gn/T/d20200715-13870-1dmivkj/SoapUI\ 5.6.0\ Installer.app/. /usr/local/Caskroom/soapui/5.6.0/SoapUI\ 5.6.0\ Installer.app
chmod -Rf +w /var/folders/bh/wpny4jt91dx10ybn6x3jpbbr0000gn/T/d20200715-13870-1dmivkj
==> Running installer script 'SoapUI 5.6.0 Installer.app/Contents/MacOS/JavaApplicationStub'
==> Purging files for version 5.6.0 of Cask soapui
==> Purging files for version 5.6.0 of Cask soapui
Warning: Reverting upgrade for Cask soapui
==> Running installer script 'SoapUI 5.5.0 Installer.app/Contents/MacOS/JavaApplicationStub'
The installation directory has been set to /Applications.
Extracting files ...
Finishing installation ...
Error: Failure while executing; `/usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/soapui/5.6.0/SoapUI\ 5.6.0\ Installer.app/Contents/MacOS/JavaApplicationStub -q -VcreateDesktopLinkAction\$Boolean=false -Vsys.component.132\$Boolean=true -Vsys.component.714\$Boolean=false -Vsys.component.1263\$Boolean=false -Vsys.component.2393\$Boolean=false -VshowFileAction\$Boolean=false -Vsys.installationDir=/Applications -VexecutionLauncherAction\$Boolean=false` exited with .
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/installer.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:101:in `upgrade_cask'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:48:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:47:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:47:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:150:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.4.7-25-g474c1ab
==> macOS
10.15.5
==> SIP
Enabled
==> Java
11.0.7, 1.8.0_251, 1.7.0_181, 1.7.0_80
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3616 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (155 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.42.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/cask-versions
homebrew/core

```

**Comment by miccal** [comment]
Does the install succeed if you pass the `--no-quarantine` flag?

**Comment by jyeary** [comment]
Yes, I was able to do install it with that flag. I was unaware of that flag. That was the first time I have ever needed to use it. Thank you. 

Shouldn't you be able to install without it though?

**Comment by miccal** [comment]
Please see https://github.com/Homebrew/homebrew-cask/issues/70798 for a discussion about this.

**Comment by vitorgalvao** [comment]
> Shouldn't you be able to install without it though?

If we made a exception to this cask, that would defeat the purpose of adding the quarantine. We could made it clearer that’s the issue, though, but considering https://github.com/Homebrew/homebrew-cask/issues/70798, closing.
