### ISSUE TITLE
Unable to install qbittorrent cask

### ISSUE THREAD

**Issue by DukeNuke3D** [Homebrew/homebrew-cask#86455]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Tried to install qbittorrent cask, but failed.

#### Command that failed

```
brew cask install qbittorrent
```

#### Output of command with `--force --verbose --debug`

```
andrei-macbook:~ andreyv$ brew cask install qbittorrent --force --verbose --debug
Updating Homebrew...
==> Downloading https://downloads.sourceforge.net/qbittorrent/qbittorrent-mac/qbittorrent-4.2.5/qbittorrent-4.2.5.dmg
Already downloaded: /Users/andreyv/Library/Caches/Homebrew/downloads/cfcd10dfa915cc2a3e6b5749b8a9d1df12ddf8bc737bf65df54ad7b5270d927a--
==> Verifying SHA-256 checksum for Cask 'qbittorrent'.
Error: Is a directory @ io_fread - /Users/andreyv/Library/Caches/Homebrew/downloads/cfcd10dfa915cc2a3e6b5749b8a9d1df12ddf8bc737bf65df54ad7b5270d927a--
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/digest.rb:52:in `read'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/digest.rb:52:in `block in file'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/digest.rb:50:in `open'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/digest.rb:50:in `file'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/digest.rb:35:in `file'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:268:in `sha256'
/usr/local/Homebrew/Library/Homebrew/cask/verify.rb:16:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:165:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:63:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:149:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:91:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
```

#### Output of `brew cask doctor`

```
andrei-macbook:~ andreyv$ brew cask doctor
==> Homebrew Version
2.4.8-96-gc9fac7c
==> macOS
10.14.6
==> SIP
Enabled
==> Java
N/A
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3623 casks)
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.42.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
```

#### Output of `brew tap`

```
andrei-macbook:~ andreyv$ brew tap
domt4/autoupdate
homebrew/cask
homebrew/core
```

Additional info:
```
andrei-macbook:~ andreyv$ ls -la /Users/andreyv/Library/Caches/Homebrew/downloads/
total 2137432
drwxr-xr-x  46 andreyv  staff       1472 Jul 23 22:08 .
drwxrwxr-x  41 andreyv  staff       1312 Jul 23 22:10 ..
-rw-r--r--   1 andreyv  staff    3695826 Oct  7  2019 024878bdabbcb44445c8148cb8d4d14e37f5db23b0457f2627227dff73179f0f--libsmi-0.5.0.mojave.bottle.1.tar.gz
-rw-r--r--   1 andreyv  staff   22481289 Jul  3 23:10 0543689dea4a0be820e4272eb9b9da1d5943200b345b2a3dabbcab89dfe1a735--wireshark-3.2.5.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff     225130 Apr 11 19:22 0946d4b50026b3d1cd85a3f31de4efe767830b4f0c5be62a17068546a1354180--libssh-0.9.4.mojave.bottle.tar.gz
-rw-r--r--@  1 andreyv  staff   10712521 Jun 28 03:03 0e4eeca9868917657b85ac8a334a543b9c4a05e2f3cd83ba3db523680330ff23--Rectangle0.31.dmg
-rw-r--r--   1 andreyv  staff     632272 Mar 27 15:48 167905dce9f2f9b715a4a045be8553ca0e1e5e0400274930f21e5414a9c04126--jemalloc-5.2.1_1.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff      53976 Nov  2  2019 204deab489e48fd9e3ebb5a3c2b298a24d4e25741b8b8d2dce69eda0a219be99--libmaxminddb-1.4.2.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff     195805 Jan  6  2019 20f9ece6784339b39c45c635874b0c85ab3c27f1bf267124cb16fb475baac429--geoip-1.6.12.mojave.bottle.1.tar.gz
-rw-r--r--@  1 andreyv  staff    2354382 Nov 20  2019 2654d6df24c405ee18f730f678627cbeb437ba903c37a01445335ad602276fa1--Flux40.1.zip
-rw-r--r--@  1 andreyv  staff   97687693 Jul  2 01:40 27b7f2f20a413d9e694640a88fa36d00152d6522a0fdefe74c88ccad2a398209--Wireshark 3.2.5 Intel 64.dmg
-rw-r--r--   1 andreyv  staff    1077362 Jul  8 22:28 2fc45ced3dfb0ecca9cb47a26a01eb55697b7a78de9351f88279414ba5f98afa--libgcrypt-1.8.6.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff      46594 May 25 05:14 302b334b616b5a0b6e3093aaa0c74deac495c749ae28c5bb16af385726a79179--subnetcalc-2.4.16.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff    1898493 Feb 13 11:47 3625a6ca886805f69e8445862d4534ebd5119ede8cc536a1422f0a622ffe567f--pcre-8.44.mojave.bottle.tar.gz
-rw-r--r--@  1 andreyv  staff  167978550 Mar 19 18:09 369e881ed8ac3e80077d07412416ca8cdce985ec2fa8f8a61866bb352cbb8585--gimp-2.10.14-x86_64.dmg
-rw-r--r--@  1 andreyv  staff  133901706 Jun  2 00:25 390a5399c69fd097a99e0937732762f2a47e98fdc1d3dfa431dbe118d30b49b9--Winbox-mac-3.24.1.zip
-rw-r--r--   1 andreyv  staff     307754 May 31 21:06 392f14f3052e41a1278d439c65860860c613684f69e45452efdef84d901900b3--libgpg-error-1.38.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff     716036 Apr 18 18:25 40a6076183eecf02af9df336b97b5cc956d15f7f5b2feacc2a4a4b2d44fbb4fd--p11-kit-0.23.20_1.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff     200907 Jan  6  2019 440b98240182d9fb5393666ca9f5411d864e84cbe189634ead14754dc3dd3712--gdbm-1.18.1.mojave.bottle.1.tar.gz
-rw-r--r--@  1 andreyv  staff   78319241 Jun 28 07:02 4b3789925b23ac79411ad83ead6cda76f818c1d8399e17c6014b980a8872d63c--TorBrowser-9.5.1-osx64_en-US.dmg
-rw-r--r--   1 andreyv  staff     168940 May 12 11:06 5178e487267097c70633833655ef9afabbaddb1538f726c610358daaa39462a0--c-ares-1.16.1.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff     103313 Aug 21  2018 5a099ccb290b74f1eeea182e0f66af89ae050352104201ff602b3aa55727aecb--lua@5.1-5.1.5_8.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff     878505 May 13 12:10 62806a7464873b0693f86540a009db657c0e95cb301fc11e5037e235b715fb41--nettle-3.6.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff    2029032 Jul  3 21:07 67392545443e249708c1d7c3f8e2ff70f148e3af4fcff1529b48c71d95c5b040--sqlite-3.32.3.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff    5551994 Apr 21 19:33 6e3ef678544db80c666b0bbc24b33d6d8887a773110106fd9a306c7e76abd222--openssl@1.1-1.1.1g.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff    1047237 Feb 18 23:18 79bc3a2e40e33dba8b52be4f2fc7ed03f8bddd913fbcd428997212a44457ebc6--gmp-6.2.0.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff     697419 Jul 12 08:34 81646bd5c7345e3024b067adef77a4965de7f1d7f3a8fe77bd15937a1d12f249--libevent-2.1.12.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff     124839 Feb  2 13:37 82512269552c69ed425229332614f17a45f36acc15ebb0b1a18b662e9a8d7963--libtasn1-4.16.0.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff    3513806 Oct 13  2019 943d8c12817ffa3836049f76d50e3731d1cf2b8f6dbc5df867ac6a006c824199--ipv6calc-2.2.0.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff     163384 Apr 18 18:18 9516741d931b4f8df4cada0a29d44693c9a49b9472a2ea9a85685eebf7bf3414--libffi-3.3.mojave.bottle.tar.gz
-rw-r--r--@  1 andreyv  staff   33630334 Jul  7 23:55 9ac994af34dd5e1ba42fdde28b68f73e2069a0bc92ad9506de6511d581d1ce68--KeePassXC-2.6.0.dmg
-rw-r--r--   1 andreyv  staff      63637 May 11 20:06 9c5d7c42d1142350c45be957dffb33def05ad97aee8982ca8a8a51de30b6ecc1--jansson-2.13.1.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff    4811125 Jul 12 02:38 9fbb7dcb8b453a278eb3a6df9a4553780a5514c97cd6c79c9bb4eda0245314b9--glib-2.64.4.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff    2640232 May 23 05:14 a34b03ce60028ffd81dad50fd1d169a2e9f5aff82f5fdd1fa89762178e7d16b5--unbound-1.10.1.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff    3188524 Jun  4 15:08 ae4c596b6ef165073d2dbef87585c9d1b0acb40f13b61086589f025352b9b31c--gnutls-3.6.14.mojave.bottle.tar.gz
-rw-r--r--@  1 andreyv  staff   49753040 Jun 23 13:45 be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg
-rw-r--r--@  1 andreyv  staff  106395080 Jul  8 13:21 c586e4bbf060f4096b89fa21b9379f2b5a1711cbae5156e6500ecbd4ae2497fa--Skype-8.62.0.85.dmg
drwxr-xr-x@  4 andreyv  staff        128 Jul 23 22:13 cfcd10dfa915cc2a3e6b5749b8a9d1df12ddf8bc737bf65df54ad7b5270d927a--
-rw-r--r--   1 andreyv  staff     985050 Jun  2 20:06 dddee6bd127b5adb6e259083d61b97ca8b1babb3caca56517295bed623df1d1c--nghttp2-1.41.0.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff   17436410 Jul 22 15:49 de7f5080226b1adf791bf431f04e17653c464823ed2bf587a577ce57f86ca735--python@3.8-3.8.5.mojave.bottle.tar.gz
-rw-r--r--@  1 andreyv  staff   14724050 May 23 04:35 e4facc51b614a05bd0c57a8da092bbfd000b549976889accc566fd2938c90826--Tunnelblick_3.8.2a_build_5481.dmg
-rw-r--r--   1 andreyv  staff     396070 Mar 18 16:53 e825d8d7c93de7b74f996f3d78be101a73d60e0b69cfba0fe216c422efd37626--xz-5.2.5.mojave.bottle.tar.gz
-rw-r--r--@  1 andreyv  staff  261968563 Jun 27 01:28 e98b82afe63e214fb2f17fe4178e95687494fc353a846ba358a95ec64d9ca90c--LibreOffice_6.4.5_MacOS_x86-64.dmg
-rw-r--r--   1 andreyv  staff    8852090 Apr 22 12:49 ea566debb013c2c2985ee6cc51dcb598cce51be8c0a4a2508acea9029a56b4a5--gettext-0.20.2_1.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff     148330 Mar 20 19:53 ee8f617650782784c03a782b5af008758b48b19f5da2faf39e9fb6301a0aabc0--libev-4.33.mojave.bottle.tar.gz
-rw-r--r--   1 andreyv  staff     530044 Feb 20 11:52 f9f38ab9709e6df1096d3cd10f1928814426b9d961f75297c2dc74466b4b08ea--readline-8.0.4.mojave.bottle.tar.gz
andrei-macbook:~ andreyv$ ls -la /Users/andreyv/Library/Caches/Homebrew/downloads/cfcd10dfa915cc2a3e6b5749b8a9d1df12ddf8bc737bf65df54ad7b5270d927a--
total 8
drwxr-xr-x@  4 andreyv  staff   128 Jul 23 22:13 .
drwxr-xr-x  46 andreyv  staff  1472 Jul 23 22:08 ..
-rw-r--r--   1 andreyv  staff   746 Jul 23 10:30 .incomplete
lrwxr-xr-x   1 andreyv  staff    79 Jul 23 22:13 cfcd10dfa915cc2a3e6b5749b8a9d1df12ddf8bc737bf65df54ad7b5270d927a-- -> ../downloads/cfcd10dfa915cc2a3e6b5749b8a9d1df12ddf8bc737bf65df54ad7b5270d927a--
```

**Comment by miccal** [comment]
I believe SourceForge are having numerous issue at the moment, and this could just be a temporary issue.

**Comment by DukeNuke3D** [comment]
True, today worked well
