### ISSUE TITLE
Unexpected method 'license' called on Cask wch-ch34x-usb-serial-driver

### ISSUE THREAD

**Issue by bmfkai** [Homebrew/homebrew-cask#86754]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

brew upgrade is reporting this:
Warning: Unexpected method 'license' called on Cask wch-ch34x-usb-serial-driver.

#### Command that failed

```
brew upgrade
brew doctor
```

#### Output of command with `--force --verbose --debug`

```
> brew upgrade --force --verbose --debug
...
Warning: Unexpected method 'license' called on Cask wch-ch34x-usb-serial-driver.

> brew doctor --verbose --debug
Error: Cask 'wch-ch34x-usb-serial-driver' is unreadable: undefined method `method_missing_message' for Utils:Module
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:66:in `rescue in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:61:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:36:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:32:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:32:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:49:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
```

#### Output of `brew cask doctor`

```
❯ brew cask doctor
==> Homebrew Version
2.4.9-61-g2b33f99
==> macOS
10.15.6
==> SIP
Enabled
==> Java
N/A
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3629 casks)
/usr/local/Homebrew/Library/Taps/alehouse/homebrew-unofficial (45 casks)
/usr/local/Homebrew/Library/Taps/adrianmihalko/homebrew-ch340g-ch34g-ch34x-mac-os-x-driver (1 cask)
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.42.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
Unknown support status
Error: There are some problems with your setup.
```

#### Output of `brew tap`

```
adrianmihalko/ch340g-ch34g-ch34x-mac-os-x-driver
alehouse/unofficial
aws/tap
homebrew/cask
homebrew/core
homebrew/services
sambadevi/powerlevel9k
tdsmith/ham
```

**Comment by vitorgalvao** [comment]
You need to report this to https://github.com/adrianmihalko/ch340g-ch34g-ch34x-mac-os-x-driver, as they’re the ones with [the bad cask](https://github.com/adrianmihalko/ch340g-ch34g-ch34x-mac-os-x-driver/blob/master/Casks/wch-ch34x-usb-serial-driver.rb).

`license` hasn’t been a valid stanza in years.
