### ISSUE TITLE
My cask is broken and not fixed by normal troubleshooting steps

### ISSUE THREAD

**Issue by tylerweitzman** [Homebrew/homebrew-cask#87133]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

No matter what command I run, I get `Error: Cask 'fastlane' is unavailable: No Cask with this name exists.`

I get it when I run `brew cask list`, `brew doctor`, etc.

#### Output of command with `--force --verbose --debug`
```
$ brew cask list --verbose --debug
Error: Cask 'fastlane' is unavailable: No Cask with this name exists.
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:175:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:184:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:40:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:32:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:32:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/list.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:153:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:95:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:95:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

```
$ brew doctor --verbose --debug
Error: Cask 'fastlane' is unavailable: No Cask with this name exists.
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:175:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:184:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:40:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:32:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:32:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:47:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew Version
2.4.9-250-gab9b15c
==> macOS
10.14.6
==> SIP
Enabled
==> Java
1.8.0_202, 1.8.0_151, 1.7.0_79
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3637 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (159 casks)
/usr/local/Homebrew/Library/Taps/peripheryapp/homebrew-periphery (1 cask)
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.42.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
```

#### Output of `brew tap`

```
$ brew tap
caskroom/versions
homebrew/cask
homebrew/core
peripheryapp/periphery
woshiccm/tap
```

**Comment by vitorgalvao** [comment]
```
brew cask uninstall --force fastlane
rm -rf "$(brew --caskroom)/fastlane"
```
