### ISSUE TITLE
`blue-jeans` casks should be named `bluejeans`

### ISSUE THREAD

**Issue by lsloan** [Homebrew/homebrew-cask#87954]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

When searching for BlueJeans casks to install, they are not found.  After finding the complete list of casks, I find that they are named `blue-jeans` instead of `bluejeans`.

Because the application and the company are named "BlueJeans", without spacing or punctuation, it would make sense to rename the cask `bluejeans`.

#### Command that failed

```
brew info bluejeans
```

#### Output of command with `--force --verbose --debug`

I received the usage for `brew info`, followed by:

```
Error: invalid option: --force
/Local/Library/Homebrew/cli/parser.rb:170:in `parse_remaining'
/Local/Library/Homebrew/cli/parser.rb:218:in `parse'
/Local/Library/Homebrew/compat/cli/parser.rb:23:in `parse'
/Local/Library/Homebrew/cmd/info.rb:64:in `info'
/Local/Library/Homebrew/brew.rb:119:in `<main>'
```

Without the `--force` option:

```
Error: No available formula with the name "bluejeans"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.4.13-27-gedefd9b
==> macOS
10.14.5
==> SIP
Enabled
==> Java
1.8.0_65, 1.7.0_25
==> Homebrew Cask Staging Location
/Local/Caskroom
==> Homebrew Cask Taps:
/Local/Library/Taps/homebrew/homebrew-cask (3636 casks)
==> $LOAD_PATHS
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.43.1/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.7.1/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.7.0/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.1/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.2/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.2/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.3/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/regexp_parser-1.7.1/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.2.0/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.7.1.4/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.19.2/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-4.0.0/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2020.0512/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.2/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.7/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.4.4/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.3/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.18.5/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.12.2/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.3.1/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/byebug-11.1.3/lib
/Local/Library/Homebrew/vendor/bundle/bundler/
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.1/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.2/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.0/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.14.1/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/Local/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/Local/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0
/Local/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/x86_64-darwin14
/Local/Library/Homebrew
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
jmhobbs/parrot
```

**Comment by lsloan** [comment]
> @Isloan it seems to me that the functionality of the `blue-jeans-browser-plugin` is now included as part of the `.app`, as this is no longer listed as an [add-on or an extension](https://support.bluejeans.com/s/topic/0TO2R000000kajKWAQ/addons-extensions).
> 
> Do you think it is safe to remove?

I'm not qualified to say whether the functionality of `blue-jeans-browser-plugin` is now included as part of `blue-jeans`.  My issue is mostly about the naming of `blue-jeans` should be `bluejeans`.  That applies to the `blue-jeans.rb` formula and any others that relate to the BlueJeans application.

Even if `blue-jeans.rb` is the only remaining formula that relates to BlueJeans, this issue should remain open until the renaming of the issue is resolved.

**Comment by miccal** [comment]
> I'm not qualified to say whether the functionality of `blue-jeans-browser-plugin` is now included as part of `blue-jeans`. My issue is mostly about the naming of `blue-jeans` should be `bluejeans`. That applies to the `blue-jeans.rb` formula and any others that relate to the BlueJeans application.
> 
> Even if `blue-jeans.rb` is the only remaining formula that relates to BlueJeans, this issue should remain open until the renaming of the issue is resolved.

[`blue-jeans` has already been re-named to `bluejeans`.](https://github.com/Homebrew/homebrew-cask/pull/87989)
