### ISSUE TITLE
All commands broken with "uninitialized constant URL::T (NameError)"

### ISSUE THREAD

**Issue by gkze** [Homebrew/homebrew-cask#90710]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Hi, my Homebrew installation suddenly broke this morning. None of the commands seem to work, as they all fail with the same stack trace.

#### Command that failed

```
brew
```

#### Output of command with `--force --verbose --debug`

<details>

```
+ [[ -z '' ]]
+ [[ -z '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export HOMEBREW_UPDATE_TO_TAG=1
+ HOMEBREW_UPDATE_TO_TAG=1
+ [[ -z '' ]]
+ HOMEBREW_AUTO_UPDATE_SECS=300
+ [[ -e /usr/local/Cellar ]]
+ [[ ! -w /usr/local/Cellar ]]
+ [[ ! -w /usr/local/Homebrew ]]
+ [[ -n '' ]]
+ git --version
+ [[ -n '' ]]
+ export GIT_TERMINAL_PROMPT=0
+ GIT_TERMINAL_PROMPT=0
+ export 'GIT_SSH_COMMAND=ssh -oBatchMode=yes'
+ GIT_SSH_COMMAND='ssh -oBatchMode=yes'
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -z 1 ]]
+ QUIET_ARGS=()
+ [[ -z '' ]]
+ CURL_DISABLE_CURLRC_ARGS=(-q)
+ lock update
+ local name=update
+ local lock_dir=/usr/local/var/homebrew/locks
+ local lock_file=/usr/local/var/homebrew/locks/update
+ [[ -d /usr/local/var/homebrew/locks ]]
+ [[ -w /usr/local/var/homebrew/locks ]]
+ exec
+ exec
+ _create_lock 200 update
+ local lock_fd=200
+ local name=update
+ local ruby=/usr/bin/ruby
+ local python=/usr/bin/python
+ [[ -x /usr/bin/ruby ]]
+ [[ -x /usr/bin/python ]]
+ [[ -x /usr/bin/ruby ]]
+ /usr/bin/ruby -e 'exit(RUBY_VERSION >= '\''1.8.7'\'')'
+ /usr/bin/ruby -e 'File.new(200).flock(File::LOCK_EX | File::LOCK_NB) || exit(1)'
+ git_init_if_necessary
+ safe_cd /usr/local/Homebrew
+ cd /usr/local/Homebrew
+ [[ ! -d .git ]]
+ [[ -d /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core ]]
+ return
+ [[ https://github.com/Homebrew/brew != \h\t\t\p\s\:\/\/\g\i\t\h\u\b\.\c\o\m\/\H\o\m\e\b\r\e\w\/\b\r\e\w ]]
+ [[ https://github.com/Homebrew/homebrew-core != \h\t\t\p\s\:\/\/\g\i\t\h\u\b\.\c\o\m\/\H\o\m\e\b\r\e\w\/\h\o\m\e\b\r\e\w\-\c\o\r\e ]]
+ safe_cd /usr/local/Homebrew
+ cd /usr/local/Homebrew
+ [[ -n '' ]]
+ trap '{ /usr/bin/pkill -P $$; wait; exit 130; }' SIGINT
+ local update_failed_file=/usr/local/Homebrew/.git/UPDATE_FAILED
+ rm -f /usr/local/Homebrew/.git/UPDATE_FAILED
+ for DIR in '"$HOMEBREW_REPOSITORY"' '"$HOMEBREW_LIBRARY"/Taps/*/*'
+ [[ -d /usr/local/Homebrew/.git ]]
+ cd /usr/local/Homebrew
+ [[ -n 1 ]]
+ echo 'Checking if we need to fetch /usr/local/Homebrew...'
Checking if we need to fetch /usr/local/Homebrew...
++ repo_var /usr/local/Homebrew
++ local repo_var
++ repo_var=/usr/local/Homebrew
++ [[ /usr/local/Homebrew = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
++ repo_var=
++ echo ''
+ TAP_VAR=
++ upstream_branch
++ local upstream_branch
+++ git symbolic-ref refs/remotes/origin/HEAD
++ upstream_branch=refs/remotes/origin/master
++ [[ -z refs/remotes/origin/master ]]
++ upstream_branch=master
++ [[ -z master ]]
++ echo master
+ UPSTREAM_BRANCH_DIR=master
+ declare UPSTREAM_BRANCH=master
++ git rev-parse -q --verify refs/remotes/origin/master
++ [[ -z /Applications/Xcode.app/Contents/Developer/usr/bin/git ]]
++ /Applications/Xcode.app/Contents/Developer/usr/bin/git rev-parse -q --verify refs/remotes/origin/master
+ declare PREFETCH_REVISION=b8a93279fd31b0569a9046f61df0da0121ce4df5
+ [[ /usr/local/Homebrew = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
++ git tag --list
++ [[ -z /Applications/Xcode.app/Contents/Developer/usr/bin/git ]]
++ /Applications/Xcode.app/Contents/Developer/usr/bin/git tag --list
+ [[ -z 0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.7.1
0.8
0.8.1
0.9
0.9.1
0.9.2
0.9.3
0.9.4
0.9.5
0.9.8
0.9.9
1.0.0
1.0.1
1.0.2
1.0.3
1.0.4
1.0.5
1.0.6
1.0.7
1.0.8
1.0.9
1.1.0
1.1.1
1.1.10
1.1.11
1.1.12
1.1.13
1.1.2
1.1.3
1.1.4
1.1.5
1.1.6
1.1.7
1.1.8
1.1.9
1.2.0
1.2.1
1.2.2
1.2.3
1.2.4
1.2.5
1.2.6
1.3.0
1.3.1
1.3.2
1.3.3
1.3.4
1.3.5
1.3.6
1.3.7
1.3.8
1.3.9
1.4.0
1.4.1
1.4.2
1.4.3
1.5.0
1.5.1
1.5.10
1.5.11
1.5.12
1.5.13
1.5.14
1.5.2
1.5.3
1.5.4
1.5.5
1.5.6
1.5.7
1.5.8
1.5.9
1.6.0
1.6.1
1.6.10
1.6.11
1.6.12
1.6.13
1.6.14
1.6.15
1.6.16
1.6.17
1.6.2
1.6.3
1.6.4
1.6.5
1.6.6
1.6.7
1.6.8
1.6.9
1.7.0
1.7.1
1.7.2
1.7.3
1.7.4
1.7.5
1.7.6
1.7.7
1.8.0
1.8.1
1.8.2
1.8.3
1.8.4
1.8.5
1.8.6
1.9.0
1.9.1
1.9.2
1.9.3
2.0.0
2.0.1
2.0.2
2.0.3
2.0.4
2.0.5
2.0.6
2.1.0
2.1.1
2.1.10
2.1.11
2.1.12
2.1.13
2.1.14
2.1.15
2.1.16
2.1.2
2.1.3
2.1.4
2.1.5
2.1.6
2.1.7
2.1.8
2.1.9
2.2.0
2.2.1
2.2.10
2.2.11
2.2.12
2.2.13
2.2.14
2.2.15
2.2.16
2.2.17
2.2.2
2.2.3
2.2.4
2.2.5
2.2.6
2.2.7
2.2.8
2.2.9
2.3.0
2.4.0
2.4.1
2.4.10
2.4.11
2.4.12
2.4.13
2.4.14
2.4.15
2.4.16
2.4.2
2.4.3
2.4.4
2.4.5
2.4.6
2.4.7
2.4.8
2.4.9
2.5.0
2.5.1
2.5.2
2.5.3
2.5.4
2.5.5
2.5.6 ]]
+ [[ -z 1 ]]
+ for DIR in '"$HOMEBREW_REPOSITORY"' '"$HOMEBREW_LIBRARY"/Taps/*/*'
+ [[ -d /usr/local/Homebrew/Library/Taps/*/*/.git ]]
+ continue
+ wait
++ git config remote.origin.url
++ [[ -z /Applications/Xcode.app/Contents/Developer/usr/bin/git ]]
++ /Applications/Xcode.app/Contents/Developer/usr/bin/git config remote.origin.url
+ UPSTREAM_REPOSITORY_URL=https://github.com/Homebrew/brew
+ [[ https://github.com/Homebrew/brew = \h\t\t\p\s\:\/\/\g\i\t\h\u\b\.\c\o\m\/* ]]
+ UPSTREAM_REPOSITORY=Homebrew/brew
+ UPSTREAM_REPOSITORY=Homebrew/brew
+ [[ /usr/local/Homebrew = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
+ [[ -n 1 ]]
++ sed -n 's/^ETag: "\([a-f0-9]\{32\}\)".*/\1/p' .git/GITHUB_HEADERS
+ GITHUB_API_ETAG=
+ GITHUB_API_ACCEPT=application/vnd.github.v3+json
+ GITHUB_API_ENDPOINT=tags
++ curl -q --silent --max-time 3 --location --output /dev/null --write-out '%{http_code}' --dump-header /usr/local/Homebrew/.git/GITHUB_HEADERS --user-agent 'Homebrew/2.5.6-2-gb8a9327 (Macintosh; Intel Mac OS X 10.15.7) curl/7.64.1' --header 'Accept: application/vnd.github.v3+json' --header 'If-None-Match: ""' https://api.github.com/repos/Homebrew/brew/tags
+ UPSTREAM_SHA_HTTP_CODE=403
+ [[ -f /usr/local/Homebrew/.git/FETCH_HEAD ]]
+ touch /usr/local/Homebrew/.git/FETCH_HEAD
+ [[ -z 1 ]]
+ [[ -n 1 ]]
+ echo 'Fetching /usr/local/Homebrew...'
Fetching /usr/local/Homebrew...
+ [[ -n '' ]]
+ git fetch --tags --force origin refs/heads/master:refs/remotes/origin/master
+ [[ -z /Applications/Xcode.app/Contents/Developer/usr/bin/git ]]
+ /Applications/Xcode.app/Contents/Developer/usr/bin/git fetch --tags --force origin refs/heads/master:refs/remotes/origin/master
+ trap - SIGINT
+ [[ -f /usr/local/Homebrew/.git/UPDATE_FAILED ]]
+ for DIR in '"$HOMEBREW_REPOSITORY"' '"$HOMEBREW_LIBRARY"/Taps/*/*'
+ [[ -d /usr/local/Homebrew/.git ]]
+ cd /usr/local/Homebrew
++ repo_var /usr/local/Homebrew
++ local repo_var
++ repo_var=/usr/local/Homebrew
++ [[ /usr/local/Homebrew = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
++ repo_var=
++ echo ''
+ TAP_VAR=
+ UPSTREAM_BRANCH_VAR=UPSTREAM_BRANCH
+ UPSTREAM_BRANCH=master
++ read_current_revision
++ git rev-parse -q --verify HEAD
++ [[ -z /Applications/Xcode.app/Contents/Developer/usr/bin/git ]]
++ /Applications/Xcode.app/Contents/Developer/usr/bin/git rev-parse -q --verify HEAD
+ CURRENT_REVISION=b8a93279fd31b0569a9046f61df0da0121ce4df5
+ PREFETCH_REVISION_VAR=PREFETCH_REVISION
+ PREFETCH_REVISION=b8a93279fd31b0569a9046f61df0da0121ce4df5
++ git rev-parse -q --verify refs/remotes/origin/master
++ [[ -z /Applications/Xcode.app/Contents/Developer/usr/bin/git ]]
++ /Applications/Xcode.app/Contents/Developer/usr/bin/git rev-parse -q --verify refs/remotes/origin/master
+ POSTFETCH_REVISION=b8a93279fd31b0569a9046f61df0da0121ce4df5
+ [[ -n '' ]]
+ [[ -z 1 ]]
+ merge_or_rebase /usr/local/Homebrew '' master
+ [[ -n 1 ]]
+ echo 'Updating /usr/local/Homebrew...'
Updating /usr/local/Homebrew...
+ local DIR
+ local TAP_VAR
+ local UPSTREAM_BRANCH
+ DIR=/usr/local/Homebrew
+ cd /usr/local/Homebrew
+ TAP_VAR=
+ UPSTREAM_BRANCH=master
+ unset STASHED
+ trap reset_on_interrupt SIGINT
+ [[ /usr/local/Homebrew = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
+ [[ -n 1 ]]
++ git tag --list
++ [[ -z /Applications/Xcode.app/Contents/Developer/usr/bin/git ]]
++ /Applications/Xcode.app/Contents/Developer/usr/bin/git tag --list
++ sort --field-separator=. --key=1,1nr -k 2,2nr -k 3,3nr
++ grep --max-count=1 '^[0-9]*\.[0-9]*\.[0-9]*$'
+ UPSTREAM_TAG=2.5.6
+ '[' -n 2.5.6 ']'
+ REMOTE_REF=refs/tags/2.5.6
+ UPSTREAM_BRANCH=stable
++ git status --untracked-files=all --porcelain
+ [[ -n '' ]]
++ git symbolic-ref --short HEAD
+ INITIAL_BRANCH=master
+ [[ -n 2.5.6 ]]
+ [[ -z 2.5.6 ]]
+ [[ -n 2.5.6 ]]
+ [[ stable != \m\a\s\t\e\r ]]
+ git checkout --force -B master origin/master
+ [[ -z /Applications/Xcode.app/Contents/Developer/usr/bin/git ]]
+ /Applications/Xcode.app/Contents/Developer/usr/bin/git checkout --force -B master origin/master
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.
+ git checkout --force -B stable refs/tags/2.5.6
+ [[ -z /Applications/Xcode.app/Contents/Developer/usr/bin/git ]]
+ /Applications/Xcode.app/Contents/Developer/usr/bin/git checkout --force -B stable refs/tags/2.5.6
Switched to and reset branch 'stable'
++ read_current_revision
++ git rev-parse -q --verify HEAD
++ [[ -z /Applications/Xcode.app/Contents/Developer/usr/bin/git ]]
++ /Applications/Xcode.app/Contents/Developer/usr/bin/git rev-parse -q --verify HEAD
+ INITIAL_REVISION=abf214c01ff1edb57acf7e23d5eb24a777335e11
+ export HOMEBREW_UPDATE_BEFORE=abf214c01ff1edb57acf7e23d5eb24a777335e11
+ HOMEBREW_UPDATE_BEFORE=abf214c01ff1edb57acf7e23d5eb24a777335e11
+ git config core.autocrlf false
+ [[ -z /Applications/Xcode.app/Contents/Developer/usr/bin/git ]]
+ /Applications/Xcode.app/Contents/Developer/usr/bin/git config core.autocrlf false
+ [[ -z '' ]]
+ [[ -z 1 ]]
+ git rebase refs/tags/2.5.6
+ [[ -z /Applications/Xcode.app/Contents/Developer/usr/bin/git ]]
+ /Applications/Xcode.app/Contents/Developer/usr/bin/git rebase refs/tags/2.5.6
Current branch stable is up to date.
++ read_current_revision
++ git rev-parse -q --verify HEAD
++ [[ -z /Applications/Xcode.app/Contents/Developer/usr/bin/git ]]
++ /Applications/Xcode.app/Contents/Developer/usr/bin/git rev-parse -q --verify HEAD
+ CURRENT_REVISION=abf214c01ff1edb57acf7e23d5eb24a777335e11
+ export HOMEBREW_UPDATE_AFTER=abf214c01ff1edb57acf7e23d5eb24a777335e11
+ HOMEBREW_UPDATE_AFTER=abf214c01ff1edb57acf7e23d5eb24a777335e11
+ [[ abf214c01ff1edb57acf7e23d5eb24a777335e11 != \a\b\f\2\1\4\c\0\1\f\f\1\e\d\b\5\7\a\c\f\7\e\2\3\d\5\e\b\2\4\a\7\7\7\3\3\5\e\1\1 ]]
+ trap '' SIGINT
+ [[ -n '' ]]
+ pop_stash_message
+ [[ -z '' ]]
+ return
+ trap - SIGINT
+ [[ -n 1 ]]
+ echo

+ for DIR in '"$HOMEBREW_REPOSITORY"' '"$HOMEBREW_LIBRARY"/Taps/*/*'
+ [[ -d /usr/local/Homebrew/Library/Taps/*/*/.git ]]
+ continue
+ safe_cd /usr/local/Homebrew
+ cd /usr/local/Homebrew
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n 1 ]]
+ brew update-report --force --verbose --debug
+ /usr/local/bin/brew update-report --force --verbose --debug
Traceback (most recent call last):
	21: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
	20: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `require_relative'
	19: from /usr/local/Homebrew/Library/Homebrew/global.rb:51:in `<top (required)>'
	18: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	16: from /usr/local/Homebrew/Library/Homebrew/cli/args.rb:3:in `<top (required)>'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	13: from /usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:5:in `<top (required)>'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:4:in `<top (required)>'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /usr/local/Homebrew/Library/Homebrew/cask/cask.rb:5:in `<top (required)>'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:23:in `<top (required)>'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 1: from /usr/local/Homebrew/Library/Homebrew/cask/url.rb:7:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/cask/url.rb:8:in `<class:URL>': uninitialized constant URL::T (NameError)
+ return 1
+ exit 1
```

</details>

#### Output of `brew doctor --verbose`

<details>

```
Traceback (most recent call last):
	21: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
	20: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `require_relative'
	19: from /usr/local/Homebrew/Library/Homebrew/global.rb:51:in `<top (required)>'
	18: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	16: from /usr/local/Homebrew/Library/Homebrew/cli/args.rb:3:in `<top (required)>'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	13: from /usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:5:in `<top (required)>'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:4:in `<top (required)>'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /usr/local/Homebrew/Library/Homebrew/cask/cask.rb:5:in `<top (required)>'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:23:in `<top (required)>'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 1: from /usr/local/Homebrew/Library/Homebrew/cask/url.rb:7:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/cask/url.rb:8:in `<class:URL>': uninitialized constant URL::T (NameError)
```

</details>

#### Output of `brew tap`

<details>

```
Traceback (most recent call last):
	21: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
	20: from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `require_relative'
	19: from /usr/local/Homebrew/Library/Homebrew/global.rb:51:in `<top (required)>'
	18: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	16: from /usr/local/Homebrew/Library/Homebrew/cli/args.rb:3:in `<top (required)>'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	13: from /usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:5:in `<top (required)>'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:4:in `<top (required)>'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /usr/local/Homebrew/Library/Homebrew/cask/cask.rb:5:in `<top (required)>'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:23:in `<top (required)>'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 1: from /usr/local/Homebrew/Library/Homebrew/cask/url.rb:7:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/cask/url.rb:8:in `<class:URL>': uninitialized constant URL::T (NameError)
```

</details>

**Comment by gkze** [comment]
I did some investigating, and it seems that https://github.com/Homebrew/brew/commit/3b944434cfba22338758f0705de4813d076b444f is the one to introduce this bug. It's strange because it has nothing to do with the stack trace above, but if I checkout Homebrew to the commit immediately before it (https://github.com/Homebrew/brew/commit/3095fbc8ec748462c8e193ee8eb1ef1ac0dc1349), Homebrew starts working fine again.

**Comment by miccal** [comment]
You have reported this issue to the wrong repository -- please open an issue in the [`brew` repository.](https://github.com/Homebrew/brew)

**Comment by gkze** [comment]
Thanks, even though the error is in /usr/local/Homebrew/Library/Homebrew/cask/url.rb?

**Comment by miccal** [comment]
Yes please, based on your investigation that it related to a PR in the `brew` repository, thanks.

**Comment by miccal** [comment]
Relevant discussion: https://github.com/Homebrew/discussions/discussions/56
