### ISSUE TITLE
Cannot reinstall/uninstall wireshark-chmodbpf

### ISSUE THREAD

**Issue by johanhaleby** [Homebrew/homebrew-cask#92154]
#### Description of issue

When I tried to upgrade Wireshark from the cask (command line) it failed with:

```
Error: Cask 'wireshark-chmodbpf' is unreadable: undefined method `undent' for #<String:0x00007f8cf1053ab8>
```

#### Command that failed

```
brew cask uninstall wireshark-chmodbpf
```

#### Output of command with `--verbose --debug`

```
==> Uninstalling Cask wireshark-chmodbpf
Warning: Unexpected method 'license' called on Cask wireshark-chmodbpf.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'wireshark-chmodbpf' is unreadable: undefined method `undent' for #<String:0x00007faa7b88c610>
/usr/local/Caskroom/wireshark-chmodbpf/.metadata/2.0.5/20161005111318.605/Casks/wireshark-chmodbpf.rb:77:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/dsl/caveats.rb:46:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/dsl/caveats.rb:46:in `eval_caveats'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:251:in `caveats'
/usr/local/Caskroom/wireshark-chmodbpf/.metadata/2.0.5/20161005111318.605/Casks/wireshark-chmodbpf.rb:76:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:59:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:59:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:46:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:87:in `cask'
/usr/local/Caskroom/wireshark-chmodbpf/.metadata/2.0.5/20161005111318.605/Casks/wireshark-chmodbpf.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:199:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:50:in `block in uninstall_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:44:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:44:in `uninstall_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:96:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:187:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:15:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:120:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:192:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:192:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:169:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:15:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:120:in `<main>'
```

#### Output of `brew doctor --verbose`

```
Warning: Unexpected method 'license' called on Cask betterzipql.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'google-drive' is unavailable: No Cask with this name exists.
```

#### Output of `brew tap`

```
chmouel/kss
datawire/blackbird
heroku/brew
homebrew/cask
homebrew/cask-drivers
homebrew/core
johanhaleby/kubetail
linode/cli
mongodb/brew
robscott/tap
wagoodman/dive
```

**Comment by miccal** [comment]
Please follow the instructions in https://github.com/Homebrew/homebrew-cask/issues/87269#issuecomment-670985384 which may help.

**Comment by johanhaleby** [comment]
@miccal Thanks for your reply. I did this to solve it:

```
find "$(brew --prefix)/Caskroom/"*'/.metadata' -type f -name '*.rb' | xargs grep 'EOS.undent' --files-with-matches | xargs sed -i '' 's/EOS.undent/EOS/'
```

and then `brew cleanup`.

Then I managed to uninstall it and install the "Wireshark" cask instead.
