### ISSUE TITLE
Electrum no longer downloads

### ISSUE THREAD

**Issue by youvegotmoxie** [Homebrew/homebrew-cask#92191]
#### General troubleshooting steps

- [ x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ x] I have retried my command with `--force`.
- [x ] I ran `brew update-reset && brew update` and retried my command.
- [x ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The download link for Electrum results in a connection refused error

#### Command that failed

```
brew upgrade electrum
```

#### Output of command with `--verbose --debug`

```
==> Upgrading 1 outdated package:
electrum 4.0.3 -> 4.0.4
==> Started upgrade process for Cask electrum
==> Upgrading electrum
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.5.8\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://download.electrum.org/4.0.4/electrum-4.0.4.dmg
==> Downloading https://download.electrum.org/4.0.4/electrum-4.0.4.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.5.8\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://download.electrum.org/4.0.4/electrum-4.0.4.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.5.8\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --continue-at 0 --output /Users/mike/Library/Caches/Homebrew/downloads/cd525601b4d98e018ee2357de9a6ccc8fe9c9b892d889d42f9ac8f1f3c810179--electrum-4.0.4.dmg.incomplete h
ttps://download.electrum.org/4.0.4/electrum-4.0.4.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to download.electrum.org port 443: Connection refused
==> Purging files for version 4.0.4 of Cask electrum
Error: electrum: Download failed on Cask 'electrum' with message: Download failed: https://download.electrum.org/4.0.4/electrum-4.0.4.dmg
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:111:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:172:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:120:in `<main>'
```

#### Output of `brew doctor --verbose`

```
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.44.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unknown support status
==> Homebrew Version
2.5.8
==> macOS
10.15.7
==> SIP
Enabled
==> Java
N/A
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3705 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (164 casks)

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  go@1.13

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /opt/puppetlabs/bolt/bin/xslt-config
  /opt/puppetlabs/bolt/bin/xml2-config
  /Users/mike/Library/Python/3.7/bin/pre-commit-validate-config
  /Users/mike/Library/Python/3.7/bin/ansible-config

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc

```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
```

**Comment by miccal** [comment]
This may have been juts a temporary issue, as it seems fine now:
```
|-> brew cask fetch electrum

==> Downloading external files for Cask electrum
==> Downloading https://download.electrum.org/4.0.4/electrum-4.0.4.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'electrum'.
==> Success! Downloaded to -> /Users/miccal/Library/Caches/Homebrew/downloads/cd525601b4d98e018ee2357de9a6ccc8fe9c9b892d889d42f9ac8f1f3c810179--electrum-4.0.4.dmg
```
