### ISSUE TITLE
Homebrew endlessly asks for password whilst remove foxitreader cast

### ISSUE THREAD

**Issue by gowerc** [Homebrew/homebrew-cask#94976]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Trying to remove foxit reader causes homebrew to endlessly ask for my password:
![image](https://user-images.githubusercontent.com/8447209/101546661-09b05100-39a1-11eb-8021-03dbed41029d.png)

#### Command that failed

```
brew remove foxitreader
```

#### Output of command with `--verbose --debug`

```
brew remove --verbose --debug foxitreader
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git-lfs.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vim.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tree.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libtool.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jansson.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gmp.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wget.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libidn2.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pandoc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/docker.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nghttp2.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nettle.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libunistring.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libyaml.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jemalloc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bdw-gc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/awscli.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/c-ares.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/unixodbc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/emacs.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lua.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openjdk.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gettext.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libtasn1.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/oniguruma.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libevent.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cask.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hello.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/unbound.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/docker-compose.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jq.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/guile.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/p11-kit.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libev.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ruby.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libffi.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@3.9.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb
==> Uninstalling Cask foxitreader
==> Uninstalling Cask foxitreader
==> Uninstalling artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fdfdc0ba9f0 @cask=#<Cask::Cask:0x00007fdfdc0aa460 @token="foxitreader", @sourcefile_path=#<Pathname:/usr/local/Caskroom/foxitreader/.metadata/4.1.0/20201116125306.583/Casks/foxitreader.rb>, @tap=nil, @block=#<Proc:0x00007fdfdc0aa348@/usr/local/Caskroom/foxitreader/.metadata/4.1.0/20201116125306.583/Casks/foxitreader.rb:1>, @default_config=#<Cask::Config:0x00007fdfdc0aa320 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/foxitreader>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/foxitreader/.metadata>, @config=#<Cask::Config:0x00007fdfdc0a82c8 @explicit={}, @default={:languages=>["en-GB"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/gowerc/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/gowerc/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/gowerc/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/gowerc/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/gowerc/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/gowerc/Library/Fonts>, :servicedir=>#<Pathname:/Users/gowerc/Library/Services>, :input_methoddir=>#<Pathname:/Users/gowerc/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/gowerc/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/gowerc/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/gowerc/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/gowerc/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/gowerc/Library/Screen Savers>}, @env={}>, @dsl=#<Cask::DSL:0x00007fdfdc0b1738 @cask=#<Cask::Cask:0x00007fdfdc0aa460 ...>, @token="foxitreader", @version="4.1.0", @sha256=#<Checksum:0x00007fdfdc0b1440 @hash_type=:sha256, @hexdigest="9cb030a61430f529ab05e3a06f3cd3b0432c9aeb5eb5bf16e6543830af50e9da">, @url=#<URL:0x00007fdfdc0b08d8 @uri=#<URI::HTTPS https://cdn01.foxitsoftware.com/pub/foxit/reader/desktop/mac/4.x/4.1/ML/FoxitReader410.L10N.Setup.pkg>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}, @caller_location="/usr/local/Caskroom/foxitreader/.metadata/4.1.0/20201116125306.583/Casks/foxitreader.rb:5:in `block in load'">, @appcast=#<Cask::DSL::Appcast:0x00007fdfdc0b0338 @uri=#<URI::HTTPS https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://www.foxitsoftware.com/downloads/latest.html%3Fproduct%3DFoxit-Reader%26platform%3DMac-OS-X>, @parameters={:must_contain=>"410"}, @must_contain="410">, @name=["Foxit Reader"], @desc="PDF reader", @homepage="https://www.foxitsoftware.com/pdf-reader/", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/foxitreader/4.1.0>, @language_eval=nil>>, @directives={:pkgutil=>["com.foxitsoftware.reader.pkg", "com.foxit.pkg.reader"], :delete=>"/Applications/Foxit Reader.app", :signal=>[]}>, #<Cask::Artifact::Pkg:0x00007fdfdc0bb940 @cask=#<Cask::Cask:0x00007fdfdc0aa460 @token="foxitreader", @sourcefile_path=#<Pathname:/usr/local/Caskroom/foxitreader/.metadata/4.1.0/20201116125306.583/Casks/foxitreader.rb>, @tap=nil, @block=#<Proc:0x00007fdfdc0aa348@/usr/local/Caskroom/foxitreader/.metadata/4.1.0/20201116125306.583/Casks/foxitreader.rb:1>, @default_config=#<Cask::Config:0x00007fdfdc0aa320 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/foxitreader>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/foxitreader/.metadata>, @config=#<Cask::Config:0x00007fdfdc0a82c8 @explicit={}, @default={:languages=>["en-GB"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/gowerc/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/gowerc/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/gowerc/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/gowerc/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/gowerc/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/gowerc/Library/Fonts>, :servicedir=>#<Pathname:/Users/gowerc/Library/Services>, :input_methoddir=>#<Pathname:/Users/gowerc/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/gowerc/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/gowerc/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/gowerc/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/gowerc/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/gowerc/Library/Screen Savers>}, @env={}>, @dsl=#<Cask::DSL:0x00007fdfdc0b1738 @cask=#<Cask::Cask:0x00007fdfdc0aa460 ...>, @token="foxitreader", @version="4.1.0", @sha256=#<Checksum:0x00007fdfdc0b1440 @hash_type=:sha256, @hexdigest="9cb030a61430f529ab05e3a06f3cd3b0432c9aeb5eb5bf16e6543830af50e9da">, @url=#<URL:0x00007fdfdc0b08d8 @uri=#<URI::HTTPS https://cdn01.foxitsoftware.com/pub/foxit/reader/desktop/mac/4.x/4.1/ML/FoxitReader410.L10N.Setup.pkg>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}, @caller_location="/usr/local/Caskroom/foxitreader/.metadata/4.1.0/20201116125306.583/Casks/foxitreader.rb:5:in `block in load'">, @appcast=#<Cask::DSL::Appcast:0x00007fdfdc0b0338 @uri=#<URI::HTTPS https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://www.foxitsoftware.com/downloads/latest.html%3Fproduct%3DFoxit-Reader%26platform%3DMac-OS-X>, @parameters={:must_contain=>"410"}, @must_contain="410">, @name=["Foxit Reader"], @desc="PDF reader", @homepage="https://www.foxitsoftware.com/pdf-reader/", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/foxitreader/4.1.0>, @language_eval=nil>>, @path=#<Pathname:/usr/local/Caskroom/foxitreader/4.1.0/FoxitReader410.L10N.Setup.pkg>, @stanza_options={}>}>
==> Uninstalling artifact of class Cask::Artifact::Uninstall
==> Uninstalling packages:
/usr/sbin/pkgutil --pkgs=com.foxitsoftware.reader.pkg
/usr/sbin/pkgutil --pkgs=com.foxit.pkg.reader
com.foxit.pkg.reader
/usr/sbin/pkgutil --files com.foxit.pkg.reader
/usr/sbin/pkgutil --pkg-info-plist com.foxit.pkg.reader
==> Deleting pkg directories
/usr/bin/stat -f \%Of -- /Applications/Foxit\ Reader.app/Contents/Frameworks/MSRightsManagement.framework/Versions/A/Resources/da.lproj
/usr/bin/sudo -E -- /bin/chmod -- 777 /Applications/Foxit\ Reader.app/Contents/Frameworks/MSRightsManagement.framework/Versions/A/Resources/da.lproj
Password:
/usr/bin/sudo -E -- /bin/rmdir -- /Applications/Foxit\ Reader.app/Contents/Frameworks/MSRightsManagement.framework/Versions/A/Resources/da.lproj
Password:
/usr/bin/stat -f \%Of -- /Applications/Foxit\ Reader.app/Contents/Frameworks/MSRightsManagement.framework/Versions/A/Resources/fi.lproj
/usr/bin/sudo -E -- /bin/chmod -- 777 /Applications/Foxit\ Reader.app/Contents/Frameworks/MSRightsManagement.framework/Versions/A/Resources/fi.lproj
Password:
/usr/bin/sudo -E -- /bin/rmdir -- /Applications/Foxit\ Reader.app/Contents/Frameworks/MSRightsManagement.framework/Versions/A/Resources/fi.lproj
Password:
/usr/bin/stat -f \%Of -- /Applications/Foxit\ Reader.app/Contents/Frameworks/MSRightsManagement.framework/Versions/A/Resources/hu.lproj
/usr/bin/sudo -E -- /bin/chmod -- 777 /Applications/Foxit\ Reader.app/Contents/Frameworks/MSRightsManagement.framework/Versions/A/Resources/hu.lproj
```

#### Output of `brew doctor --verbose`

```
❯ brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
2.6.0-174-gddfd499
==> macOS
10.15.7
==> SIP
Enabled
==> Java
15.0.1
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3752 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (167 casks)
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/lib/libwkhtmltox.0.12.dylib
  /usr/local/lib/libwkhtmltox.0.dylib
  /usr/local/lib/libwkhtmltox.dylib
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by miccal** [comment]
Does this still open if you  run `brew uninstall --force foxitreader`?

**Comment by vitorgalvao** [comment]
What’s your `sudo` timeout? Seems like you might’ve removed it (i.e. always ask for a password even if you authenticated a second ago).

**Comment by gowerc** [comment]
> Does this still happen if you run `brew uninstall --force foxitreader`?

Yup still does :( 

![image](https://user-images.githubusercontent.com/8447209/101619601-68121980-3a0b-11eb-9bac-a0361a200db9.png)

**Comment by gowerc** [comment]
> What’s your `sudo` timeout? Seems like you might’ve removed it (i.e. always ask for a password even if you authenticated a second ago).

Apologies, but how do I view or edit that ? Is there a particular configuration file ?

**Comment by gowerc** [comment]
> What’s your `sudo` timeout? Seems like you might’ve removed it (i.e. always ask for a password even if you authenticated a second ago).

This was the answer !! I don't even remember changing that value but yes it was set to a timeout to 0, upping it to 5 solved the problem thank you !
