### ISSUE TITLE
Unable to install ChronoSync

### ISSUE THREAD

**Issue by guw** [Homebrew/homebrew-cask#94993]
#### Description of issue

The installation of ChronoSync is failing. It looks like this is an installer/package specific issue. However, I'm unable to spot any error messages.

#### Command that failed

```
brew install chronosync
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 1 formula.
==> Updated Casks
fontstand                                jandi                                    keeper-password-manager                  liya                                     macx-video-converter-pro

==> Downloading https://downloads.econtechnologies.com/CS4_Download.dmg
Already downloaded: /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg
==> Installing Cask chronosync
==> Running installer for chronosync; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
installer: Package name is ChronoSync
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Install.pkg”.)
==> Purging files for version 4.9.12 of Cask chronosync
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=... USER=... USERNAME=gwagenknecht /usr/sbin/installer -pkg /usr/local/Caskroom/chronosync/4.9.12/Install.pkg -target /` exited with 1. Here's the output:
installer: Package name is ChronoSync
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Install.pkg”.)
```

#### Output of command with `--verbose --debug`

```
❯ brew install chronosync --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://downloads.econtechnologies.com/CS4_Download.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.6.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://downloads.econtechnologies.com/CS4_Download.dmg
Already downloaded: /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg
==> /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg is quarantined
==> Verifying checksum for cask 'chronosync'.
==> Downloaded to -> /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg
hdiutil imageinfo -format /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg
==> Installing Cask chronosync
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg
hdiutil attach -plist -nobrowse -readonly -mountrandom /var/folders/x0/rnf0k3d92hb_k283rchyxhgw0000gp/T/d20201209-4313-rwfi52 /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg
find . -print0
mkbom -s -i /var/folders/x0/rnf0k3d92hb_k283rchyxhgw0000gp/T/20201209-4313-cs3rjf.list -- /var/folders/x0/rnf0k3d92hb_k283rchyxhgw0000gp/T/20201209-4313-pbx04q.bom
ditto --bom /var/folders/x0/rnf0k3d92hb_k283rchyxhgw0000gp/T/20201209-4313-pbx04q.bom -- /private/var/folders/x0/rnf0k3d92hb_k283rchyxhgw0000gp/T/d20201209-4313-rwfi52/dmg.jfoojq /var/folders/x0/rnf0k3d92hb_k283rchyxhgw0000gp/T/d20201209-4313-cxd22b
diskutil eject /private/var/folders/x0/rnf0k3d92hb_k283rchyxhgw0000gp/T/d20201209-4313-rwfi52/dmg.jfoojq
cp -pR /var/folders/x0/rnf0k3d92hb_k283rchyxhgw0000gp/T/d20201209-4313-cxd22b/What\'s\ New\ in\ v4.9.pdf /usr/local/Caskroom/chronosync/4.9.12/What\'s\ New\ in\ v4.9.pdf
cp -pR /var/folders/x0/rnf0k3d92hb_k283rchyxhgw0000gp/T/d20201209-4313-cxd22b/Remove.pkg /usr/local/Caskroom/chronosync/4.9.12/Remove.pkg
cp -pR /var/folders/x0/rnf0k3d92hb_k283rchyxhgw0000gp/T/d20201209-4313-cxd22b/Install.pkg /usr/local/Caskroom/chronosync/4.9.12/Install.pkg
cp -pR /var/folders/x0/rnf0k3d92hb_k283rchyxhgw0000gp/T/d20201209-4313-cxd22b/Quick\ Start\ Guide.pdf /usr/local/Caskroom/chronosync/4.9.12/Quick\ Start\ Guide.pdf
chmod -Rf +w /var/folders/x0/rnf0k3d92hb_k283rchyxhgw0000gp/T/d20201209-4313-cxd22b
==> Verifying Gatekeeper status of /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg
==> /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg is quarantined
==> Propagating quarantine from /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg to /usr/local/Caskroom/chronosync/4.9.12
/usr/bin/xattr -p com.apple.quarantine /Users/.../Library/Caches/Homebrew/downloads/2177a05a42081591d96a3c59a9a73f9789f987ce937161b1598ad610228b3232--CS4_Download.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5fce76f6\;Homebrew\\x20Cask\;469982A4-980D-4957-BE0D-B20FAE68F7BB
==> Creating metadata directory /usr/local/Caskroom/chronosync/.metadata/4.9.12/20201209121600.792.
==> Creating metadata subdirectory /usr/local/Caskroom/chronosync/.metadata/4.9.12/20201209121600.792/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fdb7b153a98 @cask=#<Cask::Cask:0x00007fdb7ab61d88 @token="chronosync", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/chronosync.rb>, @tap=#<Tap:0x00007fdb7ab0b460 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fdb7ab61c98@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/chronosync.rb:1>, @default_config=#<Cask::Config:0x00007fdb7ab51898 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/chronosync>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/chronosync/.metadata>, @config=#<Cask::Config:0x00007fdb7b149c00 @explicit={}>, @dsl=#<Cask::DSL:0x00007fdb7b1499d0 @cask=#<Cask::Cask:0x00007fdb7ab61d88 ...>, @token="chronosync", @version="4.9.12", @sha256=#<Checksum:0x00007fdb7b1497a0 @hash_type=:sha256, @hexdigest="7fa6484511f0ff700eee104f5163016c9853de840adf4084655f462657a71592">, @url=#<URL:0x00007fdb7b149660 @uri=#<URI::HTTPS https://downloads.econtechnologies.com/CS4_Download.dmg>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}>, @appcast=#<Cask::DSL::Appcast:0x00007fdb7b148ff8 @uri=#<URI::HTTPS https://www.econtechnologies.com/UC/updatecheck.php?prod=ChronoSync&vers=4.9.0&lang=en&plat=mac&os=10.14.1&hw=i64&req=1>, @parameters={}>, @name=["ChronoSync"], @desc="Synchronization and backup tool", @homepage="https://www.econtechnologies.com/", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/chronosync/4.9.12>, @language_eval=nil>>, @directives={:pkgutil=>"com.econtechnologies.pkg.ChronoSyncApplication", :signal=>[]}>, #<Cask::Artifact::Pkg:0x00007fdb7b148828 @cask=#<Cask::Cask:0x00007fdb7ab61d88 @token="chronosync", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/chronosync.rb>, @tap=#<Tap:0x00007fdb7ab0b460 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fdb7ab61c98@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/chronosync.rb:1>, @default_config=#<Cask::Config:0x00007fdb7ab51898 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/chronosync>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/chronosync/.metadata>, @config=#<Cask::Config:0x00007fdb7b149c00 @explicit={}>, @dsl=#<Cask::DSL:0x00007fdb7b1499d0 @cask=#<Cask::Cask:0x00007fdb7ab61d88 ...>, @token="chronosync", @version="4.9.12", @sha256=#<Checksum:0x00007fdb7b1497a0 @hash_type=:sha256, @hexdigest="7fa6484511f0ff700eee104f5163016c9853de840adf4084655f462657a71592">, @url=#<URL:0x00007fdb7b149660 @uri=#<URI::HTTPS https://downloads.econtechnologies.com/CS4_Download.dmg>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}>, @appcast=#<Cask::DSL::Appcast:0x00007fdb7b148ff8 @uri=#<URI::HTTPS https://www.econtechnologies.com/UC/updatecheck.php?prod=ChronoSync&vers=4.9.0&lang=en&plat=mac&os=10.14.1&hw=i64&req=1>, @parameters={}>, @name=["ChronoSync"], @desc="Synchronization and backup tool", @homepage="https://www.econtechnologies.com/", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/chronosync/4.9.12>, @language_eval=nil>>, @path=#<Pathname:/usr/local/Caskroom/chronosync/4.9.12/Install.pkg>, @stanza_options={}>}>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for chronosync; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- /usr/bin/env LOGNAME=... USER=... USERNAME=... /usr/sbin/installer -pkg /usr/local/Caskroom/chronosync/4.9.12/Install.pkg -target / -verboseR
Password:
installer: Package name is ChronoSync
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing ChronoSync…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%13.206256
installer:PHASE:Writing files…
installer:%26.192208
installer:PHASE:Writing files…
installer:%50.489673
installer:PHASE:Running package scripts…
installer:%51.784562
installer:PHASE:Running package scripts…
installer:%53.082690
installer:PHASE:Running package scripts…
installer:%85.927589
installer:PHASE:Optimizing system for installed software…
installer:%87.221382
installer:PHASE:Running package scripts…
installer:%88.517009
installer:PHASE:Running package scripts…
installer:%88.524779
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Install.pkg”.)
==> Purging files for version 4.9.12 of Cask chronosync
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=... USER=... USERNAME=... /usr/sbin/installer -pkg /usr/local/Caskroom/chronosync/4.9.12/Install.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is ChronoSync
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing ChronoSync…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%13.206256
installer:PHASE:Writing files…
installer:%26.192208
installer:PHASE:Writing files…
installer:%50.489673
installer:PHASE:Running package scripts…
installer:%51.784562
installer:PHASE:Running package scripts…
installer:%53.082690
installer:PHASE:Running package scripts…
installer:%85.927589
installer:PHASE:Optimizing system for installed software…
installer:%87.221382
installer:PHASE:Running package scripts…
installer:%88.517009
installer:PHASE:Running package scripts…
installer:%88.524779
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Install.pkg”.)
/usr/local/Homebrew/Library/Homebrew/system_command.rb:224:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:63:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:38:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:42:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:61:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:67:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:54:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:36:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:220:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:213:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:105:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:79:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:158:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

#### Output of `brew doctor --verbose`

```
❯ brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
2.6.0
==> macOS
10.15.7
==> SIP
Enabled
==> Java
N/A
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3752 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (168 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1586 casks)
Your system is ready to brew.
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Please don’t edit out things from the template.

Can’t reproduce on a clean Mojave VM. Because you’ve changed the template and haven’t asserted you’ve run the commands that tend to fix these issues, going to assume they weren’t run. Please do.
