### ISSUE TITLE
brew install parallels fails: ditto --bom operation not permitted

### ISSUE THREAD

**Issue by kbluck** [Homebrew/homebrew-cask#95280]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Attempt to install Parallels cask fails with following error:

```
Error: Failure while executing; `ditto --bom /var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/20201211-9282-18enug0.bom -- /private/var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201211-9282-b4c5b8/dmg.vsBmmW /var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201211-9282-z7ukfd` exited with 1. Here's the output:
ditto: /private/var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201211-9282-z7ukfd/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted
```

#### Command that failed

```
brew install parallels
```

#### Output of command with `--verbose --debug`

```
$ brew install parallels --force --verbose --debug
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 1 formula.
==> Updated Casks
jalbum

==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://download.parallels.com/desktop/v16/16.1.1-49141/ParallelsDesktop-16.1.1-49141.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.6.1-36-g85373df\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://download.parallels.com/desktop/v16/16.1.1-49141/ParallelsDesktop-16.1.1-49141.dmg
Already downloaded: /Users/kbluck/Library/Caches/Homebrew/downloads/b999658936716001927f2b77cba21f88cb78ba5e233a6108490c166945d55d0b--ParallelsDesktop-16.1.1-49141.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/kbluck/Library/Caches/Homebrew/downloads/b999658936716001927f2b77cba21f88cb78ba5e233a6108490c166945d55d0b--ParallelsDesktop-16.1.1-49141.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/kbluck/Library/Caches/Homebrew/downloads/b999658936716001927f2b77cba21f88cb78ba5e233a6108490c166945d55d0b--ParallelsDesktop-16.1.1-49141.dmg
==> /Users/kbluck/Library/Caches/Homebrew/downloads/b999658936716001927f2b77cba21f88cb78ba5e233a6108490c166945d55d0b--ParallelsDesktop-16.1.1-49141.dmg is quarantined
==> Verifying checksum for cask 'parallels'.
hdiutil imageinfo -format /Users/kbluck/Library/Caches/Homebrew/downloads/b999658936716001927f2b77cba21f88cb78ba5e233a6108490c166945d55d0b--ParallelsDesktop-16.1.1-49141.dmg
==> Installing Cask parallels
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/kbluck/Library/Caches/Homebrew/downloads/b999658936716001927f2b77cba21f88cb78ba5e233a6108490c166945d55d0b--ParallelsDesktop-16.1.1-49141.dmg
hdiutil attach -plist -nobrowse -readonly -mountrandom /var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201211-9282-b4c5b8 /Users/kbluck/Library/Caches/Homebrew/downloads/b999658936716001927f2b77cba21f88cb78ba5e233a6108490c166945d55d0b--ParallelsDesktop-16.1.1-49141.dmg
find . -print0
mkbom -s -i /var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/20201211-9282-14mkj6z.list -- /var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/20201211-9282-18enug0.bom
ditto --bom /var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/20201211-9282-18enug0.bom -- /private/var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201211-9282-b4c5b8/dmg.vsBmmW /var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201211-9282-z7ukfd
ditto: /private/var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201211-9282-z7ukfd/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted
diskutil eject /private/var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201211-9282-b4c5b8/dmg.vsBmmW
==> Purging files for version 16.1.1-49141 of Cask parallels
Error: Failure while executing; `ditto --bom /var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/20201211-9282-18enug0.bom -- /private/var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201211-9282-b4c5b8/dmg.vsBmmW /var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201211-9282-z7ukfd` exited with 1. Here's the output:
ditto: /private/var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201211-9282-z7ukfd/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted

/usr/local/Homebrew/Library/Homebrew/system_command.rb:224:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:63:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:38:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:42:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:28:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:123:in `block in extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:111:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:141:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:151:in `block (2 levels) in extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:150:in `each'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:150:in `block in extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:214:in `block in mount'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:157:in `mount'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:147:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:141:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:148:in `block in extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:145:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:196:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:79:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:79:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:158:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

#### Output of `brew doctor --verbose`

```
$ brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
2.6.1-36-g85373df
==> macOS
10.14.6
==> SIP
Enabled
==> Java
N/A
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3755 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (168 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (166 casks)
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
```

#### Output of `brew tap`

```
$ brew tap
bramstein/webfonttools
homebrew/cask
homebrew/cask-drivers
homebrew/cask-versions
homebrew/core
sqitchers/sqitch
```

**Comment by kbluck** [comment]
May be related to these closed issues:
#57388
#26872

**Comment by miccal** [comment]
I have just updated an open PR for `parallels` in https://github.com/Homebrew/homebrew-cask/pull/91805 and neither myself nor our CI system can reproduce this error.

Can you try to install `parallels` with `brew install --force --no-quarantine parallels`?

**Comment by kbluck** [comment]
No difference.
```
$ brew install --force parallels==> Downloading https://download.parallels.com/desktop/v16/16.1.1-49141/ParallelsDesktop-16.1.1-49141.dmg
Already downloaded: /Users/kbluck/Library/Caches/Homebrew/downloads/b999658936716001927f2b77cba21f88cb78ba5e233a6108490c166945d55d0b--ParallelsDesktop-16.1.1-49141.dmg
==> Installing Cask parallels
ditto: /private/var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201216-13532-tmw76i/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted
==> Purging files for version 16.1.1-49141 of Cask parallels
Error: Failure while executing; `ditto --bom /var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/20201216-13532-16gq41c.bom -- /private/var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201216-13532-3nbkut/dmg.3cQnRL /var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201216-13532-tmw76i` exited with 1. Here's the output:
ditto: /private/var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201216-13532-tmw76i/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted
```

```
$ brew install --force --no-quarantine parallels
==> Downloading https://download.parallels.com/desktop/v16/16.1.1-49141/ParallelsDesktop-16.1.1-49141.dmg
Already downloaded: /Users/kbluck/Library/Caches/Homebrew/downloads/b999658936716001927f2b77cba21f88cb78ba5e233a6108490c166945d55d0b--ParallelsDesktop-16.1.1-49141.dmg
==> Installing Cask parallels
Warning: macOS's Gatekeeper has been disabled for this Cask
ditto: /private/var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201216-14519-1qu2kif/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted
==> Purging files for version 16.1.1-49141 of Cask parallels
Error: Failure while executing; `ditto --bom /var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/20201216-14519-1cksisv.bom -- /private/var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201216-14519-mk1xfe/dmg.ZM1NU2 /var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201216-14519-1qu2kif` exited with 1. Here's the output:
ditto: /private/var/folders/bm/zc1236y53yb_3rkrhjvdt3sc0000gp/T/d20201216-14519-1qu2kif/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted
```

**Comment by miccal** [comment]
Does installing `parallels` manually (that is, outside of Cask) work?

**Comment by kbluck** [comment]
Yes, installing from the downloaded DMG works fine.

**Comment by miccal** [comment]
Sorry @kbluck, I do not what else to suggest -- `parallels` is a popular Cask:
```
==> Analytics
install: 597 (30 days), 1,740 (90 days), 7,682 (365 days)
```
and we have not had any other reports of issues, and I cannot reproduce this either on my Catalina machine or via our CI tests.

**Comment by Technofrikus** [comment]
I have the same issue

`brew install parallels
==> Downloading https://download.parallels.com/desktop/v16/16.1.1-49141/ParallelsDesktop-16.1.1-49141.dmg
Already downloaded: /Users/tf/Library/Caches/Homebrew/downloads/b999658936716001927f2b77cba21f88cb78ba5e233a6108490c166945d55d0b--ParallelsDesktop-16.1.1-49141.dmg
==> Installing Cask parallels
ditto: /private/var/folders/_h/6qmp_h711934xx4jnbwxlmxh0000gp/T/d20201223-7958-rfz8ji/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted
==> Purging files for version 16.1.1-49141 of Cask parallels
Error: Failure while executing; `ditto --bom /var/folders/_h/6qmp_h711934xx4jnbwxlmxh0000gp/T/20201223-7958-v1ms9f.bom -- /private/var/folders/_h/6qmp_h711934xx4jnbwxlmxh0000gp/T/d20201223-7958-1f38lxu/dmg.jAiNUj /var/folders/_h/6qmp_h711934xx4jnbwxlmxh0000gp/T/d20201223-7958-rfz8ji` exited with 1. Here's the output:
ditto: /private/var/folders/_h/6qmp_h711934xx4jnbwxlmxh0000gp/T/d20201223-7958-rfz8ji/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted`

**Comment by miccal** [comment]
I have just updated the `parallels` Cask in https://github.com/Homebrew/homebrew-cask/pull/96859, and again it passed our CI tests.

Perhaps try again now that I have updated to the latest version?

**Comment by Technofrikus** [comment]
Thanks, but sadly it is still the same. 

`==> Downloading https://download.parallels.com/desktop/v16/16.1.2-49151/ParallelsDesktop-16.1.2-49151.dmg
######################################################################## 100.0%
==> Installing Cask parallels
ditto: /private/var/folders/_h/6qmp_h711934xx4jnbwxlmxh0000gp/T/d20201227-4283-1i91gb6/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted
==> Purging files for version 16.1.2-49151 of Cask parallels
Error: Failure while executing; `ditto --bom /var/folders/_h/6qmp_h711934xx4jnbwxlmxh0000gp/T/20201227-4283-12o0lo2.bom -- /private/var/folders/_h/6qmp_h711934xx4jnbwxlmxh0000gp/T/d20201227-4283-1wwyxy3/dmg.zWIwGk /var/folders/_h/6qmp_h711934xx4jnbwxlmxh0000gp/T/d20201227-4283-1i91gb6` exited with 1. Here's the output:
ditto: /private/var/folders/_h/6qmp_h711934xx4jnbwxlmxh0000gp/T/d20201227-4283-1i91gb6/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted`

**Comment by kbluck** [comment]
Likewise, same result.

It appears there was a very similar problem with Parallels Access, where ditto was failing with "Operation not permitted" while extracting the DMG. It seems likely that Parallels is afflicted with the same issue under certain circumstances.

Here is the PR that seems to have fixed the ditto problem for Parallels Access:
https://github.com/Homebrew/homebrew-cask/pull/32174/
