### ISSUE TITLE
Cask 'google-photos-backup' definition is invalid: Token '{:v1=>"google-photos-backup"}' in header line does not match the file name.

### ISSUE THREAD

**Issue by mattfelsen** [Homebrew/homebrew-cask#95478]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- N/A I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Attempting to use a number of commands (`brew doctor`, `brew outdated`, `brew list`) results in the error above (in the title). I'm aware the cask for `google-photos-backup` has been removed & replaced with `google-photos-backup-and-sync` (which I have installed) but I'm unsure how to handle this. 

I did [try the solution here](https://stackoverflow.com/questions/56092643/homebrew-cask-java-definition-is-invalid) by changing the first line of the rb file in the .metadata folder from:
`cask :v1 => 'google-photos-backup' do`
to:
`cask 'google-photos-backup' do`
and then running:
`brew cask uninstall google-photos-backup`

but I then receive this output/error:

```
$ brew cask uninstall google-photos-backup
Warning: Calling brew cask uninstall is deprecated! Use brew uninstall [--cask] instead.
Warning: Unexpected method 'license' called on Cask google-photos-backup.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Warning: Unexpected method 'tags' called on Cask google-photos-backup.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Warning: Unexpected method 'license' called on Cask google-photos-backup.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Warning: Unexpected method 'tags' called on Cask google-photos-backup.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
==> Uninstalling Cask google-photos-backup
Error: It seems there is already an App at '/usr/local/Caskroom/google-photos-backup/latest/Google Photos Backup.app'.
```

Separate but related, the rb file contains this line:
`:rmdir  => '~/Library/Application Support/Google'`
which seems much too broad as it would also remove my `~/Library/Application Support/Google/Chrome` folder. I changed it to:
`:rmdir  => '~/Library/Application Support/Google/Google Photos Backup'`

As expected this didn't have any impact on trying to remove the cask, but wanted to mention in case anyone else also finds themselves on this path.

#### Command that failed

```
brew list
brew outdated
brew doctor
```

#### Output of command with `--verbose --debug`

```
$ brew list --verbose --debug
ls /usr/local/Cellar
app-engine-go-64	ffmpeg			glfw3			libhid			numpy			telnet
aubio			fortune			gmp			libmpc			nvm			tree
avr-binutils		gcc			icu4c			libusb			openblas		wget
avr-gcc			gdbm			isl			libusb-compat		openjdk			x264
avrdude			gifsicle		lame			libvo-aacenc		openssl@1.1		xvid
binaryen		git			libelf			mkcert			python@3.8		xz
cowsay			git-lfs			libevent		mpfr			readline		yuicompressor
emscripten		glfw			libftdi0		node			sqlite
Error: Cask 'google-photos-backup' definition is invalid: Token '{:v1=>"google-photos-backup"}' in header line does not match the file name.
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:85:in `cask'
/usr/local/Caskroom/google-photos-backup/.metadata/latest/20150601003529.967/Casks/google-photos-backup.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:45:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/list.rb:50:in `list_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/list.rb:161:in `list_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/list.rb:122:in `list'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

```
$ brew outdated --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/aubio.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/avrdude.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git-lfs.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cowsay.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lame.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tree.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gmp.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wget.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ffmpeg.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mkcert.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/binaryen.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xvid.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpfr.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/osx-cross/homebrew-avr/Formula/avr-binutils.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libvo-aacenc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nvm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/numpy.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libusb-compat.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openjdk.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openblas.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/emscripten.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/osx-cross/homebrew-avr/Formula/avr-gcc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gifsicle.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libelf.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libftdi0.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/isl.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libevent.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/x264.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/app-engine-go-64.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/opt/app-engine-go-64/.brew/app-engine-go-64.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glfw.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libusb.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@3.8.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libhid.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yuicompressor.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/telnet.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libmpc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fortune.rb
Error: Cask 'google-photos-backup' definition is invalid: Token '{:v1=>"google-photos-backup"}' in header line does not match the file name.
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:85:in `cask'
/usr/local/Caskroom/google-photos-backup/.metadata/latest/20150601003529.967/Casks/google-photos-backup.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:45:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:183:in `outdated_formulae_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:77:in `outdated'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

#### Output of `brew doctor --verbose`

```
$ brew doctor --verbose --debug
Error: Cask 'google-photos-backup' definition is invalid: Token '{:v1=>"google-photos-backup"}' in header line does not match the file name.
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:85:in `cask'
/usr/local/Caskroom/google-photos-backup/.metadata/latest/20150601003529.967/Casks/google-photos-backup.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:45:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:51:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

#### Output of `brew tap`

```
$ brew tap
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
osx-cross/avr
```

**Comment by vitorgalvao** [comment]
You have a really old cask installed. You can try fixing all errors on that `.metadata` cask one by one, but I recommend you delete `/usr/local/Caskroom/google-photos-backup` and be done with it, removing any remnants of the app manually.
