### ISSUE TITLE
Discuss: Change metasploit cask to use Github releases to avoid outdated package urls

### ISSUE THREAD

**Issue by haswalt** [Homebrew/homebrew-cask#95730]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Updating casks results in 404 error with metaploit. This has been mentioned in several issues being caused by metasploit only hosting the last 6 versions.

This isn't an issue with cask or homebrew exactly, however I would like to discuss changing the metasploit cask to us their github releases, which have all previous versions, and building rather than downloading prebuilt packages.

#### Command that failed

```
brew upgrade metasploit
```

#### Output of command with `--verbose --debug`

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
eclipse-installer

==> Upgrading 1 outdated package:
metasploit 6.0.18,20201122112901 -> 6.0.19,20201201112841
==> Started upgrade process for Cask metasploit
==> Upgrading metasploit
==> Printing caveats
==> Cask::Installer#fetch
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nmap.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.6.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://osx.metasploit.com/metasploit-framework-6.0.19\%2B20201201112841-1rapid7-1.pkg
==> Downloading https://osx.metasploit.com/metasploit-framework-6.0.19%2B20201201112841-1rapid7-1.pkg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.6.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://osx.metasploit.com/metasploit-framework-6.0.19\%2B20201201112841-1rapid7-1.pkg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.6.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --continue-at 0 --output /Users/harry/Library/Caches/Homebrew/downloads/a29bbd375e4fbb05812b65cde3fcd0d79360de2facd12cb650f8329e1092b510--metasploit-framework-6.0.19\+20201201112841-1rapid7-1.pkg.incomplete https://osx.metasploit.com/metasploit-framework-6.0.19\%2B20201201112841-1rapid7-1.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> Purging files for version 6.0.19,20201201112841 of Cask metasploit
Error: metasploit: Download failed on Cask 'metasploit' with message: Download failed: https://osx.metasploit.com/metasploit-framework-6.0.19%2B20201201112841-1rapid7-1.pkg
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:132:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:184:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:109:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

#### Output of `brew doctor --verbose`

```
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
2.6.2
==> macOS
11.1
==> SIP
Enabled
==> Java
1.8.271.09, 1.8.0_275, 1.8.0_191
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3761 casks)
/usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk (43 casks)
/usr/local/Homebrew/Library/Taps/wix/homebrew-brew (1 cask)
```

#### Output of `brew tap`

```
adoptopenjdk/openjdk
facebook/fb
homebrew-ffmpeg/ffmpeg
homebrew/cask
homebrew/core
homebrew/services
johanhaleby/kubetail
lokalise/cli-2
nektos/tap
solo-io/tap
wix/brew
```

**Comment by vitorgalvao** [comment]
This would be better served with a PR where we could see the changes, rather than an issue where we have to infer them.

> and building rather than downloading prebuilt packages.

That isn’t possible with casks. And since they don’t seem to provide built binaries on Github, we can’t make the change.
