### ISSUE TITLE
Fail install superslicer

### ISSUE THREAD

**Issue by sl1pkn07** [Homebrew/homebrew-cask#96961]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

fail to in stall superslicer

#### Command that failed

```
brew install --cask superslicer --verbose --debug
```

#### Output of command with `--verbose --debug`

```
└───╼  brew install superslicer --cask --verbose --debug
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://github.com/supermerill/SuperSlicer/releases/download/2.2.53.4/SuperSlicer_2.2.53.4_macos_20201111.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.0-102-gbcbf585\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://github.com/supermerill/SuperSlicer/releases/download/2.2.53.4/SuperSlicer_2.2.53.4_macos_20201111.dmg
Already downloaded: /Volumes/Home/sL1ntoch/Library/Caches/Homebrew/downloads/42466abae5b62a9891a752be864ebca89095077c723a3aa0851417ff36a123ee--SuperSlicer_2.2.53.4_macos_20201111.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Volumes/Home/sL1ntoch/Library/Caches/Homebrew/downloads/42466abae5b62a9891a752be864ebca89095077c723a3aa0851417ff36a123ee--SuperSlicer_2.2.53.4_macos_20201111.dmg
/usr/bin/xattr -p com.apple.quarantine /Volumes/Home/sL1ntoch/Library/Caches/Homebrew/downloads/42466abae5b62a9891a752be864ebca89095077c723a3aa0851417ff36a123ee--SuperSlicer_2.2.53.4_macos_20201111.dmg
==> /Volumes/Home/sL1ntoch/Library/Caches/Homebrew/downloads/42466abae5b62a9891a752be864ebca89095077c723a3aa0851417ff36a123ee--SuperSlicer_2.2.53.4_macos_20201111.dmg is quarantined
==> Verifying checksum for cask 'superslicer'.
hdiutil imageinfo -format /Volumes/Home/sL1ntoch/Library/Caches/Homebrew/downloads/42466abae5b62a9891a752be864ebca89095077c723a3aa0851417ff36a123ee--SuperSlicer_2.2.53.4_macos_20201111.dmg
==> Installing Cask superslicer
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Volumes/Home/sL1ntoch/Library/Caches/Homebrew/downloads/42466abae5b62a9891a752be864ebca89095077c723a3aa0851417ff36a123ee--SuperSlicer_2.2.53.4_macos_20201111.dmg
hdiutil attach -plist -nobrowse -readonly -mountrandom /var/folders/xg/1v6_p38956l315rdkt_s1b340000gn/T/d20201226-63408-1l1yfiu /Volumes/Home/sL1ntoch/Library/Caches/Homebrew/downloads/42466abae5b62a9891a752be864ebca89095077c723a3aa0851417ff36a123ee--SuperSlicer_2.2.53.4_macos_20201111.dmg
find . -print0
mkbom -s -i /var/folders/xg/1v6_p38956l315rdkt_s1b340000gn/T/20201226-63408-v3suu0.list -- /var/folders/xg/1v6_p38956l315rdkt_s1b340000gn/T/20201226-63408-1n7xlad.bom
ditto --bom /var/folders/xg/1v6_p38956l315rdkt_s1b340000gn/T/20201226-63408-1n7xlad.bom -- /private/var/folders/xg/1v6_p38956l315rdkt_s1b340000gn/T/d20201226-63408-1l1yfiu/dmg.B2vWkM /var/folders/xg/1v6_p38956l315rdkt_s1b340000gn/T/d20201226-63408-1pb47yl
diskutil eject /private/var/folders/xg/1v6_p38956l315rdkt_s1b340000gn/T/d20201226-63408-1l1yfiu/dmg.B2vWkM
cp -pR /var/folders/xg/1v6_p38956l315rdkt_s1b340000gn/T/d20201226-63408-1pb47yl/SuperSlicer.app/. /usr/local/Caskroom/superslicer/2.2.53.4,20201111/SuperSlicer.app
chmod -Rf +w /var/folders/xg/1v6_p38956l315rdkt_s1b340000gn/T/d20201226-63408-1pb47yl
==> Verifying Gatekeeper status of /Volumes/Home/sL1ntoch/Library/Caches/Homebrew/downloads/42466abae5b62a9891a752be864ebca89095077c723a3aa0851417ff36a123ee--SuperSlicer_2.2.53.4_macos_20201111.dmg
/usr/bin/xattr -p com.apple.quarantine /Volumes/Home/sL1ntoch/Library/Caches/Homebrew/downloads/42466abae5b62a9891a752be864ebca89095077c723a3aa0851417ff36a123ee--SuperSlicer_2.2.53.4_macos_20201111.dmg
==> /Volumes/Home/sL1ntoch/Library/Caches/Homebrew/downloads/42466abae5b62a9891a752be864ebca89095077c723a3aa0851417ff36a123ee--SuperSlicer_2.2.53.4_macos_20201111.dmg is quarantined
==> Propagating quarantine from /Volumes/Home/sL1ntoch/Library/Caches/Homebrew/downloads/42466abae5b62a9891a752be864ebca89095077c723a3aa0851417ff36a123ee--SuperSlicer_2.2.53.4_macos_20201111.dmg to /usr/local/Caskroom/superslicer/2.2.53.4,20201111
/usr/bin/xattr -p com.apple.quarantine /Volumes/Home/sL1ntoch/Library/Caches/Homebrew/downloads/42466abae5b62a9891a752be864ebca89095077c723a3aa0851417ff36a123ee--SuperSlicer_2.2.53.4_macos_20201111.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5fe7b301\;Homebrew\\x20Cask\;8C21A423-7301-42A6-85FE-8C272CAB70CE
==> Creating metadata directory /usr/local/Caskroom/superslicer/.metadata/2.2.53.4,20201111/20201226222422.784.
==> Creating metadata subdirectory /usr/local/Caskroom/superslicer/.metadata/2.2.53.4,20201111/20201226222422.784/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::App:0x00007fe437036a10 @cask=#<Cask::Cask:0x00007fe43924de78 @token="superslicer", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/superslicer.rb>, @tap=#<Tap:0x00007fe439227cc8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fe43924ddd8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/superslicer.rb:1>, @default_config=#<Cask::Config:0x00007fe439245278 @explicit={}, @env={}, @default={:languages=>["es-ES"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Spotlight>, :dictionarydir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Dictionaries>, :fontdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Fonts>, :servicedir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Services>, :input_methoddir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Screen Savers>}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/superslicer>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/superslicer/.metadata>, @config=#<Cask::Config:0x00007fe4370590d8 @explicit={}, @env={}, @default={:languages=>["es-ES"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Spotlight>, :dictionarydir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Dictionaries>, :fontdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Fonts>, :servicedir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Services>, :input_methoddir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Screen Savers>}>, @dsl=#<Cask::DSL:0x00007fe437058e30 @cask=#<Cask::Cask:0x00007fe43924de78 ...>, @token="superslicer", @version="2.2.53.4,20201111", @sha256=#<Checksum:0x00007fe437058b38 @hash_type=:sha256, @hexdigest="04c07dbd71395134cc0d491d4219722aa2b9387d4a28f57b46cc52de672c2cf6">, @url=#<URL:0x00007fe437037dc0 @uri=#<URI::HTTPS https://github.com/supermerill/SuperSlicer/releases/download/2.2.53.4/SuperSlicer_2.2.53.4_macos_20201111.dmg>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}, @from_block=false, @caller_location="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/superslicer.rb:5:in `block in load'">, @appcast=#<Cask::DSL::Appcast:0x00007fe4370377d0 @uri=#<URI::HTTPS https://github.com/supermerill/SuperSlicer/releases.atom>, @parameters={}>, @name=["SuperSlicer"], @desc="Convert 3D models into G-code instructions or PNG layers", @homepage="https://github.com/supermerill/SuperSlicer", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/superslicer/2.2.53.4,20201111>, @language_eval=nil>>, @source_string="superslicer.app", @target_string="", @source=#<Pathname:/usr/local/Caskroom/superslicer/2.2.53.4,20201111/superslicer.app>, @target=#<Pathname:/Applications/superslicer.app>>, #<Cask::Artifact::Zap:0x00007fe4370671d8 @cask=#<Cask::Cask:0x00007fe43924de78 @token="superslicer", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/superslicer.rb>, @tap=#<Tap:0x00007fe439227cc8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fe43924ddd8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/superslicer.rb:1>, @default_config=#<Cask::Config:0x00007fe439245278 @explicit={}, @env={}, @default={:languages=>["es-ES"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Spotlight>, :dictionarydir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Dictionaries>, :fontdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Fonts>, :servicedir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Services>, :input_methoddir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Screen Savers>}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/superslicer>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/superslicer/.metadata>, @config=#<Cask::Config:0x00007fe4370590d8 @explicit={}, @env={}, @default={:languages=>["es-ES"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Spotlight>, :dictionarydir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Dictionaries>, :fontdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Fonts>, :servicedir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Services>, :input_methoddir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Volumes/Home/sL1ntoch/Library/Screen Savers>}>, @dsl=#<Cask::DSL:0x00007fe437058e30 @cask=#<Cask::Cask:0x00007fe43924de78 ...>, @token="superslicer", @version="2.2.53.4,20201111", @sha256=#<Checksum:0x00007fe437058b38 @hash_type=:sha256, @hexdigest="04c07dbd71395134cc0d491d4219722aa2b9387d4a28f57b46cc52de672c2cf6">, @url=#<URL:0x00007fe437037dc0 @uri=#<URI::HTTPS https://github.com/supermerill/SuperSlicer/releases/download/2.2.53.4/SuperSlicer_2.2.53.4_macos_20201111.dmg>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}, @from_block=false, @caller_location="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/superslicer.rb:5:in `block in load'">, @appcast=#<Cask::DSL::Appcast:0x00007fe4370377d0 @uri=#<URI::HTTPS https://github.com/supermerill/SuperSlicer/releases.atom>, @parameters={}>, @name=["SuperSlicer"], @desc="Convert 3D models into G-code instructions or PNG layers", @homepage="https://github.com/supermerill/SuperSlicer", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/superslicer/2.2.53.4,20201111>, @language_eval=nil>>, @directives={:trash=>"~/Library/Application Support/SuperSlicer", :signal=>[]}>}>
==> Installing artifact of class Cask::Artifact::App
==> Purging files for version 2.2.53.4,20201111 of Cask superslicer
Error: It seems the App source '/usr/local/Caskroom/superslicer/2.2.53.4,20201111/superslicer.app' is not there.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:48:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:20:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:228:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:221:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:107:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:79:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:158:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
```

#### Output of `brew doctor --verbose`

```
└───╼  brew doctor --verbose
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Homebrew Version
2.7.0-102-gbcbf585
==> macOS
10.14.6
==> SIP
Disabled
/usr/libexec/java_home --xml --failfast
==> Java
13, 1.8.0_121
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3766 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (175 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1597 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (167 casks)
/usr/bin/xattr
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  libkdcraw
  unrar

Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  lua@5.1
  hunspell
  pangomm@2.42
  atkmm@2.28
  libsigc++@2
```

#### Output of `brew tap`

```
└───╼  brew tap
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
kde-mac/kde
sl1pkn07/sl1
```

**Comment by lbibass** [comment]
do you have your own fork of the cask repository? I just had the same problems you did until I pulled in the most recent changes into mine.

**Comment by sl1pkn07** [comment]
> do you have your own fork of the cask repository? 

nope.

**Comment by vitorgalvao** [comment]
> Error: It seems the App source '/usr/local/Caskroom/superslicer/2.2.53.4,20201111/superslicer.app' is not there.

[Documentation on how to fix it](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md).

**Comment by sl1pkn07** [comment]
ok. is a Case sensitive error

the `SuperSlicer_2.2.53.4_macos_20201111.dmg` contains `SuperSlicer.app`

edit the formula from

`app superslicer.app`

to

`app SuperSlicer.app`

fix the problem

**Comment by vitorgalvao** [comment]
@sl1pkn07 [It’s a simple PR](https://github.com/Homebrew/homebrew-cask/pull/97138).

**Comment by lbibass** [comment]
This seems like a problem limited exclusively to people who have used a case-sensitive partition. 

```Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.```
