### ISSUE TITLE
Cannot install microsoft-edge

### ISSUE THREAD

**Issue by sebnaf** [Homebrew/homebrew-cask#97276]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Cannot install microsoft edge

#### Command that failed

```
⋊> ~ brew install microsoft-edge
```

#### Output of command with `--verbose --debug`

```
⋊> ~ brew install microsoft-edge --verbose --debug                                                                                                                                                 14:42:43
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdge-87.0.664.66.pkg
==> Downloading https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdge-87.0.664.66.pkg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdge-87.0.664.66.pkg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --continue-at - --output /Users/sna/Library/Caches/Homebrew/downloads/e86a4ae7d4fe46ee0c756a7666391e42730134bd7eeb0f24ab7d52b39f35748a--MicrosoftEdge-87.0.664.66.pkg.incomplete https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdge-87.0.664.66.pkg
** Resuming transfer from byte position 2867346
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  173M    0  974k    0     0  3732k      0  0:00:47 --:--:--  0:00:47 3717k
curl: (56) LibreSSL SSL_read: error:06FFF064:digital envelope routines:CRYPTO_internal:bad decrypt, errno 0
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 -V
Error: Download failed on Cask 'microsoft-edge' with message: Download failed: https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdge-87.0.664.66.pkg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:375:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:372:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:24:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:167:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:182:in `primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:325:in `collect_cask_and_formula_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:352:in `cask_and_formula_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:261:in `satisfy_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:96:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:79:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:158:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'

```

#### Output of `brew doctor --verbose`

```
⋊> ~ brew doctor --verbose                                                                                                                                                                         14:43:08
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin20
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20
/usr/local/Homebrew/Library/Homebrew
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Homebrew Version
2.7.1
==> macOS
11.1
==> SIP
Enabled
/usr/libexec/java_home --xml --failfast
==> Java
N/A
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3771 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (175 casks)
/usr/bin/xattr
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'set -g fish_user_paths "/usr/local/sbin" $fish_user_paths' >> ~/.config/fish/config.fish
```

#### Output of `brew tap`

```
⋊> ~ brew tap                                                                                                                                                                                      14:43:31
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by vitorgalvao** [comment]
Can’t reproduce.

> curl: (56) LibreSSL SSL_read: error:06FFF064:digital envelope routines:CRYPTO_internal:bad decrypt, errno 0

That’s an issue with the download part. Try the [`curl` error](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/curl_error.md) instructions, but this was either a temporary problem on their part or something else in yours.
