### ISSUE TITLE
Token seems to require workflow permissions

### ISSUE THREAD

**Issue by tiiiecherle** [Homebrew/homebrew-cask#98145]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Updating cask fails with token workflow error. Inspecting some other issues on other projects it seems the token is missing workflow permissions. My local github token is already updated with workflow permissions.

#### Command that failed

```
CASKNAME=whatsapp
NEW_CASK_VERSION=2.2100.4
brew bump-cask-pr "$CASKNAME" --version="$NEW_CASK_VERSION" --no-browse
==> Downloading https://web.whatsapp.com/desktop/mac/files/release-2.2100.4.zip
Already downloaded: /Users/tom/Library/Caches/Homebrew/downloads/f7d65f82e1db664c6e3db9002e9cc530ca172328d5e3e2ca9d91e9aacf9da809--_nc_ht=scontent.ffra1-1.fna
Warning: Cannot verify integrity of 'f7d65f82e1db664c6e3db9002e9cc530ca172328d5e3e2ca9d91e9aacf9da809--_nc_ht=scontent.ffra1-1.fna'.
No checksum was provided for this resource.
For your reference, the checksum is:
  sha256 "ce3564d09d2c549a2899bbccae2ba7cf70efa0fbb27c216972c93857ad3dbfbc"
==> replace /version\s+["']2\.2049\.10["']/m with "version \"2.2100.4\""
==> replace /sha256\s+["']857ce315fd4127083b6134fb4480fb22e641bee4a0c4d7e8f14590
audit for whatsapp: passed

1 file inspected, no offenses detected
M	Casks/whatsapp.rb
Switched to a new branch 'bump-whatsapp-2.2100.4'
[bump-whatsapp-2.2100.4 ead5c2dbad] Update whatsapp from 2.2049.10 to 2.2100.4
 1 file changed, 2 insertions(+), 2 deletions(-)
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 16 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 457 bytes | 457.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/tiiiecherle/homebrew-cask.git
 ! [remote rejected]       bump-whatsapp-2.2100.4 -> bump-whatsapp-2.2100.4 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/ci.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/tiiiecherle/homebrew-cask.git'
Error: Failure while executing; `git push --set-upstream https://e1474f026c0f3dbd9932cafc5ad1c3a5196cfa0f@github.com/tiiiecherle/homebrew-cask.git bump-whatsapp-2.2100.4:bump-whatsapp-2.2100.4` exited with 1.
```

#### Output of command with `--verbose --debug`

```
CASKNAME=whatsapp
NEW_CASK_VERSION=2.2100.4
brew bump-cask-pr "$CASKNAME" --version="$NEW_CASK_VERSION" --no-browse --verbose --debug
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

git config --replace-all homebrew.devcmdrun true
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.4-17-ge989a0f\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=whatsapp\+repo\%3AHomebrew\%2Fhomebrew-cask\+state\%3Aopen\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --header Authorization:\ token\ ****** --dump-header /private/tmp/github_api_headers20210114-45406-3crjs0
==> Downloading https://web.whatsapp.com/desktop/mac/files/release-2.2100.4.zip
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.4-17-ge989a0f\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://web.whatsapp.com/desktop/mac/files/release-2.2100.4.zip
Already downloaded: /Users/tom/Library/Caches/Homebrew/downloads/f7d65f82e1db664c6e3db9002e9cc530ca172328d5e3e2ca9d91e9aacf9da809--_nc_ht=scontent.ffra1-1.fna
==> Verifying checksum for 'f7d65f82e1db664c6e3db9002e9cc530ca172328d5e3e2ca9d91e9aacf9da809--_nc_ht=scontent.ffra1-1.fna'.
Warning: Cannot verify integrity of 'f7d65f82e1db664c6e3db9002e9cc530ca172328d5e3e2ca9d91e9aacf9da809--_nc_ht=scontent.ffra1-1.fna'.
No checksum was provided for this resource.
For your reference, the checksum is:
  sha256 "ce3564d09d2c549a2899bbccae2ba7cf70efa0fbb27c216972c93857ad3dbfbc"
==> replace /version\s+["']2\.2049\.10["']/m with "version \"2.2100.4\""
==> replace /sha256\s+["']857ce315fd4127083b6134fb4480fb22e641bee4a0c4d7e8f145902b51f82837["']/m with "sha256 \"ce3564d09d2c549a2899bbccae2ba7cf70efa0fbb27c216972c93857ad3dbfbc\""
/usr/local/bin/brew audit --cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/whatsapp.rb
audit for whatsapp: passed
/usr/local/bin/brew style --fix /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/whatsapp.rb

1 file inspected, no offenses detected
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.4-17-ge989a0f\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/repos/Homebrew/homebrew-cask/forks --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --header Authorization:\ token\ ****** --data @/private/tmp/github_api_post20210114-45406-oak5cz --dump-header /private/tmp/github_api_headers20210114-45406-d91lkd
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.4-17-ge989a0f\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/user --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --header Authorization:\ token\ ****** --dump-header /private/tmp/github_api_headers20210114-45406-t94413
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.4-17-ge989a0f\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/repos/tiiiecherle/homebrew-cask --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --header Authorization:\ token\ ****** --dump-header /private/tmp/github_api_headers20210114-45406-mx1gv1
git add /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/whatsapp.rb
git checkout --no-track -b bump-whatsapp-2.2100.4 origin/master
M	Casks/whatsapp.rb
Switched to a new branch 'bump-whatsapp-2.2100.4'
git commit --no-edit --verbose --message=Update whatsapp from 2.2049.10 to 2.2100.4 -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/whatsapp.rb
[bump-whatsapp-2.2100.4 218cf0450a] Update whatsapp from 2.2049.10 to 2.2100.4
 1 file changed, 2 insertions(+), 2 deletions(-)
git push --set-upstream https://e1474f026c0f3dbd9932cafc5ad1c3a5196cfa0f@github.com/tiiiecherle/homebrew-cask.git bump-whatsapp-2.2100.4:bump-whatsapp-2.2100.4
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 16 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 457 bytes | 457.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/tiiiecherle/homebrew-cask.git
 ! [remote rejected]       bump-whatsapp-2.2100.4 -> bump-whatsapp-2.2100.4 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/ci.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/tiiiecherle/homebrew-cask.git'
Error: Failure while executing; `git push --set-upstream https://e1474f026c0f3dbd9932cafc5ad1c3a5196cfa0f@github.com/tiiiecherle/homebrew-cask.git bump-whatsapp-2.2100.4:bump-whatsapp-2.2100.4` exited with 1.
/usr/local/Homebrew/Library/Homebrew/utils.rb:304:in `safe_system'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:729:in `block in create_bump_pr'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:318:in `block in cd'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:318:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:318:in `cd'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:688:in `create_bump_pr'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:187:in `bump_cask_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

#### Output of `brew doctor --verbose`

```
brew doctor --verbose%
tom ~ % brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tapioca-0.4.12/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/spoom-1.0.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.9.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-1.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-ast-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-sorbet-1.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-0.5.6206/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-github-2.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/regexp_parser-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/pry-0.13.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parlour-5.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-0.5.6206/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-3.0.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.20.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/method_source-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.11.1-x86_64-darwin/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/racc-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-4.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2020.1104/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.4.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/commander-4.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/highline-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/colorize-0.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coderay-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/codecov-0.2.15/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.20.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.12.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/byebug-11.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.14.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin20
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20
/usr/local/Homebrew/Library/Homebrew
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Homebrew Version
2.7.4-17-ge989a0f
==> macOS
11.1
==> SIP
Unknown (custom configuration)

configuration:
apple internal: disabled
kext signing: enabled
filesystem protections: disabled
debugging restrictions: disabled
dtrace restrictions: enabled
nvram protections: enabled
basesystem verification: enabled
/usr/libexec/java_home --xml --failfast
==> Java
15
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3791 casks)
/usr/bin/xattr
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/cask) checkout master
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

**Comment by tiiiecherle** [comment]
Worked after regenerating token completely with workflow included. Afterwards I added the new token to macOS keychain and it worked.
