### ISSUE TITLE
many brew actions (include brew uninstall) fail if now-invalid cask is installed

### ISSUE THREAD

**Issue by kevinushey** [Homebrew/homebrew-cask#99012]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I had a previously-installed cask for `filezilla` that I'm no longer able to uninstall.

#### Command that failed

```
kevin@cdrv:~
$ brew uninstall filezilla
Error: Cask 'filezilla' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :mavericks
kevin@cdrv:~
$ brew uninstall --force filezilla
Error: Cask 'filezilla' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :mavericks
```

#### Output of command with `--verbose --debug`

```
kevin@cdrv:~
$ brew uninstall --force filezilla --verbose --debug
Error: Cask 'filezilla' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :mavericks
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:232:in `rescue in depends_on'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:229:in `depends_on'
/usr/local/Caskroom/filezilla/.metadata/3.30.0/20180115032547.357/Casks/filezilla.rb:12:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:61:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:61:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:48:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:87:in `cask'
/usr/local/Caskroom/filezilla/.metadata/3.30.0/20180115032547.357/Casks/filezilla.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `load'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:302:in `warn_if_cask_conflicts'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:99:in `load_formula_or_cask'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:52:in `block in to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:51:in `each'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:51:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:51:in `to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:213:in `to_kegs_to_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:48:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

#### Output of `brew doctor --verbose`

```
kevin@cdrv:~
$ brew doctor --verbose
Error: Cask 'filezilla' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :mavericks
```

#### Output of `brew tap`

```
kevin@cdrv:~
$ brew tap
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
neovim/neovim
railwaycat/emacsmacport
```

**Comment by kevinushey** [comment]
Manually deleting the folder with:

```
rm -rf /usr/local/Caskroom/filezilla
```

got me out of this state. (alongside multiple other casks which also produced similar errors)

**Comment by kevinushey** [comment]
Sorry; I see the issue is referenced here: https://github.com/Homebrew/homebrew-cask/issues/58046
