### ISSUE TITLE
Error: Unknown command: cask

### ISSUE THREAD

**Issue by mbabauer** [Homebrew/homebrew-cask#99522]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Running the `brew cask [anything]` command gives the errror:
```
Error: Unknown command: cask
```

Where `[anything]` is any cask command (cleanup, install, etc).  This seems to have started after I got an error from `brew update` about the homebrew-cask being "shallow", but I can't be certain as I don't install things using cask ofter.  I did try it on a separate Mac, which seemed to be working prior, and it broke cask in the same way after running the recommended command:
```
>> git -C <path_to_homebrew-cask_repo> fetch --unshallow
```

#### Command that failed

```
brew cask [anything]
```

#### Output of command with `--verbose --debug`

```
>> brew cask --verbose --debug
Error: Unknown command: cask
Error: Kernel.exit
/Users/XXX/.homebrew/Library/Homebrew/utils.rb:176:in `exit'
/Users/XXX/.homebrew/Library/Homebrew/utils.rb:176:in `odie'
/Users/XXX/.homebrew/Library/Homebrew/brew.rb:136:in `<main>'
```

#### Output of `brew doctor --verbose`

```
>> brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.2.0/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.1/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.9.2/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.7/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrick-1.7.0/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.1/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.4/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.7/lib
~/.homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby
~/.homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0
~/.homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/x86_64-darwin14
~/.homebrew/Library/Homebrew
/usr/bin/xattr
/usr/bin/swift /Users/msbauer/.homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Homebrew Version
3.0.0-37-g3eb4772
==> macOS
10.15.7
==> SIP
Enabled
java -version
==> Java
N/A
==> Homebrew Cask Staging Location
~/.homebrew/Caskroom
==> Homebrew Cask Taps:
/Users/XXX/.homebrew/Library/Taps/homebrew/homebrew-cask (3809 casks)
/Users/XXX/.homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1699 casks)
/usr/bin/xattr
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  elasticsearch

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

#### Output of `brew tap`

```
>> brew tap
buo/cask-upgrade
homebrew/cask
homebrew/cask-fonts
homebrew/core
homebrew/services
mongodb/brew
sambadevi/powerlevel9k
```

**Comment by vitorgalvao** [comment]
`brew cask` has been deprecated for a while; you should’ve gotten plenty of warnings. Just do `brew` from now on, or `brew --cask` when disambiguation is necessary.
